### ISSUE TITLE
[BUG] Paperless-ngx won't start:  invalid attribute number

### ISSUE THREAD

**Issue by jeff47** [paperless-ngx/paperless-ngx#1051]
### Description

I've had paperless-ngx working fine, but suddenly it won't start.  The log contains an error about an invalid attribute number (see below).  I haven't made any changes to the configuration etc, so I don't know what caused the error to appear.

### Steps to reproduce

Start paperless-ngx in docker.

### Webserver logs

```bash
2022-05-31T13:26:09.897943668Z Paperless-ngx docker container starting...
2022-05-31T13:26:09.901249736Z Creating directory /tmp/paperless
2022-05-31T13:26:09.902476068Z Adjusting permissions of paperless files. This may take a while.
2022-05-31T13:26:09.980430140Z Waiting for PostgreSQL to start...
2022-05-31T13:26:10.254769261Z Waiting for Redis: redis://broker:6379
2022-05-31T13:26:10.257330482Z Connected to Redis broker: redis://broker:6379
2022-05-31T13:26:10.280991745Z Apply database migrations...
2022-05-31T13:26:11.106022815Z Traceback (most recent call last):
2022-05-31T13:26:11.106037382Z   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
2022-05-31T13:26:11.106146339Z     return self.cursor.execute(sql, params)
2022-05-31T13:26:11.106156163Z psycopg2.errors.InternalError_: invalid attribute number 17 for documents_document
2022-05-31T13:26:11.106159377Z LINE 1: ..."documents_document"."archive_serial_number" FROM "documents...
2022-05-31T13:26:11.106162429Z                                                              ^
2022-05-31T13:26:11.106165384Z 
2022-05-31T13:26:11.106167987Z 
2022-05-31T13:26:11.106170557Z The above exception was the direct cause of the following exception:
2022-05-31T13:26:11.106173264Z 
2022-05-31T13:26:11.106175812Z Traceback (most recent call last):
2022-05-31T13:26:11.106178457Z   File "/usr/src/paperless/src/manage.py", line 11, in <module>
2022-05-31T13:26:11.106209866Z     execute_from_command_line(sys.argv)
2022-05-31T13:26:11.106219696Z   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
2022-05-31T13:26:11.106356154Z     utility.execute()
2022-05-31T13:26:11.106361418Z   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
2022-05-31T13:26:11.106472166Z     self.fetch_command(subcommand).run_from_argv(self.argv)
2022-05-31T13:26:11.106481768Z   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 414, in run_from_argv
2022-05-31T13:26:11.106593232Z     self.execute(*args, **cmd_options)
2022-05-31T13:26:11.106597977Z   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 460, in execute
2022-05-31T13:26:11.106692381Z     output = self.handle(*args, **options)
2022-05-31T13:26:11.106701779Z   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 98, in wrapped
2022-05-31T13:26:11.106760875Z     res = handle_func(*args, **kwargs)
2022-05-31T13:26:11.106765640Z   File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 91, in handle
2022-05-31T13:26:11.106831660Z     self.check(databases=[database])
2022-05-31T13:26:11.106840042Z   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 487, in check
2022-05-31T13:26:11.106961914Z     all_issues = checks.run_checks(
2022-05-31T13:26:11.106966695Z   File "/usr/local/lib/python3.9/site-packages/django/core/checks/registry.py", line 88, in run_checks
2022-05-31T13:26:11.107040511Z     new_errors = check(app_configs=app_configs, databases=databases)
2022-05-31T13:26:11.107049077Z   File "/usr/src/paperless/src/documents/checks.py", line 19, in changed_password_check
2022-05-31T13:26:11.107106272Z     encrypted_doc = Document.objects.filter(
2022-05-31T13:26:11.107123441Z   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 753, in first
2022-05-31T13:26:11.107269340Z     for obj in (self if self.ordered else self.order_by("pk"))[:1]:
2022-05-31T13:26:11.107277628Z   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 320, in __iter__
2022-05-31T13:26:11.107374398Z     self._fetch_all()
2022-05-31T13:26:11.107378365Z   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1507, in _fetch_all
2022-05-31T13:26:11.107630511Z     self._result_cache = list(self._iterable_class(self))
2022-05-31T13:26:11.107638159Z   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 57, in __iter__
2022-05-31T13:26:11.107670826Z     results = compiler.execute_sql(
2022-05-31T13:26:11.107674359Z   File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1361, in execute_sql
2022-05-31T13:26:11.107959738Z     cursor.execute(sql, params)
2022-05-31T13:26:11.107968348Z   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
2022-05-31T13:26:11.108030304Z     return self._execute_with_wrappers(
2022-05-31T13:26:11.108035040Z   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
2022-05-31T13:26:11.108078548Z     return executor(sql, params, many, context)
2022-05-31T13:26:11.108086271Z   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
2022-05-31T13:26:11.108148811Z     return self.cursor.execute(sql, params)
2022-05-31T13:26:11.108153205Z   File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
2022-05-31T13:26:11.108202751Z     raise dj_exc_value.with_traceback(traceback) from exc_value
2022-05-31T13:26:11.108210196Z   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
2022-05-31T13:26:11.108276067Z     return self.cursor.execute(sql, params)
2022-05-31T13:26:11.108282920Z django.db.utils.InternalError: invalid attribute number 17 for documents_document
2022-05-31T13:26:11.108286810Z LINE 1: ..."documents_document"."archive_serial_number" FROM "documents...
2022-05-31T13:26:11.108297539Z                                                              ^
2022-05-31T13:26:11.108301401Z 
2022-05-31T13:26:11.886943521Z Paperless-ngx docker container starting...
2022-05-31T13:26:11.891520250Z Creating directory /tmp/paperless
2022-05-31T13:26:11.893125652Z Adjusting permissions of paperless files. This may take a while.
2022-05-31T13:26:11.968327651Z Waiting for PostgreSQL to start...
2022-05-31T13:26:12.239116304Z Waiting for Redis: redis://broker:6379
2022-05-31T13:26:12.241648682Z Connected to Redis broker: redis://broker:6379
2022-05-31T13:26:12.266265772Z Apply database migrations...
2022-05-31T13:26:13.129341129Z Traceback (most recent call last):
2022-05-31T13:26:13.129364554Z   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
2022-05-31T13:26:13.129452078Z     return self.cursor.execute(sql, params)
2022-05-31T13:26:13.129467971Z psycopg2.errors.InternalError_: invalid attribute number 17 for documents_document
2022-05-31T13:26:13.129474755Z LINE 1: ..."documents_document"."archive_serial_number" FROM "documents...
2022-05-31T13:26:13.129480225Z                                                              ^
2022-05-31T13:26:13.129486314Z 
2022-05-31T13:26:13.129490956Z 
2022-05-31T13:26:13.129495347Z The above exception was the direct cause of the following exception:
2022-05-31T13:26:13.129500537Z 
2022-05-31T13:26:13.129504713Z Traceback (most recent call last):
2022-05-31T13:26:13.129509218Z   File "/usr/src/paperless/src/manage.py", line 11, in <module>
2022-05-31T13:26:13.129633718Z     execute_from_command_line(sys.argv)
2022-05-31T13:26:13.129645643Z   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
2022-05-31T13:26:13.129704374Z     utility.execute()
2022-05-31T13:26:13.129711967Z   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
2022-05-31T13:26:13.129852137Z     self.fetch_command(subcommand).run_from_argv(self.argv)
2022-05-31T13:26:13.129867324Z   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 414, in run_from_argv
2022-05-31T13:26:13.129974726Z     self.execute(*args, **cmd_options)
2022-05-31T13:26:13.129985639Z   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 460, in execute
2022-05-31T13:26:13.130109357Z     output = self.handle(*args, **options)
2022-05-31T13:26:13.130116968Z   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 98, in wrapped
2022-05-31T13:26:13.130171106Z     res = handle_func(*args, **kwargs)
2022-05-31T13:26:13.130183752Z   File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 91, in handle
2022-05-31T13:26:13.130827236Z     self.check(databases=[database])
2022-05-31T13:26:13.130836992Z   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 487, in check
2022-05-31T13:26:13.130950158Z     all_issues = checks.run_checks(
2022-05-31T13:26:13.130964823Z   File "/usr/local/lib/python3.9/site-packages/django/core/checks/registry.py", line 88, in run_checks
2022-05-31T13:26:13.131017437Z     new_errors = check(app_configs=app_configs, databases=databases)
2022-05-31T13:26:13.131025922Z   File "/usr/src/paperless/src/documents/checks.py", line 19, in changed_password_check
2022-05-31T13:26:13.131132091Z     encrypted_doc = Document.objects.filter(
2022-05-31T13:26:13.131142825Z   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 753, in first
2022-05-31T13:26:13.131282523Z     for obj in (self if self.ordered else self.order_by("pk"))[:1]:
2022-05-31T13:26:13.131292094Z   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 320, in __iter__
2022-05-31T13:26:13.131386644Z     self._fetch_all()
2022-05-31T13:26:13.131394508Z   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1507, in _fetch_all
2022-05-31T13:26:13.131658366Z     self._result_cache = list(self._iterable_class(self))
2022-05-31T13:26:13.131674093Z   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 57, in __iter__
2022-05-31T13:26:13.131718016Z     results = compiler.execute_sql(
2022-05-31T13:26:13.131737959Z   File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1361, in execute_sql
2022-05-31T13:26:13.132009135Z     cursor.execute(sql, params)
2022-05-31T13:26:13.132016994Z   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
2022-05-31T13:26:13.132065110Z     return self._execute_with_wrappers(
2022-05-31T13:26:13.132073715Z   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
2022-05-31T13:26:13.132124831Z     return executor(sql, params, many, context)
2022-05-31T13:26:13.132133545Z   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
2022-05-31T13:26:13.132172086Z     return self.cursor.execute(sql, params)
2022-05-31T13:26:13.132179171Z   File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
2022-05-31T13:26:13.132247676Z     raise dj_exc_value.with_traceback(traceback) from exc_value
2022-05-31T13:26:13.132264188Z   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
2022-05-31T13:26:13.132311886Z     return self.cursor.execute(sql, params)
2022-05-31T13:26:13.132320814Z django.db.utils.InternalError: invalid attribute number 17 for documents_document
2022-05-31T13:26:13.132329653Z LINE 1: ..."documents_document"."archive_serial_number" FROM "documents...
2022-05-31T13:26:13.132333211Z                                                              ^
2022-05-31T13:26:13.132336271Z
```

### Paperless-ngx version

1.7.1

### Host OS

Ubuntu 20.04

### Installation method

Docker

**Comment by stumpylog** [comment]
I'm using basic sqlite, so I'm not really sure how best to do anything with postgres.  Options I can think of (which require having a recent export or working backup)

If you have a pretty recent export, you could simply clear out the Docker volume mounted for postgres and let paperless re-create all the tables, then import your files, tags, etc.

Or there might be a `pg_xyz` command to drop all the tables so they can be re-created.

Maybe if you can see the exact query or row from the database logs, dropping that row would be enough to recover to a working state, enough to generate an export.
