### ISSUE TITLE
[BUG] Concise description of the issue

### ISSUE THREAD

**Issue by Phenitei** [paperless-ngx/paperless-ngx#1055]
### Description

When using the grid view in any of the pages that allow it, instead of showing thumbnails, the well-known browser "broken image" appears instead of the thumbnail. The thumbnails are correctly generated (as in, they exist in the filesystem and are valid images, no error is produced when consuming a document, and the permissions are exactly the same as those for the documents).

### Steps to reproduce

1. Go to the "Documents" page
2. Set the document list to grid view or "large list" view
3. Observe broken thumbnails

### Webserver logs

```bash
May 31 17:26:40 stormbringer gunicorn[647]: [2022-05-31 15:26:40,762] [ERROR] [django.request] Internal Server Error: /api/documents/1/thumb/
May 31 17:26:40 stormbringer gunicorn[647]: Traceback (most recent call last):
May 31 17:26:40 stormbringer gunicorn[647]:   File "/usr/lib/python3.10/site-packages/asgiref/sync.py", line 463, in thread_handler
May 31 17:26:40 stormbringer gunicorn[647]:     raise exc_info[1]
May 31 17:26:40 stormbringer gunicorn[647]:   File "/usr/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner
May 31 17:26:40 stormbringer gunicorn[647]:     response = await get_response(request)
May 31 17:26:40 stormbringer gunicorn[647]:   File "/usr/lib/python3.10/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
May 31 17:26:40 stormbringer gunicorn[647]:     response = await wrapped_callback(
May 31 17:26:40 stormbringer gunicorn[647]:   File "/usr/lib/python3.10/site-packages/asgiref/sync.py", line 426, in __call__
May 31 17:26:40 stormbringer gunicorn[647]:     ret = await asyncio.wait_for(future, timeout=None)
May 31 17:26:40 stormbringer gunicorn[647]:   File "/usr/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
May 31 17:26:40 stormbringer gunicorn[647]:     return await fut
May 31 17:26:40 stormbringer gunicorn[647]:   File "/usr/lib/python3.10/site-packages/asgiref/current_thread_executor.py", line 22, in run
May 31 17:26:40 stormbringer gunicorn[647]:     result = self.fn(*self.args, **self.kwargs)
May 31 17:26:40 stormbringer gunicorn[647]:   File "/usr/lib/python3.10/site-packages/asgiref/sync.py", line 467, in thread_handler
May 31 17:26:40 stormbringer gunicorn[647]:     return func(*args, **kwargs)
May 31 17:26:40 stormbringer gunicorn[647]:   File "/usr/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
May 31 17:26:40 stormbringer gunicorn[647]:     return view_func(*args, **kwargs)
May 31 17:26:40 stormbringer gunicorn[647]:   File "/usr/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
May 31 17:26:40 stormbringer gunicorn[647]:     return self.dispatch(request, *args, **kwargs)
May 31 17:26:40 stormbringer gunicorn[647]:   File "/usr/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
May 31 17:26:40 stormbringer gunicorn[647]:     response = self.handle_exception(exc)
May 31 17:26:40 stormbringer gunicorn[647]:   File "/usr/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
May 31 17:26:40 stormbringer gunicorn[647]:     self.raise_uncaught_exception(exc)
May 31 17:26:40 stormbringer gunicorn[647]:   File "/usr/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
May 31 17:26:40 stormbringer gunicorn[647]:     raise exc
May 31 17:26:40 stormbringer gunicorn[647]:   File "/usr/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
May 31 17:26:40 stormbringer gunicorn[647]:     response = handler(request, *args, **kwargs)
May 31 17:26:40 stormbringer gunicorn[647]:   File "/usr/lib/python3.10/site-packages/django/views/decorators/cache.py", line 35, in _cache_controlled
May 31 17:26:40 stormbringer gunicorn[647]:     raise TypeError(
May 31 17:26:40 stormbringer gunicorn[647]: TypeError: cache_control didn't receive an HttpRequest. If you are decorating a classmethod, be sure to use @method_decorator.
```

### Paperless-ngx version

1.6.0

### Host OS

Archlinux (amd64)

### Installation method

Bare metal

### Browser

Qutebrowser, Firefox

### Configuration changes

PAPERLESS_FILENAME_FORMAT={created_year}/{correspondent}/{title}

### Other

Thank you for your work! I'll happily provide any additional needed information :)

**Comment by stumpylog** [comment]
99.9% sure you are using Django 4 with paperless 1.6.0, which didn't support that version.  You'll need to upgrade paperless or downgrade django.
