### ISSUE TITLE
[BUG] Duplicated API calls from frontend on text filtering

### ISSUE THREAD

**Issue by r2ixuz** [paperless-ngx/paperless-ngx#1131]
I have now over 400 documents in my paperless installation. Nearly 100 documents of them are fairly large (200 pages color).

Paperless-ngx V1.7.1 with postgres

When typing ~~slowly~~ at normal speed (not Superman fast...) some long search keyword into the "title and content" field at "documents" it seems that there is for every letter a new SELECT statement transferred to the postgres instance. This leads to a "flickering" effect of matching thumbnails/documents. It shows the new result for half a second, jumps back to the origin view, show another new thumbnail preview, jumps back to the origin view and so on. It takes couple of seconds when finally the final result view for the actual search keyword is found and "flickering" ends.

#############
It already does have a debounce, thats not really the same issue.

_Originally posted by @shamoon in https://github.com/paperless-ngx/paperless-ngx/discussions/288#discussioncomment-2354915_

#############

**Comment by shamoon** [comment]
So I cant exactly reproduce what youre describing, it definitely is not pinging the API on every letter but I do think theres a duplication happening which might look like that (see videos in the linked PR). If you are able to test #1133 perhaps you can let us know if that fixes this for you.

**Comment by r2ixuz** [comment]
Thank you for the very fast answer! :-)

I tested it again at 1.7.1 to see what happens in developer tools. I typed in the keyword "linux bash" where after the little pause between "linux" and "bash" it started immediately to search with sending 5! same requests:

`/api/documents/?page=1&page_size=50&ordering=-created&title_content=linux`

and after "bash" it does the same again 5 times for:

`/api/documents/?page=1&page_size=50&ordering=-created&title_content=linux%20bash`

crazy! :D

Ok now I would like to test your commit. I guess I need to exchange my current docker tag "1.7" to "feature-prevent-text-dupe-api-calls" ?

Is it possible to switch back after testing to the old tag "1.7" ?

As this is a production system, I am very cautious (despite my backup).

**Comment by r2ixuz** [comment]
Your fix works great, only one request is made now. No more flickering in the preview! Thank you. (Search starts after the 3rd letter is entered as expected, this is for 1.7.1 and dev build for me. So no problem with that.)

But still I would say the debounce timer for a key press is too short. How many ms are now set?

Some other observations with this dev build: The conversion of thumbnails to webp was smooth and fast (414 images in nearly 6 seconds (on a 6 core Intel i5 with only one paperless worker and SATA SSDs).

Some error message I got with this build:

```
10:47:15 [Q] INFO recycled worker Process-1:1
10:47:15 [Q] INFO Process-1:6 ready for work at 495
[2022-06-15 10:48:45 +0200] [470] [CRITICAL] WORKER TIMEOUT (pid:473)
[2022-06-15 10:48:45 +0200] [470] [WARNING] Worker with pid 473 was terminated due to signal 6
10:51:40 [Q] INFO Enqueued 1
```
```
[2022-06-15 10:51:41,027] [ERROR] [paperless.classifier] Unrecoverable error while loading document classification model, deleting model file.
Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/classifier.py", line 40, in load_classifier
    classifier.load()
  File "/usr/src/paperless/src/documents/classifier.py", line 82, in load
    raise IncompatibleClassifierVersionError(
documents.classifier.IncompatibleClassifierVersionError: Cannot load classifier, incompatible versions.
```
Postgres:

```
2022-06-15 08:46:36.585 UTC [34] ERROR:  column documents_document.storage_path_id does not exist at character 76
2022-06-15 08:46:36.585 UTC [34] STATEMENT:  SELECT "documents_document"."id", "documents_document"."correspondent_id", "documents_document"."storage_path_id", "documents_document"."title", "documents_document"."document_type_id", "documents_document"."content", "documents_document"."mime_type", "documents_document"."checksum", "documents_document"."archive_checksum", "documents_document"."created", "documents_document"."modified", "documents_document"."storage_type", "documents_document"."added", "documents_document"."filename", "documents_document"."archive_filename", "documents_document"."archive_serial_number" FROM "documents_document" WHERE "documents_document"."storage_type" = 'gpg' ORDER BY "documents_document"."created" DESC LIMIT 1
```

**Comment by shamoon** [comment]
Ohm and debounce is 400ms IIRC, I think thats around where a lot of others are

**Comment by shamoon** [comment]
Ok thanks for follow up, yes I think it just needs to run migrations, and I confirmed the other issue is going to be addressed (it’s also not a problem btw). 

Next release will be beta tested too (I think)!

**Comment by shamoon** [comment]
closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/f66e589312282bdf9310e81406a60c13576db909
