### ISSUE TITLE
[BUG] Import fails for TIFF files without explicit DPI

### ISSUE THREAD

**Issue by HeNine** [paperless-ngx/paperless-ngx#1164]
### Description

If a TIFF image has no Resolution (DPI) specified (as reported by ImageMagick's `identify`), Pillow assumes DPI is 1x1. When this round-trips through PDF, it crashes GhostScript (see log, -r1x1 is the fault; bigger numbers work) and OCR fails.

I'm working on connecting my Brother MFC and the scan TIFFs it produces have no explicitly set DPI, so strictly speaking it's a bug in the Brother network scanner Linux drivers, but it's fixable in software if the DPI is corrected:

`convert -units PixelsPerInch brscan_2022-06-28-09-53-59.tif -density 100 brscan_2022-06-28-09-53-59-2.tif`

Perhaps a way of forcing the OCR DPI setting could be added to the configuration?

Example of offending file: [brscan_2022-06-28-09-53-59.zip](https://github.com/paperless-ngx/paperless-ngx/files/9000756/brscan_2022-06-28-09-53-59.zip)

### Steps to reproduce

1. (Optional) Scan using Brother network scan drivers to produce a TIFF
2. Add TIFF to the `consume` directory

### Webserver logs

```bash
webserver_1    | 13:14:31 [Q] ERROR Failed [brscan_2022-06-28-09-53-59.tif] - brscan_2022-06-28-09-53-59.tif: Error while consuming document brscan_2022-06-28-09-53-59.tif: SubprocessOutputError: Ghostscript rasterizing failed : Traceback (most recent call last):
webserver_1    |   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_exec/ghostscript.py", line 126, in rasterize_pdf
webserver_1    |     p = run(args_gs, stdout=PIPE, stderr=PIPE, check=True)
webserver_1    |   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/subprocess/__init__.py", line 53, in run
webserver_1    |     proc = subprocess_run(args, env=env, **kwargs)
webserver_1    |   File "/usr/local/lib/python3.9/subprocess.py", line 528, in run
webserver_1    |     raise CalledProcessError(retcode, process.args,
webserver_1    | subprocess.CalledProcessError: Command '['gs', '-dQUIET', '-dSAFER', '-dBATCH', '-dNOPAUSE', '-dInterpolateControl=-1', '-sDEVICE=jpeggray', '-dFirstPage=1', '-dLastPage=1', '-r1.000000x1.000000', '-o', '-', '-sstdout=%stderr', '-dAutoRotatePages=/None', '-f', '/tmp/ocrmypdf.io.npxuiuch/origin.pdf']' returned non-zero exit status 255.
webserver_1    |
webserver_1    | During handling of the above exception, another exception occurred:
webserver_1    |
webserver_1    | Traceback (most recent call last):
webserver_1    |   File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 261, in parse
webserver_1    |     ocrmypdf.ocr(**args)
webserver_1    |   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/api.py", line 337, in ocr
webserver_1    |     return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)
webserver_1    |   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 385, in run_pipeline
webserver_1    |     exec_concurrent(context, executor)
webserver_1    |   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 274, in exec_concurrent
webserver_1    |     executor(
webserver_1    |   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_concurrent.py", line 82, in __call__
webserver_1    |     self._execute(
webserver_1    |   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/builtin_plugins/concurrency.py", line 135, in _execute
webserver_1    |     result = future.result()
webserver_1    |   File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result
webserver_1    |     return self.__get_result()
webserver_1    |   File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
webserver_1    |     raise self._exception
webserver_1    |   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
webserver_1    |     result = self.fn(*self.args, **self.kwargs)
webserver_1    |   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 187, in exec_page_sync
webserver_1    |     rasterize_preview_out = rasterize_preview(page_context.origin, page_context)
webserver_1    |   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 344, in rasterize_preview
webserver_1    |     page_context.plugin_manager.hook.rasterize_pdf_page(
webserver_1    |   File "/usr/local/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
webserver_1    |     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
webserver_1    |   File "/usr/local/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
webserver_1    |     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
webserver_1    |   File "/usr/local/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
webserver_1    |     return outcome.get_result()
webserver_1    |   File "/usr/local/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
webserver_1    |     raise ex[1].with_traceback(ex[2])
webserver_1    |   File "/usr/local/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
webserver_1    |     res = hook_impl.function(*args)
webserver_1    |   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/builtin_plugins/ghostscript.py", line 68, in rasterize_pdf_page
webserver_1    |     ghostscript.rasterize_pdf(
webserver_1    |   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_exec/ghostscript.py", line 129, in rasterize_pdf
webserver_1    |     raise SubprocessOutputError('Ghostscript rasterizing failed')
webserver_1    | ocrmypdf.exceptions.SubprocessOutputError: Ghostscript rasterizing failed
webserver_1    |
webserver_1    | During handling of the above exception, another exception occurred:
webserver_1    |
webserver_1    | Traceback (most recent call last):
webserver_1    |   File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 275, in main_wrap
webserver_1    |     raise exc_info[1]
webserver_1    |   File "/usr/src/paperless/src/documents/consumer.py", line 261, in try_consume_file
webserver_1    |     document_parser.parse(self.path, mime_type, self.filename)
webserver_1    |   File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 314, in parse
webserver_1    |     raise ParseError(f"{e.__class__.__name__}: {str(e)}")
webserver_1    | documents.parsers.ParseError: SubprocessOutputError: Ghostscript rasterizing failed
webserver_1    |
webserver_1    | During handling of the above exception, another exception occurred:
webserver_1    |
webserver_1    | Traceback (most recent call last):
webserver_1    |   File "/usr/local/lib/python3.9/site-packages/django_q/cluster.py", line 432, in worker
webserver_1    |     res = f(*task["args"], **task["kwargs"])
webserver_1    |   File "/usr/src/paperless/src/documents/tasks.py", line 298, in consume_file
webserver_1    |     document = Consumer().try_consume_file(
webserver_1    |   File "/usr/src/paperless/src/documents/consumer.py", line 280, in try_consume_file
webserver_1    |     self._fail(
webserver_1    |   File "/usr/src/paperless/src/documents/consumer.py", line 81, in _fail
webserver_1    |     raise ConsumerError(f"{self.filename}: {log_message or message}")
webserver_1    | documents.consumer.ConsumerError: brscan_2022-06-28-09-53-59.tif: Error while consuming document brscan_2022-06-28-09-53-59.tif: SubprocessOutputError: Ghostscript rasterizing failed
```

### Paperless-ngx version

1.7.1

### Host OS

Ubuntu 20.04

### Installation method

Docker

**Comment by stumpylog** [comment]
Is it possible to set the DPI of the original file? Perhaps in a pre consume script?

**Comment by HeNine** [comment]
Something like

```bash
#!/bin/bash

if ! identify -verbose ${1} | grep -q Resolution; then
    mogrify -units PixelsPerInch -density 100 brscan_2022-06-28-09-53-59-2.tif
fi
```

should work as a workaround, but I moved the `mogrify` line into the scanning scripts because I can also pull the actual scanning resolution into `mogrify` there.

**Comment by stumpylog** [comment]
Given that it can be fixed by either a scan script or a pre-consume script, and is not a big in paperless, I'm feeling inclined to not add another setting and custom processing for this edge case.

**Comment by HeNine** [comment]
I think the bug is upstream in either Pillow, for reporting a DPI where there is none specified ([https://github.com/python-pillow/Pillow/blob/main/src/PIL/TiffImagePlugin.py#L1396-L1397](https://github.com/python-pillow/Pillow/blob/main/src/PIL/TiffImagePlugin.py#L1396-L1397)), or somewhere in the OCRmyPDF-GhostScript interaction where the DPI of 1 produces a tiny JPEG (I suspect GS is doing DPI conversion wrong or counterintuitively, but the code and documentation are inscrutable).

Since it seems to be a rare interaction between one model of scanner in a specific use case, and a chain of libraries, adding a whole setting might be overkill. Hopefully Google indexes this issue for anyone who needs a workaround.

**Comment by lasharor** [comment]
Sorry to post a comment here again; How do I exactly add this to a post consumer script? I made a new file (script.sh) and added the code mentioned by Henine, after configuration via docker and giving the script executable premissions the same error still happens when I upload the test file.
