### ISSUE TITLE
[BUG] Upload fails with documents.parsers.ParseError: TypeError: shutdown() got an unexpected keyword argument 'cancel_futures'

### ISSUE THREAD

**Issue by jokob-sk** [paperless-ngx/paperless-ngx#1206]
### Description

The upload crashes on certain images (maybe of a certain size?)

I assume this issue is related to an upgrade of Python to 3.8. A similar issue was reported on this project here: https://github.com/DiscordTime/ggdrive/issues/56

Logged an issue here as well (probably can be mitigated by (AFAIK) UPGRADING the Python version to 3.9+?): https://github.com/linuxserver/docker-paperless-ngx/issues/30

### Steps to reproduce

1. Capture picture (decent size, e.g. full A4 of text, approx 700KB) in the Android APP 
2. Crop
3. Upload
4. Observe the Logs on the server

### Webserver logs

```bash
[2022-07-08 06:29:09,422] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-xlzgcu_k

[2022-07-08 06:29:09,454] [ERROR] [paperless.consumer] Error while consuming document crop_5547.jpeg: TypeError: shutdown() got an unexpected keyword argument 'cancel_futures'

Traceback (most recent call last):

  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/_exec/tesseract.py", line 226, in get_deskew

    p = run(args_tesseract, stdout=PIPE, stderr=STDOUT, timeout=timeout, check=True)

  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/subprocess/__init__.py", line 53, in run

    proc = subprocess_run(args, env=env, **kwargs)

  File "/usr/lib/python3.8/subprocess.py", line 516, in run

    raise CalledProcessError(retcode, process.args,

subprocess.CalledProcessError: Command '['tesseract', '-l', 'eng', '--psm', '2', '/tmp/ocrmypdf.io._d8p80vg/000001_rasterize.png', 'stdout']' died with <Signals.SIGKILL: 9>.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/builtin_plugins/concurrency.py", line 135, in _execute

    result = future.result()

  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result

    return self.__get_result()

  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result

    raise self._exception

  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run

    result = self.fn(*self.args, **self.kwargs)

  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/_sync.py", line 192, in exec_page_sync

    ocr_image, preprocess_out = make_intermediate_images(

  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/_sync.py", line 135, in make_intermediate_images

    preprocess_out = preprocess(

  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/_sync.py", line 106, in preprocess

    image = preprocess_deskew(image, page_context)

  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/_pipeline.py", line 488, in preprocess_deskew

    deskew_angle_degrees = ocr_engine.get_deskew(input_file, page_context.options)

  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/builtin_plugins/tesseract_ocr.py", line 167, in get_deskew

    return tesseract.get_deskew(

  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/_exec/tesseract.py", line 237, in get_deskew

    raise SubprocessOutputError() from e

ocrmypdf.exceptions.SubprocessOutputError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/app/paperless/src/paperless_tesseract/parsers.py", line 261, in parse

    ocrmypdf.ocr(**args)

  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/api.py", line 337, in ocr

    return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)

  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/_sync.py", line 385, in run_pipeline

    exec_concurrent(context, executor)

  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/_sync.py", line 274, in exec_concurrent

    executor(

  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/_concurrent.py", line 82, in __call__

    self._execute(

  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/builtin_plugins/concurrency.py", line 148, in _execute

    executor.shutdown(wait=False, cancel_futures=True)

TypeError: shutdown() got an unexpected keyword argument 'cancel_futures'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/app/paperless/src/documents/consumer.py", line 261, in try_consume_file

    document_parser.parse(self.path, mime_type, self.filename)

  File "/app/paperless/src/paperless_tesseract/parsers.py", line 314, in parse

    raise ParseError(f"{e.__class__.__name__}: {str(e)}")

documents.parsers.ParseError: TypeError: shutdown() got an unexpected keyword argument 'cancel_futures'
```

### Paperless-ngx version

1.7.1

### Host OS

Docker -  linux x86_64 - Synology

### Installation method

Docker - linuxserver.io image

### Browser

Firefox

### Configuration changes

```yaml  version: "3" services:   paperless:     container_name: paperless     cpu_percent: 25     mem_limit: 256m     image: linuxserver/paperless-ngx:latest     network_mode: "bridge"     restart: always     ports:       - 6688:8000 # host:container     volumes:       - ${LOCAL_SOC_LOCATION}/paperless/data:/data       - ${APP_DATA_LOCATION}/paperless-ngx:/config     environment:       - PAPERLESS_DATA_DIR=/config       - PAPERLESS_MEDIA_ROOT=/data/media       - PAPERLESS_CONSUMPTION_DIR=/data/consume   ```

**Comment by pablosproject** [comment]
Same here when adding lots of documents from the consumer data folder.
Here the attached log
```
12:47:06 [Q] INFO Enqueued 769
[2022-07-08 12:47:06,749] [ERROR] [paperless.consumer] Error while consuming document Bolletta-Luce-Retro 1.pdf: TypeError: shutdown() got an unexpected keyword argument 'cancel_futures'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/builtin_plugins/concurrency.py", line 135, in _execute
    result = future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 638, in _pdf_pageinfo_sync
    page = PageInfo(pdf, pageno, infile, check_pages, detailed_analysis)
  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 716, in __init__
    self._gather_pageinfo(pdf, pageno, infile, check_pages, detailed_analysis)
  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 762, in _gather_pageinfo
    for ci in _process_content_streams(
  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 565, in _process_content_streams
    yield from _find_regular_images(container, contentsinfo)
  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 483, in _find_regular_images
    yield ImageInfo(name=draw.name, pdfimage=pdfimage, shorthand=draw.shorthand)
  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 353, in __init__
    pim_icc = pim.icc
  File "/usr/local/lib/python3.8/dist-packages/pikepdf/models/image.py", line 479, in icc
    self._icc = ImageCms.ImageCmsProfile(iccbytesio)
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageCms.py", line 202, in __init__
    self._set(core.profile_frombytes(profile.read()))
  File "/usr/local/lib/python3.8/dist-packages/PIL/_util.py", line 19, in __getattr__
    raise self.ex
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageCms.py", line 25, in <module>
    from PIL import _imagingcms
ImportError: cannot import name '_imagingcms' from 'PIL' (/usr/local/lib/python3.8/dist-packages/PIL/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/paperless/src/paperless_tesseract/parsers.py", line 261, in parse
    ocrmypdf.ocr(**args)
  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/api.py", line 337, in ocr
    return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)
  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/_sync.py", line 370, in run_pipeline
    pdfinfo = get_pdfinfo(
  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/_pipeline.py", line 163, in get_pdfinfo
    return PdfInfo(
  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 904, in __init__
    self._pages = _pdf_pageinfo_concurrent(
  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 681, in _pdf_pageinfo_concurrent
    executor(
  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/_concurrent.py", line 82, in __call__
    self._execute(
  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/builtin_plugins/concurrency.py", line 148, in _execute
    executor.shutdown(wait=False, cancel_futures=True)
TypeError: shutdown() got an unexpected keyword argument 'cancel_futures'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/paperless/src/documents/consumer.py", line 261, in try_consume_file
    document_parser.parse(self.path, mime_type, self.filename)
  File "/app/paperless/src/paperless_tesseract/parsers.py", line 314, in parse
    raise ParseError(f"{e.__class__.__name__}: {str(e)}")
documents.parsers.ParseError: TypeError: shutdown() got an unexpected keyword argument 'cancel_futures'
```

**Comment by shamoon** [comment]
Sorry have you verified this is present in our image?

**Comment by pablosproject** [comment]
Yes, sorry for not having explicated before. I am running paperless on the latest docker image version.

**Comment by jokob-sk** [comment]
Just FYI the fix in the linked project is to conditionally use `self.executor.shutdown()` if python version is `<=` 3.8:

```python
        if current_python_version() <= python38():
            self.executor.shutdown()
        else:
            self.executor.shutdown(cancel_futures=True)
```
See fix here:

https://github.com/DiscordTime/ggdrive/commit/d811d77873ac2a71a414c4d53b752560d0032305

**Comment by bauerj** [comment]
Great! Would you be able to send a pull request with such a change?

**Comment by shamoon** [comment]
But I think the bug is in ocympdf not here, right? So its a dependency issue...

**Comment by jokob-sk** [comment]
> But I think the bug is in ocympdf not here, right? So its a dependency issue...

I think you are right. I've found a closed issue which contains an error with the `cancel_futures` keyword in the `ocympdf ` repo: https://github.com/ocrmypdf/OCRmyPDF/issues/870

...but I'm not sure if it fixes this issue. 

I'm not using Python much, so not sure if the `paperless-ngs` codebase uses the latest version of `ocympdf ` or if I should open a new issue in the  `ocympdf ` repo as well? Happy for you to do it as well if that's the case, I'm easy.

**Comment by jokob-sk** [comment]
Just BTW - thanks a lot for this great piece of software - if it works, it's magic :) Really appreciate the amount of work put into maintaining it.

**Comment by jokob-sk** [comment]
So I re-build my container with the `ghcr.io/paperless-ngx/paperless-ngx:latest`. I tried to reproduce the bug, but the scanned document is being ingested properly with OCR working as intended.  I think this is a bug only related to the linuxserver image. Not sure if you want to put out a disclaimer that the linuxserver image is broken, but I think it's OK to close this and keep the bug open on the linuxserver image repo.

**Comment by shamoon** [comment]
Well that was my first question, if you were using our image. 

lsio have had a lot of issues with dependencies in their image. We don’t have anything to do with it so not going to post anything about it here (and I’m sure they’ll sort it)

**Comment by jokob-sk** [comment]
I mentioned the installation method in my original post:
>>>
>Installation method
>Docker - linuxserver.io image
>>>
So I thought the question was directed to the second commenter. Anyway, thanks for the support and great work on this software!
