### ISSUE TITLE
[BUG] Scanner creates files in the consume folder before the scan is finished and paperless fails consuming it

### ISSUE THREAD

**Issue by amo13** [paperless-ngx/paperless-ngx#1279]
### Description

I set up my scanner (Lexmark CX317dn) to scan directly to the paperless consume folder using FTP. Unfortunately, my scanner appears to be somewhat dumb because it creates the file in the consume folder over FTP before finishing the scan. Sometimes, it works fine but it seems to be a matter of luck. This is even worse when I scan a multi-page document. My scanner supports that but still the file is created way before the scan is finished and the content of the file is actually written.
The problem here is that paperless sees the file and tries to consume it but fails because it is an empty (or invalid) file.

I don't know what exactly to do about it code-wise, but I thought I'd still report this as it is possible that other scanners and users are also affected. Maybe implementing a simple check for empty or invalid files would be enough to work around this, retrying to consume the file as soon as it is modified. 

### Steps to reproduce

Scan to the consume folder over FTP with a Lexmark CX317dn.

### Webserver logs

```bash
Jul 25 09:54:22 server paperless-manage[577867]: [2022-07-25 07:54:22,746] [INFO] [paperless.consumer] Consuming scan-2022-07-25-095249.pdf
Jul 25 09:54:22 server paperless-manage[577867]: [2022-07-25 07:54:22,936] [WARNING] [paperless.parsing.tesseract] Error while getting text from PDF document with pdfminer.six
Jul 25 09:54:22 server paperless-manage[577867]: Traceback (most recent call last):
Jul 25 09:54:22 server paperless-manage[577867]:   File "/usr/lib/python3.10/site-packages/pdfminer/pdfdocument.py", line 721, in __init__
Jul 25 09:54:22 server paperless-manage[577867]:     pos = self.find_xref(parser)
Jul 25 09:54:22 server paperless-manage[577867]:   File "/usr/lib/python3.10/site-packages/pdfminer/pdfdocument.py", line 978, in find_xref
Jul 25 09:54:22 server paperless-manage[577867]:     raise PDFNoValidXRef("Unexpected EOF")
Jul 25 09:54:22 server paperless-manage[577867]: pdfminer.pdfdocument.PDFNoValidXRef: Unexpected EOF
Jul 25 09:54:22 server paperless-manage[577867]: During handling of the above exception, another exception occurred:
Jul 25 09:54:22 server paperless-manage[577867]: Traceback (most recent call last):
Jul 25 09:54:22 server paperless-manage[577867]:   File "/usr/share/paperless/src/paperless_tesseract/parsers.py", line 120, in extract_text
Jul 25 09:54:22 server paperless-manage[577867]:     stripped = post_process_text(pdfminer_extract_text(pdf_file))
Jul 25 09:54:22 server paperless-manage[577867]:   File "/usr/lib/python3.10/site-packages/pdfminer/high_level.py", line 157, in extract_text
Jul 25 09:54:22 server paperless-manage[577867]:     for page in PDFPage.get_pages(
Jul 25 09:54:22 server paperless-manage[577867]:   File "/usr/lib/python3.10/site-packages/pdfminer/pdfpage.py", line 151, in get_pages
Jul 25 09:54:22 server paperless-manage[577867]:     doc = PDFDocument(parser, password=password, caching=caching)
Jul 25 09:54:22 server paperless-manage[577867]:   File "/usr/lib/python3.10/site-packages/pdfminer/pdfdocument.py", line 727, in __init__
Jul 25 09:54:22 server paperless-manage[577867]:     newxref.load(parser)
Jul 25 09:54:22 server paperless-manage[577867]:   File "/usr/lib/python3.10/site-packages/pdfminer/pdfdocument.py", line 241, in load
Jul 25 09:54:22 server paperless-manage[577867]:     (_, obj) = parser.nextobject()
Jul 25 09:54:22 server paperless-manage[577867]:   File "/usr/lib/python3.10/site-packages/pdfminer/psparser.py", line 607, in nextobject
Jul 25 09:54:22 server paperless-manage[577867]:     (pos, token) = self.nexttoken()
Jul 25 09:54:22 server paperless-manage[577867]:   File "/usr/lib/python3.10/site-packages/pdfminer/psparser.py", line 524, in nexttoken
Jul 25 09:54:22 server paperless-manage[577867]:     self.fillbuf()
Jul 25 09:54:22 server paperless-manage[577867]:   File "/usr/lib/python3.10/site-packages/pdfminer/psparser.py", line 239, in fillbuf
Jul 25 09:54:22 server paperless-manage[577867]:     raise PSEOF("Unexpected EOF")
Jul 25 09:54:22 server paperless-manage[577867]: pdfminer.psparser.PSEOF: Unexpected EOF
Jul 25 09:54:25 server paperless-manage[577867]: [2022-07-25 07:54:25,302] [WARNING] [paperless.parsing.tesseract] Encountered an error while running OCR: . Attempting force OCR to get the text.
Jul 25 09:54:27 server paperless-manage[577867]: [2022-07-25 07:54:27,032] [ERROR] [paperless.consumer] Error while consuming document scan-2022-07-25-095249.pdf: InputFileError:
Jul 25 09:54:27 server paperless-manage[577867]: Traceback (most recent call last):
Jul 25 09:54:27 server paperless-manage[577867]:   File "/usr/lib/python3.10/site-packages/ocrmypdf/_pipeline.py", line 163, in get_pdfinfo
Jul 25 09:54:27 server paperless-manage[577867]:     return PdfInfo(
Jul 25 09:54:27 server paperless-manage[577867]:   File "/usr/lib/python3.10/site-packages/ocrmypdf/pdfinfo/info.py", line 947, in __init__
Jul 25 09:54:27 server paperless-manage[577867]:     with Pdf.open(infile) as pdf:
Jul 25 09:54:27 server paperless-manage[577867]:   File "/usr/lib/python3.10/site-packages/pikepdf/_methods.py", line 799, in open
Jul 25 09:54:27 server paperless-manage[577867]:     pdf = Pdf._open(
Jul 25 09:54:27 server paperless-manage[577867]: pikepdf._qpdf.PdfError: /tmp/ocrmypdf.io.d3so9y3o/origin.pdf: unable to find trailer dictionary while recovering damaged file
Jul 25 09:54:27 server paperless-manage[577867]: The above exception was the direct cause of the following exception:
Jul 25 09:54:27 server paperless-manage[577867]: Traceback (most recent call last):
Jul 25 09:54:27 server paperless-manage[577867]:   File "/usr/share/paperless/src/paperless_tesseract/parsers.py", line 261, in parse
Jul 25 09:54:27 server paperless-manage[577867]:     ocrmypdf.ocr(**args)
Jul 25 09:54:27 server paperless-manage[577867]:   File "/usr/lib/python3.10/site-packages/ocrmypdf/api.py", line 341, in ocr
Jul 25 09:54:27 server paperless-manage[577867]:     return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)
Jul 25 09:54:27 server paperless-manage[577867]:   File "/usr/lib/python3.10/site-packages/ocrmypdf/_sync.py", line 378, in run_pipeline
Jul 25 09:54:27 server paperless-manage[577867]:     pdfinfo = get_pdfinfo(
Jul 25 09:54:27 server paperless-manage[577867]:   File "/usr/lib/python3.10/site-packages/ocrmypdf/_pipeline.py", line 174, in get_pdfinfo
Jul 25 09:54:27 server paperless-manage[577867]:     raise InputFileError() from e
Jul 25 09:54:27 server paperless-manage[577867]: ocrmypdf.exceptions.InputFileError
Jul 25 09:54:27 server paperless-manage[577867]: During handling of the above exception, another exception occurred:
Jul 25 09:54:27 server paperless-manage[577867]: Traceback (most recent call last):
Jul 25 09:54:27 server paperless-manage[577867]:   File "/usr/lib/python3.10/site-packages/ocrmypdf/_pipeline.py", line 163, in get_pdfinfo
Jul 25 09:54:27 server paperless-manage[577867]:     return PdfInfo(
Jul 25 09:54:27 server paperless-manage[577867]:   File "/usr/lib/python3.10/site-packages/ocrmypdf/pdfinfo/info.py", line 947, in __init__
Jul 25 09:54:27 server paperless-manage[577867]:     with Pdf.open(infile) as pdf:
Jul 25 09:54:27 server paperless-manage[577867]:   File "/usr/lib/python3.10/site-packages/pikepdf/_methods.py", line 799, in open
Jul 25 09:54:27 server paperless-manage[577867]:     pdf = Pdf._open(
Jul 25 09:54:27 server paperless-manage[577867]: pikepdf._qpdf.PdfError: /tmp/ocrmypdf.io.e5bg97n7/origin.pdf: unable to find trailer dictionary while recovering damaged file
Jul 25 09:54:27 server paperless-manage[577867]: The above exception was the direct cause of the following exception:
Jul 25 09:54:27 server paperless-manage[577867]: Traceback (most recent call last):
Jul 25 09:54:27 server paperless-manage[577867]:   File "/usr/share/paperless/src/paperless_tesseract/parsers.py", line 298, in parse
Jul 25 09:54:27 server paperless-manage[577867]:     ocrmypdf.ocr(**args)
Jul 25 09:54:27 server paperless-manage[577867]:   File "/usr/lib/python3.10/site-packages/ocrmypdf/api.py", line 341, in ocr
Jul 25 09:54:27 server paperless-manage[577867]:     return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)
Jul 25 09:54:27 server paperless-manage[577867]:   File "/usr/lib/python3.10/site-packages/ocrmypdf/_sync.py", line 378, in run_pipeline
Jul 25 09:54:27 server paperless-manage[577867]:     pdfinfo = get_pdfinfo(
Jul 25 09:54:27 server paperless-manage[577867]:   File "/usr/lib/python3.10/site-packages/ocrmypdf/_pipeline.py", line 174, in get_pdfinfo
Jul 25 09:54:27 server paperless-manage[577867]:     raise InputFileError() from e
Jul 25 09:54:27 server paperless-manage[577867]: ocrmypdf.exceptions.InputFileError
Jul 25 09:54:27 server paperless-manage[577867]: During handling of the above exception, another exception occurred:
Jul 25 09:54:27 server paperless-manage[577867]: Traceback (most recent call last):
Jul 25 09:54:27 server paperless-manage[577867]:   File "/usr/share/paperless/src/documents/consumer.py", line 261, in try_consume_file
Jul 25 09:54:27 server paperless-manage[577867]:     document_parser.parse(self.path, mime_type, self.filename)
Jul 25 09:54:27 server paperless-manage[577867]:   File "/usr/share/paperless/src/paperless_tesseract/parsers.py", line 310, in parse
Jul 25 09:54:27 server paperless-manage[577867]:     raise ParseError(f"{e.__class__.__name__}: {str(e)}")
Jul 25 09:54:27 server paperless-manage[577867]: documents.parsers.ParseError: InputFileError:
Jul 25 09:54:27 server paperless-manage[577867]: 07:54:27 [Q] INFO Process-1:3349 stopped doing work
Jul 25 09:54:27 server paperless-manage[2097]: 07:54:27 [Q] INFO recycled worker Process-1:3349
Jul 25 09:54:27 server paperless-manage[577951]: 07:54:27 [Q] INFO Process-1:3351 ready for work at 577951
Jul 25 09:54:27 server paperless-manage[2102]: 07:54:27 [Q] ERROR Failed [scan-2022-07-25-095249.pdf] - scan-2022-07-25-095249.pdf: Error while consuming document scan-2022-07-25-095249.pdf: InputFileError:  : >
Jul 25 09:54:27 server paperless-manage[2102]:   File "/usr/lib/python3.10/site-packages/ocrmypdf/_pipeline.py", line 163, in get_pdfinfo
Jul 25 09:54:27 server paperless-manage[2102]:     return PdfInfo(
Jul 25 09:54:27 server paperless-manage[2102]:   File "/usr/lib/python3.10/site-packages/ocrmypdf/pdfinfo/info.py", line 947, in __init__
Jul 25 09:54:27 server paperless-manage[2102]:     with Pdf.open(infile) as pdf:
Jul 25 09:54:27 server paperless-manage[2102]:   File "/usr/lib/python3.10/site-packages/pikepdf/_methods.py", line 799, in open
Jul 25 09:54:27 server paperless-manage[2102]:     pdf = Pdf._open(
Jul 25 09:54:27 server paperless-manage[2102]: pikepdf._qpdf.PdfError: /tmp/ocrmypdf.io.d3so9y3o/origin.pdf: unable to find trailer dictionary while recovering damaged file
Jul 25 09:54:27 server paperless-manage[2102]: The above exception was the direct cause of the following exception:
Jul 25 09:54:27 server paperless-manage[2102]: Traceback (most recent call last):
Jul 25 09:54:27 server paperless-manage[2102]:   File "/usr/share/paperless/src/paperless_tesseract/parsers.py", line 261, in parse
Jul 25 09:54:27 server paperless-manage[2102]:     ocrmypdf.ocr(**args)
Jul 25 09:54:27 server paperless-manage[2102]:   File "/usr/lib/python3.10/site-packages/ocrmypdf/api.py", line 341, in ocr
Jul 25 09:54:27 server paperless-manage[2102]:     return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)
Jul 25 09:54:27 server paperless-manage[2102]:   File "/usr/lib/python3.10/site-packages/ocrmypdf/_sync.py", line 378, in run_pipeline
Jul 25 09:54:27 server paperless-manage[2102]:     pdfinfo = get_pdfinfo(
Jul 25 09:54:27 server paperless-manage[2102]:   File "/usr/lib/python3.10/site-packages/ocrmypdf/_pipeline.py", line 174, in get_pdfinfo
Jul 25 09:54:27 server paperless-manage[2102]:     raise InputFileError() from e
Jul 25 09:54:27 server paperless-manage[2102]: ocrmypdf.exceptions.InputFileError
Jul 25 09:54:27 server paperless-manage[2102]: During handling of the above exception, another exception occurred:
Jul 25 09:54:27 server paperless-manage[2102]: Traceback (most recent call last):
Jul 25 09:54:27 server paperless-manage[2102]:   File "/usr/lib/python3.10/site-packages/ocrmypdf/_pipeline.py", line 163, in get_pdfinfo
Jul 25 09:54:27 server paperless-manage[2102]:     return PdfInfo(
Jul 25 09:54:27 server paperless-manage[2102]:   File "/usr/lib/python3.10/site-packages/ocrmypdf/pdfinfo/info.py", line 947, in __init__
Jul 25 09:54:27 server paperless-manage[2102]:     with Pdf.open(infile) as pdf:
Jul 25 09:54:27 server paperless-manage[2102]:   File "/usr/lib/python3.10/site-packages/pikepdf/_methods.py", line 799, in open
Jul 25 09:54:27 server paperless-manage[2102]:     pdf = Pdf._open(
Jul 25 09:54:27 server paperless-manage[2102]: pikepdf._qpdf.PdfError: /tmp/ocrmypdf.io.e5bg97n7/origin.pdf: unable to find trailer dictionary while recovering damaged file
Jul 25 09:54:27 server paperless-manage[2102]: The above exception was the direct cause of the following exception:
Jul 25 09:54:27 server paperless-manage[2102]: Traceback (most recent call last):
Jul 25 09:54:27 server paperless-manage[2102]:   File "/usr/share/paperless/src/paperless_tesseract/parsers.py", line 298, in parse
Jul 25 09:54:27 server paperless-manage[2102]:     ocrmypdf.ocr(**args)
Jul 25 09:54:27 server paperless-manage[2102]:   File "/usr/lib/python3.10/site-packages/ocrmypdf/api.py", line 341, in ocr
Jul 25 09:54:27 server paperless-manage[2102]:     return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)
Jul 25 09:54:27 server paperless-manage[2102]:   File "/usr/lib/python3.10/site-packages/ocrmypdf/_sync.py", line 378, in run_pipeline
Jul 25 09:54:27 server paperless-manage[2102]:     pdfinfo = get_pdfinfo(
Jul 25 09:54:27 server paperless-manage[2102]:   File "/usr/lib/python3.10/site-packages/ocrmypdf/_pipeline.py", line 174, in get_pdfinfo
Jul 25 09:54:27 server paperless-manage[2102]:     raise InputFileError() from e
Jul 25 09:54:27 server paperless-manage[2102]: ocrmypdf.exceptions.InputFileError
Jul 25 09:54:27 server paperless-manage[2102]: During handling of the above exception, another exception occurred:
Jul 25 09:54:27 server paperless-manage[2102]: Traceback (most recent call last):
Jul 25 09:54:27 server paperless-manage[2102]:   File "/usr/lib/python3.10/site-packages/asgiref/sync.py", line 280, in main_wrap
Jul 25 09:54:27 server paperless-manage[2102]:     raise exc_info[1]
Jul 25 09:54:27 server paperless-manage[2102]:   File "/usr/share/paperless/src/documents/consumer.py", line 261, in try_consume_file
Jul 25 09:54:27 server paperless-manage[2102]:     document_parser.parse(self.path, mime_type, self.filename)
Jul 25 09:54:27 server paperless-manage[2102]:   File "/usr/share/paperless/src/paperless_tesseract/parsers.py", line 310, in parse
Jul 25 09:54:27 server paperless-manage[2102]:     raise ParseError(f"{e.__class__.__name__}: {str(e)}")
Jul 25 09:54:27 server paperless-manage[2102]: documents.parsers.ParseError: InputFileError:
Jul 25 09:54:27 server paperless-manage[2102]: During handling of the above exception, another exception occurred:
Jul 25 09:54:27 server paperless-manage[2102]: Traceback (most recent call last):
Jul 25 09:54:27 server paperless-manage[2102]:   File "/usr/lib/python3.10/site-packages/django_q/cluster.py", line 432, in worker
Jul 25 09:54:27 server paperless-manage[2102]:     res = f(*task["args"], **task["kwargs"])
Jul 25 09:54:27 server paperless-manage[2102]:   File "/usr/share/paperless/src/documents/tasks.py", line 298, in consume_file
Jul 25 09:54:27 server paperless-manage[2102]:     document = Consumer().try_consume_file(
Jul 25 09:54:27 server paperless-manage[2102]:   File "/usr/share/paperless/src/documents/consumer.py", line 280, in try_consume_file
Jul 25 09:54:27 server paperless-manage[2102]:     self._fail(
Jul 25 09:54:27 server paperless-manage[2102]:   File "/usr/share/paperless/src/documents/consumer.py", line 81, in _fail
Jul 25 09:54:27 server paperless-manage[2102]:     raise ConsumerError(f"{self.filename}: {log_message or message}")
Jul 25 09:54:27 server paperless-manage[2102]: documents.consumer.ConsumerError: scan-2022-07-25-095249.pdf: Error while consuming document scan-2022-07-25-095249.pdf: InputFileError:
```

### Paperless-ngx version

1.7.1

### Host OS

Archlinux

### Installation method

Bare metal

### Browser

Firefox

### Configuration changes

Use filesystem polling every 10s instead of inotify because of the 100% CPU bug over time

**Comment by shamoon** [comment]
Many other folks have reported similar issues, most recently https://github.com/paperless-ngx/paperless-ngx/discussions/1210 , the big takeaway from that is:

> PAPERLESS_CONSUMER_INOTIFY_DELAY, coming in the next release. For the current version. try using polling instead, PAPERLESS_CONSUMER_POLLING=1, which includes additional checking for a noticed file to be unchanged before consuming.

Version 1.8 which includes the first option is currently in beta, should be released soon-ish

**Comment by amo13** [comment]
Alright, thank you.
