### ISSUE TITLE
[BUG] InterfaceError while consuming document

### ISSUE THREAD

**Issue by matze338** [paperless-ngx/paperless-ngx#1355]
### Description

Since Version 1.80 all kind of documents (docx, PDF, etc) wich i put in my consume folder executing the consuming process stops with the following error:

### Steps to reproduce

Insert a document into the consume folder.

### Webserver logs

```bash
[2022-08-03 21:10:54,601] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/TEST.docx to the task queue.
[2022-08-03 21:10:54,604] [ERROR] [paperless.management.consumer] Error while consuming document
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 262, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 256, in create_cursor
    cursor = self.connection.cursor()
psycopg2.InterfaceError: connection already closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 94, in _consume
    async_task(
  File "/usr/src/paperless/src/docker/src/django-q/django_q/tasks.py", line 67, in async_task
    pre_enqueue.send(sender="django_q", task=task)
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/usr/src/paperless/src/documents/signals/handlers.py", line 511, in init_paperless_task
    paperless_task, created = PaperlessTask.objects.get_or_create(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 657, in get_or_create
    return self.get(**kwargs), False
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 492, in get
    num = len(clone)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 302, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1507, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1359, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 284, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 262, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 262, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 256, in create_cursor
    cursor = self.connection.cursor()
django.db.utils.InterfaceError: connection already closed
```

### Paperless-ngx version

1.80

### Host OS

Synology NAS

### Installation method

Docker - official image

### Configuration changes

no changes since 1.7.0

**Comment by stumpylog** [comment]
Thank you for the bug report.  This new task viewing functionality is being a real pain.  I'm not sure what the solution will be here yet.

**Comment by schnerring** [comment]
I scanned ~500 documents with version `1.8.0` and want to report my findings, hoping this is somewhat helpful.

After the error is encountered, consuming completely stops and paperless has to be restarted. After restarting, consuming will continue until the error occurs again. I haven't looked into the code but it feels like after a while the Postgres connection of the consumer times out.

I'm running paperless-ngx via [TrueCharts](https://truecharts.org/) which uses the Postgres setup. It's basically a Helm chart running on TrueNAS Kubernetes. My paperless consume directory is also exposed via SMB to my flatbed scanner. The filename prefix configured for my scanner is `scan`. If the consume folder is empty, the scanner names the the scan `${prefix}.pdf` (`scan.pdf`). If it's not empty, it names it `${prefix}${scanned_count}.pdf` (`scan0398.pdf`).

---

So let's look at an example run. 

Assuming paperless consuming is halted, I scan a couple of documents until the contents of the consume directory look like this.

```text
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          04/09/2022    14:29        1452843 scan.pdf
-a---          04/09/2022    14:32        1297782 scan0392.pdf
-a---          04/09/2022    14:33         643211 scan0393.pdf
-a---          04/09/2022    14:35        1284924 scan0394.pdf
-a---          04/09/2022    14:37        2740166 scan0395.pdf
-a---          04/09/2022    14:40        1151291 scan0396.pdf
-a---          04/09/2022    14:40        1226760 scan0397.pdf
-a---          04/09/2022    14:41         328175 scan0398.pdf
```

Restarting paperless resumes consuming. This will always succeed, no matter whether it's only a few documents but or 50 documents or more.

Next, I'll scan another document. Since the consume directory is now empty, my scanner will name it `scan.pdf`. Paperless will quickly consume the document, and the consume directory is empty again. This seems to work for an indefinite amount of scans as long as I don't wait for too long.

Here is the timeline of my most recent run:

```text
[2022-09-04 14:59:43,483] [INFO] [paperless.management.consumer] Adding /consume/scan0394.pdf to the task queue.
[2022-09-04 14:59:43,493] [INFO] [paperless.management.consumer] Adding /consume/scan0393.pdf to the task queue.
[2022-09-04 14:59:43,501] [INFO] [paperless.management.consumer] Adding /consume/scan0392.pdf to the task queue.
[2022-09-04 14:59:43,509] [INFO] [paperless.management.consumer] Adding /consume/scan0395.pdf to the task queue.
[2022-09-04 14:59:43,517] [INFO] [paperless.management.consumer] Adding /consume/scan0396.pdf to the task queue.
[2022-09-04 14:59:43,524] [INFO] [paperless.management.consumer] Adding /consume/scan0398.pdf to the task queue.
[2022-09-04 14:59:43,531] [INFO] [paperless.management.consumer] Adding /consume/scan.pdf to the task queue.
[2022-09-04 14:59:43,543] [INFO] [paperless.management.consumer] Adding /consume/scan0397.pdf to the task queue.

[2022-09-04 14:59:43,666] [INFO] [paperless.consumer] Consuming scan0394.pdf
[2022-09-04 15:00:03,640] [INFO] [paperless.consumer] Consuming scan0393.pdf
[2022-09-04 15:00:23,683] [INFO] [paperless.consumer] Consuming scan0392.pdf
[2022-09-04 15:00:43,713] [INFO] [paperless.consumer] Consuming scan0395.pdf
[2022-09-04 15:01:03,726] [INFO] [paperless.consumer] Consuming scan0396.pdf
[2022-09-04 15:01:33,776] [INFO] [paperless.consumer] Consuming scan.pdf
[2022-09-04 15:01:53,835] [INFO] [paperless.consumer] Consuming scan0397.pdf

# <----- This is where I start scanning more documents one-by-one

[2022-09-04 15:03:43,885] [INFO] [paperless.consumer] Consuming scan.pdf
[2022-09-04 15:05:30,925] [INFO] [paperless.consumer] Consuming scan.pdf
[2022-09-04 15:12:36,142] [INFO] [paperless.consumer] Consuming scan.pdf
[2022-09-04 15:17:54,578] [INFO] [paperless.consumer] Consuming scan.pdf
[2022-09-04 15:24:48,492] [INFO] [paperless.consumer] Consuming scan.pdf
[2022-09-04 15:25:46,588] [INFO] [paperless.consumer] Consuming scan0399.pdf
[2022-09-04 15:27:04,032] [INFO] [paperless.consumer] Consuming scan.pdf
[2022-09-04 15:28:20,470] [INFO] [paperless.consumer] Consuming scan.pdf
[2022-09-04 15:28:48,250] [INFO] [paperless.consumer] Consuming scan.pdf
[2022-09-04 15:29:49,956] [INFO] [paperless.consumer] Consuming scan.pdf
[2022-09-04 15:30:42,799] [INFO] [paperless.consumer] Consuming scan.pdf
[2022-09-04 15:31:46,560] [INFO] [paperless.consumer] Consuming scan.pdf
[2022-09-04 15:35:52,317] [INFO] [paperless.consumer] Consuming scan.pdf
[2022-09-04 15:45:20,473] [INFO] [paperless.consumer] Consuming scan.pdf
[2022-09-04 15:53:24,941] [INFO] [paperless.consumer] Consuming scan.pdf
[2022-09-04 15:54:55,854] [INFO] [paperless.consumer] Consuming scan0400.pdf
[2022-09-04 15:57:15,803] [INFO] [paperless.consumer] Consuming scan.pdf
[2022-09-04 15:58:42,692] [INFO] [paperless.consumer] Consuming scan.pdf
[2022-09-04 16:00:31,732] [INFO] [paperless.consumer] Consuming scan.pdf
[2022-09-04 16:02:02,637] [INFO] [paperless.consumer] Consuming scan.pdf
[2022-09-04 16:04:05,403] [INFO] [paperless.consumer] Consuming scan.pdf
[2022-09-04 16:05:11,180] [INFO] [paperless.consumer] Consuming scan.pdf
[2022-09-04 16:07:38,721] [INFO] [paperless.consumer] Consuming scan.pdf
[2022-09-04 16:08:48,262] [INFO] [paperless.consumer] Consuming scan.pdf
[2022-09-04 16:10:49,550] [INFO] [paperless.consumer] Consuming scan.pdf
[2022-09-04 16:13:00,298] [INFO] [paperless.consumer] Consuming scan.pdf
[2022-09-04 16:15:25,658] [INFO] [paperless.consumer] Consuming scan.pdf
[2022-09-04 16:17:29,833] [INFO] [paperless.consumer] Consuming scan.pdf
[2022-09-04 16:19:26,230] [INFO] [paperless.consumer] Consuming scan.pdf
[2022-09-04 16:22:00,734] [INFO] [paperless.consumer] Consuming scan.pdf
[2022-09-04 16:23:54,481] [INFO] [paperless.consumer] Consuming scan.pdf
[2022-09-04 16:25:38,107] [INFO] [paperless.consumer] Consuming scan.pdf
[2022-09-04 16:26:37,857] [INFO] [paperless.consumer] Consuming scan.pdf
```

Everything went smoothly until I took a 30 minute break. Then I scanned the next document:

```text
[2022-09-04 16:54:43,885] [INFO] [paperless.management.consumer] Adding /consume/scan.pdf to the task queue.
[2022-09-04 16:54:43,888] [ERROR] [paperless.handlers] Creating PaperlessTask failed: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
[2022-09-04 16:54:44,035] [INFO] [paperless.consumer] Consuming scan.pdf
```

That document actually gets consumed and makes it to the document library. The next scan fails and crashes the paperless consumer with the following error:

```text
[2022-09-04 16:55:27,988] [INFO] [paperless.management.consumer] Adding /consume/scan.pdf to the task queue.
[2022-09-04 16:55:27,992] [ERROR] [paperless.management.consumer] Error while consuming document
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 262, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 256, in create_cursor
    cursor = self.connection.cursor()
psycopg2.InterfaceError: connection already closed
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 94, in _consume
    async_task(
  File "/usr/src/paperless/src/docker/src/django-q/django_q/tasks.py", line 67, in async_task
    pre_enqueue.send(sender="django_q", task=task)
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/usr/src/paperless/src/documents/signals/handlers.py", line 511, in init_paperless_task
    paperless_task, created = PaperlessTask.objects.get_or_create(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 657, in get_or_create
    return self.get(**kwargs), False
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 492, in get
    num = len(clone)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 302, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1507, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1359, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 284, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 262, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 262, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 256, in create_cursor
    cursor = self.connection.cursor()
django.db.utils.InterfaceError: connection already closed
```

**Comment by WingMan81** [comment]
100% same behaviour as described by @schnerring with my instance. Also used TrueCharts on TrueNAS.
[2022-09-09 12:44:13,252] [DEBUG] [paperless.tasks] Training data unchanged.
[2022-09-09 13:25:00,079] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: /consume
[2022-09-10 00:48:19,177] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: /consume
[2022-09-10 00:48:57,513] [DEBUG] [paperless.classifier] Gathering data from database...
[2022-09-10 00:48:57,637] [DEBUG] [paperless.tasks] Training data unchanged.
[2022-09-10 01:44:20,149] [DEBUG] [paperless.classifier] Gathering data from database...
[2022-09-10 01:44:20,169] [DEBUG] [paperless.tasks] Training data unchanged.
[2022-09-10 02:44:24,900] [DEBUG] [paperless.classifier] Gathering data from database...
[2022-09-10 02:44:24,920] [DEBUG] [paperless.tasks] Training data unchanged.
[2022-09-10 03:44:29,998] [DEBUG] [paperless.classifier] Gathering data from database...
[2022-09-10 03:44:30,017] [DEBUG] [paperless.tasks] Training data unchanged.
[2022-09-10 04:44:35,957] [DEBUG] [paperless.classifier] Gathering data from database...
[2022-09-10 04:44:35,976] [DEBUG] [paperless.tasks] Training data unchanged.
[2022-09-10 05:44:41,734] [DEBUG] [paperless.classifier] Gathering data from database...
[2022-09-10 05:44:41,753] [DEBUG] [paperless.tasks] Training data unchanged.
[2022-09-10 06:44:16,820] [DEBUG] [paperless.classifier] Gathering data from database...
[2022-09-10 06:44:16,839] [DEBUG] [paperless.tasks] Training data unchanged.
[2022-09-10 07:44:21,370] [DEBUG] [paperless.classifier] Gathering data from database...
[2022-09-10 07:44:21,388] [DEBUG] [paperless.tasks] Training data unchanged.
[2022-09-10 08:25:27,103] [INFO] [paperless.management.consumer] Adding /consume/BRWD80F993B89C9_000551.pdf to the task queue.
[2022-09-10 08:25:27,105] [ERROR] [paperless.handlers] Creating PaperlessTask failed: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
[2022-09-10 08:25:28,062] [INFO] [paperless.consumer] Consuming BRWD80F993B89C9_000551.pdf
[2022-09-10 08:25:28,145] [DEBUG] [paperless.consumer] Detected mime type: application/pdf
[2022-09-10 08:25:28,167] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser
[2022-09-10 08:25:28,177] [DEBUG] [paperless.consumer] Parsing BRWD80F993B89C9_000551.pdf...
[2022-09-10 08:25:28,503] [DEBUG] [paperless.parsing.tesseract] Extracted text from PDF file /consume/BRWD80F993B89C9_000551.pdf
[2022-09-10 08:25:29,356] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': '/consume/BRWD80F993B89C9_000551.pdf', 'output_file': '/tmp/paperless/paperless-z_o0ymg7/archive.pdf', 'use_threads': True, 'jobs': 4, 'language': 'eng', 'output_type': 'pdfa', 'progress_bar': False, 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': '/tmp/paperless/paperless-z_o0ymg7/sidecar.txt'}
[2022-09-10 08:28:25,428] [DEBUG] [paperless.parsing.tesseract] Using text from sidecar file
[2022-09-10 08:28:25,434] [DEBUG] [paperless.consumer] Generating thumbnail for BRWD80F993B89C9_000551.pdf...
[2022-09-10 08:28:25,439] [DEBUG] [paperless.parsing] Execute: convert -density 300 -scale 500x5000> -alpha remove -strip -auto-orient /tmp/paperless/paperless-z_o0ymg7/archive.pdf[0] /tmp/paperless/paperless-z_o0ymg7/convert.webp
[2022-09-10 08:28:29,101] [DEBUG] [paperless.consumer] Saving record to database
[2022-09-10 08:28:29,102] [DEBUG] [paperless.consumer] Creation date from parse_date: 2022-02-02 00:00:00-08:00
[2022-09-10 08:28:29,194] [DEBUG] [paperless.matching] Tag HT matched on document 2022-02-02 BRWD80F993B89C9_000551 because it contains this word: XY YZ
[2022-09-10 08:28:29,220] [DEBUG] [paperless.matching] Tag JH matched on document 2022-02-02 BRWD80F993B89C9_000551 because it contains this string: "AG"
[2022-09-10 08:28:29,220] [INFO] [paperless.handlers] Tagging "2022-02-02 BRWD80F993B89C9_000551" with "JH, HT"
[2022-09-10 08:28:29,544] [DEBUG] [paperless.consumer] Deleting file /consume/BRWD80F993B89C9_000551.pdf
[2022-09-10 08:28:29,549] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-z_o0ymg7
[2022-09-10 08:28:29,550] [INFO] [paperless.consumer] Document 2022-02-02 BRWD80F993B89C9_000551 consumption finished
[2022-09-10 08:29:35,460] [DEBUG] [paperless.matching] Tag HT matched on document 2022-02-02 BRWD80F993B89C9_000551 because it contains this word: XY YZ
[2022-09-10 08:29:35,477] [DEBUG] [paperless.matching] Tag JH matched on document 2022-02-02 BRWD80F993B89C9_000551 because it contains this string: "AG"
[2022-09-10 08:29:41,962] [DEBUG] [paperless.handlers] Deleted file /media/documents/originals/0000016.pdf.
[2022-09-10 08:29:41,962] [DEBUG] [paperless.handlers] Deleted file /media/documents/archive/0000016.pdf.
[2022-09-10 08:29:41,962] [DEBUG] [paperless.handlers] Deleted file /media/documents/thumbnails/0000016.webp.
[2022-09-10 08:29:50,431] [INFO] [paperless.management.consumer] Adding /consume/BRWD80F993B89C9_000551.pdf to the task queue.
[2022-09-10 08:29:50,432] [ERROR] [paperless.management.consumer] Error while consuming document
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 262, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 256, in create_cursor
    cursor = self.connection.cursor()
psycopg2.InterfaceError: connection already closed
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 94, in _consume
    async_task(
  File "/usr/src/paperless/src/docker/src/django-q/django_q/tasks.py", line 67, in async_task
    pre_enqueue.send(sender="django_q", task=task)
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/usr/src/paperless/src/documents/signals/handlers.py", line 511, in init_paperless_task
    paperless_task, created = PaperlessTask.objects.get_or_create(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 657, in get_or_create
    return self.get(**kwargs), False
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 492, in get
    num = len(clone)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 302, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1507, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1359, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 284, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 262, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 262, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 256, in create_cursor
    cursor = self.connection.cursor()
django.db.utils.InterfaceError: connection already closed

**Comment by stumpylog** [comment]
There were some fixed for django-q merged which might have helped with this.  Does it still occur with 1.9.2?

**Comment by schnerring** [comment]
Will be able to test end of next week

**Comment by matze338** [comment]
For me, it seems to be working again 👍

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/6f50285f47643560370f1f9734f57b5ab441bca1

**Comment by WingMan81** [comment]
For me it is also working. Thank you for the fix!

**Comment by calvinbui** [comment]
Strangely ran into this again on 1.11.3 but a restart resolved it.

**Comment by ginkel** [comment]
Unfortunately, I have observed this error for both of my Paperless-ngx (v1.13.0) instances:

```
[2023-04-05 16:16:44,539] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/20230405_161637.pdf to the task queue.
[2023-04-05 16:16:44,540] [ERROR] [paperless.handlers] Creating PaperlessTask failed: connection already closed
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 301, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 269, in create_cursor
    cursor = self.connection.cursor()
psycopg2.InterfaceError: connection already closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/signals/handlers.py", line 548, in before_task_publish_handler
    PaperlessTask.objects.create(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 671, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 812, in save
    self.save_base(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 863, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 1006, in _save_table
    results = self._do_insert(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 1047, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1791, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1658, in execute_sql
    with self.connection.cursor() as cursor:
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 323, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 301, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 301, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 269, in create_cursor
    cursor = self.connection.cursor()
django.db.utils.InterfaceError: connection already closed
```

So it seems that this is not fixed for all occurrences.

**Comment by bm55** [comment]
I am also having this issue:

`[2023-05-04 10:46:09,464] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/LIFENET® AED Event Viewer.pdf to the task queue.
[2023-05-04 10:46:09,579] [ERROR] [paperless.handlers] Creating PaperlessTask failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.AdminShutdown: terminating connection due to administrator command
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/signals/handlers.py", line 535, in before_task_publish_handler
    PaperlessTask.objects.create(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 671, in create
    obj.save(force_insert=True, using=self.db)`
