### ISSUE TITLE
[BUG] Webserver error 500 on 1.8.0 baremetal upgrade

### ISSUE THREAD

**Issue by Raptime** [paperless-ngx/paperless-ngx#1403]
### Description

Upgrading on baremetal (from 1.7.1), I downloaded and extracted the new archive (after doing a backup). restored paperless.conf as it is included in the archive for some reason (paperless.conf.example would probably be a safer default).
restarted all three processes just fine but when I go to the webui I get an error 500.
Logs say: "django.db.utils.OperationalError: no such table: documents_uisettings"

I thought it was maybe because the requirements.txt had changed so I ran the command to install those again but I get the same error.

See logs attached

### Steps to reproduce

1. have 1.7.1 installed in /opt/paperless
2. stop consumer, scheduler and webservice
3. move /opt/paperless folder to /opt/paperless-old
4. extract new 1.8.0 to /opt/paperless
5. copy paperless.config from /opt/paperless-old to /opt/paperless
6. start consumer, scheduler and webservice
7. browse to http://[paperless_ip]:8000
8. receive Server Error (500)

### Webserver logs

```bash
Aug 11 16:06:43 scans gunicorn[42332]: [2022-08-11 20:06:43 +0000] [42332] [INFO] Handling signal: term
Aug 11 16:06:43 scans gunicorn[42332]: [2022-08-11 20:06:43 +0000] [42332] [INFO] Shutting down: Master
Aug 11 16:10:49 scans gunicorn[44774]: [2022-08-11 20:10:49 +0000] [44774] [INFO] Starting gunicorn 20.1.0
Aug 11 16:10:49 scans gunicorn[44774]: [2022-08-11 20:10:49 +0000] [44774] [INFO] Listening at: http://[::]:8000 (44774)
Aug 11 16:10:49 scans gunicorn[44774]: [2022-08-11 20:10:49 +0000] [44774] [INFO] Using worker: paperless.workers.ConfigurableWorker
Aug 11 16:10:49 scans gunicorn[44774]: [2022-08-11 20:10:49 +0000] [44774] [INFO] Server is ready. Spawning workers
Aug 11 16:11:13 scans gunicorn[44793]: [2022-08-11 20:11:13,272] [ERROR] [django.request] Internal Server Error: /
Aug 11 16:11:13 scans gunicorn[44793]: Traceback (most recent call last):
Aug 11 16:11:13 scans gunicorn[44793]:   File "/home/nico/.local/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 442, in __get__
Aug 11 16:11:13 scans gunicorn[44793]:     rel_obj = self.related.get_cached_value(instance)
Aug 11 16:11:13 scans gunicorn[44793]:   File "/home/nico/.local/lib/python3.9/site-packages/django/db/models/fields/mixins.py", line 15, in get_cached_value
Aug 11 16:11:13 scans gunicorn[44793]:     return instance._state.fields_cache[cache_name]
Aug 11 16:11:13 scans gunicorn[44793]: KeyError: 'ui_settings'
Aug 11 16:11:13 scans gunicorn[44793]: During handling of the above exception, another exception occurred:
Aug 11 16:11:13 scans gunicorn[44793]: Traceback (most recent call last):
Aug 11 16:11:13 scans gunicorn[44793]:   File "/home/nico/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
Aug 11 16:11:13 scans gunicorn[44793]:     return self.cursor.execute(sql, params)
Aug 11 16:11:13 scans gunicorn[44793]:   File "/home/nico/.local/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 477, in execute
Aug 11 16:11:13 scans gunicorn[44793]:     return Database.Cursor.execute(self, query, params)
Aug 11 16:11:13 scans gunicorn[44793]: sqlite3.OperationalError: no such table: documents_uisettings
Aug 11 16:11:13 scans gunicorn[44793]: The above exception was the direct cause of the following exception:
Aug 11 16:11:13 scans gunicorn[44793]: Traceback (most recent call last):
Aug 11 16:11:13 scans gunicorn[44793]:   File "/home/nico/.local/lib/python3.9/site-packages/asgiref/sync.py", line 472, in thread_handler
Aug 11 16:11:13 scans gunicorn[44793]:     raise exc_info[1]
Aug 11 16:11:13 scans gunicorn[44793]:   File "/home/nico/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 42, in inner
Aug 11 16:11:13 scans gunicorn[44793]:     response = await get_response(request)
Aug 11 16:11:13 scans gunicorn[44793]:   File "/home/nico/.local/lib/python3.9/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
Aug 11 16:11:13 scans gunicorn[44793]:     response = await wrapped_callback(
Aug 11 16:11:13 scans gunicorn[44793]:   File "/home/nico/.local/lib/python3.9/site-packages/asgiref/sync.py", line 435, in __call__
Aug 11 16:11:13 scans gunicorn[44793]:     ret = await asyncio.wait_for(future, timeout=None)
Aug 11 16:11:13 scans gunicorn[44793]:   File "/usr/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
Aug 11 16:11:13 scans gunicorn[44793]:     return await fut
Aug 11 16:11:13 scans gunicorn[44793]:   File "/home/nico/.local/lib/python3.9/site-packages/asgiref/current_thread_executor.py", line 22, in run
Aug 11 16:11:13 scans gunicorn[44793]:     result = self.fn(*self.args, **self.kwargs)
Aug 11 16:11:13 scans gunicorn[44793]:   File "/home/nico/.local/lib/python3.9/site-packages/asgiref/sync.py", line 476, in thread_handler
Aug 11 16:11:13 scans gunicorn[44793]:     return func(*args, **kwargs)
Aug 11 16:11:13 scans gunicorn[44793]:   File "/home/nico/.local/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
Aug 11 16:11:13 scans gunicorn[44793]:     return view_func(request, *args, **kwargs)
Aug 11 16:11:13 scans gunicorn[44793]:   File "/home/nico/.local/lib/python3.9/site-packages/django/views/generic/base.py", line 84, in view
Aug 11 16:11:13 scans gunicorn[44793]:     return self.dispatch(request, *args, **kwargs)
Aug 11 16:11:13 scans gunicorn[44793]:   File "/home/nico/.local/lib/python3.9/site-packages/django/views/generic/base.py", line 119, in dispatch
Aug 11 16:11:13 scans gunicorn[44793]:     return handler(request, *args, **kwargs)
Aug 11 16:11:13 scans gunicorn[44793]:   File "/home/nico/.local/lib/python3.9/site-packages/django/views/generic/base.py", line 185, in get
Aug 11 16:11:13 scans gunicorn[44793]:     context = self.get_context_data(**kwargs)
Aug 11 16:11:13 scans gunicorn[44793]:   File "/opt/paperless/src/documents/views.py", line 118, in get_context_data
Aug 11 16:11:13 scans gunicorn[44793]:     context["styles_css"] = f"frontend/{self.get_frontend_language()}/styles.css"
Aug 11 16:11:13 scans gunicorn[44793]:   File "/opt/paperless/src/documents/views.py", line 95, in get_frontend_language
Aug 11 16:11:13 scans gunicorn[44793]:     if hasattr(
Aug 11 16:11:13 scans gunicorn[44793]:   File "/home/nico/.local/lib/python3.9/site-packages/django/utils/functional.py", line 259, in inner
Aug 11 16:11:13 scans gunicorn[44793]:     return func(self._wrapped, *args)
Aug 11 16:11:13 scans gunicorn[44793]:   File "/home/nico/.local/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 450, in __get__
Aug 11 16:11:13 scans gunicorn[44793]:     rel_obj = self.get_queryset(instance=instance).get(**filter_args)
Aug 11 16:11:13 scans gunicorn[44793]:   File "/home/nico/.local/lib/python3.9/site-packages/django/db/models/query.py", line 492, in get
Aug 11 16:11:13 scans gunicorn[44793]:     num = len(clone)
Aug 11 16:11:13 scans gunicorn[44793]:   File "/home/nico/.local/lib/python3.9/site-packages/django/db/models/query.py", line 302, in __len__
Aug 11 16:11:13 scans gunicorn[44793]:     self._fetch_all()
Aug 11 16:11:13 scans gunicorn[44793]:   File "/home/nico/.local/lib/python3.9/site-packages/django/db/models/query.py", line 1507, in _fetch_all
Aug 11 16:11:13 scans gunicorn[44793]:     self._result_cache = list(self._iterable_class(self))
Aug 11 16:11:13 scans gunicorn[44793]:   File "/home/nico/.local/lib/python3.9/site-packages/django/db/models/query.py", line 57, in __iter__
Aug 11 16:11:13 scans gunicorn[44793]:     results = compiler.execute_sql(
Aug 11 16:11:13 scans gunicorn[44793]:   File "/home/nico/.local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1361, in execute_sql
Aug 11 16:11:13 scans gunicorn[44793]:     cursor.execute(sql, params)
Aug 11 16:11:13 scans gunicorn[44793]:   File "/home/nico/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
Aug 11 16:11:13 scans gunicorn[44793]:     return self._execute_with_wrappers(
Aug 11 16:11:13 scans gunicorn[44793]:   File "/home/nico/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
Aug 11 16:11:13 scans gunicorn[44793]:     return executor(sql, params, many, context)
Aug 11 16:11:13 scans gunicorn[44793]:   File "/home/nico/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
Aug 11 16:11:13 scans gunicorn[44793]:     return self.cursor.execute(sql, params)
Aug 11 16:11:13 scans gunicorn[44793]:   File "/home/nico/.local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
Aug 11 16:11:13 scans gunicorn[44793]:     raise dj_exc_value.with_traceback(traceback) from exc_value
Aug 11 16:11:13 scans gunicorn[44793]:   File "/home/nico/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
Aug 11 16:11:13 scans gunicorn[44793]:     return self.cursor.execute(sql, params)
Aug 11 16:11:13 scans gunicorn[44793]:   File "/home/nico/.local/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 477, in execute
Aug 11 16:11:13 scans gunicorn[44793]:     return Database.Cursor.execute(self, query, params)
Aug 11 16:11:13 scans gunicorn[44793]: django.db.utils.OperationalError: no such table: documents_uisettings
```

### Paperless-ngx version

1.8.0

### Host OS

Debian 11.4

### Installation method

Bare metal

### Browser

Firefox

**Comment by shamoon** [comment]
You need to run db migrations

**Comment by shamoon** [comment]
Eg step 3 https://paperless-ngx.readthedocs.io/en/latest/administration.html
