### ISSUE TITLE
[BUG] Error with gmail-Account

### ISSUE THREAD

**Issue by queen4me** [paperless-ngx/paperless-ngx#1471]
### Description

I added my gmail Account in paperless-ngx but I get errors (s. Webserver logs).
Because MFA is in use I generated an App-Password.

### Steps to reproduce

After adding my mail-account johndoe@gmail.com with a rule to process all mails in the inbox I only get errors in the mail.log

Is there a possibility to check the mail-account manually in paperless-ngx?

### Webserver logs

```bash
Error in the mail.log every 10 minutes:

[2022-08-29 18:45:43,906] [DEBUG] [paperless_mail] Processing mail account johndoe@gmail.com
[2022-08-29 18:45:54,069] [ERROR] [paperless_mail] Error while retrieving mailbox johndoe@gmail.com: socket error: EOF
```

### Paperless-ngx version

1.8.0

### Host OS

Docker and Ubuntu

### Installation method

Docker - linuxserver.io image

**Comment by shamoon** [comment]
Please double-check your setup, many people use Gmail, including with app passwords, so Im not sure if theres really a bug here.

Try searching the discussions etc for example https://github.com/paperless-ngx/paperless-ngx/discussions/1145

**Comment by queen4me** [comment]
Thanks for your fast reply.
I triple-checked ;-) and my settings are exactly the same as in the mentioned discussion:

IMAP server: imap.gmail.com
IMAP port: 993
Security: SSL
User name: xxx.xxx@gmail.com
Password: ONE TIME PASSWORD CREATED IN GMAIL (NOT STANDARD PW)
Char set: UTF-8

**Comment by shamoon** [comment]
Yes from the logs auth looks ok but check the rules, especially the folder settings

**Comment by stumpylog** [comment]
`socket error: EOF` is a pretty low level error, almost reading like there's a networking issue at play here.

**Comment by obidose** [comment]
Have you allowed access to 'less secure apps' in gmail?

**Comment by queen4me** [comment]
Looks like access "less secure apps" isn't available in gmail anymore.
So unfortunately I can't unse paperless-ngx for my mails because gmail without MFA is no option for me (and others).

**Comment by stumpylog** [comment]
An exception like `socket error: EOF` indicates the peer (Google in this case) has terminated the connection on their end OR there is a network issue preventing the connection from working.  

From some reading, this is something which sometimes happens, particularly with Gmail accounts ([example](https://stackoverflow.com/questions/7575943/eof-error-in-imaplib)).  If you enable debugging, I suspect you'll see it does connect and begin processing, but then for some unknown reason, Google closes the connection.

**Comment by queen4me** [comment]
How should I enable the required debugging?

**Comment by stumpylog** [comment]
If you set the environment variable `PAPERLESS_DEBUG` to 1, there will be a lot more output to the console logs.  Don't keep this set though.

**Comment by queen4me** [comment]
All right. I'll be back ;-) with the log.

**Comment by queen4me** [comment]
Here is the paperless.log:

[2022-09-01 16:35:39,307] [ERROR] [paperless.mail.tasks] Error while processing mail account john.doe@gmail.com
Traceback (most recent call last):
  File "/app/paperless/src/paperless_mail/mail.py", line 180, in handle_mail_account
    M.login(account.username, account.password)
  File "/usr/local/lib/python3.8/dist-packages/imap_tools/mailbox.py", line 65, in login
    check_command_status(login_result, MailboxLoginError)
  File "/usr/local/lib/python3.8/dist-packages/imap_tools/utils.py", line 46, in check_command_status
    raise exception(command_result=command_result, expected=expected)
imap_tools.errors.MailboxLoginError: Response status "OK" expected, but "NO" received. Data: [b'[AUTHENTICATIONFAILED] Invalid credentials (Failure)']
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/app/paperless/src/paperless_mail/tasks.py", line 15, in process_mail_accounts
    total_new_documents += MailAccountHandler().handle_mail_account(account)
  File "/app/paperless/src/paperless_mail/mail.py", line 212, in handle_mail_account
    raise MailError(
paperless_mail.mail.MailError: Error while authenticating account john.doe@gmail.com

and the mail.log:

[2022-09-01 16:35:37,690] [DEBUG] [paperless_mail] Processing mail account john.doe@gmail.com
[2022-09-01 16:35:39,284] [ERROR] [paperless_mail] Error while authenticating account john.doe@gmail.com: Response status "OK" expected, but "NO" received. Data: [b'[AUTHENTICATIONFAILED] Invalid credentials (Failure)']

**Comment by stumpylog** [comment]
That appears to be a different error than the above.  In this case, the authentication has failed, so your password or application specific password is at issue.

**Comment by shamoon** [comment]
That seems reasonable. It's "app passwords" you want. I just tried my own and it works just fine. I still see no Paperless bug here so I'll convert this to a discussion, please let us know if theres a true bug.
