### ISSUE TITLE
[BUG] Services fail to start after upgrade of Python to 3.10.6 on Debian

### ISSUE THREAD

**Issue by nomad-999** [paperless-ngx/paperless-ngx#1475]
### Description

A working installation of Paperless-ngx 1.8 stopped working after the system upgraded Python from 3.9 to 3.10.6

```
`sudo systemctl status paperless-webserver.service 
× paperless-webserver.service - Paperless webserver
     Loaded: loaded (/etc/systemd/system/paperless-webserver.service; enabled; preset: enabled)
     Active: failed (Result: start-limit-hit) since Tue 2022-08-30 07:41:23 CEST; 7min ago
   Duration: 212ms
    Process: 13331 ExecStart=/opt/paperless/.local/bin/gunicorn -c /opt/paperless/gunicorn.conf.py paperless.asgi:application (code=killed, signal=TERM)
   Main PID: 13331 (code=killed, signal=TERM)
        CPU: 213ms

Aug 30 07:41:23 nadia systemd[1]: Started Paperless webserver.
Aug 30 07:41:23 nadia systemd[1]: Stopping Paperless webserver...
Aug 30 07:41:23 nadia systemd[1]: paperless-webserver.service: Deactivated successfully.
Aug 30 07:41:23 nadia systemd[1]: Stopped Paperless webserver.
Aug 30 07:41:23 nadia systemd[1]: paperless-webserver.service: Start request repeated too quickly.
Aug 30 07:41:23 nadia systemd[1]: paperless-webserver.service: Failed with result 'start-limit-hit'.
Aug 30 07:41:23 nadia systemd[1]: Failed to start Paperless webserver.`
```

When I try to run (and I am not sure if it's a valid way to start the service manually) the exec line from above as 

`sudo /opt/paperless/.local/bin/gunicorn -c /opt/paperless/gunicorn.conf.py paperless.asgi:application`

I get the following error

```
sudo -u paperless /opt/paperless/.local/bin/gunicorn -c /opt/paperless/gunicorn.conf.py paperless.asgi:application

Error: class uri 'paperless.workers.ConfigurableWorker' invalid or not found: 

[Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/util.py", line 99, in load_class
    mod = importlib.import_module('.'.join(components))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'paperless'
```

### Steps to reproduce

1. Using official Debian packages, upgrade Python from 3.9 to 3.10.6
2. After rebooting the machine, paperless services (webserver, scheduler, consumer) don't start automatically, and attempts to start webserver service manually ends with abovementioned error

### Paperless-ngx version

1.8.0

### Host OS

Debian GNU/Linux bookworm/sid x86_64

### Installation method

Bare metal

### Browser

Firefox

**Comment by efelon** [comment]
Have you tried to execute the installation of the requirements again:
```
cd /opt/paperless
sudo -Hu paperless pip3 install --requirement requirements.txt
```
and maybe also
```
cd /opt/paperless/src
sudo -Hu paperless python3 manage.py migrate
```
_pathes and user to be adjusted_

**Comment by nomad-999** [comment]
Thanks, I tried both now and there were no errors. I can now start the webserver manually using `sudo -Hu paperless /opt/paperless/.local/bin/gunicorn -c /opt/paperless/gunicorn.conf.py paperless.asgi:application` but not using `sudo systemctl start paperless-webserver.service`. The consumer and scheduler services also do not start using systemctl.

**Comment by efelon** [comment]
How did you install paperless (bare metal I suppose)?
What are the errors from systemd now?
And how exactly do your service files look like (`systemctl cat paperless-*`)?

**Comment by nomad-999** [comment]
Yes, it is a bare metal install.
The systemd errors are

Scheduler:
```
sudo systemctl status paperless-scheduler.service 
● paperless-scheduler.service - Paperless scheduler
     Loaded: loaded (/etc/systemd/system/paperless-scheduler.service; enabled; preset: enabled)
     Active: active (running) since Tue 2022-08-30 14:02:56 CEST; 11min ago
   Main PID: 254600 (python3)
      Tasks: 2 (limit: 18873)
     Memory: 57.6M
        CPU: 1.248s
     CGroup: /system.slice/paperless-scheduler.service
             └─254600 python3 manage.py qcluster

Aug 30 14:02:56 nadia python3[254618]:     return self.connection.ping()
Aug 30 14:02:56 nadia python3[254618]:   File "/opt/paperless/.local/lib/python3.10/site-packages/redis/commands/core.py", line 1132, in ping
Aug 30 14:02:56 nadia python3[254618]:     return self.execute_command("PING", **kwargs)
Aug 30 14:02:56 nadia python3[254618]:   File "/opt/paperless/.local/lib/python3.10/site-packages/redis/client.py", line 1235, in execute_command
Aug 30 14:02:56 nadia python3[254618]:     conn = self.connection or pool.get_connection(command_name, **options)
Aug 30 14:02:56 nadia python3[254618]:   File "/opt/paperless/.local/lib/python3.10/site-packages/redis/connection.py", line 1387, in get_connection
Aug 30 14:02:56 nadia python3[254618]:     connection.connect()
Aug 30 14:02:56 nadia python3[254618]:   File "/opt/paperless/.local/lib/python3.10/site-packages/redis/connection.py", line 617, in connect
Aug 30 14:02:56 nadia python3[254618]:     raise ConnectionError(self._error_message(e))
Aug 30 14:02:56 nadia python3[254618]: redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
```
Consumer:
```
sudo systemctl status paperless-consumer.service 
× paperless-consumer.service - Paperless consumer
     Loaded: loaded (/etc/systemd/system/paperless-consumer.service; enabled; preset: enabled)
     Active: failed (Result: start-limit-hit) since Tue 2022-08-30 14:16:46 CEST; 690ms ago
   Duration: 242ms
    Process: 264106 ExecStart=python3 manage.py document_consumer (code=killed, signal=TERM)
   Main PID: 264106 (code=killed, signal=TERM)
        CPU: 241ms

Aug 30 14:16:46 nadia systemd[1]: Started Paperless consumer.
Aug 30 14:16:46 nadia systemd[1]: Stopping Paperless consumer...
Aug 30 14:16:46 nadia systemd[1]: paperless-consumer.service: Deactivated successfully.
Aug 30 14:16:46 nadia systemd[1]: Stopped Paperless consumer.
Aug 30 14:16:46 nadia systemd[1]: paperless-consumer.service: Start request repeated too quickly.
Aug 30 14:16:46 nadia systemd[1]: paperless-consumer.service: Failed with result 'start-limit-hit'.
Aug 30 14:16:46 nadia systemd[1]: Failed to start Paperless consumer.
```
and Webserver:
```
sudo systemctl status paperless-webserver.service 
× paperless-webserver.service - Paperless webserver
     Loaded: loaded (/etc/systemd/system/paperless-webserver.service; enabled; preset: enabled)
     Active: failed (Result: start-limit-hit) since Tue 2022-08-30 14:17:20 CEST; 11s ago
   Duration: 243ms
    Process: 264467 ExecStart=/opt/paperless/.local/bin/gunicorn -c /opt/paperless/gunicorn.conf.py paperless.asgi:application (code=killed, signal=TERM)
   Main PID: 264467 (code=killed, signal=TERM)
        CPU: 244ms

Aug 30 14:17:20 nadia systemd[1]: Started Paperless webserver.
Aug 30 14:17:20 nadia systemd[1]: Stopping Paperless webserver...
Aug 30 14:17:20 nadia systemd[1]: paperless-webserver.service: Deactivated successfully.
Aug 30 14:17:20 nadia systemd[1]: Stopped Paperless webserver.
Aug 30 14:17:20 nadia systemd[1]: paperless-webserver.service: Start request repeated too quickly.
Aug 30 14:17:20 nadia systemd[1]: paperless-webserver.service: Failed with result 'start-limit-hit'.
Aug 30 14:17:20 nadia systemd[1]: Failed to start Paperless webserver
```
The services look like this:
```
systemctl cat paperless-*
# /etc/systemd/system/paperless-consumer.service
[Unit]
Description=Paperless consumer
Requires=redis.service

[Service]
User=paperless
Group=paperless
WorkingDirectory=/opt/paperless/src
ExecStart=python3 manage.py document_consumer

[Install]
WantedBy=multi-user.target

# /etc/systemd/system/paperless-scheduler.service
[Unit]
Description=Paperless scheduler
Requires=redis.service

[Service]
User=paperless
Group=paperless
WorkingDirectory=/opt/paperless/src
ExecStart=python3 manage.py qcluster

[Install]
WantedBy=multi-user.target

# /etc/systemd/system/paperless-webserver.service
[Unit]
Description=Paperless webserver
After=network.target
Wants=network.target
Requires=redis.service
#Requires=paperless-webserver.socket

[Service]
User=paperless
Group=paperless
WorkingDirectory=/opt/paperless/src
ExecStart=/opt/paperless/.local/bin/gunicorn -c /opt/paperless/gunicorn.conf.py paperless.asgi:application

[Install]
WantedBy=multi-user.target
```
Redis seems to be down as well:
```
sudo systemctl status redis-server.service
× redis-server.service - Advanced key-value store
     Loaded: loaded (/lib/systemd/system/redis-server.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Tue 2022-08-30 14:20:38 CEST; 14s ago
       Docs: http://redis.io/documentation,
             man:redis-server(1)
    Process: 266601 ExecStart=/usr/bin/redis-server /etc/redis/redis.conf --supervised systemd --daemonize no (code=exited, status=127)
   Main PID: 266601 (code=exited, status=127)
        CPU: 84ms

Aug 30 14:20:38 nadia systemd[1]: redis-server.service: Scheduled restart job, restart counter is at 5.
Aug 30 14:20:38 nadia systemd[1]: Stopped Advanced key-value store.
Aug 30 14:20:38 nadia systemd[1]: redis-server.service: Start request repeated too quickly.
Aug 30 14:20:38 nadia systemd[1]: redis-server.service: Failed with result 'exit-code'.
Aug 30 14:20:38 nadia systemd[1]: Failed to start Advanced key-value store
```

**Comment by efelon** [comment]
> `Aug 30 14:02:56 nadia python3[254618]: redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.`

This points to redis being down, what you already found out yourself.

> `...: Start request repeated too quickly.`

You may look into it yourself a bit, as it may have multiple causes. Why your services restart so quickly is unclear to me. Since also redis shows the same error indicates that something is wrong with your system.

I would first try to reboot the system if possible. If that doesn't help:
1. stop and maybe even disable all paperless services
2. wait a minute
3. `systemctl daemon-reload`
4. try to get redis-server.service started first
5. and then one by one the paperless- services

I'm out of advice here. Maybe someone else can step in if you're still facing the problem. I think that it has nothing to do with paperless at this point.

**Comment by stumpylog** [comment]
If `journalctl` doesn't go back far enough to see what is actually failing in the service, the `paperless.log` file might include more information.
