### ISSUE TITLE
[BUG] Concise description of the issue

### ISSUE THREAD

**Issue by Totil-a** [paperless-ngx/paperless-ngx#1595]
### Description

Installed the docker container and finished the install with success on my raspberry 
Website opens
Login works
But as soon as I upload a file, I get an Internal Server error 500

### Steps to reproduce

Open paperless website
Login
Upload a file

### Webserver logs

```bash
22:06:41 [Q] INFO Enqueued 1
22:06:41 [Q] INFO Process-1 created a task from schedule [Check all e-mail accounts]
22:06:41 [Q] INFO Process-1:148 processing [juliet-crazy-artist-washington]
22:06:42 [Q] INFO Process-1:148 stopped doing work
22:06:42 [Q] INFO Processed [juliet-crazy-artist-washington]
22:06:46 [Q] INFO recycled worker Process-1:148
22:06:46 [Q] INFO Process-1:149 ready for work at 22564
[2022-09-14 22:07:39,372] [ERROR] [django.request] Internal Server Error: /api/documents/post_document/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
  File "/usr/local/lib/python3.9/site-packages/asgiref/current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/src/paperless/src/documents/views.py", line 539, in post
    os.utime(f.name, times=(t, t))
PermissionError: [Errno 1] Operation not permitted
```

### Paperless-ngx version

1.8.0

### Host OS

Raspberry Pi 3b

### Installation method

Docker - official image

### Browser

Chrome

**Comment by stumpylog** [comment]
It's highly likely you need to set the USERMAP_UID and USERMAP_GID so the permissions are correct.  Are you overriding PAPERLESS_SCRATCH_DIR?
