### ISSUE TITLE
[BUG] Text encoding issue when using the MariaDB backend

### ISSUE THREAD

**Issue by Venem** [paperless-ngx/paperless-ngx#1668]
### Description

Certain documents return errors depending on their content when scanned. I believe that this is because of certain equation-like expressions within the document.

This does not occur when using the SQLite backend. I have yet to test PostgreSQL.

### Steps to reproduce

The following is an example of such a document:
https://www.ukmt.org.uk/sites/default/files/ukmt/SMC_2021_paper.pdf

Import the document when using the mariadb backend.

### Webserver logs

```bash
SMC_2021_paper.pdf: The following error occurred while consuming SMC_2021_paper.pdf: (1366, "Incorrect string value: '\\xF0\\x9D\\x91\\xA5\\xC2\\xB0...' for column `paperless`.`documents_document`.`content` at row 1") : Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 320, in _query
    self._do_get_result(db)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 145, in _do_get_result
    self._result = result = self._get_result()
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 352, in _get_result
    return self._get_db().store_result()
MySQLdb.OperationalError: (1366, "Incorrect string value: '\\xF0\\x9D\\x91\\xA5\\xC2\\xB0...' for column `paperless`.`documents_document`.`content` at row 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 280, in main_wrap
    raise exc_info[1]
  File "/usr/src/paperless/src/documents/consumer.py", line 361, in try_consume_file
    document = self._store(text=text, date=date, mime_type=mime_type)
  File "/usr/src/paperless/src/documents/consumer.py", line 471, in _store
    document = Document.objects.create(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 514, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 806, in save
    self.save_base(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 857, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 1000, in _save_table
    results = self._do_insert(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 1041, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1621, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 320, in _query
    self._do_get_result(db)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 145, in _do_get_result
    self._result = result = self._get_result()
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 352, in _get_result
    return self._get_db().store_result()
django.db.utils.OperationalError: (1366, "Incorrect string value: '\\xF0\\x9D\\x91\\xA5\\xC2\\xB0...' for column `paperless`.`documents_document`.`content` at row 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/paperless/src/src/django-q/django_q/cluster.py", line 454, in worker
    res = f(*task["args"], **task["kwargs"])
  File "/usr/src/paperless/src/documents/tasks.py", line 154, in consume_file
    document = Consumer().try_consume_file(
  File "/usr/src/paperless/src/documents/consumer.py", line 423, in try_consume_file
    self._fail(
  File "/usr/src/paperless/src/documents/consumer.py", line 90, in _fail
    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
documents.consumer.ConsumerError: SMC_2021_paper.pdf: The following error occurred while consuming SMC_2021_paper.pdf: (1366, "Incorrect string value: '\\xF0\\x9D\\x91\\xA5\\xC2\\xB0...' for column `paperless`.`documents_document`.`content` at row 1")
```

### Paperless-ngx version

1.9

### Host OS

Alpine Linux

### Installation method

Docker - official image

### Other

This should be a relatively easy fix, hopefully just a swap of the encoding type when using mariadb, however I am not experienced enough with SQL to resolve this on my own.

**Comment by stumpylog** [comment]
It doesn't seem as simple as setting the charset to `utf8mb4`, which is the usual suggested fix I find.

**Comment by Venem** [comment]
I did try changing the charset to various different options for the table but it seems like it's an issue with how paperless deals with it rather than with how it's stored.

I'll try and have a look through the code that deals with mariadb

**Comment by stumpylog** [comment]
The direct interfacing to a DB is handled by Django.  This is probably something in `src\paperless_tesseract\parsers.py`

**Comment by Venem** [comment]
If the issue is in that file, theoretically disabling OCR should temporarily resolve this.

I'll give that a shot

**Comment by Venem** [comment]
Setting `PAPERLESS_OCR_MODE=skip` in `docker-compose.yml` did not work.

<details>
<summary>
Logs:
</summary>

```
SMC_2021_paper.pdf: The following error occurred while consuming SMC_2021_paper.pdf: (1366, "Incorrect string value: '\\xF0\\x9D\\x91\\xA5\\xC2\\xB0...' for column `paperless`.`documents_document`.`content` at row 1") : Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 320, in _query
    self._do_get_result(db)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 145, in _do_get_result
    self._result = result = self._get_result()
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 352, in _get_result
    return self._get_db().store_result()
MySQLdb.OperationalError: (1366, "Incorrect string value: '\\xF0\\x9D\\x91\\xA5\\xC2\\xB0...' for column `paperless`.`documents_document`.`content` at row 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 280, in main_wrap
    raise exc_info[1]
  File "/usr/src/paperless/src/documents/consumer.py", line 361, in try_consume_file
    document = self._store(text=text, date=date, mime_type=mime_type)
  File "/usr/src/paperless/src/documents/consumer.py", line 471, in _store
    document = Document.objects.create(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 514, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 806, in save
    self.save_base(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 857, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 1000, in _save_table
    results = self._do_insert(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 1041, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1621, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 320, in _query
    self._do_get_result(db)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 145, in _do_get_result
    self._result = result = self._get_result()
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 352, in _get_result
    return self._get_db().store_result()
django.db.utils.OperationalError: (1366, "Incorrect string value: '\\xF0\\x9D\\x91\\xA5\\xC2\\xB0...' for column `paperless`.`documents_document`.`content` at row 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/paperless/src/src/django-q/django_q/cluster.py", line 454, in worker
    res = f(*task["args"], **task["kwargs"])
  File "/usr/src/paperless/src/documents/tasks.py", line 154, in consume_file
    document = Consumer().try_consume_file(
  File "/usr/src/paperless/src/documents/consumer.py", line 423, in try_consume_file
    self._fail(
  File "/usr/src/paperless/src/documents/consumer.py", line 90, in _fail
    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
documents.consumer.ConsumerError: SMC_2021_paper.pdf: The following error occurred while consuming SMC_2021_paper.pdf: (1366, "Incorrect string value: '\\xF0\\x9D\\x91\\xA5\\xC2\\xB0...' for column `paperless`.`documents_document`.`content` at row 1")
```
</summary>

**Comment by stumpylog** [comment]
This is a digital PDF I think?  In that case, the text is directly extracted from the PDF (without OCR) and used.  So there's still content from the PDF trying to go into the DB

**Comment by Venem** [comment]
It seems like it's digital, yes. I'll try and use the `force` option instead of `skip`; from what I understand this should force rasterization of the document.

**Comment by Venem** [comment]
The document was successfully imported with `OCR_MODE` set to `force`. This works for the moment but it has the caveat of it having to be rasteri(z|s)ed which takes up more storage and loses resolution in the text.

**Comment by stumpylog** [comment]
I'm still looking into this.  Neither sqlite nor postgres have any issues with the file.  `\\xF0\\x9D\\x91\\xA5 corresponds to "	MATHEMATICAL ITALIC SMALL X" in unicode, which is a valid 4 byte and should be fine with after setting the `utf8mb4` charset.  It's almost like two (or more) unicode chars are getting smushed together.

**Comment by stumpylog** [comment]
I'm not sure what image I was testing with, but adding the charset did fix this.  With it, I could consume the sample file with no problems.

**Comment by Venem** [comment]
Thanks for solving it!
