### ISSUE TITLE
[BUG] This writer is closed

### ISSUE THREAD

**Issue by rodlord5000** [paperless-ngx/paperless-ngx#1721]
### Description

I'm receiving the error "This writer is closed" when trying to upload new documents to Paperless. This began occurring after the update to 1.9.2. 

![image](https://user-images.githubusercontent.com/114850211/193441970-c6e48c90-459d-443d-8810-a8bf006b041d.png)

### Steps to reproduce

Uploading any new document, regardless of content, file type or file name.

### Webserver logs

```bash
keys.txt: The following error occurred while consuming keys.txt: This writer is closed : Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/index.py", line 72, in open_index_writer
    yield writer
  File "/usr/src/paperless/src/documents/index.py", line 126, in add_or_update_document
    update_document(writer, document)
  File "/usr/src/paperless/src/documents/index.py", line 93, in update_document
    writer.update_document(
  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 1024, in update_document
    self._record("update_document", args, kwargs)
  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 1001, in _record
    getattr(self.writer, method)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 483, in update_document
    with self.searcher() as s:
  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 297, in searcher
    return Searcher(self.reader(), **kwargs)
  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 638, in reader
    return FileIndex._reader(self.storage, self.schema, self.segments,
  File "/usr/local/lib/python3.9/site-packages/whoosh/index.py", line 529, in _reader
    return segreader(segments[0])
  File "/usr/local/lib/python3.9/site-packages/whoosh/index.py", line 523, in segreader
    return SegmentReader(storage, schema, segment,
  File "/usr/local/lib/python3.9/site-packages/whoosh/reading.py", line 610, in __init__
    files = segment.open_compound_file(storage)
  File "/usr/local/lib/python3.9/site-packages/whoosh/codec/base.py", line 570, in open_compound_file
    return CompoundStorage(dbfile, use_mmap=storage.supports_mmap)
  File "/usr/local/lib/python3.9/site-packages/whoosh/filedb/compound.py", line 58, in __init__
    self._diroffset = self._file.read_long()
  File "/usr/local/lib/python3.9/site-packages/whoosh/filedb/structfile.py", line 302, in read_long
    return unpack_long(self.read(_LONG_SIZE))[0]
struct.error: unpack requires a buffer of 8 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 280, in main_wrap
    raise exc_info[1]
  File "/usr/src/paperless/src/documents/consumer.py", line 366, in try_consume_file
    document_consumption_finished.send(
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/usr/src/paperless/src/documents/signals/handlers.py", line 503, in add_to_index
    index.add_or_update_document(document)
  File "/usr/src/paperless/src/documents/index.py", line 126, in add_or_update_document
    update_document(writer, document)
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/src/paperless/src/documents/index.py", line 77, in open_index_writer
    writer.commit(optimize=optimize)
  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 1037, in commit
    self.writer.commit(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 920, in commit
    self._check_state()
  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 555, in _check_state
    raise IndexingError("This writer is closed")
whoosh.writing.IndexingError: This writer is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/paperless/src/src/django-q/django_q/cluster.py", line 454, in worker
    res = f(*task["args"], **task["kwargs"])
  File "/usr/src/paperless/src/documents/tasks.py", line 154, in consume_file
    document = Consumer().try_consume_file(
  File "/usr/src/paperless/src/documents/consumer.py", line 423, in try_consume_file
    self._fail(
  File "/usr/src/paperless/src/documents/consumer.py", line 90, in _fail
    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
documents.consumer.ConsumerError: keys.txt: The following error occurred while consuming keys.txt: This writer is closed
```

### Paperless-ngx version

1.9.2

### Host OS

Debian 11

### Installation method

Docker - official image

### Browser

Chrome

**Comment by shamoon** [comment]
Havent seen that before. Are you getting this with specific files (txt?) or all? I cant reproduce this with a test text file so if its something specific perhaps you can share it here.

**Comment by rodlord5000** [comment]
This is happening for all files I've tried- PDF, txt, DOCX, csv

**Comment by shamoon** [comment]
Well thats pretty suspicious, consumption of all documents is not broken in our current release (see https://demo.paperless-ngx.com ), there must be something specific to your setup here, any configuration changes etc? Just asking, have you tried simple things like restarting / re-creating the container?

**Comment by rodlord5000** [comment]
> Well thats pretty suspicious, consumption of all documents is not broken in our current release (see https://demo.paperless-ngx.com ), there must be something specific to your setup here, any configuration changes etc? Just asking, have you tried simple things like restarting / re-creating the container?

I'll run a backup and try recreating the container again.

**Comment by rodlord5000** [comment]
After a complete wipe and recreation of the image (database and all) it seems to be importing documents OK.

**Comment by shamoon** [comment]
Odd, thanks for the update.
