### ISSUE TITLE
[BUG] Unknown argument X-GM-LABELS error while fetching mails via IMAP

### ISSUE THREAD

**Issue by HaJanDo** [paperless-ngx/paperless-ngx#1753]
### Description

Currently when my paperless-ngx instance tries to fetch mails over IMAP with the option to use tagging enabled, it fails with an error "Unknown argument X-GM-LABELS".
The IMAP mailserver queried is my dovecot (within mailcow-dockerized), which does not know/support "X-GM-LABELS" and therefore returns the error. I also confirmed this by running the query locally on the dovecot - it returned the same error.

This seems to be related to #1433 as it adds the support for gmail accounts and use the "gmail_label" which imap-tools translates to "X-GM-LABELS".

I tried a quick and dirty workaround and removed "gmail_label" for one run from "criterias" and it worked just fine and as expected.

As an idea: maybe it is possible to check the mailbox host ("M._host") for gmail/googlemail as it is done in the post consume (post_consume) and only then use "gmail_label"/"X-GM-LABELS"?

### Steps to reproduce

1. Configure a mail account with a non-gmail mailserver (f.e. dovecot)
2. Create a rule with action "Tag" (5)
3. Let paperless try to fetch mails

### Webserver logs

```bash
[2022-10-06 23:14:56,558] [DEBUG] [paperless_mail] Processing mail account <redacted>
[2022-10-06 23:14:56,673] [DEBUG] [paperless_mail] Account <redacted>: Processing 1 rule(s)
[2022-10-06 23:14:56,676] [DEBUG] [paperless_mail] Rule <redacted>.Catch all: Selecting folder INBOX
[2022-10-06 23:14:56,691] [DEBUG] [paperless_mail] Rule <redacted>.Catch all: Searching folder with criteria (NOT (X-GM-LABELS "Paperless") SINCE 6-Sep-2022 UNKEYWORD Paperless)
[2022-10-06 23:14:56,707] [ERROR] [paperless_mail] Rule <redacted>.Catch all: Error while processing rule: SEARCH command error: BAD [b'Error in IMAP command SEARCH: Unknown argument X-GM-LABELS (0.001 + 0.000 secs).']
Traceback (most recent call last):
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 218, in handle_mail_account
    total_processed_files += self.handle_mail_rule(M, rule)
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 291, in handle_mail_rule
    for message in messages:
  File "/usr/local/lib/python3.9/site-packages/imap_tools/mailbox.py", line 170, in fetch
    nums = tuple((reversed if reverse else iter)(self.numbers(criteria, charset)))[limit_range]
  File "/usr/local/lib/python3.9/site-packages/imap_tools/mailbox.py", line 108, in numbers
    search_result = self.client.search(charset, encoded_criteria)
  File "/usr/local/lib/python3.9/imaplib.py", line 732, in search
    typ, dat = self._simple_command(name, 'CHARSET', charset, *criteria)
  File "/usr/local/lib/python3.9/imaplib.py", line 1230, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/local/lib/python3.9/imaplib.py", line 1055, in _command_complete
    raise self.error('%s command error: %s %s' % (name, typ, data))
imaplib.IMAP4.error: SEARCH command error: BAD [b'Error in IMAP command SEARCH: Unknown argument X-GM-LABELS (0.001 + 0.000 secs).']
```

### Paperless-ngx version

1.9.2

### Host OS

UnraidOS

### Installation method

Docker - official image

**Comment by HaJanDo** [comment]
Quick addition: this was added to imap-tools within https://github.com/ikvk/imap_tools/pull/43 they also discussed, that this is non-standard and gmail specific.
The best would be to check for the imap capability X-GM-EXT-1 [Google dev docu on IMAP extensions](https://developers.google.com/gmail/imap/imap-extensions) and only then use X-GM-LABELS but I do not think imap-tools provides the feature to list the capabilities.

**Comment by stumpylog** [comment]
Thank you, fortunately the imaplib client does allow access to capabilities.  This has been fixed in `dev` now.
