### ISSUE TITLE
[BUG] AttributeError: /MediaBox

### ISSUE THREAD

**Issue by robert-uhl** [paperless-ngx/paperless-ngx#1763]
### Description

Attempting to upload a particular PDF I receive the following error:

```
12345.pdf: Error while consuming document 12345.pdf: AttributeError: /MediaBox : Traceback (most recent call last):
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 277, in parse
    ocrmypdf.ocr(**args)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/api.py", line 340, in ocr
    return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 377, in run_pipeline
    pdfinfo = get_pdfinfo(
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 162, in get_pdfinfo
    return PdfInfo(
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 943, in __init__
    self._pages = _pdf_pageinfo_concurrent(
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 720, in _pdf_pageinfo_concurrent
    executor(
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_concurrent.py", line 87, in __call__
    self._execute(
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/builtin_plugins/concurrency.py", line 141, in _execute
    result = future.result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 677, in _pdf_pageinfo_sync
    page = PageInfo(pdf, pageno, infile, check_pages, detailed_analysis)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 757, in __init__
    self._gather_pageinfo(pdf, pageno, infile, check_pages, detailed_analysis)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 768, in _gather_pageinfo
    mediabox = [Decimal(d) for d in page.MediaBox.as_list()]
  File "/usr/local/lib/python3.9/site-packages/pikepdf/_methods.py", line 1105, in __getattr__
    return getattr(self.obj, name)
AttributeError: /MediaBox

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 280, in main_wrap
    raise exc_info[1]
  File "/usr/src/paperless/src/documents/consumer.py", line 320, in try_consume_file
    document_parser.parse(self.path, mime_type, self.filename)
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 333, in parse
    raise ParseError(f"{e.__class__.__name__}: {str(e)}") from e
documents.parsers.ParseError: AttributeError: /MediaBox

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/paperless/src/src/django-q/django_q/cluster.py", line 454, in worker
    res = f(*task["args"], **task["kwargs"])
  File "/usr/src/paperless/src/documents/tasks.py", line 154, in consume_file
    document = Consumer().try_consume_file(
  File "/usr/src/paperless/src/documents/consumer.py", line 339, in try_consume_file
    self._fail(
  File "/usr/src/paperless/src/documents/consumer.py", line 90, in _fail
    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
documents.consumer.ConsumerError: 12345.pdf: Error while consuming document 12345.pdf: AttributeError: /MediaBox
```

### Steps to reproduce

1. Open Paperless-ngx web UI.
2. Go to Dashboard.
3. Browse files.
4. Select PDF.
5. See error.

### Paperless-ngx version

1.9.2

### Host OS

Debian 11 x86_64

### Installation method

Docker - official image

**Comment by shamoon** [comment]
If you are able to provide the PDF it would be helpful, without we cant reproduce this. But if being involved with this project has taught me anything its that many, many PDFs are malformed. At first blush, I'd guess thats what this is (partly since we havent seen this one before). Have you tried re-generating the PDF somehow?

**Comment by stumpylog** [comment]
Seeing as that comes out of ocrmypdf, likely little to nothing we can fix about it.  I'd suggest trying to clean it with qpdf, ie: `qpdf infile.pdf outfile.pdf`

**Comment by robert-uhl** [comment]
Unfortunately the `qpdf` trick didn’t work. What _did_ work, though, was opening it and then printing to a PDF file. I suppose that I shouldn’t be so surprised that there are so many malformed PDFs!
