### ISSUE TITLE
[BUG] Use MariaDB Protokoll: [ERROR] [paperless.handlers] Creating PaperlessTask failed: (2006, 'MySQL server has gone away')

### ISSUE THREAD

**Issue by matze338** [paperless-ngx/paperless-ngx#1783]
### Description

Since changed my database to MariaDB i got Errors when consuming a document:

> [2022-10-12 13:25:13,360] [ERROR] [paperless.handlers] Creating PaperlessTask failed: (2006, 'MySQL server has gone away')

also in MariaDB i got Errors:

> 2022-10-12 11:25:14 21737 [Warning] Aborted connection 21737 to db: 'paperless' user: 'paperless' host: '172.18.0.10' (Got an error reading communication packets)

With PostgreSQL there was no problems, also with other Applications which use the MariaDB do not have any Problems.
So i think there must be problem between handling the DB on Paperless to MariaDB 

### Steps to reproduce

Change DB-Connection to MariaDB
Import an document

### Webserver logs

```bash
[2022-10-12 10:00:18,062] [DEBUG] [paperless.tasks] Training data unchanged.
[2022-10-12 10:49:51,675] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/Vorvertragliche_Informationen_Vertragscheck_vom_12_10_2022.PDF to the task queue.
[2022-10-12 10:49:51,678] [ERROR] [paperless.handlers] Creating PaperlessTask failed: (2006, 'MySQL server has gone away')
[2022-10-12 10:49:52,686] [INFO] [paperless.consumer] Consuming Vorvertragliche_Informationen_Vertragscheck_vom_12_10_2022.PDF
[2022-10-12 10:49:52,741] [DEBUG] [paperless.consumer] Detected mime type: application/pdf
[2022-10-12 10:49:52,761] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser
[2022-10-12 10:49:52,766] [DEBUG] [paperless.consumer] Parsing Vorvertragliche_Informationen_Vertragscheck_vom_12_10_2022.PDF...
[2022-10-12 10:49:54,047] [DEBUG] [paperless.parsing.tesseract] Extracted text from PDF file /usr/src/paperless/consume/Vorvertragliche_Informationen_Vertragscheck_vom_12_10_2022.PDF
[2022-10-12 10:49:54,591] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/usr/src/paperless/consume/Vorvertragliche_Informationen_Vertragscheck_vom_12_10_2022.PDF'), 'output_file': '/tmp/paperless/paperless-ehlzdcuv/archive.pdf', 'use_threads': True, 'jobs': 4, 'language': 'deu', 'output_type': 'pdfa', 'progress_bar': False, 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': '/tmp/paperless/paperless-ehlzdcuv/sidecar.txt'}
[2022-10-12 10:50:00,141] [DEBUG] [paperless.parsing.tesseract] Incomplete sidecar file: discarding.
[2022-10-12 10:50:01,231] [DEBUG] [paperless.parsing.tesseract] Extracted text from PDF file /tmp/paperless/paperless-ehlzdcuv/archive.pdf
[2022-10-12 10:50:01,232] [DEBUG] [paperless.consumer] Generating thumbnail for Vorvertragliche_Informationen_Vertragscheck_vom_12_10_2022.PDF...
[2022-10-12 10:50:01,237] [DEBUG] [paperless.parsing] Execute: convert -density 300 -scale 500x5000> -alpha remove -strip -auto-orient /tmp/paperless/paperless-ehlzdcuv/archive.pdf[0] /tmp/paperless/paperless-ehlzdcuv/convert.webp
[2022-10-12 10:50:06,355] [DEBUG] [paperless.consumer] Saving record to database
[2022-10-12 10:50:06,356] [DEBUG] [paperless.consumer] Creation date from parse_date: 2022-10-12 00:00:00+02:00
[2022-10-12 10:50:06,577] [INFO] [paperless.handlers] Assigning correspondent Kreissparkasse Kusel to 2022-10-12 Vorvertragliche_Informationen_Vertragscheck_vom_12_10_2022
[2022-10-12 10:50:07,150] [DEBUG] [paperless.consumer] Deleting file /usr/src/paperless/consume/Vorvertragliche_Informationen_Vertragscheck_vom_12_10_2022.PDF
[2022-10-12 10:50:07,294] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-ehlzdcuv
[2022-10-12 10:50:07,295] [INFO] [paperless.consumer] Executing post-consume script /usr/src/paperless/scripts/post-consumption-script.sh
[2022-10-12 10:50:07,564] [INFO] [paperless.consumer] Document 2022-10-12 Kreissparkasse Kusel Vorvertragliche_Informationen_Vertragscheck_vom_12_10_2022 consumption finished
```

### Paperless-ngx version

1.9.2

### Host OS

Synology

### Installation method

Docker - official image

### Browser

Chrome/Windows SMB

**Comment by matze338** [comment]
MariaDB docker-compose.yml:

> version: "3"
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.monitor-only=true"      
    environment:
      - "MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}"
      - "MARIADB_AUTO_UPGRADE=true"
    volumes:
      - "/volume1/docker/mariadb/files:/var/lib/mysql:rw"
    ports:
      - 0.0.0.0:3306:3306/tcp
    networks:
      bridge_self:
networks:
  bridge_self:
    name: docker_bridge
    external: true

Paperless docker-compose.yml:

> ...
  paperless:
    image: paperlessngx/paperless-ngx:latest
    container_name: paperless
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - redis
      - tika
    ports:
      - 0.0.0.0:8085:8000/tcp
    volumes:
      - "/volume1/docker/paperless/files/data:/usr/src/paperless/data:rw"
      - "/volume1/docker/paperless/files/export:/usr/src/paperless/export:rw"
      - "/volume1/docker/paperless/scripts:/usr/src/paperless/scripts:rw"
      - "${FOLDER_DOCUMENTS}:/usr/src/paperless/media/documents:rw"
      - "${FOLDER_CONSUME}:/usr/src/paperless/consume:rw"
    environment:
      - "USERMAP_UID=${UID}"
      - "USERMAP_GID=${GID}"
      - "PAPERLESS_SECRET_KEY=${PAPERLESS_SECRET_KEY}"
      - "PAPERLESS_TIME_ZONE=Europe/Berlin"
      - "PAPERLESS_ENABLE_UPDATE_CHECK=true"
      - "PAPERLESS_ADMIN_USER=${PAPERLESS_ADMIN_USER}"
      - "PAPERLESS_ADMIN_PASSWORD=${PAPERLESS_ADMIN_PASSWORD}"
      - "PAPERLESS_ADMIN_MAIL=${PAPERLESS_ADMIN_MAIL}"
      - "PAPERLESS_URL=${PAPERLESS_URL}"
      - "PAPERLESS_CONSUMER_RECURSIVE=true"
      - "PAPERLESS_CONSUMER_DELETE_DUPLICATES=true"
      - "PAPERLESS_OPTIMIZE_THUMBNAILS=true"
      - "PAPERLESS_IGNORE_DATES=${PAPERLESS_IGNORE_DATES}"
      - "PAPERLESS_OCR_LANGUAGES=eng deu"
      - "PAPERLESS_OCR_LANGUAGE=deu"
      - "PAPERLESS_POST_CONSUME_SCRIPT=/usr/src/paperless/scripts/post-consumption-script.sh"
      - "PAPERLESS_FILENAME_FORMAT={correspondent}/{created_year}/{document_type}/{created} - {title}"
      - "PAPERLESS_FILENAME_FORMAT_REMOVE_NONE=true"
      - "PAPERLESS_DBENGINE=${DB_ENGINE}"
      - "PAPERLESS_DBHOST=${DB_HOST}"
      - "PAPERLESS_DBPORT=${DB_PORT}"
      - "PAPERLESS_DBNAME=${DB_NAME}"
      - "PAPERLESS_DBUSER=${DB_USER}"
      - "PAPERLESS_DBPASS=${DB_PASSWORD}"
      - "PAPERLESS_REDIS=redis://redis:6379"
      - "PAPERLESS_TIKA_ENABLED=1"
      - "PAPERLESS_TIKA_GOTENBERG_ENDPOINT=http://gotenberg:3000/forms/libreoffice/convert#"
      - "PAPERLESS_TIKA_ENDPOINT=http://tika:9998"
    networks:
      bridge_self:
      paperless_net:
networks:
  paperless_net:
    name: paperless_net
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: "172.19.0.0/16"
        - subnet: "fe80::/64"
  bridge_self:
    name: docker_bridge
    external: true

**Comment by shamoon** [comment]
Thanks for the report. The current way that tasks are passed to the frontend is going to be completely overhauled in our next release so this isnt something we'll be able to work on in the meantime. But of course our hope is that the upcoming changes will improve things (not just issues like this).

One thing I will say is that 'MySQL server has gone away' is potentially an issue with the db container rather than Paperless, perhaps the db was under load (from other things?) etc.

Thanks for your understanding

**Comment by roest01** [comment]
I can confirm this bug on 26.11.22. The mysql is not under load. 

```javascript
[2022-11-26 22:25:59,427] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: /usr/src/paperless/consume

[2022-11-26 22:32:06,675] [ERROR] [paperless.management.consumer] Error creating tags from path

Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute

    return self.cursor.execute(sql, params)

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute

    return self.cursor.execute(query, args)

  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute

    res = self._query(query)

  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query

    db.query(q)

  File "/usr/local/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query

    _mysql.connection.query(self, query)

MySQLdb.OperationalError: (2013, 'Lost connection to MySQL server during query')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 89, in _consume

    tag_ids = _tags_from_path(filepath)

  File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 39, in _tags_from_path

    Tag.objects.get_or_create(name__iexact=part, defaults={"name": part})[0].pk,

  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method

    return getattr(self.get_queryset(), name)(*args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 657, in get_or_create

    return self.get(**kwargs), False

  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 492, in get

    num = len(clone)

  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 302, in __len__

    self._fetch_all()

  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1507, in _fetch_all

    self._result_cache = list(self._iterable_class(self))

  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 57, in __iter__

    results = compiler.execute_sql(

  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1361, in execute_sql

    cursor.execute(sql, params)

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute

    return self._execute_with_wrappers(

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers

    return executor(sql, params, many, context)

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute

    return self.cursor.execute(sql, params)

  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__

    raise dj_exc_value.with_traceback(traceback) from exc_value

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute

    return self.cursor.execute(sql, params)

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute

    return self.cursor.execute(query, args)

  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute

    res = self._query(query)

  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query

    db.query(q)

  File "/usr/local/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query

    _mysql.connection.query(self, query)

django.db.utils.OperationalError: (2013, 'Lost connection to MySQL server during query')

[2022-11-26 22:32:06,681] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/Briefpost/scan-11-26-11-2022_21-51-13.pdf to the task queue.

[2022-11-26 22:32:06,686] [ERROR] [paperless.handlers] Creating PaperlessTask failed: (2006, 'MySQL server has gone away')

[2022-11-26 22:42:54,545] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/scan-11-26-11-2022_21-51-13.pdf to the task queue.

[2022-11-26 22:42:54,549] [ERROR] [paperless.handlers] Creating PaperlessTask failed: (2006, 'MySQL server has gone away')

[2022-11-26 22:43:26,680] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/scan_123123123123.pdf to the task queue.

[2022-11-26 22:43:26,684] [ERROR] [paperless.handlers] Creating PaperlessTask failed: (2006, 'MySQL server has gone away')
```

**Comment by matze338** [comment]
Also in Paperless 1.10.0 there is still the messages in MariaDB.
`[Warning] Aborted connection 21737 to db: 'paperless' user: 'paperless' host: '172.18.0.10' (Got an error reading communication packets)`

I read something about that the App do not know that the handle to the Database got closed (becasue of timeout) but it still try to use this closed handle instead of open a new connection. https://stackoverflow.com/a/32720475

So i tried the `PAPERLESS_DB_TIMEOUT` Variable but then Paperless went into en error. It seems that this variable also do not work with MariaDB. https://paperless-ngx.readthedocs.io/en/latest/configuration.html#required-services
![image](https://user-images.githubusercontent.com/54413820/204500922-7bf5896e-6290-461a-bcb9-53c6b0665c51.png)

So i guess, i will change back to postgresql.

**Comment by matze338** [comment]
Ok after view days i can see that it seems that i only get an Warning in MariaDB about error in reading communication packets when the Paperless Container is restarting. I guess thats normal.

Currently I also do not get any Error in Paperless log about "MSQL go away".
So i guess its work with Version 1.10.0.

**Comment by virtadpt** [comment]
I'm seeing this as well.  Same error output as @roest01.

Paperless-ngx v1.11.3, MariaDB v10.9.3.  Bare metal install.  MariaDB is also not under load.

Restarting the consumer subprocess seems to fix it for a while.

**Comment by matze338** [comment]
I guess i figured out what the problem is. Currently i use postgresql for paperless but:
Lately I have had a similar Problem with an other Docker Container.
Do you use ipv6 in on your Docker networks? In my case in etc/resolv.conf on the docker process the resolver for ipv6 was wrong.

My docker server did not share the correct ipv6 DNS-Server to the docker process, so that's the reason why the docker internal name cannot be resolved to an valid IP address when the paperless container try to resolve the address "mariadb" over ipv6.
So I had to disable ipv6 for my docker networks and all is working as expect.

**Comment by virtadpt** [comment]
@matze338 I just checked - I'm not.  MariaDB is listening on IPv4's loopback only (and /run/mysqld/mysqld.sock, which I didn't configure it for, but it should be harmless).

**Comment by sinx86** [comment]
everyday i have to restart webserver container....



`[2023-03-28 10:53:30,751] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/S22C-623032810410.pdf to the task queue.
[2023-03-28 10:53:30,753] [ERROR] [paperless.handlers] Creating PaperlessTask failed: (2006, 'MySQL server has gone away')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (2006, 'MySQL server has gone away')
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/signals/handlers.py", line 548, in before_task_publish_handler
    PaperlessTask.objects.create(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 671, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 812, in save
    self.save_base(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 863, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 1006, in _save_table
    results = self._do_insert(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 1047, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1791, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1660, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (2006, 'MySQL server has gone away')
[2023-03-28 10:53:50,908] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/S22C-623032810420_0001.pdf to the task queue.
[2023-03-28 10:53:50,910] [ERROR] [paperless.handlers] Creating PaperlessTask failed: (2006, 'MySQL server has gone away')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (2006, 'MySQL server has gone away')
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/signals/handlers.py", line 548, in before_task_publish_handler
    PaperlessTask.objects.create(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 671, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 812, in save
    self.save_base(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 863, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 1006, in _save_table
    results = self._do_insert(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 1047, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1791, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1660, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (2006, 'MySQL server has gone away')
[2023-03-28 10:53:51,851] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/S22C-623032810420_0002.pdf to the task queue.
[2023-03-28 10:53:51,853] [ERROR] [paperless.handlers] Creating PaperlessTask failed: (2006, 'MySQL server has gone away')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (2006, 'MySQL server has gone away')
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/signals/handlers.py", line 548, in before_task_publish_handler
    PaperlessTask.objects.create(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 671, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 812, in save
    self.save_base(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 863, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 1006, in _save_table
    results = self._do_insert(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 1047, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1791, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1660, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (2006, 'MySQL server has gone away')`

**Comment by sinx86** [comment]
and then after restart, i have a lot of these

![image](https://user-images.githubusercontent.com/104587728/228205044-479379c6-e8dd-4c1a-bd2d-92efdcf5bf6b.png)
