### ISSUE TITLE
[BUG] Can't connect MariaDB, port 3306 failed: received invalid response to SSL negotiation

### ISSUE THREAD

**Issue by zutewas** [paperless-ngx/paperless-ngx#1825]
### Description

I follow the Bare Metal Route install method and try to create the database schema with

`sudo -Hu paperless python3 manage.py migrate`

After this I get the error:

```
Traceback (most recent call last):
  File "/opt/paperless/.local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 244, in ensure_connection
    self.connect()
  File "/opt/paperless/.local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/paperless/.local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 225, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/paperless/.local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/paperless/.local/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 203, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/opt/paperless/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "nas.intranet" (192.168.1.200), port 3306 failed: received invalid response to SSL negotiation: Y
```

From host where paperless is installed I can access to mariadb successfully.

This is the config part of parentless.conf with db settings

```
PAPERLESS_REDIS=redis://localhost:6379
PAPERLESS_DBENGIN=mariadb
PAPERLESS_DBHOST=nas.intranet
PAPERLESS_DBPORT=3306
PAPERLESS_DBNAME=paperless
PAPERLESS_DBUSER=paperless
PAPERLESS_DBPASS=mypass12!
#PAPERLESS_DBSSLMODE=disable
```

Thanks for help :-)

### Steps to reproduce

Try to connect with MariaDB on a remote host with bare metal installation.

### Paperless-ngx version

1.9.2

### Host OS

Ubuntu 22.04

### Installation method

Bare metal

**Comment by stumpylog** [comment]
Is the remote database using SSL?  Or configured to prefer it?

**Comment by zutewas** [comment]
@stumpylog 
Many thanks for your check. Sorry, my problem is solved. 👍
