### ISSUE TITLE
[BUG] Barcode seperator processing fails with password protected PDFs

### ISSUE THREAD

**Issue by gebrk** [paperless-ngx/paperless-ngx#1850]
### Description

With PAPERLESS_CONSUMER_ENABLE_BARCODES=true uploading a password protected PDF causes the file task to fail. It appears that the barcode separation stage fails with an error rather than skipping the document. The same document imports correctly with the above settings commented out.

Traceback from the failed task:
```python
/tmp/paperless/paperless-upload-0bj7vn9g: invalid password : Traceback (most recent call last):
  File "/usr/src/paperless/src/src/django-q/django_q/cluster.py", line 454, in worker
    res = f(*task["args"], **task["kwargs"])
  File "/usr/src/paperless/src/documents/tasks.py", line 99, in consume_file
    pdf_filepath, separators = barcodes.scan_file_for_separating_barcodes(path)
  File "/usr/src/paperless/src/documents/barcodes.py", line 121, in scan_file_for_separating_barcodes
    pdf = Pdf.open(pdf_filepath)
  File "/usr/local/lib/python3.9/site-packages/pikepdf/_methods.py", line 791, in open
    pdf = Pdf._open(
pikepdf._qpdf.PasswordError: /tmp/paperless/paperless-upload-0bj7vn9g: invalid password
```

### Steps to reproduce

1. Launch paperless with PAPERLESS_CONSUMER_ENABLE_BARCODES=true
2. Upload password protected PDF
3. Check the file tasks menu for failed jobs

### Paperless-ngx version

1.9.2

### Host OS

Fedora Server 36

### Installation method

Other (please describe above)

### Other

Official docker image running under root podman

**Comment by stumpylog** [comment]
This should be fixed by #1745, but if you can provide a sample, it should be quick to confirm.

**Comment by stumpylog** [comment]
You can now configure using the old method for barcodes, which presumably ignores passwords, assuming these files worked in 1.8

**Comment by gebrk** [comment]
I've retested this with the :dev version of the docker container and now get an exception in both pikepdf and pdf2image when the process fails. 
I've created a simple test file (password is "test") as I can't share the actual files I'm using: [protected.pdf](https://github.com/paperless-ngx/paperless-ngx/files/9854267/protected.pdf)

```python

[2022-10-24 18:21:57,070] [INFO] [celery.worker.strategy] Task documents.tasks.consume_file[53689d80-79cb-41ec-ad58-30db27882c7a] received
[2022-10-24 18:21:57,115] [WARNING] [paperless.barcodes] Exception using pikepdf for barcodes, falling back to pdf2image: /tmp/paperless/paperless-upload-8t1qyflc: invalid password
[2022-10-24 18:21:57,149] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[53689d80-79cb-41ec-ad58-30db27882c7a] raised unexpected: PDFPageCountError('Unable to get page count.\nCommand Line Error: Incorrect password\n')
Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/barcodes.py", line 157, in scan_file_for_separating_barcodes
    _pikepdf_barcode_scan(pdf_filepath)
  File "/usr/src/paperless/src/documents/barcodes.py", line 117, in _pikepdf_barcode_scan
    with Pdf.open(pdf_filepath) as pdf:
  File "/usr/local/lib/python3.9/site-packages/pikepdf/_methods.py", line 803, in open
    pdf = Pdf._open(
pikepdf._qpdf.PasswordError: /tmp/paperless/paperless-upload-8t1qyflc: invalid password

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pdf2image/pdf2image.py", line 479, in pdfinfo_from_path
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/paperless/src/documents/tasks.py", line 104, in consume_file
    pdf_filepath, separators = barcodes.scan_file_for_separating_barcodes(path)
  File "/usr/src/paperless/src/documents/barcodes.py", line 166, in scan_file_for_separating_barcodes
    _pdf2image_barcode_scan(pdf_filepath)
  File "/usr/src/paperless/src/documents/barcodes.py", line 137, in _pdf2image_barcode_scan
    pages_from_path = convert_from_path(pdf_filepath, output_folder=path)
  File "/usr/local/lib/python3.9/site-packages/pdf2image/pdf2image.py", line 98, in convert_from_path
    page_count = pdfinfo_from_path(pdf_path, userpw, poppler_path=poppler_path)["Pages"]
  File "/usr/local/lib/python3.9/site-packages/pdf2image/pdf2image.py", line 488, in pdfinfo_from_path
    raise PDFPageCountError(
pdf2image.exceptions.PDFPageCountError: Unable to get page count.
Command Line Error: Incorrect password
```

**Comment by gebrk** [comment]
It looks to me like it would be possible to explicitly capture ```pikepdf.PasswordException``` here: https://github.com/paperless-ngx/paperless-ngx/blob/f8ce6285df44cc580319c370a9d76149012615b1/src/documents/barcodes.py#L158 and then skip trying with pdf2img but would it be better to just pass on a PDF that neither pikepdf or pdf2img can handle (by catching exceptions in the pdf2img code too) rather than failing the import?

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/37a892d4612a6de019efc9144e4b0ce08780cd2c

**Comment by shamoon** [comment]
Hey @gebrk this should be fixed in `dev` now, thanks to stumpylog

```
[2022-10-25 07:00:55,487] [INFO] [celery.worker.strategy] Task documents.tasks.consume_file[6323c631-1f6f-44fb-a49d-093011e19cef] received
[2022-10-25 07:00:55,524] [WARNING] [paperless.barcodes] File is likely password protected, not splitting: /tmp/paperless/paperless-upload-despfquy: invalid password
```

**Comment by gebrk** [comment]
Thanks, I can confirm that works for me with the real documents too.
