### ISSUE TITLE
[BUG] Not sure how to get colorspace

### ISSUE THREAD

**Issue by ItsEcholot** [paperless-ngx/paperless-ngx#1924]
### Description

When importing a document (sadly can't upload it as it contains too much confidential data) the following error is thrown:

```
not sure how to get colorspace:
...
  File "/usr/src/paperless/src/src/django-q/django_q/cluster.py", line 454, in worker
    res = f(*task["args"], **task["kwargs"])
  File "/usr/src/paperless/src/documents/tasks.py", line 99, in consume_file
    pdf_filepath, separators = barcodes.scan_file_for_separating_barcodes(path)
```

### Steps to reproduce

1. Upload file
2. Note error under failed file tasks

### Webserver logs

```bash
not sure how to get colorspace: ['/Indexed', ['/CalRGB', pikepdf.Dictionary({
  "/Gamma": [ Decimal('2.2'), Decimal('2.2'), Decimal('2.2') ],
  "/Matrix": [ Decimal('0.41239'), Decimal('0.21264'), Decimal('0.01933'), Decimal('0.35758'), Decimal('0.71517'), Decimal('0.11919'), Decimal('0.18045'), Decimal('0.07218'), Decimal('0.9504') ],
  "/WhitePoint": [ Decimal('0.95043'), 1, Decimal('1.09') ]
})], 255, b'\xbb\x03\x08\xbc\x07\x13\xbe\x14\x00\xbd\x14\x18\xb8\x19(\xbb\x1c0\xb6#\x1c\xb8%+\xba.6\xba47\xbdAA\xbaLS\xca\x02\t\xca\x05\x15\xcb\x11\x0c\xc8\x13\x19\xd3\x00\x04\xd3\x00\x0c\xd3\x0b\x03\xd4\t\r\xdb\x00\x05\xdb\x01\r\xdd\n\x05\xdc\n\x0c\xd4\x01\x13\xd4\x03\x1a\xd4\n\x14\xd4\n\x1b\xdb\x01\x14\xdc\x02\x1a\xdb\n\x14\xdb\n\x1b\xd5\x11\t\xd7\x13\x1a\xca\x0b$\xca\x16&\xcb\x191\xd4\x03"\xd5\x05)\xd4\x0b"\xd4\x0c+\xde\x02!\xdc\x03*\xdc\x0b!\xdc\x0b*\xda\n1\xd8\x15&\xd9\x1a3\xd9!\x19\xca$+\xc9(6\xca2)\xcb4:\xd7$+\xd7\'7\xd22&\xd74:\xe4\x01\x0c\xe3\x01\x14\xe2\x00\x1a\xe2\t\x14\xe4\t\x1c\xea\x00\x13\xea\x00\x1c\xea\t\x14\xeb\n\x1c\xe4\x11\x1e\xf4\x00\x0b\xf2\x00\x14\xf2\x00\x1b\xf1\n\x14\xf2\t\x1d\xfa\x00\x14\xfa\x00\x1b\xf8\r\x12\xfa\t\x1a\xf2\x10\x1c\xe3\x02"\xe1\x02)\xe3\t!\xe4\x0c*\xeb\x02"\xec\x02)\xea\t#\xed\r+\xe6\n1\xe4\x13\'\xe6\x1c9\xf2\x01"\xf2\x01*\xf3\n$\xf2\x0b*\xfb\x01"\xfc\x02+\xfc\n#\xfc\n+\xfa\x032\xf4\x14)\xf5\x185\xef&\x1f\xe5"*\xe6&7\xe52.\xe84;\xf5\'-\xf7(:\xf16=\xc7,B\xca7E\xd8+B\xd98E\xdb:R\xfa\x1cG\xe8#A\xe76G\xe6;T\xf5)E\xf86H\xf5;S\xd9A9\xc9EF\xc1OW\xc9WM\xccX]\xd8EJ\xd9HT\xdePN\xd8VY\xcb[c\xd8M`\xd9Yc\xdd]s\xd7d\\\xc9bg\xc9mx\xc9vn\xd9fg\xdbhs\xd6sl\xd9wt\xe6FJ\xe4GT\xe3TL\xe6TX\xf6DL\xf8HW\xf7S[\xe8Jc\xe7Ye\xe8Xq\xf7Lb\xf5Yf\xfd\\p\xe6cZ\xe7hh\xe7jt\xe5qj\xe7uw\xf5fi\xf6iv\xf3sm\xf6wy\xd8{\x83\xe8o\x80\xe8{\x84\xf6k\x82\xf8x\x85\xda\x83{\xe7\x85|\xef\x90|\xf2\x8b}\xc6\x83\x88\xc1\x8e\x93\xc4\x96\x99\xdc\x87\x85\xd2\x81\x90\xdb\x91\x86\xdd\x99\x90\xda\xa9\x96\xd5\xb1\x99\xcc\xa5\xab\xcd\xa9\xb3\xda\xad\xb4\xdb\xb6\xa9\xd7\xb3\xbf\xeb\x8b\x8b\xe8\x8b\x92\xe9\x94\x8b\xeb\x95\x94\xf6\x86\x89\xf8\x88\x92\xf9\x95\x8a\xf8\x96\x97\xea\x9a\xa1\xff\x8f\xa3\xf9\x9b\xa4\xeb\xa3\x9b\xe4\xb7\x9d\xf9\xa4\x9b\xf6\xb5\x9b\xea\xa8\xa5\xed\xac\xb4\xe8\xb5\xa8\xee\xbd\xb3\xf6\xaa\xa6\xfc\xab\xb2\xf8\xb3\xaa\xf8\xba\xb4\xda\xb6\xc2\xfc\xbc\xc3\xff\xbf\xd1\xdb\xc8\xaa\xdd\xc1\xbd\xe8\xc5\xaf\xea\xc6\xb8\xe9\xd2\xbb\xf5\xc1\xad\xfb\xc5\xba\xf4\xd2\xaf\xf8\xd3\xbc\xd7\xc5\xcc\xda\xc2\xd8\xda\xd3\xc2\xd6\xe6\xcb\xcb\xff\xff\xdc\xea\xea\xda\xf9\xe9\xdb\xfe\xf7\xea\xcb\xc9\xea\xcb\xd7\xea\xd6\xc7\xeb\xd6\xd5\xf8\xc7\xc9\xfd\xcb\xd3\xfa\xd6\xc8\xf9\xd9\xd3\xef\xdc\xe2\xfb\xdc\xe3\xff\xde\xfa\xea\xe2\xc7\xea\xe7\xd5\xeb\xf8\xdb\xf9\xe2\xca\xf9\xe8\xdb\xf9\xf4\xdb\xe9\xe9\xe9\xeb\xee\xf2\xe9\xfb\xeb\xea\xfd\xf9\xfd\xea\xe5\xfd\xec\xf8\xfc\xf7\xea\xfe\xfe\xfe\x00\x00\x00\x00\x00\x00\x00\x00\x00'] : Traceback (most recent call last):
  File "/usr/src/paperless/src/src/django-q/django_q/cluster.py", line 454, in worker
    res = f(*task["args"], **task["kwargs"])
  File "/usr/src/paperless/src/documents/tasks.py", line 99, in consume_file
    pdf_filepath, separators = barcodes.scan_file_for_separating_barcodes(path)
  File "/usr/src/paperless/src/documents/barcodes.py", line 126, in scan_file_for_separating_barcodes
    pillow_img = pdfimage.as_pil_image()
  File "/usr/local/lib/python3.9/site-packages/pikepdf/models/image.py", line 742, in as_pil_image
    im = self._extract_transcoded()
  File "/usr/local/lib/python3.9/site-packages/pikepdf/models/image.py", line 623, in _extract_transcoded
    im = self._extract_transcoded_1248bits()
  File "/usr/local/lib/python3.9/site-packages/pikepdf/models/image.py", line 568, in _extract_transcoded_1248bits
    if self.mode == 'P' and self.palette is not None:
  File "/usr/local/lib/python3.9/site-packages/pikepdf/models/image.py", line 331, in palette
    if self.icc or self.is_device_n or self.is_separation:
  File "/usr/local/lib/python3.9/site-packages/pikepdf/models/image.py", line 493, in icc
    if self.colorspace not in ('/ICCBased', '/Indexed'):
  File "/usr/local/lib/python3.9/site-packages/pikepdf/models/image.py", line 198, in colorspace
    raise NotImplementedError(
NotImplementedError: not sure how to get colorspace: ['/Indexed', ['/CalRGB', pikepdf.Dictionary({
  "/Gamma": [ Decimal('2.2'), Decimal('2.2'), Decimal('2.2') ],
  "/Matrix": [ Decimal('0.41239'), Decimal('0.21264'), Decimal('0.01933'), Decimal('0.35758'), Decimal('0.71517'), Decimal('0.11919'), Decimal('0.18045'), Decimal('0.07218'), Decimal('0.9504') ],
  "/WhitePoint": [ Decimal('0.95043'), 1, Decimal('1.09') ]
})], 255, b'\xbb\x03\x08\xbc\x07\x13\xbe\x14\x00\xbd\x14\x18\xb8\x19(\xbb\x1c0\xb6#\x1c\xb8%+\xba.6\xba47\xbdAA\xbaLS\xca\x02\t\xca\x05\x15\xcb\x11\x0c\xc8\x13\x19\xd3\x00\x04\xd3\x00\x0c\xd3\x0b\x03\xd4\t\r\xdb\x00\x05\xdb\x01\r\xdd\n\x05\xdc\n\x0c\xd4\x01\x13\xd4\x03\x1a\xd4\n\x14\xd4\n\x1b\xdb\x01\x14\xdc\x02\x1a\xdb\n\x14\xdb\n\x1b\xd5\x11\t\xd7\x13\x1a\xca\x0b$\xca\x16&\xcb\x191\xd4\x03"\xd5\x05)\xd4\x0b"\xd4\x0c+\xde\x02!\xdc\x03*\xdc\x0b!\xdc\x0b*\xda\n1\xd8\x15&\xd9\x1a3\xd9!\x19\xca$+\xc9(6\xca2)\xcb4:\xd7$+\xd7\'7\xd22&\xd74:\xe4\x01\x0c\xe3\x01\x14\xe2\x00\x1a\xe2\t\x14\xe4\t\x1c\xea\x00\x13\xea\x00\x1c\xea\t\x14\xeb\n\x1c\xe4\x11\x1e\xf4\x00\x0b\xf2\x00\x14\xf2\x00\x1b\xf1\n\x14\xf2\t\x1d\xfa\x00\x14\xfa\x00\x1b\xf8\r\x12\xfa\t\x1a\xf2\x10\x1c\xe3\x02"\xe1\x02)\xe3\t!\xe4\x0c*\xeb\x02"\xec\x02)\xea\t#\xed\r+\xe6\n1\xe4\x13\'\xe6\x1c9\xf2\x01"\xf2\x01*\xf3\n$\xf2\x0b*\xfb\x01"\xfc\x02+\xfc\n#\xfc\n+\xfa\x032\xf4\x14)\xf5\x185\xef&\x1f\xe5"*\xe6&7\xe52.\xe84;\xf5\'-\xf7(:\xf16=\xc7,B\xca7E\xd8+B\xd98E\xdb:R\xfa\x1cG\xe8#A\xe76G\xe6;T\xf5)E\xf86H\xf5;S\xd9A9\xc9EF\xc1OW\xc9WM\xccX]\xd8EJ\xd9HT\xdePN\xd8VY\xcb[c\xd8M`\xd9Yc\xdd]s\xd7d\\\xc9bg\xc9mx\xc9vn\xd9fg\xdbhs\xd6sl\xd9wt\xe6FJ\xe4GT\xe3TL\xe6TX\xf6DL\xf8HW\xf7S[\xe8Jc\xe7Ye\xe8Xq\xf7Lb\xf5Yf\xfd\\p\xe6cZ\xe7hh\xe7jt\xe5qj\xe7uw\xf5fi\xf6iv\xf3sm\xf6wy\xd8{\x83\xe8o\x80\xe8{\x84\xf6k\x82\xf8x\x85\xda\x83{\xe7\x85|\xef\x90|\xf2\x8b}\xc6\x83\x88\xc1\x8e\x93\xc4\x96\x99\xdc\x87\x85\xd2\x81\x90\xdb\x91\x86\xdd\x99\x90\xda\xa9\x96\xd5\xb1\x99\xcc\xa5\xab\xcd\xa9\xb3\xda\xad\xb4\xdb\xb6\xa9\xd7\xb3\xbf\xeb\x8b\x8b\xe8\x8b\x92\xe9\x94\x8b\xeb\x95\x94\xf6\x86\x89\xf8\x88\x92\xf9\x95\x8a\xf8\x96\x97\xea\x9a\xa1\xff\x8f\xa3\xf9\x9b\xa4\xeb\xa3\x9b\xe4\xb7\x9d\xf9\xa4\x9b\xf6\xb5\x9b\xea\xa8\xa5\xed\xac\xb4\xe8\xb5\xa8\xee\xbd\xb3\xf6\xaa\xa6\xfc\xab\xb2\xf8\xb3\xaa\xf8\xba\xb4\xda\xb6\xc2\xfc\xbc\xc3\xff\xbf\xd1\xdb\xc8\xaa\xdd\xc1\xbd\xe8\xc5\xaf\xea\xc6\xb8\xe9\xd2\xbb\xf5\xc1\xad\xfb\xc5\xba\xf4\xd2\xaf\xf8\xd3\xbc\xd7\xc5\xcc\xda\xc2\xd8\xda\xd3\xc2\xd6\xe6\xcb\xcb\xff\xff\xdc\xea\xea\xda\xf9\xe9\xdb\xfe\xf7\xea\xcb\xc9\xea\xcb\xd7\xea\xd6\xc7\xeb\xd6\xd5\xf8\xc7\xc9\xfd\xcb\xd3\xfa\xd6\xc8\xf9\xd9\xd3\xef\xdc\xe2\xfb\xdc\xe3\xff\xde\xfa\xea\xe2\xc7\xea\xe7\xd5\xeb\xf8\xdb\xf9\xe2\xca\xf9\xe8\xdb\xf9\xf4\xdb\xe9\xe9\xe9\xeb\xee\xf2\xe9\xfb\xeb\xea\xfd\xf9\xfd\xea\xe5\xfd\xec\xf8\xfc\xf7\xea\xfe\xfe\xfe\x00\x00\x00\x00\x00\x00\x00\x00\x00']
```

### Paperless-ngx version

1.9.2

### Host OS

Docker

### Installation method

Docker - official image

**Comment by stumpylog** [comment]
The mix of fixes made in #1858 and #1857 should resolve this kind of issue.  In general terms, it means errors during barcode scanning won't prevent consumption.

Does the PDF contain barcodes to split on?

**Comment by ItsEcholot** [comment]
> Does the PDF contain barcodes to split on?

No it doesn’t contain specific PDF split barcodes and also no other barcodes „normal“ barcodes

**Comment by stumpylog** [comment]
Great.  The file will be consumed with just a warning about this in the next version then.  Hoping to make a `beta` soon (tm).

**Comment by ItsEcholot** [comment]
Is there a reason this can’t be fixed instead of just ignored?

**Comment by stumpylog** [comment]
It's not being ignored?  It's something already fixed in the development version, where this error will no longer result in the file not being consumed.

**Comment by ItsEcholot** [comment]
I mean that the Barcode scanner fails to scan the file. If I understood correctly this error will, when properly handled like it is in dev, lead to files not being scanned for Barcodes?

**Comment by stumpylog** [comment]
A file with an image like this wouldn't get scanned for barcodes.  or at least not all images in the file would be scanned, depending on where the problematic image exists.  If these sorts of files worked in 1.8, there is a setting to utilize the older method for detecting barcodes instead, which generally support the odder image encodings better.

I think that covers the possible cases here for still allowing consumption, and still doing the scanning.

**Comment by ItsEcholot** [comment]
> I think that covers the possible cases here for still allowing consumption, and still doing the scanning.

I agree thanks for your response.
