### ISSUE TITLE
[BUG] Error while processing mail - CELERY

### ISSUE THREAD

**Issue by darkobg79** [paperless-ngx/paperless-ngx#1933]
### Description

I have problem with Dev branch with Celery. When Paperless consume email with attacment, error is occure :

 Error while processing mail 76999: consume_file() got an **unexpected keyword argument 'task_name'**

### Steps to reproduce

1. Create mail rule
2. Error is occure

### Webserver logs

```bash
[2022-11-06 00:03:18,951] [DEBUG] [paperless_mail] Rule ***@gmail.com.***: Processing mail *** from ***@mail.com with 1 attachment(s)

[2022-11-06 00:03:18,954] [INFO] [paperless_mail] Rule ***@gmail.com.***: Consuming attachment ***.pdf from mail *** from ***@mail.com

[2022-11-06 00:03:18,955] [ERROR] [paperless_mail] Rule ***@gmail.com.***: Error while processing mail 76999: consume_file() got an unexpected keyword argument 'task_name'

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_mail/mail.py", line 318, in handle_mail_rule

    processed_files = self.handle_message(message, rule)

  File "/usr/src/paperless/src/paperless_mail/mail.py", line 417, in handle_message

    consume_file.delay(

  File "/usr/local/lib/python3.9/site-packages/celery/app/task.py", line 425, in delay

    return self.apply_async(args, kwargs)

  File "/usr/local/lib/python3.9/site-packages/celery/app/task.py", line 540, in apply_async

    check_arguments(*(args or ()), **(kwargs or {}))

TypeError: consume_file() got an unexpected keyword argument 'task_name'
```

### Paperless-ngx version

dev

### Host OS

Ubuntu

### Installation method

Docker - official image

**Comment by shamoon** [comment]
Thanks :) looks like just a dangling issue from the migration to celery

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/39149a891ce19b816464ed119b637ef83c74aac5
