### ISSUE TITLE
[BUG] Document Upload API: Connection timeout during response

### ISSUE THREAD

**Issue by steilerDev** [paperless-ngx/paperless-ngx#1972]
### Description

I want to use the [document upload API](https://paperless-ngx.readthedocs.io/en/latest/api.html#posting-documents) to send files to paperless.

The API never responds to the upload request. The document is successfully uploaded, but the request times-out.

This behaviour could be independently verified by uploading from the container directly.

~~However I noticed that sometimes the Proxy would randomly timeout after not receiving a timely response from the paperless backend.~~

~~After digging a bit, I noticed, that upon upload a duplicate file, the paperless logs show an unhandled exception:~~
```
2:21:21 [Q] ERROR Failed [Clipboard 12.11.2022, 12.21.pdf] - Clipboard 12.11.2022, 12.21.pdf: Not consuming Clipboard 12.11.2022, 12.21.pdf: It is a duplicate. : Traceback (most recent call last):
  File "/usr/src/paperless/src/src/django-q/django_q/cluster.py", line 454, in worker
    res = f(*task["args"], **task["kwargs"])
  File "/usr/src/paperless/src/documents/tasks.py", line 154, in consume_file
    document = Consumer().try_consume_file(
  File "/usr/src/paperless/src/documents/consumer.py", line 266, in try_consume_file
    self.pre_check_duplicate()
  File "/usr/src/paperless/src/documents/consumer.py", line 119, in pre_check_duplicate
    self._fail(
  File "/usr/src/paperless/src/documents/consumer.py", line 90, in _fail
    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
documents.consumer.ConsumerError: Clipboard 12.11.2022, 12.21.pdf: Not consuming Clipboard 12.11.2022, 12.21.pdf: It is a duplicate.
```

~~It seems that the [document consumer task is throwing an error upon failure](https://github.com/paperless-ngx/paperless-ngx/blob/34a0111ff5ca7dd096d69d0b4a11b97dd6121ea1/src/documents/tasks.py#L154), which is not handled by the API logic.~~

Unfortunately I don't know python and how the API is registered in paperless well enough to be confident to open a PR, however I hope this helps properly respond upon failure instead of timing out on a response.

### Steps to reproduce

1. Upload a file through the [REST API](https://paperless-ngx.readthedocs.io/en/latest/api.html#posting-documents)
2. ~~Upload the file again (which will be rejected from paperless due to being a duplicate)~~
3. The ~~second~~ request times out

Expected: Receive an appropriate error code - for duplicates this should be either 400 or maybe 409 (Conflict).

### Webserver logs

```bash
2:20:16 [Q] INFO Process-1:1740 ready for work at 12354
12:21:21 [Q] INFO Process-1:1740 processing [Clipboard 12.11.2022, 12.21.pdf]
[2022-11-12 12:21:21,815] [ERROR] [paperless.consumer] Not consuming Clipboard 12.11.2022, 12.21.pdf: It is a duplicate.
12:21:21 [Q] INFO Process-1:1740 stopped doing work
12:21:21 [Q] ERROR Failed [Clipboard 12.11.2022, 12.21.pdf] - Clipboard 12.11.2022, 12.21.pdf: Not consuming Clipboard 12.11.2022, 12.21.pdf: It is a duplicate. : Traceback (most recent call last):
  File "/usr/src/paperless/src/src/django-q/django_q/cluster.py", line 454, in worker
    res = f(*task["args"], **task["kwargs"])
  File "/usr/src/paperless/src/documents/tasks.py", line 154, in consume_file
    document = Consumer().try_consume_file(
  File "/usr/src/paperless/src/documents/consumer.py", line 266, in try_consume_file
    self.pre_check_duplicate()
  File "/usr/src/paperless/src/documents/consumer.py", line 119, in pre_check_duplicate
    self._fail(
  File "/usr/src/paperless/src/documents/consumer.py", line 90, in _fail
    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
documents.consumer.ConsumerError: Clipboard 12.11.2022, 12.21.pdf: Not consuming Clipboard 12.11.2022, 12.21.pdf: It is a duplicate.

12:21:26 [Q] INFO recycled worker Process-1:1740
12:21:26 [Q] INFO Process-1:1741 ready for work at 12381
12:27:57 [Q] INFO Enqueued 1
```

### Paperless-ngx version

1.9.0

### Host OS

gcr.io/paperless-ngx/paperless-ngx:latest container on Debian 10 x86_64

### Installation method

Docker - official image

**Comment by steilerDev** [comment]
nginx-proxy error:
```
nginx.1     | 2022/11/12 12:32:20 [error] 277#277: *453222 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 10.13.0.34, server: paperless.xxx.net, request: "POST /api/documents/post_document/ HTTP/2.0", upstream: "http://172.19.0.25:8000/api/documents/post_document/", host: "paperless.xxx.net"
```

**Comment by stumpylog** [comment]
The API request and the actual consumption of a document are not coupled together in a way I can see causing this.  The API creates a task and returns OK, while the task is picked up and run in the background by a worker.  It's the same API endpoint used by the frontend for uploading, which also has to handle the same kind of case.

**Comment by steilerDev** [comment]
@stumpylog I just uploaded another file via the API and the connection is also timing out, when the upload is successful.

It seems this particular API is not responding correctly independently of the consumer's status (which matches your explanation on how the API is working).

**Comment by steilerDev** [comment]
`nginx-proxy` error:
```
nginx.1     | 2022/11/19 12:01:50 [error] 153#153: *27 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 10.13.0.34, server: paperless.xxx.net, request: "POST /api/documents/post_document/ HTTP/2.0", upstream: "http://172.19.0.25:8000/api/documents/post_document/", host: "paperless.xxx.net"
```

`paperless` log:
```
11:57:48 [Q] INFO recycled worker Process-1:2931
11:57:48 [Q] INFO Process-1:2932 ready for work at 5550
12:00:50 [Q] INFO Process-1:2932 processing [XX.pdf]
[2022-11-19 12:00:51,088] [INFO] [paperless.consumer] Consuming XX.pdf
[2022-11-19 12:00:55,296] [WARNING] [ocrmypdf._sync] Output file is okay but is not PDF/A (seems to be No PDF/A metadata in XMP)
[2022-11-19 12:00:57,648] [INFO] [paperless.handlers] Assigning document type Antrag to 2022-11-19 XXX
[2022-11-19 12:00:58,066] [INFO] [paperless.consumer] Document 2022-11-19 XXX consumption finished
12:00:58 [Q] INFO Process-1:2932 stopped doing work
12:00:58 [Q] INFO Processed [Datenblatt_Kaufvertrag.pdf]
12:00:58 [Q] INFO recycled worker Process-1:2932
12:00:58 [Q] INFO Process-1:2933 ready for work at 5670
```

**Comment by stumpylog** [comment]
Can you reproduce it without going through the proxy?

**Comment by steilerDev** [comment]
Yes - using `curl` inside the application container:
```
root@b89f6ebc90ce:~# curl --max-time 20 -v --header "Authorization: Basic <Base64>" -F "document=@/root/108219.pdf" http://localhost:8000/api/documents/post_document/
*   Trying 127.0.0.1:8000...
* Connected to localhost (127.0.0.1) port 8000 (#0)
> POST /api/documents/post_document/ HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.74.0
> Accept: */*
> Authorization: Basic <Base64>
> Content-Length: 18202
> Content-Type: multipart/form-data; boundary=------------------------fb88d30d3c1e36c6
> 
* We are completely uploaded and fine
* Operation timed out after 20001 milliseconds with 0 bytes received
* Closing connection 0
curl: (28) Operation timed out after 20001 milliseconds with 0 bytes received
```

Corresponding paperless log:
```
17:37:59 [Q] INFO Process-1:2975 processing [108219.pdf]
[2022-11-19 17:37:59,500] [INFO] [paperless.consumer] Consuming 108219.pdf
[2022-11-19 17:38:01,814] [INFO] [paperless.handlers] Assigning correspondent xxx to 2022-11-19 108219
[2022-11-19 17:38:01,818] [INFO] [paperless.handlers] Assigning document type Rechnung to 2022-11-19 xxx 108219
[2022-11-19 17:38:01,825] [INFO] [paperless.handlers] Tagging "2022-11-19 xxx 108219" with "zzz"
[2022-11-19 17:38:01,928] [INFO] [paperless.consumer] Document 2022-11-19 xxx 108219 consumption finished
17:38:01 [Q] INFO Process-1:2975 stopped doing work
17:38:01 [Q] INFO Processed [108219.pdf]
17:38:04 [Q] INFO recycled worker Process-1:2975
17:38:04 [Q] INFO Process-1:2976 ready for work at 12820
```

**Comment by stumpylog** [comment]
Hm, you could try enabling debug (`PAPERLESS_DEBUG=1`).  I don't think that really gets anything extra from DRF or Django, which is where this pretty much has to be coming from, since our code returns

Another option is to try with our `beta`, which has seen updates to both DRF and Django and many other fixes.

**Comment by steilerDev** [comment]
Okay... Doing a full `docker compose pull` seems to have fixed the issue (maybe the restart did it)

In case the issue comes back I'll open another issue - thanks for your support @stumpylog
