### ISSUE TITLE
[BUG] Tagging in mail rules not working for iCloud

### ISSUE THREAD

**Issue by Disane87** [paperless-ngx/paperless-ngx#2037]
### Description

I want to tag my mails to indicate that these are already imported by paperless like this:

![image](https://user-images.githubusercontent.com/956158/203853281-f1276d25-6954-4bde-950e-05fe77911dac.png)

But this leads to this error:

```
Error while processing rule: SEARCH command error: BAD [b'Parse Error (took 0 ms)']
```

### Steps to reproduce

1) Create a new mail rule for iCloud account
2) Use as action marking mails with tags
3) Add as parameter a tagname

### Webserver logs

```bash
[2022-11-24 20:13:19,808] [DEBUG] [paperless_mail] Rule iCloud.Test Tags: Selecting folder Test Paperless Tags

[2022-11-24 20:13:20,078] [DEBUG] [paperless_mail] Rule iCloud.Test Tags: Searching folder with criteria (NOT (X-GM-LABELS "Test") SINCE 25-Oct-2022 UNKEYWORD Test)

[2022-11-24 20:13:20,312] [ERROR] [paperless_mail] Rule iCloud.Test Tags: Error while processing rule: SEARCH command error: BAD [b'Parse Error (took 0 ms)']

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_mail/mail.py", line 218, in handle_mail_account

    total_processed_files += self.handle_mail_rule(M, rule)

  File "/usr/src/paperless/src/paperless_mail/mail.py", line 291, in handle_mail_rule

    for message in messages:

  File "/usr/local/lib/python3.9/site-packages/imap_tools/mailbox.py", line 170, in fetch

    nums = tuple((reversed if reverse else iter)(self.numbers(criteria, charset)))[limit_range]

  File "/usr/local/lib/python3.9/site-packages/imap_tools/mailbox.py", line 108, in numbers

    search_result = self.client.search(charset, encoded_criteria)

  File "/usr/local/lib/python3.9/imaplib.py", line 732, in search

    typ, dat = self._simple_command(name, 'CHARSET', charset, *criteria)

  File "/usr/local/lib/python3.9/imaplib.py", line 1230, in _simple_command

    return self._command_complete(name, self._command(name, *args))

  File "/usr/local/lib/python3.9/imaplib.py", line 1055, in _command_complete

    raise self.error('%s command error: %s %s' % (name, typ, data))

imaplib.IMAP4.error: SEARCH command error: BAD [b'Parse Error (took 0 ms)']
```

### Paperless-ngx version

1.9.2

### Host OS

Unraid x86_64

### Installation method

Docker - official image

### Browser

Edge

**Comment by Disane87** [comment]
Just saw, that `X-GM-LABELS` is gmail specific. Is there any chance to get this working with icloud, like flagging?

**Comment by stumpylog** [comment]
The beta is quite stable at this point, so I'd suggest trying with it.  The linked probably resolves it, though the traceback is slightly different.

**Comment by Disane87** [comment]
> The beta is now out of... beta. Can you see if this is still present in 1.10.0?

It doesn't crash anymore, thats good:
```
[2022-11-28 09:12:20,440] [DEBUG] [paperless_mail] Rule iCloud.Test Tags: Selecting folder Test Paperless Tags

[2022-11-28 09:12:20,654] [DEBUG] [paperless_mail] Rule iCloud.Test Tags: Searching folder with criteria (SINCE 29-Oct-2022 UNKEYWORD Test)

[2022-11-28 09:12:21,307] [DEBUG] [paperless_mail] Rule iCloud.Test Tags: Processing mail Test from disane@icloud.com with 1 attachment(s)

[2022-11-28 09:12:21,311] [INFO] [paperless_mail] Rule iCloud.Test Tags: Consuming attachment sdfsdfdsf.pdf from mail Test from disane@icloud.com

[2022-11-28 09:12:22,751] [DEBUG] [paperless_mail] Rule iCloud.Test Tags: Processed 1 matching mail(s)

[2022-11-28 09:12:22,752] [DEBUG] [paperless_mail] Rule iCloud.Test Tags: Running mail actions on 1 mails
```

But tags are not set :-(
I guess iCloud doesn't support them. Do you know how to set a custom flag for mails in iCloud?

**Comment by shamoon** [comment]
Ah, yea seems it doesn’t. Well your options would be one of the other actions, ie to move, flag or mark as read (or delete)

glad the crash is sorted

**Comment by Disane87** [comment]
> Ah, yea seems it doesn’t. Well your options would be one of the other actions, ie to move, flag or mark as read (or delete)
> 
> glad the crash is sorted

Thank you! I guess I have to stick with moving to a dedicated folder actually :) Thank you for your assistance.
