### ISSUE TITLE
[BUG] Last update of docker beta version not launching anymore

### ISSUE THREAD

**Issue by sarakha63** [paperless-ngx/paperless-ngx#2056]
### Description

Since Last update of papierlesse docker (watchtower)

Paperless doesnt launch anymore

See log under 

But here is the error

ImportError: pikepdf's extension library failed to import

### Steps to reproduce

Docker install the Last image should see the error

### Webserver logs

```bash
Waiting for PostgreSQL to start...
Waiting for Redis...
Connected to Redis broker.
Apply database migrations...
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pikepdf/__init__.py", line 10, in <module>
    from . import _qpdf
ImportError: /usr/local/lib/python3.9/site-packages/pikepdf/_qpdf.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZTI16QPDFObjectHelper, version LIBQPDF_29
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 97, in handle
    self.check(databases=[database])
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 475, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.9/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.9/site-packages/django/core/checks/urls.py", line 42, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/usr/local/lib/python3.9/site-packages/django/core/checks/urls.py", line 61, in _load_all_namespaces
    url_patterns = getattr(resolver, "url_patterns", [])
  File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/src/paperless/src/paperless/urls.py", line 10, in <module>
    from documents.views import AcknowledgeTasksView
  File "/usr/src/paperless/src/documents/views.py", line 31, in <module>
    from documents.tasks import consume_file
  File "/usr/src/paperless/src/documents/tasks.py", line 17, in <module>
    from documents import barcodes
  File "/usr/src/paperless/src/documents/barcodes.py", line 13, in <module>
    from pikepdf import Page
  File "/usr/local/lib/python3.9/site-packages/pikepdf/__init__.py", line 13, in <module>
    raise ImportError(_msg) from _e
ImportError: pikepdf's extension library failed to import
```

### Paperless-ngx version

Last beta

### Host OS

Docker on x64

### Installation method

Docker - official image

### Browser

Not revelant

### Configuration changes

Nothing only updated today

**Comment by shamoon** [comment]
Sorry this is on the beta or the v1.10.0 release i.e. `ghcr.io/paperless-ngx/paperless-ngx:latest`?

**Comment by sarakha63** [comment]
Last beta.

I wrote it in the section Version

Sorry changed the title to be more clear

**Comment by shamoon** [comment]
Can you try the release?

**Comment by stumpylog** [comment]
I've untagged the version so it can't be easily downloaded again.  No idea what happened in that build, all looks normal.
