### ISSUE TITLE
[BUG] pikepdf._qpdf.PasswordError: /usr/src/paperless/consume/[42757].pdf: invalid password

### ISSUE THREAD

**Issue by nodecentral** [paperless-ngx/paperless-ngx#2081]
### Description

Hi

I’m trying to import a password protected pdf file, but it fails each time with the following `pdf:invalid password` message , yet I’m not even prompted to add one ? 

It looks similar to https://github.com/paperless-ngx/paperless-ngx/issues/1850 as both refers to barcodes, and I have PAPERLESS_CONSUMER_ENABLE_BARCODES=true too.

### Steps to reproduce

Unfortunately its a tax form so I can post to share it.

### Webserver logs

```bash
`
/usr/src/paperless/consume/[42757].pdf: invalid password : Traceback (most recent call last):
  File "/usr/src/paperless/src/src/django-q/django_q/cluster.py", line 454, in worker
    res = f(*task["args"], **task["kwargs"])
  File "/usr/src/paperless/src/documents/tasks.py", line 99, in consume_file
    pdf_filepath, separators = barcodes.scan_file_for_separating_barcodes(path)
  File "/usr/src/paperless/src/documents/barcodes.py", line 121, in scan_file_for_separating_barcodes
    pdf = Pdf.open(pdf_filepath)
  File "/usr/local/lib/python3.9/site-packages/pikepdf/_methods.py", line 791, in open
    pdf = Pdf._open(
pikepdf._qpdf.PasswordError: /usr/src/paperless/consume/[42757].pdf: invalid password
````
```


### Browser logs

_No response_

### Paperless-ngx version

1.9.2

### Host OS

QNAP Linux

### Installation method

Docker - official image

### Browser

IOS Safari

### Configuration changes

_No response_

### Other

_No response_

**Comment by stumpylog** [comment]
The fix is already in 1.10.0.  Please update.
