### ISSUE TITLE
[BUG] PDF converting of Office documents

### ISSUE THREAD

**Issue by mztiq** [paperless-ngx/paperless-ngx#2116]
### Description

I'm having problems with PDF converting of Office documents on a fresh installation (via installation script).
Whenever I add an Office document (doesn't matter if I add it via the consume directory or Web GUI) it ends up with the following error (source: Web GUI):
```
file-sample_500kB.docx: Error while consuming document file-sample_500kB.docx: Error while converting document to PDF: HTTPConnectionPool(host='gotenberg', port=3000): Max retries exceeded with url: /forms/libreoffice/convert (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f61e9b12e20>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

Logs of Gotenberg look as following:
```
A Docker-powered stateless API for PDF files.
Version: 7.6.2
-------------------------------------------------------
[SYSTEM] modules: api chromium gc libreoffice logging pdfcpu pdfengines pdftk prometheus qpdf uno uno-pdfengine webhook 
[SYSTEM] api: server listening on port 3000
[SYSTEM] gc: application started
[SYSTEM] prometheus: collecting metrics
[SYSTEM] uno: long-running LibreOffice listener ready to start
[SYSTEM] pdfengines: pdfcpu pdftk qpdf uno-pdfengine
{"level":"error","ts":1670192985.0860496,"logger":"api","msg":"convert to PDF: lock long-running LibreOffice listener: start long-running LibreOffice listener: execute LibreOffice listener: context done: context deadline exceeded","trace":"9a85e549-35c7-4101-b358-6cf946bf219f","remote_ip":"172.18.0.3","host":"gotenberg:3000","uri":"/forms/libreoffice/convert","method":"POST","path":"/forms/libreoffice/convert","referer":"","user_agent":"python-requests/2.28.1","status":503,"latency":10905580166,"latency_human":"10.905580166s","bytes_in":551979,"bytes_out":19}
```

Things I already tried:
- gotenberg V 7.4 and 7.7
  - Same error as with 7.6
- Changed gotenberg endpoint to http://gotenberg:3000/forms/libreoffice/convert# in the `docker-compose.yml`
  - Error changed to the following:
```
Error while converting document to PDF: 503 Server Error: Service Unavailable for url: http://gotenberg:3000/forms/libreoffice/convert/forms/libreoffice/convert
```
- Tried to expose port 3000 for the gotenberg service and changed gotenberg endpoint to http://IP-ADDRESS:3000/forms/libreoffice/convert#
  - Same error 503 
- Installed gotenberg as a separate docker container with port 3000 exposed and gotenberg endpoint to http://IP-ADDRESS:3000/forms/libreoffice/convert#
  - Same error 503 

All containers are up and running:
```
        Name                       Command                  State                         Ports                   
------------------------------------------------------------------------------------------------------------------
paperless_broker_1      docker-entrypoint.sh redis ...   Up             6379/tcp                                  
paperless_db_1          docker-entrypoint.sh postgres    Up             5432/tcp                                  
paperless_gotenberg_1   /usr/bin/tini -- gotenberg ...   Up             3000/tcp                                  
paperless_tika_1        /bin/sh -c exec java -jar  ...   Up             9998/tcp                                  
paperless_webserver_1   /sbin/docker-entrypoint.sh ...   Up (healthy)   0.0.0.0:50056->8000/tcp,:::50056->8000/tcp
```

Any help would be appreciated, I'd really love to switch to Paperless-ngx.

Thanks in advance.

### Steps to reproduce

1. Add an Office document to Paperless-ngx (via consume Folder or Web GUI).
2. Check output of "File Tasks" and log of webserver/gotenberg

### Webserver logs

```bash
Paperless-ngx docker container starting...
Creating directory /tmp/paperless
[nltk_data] Downloading package snowball_data to
[nltk_data]     /usr/src/paperless/data/nltk...
[nltk_data]   Package snowball_data is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /usr/src/paperless/data/nltk...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     /usr/src/paperless/data/nltk...
[nltk_data]   Package punkt is already up-to-date!
Adjusting permissions of paperless files. This may take a while.
Waiting for PostgreSQL to start...
Waiting for Redis...
Connected to Redis broker.
Apply database migrations...
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, django_celery_results, documents, paperless_mail, sessions
Running migrations:
  No migrations to apply.
Executing /usr/local/bin/paperless_cmd.sh
2022-12-04 22:28:37,700 INFO Set uid to user 0 succeeded
2022-12-04 22:28:37,708 INFO supervisord started with pid 1
2022-12-04 22:28:38,716 INFO spawned: 'gunicorn' with pid 55
2022-12-04 22:28:38,719 INFO spawned: 'celery' with pid 56
2022-12-04 22:28:38,726 INFO spawned: 'celery-beat' with pid 57
2022-12-04 22:28:38,734 INFO spawned: 'consumer' with pid 58
2022-12-04 22:28:38,743 INFO spawned: 'celery-flower' with pid 59
Checking if we should start flower...
2022-12-04 22:28:38,811 INFO success: celery-flower entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2022-12-04 22:28:39,819 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-12-04 22:28:39,820 INFO success: celery entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-12-04 22:28:39,820 INFO success: celery-beat entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-12-04 22:28:39,822 INFO success: consumer entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-12-04 22:28:39,823 INFO exited: celery-flower (exit status 0; expected)
[2022-12-04 23:28:51 +0100] [55] [INFO] Starting gunicorn 20.1.0
[2022-12-04 23:28:51 +0100] [55] [INFO] Listening at: http://[::]:8000 (55)
[2022-12-04 23:28:51 +0100] [55] [INFO] Using worker: paperless.workers.ConfigurableWorker
[2022-12-04 23:28:51 +0100] [55] [INFO] Server is ready. Spawning workers
[2022-12-04 23:28:52,483] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: /usr/src/paperless/consume
[2022-12-04 23:28:53,862] [INFO] [celery.beat] beat: Starting...
 
 -------------- celery@ac79d55b53b4 v5.2.7 (dawn-chorus)
--- ***** ----- 
-- ******* ---- Linux-5.15.74-1-pve-x86_64-with-glibc2.31 2022-12-04 23:28:54
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         paperless:0x7fb8c03f33a0
- ** ---------- .> transport:   redis://broker:6379//
- ** ---------- .> results:     
- *** --- * --- .> concurrency: 1 (prefork)
-- ******* ---- .> task events: ON
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . documents.tasks.bulk_update_documents
  . documents.tasks.consume_file
  . documents.tasks.index_optimize
  . documents.tasks.sanity_check
  . documents.tasks.train_classifier
  . documents.tasks.update_document_archive_file
  . paperless_mail.tasks.process_mail_accounts

[2022-12-04 23:28:54,495] [INFO] [celery.worker.consumer.connection] Connected to redis://broker:6379//
[2022-12-04 23:28:54,521] [INFO] [celery.worker.consumer.mingle] mingle: searching for neighbors
[2022-12-04 23:28:55,584] [INFO] [celery.worker.consumer.mingle] mingle: all alone
[2022-12-04 23:28:55,634] [INFO] [celery.apps.worker] celery@ac79d55b53b4 ready.
[2022-12-04 23:29:08,815] [INFO] [celery.worker.strategy] Task documents.tasks.consume_file[167d5b7b-c45a-462a-a61d-710bd3a04fc1] received
[2022-12-04 23:29:09,054] [INFO] [paperless.consumer] Consuming file-sample_500kB.docx
[2022-12-04 23:29:09,108] [INFO] [paperless.parsing.tika] Sending /tmp/paperless/paperless-upload-p84jvuoe to Tika server
[2022-12-04 23:29:28,899] [WARNING] [paperless.parsing.tika] Unable to extract date for document /tmp/paperless/paperless-upload-p84jvuoe: 'Creation-Date'
[2022-12-04 23:29:28,918] [INFO] [paperless.parsing.tika] Converting /tmp/paperless/paperless-upload-p84jvuoe to PDF as /tmp/paperless/paperless-t6q6zam3/convert.pdf
[2022-12-04 23:29:45,339] [ERROR] [paperless.consumer] Error while consuming document file-sample_500kB.docx: Error while converting document to PDF: 503 Server Error: Service Unavailable for url: http://gotenberg:3000/forms/libreoffice/convert
Traceback (most recent call last):
  File "/usr/src/paperless/src/paperless_tika/parsers.py", line 101, in convert_to_pdf
    response.raise_for_status()  # ensure we notice bad responses
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://gotenberg:3000/forms/libreoffice/convert

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/consumer.py", line 337, in try_consume_file    document_parser.parse(self.path, mime_type, self.filename)
  File "/usr/src/paperless/src/paperless_tika/parsers.py", line 82, in parse
    self.archive_path = self.convert_to_pdf(document_path, file_name)
  File "/usr/src/paperless/src/paperless_tika/parsers.py", line 103, in convert_to_pdf
    raise ParseError(
documents.parsers.ParseError: Error while converting document to PDF: 503 Server Error: Service Unavailable for url: http://gotenberg:3000/forms/libreoffice/convert
[2022-12-04 23:29:46,156] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[167d5b7b-c45a-462a-a61d-710bd3a04fc1] raised unexpected: ConsumerError('file-sample_500kB.docx: Error while consuming document file-sample_500kB.docx: Error while converting document to PDF: 503 Server Error: Service Unavailable for url: http://gotenberg:3000/forms/libreoffice/convert')
Traceback (most recent call last):
  File "/usr/src/paperless/src/paperless_tika/parsers.py", line 101, in convert_to_pdf
    response.raise_for_status()  # ensure we notice bad responses
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://gotenberg:3000/forms/libreoffice/convert

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 280, in main_wrap
    raise exc_info[1]
  File "/usr/src/paperless/src/documents/consumer.py", line 337, in try_consume_file    document_parser.parse(self.path, mime_type, self.filename)
  File "/usr/src/paperless/src/paperless_tika/parsers.py", line 82, in parse
    self.archive_path = self.convert_to_pdf(document_path, file_name)
  File "/usr/src/paperless/src/paperless_tika/parsers.py", line 103, in convert_to_pdf
    raise ParseError(
documents.parsers.ParseError: Error while converting document to PDF: 503 Server Error: Service Unavailable for url: http://gotenberg:3000/forms/libreoffice/convert

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/paperless/src/documents/tasks.py", line 177, in consume_file
    document = Consumer().try_consume_file(
  File "/usr/src/paperless/src/documents/consumer.py", line 356, in try_consume_file    self._fail(
  File "/usr/src/paperless/src/documents/consumer.py", line 91, in _fail
    raise ConsumerError(f"{self.filename}: {log_message or message}") from exceptiondocuments.consumer.ConsumerError: file-sample_500kB.docx: Error while consuming document file-sample_500kB.docx: Error while converting document to PDF: 503 Server Error: Service Unavailable for url: http://gotenberg:3000/forms/libreoffice/convert
```

### Paperless-ngx version

1.10.1 and 1.10.2

### Host OS

Ubuntu 20.04.5 LTS and Ubuntu 22.04.1 LTS

### Installation method

Docker - official image

### Browser

Firefox, MS Edge

### Configuration changes

Changes in `docker-compose.env`:
PAPERLESS_FILENAME_FORMAT={created_year}/{correspondent}/{title} PAPERLESS_FILENAME_FORMAT_REMOVE_NONE=True

**Comment by stumpylog** [comment]
I think this would be better asked in the Gotenberg issues. From a quick search, this looks related to gotenberg/gotenberg/issues/442 which doesn't have a resolution upstream yet.

**Comment by mztiq** [comment]
Referencing to https://github.com/paperless-ngx/paperless-ngx/issues/2065#issuecomment-1344332980 I finally could fix the issue by using `gotenberg:7.4`.  
I probably failed to make sure `Gotenberg` actually was running in `7.4` on my previous tests, sorry for the confusion.  

Still might be something to look into since file conversion does not work in Versions `7.6` and `7.7`.

**Comment by stumpylog** [comment]
As we don't control anything about Gotenberg, there isn't something to look into in this repo.  I'm going to close this issue.

You can comment on the above issue in their repository and perhaps they will be able to resolve it in a new version.  Or when the embedded LibreOffice updates.

**Comment by savek-cc** [comment]
> As we don't control anything about Gotenberg, there isn't something to look into in this repo. I'm going to close this issue.
> 
> You can comment on the above issue in their repository and perhaps they will be able to resolve it in a new version. Or when the embedded LibreOffice updates.

Just a note: I had the same issue and just stumbled across this closed bug - this repo is referencing gotenberg:7.6 in the docker-compose files though - so there is something that could be done in this repo: Switch back to gotenberg:7.4 in the docker-compose files.
