### ISSUE TITLE
[BUG] MissingDependencyError: tesseract after upgrade to 1.10.2

### ISSUE THREAD

**Issue by efelon** [paperless-ngx/paperless-ngx#2188]
### Description

After the upgrade all services run normal without error. As soon as I want to consume a document I get the error below.

## Log
```
[2022-12-15 13:49:03,288] [DEBUG] [paperless.consumer] Parsing 20221101_Scan_010538.pdf...
[2022-12-15 13:49:03,842] [DEBUG] [paperless.parsing.tesseract] Extracted text from PDF file /mnt/edms/consume/20221101_Scan_010538.pdf
[2022-12-15 13:49:04,082] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/mnt/edms/consume/20221101_Scan_010538.pdf'), 'o
utput_file': '/tmp/paperless/paperless-y2scef1v/archive.pdf', 'use_threads': True, 'jobs': 4, 'language': 'deu+eng', 'output_type': 'pdfa', 'progress_bar': False, 'sk
ip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': '/tmp/paperless/paperless-y2scef1v/sidecar.txt'}
[2022-12-15 13:49:04,355] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-y2scef1v
[2022-12-15 13:49:04,372] [ERROR] [paperless.consumer] Error while consuming document 20221101_Scan_010538.pdf: MissingDependencyError: tesseract
Traceback (most recent call last):
  File "/opt/paperless/paperless-ngx/src/paperless_tesseract/parsers.py", line 292, in parse
    ocrmypdf.ocr(**args)
  File "/opt/paperless/venv/lib/python3.9/site-packages/ocrmypdf/api.py", line 331, in ocr
    check_options(options, plugin_manager)
  File "/opt/paperless/venv/lib/python3.9/site-packages/ocrmypdf/_validation.py", line 246, in check_options
    _check_plugin_options(options, plugin_manager)
  File "/opt/paperless/venv/lib/python3.9/site-packages/ocrmypdf/_validation.py", line 239, in _check_plugin_options
    plugin_manager.hook.check_options(options=options)
  File "/opt/paperless/venv/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/opt/paperless/venv/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/opt/paperless/venv/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/opt/paperless/venv/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/opt/paperless/venv/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/opt/paperless/venv/lib/python3.9/site-packages/ocrmypdf/builtin_plugins/tesseract_ocr.py", line 92, in check_options
    check_external_program(
  File "/opt/paperless/venv/lib/python3.9/site-packages/ocrmypdf/subprocess/__init__.py", line 346, in check_external_program
    raise MissingDependencyError(program)
ocrmypdf.exceptions.MissingDependencyError: tesseract

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/paperless/paperless-ngx/src/documents/consumer.py", line 337, in try_consume_file
    document_parser.parse(self.path, mime_type, self.filename)
  File "/opt/paperless/paperless-ngx/src/paperless_tesseract/parsers.py", line 346, in parse
    raise ParseError(f"{e.__class__.__name__}: {str(e)}") from e
documents.parsers.ParseError: MissingDependencyError: tesseract

```
## Infos
* Tesseract is installed
    ```
    which tesseract
    /usr/bin/tesseract

    dpkg -l tesseract* | grep ii
    ii  tesseract-ocr            4.0.0-2                armhf        Tesseract command line OCR tool
    ii  tesseract-ocr-deu        1:4.00~git30-7274cfa-1 all          tesseract-ocr language files for German
    ii  tesseract-ocr-eng        1:4.00~git30-7274cfa-1 all          tesseract-ocr language files for English
    ii  tesseract-ocr-osd        1:4.00~git30-7274cfa-1 all          tesseract-ocr language files for script and orientation
    ```
* requirements and migration are ok:
    
![image](https://user-images.githubusercontent.com/10722552/207865876-0c7232ca-4082-4064-9b06-57ae52ed4127.png)

### Steps to reproduce

1. Move a file to the consumer folder
  (tested several pdfs)
2. Watch log

### Webserver logs

```bash
Not involved, only consumer.
```

### Paperless-ngx version

1.10.2

### Host OS

Linux 5.10.103-v7l+ #1529 SMP [...] armv7l GNU/Linux

### Installation method

Bare metal

### Browser

not relevant

### Configuration changes

paperless.conf - using poller and redis

### Other

Im running a bare metal installation from a venv which worked on the previous version 1.9.2

**Comment by efelon** [comment]
If I run the ocrmypdf from within the venv, I get:
```
ocrmypdf pdf-test.pdf /tmp/pdf-test.pdf

OCRmyPDF requires 'tesseract' 4.1.1 or higher.  Your system appears
to have 4.0.0.  Please update this program.
```
This might be the problem?!

**Comment by shamoon** [comment]
It certainly is the problem yes. If you installed bare metal you’re responsible for making sure all dependencies are present and at the right version…
