### ISSUE TITLE
[BUG] Folder gets unaccessible after the last document has been deleted/moved. Also for new documents.

### ISSUE THREAD

**Issue by Grmlrckr** [paperless-ngx/paperless-ngx#2207]
### Description

I use a custom path/file name format (PAPERLESS_FILENAME_FORMAT={correspondent}/{document_type}/{created}, {title}).
My media folder is on a CIFS share (auto-mounted in fstab)

When uploading several files, they first all appear in media/documents/_[originals|archive]_/**none**/**none** as either correspondent or document_type are set yet. So far, so good.

But as soon as the last document is deleted or moved to its new location (due to the Correspondent and Document Type being set then), the folder "**none**" becomes unaccessible. So it's not possible to add new documents that would initially be placed in the "none"-folder because they don't have a Correspondent yet. Same of course for all other folders that get empty when documents are moved by Paperless-NGX.

### Steps to reproduce

1. Upload a file and have it moved [by a custom filename format] to a folder.
2. Make sure there are no other files in that folder
3. Change e.g. the Correspondent so that the file will be moved to another folder (due to the custom filename format)
4. If that file was the last file in the original folder, that one will become unaccessible to Paperport-NGX
5. (Upload another file with the same details as in 1. You should get an error message)

### Webserver logs

```bash
[2022-12-18 13:47:51,137] [INFO] [paperless.consumer] Consuming owntitle2.pdf
[2022-12-18 13:47:51,138] [DEBUG] [paperless.consumer] Detected mime type: application/pdf
[2022-12-18 13:47:51,143] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser
[2022-12-18 13:47:51,151] [DEBUG] [paperless.consumer] Parsing owntitle2.pdf...
[2022-12-18 13:47:51,217] [DEBUG] [paperless.parsing.tesseract] Extracted text from PDF file /tmp/paperless/paperless-upload-ok6skfe0
[2022-12-18 13:47:51,379] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-upload-ok6skfe0'), 'output_file': '/tmp/paperless/paperless-y5htj95z/archive.pdf', 'use_threads': True, 'jobs': 1, 'language': 'deu', 'output_type': 'pdfa', 'progress_bar': False, 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': '/tmp/paperless/paperless-y5htj95z/sidecar.txt'}
[2022-12-18 13:47:52,093] [DEBUG] [paperless.parsing.tesseract] Incomplete sidecar file: discarding.
[2022-12-18 13:47:52,101] [DEBUG] [paperless.parsing.tesseract] Extracted text from PDF file /tmp/paperless/paperless-y5htj95z/archive.pdf
[2022-12-18 13:47:52,101] [DEBUG] [paperless.consumer] Generating thumbnail for owntitle2.pdf...
[2022-12-18 13:47:52,109] [DEBUG] [paperless.parsing] Execute: convert -density 300 -scale 500x5000> -alpha remove -strip -auto-orient /tmp/paperless/paperless-y5htj95z/archive.pdf[0] /tmp/paperless/paperless-y5htj95z/convert.webp
[2022-12-18 13:47:52,914] [DEBUG] [paperless.classifier] Document classification model does not exist (yet), not performing automatic matching.
[2022-12-18 13:47:52,920] [DEBUG] [paperless.consumer] Saving record to database
[2022-12-18 13:47:52,921] [DEBUG] [paperless.consumer] Creation date from st_mtime: 2022-12-18 13:47:50+01:00
[2022-12-18 13:47:53,022] [DEBUG] [paperless.consumer] Deleting file /tmp/paperless/paperless-upload-ok6skfe0
[2022-12-18 13:47:53,026] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-y5htj95z
[2022-12-18 13:47:53,027] [INFO] [paperless.consumer] Document 2022-12-18 owntitle2 consumption finished
[2022-12-18 13:48:14,332] [DEBUG] [paperless.classifier] Document classification model does not exist (yet), not performing automatic matching.
[2022-12-18 13:50:15,742] [DEBUG] [paperless.filehandling] Document has storage_path 1 (Testspeicherpfad1) set
[2022-12-18 14:05:00,124] [DEBUG] [paperless.classifier] Document classification model does not exist (yet), not performing automatic matching.
[2022-12-18 14:05:00,125] [DEBUG] [paperless.classifier] Gathering data from database...
[2022-12-18 14:05:00,129] [WARNING] [paperless.tasks] Classifier error: No training data available.
[2022-12-18 14:06:47,059] [DEBUG] [paperless.handlers] Deleted file /usr/src/paperless/media/documents/originals/Testspeicherpfad1.pdf.
[2022-12-18 14:06:47,062] [DEBUG] [paperless.handlers] Deleted file /usr/src/paperless/media/documents/archive/Testspeicherpfad1.pdf.
[2022-12-18 14:06:47,064] [DEBUG] [paperless.handlers] Deleted file /usr/src/paperless/media/documents/thumbnails/0000001.webp.
[2022-12-18 14:07:13,821] [INFO] [paperless.consumer] Consuming owntitle2.pdf
[2022-12-18 14:07:13,823] [DEBUG] [paperless.consumer] Detected mime type: application/pdf
[2022-12-18 14:07:13,825] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser
[2022-12-18 14:07:13,831] [DEBUG] [paperless.consumer] Parsing owntitle2.pdf...
[2022-12-18 14:07:13,871] [DEBUG] [paperless.parsing.tesseract] Extracted text from PDF file /tmp/paperless/paperless-upload-5amdlrp2
[2022-12-18 14:07:13,949] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-upload-5amdlrp2'), 'output_file': '/tmp/paperless/paperless-iqfnbm20/archive.pdf', 'use_threads': True, 'jobs': 1, 'language': 'deu', 'output_type': 'pdfa', 'progress_bar': False, 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': '/tmp/paperless/paperless-iqfnbm20/sidecar.txt'}
[2022-12-18 14:07:14,363] [DEBUG] [paperless.parsing.tesseract] Incomplete sidecar file: discarding.
[2022-12-18 14:07:14,369] [DEBUG] [paperless.parsing.tesseract] Extracted text from PDF file /tmp/paperless/paperless-iqfnbm20/archive.pdf
[2022-12-18 14:07:14,370] [DEBUG] [paperless.consumer] Generating thumbnail for owntitle2.pdf...
[2022-12-18 14:07:14,377] [DEBUG] [paperless.parsing] Execute: convert -density 300 -scale 500x5000> -alpha remove -strip -auto-orient /tmp/paperless/paperless-iqfnbm20/archive.pdf[0] /tmp/paperless/paperless-iqfnbm20/convert.webp
[2022-12-18 14:07:15,112] [DEBUG] [paperless.classifier] Document classification model does not exist (yet), not performing automatic matching.
[2022-12-18 14:07:15,119] [DEBUG] [paperless.consumer] Saving record to database
[2022-12-18 14:07:15,120] [DEBUG] [paperless.consumer] Creation date from st_mtime: 2022-12-18 14:07:13+01:00
[2022-12-18 14:07:15,177] [ERROR] [paperless.consumer] The following error occurred while consuming owntitle2.pdf: [Errno 2] No such file or directory: '/usr/src/paperless/media/documents/originals/none/none'
Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/consumer.py", line 394, in try_consume_file
    create_source_path_directory(document.source_path)
  File "/usr/src/paperless/src/documents/file_handling.py", line 20, in create_source_path_directory
    os.makedirs(os.path.dirname(source_path), exist_ok=True)
  File "/usr/local/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/src/paperless/media/documents/originals/none/none'
```

### Paperless-ngx version

1.10.2

### Host OS

Debian 11.x

### Installation method

Docker - official image

### Configuration changes

PAPERLESS_FILENAME_FORMAT={correspondent}/{document_type}/{created}, {title}

**Comment by shamoon** [comment]
We see a lot of issues with CIFS shares, does this happen for you with local volumes? Wonder if it’s permissions issue

**Comment by Grmlrckr** [comment]
No, doesn't happen when the file/structure is kept locally/in a local volume. Just checked it with a fresh installation that has no CIFS shares mapped and all is managed in Docker volumes.
Probably a permission error, but only when the last file of a folder is being moved/deleted. As long as one document still exists in a CIFS share, there is no problem.

**Comment by stumpylog** [comment]
We aren't setting any sort of permissions beyond what running as the user `paperless` provides.

Are you changing correspondents, etc while consuming files?

**Comment by Grmlrckr** [comment]
I change correspondents etc. AFTER consuming. At least from what I understand how the system works. 
I upload a file manually (or automatically through the consume-folder), and later I change the details. But not directly WHILE consuming (if I understand that right).

I'm not working that long with Paperless-NGX. Actually still evaluating. In my first tests in summer this year, I (believe!) didn't have that problem (not 100% sure though).

**Comment by Grmlrckr** [comment]
Ok, thought I give some more background info. Maybe that helps to decide if it is really a bug or maybe just me doing something wrong. Unfortunately I'm not a Linux pro, so my approach might be wrong at some point... Maybe it is only some misunderstanding from my end in the /etc/fstab?

- No Active Directory or SMB domain. Only local users. 

- Docker runs on my Linux machine (A52VM901) with a local user ("a52vm901r00t") that has sudo-permissions. That user spawns the docker container.

- The CIFS share is on my NAS (\\A52VM402) in the same network
- The share is mounted during the startup of the Paperless-ngx machine with the following line in /etc/fstab:
`//a52vm402/Documents/Paperless /home/a52vm901r00t/paperless-ngx/mnt cifs credentials=/home/a52vm301r00t/paperless-ngx/server_connect.txt,uid=1000,gid=1000,iocharset=utf8,file_mode=0777,dir_mode=0777,auto,noperm,x-systemd.automount 0 0`
- The "consume", "export" and "media" folder are on the NAS and mounted into /home/a52vm901r00t/paperless-ngx/**mnt**
- The file "server_connect.txt" refered in /etc/fstab contains the credentials of the local user I have created on the NAS

So, effectively there are two local users that Paperless-ngx is in some way working with: The local user on my Linux machine that spawns the container(s) and the local user of my NAS that is used to mount the CIFS share.
But, as I'm not a Linux pro I don't know/understand where they might be interfering each other when it comes to permissions etc.

**Comment by shamoon** [comment]
Thanks for the more detailed description, it very much seems related to your (somewhat atypical, by my read) setup. In general using remote shares tend to be problematic, and it doesnt seem there's an obvious way that the fix would be on our end as opposed to changing your setup. Obviously welcome any more input here but I'll close this as not planned for now.
