### ISSUE TITLE
[BUG] Can't import an exported paperless-ngx config

### ISSUE THREAD

**Issue by bee-san** [paperless-ngx/paperless-ngx#2266]
### Description

I exported paperless-ngx from a docker container (using Compose) with:

```
docker exec 109f6546f62e document_exporter ../export
```

I then go to a different PC and try to import it with:

```
docker exec 2ec6cf06bac4 document_importer ../export
Version mismatch: Currently 1.11.0, importing 1.10.2. Continuing, but import may fail.
Installed 253 object(s) from 1 fixture(s)
Copy files into paperless...
  0%|          | 0/221 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/usr/src/paperless/src/documents/management/commands/document_importer.py", line 133, in handle
    self._import_files_from_manifest(options["no_progress_bar"])
  File "/usr/src/paperless/src/documents/management/commands/document_importer.py", line 209, in _import_files_from_manifest
    raise FileExistsError(document.source_path)
FileExistsError: /usr/src/paperless/media/documents/originals/12/Adobe Scan 26 Feb 2022 (1).pdf
```

### Steps to reproduce

I presume it has something to do with the spaces in the name?

### Webserver logs

```bash
N/A I believe, it's an importing issue
```

### Paperless-ngx version

1.10.0

### Host OS

Raspbian (Armv7) -> Ubuntu Server(i386, I think)

### Installation method

Docker - official image

**Comment by stumpylog** [comment]
- if you match versions as the message suggested, does it work?
- is the import to a clean instance?
- does the listed file actually exist?

**Comment by bee-san** [comment]
Ooh thanks! Version downgrade works 🤔 

However, I cannot upload files or run the import script because of a permissions error and I'd appreciate a helping hand 🙈 

Per the docs if I am having permission issues with the `consume` folder:

>  If your UID and GID on the host system is 1000 (the default for the first normal user on most systems), it will work out of the box without any modifications.

My UID and GID are both 1000. _I_ can write into the consume folder just fine, I even updated the `env` file to make sure it's using 1000 :)

```
PAPERLESS_TIME_ZONE=Europe/London
PAPERLESS_OCR_LANGUAGE=eng
USERMAP_UID=1000
USERMAP_GID=1000
PAPERLESS_SECRET_KEY=XXX
```

My compose.yaml:

```
# docker-compose file for running paperless from the Docker Hub.
# This file contains everything paperless needs to run.
# Paperless supports amd64, arm and arm64 hardware.
#
# All compose files of paperless configure paperless in the following way:
#
# - Paperless is (re)started on system boot, if it was running before shutdown.
# - Docker volumes for storing data are managed by Docker.
# - Folders for importing and exporting files are created in the same directory
#   as this file and mounted to the correct folders inside the container.
# - Paperless listens on port 8000.
#
# SQLite is used as the database. The SQLite file is stored in the data volume.
#
# To install and update paperless with this file, do the following:
#
# - Copy this file as 'docker-compose.yml' and the files 'docker-compose.env'
#   and '.env' into a folder.
# - Run 'docker-compose pull'.
# - Run 'docker-compose run --rm webserver createsuperuser' to create a user.
# - Run 'docker-compose up -d'.
#
# For more extensive installation and update instructions, refer to the
# documentation.

version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:1.10.2
    restart: unless-stopped
    depends_on:
      - broker
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - /mnt/ssd/paperless-ngx/media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - /mnt/ssd/paperless-ngx/consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379


volumes:
  data:
  redisdata:
```

The logs spit out a few errors too:

```

[2022-12-30 21:41:33,321] [ERROR] [paperless.consumer] The following error occurred while consuming sample.pdf: [Errno 13] Permission denied: '/usr/src/paperless/media/media.lock'
Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/consumer.py", line 392, in try_consume_file
    with FileLock(settings.MEDIA_LOCK):
  File "/usr/local/lib/python3.9/site-packages/filelock/_api.py", line 220, in __enter__
    self.acquire()
  File "/usr/local/lib/python3.9/site-packages/filelock/_api.py", line 173, in acquire
    self._acquire()
  File "/usr/local/lib/python3.9/site-packages/filelock/_unix.py", line 35, in _acquire
    fd = os.open(self._lock_file, open_mode)
PermissionError: [Errno 13] Permission denied: '/usr/src/paperless/media/media.lock'
[2022-12-30 21:41:33,322] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-38y9u6fr
[2022-12-30 21:41:33,338] [ERROR] [paperless.handlers] Updating PaperlessTask failed: no such column: documents_paperlesstask.task_args
[2022-12-30 21:41:33,537] [ERROR] [paperless.handlers] Setting PaperlessTask started failed: no such column: documents_paperlesstask.task_args
[2022-12-30 21:41:33,569] [ERROR] [paperless.handlers] Updating PaperlessTask failed: no such column: documents_paperlesstask.task_args
```

**Comment by stumpylog** [comment]
The error looks to be in the media folder, not the consume folder.  Can your user write to `/mnt/ssd/paperless-ngx/media`?

**Comment by bee-san** [comment]
> /mnt/ssd/paperless-ngx/media

Yup 🤔  It is also `chmod 777`'d:

```
drwxrwxrwx  3 root   root    4096 Dec 30 23:50 media
```
