### ISSUE TITLE
[BUG] Consumption of eml files in 1.11.2

### ISSUE THREAD

**Issue by hspe98** [paperless-ngx/paperless-ngx#2285]
### Description

The import of mails as .eml files isn't working.

### Steps to reproduce

1. Mark email as unread
2. Paperless consumes the mail
3. ... puts it in the queue
4. ... gives error message

mail config:
![error](https://user-images.githubusercontent.com/7887268/210122979-b9d584ab-a5ac-4e60-a968-43be089f552b.png)

### Webserver logs

```bash
[2022-12-31 03:55:39,164] [ERROR] [paperless.consumer] Error while consuming document private mail.eml: Error while converting document to PDF: 404 Client Error: Not Found for url: http://gotenberg:3000/forms/chromium/convert/html

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_mail/parsers.py", line 275, in generate_pdf_from_mail

    response.raise_for_status()  # ensure we notice bad responses

  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status

    raise HTTPError(http_error_msg, response=self)

requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://gotenberg:3000/forms/chromium/convert/html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/consumer.py", line 337, in try_consume_file

    document_parser.parse(self.path, mime_type, self.filename)

  File "/usr/src/paperless/src/paperless_mail/parsers.py", line 139, in parse

    self.archive_path = self.generate_pdf(document_path)

  File "/usr/src/paperless/src/paperless_mail/parsers.py", line 162, in generate_pdf

    pdf_collection.append(("1_mail.pdf", self.generate_pdf_from_mail(mail)))

  File "/usr/src/paperless/src/paperless_mail/parsers.py", line 277, in generate_pdf_from_mail

    raise ParseError(f"Error while converting document to PDF: {err}")

documents.parsers.ParseError: Error while converting document to PDF: 404 Client Error: Not Found for url: http://gotenberg:3000/forms/chromium/convert/html
```

### Browser logs

```bash
private mail.eml: Error while converting document to PDF: 404 Client Error: Not Found for url: http://gotenberg:3000/forms/chromium/convert/html
```

### Paperless-ngx version

1.11.2

### Host OS

Raspberry Pi arm64

### Installation method

Docker - official image

### Browser

Chrome

### Other

Also the translation of the new feature isn't done already

**Comment by hspe98** [comment]
Gotenberg is up and running: It's possible to process .xlsx and .docx files.

**Comment by stumpylog** [comment]
Double check you have updated the gotenberg command: section as per the example compose files.

**Comment by hspe98** [comment]
Thank you for your quick help. Maybe it would be helpful to specify the needed change in the changelog.
