### ISSUE TITLE
[BUG] eml: filetype message/rfc822 not supported

### ISSUE THREAD

**Issue by Maik1** [paperless-ngx/paperless-ngx#2315]
### Description

With the latest updates it should be possible to process the whole mail message as eml.
However, on all emails I try to consume I get the following error:
File type message/rfc822 not supported

![image](https://user-images.githubusercontent.com/12293016/210221829-729f4335-1491-468a-8fba-f571637fc35a.png)

It does not matter if the mail is fetched via IMAP or manually uploaded as eml.
Attached the mail (eml zipped) which causes the explained errors.

### Steps to reproduce

1. Drag and drop [Sample eml.zip](https://github.com/paperless-ngx/paperless-ngx/files/10331149/Sample.eml.zip) file to webpage (unzip before usage)
2. Error: File type message/rfc822 not supported

### Webserver logs

```bash
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
R = retval = fun(*args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
return self.run(*args, **kwargs)
File "/usr/src/paperless/src/documents/tasks.py", line 179, in consume_file
document = Consumer().try_consume_file(
File "/usr/src/paperless/src/documents/consumer.py", line 298, in try_consume_file
self._fail(MESSAGE_UNSUPPORTED_TYPE, f"Unsupported mime type {mime_type}")
File "/usr/src/paperless/src/documents/consumer.py", line 91, in _fail
raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
documents.consumer.ConsumerError: Paperless-ngx v1.11.3.eml: Unsupported mime type message/rfc822
```

### Browser logs

```bash
Paperless-ngx v1.11.3.eml
Dateityp message/rfc822 nicht unterstützt
--> File type message/rfc822 not supported

[2023-01-02 11:40:01,375] [INFO] [paperless.consumer] Consuming Paperless-ngx v1.11.3.eml
[2023-01-02 11:40:01,389] [DEBUG] [paperless.consumer] Detected mime type: message/rfc822
[2023-01-02 11:40:01,395] [ERROR] [paperless.consumer] Unsupported mime type message/rfc822
```

### Paperless-ngx version

1.11.3

### Host OS

unraid 6.11.5

### Installation method

Docker - official image

### Browser

Chrome

**Comment by stumpylog** [comment]
Have you enabled Tika?  That's documented as a requirement for consuming emails

**Comment by stumpylog** [comment]
If enabling Tika as required doesn't work, feel free to let us know.

**Comment by Maik1** [comment]
You're right. After setting up a Tika and Gotenberg server it works flawless.
Not sure how I overlooked that these two instances are required for eml parsing.

Thanks a lot for your help.
