### ISSUE TITLE
[BUG] App crash if consume directory contains problematic content

### ISSUE THREAD

**Issue by stevenengland** [paperless-ngx/paperless-ngx#2318]
### Description

If I add an empty .txt (for testing purposes, not a real thing...) file to the consume dir, the following happens:

```
Jan  2 14:41:45 paperless-ngx celery[49752]: [2023-01-02 14:41:45,830] [INFO] [paperless.consumer] Consuming new_test.txt
Jan  2 14:41:45 paperless-ngx celery[49752]: [2023-01-02 14:41:45,856] [ERROR] [paperless.consumer] Unsupported mime type inode/x-empty
Jan  2 14:41:45 paperless-ngx celery[49752]: [2023-01-02 14:41:45,879] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[fb1178ba-6185-43d2-a8d6-e3839b9d49cc] raised unexpected: ConsumerError('new_test.txt: Unsupported mime type inode/x-empty')
Jan  2 14:41:45 paperless-ngx celery[49752]: Traceback (most recent call last):
Jan  2 14:41:45 paperless-ngx celery[49752]:   File "/opt/paperless_ngx/.venv/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
Jan  2 14:41:45 paperless-ngx celery[49752]:     R = retval = fun(*args, **kwargs)
Jan  2 14:41:45 paperless-ngx celery[49752]:   File "/opt/paperless_ngx/.venv/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
Jan  2 14:41:45 paperless-ngx celery[49752]:     return self.run(*args, **kwargs)
Jan  2 14:41:45 paperless-ngx celery[49752]:   File "/opt/paperless_ngx/src/documents/tasks.py", line 179, in consume_file
Jan  2 14:41:45 paperless-ngx celery[49752]:     document = Consumer().try_consume_file(
Jan  2 14:41:45 paperless-ngx celery[49752]:   File "/opt/paperless_ngx/src/documents/consumer.py", line 298, in try_consume_file
Jan  2 14:41:45 paperless-ngx celery[49752]:     self._fail(MESSAGE_UNSUPPORTED_TYPE, f"Unsupported mime type {mime_type}")
Jan  2 14:41:45 paperless-ngx celery[49752]:   File "/opt/paperless_ngx/src/documents/consumer.py", line 91, in _fail
Jan  2 14:41:45 paperless-ngx celery[49752]:     raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
Jan  2 14:41:45 paperless-ngx celery[49752]: documents.consumer.ConsumerError: new_test.txt: Unsupported mime type inode/x-empty
Jan  2 14:41:51 paperless-ngx python3[49789]: ansible-ansible.builtin.systemd Invoked with name=paperless-webserver enabled=True masked=False state=started daemon_reload=False daemon_reexec=False scope=system no_block=False force=None
Jan  2 14:41:52 paperless-ngx celery[49791]: [2023-01-02 14:41:52,240] [INFO] [paperless.consumer] Consuming scanner_001129.pdf
Jan  2 14:41:53 paperless-ngx celery[49662]: [2023-01-02 14:41:53,322] [INFO] [celery.worker.strategy] Task documents.tasks.consume_file[9f4c41af-f426-41c8-b671-72e5559d9fe9] received
Jan  2 14:41:58 paperless-ngx python3[49827]: ansible-ansible.builtin.systemd Invoked with name=paperless-task-queue enabled=True masked=False state=started daemon_reload=False daemon_reexec=False scope=system no_block=False force=None
Jan  2 14:41:58 paperless-ngx systemd[1]: Reloading.
Jan  2 14:42:03 paperless-ngx celery[49791]: [2023-01-02 14:42:02,992] [WARNING] [paperless.parsing.tesseract] Error while getting text from PDF document with pdfminer.six
Jan  2 14:42:03 paperless-ngx celery[49791]: Traceback (most recent call last):
Jan  2 14:42:03 paperless-ngx celery[49791]:   File "/opt/paperless_ngx/src/paperless_tesseract/parsers.py", line 140, in extract_text
Jan  2 14:42:03 paperless-ngx celery[49791]:     lang = detect(stripped)
Jan  2 14:42:03 paperless-ngx celery[49791]:   File "/opt/paperless_ngx/.venv/lib/python3.10/site-packages/langdetect/detector_factory.py", line 130, in detect
Jan  2 14:42:03 paperless-ngx celery[49791]:     return detector.detect()
Jan  2 14:42:03 paperless-ngx celery[49791]:   File "/opt/paperless_ngx/.venv/lib/python3.10/site-packages/langdetect/detector.py", line 136, in detect
Jan  2 14:42:03 paperless-ngx celery[49791]:     probabilities = self.get_probabilities()
Jan  2 14:42:03 paperless-ngx celery[49791]:   File "/opt/paperless_ngx/.venv/lib/python3.10/site-packages/langdetect/detector.py", line 143, in get_probabilities
Jan  2 14:42:03 paperless-ngx celery[49791]:     self._detect_block()
Jan  2 14:42:03 paperless-ngx celery[49791]:   File "/opt/paperless_ngx/.venv/lib/python3.10/site-packages/langdetect/detector.py", line 150, in _detect_block
Jan  2 14:42:03 paperless-ngx celery[49791]:     raise LangDetectException(ErrorCode.CantDetectError, 'No features in text.')
Jan  2 14:42:03 paperless-ngx celery[49791]: langdetect.lang_detect_exception.LangDetectException: No features in text.
```

I think the consumer and task scheduler service should be more resilient towards situations like this.

### Steps to reproduce

Add a empty .txt file to the consume dir.

### Webserver logs

```bash
-
```

### Paperless-ngx version

1.11.3

### Host OS

Ubuntu 22.04

### Installation method

Bare metal

### Browser

-

### Configuration changes

-

### Other

-

**Comment by stumpylog** [comment]
I'm not seeing the problem here.  The consumer handled the problem and reported what the issue is

**Comment by stumpylog** [comment]
Testing consumption with an empty file, this is exactly what I expect to happen.  The message is informative, the error is handled, logged and doesn't affect following consumption.

**Comment by stevenengland** [comment]
Hi together,

there must be something. Now, even if I try to read pdf files this error occurs and the paperless-task-queue service enters failed state, never recovers from that:

```
x paperless-task-queue.service - Paperless Celery Workers
     Loaded: loaded (/etc/systemd/system/paperless-task-queue.service; enabled; vendor preset: enabled)
     Active: failed (Result: oom-kill) since Mon 2023-01-02 15:07:25 CET; 2h 0min ago
    Process: 119 ExecStart=/opt/paperless_ngx/.venv/bin/celery --app paperless worker --loglevel INFO (code=killed, signal=KILL)
   Main PID: 119 (code=killed, signal=KILL)
        CPU: 1min 31.083s

Jan 02 15:07:25 paperless-ngx systemd[1]: paperless-task-queue.service: Killing process 382 (n/a) with signal SIGKILL.
Jan 02 15:07:25 paperless-ngx systemd[1]: paperless-task-queue.service: Killing process 384 (n/a) with signal SIGKILL.
Jan 02 15:07:25 paperless-ngx systemd[1]: paperless-task-queue.service: Killing process 386 (n/a) with signal SIGKILL.
Jan 02 15:07:25 paperless-ngx systemd[1]: paperless-task-queue.service: Killing process 388 (n/a) with signal SIGKILL.
Jan 02 15:07:25 paperless-ngx systemd[1]: paperless-task-queue.service: Killing process 566 (n/a) with signal SIGKILL.
Jan 02 15:07:25 paperless-ngx systemd[1]: paperless-task-queue.service: Killing process 570 ([celeryd: celer) with signal SIGKILL.
Jan 02 15:07:25 paperless-ngx systemd[1]: paperless-task-queue.service: Main process exited, code=killed, status=9/KILL
Jan 02 15:07:25 paperless-ngx systemd[1]: paperless-task-queue.service: Killing process 570 ([celeryd: celer) with signal SIGKILL.
Jan 02 15:07:25 paperless-ngx systemd[1]: paperless-task-queue.service: Failed with result 'oom-kill'.
Jan 02 15:07:25 paperless-ngx systemd[1]: paperless-task-queue.service: Consumed 1min 31.083s CPU time.
```

Here is a corresponding log:

```
Jan  2 15:05:36 paperless-ngx celery[542]: [2023-01-02 15:05:36,083] [INFO] [paperless.consumer] Consuming scanner_001130.pdf
Jan  2 15:05:43 paperless-ngx celery[542]: [2023-01-02 15:05:43,106] [WARNING] [paperless.parsing.tesseract] Error while getting text from PDF document with pdfminer.six
Jan  2 15:05:43 paperless-ngx celery[542]: Traceback (most recent call last):
Jan  2 15:05:43 paperless-ngx celery[542]:   File "/opt/paperless_ngx/src/paperless_tesseract/parsers.py", line 140, in extract_text
Jan  2 15:05:43 paperless-ngx celery[542]:     lang = detect(stripped)
Jan  2 15:05:43 paperless-ngx celery[542]:   File "/opt/paperless_ngx/.venv/lib/python3.10/site-packages/langdetect/detector_factory.py", line 130, in detect
Jan  2 15:05:43 paperless-ngx celery[542]:     return detector.detect()
Jan  2 15:05:43 paperless-ngx celery[542]:   File "/opt/paperless_ngx/.venv/lib/python3.10/site-packages/langdetect/detector.py", line 136, in detect
Jan  2 15:05:43 paperless-ngx celery[542]:     probabilities = self.get_probabilities()
Jan  2 15:05:43 paperless-ngx celery[542]:   File "/opt/paperless_ngx/.venv/lib/python3.10/site-packages/langdetect/detector.py", line 143, in get_probabilities
Jan  2 15:05:43 paperless-ngx celery[542]:     self._detect_block()
Jan  2 15:05:43 paperless-ngx celery[542]:   File "/opt/paperless_ngx/.venv/lib/python3.10/site-packages/langdetect/detector.py", line 150, in _detect_block
Jan  2 15:05:43 paperless-ngx celery[542]:     raise LangDetectException(ErrorCode.CantDetectError, 'No features in text.')
Jan  2 15:05:43 paperless-ngx celery[542]: langdetect.lang_detect_exception.LangDetectException: No features in text.
Jan  2 15:05:55 paperless-ngx systemd[1]: paperless-task-queue.service: A process of this unit has been killed by the OOM killer.
Jan  2 15:05:55 paperless-ngx celery[119]: worker: Warm shutdown (MainProcess)
Jan  2 15:05:55 paperless-ngx celery[542]: [2023-01-02 15:05:55,287] [ERROR] [ocrmypdf._exec.ghostscript]
Jan  2 15:06:22 paperless-ngx celery[542]: [2023-01-02 15:06:22,654] [INFO] [ocrmypdf._pipeline] page is facing ⇩, confidence 12.16 - will rotate ↻
Jan  2 15:07:25 paperless-ngx systemd[1]: paperless-task-queue.service: State 'stop-sigterm' timed out. Killing.
```

I'll dig deeper into this today in the evening. Do you have any suggestion for me what I should try?

**Comment by shamoon** [comment]
`oom-kill` meaning out of memory? Bare metal installs are a bit harder to troubleshoot (remotely)

**Comment by stumpylog** [comment]
Yeah, I'm seeing a lot in the logs of OOM being the cause here, not an empty file in the consume directory. Depending on settings and the input, OCR can take up a lot of time and memory
