### ISSUE TITLE
[BUG] ValueError while importing PDF generated with AirMail

### ISSUE THREAD

**Issue by VanillaChief** [paperless-ngx/paperless-ngx#2356]
### Description

When I try to upload a PDF of an e-mail generated with AirMail I get a ValueError (see log below).
The same e-mail PDF gets ingested without problems when I generate the PDF with Apple Mail or GMail. Same behavior with different kinds of e-mail.

### Steps to reproduce

1. Use the AirMail Export as PDF Feature to Export an E-Mail
2. Upload this PDF to Paperless

### Webserver logs

```bash
´´´
Jan 05 22:19:04 documents.parsers.ParseError: ValueError: overflow/underflow converting -62806905613665923545118765947072571844917402415851704276502104337195767489372368608328360908813210077702385327753039275704840374816493044728951098869230380460395634970686121290256680885128908355274696335042432121708481169296888605344698926857336602911999308761597986841823781496644915736629278359895320559616 to 64-bit integer
Jan 05 22:19:04
Jan 05 22:19:04 The above exception was the direct cause of the following exception:
Jan 05 22:19:04
Jan 05 22:19:04 Traceback (most recent call last):
Jan 05 22:19:04 File "/usr/local/lib/python3.10/dist-packages/celery/app/trace.py", line 451, in trace_task
Jan 05 22:19:04 R = retval = fun(*args, **kwargs)
Jan 05 22:19:04 File "/usr/local/lib/python3.10/dist-packages/celery/app/trace.py", line 734, in __protected_call__
Jan 05 22:19:04 return self.run(*args, **kwargs)
Jan 05 22:19:04 File "/app/code/src/documents/tasks.py", line 179, in consume_file
Jan 05 22:19:04 document = Consumer().try_consume_file(
Jan 05 22:19:04 File "/app/code/src/documents/consumer.py", line 356, in try_consume_file
Jan 05 22:19:04 self._fail(
Jan 05 22:19:04 File "/app/code/src/documents/consumer.py", line 91, in _fail
Jan 05 22:19:04 raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
´´´
```

### Paperless-ngx version

Paperless-ngx 1.11.3

### Host OS

Cloudron

### Installation method

Docker - official image

### Browser

Chrome

**Comment by stumpylog** [comment]
- There should be more exception information above what you posted.  Please provide that
- A sample file always helps
- Strongly seems like this AirMail app is producing a corrupted PDF in some way

**Comment by VanillaChief** [comment]
sorry, will send the rest. Just started a big import of some other PDFs but then will recreate the error and give more info

**Comment by VanillaChief** [comment]
I hope this is the whole error log:
```
Jan 06 09:17:01 return PdfInfo(
Jan 06 09:17:01 File "/usr/local/lib/python3.10/dist-packages/ocrmypdf/pdfinfo/info.py", line 934, in __init__
Jan 06 09:17:01 self._pages = _pdf_pageinfo_concurrent(
Jan 06 09:17:01 File "/usr/local/lib/python3.10/dist-packages/ocrmypdf/pdfinfo/info.py", line 711, in _pdf_pageinfo_concurrent
Jan 06 09:17:01 executor(
Jan 06 09:17:01 File "/usr/local/lib/python3.10/dist-packages/ocrmypdf/_concurrent.py", line 87, in __call__
Jan 06 09:17:01 self._execute(
Jan 06 09:17:01 File "/usr/local/lib/python3.10/dist-packages/ocrmypdf/builtin_plugins/concurrency.py", line 141, in _execute
Jan 06 09:17:01 result = future.result()
Jan 06 09:17:01 File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
Jan 06 09:17:01 return self.__get_result()
Jan 06 09:17:01 File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
Jan 06 09:17:01 raise self._exception
Jan 06 09:17:01 File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Jan 06 09:17:01 result = self.fn(*self.args, **self.kwargs)
Jan 06 09:17:01 File "/usr/local/lib/python3.10/dist-packages/ocrmypdf/pdfinfo/info.py", line 668, in _pdf_pageinfo_sync
Jan 06 09:17:01 page = PageInfo(pdf, pageno, infile, check_pages, detailed_analysis)
Jan 06 09:17:01 File "/usr/local/lib/python3.10/dist-packages/ocrmypdf/pdfinfo/info.py", line 748, in __init__
Jan 06 09:17:01 self._gather_pageinfo(pdf, pageno, infile, check_pages, detailed_analysis)
Jan 06 09:17:01 File "/usr/local/lib/python3.10/dist-packages/ocrmypdf/pdfinfo/info.py", line 794, in _gather_pageinfo
Jan 06 09:17:01 for info in _process_content_streams(
Jan 06 09:17:01 File "/usr/local/lib/python3.10/dist-packages/ocrmypdf/pdfinfo/info.py", line 588, in _process_content_streams
Jan 06 09:17:01 contentsinfo = _interpret_contents(container, initial_shorthand)
Jan 06 09:17:01 File "/usr/local/lib/python3.10/dist-packages/ocrmypdf/pdfinfo/info.py", line 217, in _interpret_contents
Jan 06 09:17:01 _normalize_stack(parse_content_stream(contentstream, operator_whitelist))
Jan 06 09:17:01 File "/usr/local/lib/python3.10/dist-packages/pikepdf/models/_content_stream.py", line 94, in parse_content_stream
Jan 06 09:17:01 page._parse_page_contents_grouped(operators),
Jan 06 09:17:01 ValueError: overflow/underflow converting -73705418529354947826052831845966428434317087455589724133713560316663805774651461522544313590466145041751722606948728880086720747990421278482703872096278337368706880077565724259271429544122410250392776832756280563386256941763776996076521374055824311681492118794983235762712375708113392071793806588389110054912 to 64-bit integer
Jan 06 09:17:01
Jan 06 09:17:01 The above exception was the direct cause of the following exception:
Jan 06 09:17:01
Jan 06 09:17:01 Traceback (most recent call last):
Jan 06 09:17:01 File "/app/code/src/documents/consumer.py", line 337, in try_consume_file
Jan 06 09:17:01 document_parser.parse(self.path, mime_type, self.filename)
Jan 06 09:17:01 File "/app/code/src/paperless_tesseract/parsers.py", line 379, in parse
Jan 06 09:17:01 raise ParseError(f"{e.__class__.__name__}: {str(e)}") from e
Jan 06 09:17:01 documents.parsers.ParseError: ValueError: overflow/underflow converting -73705418529354947826052831845966428434317087455589724133713560316663805774651461522544313590466145041751722606948728880086720747990421278482703872096278337368706880077565724259271429544122410250392776832756280563386256941763776996076521374055824311681492118794983235762712375708113392071793806588389110054912 to 64-bit integer
Jan 06 09:17:01 [2023-01-06 08:17:01,642] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[863bdccb-a9bc-4135-99d6-b0451ce0eeb6] raised unexpected: ConsumerError('TEST.pdf: Error while consuming document TEST.pdf: ValueError: overflow/underflow converting -73705418529354947826052831845966428434317087455589724133713560316663805774651461522544313590466145041751722606948728880086720747990421278482703872096278337368706880077565724259271429544122410250392776832756280563386256941763776996076521374055824311681492118794983235762712375708113392071793806588389110054912 to 64-bit integer')
Jan 06 09:17:01 Traceback (most recent call last):
Jan 06 09:17:01 File "/app/code/src/paperless_tesseract/parsers.py", line 321, in parse
Jan 06 09:17:01 ocrmypdf.ocr(**args)
Jan 06 09:17:01 File "/usr/local/lib/python3.10/dist-packages/ocrmypdf/api.py", line 332, in ocr
Jan 06 09:17:01 return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)
Jan 06 09:17:01 File "/usr/local/lib/python3.10/dist-packages/ocrmypdf/_sync.py", line 378, in run_pipeline
Jan 06 09:17:01 pdfinfo = get_pdfinfo(
Jan 06 09:17:01 File "/usr/local/lib/python3.10/dist-packages/ocrmypdf/_pipeline.py", line 165, in get_pdfinfo
Jan 06 09:17:01 return PdfInfo(
Jan 06 09:17:01 File "/usr/local/lib/python3.10/dist-packages/ocrmypdf/pdfinfo/info.py", line 934, in __init__
Jan 06 09:17:01 self._pages = _pdf_pageinfo_concurrent(
Jan 06 09:17:01 File "/usr/local/lib/python3.10/dist-packages/ocrmypdf/pdfinfo/info.py", line 711, in _pdf_pageinfo_concurrent
Jan 06 09:17:01 executor(
Jan 06 09:17:01 File "/usr/local/lib/python3.10/dist-packages/ocrmypdf/_concurrent.py", line 87, in __call__
Jan 06 09:17:01 self._execute(
Jan 06 09:17:01 File "/usr/local/lib/python3.10/dist-packages/ocrmypdf/builtin_plugins/concurrency.py", line 141, in _execute
Jan 06 09:17:01 result = future.result()
Jan 06 09:17:01 File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
Jan 06 09:17:01 return self.__get_result()
Jan 06 09:17:01 File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
Jan 06 09:17:01 raise self._exception
Jan 06 09:17:01 File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Jan 06 09:17:01 result = self.fn(*self.args, **self.kwargs)
Jan 06 09:17:01 File "/usr/local/lib/python3.10/dist-packages/ocrmypdf/pdfinfo/info.py", line 668, in _pdf_pageinfo_sync
Jan 06 09:17:01 page = PageInfo(pdf, pageno, infile, check_pages, detailed_analysis)
Jan 06 09:17:01 File "/usr/local/lib/python3.10/dist-packages/ocrmypdf/pdfinfo/info.py", line 748, in __init__
Jan 06 09:17:01 self._gather_pageinfo(pdf, pageno, infile, check_pages, detailed_analysis)
Jan 06 09:17:01 File "/usr/local/lib/python3.10/dist-packages/ocrmypdf/pdfinfo/info.py", line 794, in _gather_pageinfo
Jan 06 09:17:01 for info in _process_content_streams(
Jan 06 09:17:01 File "/usr/local/lib/python3.10/dist-packages/ocrmypdf/pdfinfo/info.py", line 588, in _process_content_streams
Jan 06 09:17:01 contentsinfo = _interpret_contents(container, initial_shorthand)
Jan 06 09:17:01 File "/usr/local/lib/python3.10/dist-packages/ocrmypdf/pdfinfo/info.py", line 217, in _interpret_contents
Jan 06 09:17:01 _normalize_stack(parse_content_stream(contentstream, operator_whitelist))
Jan 06 09:17:01 File "/usr/local/lib/python3.10/dist-packages/pikepdf/models/_content_stream.py", line 94, in parse_content_stream
Jan 06 09:17:01 page._parse_page_contents_grouped(operators),
Jan 06 09:17:01 ValueError: overflow/underflow converting -73705418529354947826052831845966428434317087455589724133713560316663805774651461522544313590466145041751722606948728880086720747990421278482703872096278337368706880077565724259271429544122410250392776832756280563386256941763776996076521374055824311681492118794983235762712375708113392071793806588389110054912 to 64-bit integer
Jan 06 09:17:01
Jan 06 09:17:01 The above exception was the direct cause of the following exception:
Jan 06 09:17:01
Jan 06 09:17:01 Traceback (most recent call last):
Jan 06 09:17:01 File "/usr/local/lib/python3.10/dist-packages/asgiref/sync.py", line 302, in main_wrap
Jan 06 09:17:01 raise exc_info[1]
Jan 06 09:17:01 File "/app/code/src/documents/consumer.py", line 337, in try_consume_file
Jan 06 09:17:01 document_parser.parse(self.path, mime_type, self.filename)
Jan 06 09:17:01 File "/app/code/src/paperless_tesseract/parsers.py", line 379, in parse
Jan 06 09:17:01 raise ParseError(f"{e.__class__.__name__}: {str(e)}") from e
Jan 06 09:17:01 documents.parsers.ParseError: ValueError: overflow/underflow converting -73705418529354947826052831845966428434317087455589724133713560316663805774651461522544313590466145041751722606948728880086720747990421278482703872096278337368706880077565724259271429544122410250392776832756280563386256941763776996076521374055824311681492118794983235762712375708113392071793806588389110054912 to 64-bit integer
Jan 06 09:17:01
Jan 06 09:17:01 The above exception was the direct cause of the following exception:
Jan 06 09:17:01
Jan 06 09:17:01 Traceback (most recent call last):
Jan 06 09:17:01 File "/usr/local/lib/python3.10/dist-packages/celery/app/trace.py", line 451, in trace_task
Jan 06 09:17:01 R = retval = fun(*args, **kwargs)
Jan 06 09:17:01 File "/usr/local/lib/python3.10/dist-packages/celery/app/trace.py", line 734, in __protected_call__
Jan 06 09:17:01 return self.run(*args, **kwargs)
Jan 06 09:17:01 File "/app/code/src/documents/tasks.py", line 179, in consume_file
Jan 06 09:17:01 document = Consumer().try_consume_file(
Jan 06 09:17:01 File "/app/code/src/documents/consumer.py", line 356, in try_consume_file
Jan 06 09:17:01 self._fail(
Jan 06 09:17:01 File "/app/code/src/documents/consumer.py", line 91, in _fail
Jan 06 09:17:01 raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
Jan 06 09:17:01 documents.consumer.ConsumerError: TEST.pdf: Error while consuming document TEST.pdf: ValueError: overflow/underflow converting -73705418529354947826052831845966428434317087455589724133713560316663805774651461522544313590466145041751722606948728880086720747990421278482703872096278337368706880077565724259271429544122410250392776832756280563386256941763776996076521374055824311681492118794983235762712375708113392071793806588389110054912 to 64-bit integer
Jan 06 07:23:31 12:M 06 Jan 2023 06:23:31.063 * 10 changes in 300 seconds. Saving...
Jan 06 07:23:31 12:M 06 Jan 2023 06:23:31.067 * Background saving started by pid 260
Jan 06 07:23:31 260:C 06 Jan 2023 06:23:31.076 * DB saved on disk
Jan 06 07:23:31 260:C 06 Jan 2023 06:23:31.078 * RDB: 0 MB of memory used by copy-on-write
Jan 06 07:23:31 12:M 06 Jan 2023 06:23:31.169 * Background saving terminated with success
Jan 06 07:30:00 12:M 06 Jan 2023 06:30:00.145 * 10 changes in 300 seconds. Saving...
Jan 06 07:30:00 12:M 06 Jan 2023 06:30:00.149 * Background saving started by pid 261
Jan 06 07:30:00 261:C 06 Jan 2023 06:30:00.163 * DB saved on disk
Jan 06 07:30:00 261:C 06 Jan 2023 06:30:00.167 * RDB: 0 MB of memory used by copy-on-write
Jan 06 07:30:00 12:M 06 Jan 2023 06:30:00.250 * Background saving terminated with success
Jan 06 07:35:11 12:M 06 Jan 2023 06:35:11.081 * 10 changes in 300 seconds. Saving...
Jan 06 07:35:11 12:M 06 Jan 2023 06:35:11.085 * Background saving started by pid 262
Jan 06 07:35:11 262:C 06 Jan 2023 06:35:11.106 * DB saved on disk
Jan 06 07:35:11 262:C 06 Jan 2023 06:35:11.108 * RDB: 0 MB of memory used by copy-on-write
Jan 06 07:35:11 12:M 06 Jan 2023 06:35:11.187 * Background saving terminated with success
Jan 06 07:40:12 12:M 06 Jan 2023 06:40:12.022 * 10 changes in 300 seconds. Saving...
Jan 06 07:40:12 12:M 06 Jan 2023 06:40:12.026 * Background saving started by pid 263
Jan 06 07:40:12 263:C 06 Jan 2023 06:40:12.038 * DB saved on disk
Jan 06 07:40:12 263:C 06 Jan 2023 06:40:12.041 * RDB: 0 MB of memory used by copy-on-write
Jan 06 07:40:12 12:M 06 Jan 2023 06:40:12.128 * Background saving terminated with success
Jan 06 07:48:31 12:M 06 Jan 2023 06:48:31.217 * 10 changes in 300 seconds. Saving...
Jan 06 07:48:31 12:M 06 Jan 2023 06:48:31.224 * Background saving started by pid 264
Jan 06 07:48:31 264:C 06 Jan 2023 06:48:31.236 * DB saved on disk
Jan 06 07:48:31 264:C 06 Jan 2023 06:48:31.238 * RDB: 0 MB of memory used by copy-on-write
Jan 06 07:48:31 12:M 06 Jan 2023 06:48:31.327 * Background saving terminated with success
Jan 06 07:53:32 12:M 06 Jan 2023 06:53:32.097 * 10 changes in 300 seconds. Saving...
Jan 06 07:53:32 12:M 06 Jan 2023 06:53:32.103 * Background saving started by pid 265
Jan 06 07:53:32 265:C 06 Jan 2023 06:53:32.115 * DB saved on disk
Jan 06 07:53:32 265:C 06 Jan 2023 06:53:32.119 * RDB: 0 MB of memory used by copy-on-write
Jan 06 07:53:32 12:M 06 Jan 2023 06:53:32.205 * Background saving terminated with success
Jan 06 08:00:00 12:M 06 Jan 2023 07:00:00.226 * 10 changes in 300 seconds. Saving...
Jan 06 08:00:00 12:M 06 Jan 2023 07:00:00.231 * Background saving started by pid 266
Jan 06 08:00:00 266:C 06 Jan 2023 07:00:00.244 * DB saved on disk
Jan 06 08:00:00 266:C 06 Jan 2023 07:00:00.247 * RDB: 0 MB of memory used by copy-on-write
Jan 06 08:00:00 12:M 06 Jan 2023 07:00:00.333 * Background saving terminated with success
Jan 06 08:05:01 12:M 06 Jan 2023 07:05:01.098 * 10 changes in 300 seconds. Saving...
Jan 06 08:05:01 12:M 06 Jan 2023 07:05:01.102 * Background saving started by pid 267
Jan 06 08:05:01 267:C 06 Jan 2023 07:05:01.115 * DB saved on disk
Jan 06 08:05:01 267:C 06 Jan 2023 07:05:01.116 * RDB: 0 MB of memory used by copy-on-write
Jan 06 08:05:01 12:M 06 Jan 2023 07:05:01.203 * Background saving terminated with success
Jan 06 08:10:02 12:M 06 Jan 2023 07:10:02.047 * 10 changes in 300 seconds. Saving...
Jan 06 08:10:02 12:M 06 Jan 2023 07:10:02.051 * Background saving started by pid 268
Jan 06 08:10:02 268:C 06 Jan 2023 07:10:02.061 * DB saved on disk
Jan 06 08:10:02 268:C 06 Jan 2023 07:10:02.063 * RDB: 0 MB of memory used by copy-on-write
Jan 06 08:10:02 12:M 06 Jan 2023 07:10:02.154 * Background saving terminated with success
Jan 06 08:16:51 12:M 06 Jan 2023 07:16:51.586 * 10 changes in 300 seconds. Saving...
Jan 06 08:16:51 12:M 06 Jan 2023 07:16:51.588 * Background saving started by pid 269
Jan 06 08:16:51 269:C 06 Jan 2023 07:16:51.600 * DB saved on disk
Jan 06 08:16:51 269:C 06 Jan 2023 07:16:51.601 * RDB: 0 MB of memory used by copy-on-write
Jan 06 08:16:51 12:M 06 Jan 2023 07:16:51.690 * Background saving terminated with success
Jan 06 08:21:52 12:M 06 Jan 2023 07:21:52.019 * 10 changes in 300 seconds. Saving...
Jan 06 08:21:52 12:M 06 Jan 2023 07:21:52.023 * Background saving started by pid 270
Jan 06 08:21:52 270:C 06 Jan 2023 07:21:52.043 * DB saved on disk
Jan 06 08:21:52 270:C 06 Jan 2023 07:21:52.047 * RDB: 0 MB of memory used by copy-on-write
Jan 06 08:21:52 12:M 06 Jan 2023 07:21:52.124 * Background saving terminated with success
Jan 06 08:30:00 12:M 06 Jan 2023 07:30:00.202 * 10 changes in 300 seconds. Saving...
Jan 06 08:30:00 12:M 06 Jan 2023 07:30:00.204 * Background saving started by pid 271
Jan 06 08:30:00 271:C 06 Jan 2023 07:30:00.219 * DB saved on disk
Jan 06 08:30:00 271:C 06 Jan 2023 07:30:00.220 * RDB: 0 MB of memory used by copy-on-write
Jan 06 08:30:00 12:M 06 Jan 2023 07:30:00.307 * Background saving terminated with success
Jan 06 08:36:51 12:M 06 Jan 2023 07:36:51.870 * 10 changes in 300 seconds. Saving...
Jan 06 08:36:51 12:M 06 Jan 2023 07:36:51.876 * Background saving started by pid 272
Jan 06 08:36:51 272:C 06 Jan 2023 07:36:51.888 * DB saved on disk
Jan 06 08:36:51 272:C 06 Jan 2023 07:36:51.892 * RDB: 0 MB of memory used by copy-on-write
Jan 06 08:36:51 12:M 06 Jan 2023 07:36:51.978 * Background saving terminated with success
Jan 06 08:41:52 12:M 06 Jan 2023 07:41:52.076 * 10 changes in 300 seconds. Saving...
Jan 06 08:41:52 12:M 06 Jan 2023 07:41:52.083 * Background saving started by pid 273
Jan 06 08:41:52 273:C 06 Jan 2023 07:41:52.095 * DB saved on disk
Jan 06 08:41:52 273:C 06 Jan 2023 07:41:52.098 * RDB: 0 MB of memory used by copy-on-write
Jan 06 08:41:52 12:M 06 Jan 2023 07:41:52.184 * Background saving terminated with success
Jan 06 08:50:00 12:M 06 Jan 2023 07:50:00.200 * 10 changes in 300 seconds. Saving...
Jan 06 08:50:00 12:M 06 Jan 2023 07:50:00.203 * Background saving started by pid 274
Jan 06 08:50:00 274:C 06 Jan 2023 07:50:00.211 * DB saved on disk
Jan 06 08:50:00 274:C 06 Jan 2023 07:50:00.213 * RDB: 0 MB of memory used by copy-on-write
Jan 06 08:50:00 12:M 06 Jan 2023 07:50:00.305 * Background saving terminated with success
Jan 06 08:55:12 12:M 06 Jan 2023 07:55:12.106 * 10 changes in 300 seconds. Saving...
Jan 06 08:55:12 12:M 06 Jan 2023 07:55:12.110 * Background saving started by pid 275
Jan 06 08:55:12 275:C 06 Jan 2023 07:55:12.121 * DB saved on disk
Jan 06 08:55:12 275:C 06 Jan 2023 07:55:12.123 * RDB: 0 MB of memory used by copy-on-write
Jan 06 08:55:12 12:M 06 Jan 2023 07:55:12.213 * Background saving terminated with success
Jan 06 09:00:13 12:M 06 Jan 2023 08:00:13.066 * 10 changes in 300 seconds. Saving...
Jan 06 09:00:13 12:M 06 Jan 2023 08:00:13.073 * Background saving started by pid 276
Jan 06 09:00:13 276:C 06 Jan 2023 08:00:13.086 * DB saved on disk
Jan 06 09:00:13 276:C 06 Jan 2023 08:00:13.088 * RDB: 0 MB of memory used by copy-on-write
Jan 06 09:00:13 12:M 06 Jan 2023 08:00:13.175 * Background saving terminated with success
Jan 06 09:05:14 12:M 06 Jan 2023 08:05:14.064 * 10 changes in 300 seconds. Saving...
Jan 06 09:05:14 12:M 06 Jan 2023 08:05:14.071 * Background saving started by pid 277
Jan 06 09:05:14 277:C 06 Jan 2023 08:05:14.092 * DB saved on disk
Jan 06 09:05:14 277:C 06 Jan 2023 08:05:14.094 * RDB: 0 MB of memory used by copy-on-write
Jan 06 09:05:14 12:M 06 Jan 2023 08:05:14.173 * Background saving terminated with success
Jan 06 09:10:15 12:M 06 Jan 2023 08:10:15.093 * 10 changes in 300 seconds. Saving...
Jan 06 09:10:15 12:M 06 Jan 2023 08:10:15.096 * Background saving started by pid 278
Jan 06 09:10:15 278:C 06 Jan 2023 08:10:15.110 * DB saved on disk
Jan 06 09:10:15 278:C 06 Jan 2023 08:10:15.112 * RDB: 0 MB of memory used by copy-on-write
Jan 06 09:10:15 12:M 06 Jan 2023 08:10:15.198 * Background saving terminated with success
Jan 06 09:16:52 12:M 06 Jan 2023 08:16:52.289 * 10 changes in 300 seconds. Saving...
Jan 06 09:16:52 12:M 06 Jan 2023 08:16:52.295 * Background saving started by pid 279
Jan 06 09:16:52 279:C 06 Jan 2023 08:16:52.308 * DB saved on disk
Jan 06 09:16:52 279:C 06 Jan 2023 08:16:52.311 * RDB: 0 MB of memory used by copy-on-write
Jan 06 09:16:52 12:M 06 Jan 2023 08:16:52.397 * Background saving terminated with success
```
Hier ist the Testfile I used
[TEST.pdf](https://github.com/paperless-ngx/paperless-ngx/files/10358623/TEST.pdf)

Here is how the error is shown in the frontend:
![Screenshot 2023-01-06 at 09 19 43](https://user-images.githubusercontent.com/4238850/210959758-ca3e8014-60d2-4c75-ad3d-b5989ded23a7.png)

**Comment by stumpylog** [comment]
Looks like the error comes from really low down the dependencies, in this case from qpdf even:
```
 qpdf --check TEST.pdf
checking TEST.pdf
PDF Version: 1.3
File is not encrypted
File is not linearized
ERROR: overflow/underflow converting -73705418529354947826052831845966428434317087455589724133713560316663805774651461522544313590466145041751722606948728880086720747990421278482703872096278337368706880077565724259271429544122410250392776832756280563386256941763776996076521374055824311681492118794983235762712375708113392071793806588389110054912 to 64-bit integer
qpdf: errors detected
```

There's a very similar error report qpdf/qpdf/issues/408 which hasn't gotten much traction.  With the sample file, that may help.  Or the issue could be reported to Airmail, however they do.

At a guess though, the PDF isn't being formed correctly by the app.  Probably saying something is 1 type when it's another
