### ISSUE TITLE
[BUG] Can't access from local IP when URL is set.

### ISSUE THREAD

**Issue by DimitriDR** [paperless-ngx/paperless-ngx#2362]
### Description

I got a "Bad Request (400)" error when I try to access to my local IP server after setting up an external URL.

I tried several combinations from the Docker Compose (in environment part):

```
PAPERLESS_URL: https://paperless.domain.tld
PAPERLESS_ALLOWED_HOSTS: localhost, http://192.168.1.200, 192.168.1.200, 192.168.1.200:8010, http://192.168.1.200:8010
ALLOWED_HOSTS: "192.168.1.200,"
```

```
PAPERLESS_URL: https://paperless.domain.tld
PAPERLESS_ALLOWED_HOSTS: localhost, http://192.168.1.200, 192.168.1.200, 192.168.1.200:8010, http://192.168.1.200:8010
ALLOWED_HOSTS: "192.168.1.200"
```

```
PAPERLESS_URL: https://paperless.domain.tld
PAPERLESS_ALLOWED_HOSTS: localhost, 192.168.1.200, 192.168.1.200:8010
ALLOWED_HOSTS: 192.168.1.200
```

Absolutely nothing works.

And the console still displays the same message:

`django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '192.168.1.200:8010'. You may need to add '192.168.1.200' to ALLOWED_HOSTS.`

Thing I did billion times.

My whole Docker compose:

```
version: "3.9"

services:
  broker:
    image: docker.io/library/redis:7
    container_name: paperless-ngx-broker
    restart: unless-stopped
    volumes:
      - /volume1/docker/paperless-ngx/redis/:/data
    networks:
      - paperless-ngx-network

  db:
    image: docker.io/library/postgres:13
    container_name: paperless-ngx-database
    restart: unless-stopped
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
    volumes:
      - /volume1/docker/paperless-ngx/db/:/var/lib/postgresql/data
    networks:
      - paperless-ngx-network

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless-ngx
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - 8010:8000
    environment:
      PAPERLESS_DBHOST: db
      PAPERLESS_OCR_LANGUAGE: fra
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_TIME_ZONE: Europe/Paris
      # PAPERLESS_URL: https://paperless.domain.tld
      PAPERLESS_ALLOWED_HOSTS: localhost, http://192.168.1.200, 192.168.1.200, 192.168.1.200:8010, http://192.168.1.200:8010
      ALLOWED_HOSTS: "192.168.1.200,"
      USERMAP_GID: 100
      USERMAP_UID: 1027
    volumes:
      - /volume1/docker/paperless-ngx/core/data/:/usr/src/paperless/data
      - /volume1/docker/paperless-ngx/core/media/:/usr/src/paperless/media
      - /volume1/docker/paperless-ngx/core/export/:/usr/src/paperless/export
      - /volume1/docker/paperless-ngx/core/consume/:/usr/src/paperless/consume
    networks:
      - paperless-ngx-network
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  paperless-ngx-network:
    name: paperless-ngx-network
    driver: bridge
```

I found another [recent comment on SO](https://stackoverflow.com/a/74871273/16190227) that stated to modify the request.py file directly which is not ideal at all.

### Steps to reproduce

1. Add these environment after setting up Paperless.
2. Access from a PC connected to the same network of your server.

### Webserver logs

```bash
Running Django checks
System check identified no issues (0 silenced).
Executing /usr/local/bin/paperless_cmd.sh
2023-01-06 18:33:45,404 INFO Set uid to user 0 succeeded
2023-01-06 18:33:45,425 INFO supervisord started with pid 1
2023-01-06 18:33:46,428 INFO spawned: 'gunicorn' with pid 82
2023-01-06 18:33:46,430 INFO spawned: 'celery' with pid 83
2023-01-06 18:33:46,432 INFO spawned: 'celery-beat' with pid 84
2023-01-06 18:33:46,435 INFO spawned: 'consumer' with pid 85
2023-01-06 18:33:46,437 INFO spawned: 'celery-flower' with pid 86
Checking if we should start flower...
2023-01-06 18:33:46,473 INFO success: celery-flower entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2023-01-06 18:33:46,473 INFO exited: celery-flower (exit status 0; expected)
2023-01-06 18:33:47,474 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-01-06 18:33:47,474 INFO success: celery entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-01-06 18:33:47,474 INFO success: celery-beat entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-01-06 18:33:47,474 INFO success: consumer entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[2023-01-06 19:33:48,239] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: /usr/src/paperless/consume
[2023-01-06 19:33:49 +0100] [82] [INFO] Starting gunicorn 20.1.0
[2023-01-06 19:33:49 +0100] [82] [INFO] Listening at: http://[::]:8000 (82)
[2023-01-06 19:33:49 +0100] [82] [INFO] Using worker: paperless.workers.ConfigurableWorker
[2023-01-06 19:33:49 +0100] [82] [INFO] Server is ready. Spawning workers
[2023-01-06 19:33:49,750] [ERROR] [django.security.DisallowedHost] Invalid HTTP_HOST header: '192.168.1.200:8010'. You may need to add '192.168.1.200' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.9/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '192.168.1.200:8010'. You may need to add '192.168.1.200' to ALLOWED_HOSTS.
[2023-01-06 19:33:49,761] [ERROR] [django.security.DisallowedHost] Invalid HTTP_HOST header: '192.168.1.200:8010'. You may need to add '192.168.1.200' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.9/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '192.168.1.200:8010'. You may need to add '192.168.1.200' to ALLOWED_HOSTS.
[2023-01-06 19:33:49,951] [WARNING] [django.request] Bad Request: /
[2023-01-06 19:33:49,953] [WARNING] [django.request] Bad Request: /
[2023-01-06 19:33:49,988] [ERROR] [django.security.DisallowedHost] Invalid HTTP_HOST header: '192.168.1.200:8010'. You may need to add '192.168.1.200' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.9/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '192.168.1.200:8010'. You may need to add '192.168.1.200' to ALLOWED_HOSTS.
[2023-01-06 19:33:50,035] [WARNING] [django.request] Bad Request: /favicon.ico
[2023-01-06 19:33:50,716] [ERROR] [django.security.DisallowedHost] Invalid HTTP_HOST header: '192.168.1.200:8010'. You may need to add '192.168.1.200' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.9/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '192.168.1.200:8010'. You may need to add '192.168.1.200' to ALLOWED_HOSTS.
[2023-01-06 19:33:50,742] [WARNING] [django.request] Bad Request: /
[2023-01-06 19:33:51,241] [INFO] [celery.beat] beat: Starting...
 
 -------------- celery@e2ae4e672e22 v5.2.7 (dawn-chorus)
--- ***** ----- 
-- ******* ---- Linux-4.4.180+-x86_64-with-glibc2.31 2023-01-06 19:33:51
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         paperless:0x7f927225a460
- ** ---------- .> transport:   redis://broker:6379//
- ** ---------- .> results:     
- *** --- * --- .> concurrency: 1 (prefork)
-- ******* ---- .> task events: ON
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                
[tasks]
  . documents.tasks.bulk_update_documents
  . documents.tasks.consume_file
  . documents.tasks.index_optimize
  . documents.tasks.sanity_check
  . documents.tasks.train_classifier
  . documents.tasks.update_document_archive_file
  . paperless_mail.tasks.process_mail_accounts
[2023-01-06 19:33:51,570] [INFO] [celery.worker.consumer.connection] Connected to redis://broker:6379//
[2023-01-06 19:33:51,575] [INFO] [celery.worker.consumer.mingle] mingle: searching for neighbors
[2023-01-06 19:33:52,588] [INFO] [celery.worker.consumer.mingle] mingle: all alone
[2023-01-06 19:33:52,649] [INFO] [celery.apps.worker] celery@e2ae4e672e22 ready.
```

### Paperless-ngx version

1.11.3

### Host OS

x86_64

### Installation method

Docker - official image

**Comment by stumpylog** [comment]
I'd be curious what ALLOWED_HOSTS is actually ending up as.

From a shell inside the container:
```shell
$ export DJANGO_SETTINGS_MODULE="paperless.settings"
$ python3
>> from django.conf import settings
>> settings.ALLOWED_HOSTS
```

**Comment by stumpylog** [comment]
Well, I can't reproduce this with the following settings:
```
PAPERLESS_URL: "https://devpaperless.tld.com"
PAPERLESS_ALLOWED_HOSTS: "servername,<server ip>
```

I'm able to access via hostname, IP and domain.

**Comment by shamoon** [comment]
How about removing the spaces? I also cant reproduce this issue. Also, if youre setting `PAPERLESS_ALLOWED_HOSTS` make sure to include `localhost` (noted in the docs)

**Comment by DimitriDR** [comment]
Yes, indeed, It's without spaces around comma. Maybe It is worth adding it in the docs? Space after comma is the rule in most languages, so It can be confusing IMO 😄 

Thanks again!

**Comment by shamoon** [comment]
> Yes, indeed, It's without spaces around comma. Maybe It is worth adding it in the docs? Space after comma is the rule in most languages, so It can be confusing IMO 😄
> 
> Thanks again!

Glad it’s sorted. From the docs:

> Just remember that this is a comma-separated list, so "example.com" is fine, as is "example.com,www.example.com", but NOT " example.com" or "example.com,"
