### ISSUE TITLE
[BUG] pdfimer.six exception

### ISSUE THREAD

**Issue by p-h-a-i-l** [paperless-ngx/paperless-ngx#2395]
### Description

During consumption I get an exception in my log.

### Steps to reproduce

Document consumed via mail attachment

### Webserver logs

```bash
[2023-01-09 22:00:20,709] [INFO] [paperless.consumer] Consuming Epson_09012023205453.pdf
[2023-01-09 22:00:20,713] [DEBUG] [paperless.consumer] Detected mime type: application/pdf
[2023-01-09 22:00:20,716] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser
[2023-01-09 22:00:20,722] [DEBUG] [paperless.consumer] Parsing Epson_09012023205453.pdf...
[2023-01-09 22:00:20,742] [DEBUG] [paperless.parsing.tesseract] Extracted text from PDF file /tmp/paperless/paperless-mail-x431aiuz
[2023-01-09 22:00:20,991] [WARNING] [paperless.parsing.tesseract] Error while getting text from PDF document with pdfminer.six
Traceback (most recent call last):
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 140, in extract_text
    lang = detect(stripped)
  File "/usr/local/lib/python3.9/site-packages/langdetect/detector_factory.py", line 130, in detect
    return detector.detect()
  File "/usr/local/lib/python3.9/site-packages/langdetect/detector.py", line 136, in detect
    probabilities = self.get_probabilities()
  File "/usr/local/lib/python3.9/site-packages/langdetect/detector.py", line 143, in get_probabilities
    self._detect_block()
  File "/usr/local/lib/python3.9/site-packages/langdetect/detector.py", line 150, in _detect_block
    raise LangDetectException(ErrorCode.CantDetectError, 'No features in text.')
langdetect.lang_detect_exception.LangDetectException: No features in text.
[2023-01-09 22:00:21,030] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-mail-x431aiuz'), 'output_file': PosixPath('/tmp/paperless/paperless-3_76t6tk/archive.pdf'), 'use_threads': True, 'jobs': 4, 'language': 'deu', 'output_type': 'pdfa', 'progress_bar': False, 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-3_76t6tk/sidecar.txt')}
[2023-01-09 22:00:53,979] [DEBUG] [paperless.parsing.tesseract] Using text from sidecar file
[2023-01-09 22:00:53,985] [DEBUG] [paperless.consumer] Generating thumbnail for Epson_09012023205453.pdf...
[2023-01-09 22:00:53,992] [DEBUG] [paperless.parsing] Execute: convert -density 300 -scale 500x5000> -alpha remove -strip -auto-orient /tmp/paperless/paperless-3_76t6tk/archive.pdf[0] /tmp/paperless/paperless-3_76t6tk/convert.webp
[2023-01-09 22:00:56,736] [DEBUG] [paperless.consumer] Saving record to database
[2023-01-09 22:00:56,739] [DEBUG] [paperless.consumer] Creation date from parse_date: 2021-02-02 00:00:00+01:00
[2023-01-09 22:00:57,476] [DEBUG] [paperless.consumer] Deleting file /tmp/paperless/paperless-mail-x431aiuz
[2023-01-09 22:00:57,481] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-3_76t6tk
[2023-01-09 22:00:57,483] [INFO] [paperless.consumer] Document 2021-02-02 Epson_09012023205453 consumption finished
```

### Paperless-ngx version

1.11.3

### Host OS

MacOS arm64

### Installation method

Docker - official image

**Comment by stumpylog** [comment]
It doesn't actually stop consumption.  You can see the file `/tmp/paperless/paperless-mail-x431aiuz` is only removed after everything has been saved to the database.  But usage of `langdetect` will go away in the linked pull request and the error won't show up anymore.

**Comment by p-h-a-i-l** [comment]
Thanks!
