### ISSUE TITLE
[Feature Request] Mails are deleted (or marked as consumed) unrelated to consumption result

### ISSUE THREAD

**Issue by p-h-a-i-l** [paperless-ngx/paperless-ngx#2396]
### Description

When a document is consumed via mail, document consumption is decoupled from mail processing.
As soon as a mail is processed and consumptions jobs for the documents are created, a mail is considered done. The mail is being deleted or somehow marked, depending on configuration.
If consumption fails for whatever reason, there is no way back.

In the attached log, my mail is already deleted when the consumption fails, the document is lost forever.

(The exception in the log is probably unrelated, I created another issue: https://github.com/paperless-ngx/paperless-ngx/issues/2395)

The unfinished documents should be kept somewhere for recovery.
Would also be helpful to reproduce the underlying problem. I have lost missed some more documents in the last weeks but didn't check the logs.

### Steps to reproduce

Consume scanned pdf via mail attachment. 

### Webserver logs

```bash
[2023-01-09 21:20:34,648] [INFO] [paperless.consumer] Consuming Epson_09012023201554.pdf
[2023-01-09 21:20:34,653] [DEBUG] [paperless.consumer] Detected mime type: application/pdf
[2023-01-09 21:20:34,655] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser
[2023-01-09 21:20:34,660] [DEBUG] [paperless.consumer] Parsing Epson_09012023201554.pdf...
[2023-01-09 21:20:34,679] [DEBUG] [paperless.parsing.tesseract] Extracted text from PDF file /tmp/paperless/paperless-mail-8nmph759
[2023-01-09 21:20:34,869] [WARNING] [paperless.parsing.tesseract] Error while getting text from PDF document with pdfminer.six

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 140, in extract_text

    lang = detect(stripped)

  File "/usr/local/lib/python3.9/site-packages/langdetect/detector_factory.py", line 130, in detect

    return detector.detect()

  File "/usr/local/lib/python3.9/site-packages/langdetect/detector.py", line 136, in detect

    probabilities = self.get_probabilities()

  File "/usr/local/lib/python3.9/site-packages/langdetect/detector.py", line 143, in get_probabilities

    self._detect_block()

  File "/usr/local/lib/python3.9/site-packages/langdetect/detector.py", line 150, in _detect_block

    raise LangDetectException(ErrorCode.CantDetectError, 'No features in text.')

langdetect.lang_detect_exception.LangDetectException: No features in text.

[2023-01-09 21:20:34,903] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-mail-8nmph759'), 'output_file': PosixPath('/tmp/paperless/paperless-jtyopbxp/archive.pdf'), 'use_threads': True, 'jobs': 4, 'language': 'deu', 'output_type': 'pdfa', 'progress_bar': False, 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-jtyopbxp/sidecar.txt')}

[2023-01-09 21:20:50,141] [INFO] [paperless.management.consumer] Received SIGINT, stopping inotify

[2023-01-09 21:20:50,147] [DEBUG] [paperless.management.consumer] Consumer exiting.
```

### Paperless-ngx version

1.11.3

### Host OS

MacOS arm64

### Installation method

Docker - official image

**Comment by shamoon** [comment]
Are you proposing a solution here? If you used mark as read instead of delete would at least prevent loss, we could note this. Otherwise I guess we're talking about having the mail function wait until after [successful] consumption before performing mail actions? But currently no consumption works like that

**Comment by p-h-a-i-l** [comment]
I think changing the workflow to wait for consumption to finish is too much. For me it would be sufficient to put the unfinished files into a crash report folder or something. Somewhere, where you can recover the files from.

**Comment by shamoon** [comment]
maybe moving emails to trash instead of deleting? Imagine there could be some complexity to this of course

**Comment by stumpylog** [comment]
I don't think IMAP has a simple move to trash, it's usually just a folder the software treats differently.  The simple solution I see would be a "crash dir" where consumption makes a best effort to move the file to on a crash of some sort.  There would be some types of crashes, such as a SIGKILL that couldn't do that, but most exceptions could

**Comment by ph1248** [comment]
> I think changing the workflow to wait for consumption to finish is too much.´



> I think changing the workflow to wait for consumption to finish is too much. For me it would be sufficient to put the unfinished files into a crash report folder or something. Somewhere, where you can recover the files from.

I disagree. I think it would be best to leave the email untouched in its original folder until consumption is successful. In this way it would also be consistent to processing of files in the conusmption folder. Those are also left in place if consumption fails, and are only deleted after consumption was successful. I think it's not optimal to move the emails in another folder. For example, the user might use different rules to scan different folders on a server. If then all failed mails are moved to one crash_folder, this might cause confusion. 

However, it might be a good thing to add a custom tag (IMAP keyword) to those mails ("paperless_consumption_error") to help the user to identify them. But this is not essential, so it's no problem if not all IMAP servers support this.


I imagine this would also be a good way to deal with the following case: If both the message (.eml) and its attachments are to be processed, it can happen that only the attachments can be consumed but not the message. If they are left in place, then the user can still process the message as he likes, and then move or delete the message manually. Similar, if only some of the attachments are successfully scanned and some fail.

Just my 2 cents...

**Comment by jonaswinkler** [comment]
I'm still in the process of getting a grip on the current state of the code, but since you switched the backend task queue from django-q to celery, we *might* be able to delay result processing (i.e., starring/moving/deleting) until after consumption is finished, and have it execute depending on result.

Celery has support for freezing method signatures, and orchestrating tasks with chords and groups. Maybe that's useful. https://docs.celeryq.dev/en/stable/userguide/canvas.html.

I'll test that as part of my efforts to revive that split and merge feature.

**Comment by jonaswinkler** [comment]
Solved, included in next release.
