### ISSUE TITLE
[BUG] [WARNING] [paperless.parsing.tesseract] Error while getting text from PDF document with pdfminer.six

### ISSUE THREAD

**Issue by ZoXx** [paperless-ngx/paperless-ngx#2442]
### Description

Hello I have with some .pdf files the problem that they can no longer be read due to the error:
`[2023-01-16 01:39:30,108] [WARNING] [paperless.parsing.tesseract] Error while getting text from PDF document with pdfminer.six`

This error has occurred several times in the last few days with a large number of .pdf files.
Anyone have any advice?

### Steps to reproduce

1. Load .pdf files into the consume folder.
2. queue is processed until the error occurs.

### Webserver logs

```bash
`[2023-01-16 01:39:30,108] [WARNING] [paperless.parsing.tesseract] Error while getting text from PDF document with pdfminer.six
Traceback (most recent call last):
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 140, in extract_text
    lang = detect(stripped)
  File "/usr/local/lib/python3.9/site-packages/langdetect/detector_factory.py", line 130, in detect
    return detector.detect()
  File "/usr/local/lib/python3.9/site-packages/langdetect/detector.py", line 136, in detect
    probabilities = self.get_probabilities()
  File "/usr/local/lib/python3.9/site-packages/langdetect/detector.py", line 143, in get_probabilities
    self._detect_block()
  File "/usr/local/lib/python3.9/site-packages/langdetect/detector.py", line 150, in _detect_block
    raise LangDetectException(ErrorCode.CantDetectError, 'No features in text.')
langdetect.lang_detect_exception.LangDetectException: No features in text.
```

### Paperless-ngx version

1.11.3

### Host OS

Docker

### Installation method

Docker - official image

### Browser

Chrome

**Comment by shamoon** [comment]
That is a warning and doesn’t prevent consumption

**Comment by ZoXx** [comment]
Thanks for the quick feedback. But my consume folder is not processed further afterwards?

**Comment by shamoon** [comment]
If theres an error that prevents a file from being consumed it would presumably come after this. If youre talking about processing through an entire batch of files in your consume folder, perhaps take a look at https://docs.paperless-ngx.com/troubleshooting/ ?

**Comment by ZoXx** [comment]
Thanks for the link. I have looked at the FAQ once, nothing suitable found. The documents are now even double in the queue. This is still not processed. I can't find any entry in the log for Paperless.

The documents were added at 01:30:
`
[2023-01-16 01:36:46,251] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/2022-10-14 XXXXX.pdf to the task queue.
[2023-01-16 01:39:29,484] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/2019-09-04 XXXXX.pdf to the task queue.
[2023-01-16 01:39:29,538] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/2020-09-02 XXXXX.pdf to the task queue.
[2023-01-16 01:39:29,605] [INFO] [paperless.consumer] Consuming 2019-09-04 XXXXX.pdf
[2023-01-16 01:39:29,609] [DEBUG] [paperless.consumer] Detected mime type: application/pdf
[2023-01-16 01:39:29,611] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser
[2023-01-16 01:39:29,615] [DEBUG] [paperless.consumer] Parsing 2019-09-04 XXXXX.pdf...
[2023-01-16 01:39:29,663] [DEBUG] [paperless.parsing.tesseract] Extracted text from PDF file /usr/src/paperless/consume/2019-09-04 XXXXX.pdf
[2023-01-16 01:39:29,676] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/2021-09-03 XXXXX.pdf to the task queue.
[2023-01-16 01:39:29,802] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/2022-09-04 XXXXX.pdf to the task queue.
`

After that, there is only one entry at 03:16:
`
[2023-01-16 03:16:44,281] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/2022-10-14 XXXXX.pdf to the task queue.
[2023-01-16 03:16:44,908] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/2020-09-02 XXXXX.pdf to the task queue.
[2023-01-16 03:16:44,942] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/2022-09-04 XXXXX.pdf to the task queue.
[2023-01-16 03:16:44,960] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: /usr/src/paperless/consume
`

**Comment by shamoon** [comment]
Try consumer polling, that’s one of the most common reasons https://docs.paperless-ngx.com/troubleshooting/#consumer-fails-to-pickup-any-new-files

**Comment by shamoon** [comment]
Ah yea I see the tasks were added. I wonder if celery is running, you can manually start it with `celery --app paperless worker` though docker should do this for you

I assume you’ve already tried re-creating the container?

**Comment by ZoXx** [comment]
i have already reacreated the docker several times. that's why i had the documents in the queue several times (the same ones).

how i send the command? Iam working with portainer.

**Comment by ZoXx** [comment]
Nobody? :(

**Comment by shamoon** [comment]
Does consumption work via the UI?

**Comment by ZoXx** [comment]
Pretty much the same problem. Recognition takes a very long time (3-4 minutes in some cases) for a one page .pdf file.
After that it is recognized and completed. The other files are then "gone".

**Comment by ZoXx** [comment]
News!

If I upload the file through my domain (nginx) (web interface) then the behavior is as described above.

If I add the file via local (webinterface), the file uploads without problems, the display works fine and the file is completed after not even 3 seconds.

**Comment by ZoXx** [comment]
Silly question.
I have two paperless instances running. Does each one need its own redis container? I have both running over one database (with separate users and databases) and over a shared redis container.

I have seen that in the second paperless instance the .pdf files of the other paperless instance have appeared in the protocols and are written in red as "file not found".

**Comment by shamoon** [comment]
Ah, yes they certainly do

**Comment by ZoXx** [comment]
Two own containers for the docker (redis) and the problems are no longer present.
