### ISSUE TITLE
[BUG] Archive serial number is parsed as int during index creation causing overflow issues

### ISSUE THREAD

**Issue by BertanAygun** [paperless-ngx/paperless-ngx#2496]
### Description

I have a document where I put 9364061719 as archive serial number field and everything saved properly. Recently I was trying to update my paperless-ngx to a newer version but updating search index failed with:

ValueError: Numeric field value 9364061719 out of range [-2147483648, 2147483647]

This also happens if I just run "document_index rebuild" on the same build (1.8.0) but I can also reproduce it in "latest".

### Steps to reproduce

1. Create a document
2. Set archive serial number to a large number like 9364061719 
3. Run document_index rebuild script or try to upgrade.

### Webserver logs

```bash
Traceback (most recent call last):
  File "/app/paperless/src/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 414, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "/app/paperless/src/documents/management/commands/document_index.py", line 23, in handle
    index_reindex(progress_bar_disable=options["no_progress_bar"])
  File "/app/paperless/src/documents/tasks.py", line 48, in index_reindex
    index.update_document(writer, document)
  File "/app/paperless/src/documents/index.py", line 93, in update_document
    writer.update_document(
  File "/usr/local/lib/python3.8/dist-packages/whoosh/writing.py", line 1024, in update_document
    self._record("update_document", args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/whoosh/writing.py", line 1001, in _record
    getattr(self.writer, method)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/whoosh/writing.py", line 490, in update_document
    self.add_document(**fields)
  File "/usr/local/lib/python3.8/dist-packages/whoosh/writing.py", line 750, in add_document
    for tbytes, freq, weight, vbytes in items:
  File "/usr/local/lib/python3.8/dist-packages/whoosh/fields.py", line 669, in index
    yield (self.to_bytes(num, shift), 1, 1.0, emptybytes)
  File "/usr/local/lib/python3.8/dist-packages/whoosh/fields.py", line 722, in to_bytes
    x = self.prepare_number(x)
  File "/usr/local/lib/python3.8/dist-packages/whoosh/fields.py", line 691, in prepare_number
    raise ValueError("Numeric field value %s out of range [%s, %s]"
ValueError: Numeric field value 9364061719 out of range [-2147483648, 2147483647]
```

### Paperless-ngx version

1.8.0 (but also occurs on latest)

### Host OS

Docker container (not sure)

### Installation method

Docker - official image

### Configuration changes

I am using Sqlite option due to having started with linuxserver.io images.

**Comment by shamoon** [comment]
I guess not many people use ASNs that high...

It is a bit surprising since IntegerField shouldnt support this from the start so I would have assumed it would have failed https://docs.djangoproject.com/en/4.1/ref/models/fields#django.db.models.IntegerField

**Comment by BertanAygun** [comment]
@shamoon, one thing that I forgot to mention initially was that I am using sqlite db option. Not sure if that would change things.

I was using serial number field to store receipt numbers, this particular company happened to have such a large invoice number.

**Comment by shamoon** [comment]
@BertanAygun just FYI:

- The fix will still not support that ASN, it will just prevent it from being accepted in the future, you'll need to edit yours to fix things in your install.
- Of course there are a million ways to use the software, but generally ASN is designed as a system of your own cataloging, and would be used sequentially for documents youre keeping a physical copy of. So in some ways its just not expected to have an ASN of 9 billion+ unless you have that many docs 😜

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/c7690c05f5dad977435116ac5d03f5e63bd2d97b
