### ISSUE TITLE
[BUG] Exception applying db migration - check constraint "documents_document_archive_serial_number_550aa63f_check" of relation "documents_document" is violated by some row

### ISSUE THREAD

**Issue by TheMiller2015** [paperless-ngx/paperless-ngx#2535]
### Description

Hello,

using the latest paperless docker image from ghcr.io, paperless isn't starting any more. It seems, that there are problems while migrating the database. I'm using postgres, paperless and redis, just like the docker-compose says. No problems for more than a year (switched from ng to ngx 8 months before). I'm nightly updating all images through watchtower. The paperless logs are saying the following. I think the most interesting part is the exception while applying a db migration and error message 

**check constraint "documents_document_archive_serial_number_550aa63f_check" of relation "documents_document" is violated by some row**

Issue persists since 2023-01-25

```Installing languages...

Hit:1 http://deb.debian.org/debian bullseye InRelease

Hit:2 http://deb.debian.org/debian-security bullseye-security InRelease

Hit:3 http://deb.debian.org/debian bullseye-updates InRelease

Reading package lists...

Package tesseract-ocr-deu already installed!

Package tesseract-ocr-eng already installed!

Creating directory /tmp/paperless

Adjusting permissions of paperless files. This may take a while.

Waiting for PostgreSQL to start...

Waiting for Redis...

Connected to Redis broker.

Apply database migrations...

Operations to perform:

  Apply all migrations: admin, auth, authtoken, contenttypes, django_celery_results, documents, paperless_mail, sessions

Running migrations:

Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute

    return self.cursor.execute(sql, params)

psycopg2.errors.CheckViolation: check constraint "documents_document_archive_serial_number_550aa63f_check" of relation "documents_document" is violated by some row

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/manage.py", line 11, in <module>

    execute_from_command_line(sys.argv)

  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line

    utility.execute()

  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute

    self.fetch_command(subcommand).run_from_argv(self.argv)

  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 402, in run_from_argv

    self.execute(*args, **cmd_options)

  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 448, in execute

    output = self.handle(*args, **options)

  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 96, in wrapped

    res = handle_func(*args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 349, in handle

    post_migrate_state = executor.migrate(

  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 135, in migrate

    state = self._migrate_all_forwards(

  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards

    state = self.apply_migration(

  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 252, in apply_migration

    state = migration.apply(state, schema_editor)

  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/migration.py", line 130, in apply

    operation.database_forwards(

  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/operations/fields.py", line 235, in database_forwards

    schema_editor.alter_field(from_model, from_field, to_field)

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 788, in alter_field

    self._alter_field(

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/schema.py", line 246, in _alter_field

    super()._alter_field(

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 1126, in _alter_field

    self.execute(

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 199, in execute

    cursor.execute(sql, params)

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute

    return self._execute_with_wrappers(

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers

    return executor(sql, params, many, context)

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute

    return self.cursor.execute(sql, params)

  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__

    raise dj_exc_value.with_traceback(traceback) from exc_value

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute

    return self.cursor.execute(sql, params)

django.db.utils.IntegrityError: check constraint "documents_document_archive_serial_number_550aa63f_check" of relation "documents_document" is violated by some row

  Applying documents.1029_alter_document_archive_serial_number...```

Thanks in advance. Tell me, how I can help.

### Steps to reproduce

Just ran a docker pull. Issue persists since 2023-01-25

### Webserver logs

```bash
no webserver logs, just cli logs (see above)
```

### Paperless-ngx version

latest as of 2023-01-25 (can't access webUI)

### Host OS

CentOS / docker

### Installation method

Docker - official image

**Comment by TheMiller2015** [comment]
Tell me, how I can help you with.

**Comment by stumpylog** [comment]
Do you have ASNs assigned?  Are any of them very large or negative?

**Comment by TheMiller2015** [comment]
Thanks. What do you mean by "ASNs assigned"? I don't know, what you mean. I can't remeber settings up sth. related to asn in the settings. And I haven't read anything about asn in docker-compose or the settings. I'm completly lost with this term, sorry ;)

**Comment by stumpylog** [comment]
Do you use archive serial numbers?  The failing check is related to those, and applying a min/max to them.

**Comment by TheMiller2015** [comment]
do you mean ASN as part of the filename? If so, then no. These are my env-vars for paperless:

```
      - PAPERLESS_REDIS=redis://broker:6379
      - PAPERLESS_DBHOST=db-postgres
      - PAPERLESS_DBNAME=paperless
      - PAPERLESS_DBUSER=xxxxxxxxxx
      - PAPERLESS_DBPASS=xxxxxxxxxxxx
      - USERMAP_UID=1000
      - USERMAP_GID=100
      - PAPERLESS_TASK_WORKERS=4
      - PAPERLESS_THREADS_PER_WORKER=4
      - PAPERLESS_OCR_LANGUAGES=deu eng
      - PAPERLESS_TIME_ZONE=Europe/Berlin
      - PAPERLESS_OCR_LANGUAGE=deu
      - PAPERLESS_CONSUMER_POLLING=30
      - PAPERLESS_CONSUMER_RECURSIVE=true
      - PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS=true
      - PAPERLESS_SECRET_KEY=xxxxxxxxxxxxxxxx
      - PAPERLESS_FILENAME_FORMAT={created_year}/{created_month}/{correspondent}/{created}-{correspondent}-{title}
```

are there any other settings related to asn that I can check? Thanks!

**Comment by stumpylog** [comment]
I'm talking about this field:
![image](https://user-images.githubusercontent.com/797416/215276526-c678c4b9-f9a2-42fc-bfb8-e7849e89c1fb.png)

Do you have documents with it filled in?  If yes, are they over 4294967295 or less than zero?

**Comment by TheMiller2015** [comment]
Hello, I don't use asn, but I queried the db and indeed, there is one document having an asn set and it's smaller than 0

```paperless=# select id, title, archive_serial_number from documents_document where archive_serial_number IS NOT NULL LIMIT 100000;
  id  |              title               | archive_serial_number
------+----------------------------------+-----------------------
 4174 | xxxxxx_20220125_104750_041968 |                    -2
(1 row)
```

So I updated this specific document, setting the asn to NULL with this sql

```
 update documents_document SET archive_serial_number = NULL WHERE id = 4174;
```

And... what shall I say? Paperless starts, did his migration and the webUI is accessable. Works without any errors (so far as I can see). So, I think this is all I had to do, or do you think I forget sth. to alter/update?

If not, many thanks and great/fast help. Nice project, thumbs up!

**Comment by shamoon** [comment]
Thanks for the follow-up

**Comment by rhierlmeier** [comment]
I run into the same problem.

How did found out want the next free ASN (archive_serial_number) is?

With this SQL-Statement?
```sql
select max(archive_serial_number) from documents_document;
```

The question for me is. How can it happen that an ASN is negative?

**Comment by bllngr** [comment]
I've just hit the same issue. I'm using negative ASNs quite extensively, because I scanned documents with earlier dates than ASN-0, and I wanted them to be in the correct order. Given that this was possible & supported using the UI  before, this looks like a regression to me.
