### ISSUE TITLE
[BUG] Consume fails with "This writer is closed"

### ISSUE THREAD

**Issue by jeff47** [paperless-ngx/paperless-ngx#2573]
### Description

I am getting a periodic problem when I try to add documents.  Paperless-ngx fails with a "This writer is closed" error.  Broker, db, tika, and gotenberg logs are clean.  I attached the log from webserver.

If I run `docker compose exec webserver document_index reindex`, then the error goes away for a while but reappears after some time.  I don't know if that's a clue or a red-herring.

This looks different from #1721 

### Steps to reproduce

Add document, either from consume directory or direct upload via web browser.

### Webserver logs

```bash
2023-02-01 07:32:25 [2023-02-01 07:32:25,752] [INFO] [celery.worker.strategy] Task documents.tasks.consume_file[a39f4813-1cfb-40c4-8c7b-2230ecf45cae] received
2023-02-01 07:32:25 [2023-02-01 07:32:25,939] [INFO] [paperless.consumer] Consuming Official GWU Transcript (2017_10_11 11_50_14 UTC).pdf
2023-02-01 07:32:26 [2023-02-01 07:32:26,792] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
2023-02-01 07:32:26 [2023-02-01 07:32:26,817] [INFO] [ocrmypdf._sync] Postprocessing...
2023-02-01 07:32:28 [2023-02-01 07:32:28,014] [WARNING] [ocrmypdf._pipeline] Some input metadata could not be copied because it is not permitted in PDF/A. You may wish to examine the output PDF's XMP metadata.
2023-02-01 07:32:29 [2023-02-01 07:32:29,466] [INFO] [ocrmypdf._pipeline] Optimize ratio: 1.00 savings: 0.3%
2023-02-01 07:32:29 [2023-02-01 07:32:29,477] [INFO] [ocrmypdf._sync] Output file is a PDF/A-2B (as expected)
2023-02-01 07:32:41 [2023-02-01 07:32:41,090] [INFO] [paperless.handlers] Assigning document type Financial to 2014-04-21 Official GWU Transcript (2017_10_11 11_50_14 UTC)
2023-02-01 07:32:41 [2023-02-01 07:32:41,139] [INFO] [paperless.handlers] Tagging "2014-04-21 Official GWU Transcript (2017_10_11 11_50_14 UTC)" with "Jana"
2023-02-01 07:32:41 [2023-02-01 07:32:41,599] [ERROR] [paperless.index] [Errno 2] No such file or directory: '/usr/src/paperless/data/index/MAIN_zz5n17mpodmcdexe.seg'
2023-02-01 07:32:41 Traceback (most recent call last):
2023-02-01 07:32:41   File "/usr/src/paperless/src/documents/index.py", line 74, in open_index_writer
2023-02-01 07:32:41     yield writer
2023-02-01 07:32:41   File "/usr/src/paperless/src/documents/index.py", line 130, in add_or_update_document
2023-02-01 07:32:41     update_document(writer, document)
2023-02-01 07:32:41   File "/usr/src/paperless/src/documents/index.py", line 96, in update_document
2023-02-01 07:32:41     writer.update_document(
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 1024, in update_document
2023-02-01 07:32:41     self._record("update_document", args, kwargs)
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 1001, in _record
2023-02-01 07:32:41     getattr(self.writer, method)(*args, **kwargs)
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 483, in update_document
2023-02-01 07:32:41     with self.searcher() as s:
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 297, in searcher
2023-02-01 07:32:41     return Searcher(self.reader(), **kwargs)
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 638, in reader
2023-02-01 07:32:41     return FileIndex._reader(self.storage, self.schema, self.segments,
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/site-packages/whoosh/index.py", line 535, in _reader
2023-02-01 07:32:41     readers = [segreader(segment) for segment in segments]
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/site-packages/whoosh/index.py", line 535, in <listcomp>
2023-02-01 07:32:41     readers = [segreader(segment) for segment in segments]
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/site-packages/whoosh/index.py", line 523, in segreader
2023-02-01 07:32:41     return SegmentReader(storage, schema, segment,
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/site-packages/whoosh/reading.py", line 610, in __init__
2023-02-01 07:32:41     files = segment.open_compound_file(storage)
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/site-packages/whoosh/codec/base.py", line 569, in open_compound_file
2023-02-01 07:32:41     dbfile = storage.open_file(name)
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/site-packages/whoosh/filedb/filestore.py", line 504, in open_file
2023-02-01 07:32:41     f = StructFile(open(self._fpath(name), "rb"), name=name, **kwargs)
2023-02-01 07:32:41 FileNotFoundError: [Errno 2] No such file or directory: '/usr/src/paperless/data/index/MAIN_zz5n17mpodmcdexe.seg'
2023-02-01 07:32:41 [2023-02-01 07:32:41,637] [ERROR] [paperless.consumer] The following error occurred while consuming Official GWU Transcript (2017_10_11 11_50_14 UTC).pdf: This writer is closed
2023-02-01 07:32:41 Traceback (most recent call last):
2023-02-01 07:32:41   File "/usr/src/paperless/src/documents/index.py", line 74, in open_index_writer
2023-02-01 07:32:41     yield writer
2023-02-01 07:32:41   File "/usr/src/paperless/src/documents/index.py", line 130, in add_or_update_document
2023-02-01 07:32:41     update_document(writer, document)
2023-02-01 07:32:41   File "/usr/src/paperless/src/documents/index.py", line 96, in update_document
2023-02-01 07:32:41     writer.update_document(
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 1024, in update_document
2023-02-01 07:32:41     self._record("update_document", args, kwargs)
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 1001, in _record
2023-02-01 07:32:41     getattr(self.writer, method)(*args, **kwargs)
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 483, in update_document
2023-02-01 07:32:41     with self.searcher() as s:
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 297, in searcher
2023-02-01 07:32:41     return Searcher(self.reader(), **kwargs)
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 638, in reader
2023-02-01 07:32:41     return FileIndex._reader(self.storage, self.schema, self.segments,
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/site-packages/whoosh/index.py", line 535, in _reader
2023-02-01 07:32:41     readers = [segreader(segment) for segment in segments]
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/site-packages/whoosh/index.py", line 535, in <listcomp>
2023-02-01 07:32:41     readers = [segreader(segment) for segment in segments]
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/site-packages/whoosh/index.py", line 523, in segreader
2023-02-01 07:32:41     return SegmentReader(storage, schema, segment,
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/site-packages/whoosh/reading.py", line 610, in __init__
2023-02-01 07:32:41     files = segment.open_compound_file(storage)
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/site-packages/whoosh/codec/base.py", line 569, in open_compound_file
2023-02-01 07:32:41     dbfile = storage.open_file(name)
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/site-packages/whoosh/filedb/filestore.py", line 504, in open_file
2023-02-01 07:32:41     f = StructFile(open(self._fpath(name), "rb"), name=name, **kwargs)
2023-02-01 07:32:41 FileNotFoundError: [Errno 2] No such file or directory: '/usr/src/paperless/data/index/MAIN_zz5n17mpodmcdexe.seg'
2023-02-01 07:32:41 
2023-02-01 07:32:41 During handling of the above exception, another exception occurred:
2023-02-01 07:32:41 
2023-02-01 07:32:41 Traceback (most recent call last):
2023-02-01 07:32:41   File "/usr/src/paperless/src/documents/consumer.py", line 425, in try_consume_file
2023-02-01 07:32:41     document_consumption_finished.send(
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 176, in send
2023-02-01 07:32:41     return [
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
2023-02-01 07:32:41     (receiver, receiver(signal=self, sender=sender, **named))
2023-02-01 07:32:41   File "/usr/src/paperless/src/documents/signals/handlers.py", line 516, in add_to_index
2023-02-01 07:32:41     index.add_or_update_document(document)
2023-02-01 07:32:41   File "/usr/src/paperless/src/documents/index.py", line 130, in add_or_update_document
2023-02-01 07:32:41     update_document(writer, document)
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
2023-02-01 07:32:41     self.gen.throw(typ, value, traceback)
2023-02-01 07:32:41   File "/usr/src/paperless/src/documents/index.py", line 79, in open_index_writer
2023-02-01 07:32:41     writer.commit(optimize=optimize)
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 1037, in commit
2023-02-01 07:32:41     self.writer.commit(*args, **kwargs)
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 920, in commit
2023-02-01 07:32:41     self._check_state()
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 555, in _check_state
2023-02-01 07:32:41     raise IndexingError("This writer is closed")
2023-02-01 07:32:41 whoosh.writing.IndexingError: This writer is closed
2023-02-01 07:32:41 [2023-02-01 07:32:41,731] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[a39f4813-1cfb-40c4-8c7b-2230ecf45cae] raised unexpected: ConsumerError('Official GWU Transcript (2017_10_11 11_50_14 UTC).pdf: The following error occurred while consuming Official GWU Transcript (2017_10_11 11_50_14 UTC).pdf: This writer is closed')
2023-02-01 07:32:41 Traceback (most recent call last):
2023-02-01 07:32:41   File "/usr/src/paperless/src/documents/index.py", line 74, in open_index_writer
2023-02-01 07:32:41     yield writer
2023-02-01 07:32:41   File "/usr/src/paperless/src/documents/index.py", line 130, in add_or_update_document
2023-02-01 07:32:41     update_document(writer, document)
2023-02-01 07:32:41   File "/usr/src/paperless/src/documents/index.py", line 96, in update_document
2023-02-01 07:32:41     writer.update_document(
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 1024, in update_document
2023-02-01 07:32:41     self._record("update_document", args, kwargs)
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 1001, in _record
2023-02-01 07:32:41     getattr(self.writer, method)(*args, **kwargs)
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 483, in update_document
2023-02-01 07:32:41     with self.searcher() as s:
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 297, in searcher
2023-02-01 07:32:41     return Searcher(self.reader(), **kwargs)
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 638, in reader
2023-02-01 07:32:41     return FileIndex._reader(self.storage, self.schema, self.segments,
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/site-packages/whoosh/index.py", line 535, in _reader
2023-02-01 07:32:41     readers = [segreader(segment) for segment in segments]
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/site-packages/whoosh/index.py", line 535, in <listcomp>
2023-02-01 07:32:41     readers = [segreader(segment) for segment in segments]
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/site-packages/whoosh/index.py", line 523, in segreader
2023-02-01 07:32:41     return SegmentReader(storage, schema, segment,
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/site-packages/whoosh/reading.py", line 610, in __init__
2023-02-01 07:32:41     files = segment.open_compound_file(storage)
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/site-packages/whoosh/codec/base.py", line 569, in open_compound_file
2023-02-01 07:32:41     dbfile = storage.open_file(name)
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/site-packages/whoosh/filedb/filestore.py", line 504, in open_file
2023-02-01 07:32:41     f = StructFile(open(self._fpath(name), "rb"), name=name, **kwargs)
2023-02-01 07:32:41 FileNotFoundError: [Errno 2] No such file or directory: '/usr/src/paperless/data/index/MAIN_zz5n17mpodmcdexe.seg'
2023-02-01 07:32:41 
2023-02-01 07:32:41 During handling of the above exception, another exception occurred:
2023-02-01 07:32:41 
2023-02-01 07:32:41 Traceback (most recent call last):
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 302, in main_wrap
2023-02-01 07:32:41     raise exc_info[1]
2023-02-01 07:32:41   File "/usr/src/paperless/src/documents/consumer.py", line 425, in try_consume_file
2023-02-01 07:32:41     document_consumption_finished.send(
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 176, in send
2023-02-01 07:32:41     return [
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
2023-02-01 07:32:41     (receiver, receiver(signal=self, sender=sender, **named))
2023-02-01 07:32:41   File "/usr/src/paperless/src/documents/signals/handlers.py", line 516, in add_to_index
2023-02-01 07:32:41     index.add_or_update_document(document)
2023-02-01 07:32:41   File "/usr/src/paperless/src/documents/index.py", line 130, in add_or_update_document
2023-02-01 07:32:41     update_document(writer, document)
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
2023-02-01 07:32:41     self.gen.throw(typ, value, traceback)
2023-02-01 07:32:41   File "/usr/src/paperless/src/documents/index.py", line 79, in open_index_writer
2023-02-01 07:32:41     writer.commit(optimize=optimize)
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 1037, in commit
2023-02-01 07:32:41     self.writer.commit(*args, **kwargs)
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 920, in commit
2023-02-01 07:32:41     self._check_state()
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 555, in _check_state
2023-02-01 07:32:41     raise IndexingError("This writer is closed")
2023-02-01 07:32:41 whoosh.writing.IndexingError: This writer is closed
2023-02-01 07:32:41 
2023-02-01 07:32:41 The above exception was the direct cause of the following exception:
2023-02-01 07:32:41 
2023-02-01 07:32:41 Traceback (most recent call last):
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
2023-02-01 07:32:41     R = retval = fun(*args, **kwargs)
2023-02-01 07:32:41   File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
2023-02-01 07:32:41     return self.run(*args, **kwargs)
2023-02-01 07:32:41   File "/usr/src/paperless/src/documents/tasks.py", line 192, in consume_file
2023-02-01 07:32:41     document = Consumer().try_consume_file(
2023-02-01 07:32:41   File "/usr/src/paperless/src/documents/consumer.py", line 484, in try_consume_file
2023-02-01 07:32:41     self._fail(
2023-02-01 07:32:41   File "/usr/src/paperless/src/documents/consumer.py", line 96, in _fail
2023-02-01 07:32:41     raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
2023-02-01 07:32:41 documents.consumer.ConsumerError: Official GWU Transcript (2017_10_11 11_50_14 UTC).pdf: The following error occurred while consuming Official GWU Transcript (2017_10_11 11_50_14 UTC).pdf: This writer is closed
```

### Paperless-ngx version

1.12.2

### Host OS

MacOS 

### Installation method

Docker - official image

**Comment by shamoon** [comment]
I don’t know if there’s an issue with permissions or accessing the search index file but in the other case it was solved by clean installing, perhaps that’s something to try. But here `FileNotFoundError: [Errno 2] No such file or directory: '/usr/src/paperless/data/index/MAIN_zz5n17mpodmcdexe.seg'` is pretty suspicious. What is your setup for the data volume?

that said, I certainly can’t reproduce this on my end

**Comment by jeff47** [comment]
In the example above, I had hundreds of PDFs happily stored, then it stopped working this morning.  I reindexed, put the failed file back in my consume directory, and it worked.  Wouldn't reindexing within docker hit the same problem, if it was a permissions issue?

Does "mpodmcdexe.seg" indicate something segfaulted?

[docker-compose.yml.txt](https://github.com/paperless-ngx/paperless-ngx/files/10558637/docker-compose.yml.txt)

**Comment by shamoon** [comment]
Yes the intermittent nature does point against that, and looks like your data is a pretty typical local mount.

The .seg files are just part of the search index files, so there’s some concurrency issue perhaps as the file isn’t found. I’m not sure. It may be an issue upstream with whoosh though

**Comment by stumpylog** [comment]
The `AsyncWriter` is the suggested class for writing to the index in a concurrent environment and it's what we use, so that shouldn't be the case.
