### ISSUE TITLE
[BUG] Re-indexing fails with out of range error

### ISSUE THREAD

**Issue by laurentlbm** [paperless-ngx/paperless-ngx#2583]
### Description

Since 1.12.2, the docker container of Paperless crashes when trying to rebuild the search index.

### Steps to reproduce

I don't know.

### Webserver logs

```bash
paperless  | Waiting for Redis...
paperless  | Connected to Redis broker.
paperless  | Apply database migrations...
paperless  | Operations to perform:
paperless  |   Apply all migrations: admin, auth, authtoken, contenttypes, django_celery_results, documents, paperless_mail, sessions
paperless  | Running migrations:
paperless  |   No migrations to apply.
paperless  | Running Django checks
paperless  | System check identified no issues (0 silenced).
paperless  | Search index out of date. Updating...
paperless  | Traceback (most recent call last):
paperless  |   File "/usr/src/paperless/src/manage.py", line 11, in <module>
paperless  |     execute_from_command_line(sys.argv)
paperless  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
paperless  |     utility.execute()
paperless  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
paperless  |     self.fetch_command(subcommand).run_from_argv(self.argv)
paperless  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 402, in run_from_argv
paperless  |     self.execute(*args, **cmd_options)
paperless  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 448, in execute
paperless  |     output = self.handle(*args, **options)
paperless  |   File "/usr/src/paperless/src/documents/management/commands/document_index.py", line 23, in handle
paperless  |     index_reindex(progress_bar_disable=options["no_progress_bar"])
paperless  |   File "/usr/src/paperless/src/documents/tasks.py", line 56, in index_reindex
paperless  |     index.update_document(writer, document)
paperless  |   File "/usr/src/paperless/src/documents/index.py", line 96, in update_document
paperless  |     writer.update_document(
paperless  |   File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 1024, in update_document
paperless  |     self._record("update_document", args, kwargs)
paperless  |   File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 1001, in _record
paperless  |     getattr(self.writer, method)(*args, **kwargs)
paperless  |   File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 490, in update_document
paperless  |     self.add_document(**fields)
paperless  |   File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 750, in add_document
paperless  |     for tbytes, freq, weight, vbytes in items:
paperless  |   File "/usr/local/lib/python3.9/site-packages/whoosh/fields.py", line 669, in index
paperless  |     yield (self.to_bytes(num, shift), 1, 1.0, emptybytes)
paperless  |   File "/usr/local/lib/python3.9/site-packages/whoosh/fields.py", line 722, in to_bytes
paperless  |     x = self.prepare_number(x)
paperless  |   File "/usr/local/lib/python3.9/site-packages/whoosh/fields.py", line 691, in prepare_number
paperless  |     raise ValueError("Numeric field value %s out of range [%s, %s]"
paperless  | ValueError: Numeric field value 1460318454054548 out of range [0, 4294967295]
```

### Paperless-ngx version

1.12.2

### Host OS

Archlinux

### Installation method

Docker - official image

**Comment by laurentlbm** [comment]
I don't know what an ASN is and I haven't entered any manually AFAIK. The error doesn't give me precise info about the offending document.

Either way, it's in an existing document and I don't think a value not being allowed anymore should make an update fail and the app completely stop working. Maybe it could notify the admin or show an error on the dashboard. 

Luckily, I can revert the container to 1.12.1. But what if I couldn't? The re-indexing happens after the database migrations, and if those migrations aren't backward-compatible, you can't go back to your previous version unless you have a proper backup.

**Comment by stumpylog** [comment]
So v1.12.1 works if you run the `reindex` command?  That's odd as the index itself didn't change between those versions.

It was a bug that a value over 1 quadrillion was ever accepted and merely incidental the database happened to be able to store it.  I suppose it's always [some one's workflow](https://xkcd.com/1172/).  The admin page for documents will let you have a look and filter by the ASN, to confirm it is that field.

**Comment by laurentlbm** [comment]
> So v1.12.1 works if you run the reindex command? That's odd as the index itself didn't change between those versions.

Just tested: re-indexing doesn't work in v1.12.1 either. It didn't force a re-index at start-up though, so the container was able to start without crashing.

>  The admin page for documents will let you have a look and filter by the ASN, to confirm it is that field.

Thank you! I found the document and fixed it. v1.12.2 now starts up correctly.

**Comment by stumpylog** [comment]
This will be fixed in the next release.  ASNs out of range will be reset and an error logged, instead of a crash.
