### ISSUE TITLE
[BUG] Consumption fails with Updating PaperlessTask failed: connection already closed

### ISSUE THREAD

**Issue by eLem3ntx** [paperless-ngx/paperless-ngx#2588]
### Description

Since 2 days, no more documents are consumed. It doesn't matter if they are in the consume folder or uploaded manually.
Message on the manual upload says "File uploaded, waiting..." - but it never changes.
The Log shows these Errors:
`[ERROR] [paperless.handlers] Updating PaperlessTask failed: connection already closed`

restarted several times via Portainer.

### Steps to reproduce

putting new files in the consumption folder or manually uploading them via dashboard.

### Webserver logs

```bash
[2023-02-02 15:29:10,105] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/Gescannt_20230202-1253.pdf to the task queue.

[2023-02-02 15:29:10,200] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: /usr/src/paperless/consume

[2023-02-02 16:29:14,016] [DEBUG] [paperless.classifier] Gathering data from database...

[2023-02-02 16:29:16,868] [DEBUG] [paperless.classifier] 132 documents, 6 tag(s), 24 correspondent(s), 13 document type(s). 0 storage path(es)

[2023-02-02 16:29:16,868] [DEBUG] [paperless.classifier] Vectorizing data...

[2023-02-02 16:29:17,124] [DEBUG] [paperless.classifier] Training tags classifier...

[2023-02-02 16:29:19,202] [DEBUG] [paperless.classifier] Training correspondent classifier...

[2023-02-02 16:29:21,119] [DEBUG] [paperless.classifier] Training document type classifier...

[2023-02-02 16:29:22,797] [DEBUG] [paperless.classifier] There are no storage paths. Not training storage path classifier.

[2023-02-02 16:29:22,798] [INFO] [paperless.tasks] Saving updated classifier model to /usr/src/paperless/data/classification_model.pickle...

[2023-02-02 19:53:48,364] [INFO] [paperless.management.consumer] Received SIGINT, stopping inotify

[2023-02-02 19:53:48,365] [DEBUG] [paperless.management.consumer] Consumer exiting.

[2023-02-02 19:53:52,984] [ERROR] [paperless.handlers] Updating PaperlessTask failed: connection already closed

Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task

    R = retval = fun(*args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__

    return self.run(*args, **kwargs)

  File "/usr/src/paperless/src/paperless_mail/tasks.py", line 16, in process_mail_accounts

    total_new_documents += MailAccountHandler().handle_mail_account(account)

  File "/usr/src/paperless/src/paperless_mail/mail.py", line 290, in handle_mail_account

    total_processed_files += self.handle_mail_rule(

  File "/usr/src/paperless/src/paperless_mail/mail.py", line 380, in handle_mail_rule

    for message in messages:

  File "/usr/local/lib/python3.9/site-packages/imap_tools/mailbox.py", line 171, in fetch

    for fetch_item in (self._fetch_in_bulk if bulk else self._fetch_by_one)(nums, message_parts, reverse):  # noqa

  File "/usr/local/lib/python3.9/site-packages/imap_tools/mailbox.py", line 137, in _fetch_by_one

    fetch_result = self.client.fetch(message_num, message_parts)

  File "/usr/local/lib/python3.9/imaplib.py", line 548, in fetch

    typ, dat = self._simple_command(name, message_set, message_parts)

  File "/usr/local/lib/python3.9/imaplib.py", line 1230, in _simple_command

    return self._command_complete(name, self._command(name, *args))

  File "/usr/local/lib/python3.9/imaplib.py", line 1047, in _command_complete

    typ, data = self._get_tagged_response(tag, expect_bye=logout)

  File "/usr/local/lib/python3.9/imaplib.py", line 1173, in _get_tagged_response

    self._get_response()

  File "/usr/local/lib/python3.9/imaplib.py", line 1075, in _get_response

    resp = self._get_line()

  File "/usr/local/lib/python3.9/imaplib.py", line 1183, in _get_line

    line = self.readline()

  File "/usr/local/lib/python3.9/imaplib.py", line 323, in readline

    line = self.file.readline(_MAXLINE + 1)

  File "/usr/local/lib/python3.9/socket.py", line 704, in readinto

    return self._sock.recv_into(b)

  File "/usr/local/lib/python3.9/ssl.py", line 1242, in recv_into

    return self.read(nbytes, buffer)

  File "/usr/local/lib/python3.9/ssl.py", line 1100, in read

    return self._sslobj.read(len, buffer)

  File "/usr/local/lib/python3.9/site-packages/billiard/common.py", line 119, in _shutdown_cleanup

    sys.exit(-(256 - signum))

  File "/usr/local/lib/python3.9/site-packages/billiard/pool.py", line 283, in exit

    return _exit(status)

SystemExit: -241

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 301, in _cursor

    return self._prepare_cursor(self.create_cursor(name))

  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner

    return func(*args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 269, in create_cursor

    cursor = self.connection.cursor()

psycopg2.InterfaceError: connection already closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/signals/handlers.py", line 596, in task_postrun_handler

    task_instance = PaperlessTask.objects.filter(task_id=task_id).first()

  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1047, in first

    for obj in (self if self.ordered else self.order_by("pk"))[:1]:

  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 394, in __iter__

    self._fetch_all()

  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1867, in _fetch_all

    self._result_cache = list(self._iterable_class(self))

  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 87, in __iter__

    results = compiler.execute_sql(

  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1396, in execute_sql

    cursor = self.connection.cursor()

  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner

    return func(*args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 323, in cursor

    return self._cursor()

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 301, in _cursor

    return self._prepare_cursor(self.create_cursor(name))

  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__

    raise dj_exc_value.with_traceback(traceback) from exc_value

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 301, in _cursor

    return self._prepare_cursor(self.create_cursor(name))

  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner

    return func(*args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 269, in create_cursor

    cursor = self.connection.cursor()

django.db.utils.InterfaceError: connection already closed
```

### Paperless-ngx version

1.12.2

### Host OS

linux x86_64 (via docker on synology DS1821+)

### Installation method

Docker - official image

### Browser

Chrome

**Comment by manuelrodegro** [comment]
Same issue here. (1.12.2 running in Docker on a Synology 220+)

**Comment by temak1238** [comment]
Yes, same issue for me on 1.12.2 running in Docker on a Debian VM.

**Comment by stumpylog** [comment]
Based on the very first exception, something is sending a SIGTERM to the worker, while it's in the middle of working.  I can also see the consumer receiving a SIGINT.  Is the system running low on memory?  Or are you stopping the container manually?

**Comment by eLem3ntx** [comment]
> 

So far as i can see there is no low memory or massive CPU drop visible - 20gb of ram and there is used maximal 2gb right now und CPU is low on the integrated quad core ryzen. I think the problem has something to do with the paperless update done automatically via watchtower? Maybe?

**Comment by eLem3ntx** [comment]
So far as i can see there is no low memory or massive CPU drop visible - 20gb of ram and there is used maximal 2gb right now und CPU is low on the integrated quad core ryzen. I think the problem has something to do with the paperless update done automatically via watchtower? Maybe?

**Comment by shamoon** [comment]
Im not aware of what in the last release would affect this. If the most recent version is the issue then downgrading would presumably fix it. Please try that and let us know, otherwise there doesn't seem to be much actionable information here for us, and this certainly doesn't seem to be widespread

**Comment by flooo89** [comment]
I have the same issue. My Documents are stuck in the Queue. Neither the upload, nor the consume folder are working.

**Comment by muecke6** [comment]
I have the same issue 1.12.2 ( 1.12.1 works fine )
error en 1.12.2 ( Error while converting document to PDF: 400 Client Error: Bad Request for url: http://gotenberg:3000/forms/libreoffice/convert#/forms/chromium/convert/html )
no error 1.12.1
😒

**Comment by shamoon** [comment]
Just to clarify, “me too” only applies if your error log shows a very similar output to the above . Also while helpful from a “is this a bigger issue?” perspective, it would be potentially more helpful to get more information beyond that

**Comment by SimpleSimonLA** [comment]
Hi. I've had a similar issue today, I was already on docker version 1.12.2.  

The log was showing the following for new .pdf files in consume folder

```
[2023-02-05 10:19:16,730] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/E79221E2X113703_01012019_000213_000116.pdf to the task queue.

[2023-02-05 10:19:18,010] [ERROR] [paperless.handlers] Creating PaperlessTask failed: server closed the connection unexpectedly

	This probably means the server terminated abnormally

	before or while processing the request.

Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute

    return self.cursor.execute(sql, params)

psycopg2.OperationalError: server closed the connection unexpectedly

	This probably means the server terminated abnormally

	before or while processing the request.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/signals/handlers.py", line 548, in before_task_publish_handler

    PaperlessTask.objects.create(

  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method

    return getattr(self.get_queryset(), name)(*args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 671, in create

    obj.save(force_insert=True, using=self.db)

  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 812, in save

    self.save_base(

  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 863, in save_base

    updated = self._save_table(

  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 1006, in _save_table

    results = self._do_insert(

  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 1047, in _do_insert

    return manager._insert(

  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method

    return getattr(self.get_queryset(), name)(*args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1791, in _insert

    return query.get_compiler(using=using).execute_sql(returning_fields)

  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1660, in execute_sql

    cursor.execute(sql, params)

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute

    return self._execute_with_wrappers(

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers

    return executor(sql, params, many, context)

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute

    return self.cursor.execute(sql, params)

  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__

    raise dj_exc_value.with_traceback(traceback) from exc_value

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute

    return self.cursor.execute(sql, params)

django.db.utils.OperationalError: server closed the connection unexpectedly

	This probably means the server terminated abnormally

	before or while processing the request.
```

When I realized it and couldn't solve it, I've switched back to 1.11. Afterwards it was working fine and "emptied" the consume foled as expected. Log extract with 1.11, same file as above

```
[2023-02-05 15:17:11,923] [INFO] [paperless.consumer] Consuming E79221E2X113703_01012019_000213_000116.pdf

[2023-02-05 15:17:11,931] [DEBUG] [paperless.consumer] Detected mime type: application/pdf

[2023-02-05 15:17:11,951] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser

[2023-02-05 15:17:11,963] [DEBUG] [paperless.consumer] Parsing E79221E2X113703_01012019_000213_000116.pdf...

[2023-02-05 15:17:12,908] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-ngxmuk_apgo/E79221E2X113703_01012019_000213_000116.pdf'), 'output_file': PosixPath('/tmp/paperless/paperless-hdorjkuc/archive.pdf'), 'use_threads': True, 'jobs': 4, 'language': 'deu', 'output_type': 'pdfa', 'progress_bar': False, 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-hdorjkuc/sidecar.txt')}

[2023-02-05 15:18:04,170] [DEBUG] [paperless.parsing.tesseract] Using text from sidecar file

[2023-02-05 15:18:04,172] [DEBUG] [paperless.consumer] Generating thumbnail for E79221E2X113703_01012019_000213_000116.pdf...

[2023-02-05 15:18:04,188] [DEBUG] [paperless.parsing] Execute: convert -density 300 -scale 500x5000> -alpha remove -strip -auto-orient /tmp/paperless/paperless-hdorjkuc/archive.pdf[0] /tmp/paperless/paperless-hdorjkuc/convert.webp

[2023-02-05 15:18:11,234] [DEBUG] [paperless.classifier] Document classification model does not exist (yet), not performing automatic matching.

[2023-02-05 15:18:11,244] [DEBUG] [paperless.consumer] Saving record to database

[2023-02-05 15:18:11,245] [DEBUG] [paperless.consumer] Creation date from parse_date: 2023-01-30 00:00:00+01:00

[2023-02-05 15:18:11,665] [DEBUG] [paperless.consumer] Deleting file /tmp/paperless/paperless-ngxmuk_apgo/E79221E2X113703_01012019_000213_000116.pdf

[2023-02-05 15:18:11,793] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-hdorjkuc

[2023-02-05 15:18:11,795] [INFO] [paperless.consumer] Document 2023-01-30 E79221E2X113703_01012019_000213_000116 consumption finished
```

If you need any more information, let me know.

**Comment by shamoon** [comment]
Both of these log outputs suggest some kind of unexpected shutdown of the db server, the most recent one literally says `This probably means the server terminated abnormally`. It's hard for us to distinguish occasional deployment failures e.g. running out of resources or some other kind of random failure vs a truly reproducible error in the codebase.

@SimpleSimonLA if you switch back to 1.12 can you again reproduce the error? If so, let us know if you are able to provide the file.

Otherwise I worry we're just hearing about occasional crashes on folks' installations, which lets be honest, is going to happen.

**Comment by SimpleSimonLA** [comment]
Okay, I switched back to 1.12 and can confirm that it is working. I cannot reproduce any issue.
Not sure what it was, but I will go on mute again. Thank you :-)
