### ISSUE TITLE
[BUG] Gotenberg Error when processing files

### ISSUE THREAD

**Issue by trunneml** [paperless-ngx/paperless-ngx#2605]
### Description

Processing files are failing with:

```
2022-12-14.eml: Error while consuming document 2022-12-14.eml: Error while converting document to PDF: 503 Server Error: Service Unavailable for url: http://gotenberg:3000/forms/chromium/convert/htm
```

Paperless-NGX is installed by docker-compose. Gotenberg is running with the following settings:

```
  gotenberg:
    image: gotenberg/gotenberg:7.6
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
```

### Steps to reproduce

1. Upload a `eml` file into the consume folder
2. Wait for processing
3. Processing fails with the given error

### Webserver logs

```
[2023-02-04 18:22:19,329] [INFO] [paperless.consumer] Consuming 2022-12-14.eml
[2023-02-04 18:22:19,338] [DEBUG] [paperless.consumer] Detected mime type: message/rfc822
[2023-02-04 18:22:19,438] [DEBUG] [paperless.consumer] Parser: MailDocumentParser
[2023-02-04 18:22:19,455] [DEBUG] [paperless.consumer] Parsing 2022-12-14.eml...
[2023-02-04 18:22:19,460] [INFO] [paperless.parsing.mail] Sending content to Tika server
[2023-02-04 18:22:19,523] [INFO] [paperless.parsing.mail] Converting mail to PDF
[2023-02-04 18:22:49,583] [DEBUG] [paperless.parsing.mail] Deleting directory /tmp/paperless/paperless-i04x_dux
[2023-02-04 18:22:49,594] [ERROR] [paperless.consumer] Error while consuming document 2022-12-14.eml: Error while converting document to PDF: 503 Server Error: Service Unavailable for url: http://gotenberg:3000/forms/chromium/convert/html
Traceback (most recent call last):
  File "/usr/src/paperless/src/paperless_mail/parsers.py", line 291, in generate_pdf_from_mail
    response.raise_for_status()  # ensure we notice bad responses
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://gotenberg:3000/forms/chromium/convert/html
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/consumer.py", line 379, in try_consume_file
    document_parser.parse(self.path, mime_type, self.filename)
  File "/usr/src/paperless/src/paperless_mail/parsers.py", line 145, in parse
    self.archive_path = self.generate_pdf(document_path)
  File "/usr/src/paperless/src/paperless_mail/parsers.py", line 168, in generate_pdf
    pdf_collection.append(("1_mail.pdf", self.generate_pdf_from_mail(mail)))
  File "/usr/src/paperless/src/paperless_mail/parsers.py", line 293, in generate_pdf_from_mail
    raise ParseError(f"Error while converting document to PDF: {err}")
documents.parsers.ParseError: Error while converting document to PDF: 503 Server Error: Service Unavailable for url: http://gotenberg:3000/forms/chromium/convert/html
```

### Gotenberg Docker logs

```
gotenberg_1  | A Docker-powered stateless API for PDF files.
gotenberg_1  | Version: 7.6.2
gotenberg_1  | -------------------------------------------------------
gotenberg_1  | [SYSTEM] modules: api chromium gc libreoffice logging pdfcpu pdfengines pdftk prometheus qpdf uno uno-pdfengine webhook
gotenberg_1  | [SYSTEM] prometheus: collecting metrics
gotenberg_1  | [SYSTEM] uno: long-running LibreOffice listener ready to start
gotenberg_1  | [SYSTEM] pdfengines: pdfcpu pdftk qpdf uno-pdfengine
gotenberg_1  | [SYSTEM] gc: application started
gotenberg_1  | [SYSTEM] api: server listening on port 3000
gotenberg_1  | {"level":"error","ts":1675531300.674187,"logger":"api","msg":"convert HTML to PDF: convert PDF: convert PDF to 'PDF/A-2b' with multi PDF engines: convert PDF to 'PDF/A-2b' with PDFcpu: method not available; convert PDF to 'PDF/A-2b' with PDFtk: method not available; convert PDF to 'PDF/A-2b' with QPDF: method not available; convert PDF to 'PDF/A-2b' with unoconv: lock long-running LibreOffice listener: start long-running LibreOffice listener: LibreOffice listener socket not available: context deadline exceeded","trace":"12b02880-53e1-4fa1-8031-9151e387fa7f","remote_ip":"172.19.0.6","host":"gotenberg:3000","uri":"/forms/chromium/convert/html","method":"POST","path":"/forms/chromium/convert/html","referer":"","user_agent":"python-requests/2.28.1","status":503,"latency":19684591568,"latency_human":"19.684591568s","bytes_in":15045,"bytes_out":19}
gotenberg_1  | {"level":"error","ts":1675531334.2500422,"logger":"api","msg":"convert HTML to PDF: convert PDF: context deadline exceeded","trace":"9b3f611a-2b32-4536-9b2b-cd6d86e25d7a","remote_ip":"172.19.0.6","host":"gotenberg:3000","uri":"/forms/chromium/convert/html","method":"POST","path":"/forms/chromium/convert/html","referer":"","user_agent":"python-requests/2.28.1","status":503,"latency":30001769351,"latency_human":"30.001769351s","bytes_in":15045,"bytes_out":19}
gotenberg_1  | {"level":"error","ts":1675531369.5818346,"logger":"api","msg":"convert HTML to PDF: convert PDF: context deadline exceeded","trace":"357e99a4-9380-4c63-97ab-c2cd8e7c005a","remote_ip":"172.19.0.6","host":"gotenberg:3000","uri":"/forms/chromium/convert/html","method":"POST","path":"/forms/chromium/convert/html","referer":"","user_agent":"python-requests/2.28.1","status":503,"latency":30001468965,"latency_human":"30.001468965s","bytes_in":15045,"bytes_out":19}
```

### Paperless-ngx version

1.12.2

### Host OS

Synology NAS (Intel/amd64)

### Installation method

Docker - official image

### Browser

Firefox

**Comment by shamoon** [comment]
Please try upgrading (or downgrading) gotenberg, this is probably a duplicate of #2065

**Comment by trunneml** [comment]
@shamoon Thanks a lot. Updating gotenberg to 7.7.2 helped.

Because of the slow CPU I also increased Timeouts. For other people here is my gotenberg docker-compose settings:

```
  gotenberg:
    image: gotenberg/gotenberg:7.7
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--log-level=debug"
      - "--api-timeout=600s"
      - "--uno-listener-start-timeout=180s"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*
```
