### ISSUE TITLE
[BUG] Unsupported mime type message/rfc822

### ISSUE THREAD

**Issue by NODeeJay** [paperless-ngx/paperless-ngx#2606]
### Description

Emails imported from Exchange IMAP seem not to work well, when the content is not plain text.
If a PDF is attached it is still exported correctly, but the content of the mail is not.

Example email:
[Google Alert - Daily Digest.zip](https://github.com/paperless-ngx/paperless-ngx/files/10609920/Google.Alert.-.Daily.Digest.zip)

### Steps to reproduce

1. Setup mail in the UI
2. Setup a rule, in my case I have a dedicated folder called __DA_
![image](https://user-images.githubusercontent.com/83764033/216794719-b82abc59-0ad0-4e01-a89f-3aebcc6c1141.png)
4. add an email unread that is not plain text

### Webserver logs

```bash
[2023-02-05 00:50:00,098] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
[2023-02-05 00:50:00,108] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[935e8c1a-531f-46ab-b92d-806971f8c4b3] received
[2023-02-05 00:50:01,149] [INFO] [celery.app.trace] Task paperless_mail.tasks.process_mail_accounts[935e8c1a-531f-46ab-b92d-806971f8c4b3] succeeded in 1.033086605999415s: 'No new documents were added.'
[2023-02-05 01:00:00,095] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
[2023-02-05 01:00:00,105] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[93bfc053-193b-4d3b-8f2c-d438f61a0acd] received
[2023-02-05 01:00:01,145] [INFO] [paperless_mail] Rule Alex Inbox.Alex _DA: Consuming eml from mail Google Alert - Daily Digest from googlealerts-noreply@google.com
[2023-02-05 01:00:01,190] [INFO] [celery.worker.strategy] Task documents.tasks.consume_file[98cc61f5-7526-4261-b99a-165917745f0e] received
[2023-02-05 01:00:01,274] [INFO] [celery.app.trace] Task paperless_mail.tasks.process_mail_accounts[93bfc053-193b-4d3b-8f2c-d438f61a0acd] succeeded in 1.1610787240006175s: 'Added 1 document(s).'
[05/Feb/2023:01:00:02 +0100] 200 -(192.168.103.209) GET /api/tasks/ HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36)
[2023-02-05 01:00:04,315] [INFO] [paperless.consumer] Consuming Google Alert - Daily Digest.eml
[2023-02-05 01:00:04,362] [ERROR] [paperless.consumer] Unsupported mime type message/rfc822
[2023-02-05 01:00:04,384] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[98cc61f5-7526-4261-b99a-165917745f0e] raised unexpected: ConsumerError('Google Alert - Daily Digest.eml: Unsupported mime type message/rfc822')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/paperless/src/documents/tasks.py", line 192, in consume_file
    document = Consumer().try_consume_file(
  File "/usr/src/paperless/src/documents/consumer.py", line 340, in try_consume_file
    self._fail(MESSAGE_UNSUPPORTED_TYPE, f"Unsupported mime type {mime_type}")
  File "/usr/src/paperless/src/documents/consumer.py", line 96, in _fail
    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
documents.consumer.ConsumerError: Google Alert - Daily Digest.eml: Unsupported mime type message/rfc822
[05/Feb/2023:01:00:04 +0100] 200 -(192.168.103.209) GET /api/tasks/ HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36)
```

### Paperless-ngx version

1.12.2

### Host OS

Home Assistant (amd64)

### Installation method

Other (please describe above)

### Configuration changes

PAPERLESS_OCR_CLEAN: clean-final PAPERLESS_MEDIA_ROOT: "/mnt/Paperless/media" PAPERLESS_COMMENTS_ENABLED: true

### Other

MS Exchange 2016

**Comment by shamoon** [comment]
Please search around, this has been reported many times and happens when you haven’t enabled tika and gotenberg which are required for eml parsing
