### ISSUE TITLE
[BUG] Big documents (100MB) filling up /var/lib/docker/overlay2

### ISSUE THREAD

**Issue by derAlff** [paperless-ngx/paperless-ngx#2715]
### Description

I scanned an insurance policy and imported the ~100MB big document to paperless-ngx. The process started, and aifter 5 minutes the paperless webserver shows me code 500. I took a look at the commandline of the docker host and seen, there is my Systempartition full (10GB). After restarting docker compose (portainer) there wasn't any free of the filesystem. So i restored the machine and tested again.... Same problem :(

At the moment I had resized the storage of my systempartition to 64GB. I tested the 100MG document again.... it failed... i think this is the error inside the logfile:

```
[2023-02-19 20:31:43,005] [ERROR] [paperless.handlers] Updating PaperlessTask failed: terminating connection due to administrator command

server closed the connection unexpectedly

	This probably means the server terminated abnormally

	before or while processing the request.

Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task

    R = retval = fun(*args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__

    return self.run(*args, **kwargs)

  File "/usr/src/paperless/src/documents/tasks.py", line 46, in index_optimize

    writer.commit(optimize=True)

  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 1037, in commit

    self.writer.commit(*args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 922, in commit

    finalsegments = self._merge_segments(mergetype, optimize, merge)

  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 827, in _merge_segments

    return mergetype(self, self.segments)

  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 116, in OPTIMIZE

    writer.add_reader(reader)

  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 710, in add_reader

    self.add_postings_to_pool(reader, basedoc, docmap)

  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 647, in add_postings_to_pool

    for item in items:

  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 583, in _process_posts

    for fieldname, text, docnum, weight, vbytes in items:

  File "/usr/local/lib/python3.9/site-packages/whoosh/reading.py", line 427, in iter_postings

    m = self.postings(fieldname, btext)

  File "/usr/local/lib/python3.9/site-packages/whoosh/reading.py", line 818, in postings

    matcher = self._terms.matcher(fieldname, text, format_, scorer=scorer)

  File "/usr/local/lib/python3.9/site-packages/whoosh/codec/whoosh3.py", line 635, in matcher

    m = self._codec.postings_reader(self._postfile, terminfo, format_,

  File "/usr/local/lib/python3.9/site-packages/whoosh/codec/whoosh3.py", line 108, in postings_reader

    m = W3LeafMatcher(dbfile, offset, length, format_, term=term,

  File "/usr/local/lib/python3.9/site-packages/whoosh/codec/whoosh3.py", line 885, in __init__

    self._read_header()

  File "/usr/local/lib/python3.9/site-packages/whoosh/codec/whoosh3.py", line 899, in _read_header

    self._baseoffset = postfile.tell()

  File "/usr/local/lib/python3.9/site-packages/billiard/common.py", line 119, in _shutdown_cleanup

    sys.exit(-(256 - signum))

  File "/usr/local/lib/python3.9/site-packages/billiard/pool.py", line 283, in exit

    return _exit(status)

SystemExit: -241

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute

    return self.cursor.execute(sql, params)

psycopg2.errors.AdminShutdown: terminating connection due to administrator command

server closed the connection unexpectedly

	This probably means the server terminated abnormally

	before or while processing the request.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/signals/handlers.py", line 596, in task_postrun_handler

    task_instance = PaperlessTask.objects.filter(task_id=task_id).first()

  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1047, in first

    for obj in (self if self.ordered else self.order_by("pk"))[:1]:

  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 394, in __iter__

    self._fetch_all()

  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1867, in _fetch_all

    self._result_cache = list(self._iterable_class(self))

  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 87, in __iter__

    results = compiler.execute_sql(

  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1398, in execute_sql

    cursor.execute(sql, params)

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute

    return self._execute_with_wrappers(

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers

    return executor(sql, params, many, context)

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute

    return self.cursor.execute(sql, params)

  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__

    raise dj_exc_value.with_traceback(traceback) from exc_value

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute

    return self.cursor.execute(sql, params)

django.db.utils.OperationalError: terminating connection due to administrator command

server closed the connection unexpectedly

	This probably means the server terminated abnormally

	before or while processing the request.
```

At the moment I split big documents and sort them by adding the same ASN with an extra extension. Its a workaround to add the complete document.

But, how can I free up the `/var/lib/docker/overlay2/` ? 

I had seen... when I import a document with a size of ~4MB, the `/var/lib/docker/overlay2/` grows up for 1GB and when the document is finished, `/var/lib/docker/overlay2/` is the same like before starting.

I think, when the task fails, and i remove the Task, the `/var/lib/docker/overlay2/` is not free up. Is that possible?

Here is a picture of the `df -h` BY the import and AFTER the import on my docker host:
![image](https://user-images.githubusercontent.com/64785948/220065178-fe001a7a-78e9-40e2-9ac4-7c51a238e0a5.png)

### Steps to reproduce

1. Upload a document with a size of ~100MB
2. See `df -h`
3. When the webserver goes down, restart the docker-compose
4. the Task is not finished and stays there. Delete it from Tasks
5. See `df -h`, `/var/lib/docker/overlay2` should grow up. (do this zwo or more times)

### Webserver logs

```bash
Don't saved the log :(
```

### Browser logs

```bash
[2023-02-19 20:31:43,005] [ERROR] [paperless.handlers] Updating PaperlessTask failed: terminating connection due to administrator command

server closed the connection unexpectedly

	This probably means the server terminated abnormally

	before or while processing the request.

Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task

    R = retval = fun(*args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__

    return self.run(*args, **kwargs)

  File "/usr/src/paperless/src/documents/tasks.py", line 46, in index_optimize

    writer.commit(optimize=True)

  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 1037, in commit

    self.writer.commit(*args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 922, in commit

    finalsegments = self._merge_segments(mergetype, optimize, merge)

  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 827, in _merge_segments

    return mergetype(self, self.segments)

  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 116, in OPTIMIZE

    writer.add_reader(reader)

  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 710, in add_reader

    self.add_postings_to_pool(reader, basedoc, docmap)

  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 647, in add_postings_to_pool

    for item in items:

  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 583, in _process_posts

    for fieldname, text, docnum, weight, vbytes in items:

  File "/usr/local/lib/python3.9/site-packages/whoosh/reading.py", line 427, in iter_postings

    m = self.postings(fieldname, btext)

  File "/usr/local/lib/python3.9/site-packages/whoosh/reading.py", line 818, in postings

    matcher = self._terms.matcher(fieldname, text, format_, scorer=scorer)

  File "/usr/local/lib/python3.9/site-packages/whoosh/codec/whoosh3.py", line 635, in matcher

    m = self._codec.postings_reader(self._postfile, terminfo, format_,

  File "/usr/local/lib/python3.9/site-packages/whoosh/codec/whoosh3.py", line 108, in postings_reader

    m = W3LeafMatcher(dbfile, offset, length, format_, term=term,

  File "/usr/local/lib/python3.9/site-packages/whoosh/codec/whoosh3.py", line 885, in __init__

    self._read_header()

  File "/usr/local/lib/python3.9/site-packages/whoosh/codec/whoosh3.py", line 899, in _read_header

    self._baseoffset = postfile.tell()

  File "/usr/local/lib/python3.9/site-packages/billiard/common.py", line 119, in _shutdown_cleanup

    sys.exit(-(256 - signum))

  File "/usr/local/lib/python3.9/site-packages/billiard/pool.py", line 283, in exit

    return _exit(status)

SystemExit: -241

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute

    return self.cursor.execute(sql, params)

psycopg2.errors.AdminShutdown: terminating connection due to administrator command

server closed the connection unexpectedly

	This probably means the server terminated abnormally

	before or while processing the request.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/signals/handlers.py", line 596, in task_postrun_handler

    task_instance = PaperlessTask.objects.filter(task_id=task_id).first()

  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1047, in first

    for obj in (self if self.ordered else self.order_by("pk"))[:1]:

  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 394, in __iter__

    self._fetch_all()

  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1867, in _fetch_all

    self._result_cache = list(self._iterable_class(self))

  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 87, in __iter__

    results = compiler.execute_sql(

  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1398, in execute_sql

    cursor.execute(sql, params)

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute

    return self._execute_with_wrappers(

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers

    return executor(sql, params, many, context)

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute

    return self.cursor.execute(sql, params)

  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__

    raise dj_exc_value.with_traceback(traceback) from exc_value

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute

    return self.cursor.execute(sql, params)

django.db.utils.OperationalError: terminating connection due to administrator command

server closed the connection unexpectedly

	This probably means the server terminated abnormally

	before or while processing the request.
```
```


### Paperless-ngx version

1.12.2

### Host OS

Debian 11 x86_64

### Installation method

Docker - official image

### Browser

Brave

### Configuration changes

Canged:

### Other

_No response_

**Comment by sbrunner** [comment]
Do you try to use the consume directory?

**Comment by derAlff** [comment]
Had tried the consume folder and the upload function of the webpage.

The problem with filled `/var/lib/docker/overlay2` is fixed by a recreate of the webserver image... strange... but uploading big PDFs is still not possible :(

**Comment by stumpylog** [comment]
The external size of `/var/lib/docker/overlay2/` isn't the most helpful metric.  You could try some of the commands from [here](https://buisteven.medium.com/debugging-docker-overlay2-out-of-space-d1edc2ea412f) and see where the actual size increase is coming from.

**Comment by encbladexp** [comment]
I would also recommend to take a look with ncdu on the folder/container, to see where the space goes. Either mount this (most likely temporary) directory to another host path or move `/var/lib/docker` to a sufficient big volume/partition.

**Comment by MichaelSasser** [comment]
For me, it was the `/tmp` directory in the container piling up. I think the files were all around 24 MB in size. In total, the `/tmp` directory had over 25 GB. I've imported around 1.4k files, most of them fairly small:
```
  1k:     22
  2k:      3
  4k:      4
  8k:     37
 16k:     74
 32k:    127
 64k:    201
128k:    241
256k:    227
512k:    164
  1M:    164
  2M:     65
  4M:     41
  8M:     29
 16M:     25
 32M:      9
 64M:      4
128M:      3
```

Though, I might not have been very generously with the capabilities initially and caused the issue myself.

```yaml
cap_drop:
  - all
capabilities:
  - chown
  - setuid
  - setgid
  - dac_override
```

I have 9-ish MB of logs, but redacting personal information in there would take ages.

(Version: Paperless-ngx 1.14.4; official images; Docker version 23.0.6, build ef23cbc; Linux app-07 5.10.0-22-arm64 #1 SMP Debian 5.10.178-3 (2023-04-22) aarch64 GNU/Linux)
