### ISSUE TITLE
gotenberg error while uploading .docx file

### ISSUE THREAD

**Issue by mdangst** [paperless-ngx/paperless-ngx#2723]
### Description

gotenberg error after uploading a .docx file.

My configuration:
      environment:
      # ...

      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

    gotenberg:
      image: gotenberg/gotenberg:7.8
      restart: unless-stopped
    
      command:
        - 'gotenberg'
        - '--chromium-disable-javascript=true'
        - '--chromium-allow-list=file:///tmp/.*'

![gotenberg error](https://user-images.githubusercontent.com/118683900/220201618-b86f5c7f-f6d3-4b40-8c20-4b4731bd759e.PNG)

### Steps to reproduce

See error above and below

### Webserver logs

```bash
documents.parsers.ParseError: Error while converting document to PDF: 503 Server Error: Service Unavailable for url: http://gotenberg:3000/forms/libreoffice/convert

[2023-02-20 22:29:56,573] [INFO] [paperless.consumer] Consuming paperless ngx.docx

[2023-02-20 22:29:56,704] [DEBUG] [paperless.consumer] Detected mime type: application/vnd.openxmlformats-officedocument.wordprocessingml.document

[2023-02-20 22:29:57,194] [DEBUG] [paperless.consumer] Parser: TikaDocumentParser

[2023-02-20 22:29:57,200] [DEBUG] [paperless.consumer] Parsing paperless ngx.docx...

[2023-02-20 22:29:57,201] [INFO] [paperless.parsing.tika] Sending /tmp/paperless/paperless-ngxsc57oakr/paperless ngx.docx to Tika server

[2023-02-20 22:30:01,095] [WARNING] [paperless.parsing.tika] Unable to extract date for document /tmp/paperless/paperless-ngxsc57oakr/paperless ngx.docx: 'Creation-Date'

[2023-02-20 22:30:01,096] [INFO] [paperless.parsing.tika] Converting /tmp/paperless/paperless-ngxsc57oakr/paperless ngx.docx to PDF as /tmp/paperless/paperless-fs1n356g/convert.pdf

[2023-02-20 22:30:12,245] [DEBUG] [paperless.parsing.tika] Deleting directory /tmp/paperless/paperless-fs1n356g

[2023-02-20 22:30:12,894] [ERROR] [paperless.consumer] Error while consuming document paperless ngx.docx: Error while converting document to PDF: 503 Server Error: Service Unavailable for url: http://gotenberg:3000/forms/libreoffice/convert

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_tika/parsers.py", line 111, in convert_to_pdf

    response.raise_for_status()  # ensure we notice bad responses

  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status

    raise HTTPError(http_error_msg, response=self)

requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://gotenberg:3000/forms/libreoffice/convert

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/consumer.py", line 385, in try_consume_file

    document_parser.parse(self.path, mime_type, self.filename)

  File "/usr/src/paperless/src/paperless_tika/parsers.py", line 82, in parse

    self.archive_path = self.convert_to_pdf(document_path, file_name)

  File "/usr/src/paperless/src/paperless_tika/parsers.py", line 113, in convert_to_pdf

    raise ParseError(

documents.parsers.ParseError: Error while converting document to PDF: 503 Server Error: Service Unavailable for url: http://gotenberg:3000/forms/libreoffice/convert

[2023-02-20 23:05:06,618] [DEBUG] [paperless.classifier] Gathering data from database...

[2023-02-20 23:05:21,487] [DEBUG] [paperless.tasks] Training data unchanged.
```

### Paperless-ngx version

1.13.0

### Host OS

DSM 7.1.1-42962 Update 3 (Synology 420)

### Installation method

Docker - official image

### Browser

Chrome

**Comment by shamoon** [comment]
How about with Gutenberg version 7.7.2? There have been a bunch of issues with Gutenberg lately

**Comment by Auer1329** [comment]
For me it worked on version 1.12.2 after upgrading to Gotenberg 7.8.

Are you sure all containers are started up properly? In my case it seemed like I had to wait a bit longer after startup.

I am using the Gotenberg container with a fixed name, but I don't know if that makes any difference.

```
  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.8
    restart: unless-stopped
    container_name: gotenberg

    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
```

**Comment by mdangst** [comment]
> For me it worked on version 1.12.2 after upgrading to Gotenberg 7.8.
> 
> Are you sure all containers are started up properly? In my case it seemed like I had to wait a bit longer after startup.
> 
> I am using the Gotenberg container with a fixed name, but I don't know if that makes any difference.
> 
> ```
>   gotenberg:
>     image: docker.io/gotenberg/gotenberg:7.8
>     restart: unless-stopped
>     container_name: gotenberg
> 
>     command:
>       - "gotenberg"
>       - "--chromium-disable-javascript=true"
>       - "--chromium-allow-list=file:///tmp/.*"
> ```

Hi, all is up and runnning, including the gotenberg container. However it is not possible to upload a .docx file
![gotenberg error](https://user-images.githubusercontent.com/118683900/220429144-cc6ee657-fb63-4d40-8f60-91e9f638d0c0.PNG)
