### ISSUE TITLE
[BUG] documents.parsers.ParseError: AttributeError: /MediaBox

### ISSUE THREAD

**Issue by macross5** [paperless-ngx/paperless-ngx#2923]
### Description

Currently Paperless cant import a PDF File from german company Sixt because the following Error: documents.parsers.ParseError: AttributeError: /MediaBox

The PDF File isnt password protected. 

### Steps to reproduce

1. Move the file to the consumer folder
2. wait..
3. get the Error Message in log

### Webserver logs

```bash
[2023-03-21 06:35:16,290] [INFO] [paperless.consumer] Consuming CIR9473514602_0421.PDF

[2023-03-21 06:35:16,298] [DEBUG] [paperless.consumer] Detected mime type: application/pdf

[2023-03-21 06:35:16,302] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser

[2023-03-21 06:35:16,320] [DEBUG] [paperless.consumer] Parsing CIR9473514602_0421.PDF...

[2023-03-21 06:35:16,725] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-ngxut0xrtqo/CIR9473514602_0421.PDF'), 'output_file': PosixPath('/tmp/paperless/paperless-5e2dba8x/archive.pdf'), 'use_threads': True, 'jobs': '1', 'language': 'deu', 'output_type': 'pdfa', 'progress_bar': False, 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-5e2dba8x/sidecar.txt')}

[2023-03-21 06:35:17,621] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-5e2dba8x

[2023-03-21 06:35:17,640] [ERROR] [paperless.consumer] Error while consuming document CIR9473514602_0421.PDF: AttributeError: /MediaBox

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 321, in parse

    ocrmypdf.ocr(**args)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/api.py", line 332, in ocr

    return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 378, in run_pipeline

    pdfinfo = get_pdfinfo(

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 165, in get_pdfinfo

    return PdfInfo(

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 932, in __init__

    self._pages = _pdf_pageinfo_concurrent(

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 709, in _pdf_pageinfo_concurrent

    executor(

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_concurrent.py", line 87, in __call__

    self._execute(

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/builtin_plugins/concurrency.py", line 141, in _execute

    result = future.result()

  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result

    return self.__get_result()

  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result

    raise self._exception

  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run

    result = self.fn(*self.args, **self.kwargs)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 666, in _pdf_pageinfo_sync

    page = PageInfo(pdf, pageno, infile, check_pages, detailed_analysis)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 746, in __init__

    self._gather_pageinfo(pdf, pageno, infile, check_pages, detailed_analysis)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 757, in _gather_pageinfo

    mediabox = [Decimal(d) for d in page.MediaBox.as_list()]

  File "/usr/local/lib/python3.9/site-packages/pikepdf/_methods.py", line 1117, in __getattr__

    return getattr(self.obj, name)

AttributeError: /MediaBox

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/consumer.py", line 385, in try_consume_file

    document_parser.parse(self.path, mime_type, self.filename)

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 379, in parse

    raise ParseError(f"{e.__class__.__name__}: {str(e)}") from e

documents.parsers.ParseError: AttributeError: /MediaBox
```

### Paperless-ngx version

1.13.0

### Host OS

Raspberry Pi 4 B arm64

### Installation method

Docker - official image

**Comment by stumpylog** [comment]
As that error arrises from inside OCRMyPDF and pikepdf, it's likely there is little we can do to assist.  You can try "cleaning" the file with QPDF, which can sometimes fix invalid PDFs.
