### ISSUE TITLE
[BUG] Not checking mail after redis restart (Celery tasks show as REVOKED)

### ISSUE THREAD

**Issue by yaakovfeldman** [paperless-ngx/paperless-ngx#2926]
### Description

I am running paperless-ngx in Docker. My Docker setup includes the Watchtower container which auto updates all other containers (I have since stopped this).

At around 12 last night it restarted the redis container. Since then paperless-ngx stopped checking mail and processing scans from the files queue (scans in the local watch folder were being added to the queue but not being processed).

I restarted all the containers and processing restarted. I ended up with all scans being added a second time to the queue but that sorted itself out (they were not processed a second time as the original processing had already moved them out the watch folder). However mail is still not being checked.

I see in Django admin that the Celery task `paperless_mail.tasks.process_mail_accounts` is being called regularly but the result is always `REVOKED`. 

After the redis restart at midnight, but before I restarted the whole stack, the log (in docker) is full of (every 10 minutes, which is my mail check frequency)

    2023-03-21 01:20:00 [2023-03-21 01:20:00,059] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)

with no results. After I restarted the stack it is now full of

    2023-03-21 12:36:06 [2023-03-21 12:36:06,018] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[b78dc734-2de4-45e5-9421-9ec6b168c222] received
    2023-03-21 12:36:06 [2023-03-21 12:36:06,019] [INFO] [celery.worker.request] Discarding revoked task: paperless_mail.tasks.process_mail_accounts[b78dc734-2de4-45e5-9421-9ec6b168c222]

There is nothing related in paperless.log and no errors in mail.log. There are no entries in mail.log at all since before midnight.

In the 'webserver logs' below I have included the docker logs from around midnight (the Watchtower restart of redis) and around noon (the manual restart).

### Steps to reproduce

Restart redis? Not sure if this can be reproduced

### Webserver logs

```bash
2023-03-21 00:10:00 [2023-03-21 00:10:00,063] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
2023-03-21 00:10:00 [2023-03-21 00:10:00,070] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[ad1c2eda-d234-4b97-ad44-c1d848b47702] received
2023-03-21 00:10:01 [2023-03-21 00:10:01,378] [INFO] [celery.app.trace] Task paperless_mail.tasks.process_mail_accounts[ad1c2eda-d234-4b97-ad44-c1d848b47702] succeeded in 1.3017274150042795s: 'No new documents were added.'
2023-03-21 00:20:00 [2023-03-21 00:20:00,070] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
2023-03-21 00:20:00 [2023-03-21 00:20:00,076] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[0a7d1063-7496-4def-af41-f5deb97255ca] received
2023-03-21 00:20:01 [2023-03-21 00:20:01,038] [INFO] [celery.app.trace] Task paperless_mail.tasks.process_mail_accounts[0a7d1063-7496-4def-af41-f5deb97255ca] succeeded in 0.9564024010032881s: 'No new documents were added.'
2023-03-21 00:30:00 [2023-03-21 00:30:00,091] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
2023-03-21 00:30:00 [2023-03-21 00:30:00,102] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[5b535945-527c-4c0b-b254-5285af827f91] received
2023-03-21 00:30:01 [2023-03-21 00:30:01,310] [INFO] [celery.app.trace] Task paperless_mail.tasks.process_mail_accounts[5b535945-527c-4c0b-b254-5285af827f91] succeeded in 1.2006912099895999s: 'No new documents were added.'
2023-03-21 00:40:00 [2023-03-21 00:40:00,092] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
2023-03-21 00:40:00 [2023-03-21 00:40:00,099] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[ba49c723-05f1-43c0-b93d-c2061bc5b21c] received
2023-03-21 00:40:01 [2023-03-21 00:40:01,069] [INFO] [celery.app.trace] Task paperless_mail.tasks.process_mail_accounts[ba49c723-05f1-43c0-b93d-c2061bc5b21c] succeeded in 0.9659749959973851s: 'No new documents were added.'
2023-03-21 00:43:27 [2023-03-21 00:43:26,873] [WARNING] [celery.worker.consumer.consumer] consumer: Connection to broker lost. Trying to re-establish the connection...
2023-03-21 00:43:27 Traceback (most recent call last):
2023-03-21 00:43:27   File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 332, in start
2023-03-21 00:43:27     blueprint.start(self)
2023-03-21 00:43:27   File "/usr/local/lib/python3.9/site-packages/celery/bootsteps.py", line 116, in start
2023-03-21 00:43:27     step.start(parent)
2023-03-21 00:43:27   File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 628, in start
2023-03-21 00:43:27     c.loop(*c.loop_args())
2023-03-21 00:43:27   File "/usr/local/lib/python3.9/site-packages/celery/worker/loops.py", line 97, in asynloop
2023-03-21 00:43:27     next(loop)
2023-03-21 00:43:27   File "/usr/local/lib/python3.9/site-packages/kombu/asynchronous/hub.py", line 362, in create_loop
2023-03-21 00:43:27     cb(*cbargs)
2023-03-21 00:43:27   File "/usr/local/lib/python3.9/site-packages/kombu/transport/redis.py", line 1326, in on_readable
2023-03-21 00:43:27     self.cycle.on_readable(fileno)
2023-03-21 00:43:27   File "/usr/local/lib/python3.9/site-packages/kombu/transport/redis.py", line 562, in on_readable
2023-03-21 00:43:27     chan.handlers[type]()
2023-03-21 00:43:27   File "/usr/local/lib/python3.9/site-packages/kombu/transport/redis.py", line 906, in _receive
2023-03-21 00:43:27     ret.append(self._receive_one(c))
2023-03-21 00:43:27   File "/usr/local/lib/python3.9/site-packages/kombu/transport/redis.py", line 916, in _receive_one
2023-03-21 00:43:27     response = c.parse_response()
2023-03-21 00:43:27   File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1531, in parse_response
2023-03-21 00:43:27     response = self._execute(conn, try_read)
2023-03-21 00:43:27   File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1507, in _execute
2023-03-21 00:43:27     return conn.retry.call_with_retry(
2023-03-21 00:43:27   File "/usr/local/lib/python3.9/site-packages/redis/retry.py", line 49, in call_with_retry
2023-03-21 00:43:27     fail(error)
2023-03-21 00:43:27   File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1509, in <lambda>
2023-03-21 00:43:27     lambda error: self._disconnect_raise_connect(conn, error),
2023-03-21 00:43:27   File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1496, in _disconnect_raise_connect
2023-03-21 00:43:27     raise error
2023-03-21 00:43:27   File "/usr/local/lib/python3.9/site-packages/redis/retry.py", line 46, in call_with_retry
2023-03-21 00:43:27     return do()
2023-03-21 00:43:27   File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1508, in <lambda>
2023-03-21 00:43:27     lambda: command(*args, **kwargs),
2023-03-21 00:43:27   File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1529, in try_read
2023-03-21 00:43:27     return conn.read_response()
2023-03-21 00:43:27   File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 848, in read_response
2023-03-21 00:43:27     response = self._parser.read_response(disable_decoding=disable_decoding)
2023-03-21 00:43:27   File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 482, in read_response
2023-03-21 00:43:27     self.read_from_socket()
2023-03-21 00:43:27   File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 444, in read_from_socket
2023-03-21 00:43:27     raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
2023-03-21 00:43:27 redis.exceptions.ConnectionError: Connection closed by server.
2023-03-21 00:43:27 [2023-03-21 00:43:27,019] [WARNING] [py.warnings] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:367: CPendingDeprecationWarning: 
2023-03-21 00:43:27 In Celery 5.1 we introduced an optional breaking change which
2023-03-21 00:43:27 on connection loss cancels all currently executed tasks with late acknowledgement enabled.
2023-03-21 00:43:27 These tasks cannot be acknowledged as the connection is gone, and the tasks are automatically redelivered back to the queue.
2023-03-21 00:43:27 You can enable this behavior using the worker_cancel_long_running_tasks_on_connection_loss setting.
2023-03-21 00:43:27 In Celery 5.1 it is set to False by default. The setting will be set to True by default in Celery 6.0.
2023-03-21 00:43:27 
2023-03-21 00:43:27   warnings.warn(CANCEL_TASKS_BY_DEFAULT, CPendingDeprecationWarning)
2023-03-21 00:43:27 
2023-03-21 00:43:27 [2023-03-21 00:43:27,125] [ERROR] [celery.worker.consumer.consumer] consumer: Cannot connect to redis://broker:6379//: Error 111 connecting to broker:6379. Connection refused..
2023-03-21 00:43:27 Trying again in 2.00 seconds... (1/100)
2023-03-21 00:43:27 
2023-03-21 00:43:29 [2023-03-21 00:43:29,326] [ERROR] [celery.worker.consumer.consumer] consumer: Cannot connect to redis://broker:6379//: Error -5 connecting to broker:6379. No address associated with hostname..
2023-03-21 00:43:29 Trying again in 4.00 seconds... (2/100)
2023-03-21 00:43:29 
2023-03-21 00:43:33 [2023-03-21 00:43:33,429] [ERROR] [celery.worker.consumer.consumer] consumer: Cannot connect to redis://broker:6379//: Error -5 connecting to broker:6379. No address associated with hostname..
2023-03-21 00:43:33 Trying again in 6.00 seconds... (3/100)
2023-03-21 00:43:33 
2023-03-21 00:43:39 [2023-03-21 00:43:39,722] [ERROR] [celery.worker.consumer.consumer] consumer: Cannot connect to redis://broker:6379//: Error -5 connecting to broker:6379. No address associated with hostname..
2023-03-21 00:43:39 Trying again in 8.00 seconds... (4/100)
2023-03-21 00:43:39 
2023-03-21 00:43:47 [2023-03-21 00:43:47,815] [INFO] [celery.worker.consumer.connection] Connected to redis://broker:6379//
2023-03-21 00:43:47 [2023-03-21 00:43:47,964] [INFO] [celery.worker.consumer.mingle] mingle: searching for neighbors
2023-03-21 00:43:49 [2023-03-21 00:43:49,191] [INFO] [celery.worker.consumer.mingle] mingle: all alone
2023-03-21 00:50:00 [2023-03-21 00:50:00,091] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
2023-03-21 00:50:00 [2023-03-21 00:50:00,098] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[6156c1ed-b0b6-4cce-97bd-a0a897798d5a] received
2023-03-21 00:50:01 [2023-03-21 00:50:01,085] [INFO] [celery.app.trace] Task paperless_mail.tasks.process_mail_accounts[6156c1ed-b0b6-4cce-97bd-a0a897798d5a] succeeded in 0.9831547429930652s: 'No new documents were added.'
2023-03-21 01:00:00 [2023-03-21 01:00:00,041] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
2023-03-21 01:05:00 [2023-03-21 01:05:00,090] [INFO] [celery.beat] Scheduler: Sending due task Train the classifier (documents.tasks.train_classifier)
2023-03-21 01:10:00 [2023-03-21 01:10:00,091] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
2023-03-21 01:20:00 [2023-03-21 01:20:00,059] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
2023-03-21 01:30:00 [2023-03-21 01:30:00,071] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
2023-03-21 01:40:00 [2023-03-21 01:40:00,091] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
2023-03-21 01:50:00 [2023-03-21 01:50:00,071] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
2023-03-21 02:00:00 [2023-03-21 02:00:00,067] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
2023-03-21 02:05:00 [2023-03-21 02:05:00,094] [INFO] [celery.beat] Scheduler: Sending due task Train the classifier (documents.tasks.train_classifier)
2023-03-21 02:10:00 [2023-03-21 02:10:00,056] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
2023-03-21 02:20:00 [2023-03-21 02:20:00,088] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
2023-03-21 02:30:00 [2023-03-21 02:30:00,074] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
2023-03-21 02:40:00 [2023-03-21 02:40:00,091] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
2023-03-21 02:50:00 [2023-03-21 02:50:00,076] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
2023-03-21 03:00:00 [2023-03-21 03:00:00,083] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)







2023-03-21 12:35:35 [2023-03-21 12:35:35,617] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[b78dc734-2de4-45e5-9421-9ec6b168c222] received
2023-03-21 12:35:35 [2023-03-21 12:35:35,618] [INFO] [celery.worker.request] Discarding revoked task: paperless_mail.tasks.process_mail_accounts[b78dc734-2de4-45e5-9421-9ec6b168c222]
2023-03-21 12:35:35 [2023-03-21 12:35:35,643] [CRITICAL] [celery.worker] Unrecoverable error: InterfaceError('connection already closed')
2023-03-21 12:35:35 Traceback (most recent call last):
2023-03-21 12:35:35   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 301, in _cursor
2023-03-21 12:35:35     return self._prepare_cursor(self.create_cursor(name))
2023-03-21 12:35:35   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
2023-03-21 12:35:35     return func(*args, **kwargs)
2023-03-21 12:35:35   File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 269, in create_cursor
2023-03-21 12:35:35     cursor = self.connection.cursor()
2023-03-21 12:35:35 psycopg2.InterfaceError: connection already closed
2023-03-21 12:35:35 2023-03-21 12:35:35,433 WARN received SIGTERM indicating exit request
2023-03-21 12:35:35 2023-03-21 12:35:35,472 INFO waiting for gunicorn, celery, celery-beat, consumer to die
2023-03-21 12:35:35 
2023-03-21 12:35:35 The above exception was the direct cause of the following exception:
2023-03-21 12:35:35 
2023-03-21 12:35:35 Traceback (most recent call last):
2023-03-21 12:35:35   File "/usr/local/lib/python3.9/site-packages/celery/worker/worker.py", line 203, in start
2023-03-21 12:35:35     self.blueprint.start(self)
2023-03-21 12:35:35   File "/usr/local/lib/python3.9/site-packages/celery/bootsteps.py", line 116, in start
2023-03-21 12:35:35     step.start(parent)
2023-03-21 12:35:35   File "/usr/local/lib/python3.9/site-packages/celery/bootsteps.py", line 365, in start
2023-03-21 12:35:35     return self.obj.start()
2023-03-21 12:35:35   File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 332, in start
2023-03-21 12:35:35     blueprint.start(self)
2023-03-21 12:35:35   File "/usr/local/lib/python3.9/site-packages/celery/bootsteps.py", line 116, in start
2023-03-21 12:35:35     step.start(parent)
2023-03-21 12:35:35   File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 628, in start
2023-03-21 12:35:35     c.loop(*c.loop_args())
2023-03-21 12:35:35   File "/usr/local/lib/python3.9/site-packages/celery/worker/loops.py", line 97, in asynloop
2023-03-21 12:35:35     next(loop)
2023-03-21 12:35:35   File "/usr/local/lib/python3.9/site-packages/kombu/asynchronous/hub.py", line 362, in create_loop
2023-03-21 12:35:35     cb(*cbargs)
2023-03-21 12:35:35   File "/usr/local/lib/python3.9/site-packages/kombu/transport/redis.py", line 1326, in on_readable
2023-03-21 12:35:35     self.cycle.on_readable(fileno)
2023-03-21 12:35:35   File "/usr/local/lib/python3.9/site-packages/kombu/transport/redis.py", line 562, in on_readable
2023-03-21 12:35:35     chan.handlers[type]()
2023-03-21 12:35:35   File "/usr/local/lib/python3.9/site-packages/kombu/transport/redis.py", line 967, in _brpop_read
2023-03-21 12:35:35     self.connection._deliver(loads(bytes_to_str(item)), dest)
2023-03-21 12:35:35   File "/usr/local/lib/python3.9/site-packages/kombu/transport/virtual/base.py", line 991, in _deliver
2023-03-21 12:35:35     callback(message)
2023-03-21 12:35:35   File "/usr/local/lib/python3.9/site-packages/kombu/transport/virtual/base.py", line 624, in _callback
2023-03-21 12:35:35     return callback(message)
2023-03-21 12:35:35   File "/usr/local/lib/python3.9/site-packages/kombu/messaging.py", line 626, in _receive_callback
2023-03-21 12:35:35     return on_m(message) if on_m else self.receive(decoded, message)
2023-03-21 12:35:35   File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 596, in on_task_received
2023-03-21 12:35:35     strategy(
2023-03-21 12:35:35   File "/usr/local/lib/python3.9/site-packages/celery/worker/strategy.py", line 162, in task_message_handler
2023-03-21 12:35:35     if (req.expires or req.id in revoked_tasks) and req.revoked():
2023-03-21 12:35:35   File "/usr/local/lib/python3.9/site-packages/celery/worker/request.py", line 456, in revoked
2023-03-21 12:35:35     self._announce_revoked(
2023-03-21 12:35:35   File "/usr/local/lib/python3.9/site-packages/celery/worker/request.py", line 438, in _announce_revoked
2023-03-21 12:35:35     self.task.backend.mark_as_revoked(
2023-03-21 12:35:35   File "/usr/local/lib/python3.9/site-packages/celery/backends/base.py", line 272, in mark_as_revoked
2023-03-21 12:35:35     self.store_result(task_id, exc, state,
2023-03-21 12:35:35   File "/usr/local/lib/python3.9/site-packages/celery/backends/base.py", line 528, in store_result
2023-03-21 12:35:35     self._store_result(task_id, result, state, traceback,
2023-03-21 12:35:35   File "/usr/local/lib/python3.9/site-packages/django_celery_results/backends/database.py", line 132, in _store_result
2023-03-21 12:35:35     self.TaskModel._default_manager.store_result(**task_props)
2023-03-21 12:35:35   File "/usr/local/lib/python3.9/site-packages/django_celery_results/managers.py", line 43, in _inner
2023-03-21 12:35:35     return fun(*args, **kwargs)
2023-03-21 12:35:35   File "/usr/local/lib/python3.9/site-packages/django_celery_results/managers.py", line 168, in store_result
2023-03-21 12:35:35     obj, created = self.using(using).get_or_create(task_id=task_id,
2023-03-21 12:35:35   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 929, in get_or_create
2023-03-21 12:35:35     return self.get(**kwargs), False
2023-03-21 12:35:35   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 646, in get
2023-03-21 12:35:35     num = len(clone)
2023-03-21 12:35:35   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 376, in __len__
2023-03-21 12:35:35     self._fetch_all()
2023-03-21 12:35:35   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1867, in _fetch_all
2023-03-21 12:35:35     self._result_cache = list(self._iterable_class(self))
2023-03-21 12:35:35   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 87, in __iter__
2023-03-21 12:35:35     results = compiler.execute_sql(
2023-03-21 12:35:35   File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1396, in execute_sql
2023-03-21 12:35:35     cursor = self.connection.cursor()
2023-03-21 12:35:35   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
2023-03-21 12:35:35     return func(*args, **kwargs)
2023-03-21 12:35:35   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 323, in cursor
2023-03-21 12:35:35     return self._cursor()
2023-03-21 12:35:35   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 301, in _cursor
2023-03-21 12:35:35     return self._prepare_cursor(self.create_cursor(name))
2023-03-21 12:35:35   File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
2023-03-21 12:35:35     raise dj_exc_value.with_traceback(traceback) from exc_value
2023-03-21 12:35:35   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 301, in _cursor
2023-03-21 12:35:35     return self._prepare_cursor(self.create_cursor(name))
2023-03-21 12:35:35   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
2023-03-21 12:35:35     return func(*args, **kwargs)
2023-03-21 12:35:35   File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 269, in create_cursor
2023-03-21 12:35:35     cursor = self.connection.cursor()
2023-03-21 12:35:35 django.db.utils.InterfaceError: connection already closed
```

### Paperless-ngx version

1.13.0

### Host OS

macOS Ventura on Intel x64

### Installation method

Docker - official image

**Comment by yaakovfeldman** [comment]
Bizarrely, it has just started checking mail again. Perhaps it just had a large backlog of revoked tasks to complain about??
