### ISSUE TITLE
[BUG] Celery is using 100 % CPU on rPi

### ISSUE THREAD

**Issue by fakerli** [paperless-ngx/paperless-ngx#2953]
### Description

Celery uses 100 % CPU when paperless is idling / doing nothing.

![image](https://user-images.githubusercontent.com/12958497/227713678-584fe536-9a14-4c8f-9bcc-f5d0a7c258ad.png)

### Steps to reproduce

1. docker-compose up -d
2. htop

### Webserver logs

```bash
LocalTime -> 2023-03-25 12:08:14
Configuration ->
    . broker -> redis://broker:6379//
    . loader -> celery.loaders.app.AppLoader
    . scheduler -> celery.beat.PersistentScheduler
    . db -> /usr/src/paperless/data/celerybeat-schedule.db
    . logfile -> [stderr]@%INFO
    . maxinterval -> 5.00 minutes (300s)
2023-03-25 11:08:15,268 WARN exited: celery-beat (exit status 1; not expected)
2023-03-25 11:08:16,278 INFO spawned: 'celery-beat' with pid 1448
2023-03-25 11:08:17,283 INFO success: celery-beat entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[2023-03-25 12:08:25,347] [INFO] [celery.beat] beat: Starting...
[2023-03-25 12:08:25,396] [CRITICAL] [celery.beat] beat raised exception <class '_gdbm.error'>: error('Database needs recovery')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/shelve.py", line 111, in __getitem__
    value = self.cache[key]
KeyError: 'entries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/beat.py", line 572, in _create_schedule
    self._store['entries']
  File "/usr/local/lib/python3.9/shelve.py", line 113, in __getitem__
    f = BytesIO(self.dict[key.encode(self.keyencoding)])
KeyError: b'entries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/apps/beat.py", line 105, in start_scheduler
    service.start()
  File "/usr/local/lib/python3.9/site-packages/celery/beat.py", line 636, in start
    humanize_seconds(self.scheduler.max_interval))
  File "/usr/local/lib/python3.9/site-packages/kombu/utils/objects.py", line 30, in __get__
    return super().__get__(instance, owner)
  File "/usr/local/lib/python3.9/functools.py", line 993, in __get__
    val = self.func(instance)
  File "/usr/local/lib/python3.9/site-packages/celery/beat.py", line 679, in scheduler
    return self.get_scheduler()
  File "/usr/local/lib/python3.9/site-packages/celery/beat.py", line 670, in get_scheduler
    return symbol_by_name(self.scheduler_cls, aliases=aliases)(
  File "/usr/local/lib/python3.9/site-packages/celery/beat.py", line 515, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/beat.py", line 271, in __init__
    self.setup_schedule()
  File "/usr/local/lib/python3.9/site-packages/celery/beat.py", line 543, in setup_schedule
    self._create_schedule()
  File "/usr/local/lib/python3.9/site-packages/celery/beat.py", line 576, in _create_schedule
    self._store['entries'] = {}
  File "/usr/local/lib/python3.9/shelve.py", line 125, in __setitem__
    self.dict[key.encode(self.keyencoding)] = f.getvalue()
_gdbm.error: Database needs recovery
[2023-03-25 12:08:25,403] [WARNING] [celery.redirected] Traceback (most recent call last):
[2023-03-25 12:08:25,404] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/shelve.py", line 111, in __getitem__
[2023-03-25 12:08:25,405] [WARNING] [celery.redirected]
[2023-03-25 12:08:25,406] [WARNING] [celery.redirected] value = self.cache[key]
[2023-03-25 12:08:25,407] [WARNING] [celery.redirected] KeyError
[2023-03-25 12:08:25,408] [WARNING] [celery.redirected] :
[2023-03-25 12:08:25,408] [WARNING] [celery.redirected] 'entries'
[2023-03-25 12:08:25,409] [WARNING] [celery.redirected]
During handling of the above exception, another exception occurred:
[2023-03-25 12:08:25,410] [WARNING] [celery.redirected] Traceback (most recent call last):
[2023-03-25 12:08:25,411] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/site-packages/celery/beat.py", line 572, in _create_schedule
[2023-03-25 12:08:25,416] [WARNING] [celery.redirected]
[2023-03-25 12:08:25,417] [WARNING] [celery.redirected] self._store['entries']
[2023-03-25 12:08:25,418] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/shelve.py", line 113, in __getitem__
[2023-03-25 12:08:25,420] [WARNING] [celery.redirected]
[2023-03-25 12:08:25,421] [WARNING] [celery.redirected] f = BytesIO(self.dict[key.encode(self.keyencoding)])
[2023-03-25 12:08:25,422] [WARNING] [celery.redirected] KeyError
[2023-03-25 12:08:25,423] [WARNING] [celery.redirected] :
[2023-03-25 12:08:25,423] [WARNING] [celery.redirected] b'entries'
[2023-03-25 12:08:25,424] [WARNING] [celery.redirected]
During handling of the above exception, another exception occurred:
[2023-03-25 12:08:25,425] [WARNING] [celery.redirected] Traceback (most recent call last):
[2023-03-25 12:08:25,426] [WARNING] [celery.redirected]   File "/usr/local/bin/celery", line 8, in <module>
[2023-03-25 12:08:25,427] [WARNING] [celery.redirected]
[2023-03-25 12:08:25,428] [WARNING] [celery.redirected] sys.exit(main())
[2023-03-25 12:08:25,429] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/site-packages/celery/__main__.py", line 15, in main
[2023-03-25 12:08:25,431] [WARNING] [celery.redirected]
[2023-03-25 12:08:25,432] [WARNING] [celery.redirected] sys.exit(_main())
[2023-03-25 12:08:25,433] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/site-packages/celery/bin/celery.py", line 217, in main
[2023-03-25 12:08:25,435] [WARNING] [celery.redirected]
[2023-03-25 12:08:25,436] [WARNING] [celery.redirected] return celery(auto_envvar_prefix="CELERY")
[2023-03-25 12:08:25,437] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
[2023-03-25 12:08:25,441] [WARNING] [celery.redirected]
[2023-03-25 12:08:25,443] [WARNING] [celery.redirected] return self.main(*args, **kwargs)
[2023-03-25 12:08:25,445] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
[2023-03-25 12:08:25,448] [WARNING] [celery.redirected]
[2023-03-25 12:08:25,450] [WARNING] [celery.redirected] rv = self.invoke(ctx)
[2023-03-25 12:08:25,452] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
[2023-03-25 12:08:25,457] [WARNING] [celery.redirected]
[2023-03-25 12:08:25,458] [WARNING] [celery.redirected] return _process_result(sub_ctx.command.invoke(sub_ctx))
[2023-03-25 12:08:25,460] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
[2023-03-25 12:08:25,465] [WARNING] [celery.redirected]
[2023-03-25 12:08:25,466] [WARNING] [celery.redirected] return ctx.invoke(self.callback, **ctx.params)
[2023-03-25 12:08:25,468] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
[2023-03-25 12:08:25,472] [WARNING] [celery.redirected]
[2023-03-25 12:08:25,474] [WARNING] [celery.redirected] return __callback(*args, **kwargs)
[2023-03-25 12:08:25,475] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
[2023-03-25 12:08:25,478] [WARNING] [celery.redirected]
[2023-03-25 12:08:25,480] [WARNING] [celery.redirected] return f(get_current_context(), *args, **kwargs)
[2023-03-25 12:08:25,482] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/site-packages/celery/bin/base.py", line 134, in caller
[2023-03-25 12:08:25,484] [WARNING] [celery.redirected]
[2023-03-25 12:08:25,486] [WARNING] [celery.redirected] return f(ctx, *args, **kwargs)
[2023-03-25 12:08:25,488] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/site-packages/celery/bin/beat.py", line 72, in beat
[2023-03-25 12:08:25,490] [WARNING] [celery.redirected]
[2023-03-25 12:08:25,492] [WARNING] [celery.redirected] return beat().run()
[2023-03-25 12:08:25,494] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/site-packages/celery/apps/beat.py", line 77, in run
[2023-03-25 12:08:25,496] [WARNING] [celery.redirected]
[2023-03-25 12:08:25,498] [WARNING] [celery.redirected] self.start_scheduler()
[2023-03-25 12:08:25,500] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/site-packages/celery/apps/beat.py", line 105, in start_scheduler
[2023-03-25 12:08:25,502] [WARNING] [celery.redirected]
[2023-03-25 12:08:25,504] [WARNING] [celery.redirected] service.start()
[2023-03-25 12:08:25,506] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/site-packages/celery/beat.py", line 636, in start
[2023-03-25 12:08:25,509] [WARNING] [celery.redirected]
[2023-03-25 12:08:25,511] [WARNING] [celery.redirected] humanize_seconds(self.scheduler.max_interval))
[2023-03-25 12:08:25,513] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/site-packages/kombu/utils/objects.py", line 30, in __get__
[2023-03-25 12:08:25,515] [WARNING] [celery.redirected]
[2023-03-25 12:08:25,517] [WARNING] [celery.redirected] return super().__get__(instance, owner)
[2023-03-25 12:08:25,519] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/functools.py", line 993, in __get__
[2023-03-25 12:08:25,523] [WARNING] [celery.redirected]
[2023-03-25 12:08:25,525] [WARNING] [celery.redirected] val = self.func(instance)
[2023-03-25 12:08:25,526] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/site-packages/celery/beat.py", line 679, in scheduler
[2023-03-25 12:08:25,530] [WARNING] [celery.redirected]
[2023-03-25 12:08:25,531] [WARNING] [celery.redirected] return self.get_scheduler()
[2023-03-25 12:08:25,533] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/site-packages/celery/beat.py", line 670, in get_scheduler
[2023-03-25 12:08:25,537] [WARNING] [celery.redirected]
[2023-03-25 12:08:25,538] [WARNING] [celery.redirected] return symbol_by_name(self.scheduler_cls, aliases=aliases)(
[2023-03-25 12:08:25,540] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/site-packages/celery/beat.py", line 515, in __init__
[2023-03-25 12:08:25,543] [WARNING] [celery.redirected]
[2023-03-25 12:08:25,545] [WARNING] [celery.redirected] super().__init__(*args, **kwargs)
[2023-03-25 12:08:25,547] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/site-packages/celery/beat.py", line 271, in __init__
[2023-03-25 12:08:25,550] [WARNING] [celery.redirected]
[2023-03-25 12:08:25,551] [WARNING] [celery.redirected] self.setup_schedule()
[2023-03-25 12:08:25,553] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/site-packages/celery/beat.py", line 543, in setup_schedule
[2023-03-25 12:08:25,556] [WARNING] [celery.redirected]
[2023-03-25 12:08:25,558] [WARNING] [celery.redirected] self._create_schedule()
[2023-03-25 12:08:25,560] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/site-packages/celery/beat.py", line 576, in _create_schedule
[2023-03-25 12:08:25,563] [WARNING] [celery.redirected]
[2023-03-25 12:08:25,565] [WARNING] [celery.redirected] self._store['entries'] = {}
[2023-03-25 12:08:25,567] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/shelve.py", line 125, in __setitem__
[2023-03-25 12:08:25,569] [WARNING] [celery.redirected]
[2023-03-25 12:08:25,571] [WARNING] [celery.redirected] self.dict[key.encode(self.keyencoding)] = f.getvalue()
[2023-03-25 12:08:25,573] [WARNING] [celery.redirected] _gdbm
[2023-03-25 12:08:25,575] [WARNING] [celery.redirected] .
[2023-03-25 12:08:25,577] [WARNING] [celery.redirected] error
[2023-03-25 12:08:25,579] [WARNING] [celery.redirected] :
[2023-03-25 12:08:25,580] [WARNING] [celery.redirected] Database needs recovery
[2023-03-25 12:08:25,803] [WARNING] [celery.redirected] Exception ignored in:
[2023-03-25 12:08:25,805] [WARNING] [celery.redirected] <function Shelf.__del__ at 0x758a1a90>
[2023-03-25 12:08:25,806] [WARNING] [celery.redirected] Traceback (most recent call last):
[2023-03-25 12:08:25,807] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/shelve.py", line 162, in __del__
[2023-03-25 12:08:25,808] [WARNING] [celery.redirected]
[2023-03-25 12:08:25,808] [WARNING] [celery.redirected] self.close()
[2023-03-25 12:08:25,809] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/shelve.py", line 144, in close
[2023-03-25 12:08:25,810] [WARNING] [celery.redirected]
[2023-03-25 12:08:25,811] [WARNING] [celery.redirected] self.sync()
[2023-03-25 12:08:25,811] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/shelve.py", line 168, in sync
[2023-03-25 12:08:25,812] [WARNING] [celery.redirected]
[2023-03-25 12:08:25,814] [WARNING] [celery.redirected] self[key] = entry
[2023-03-25 12:08:25,816] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/shelve.py", line 125, in __setitem__
[2023-03-25 12:08:25,819] [WARNING] [celery.redirected]
[2023-03-25 12:08:25,820] [WARNING] [celery.redirected] self.dict[key.encode(self.keyencoding)] = f.getvalue()
[2023-03-25 12:08:25,821] [WARNING] [celery.redirected] _gdbm
[2023-03-25 12:08:25,821] [WARNING] [celery.redirected] .
[2023-03-25 12:08:25,822] [WARNING] [celery.redirected] error
[2023-03-25 12:08:25,824] [WARNING] [celery.redirected] :
[2023-03-25 12:08:25,825] [WARNING] [celery.redirected] Database needs recovery
celery beat v5.2.7 (dawn-chorus) is starting.
__    -    ... __   -        _
LocalTime -> 2023-03-25 12:08:25
Configuration ->
    . broker -> redis://broker:6379//
    . loader -> celery.loaders.app.AppLoader
    . scheduler -> celery.beat.PersistentScheduler
    . db -> /usr/src/paperless/data/celerybeat-schedule.db
    . logfile -> [stderr]@%INFO
    . maxinterval -> 5.00 minutes (300s)
2023-03-25 11:08:26,626 WARN exited: celery-beat (exit status 1; not expected)
2023-03-25 11:08:27,637 INFO spawned: 'celery-beat' with pid 1484
2023-03-25 11:08:28,642 INFO success: celery-beat entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[2023-03-25 12:08:36,503] [INFO] [celery.beat] beat: Starting...
```

### Paperless-ngx version

1.13.0

### Host OS

Raspberry Pi 3b / raspbian

### Installation method

Docker - official image

**Comment by fakerli** [comment]
Update from containerd.io:armhf 1.6.18-1 to containerd.io:armhf 1.6.19-1 solved the problem for me.
