### ISSUE TITLE
[BUG] Unable to import PDF, TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by deviantintegral** [paperless-ngx/paperless-ngx#3010]
### Description

I have a PDF file that Paperless is unable to import.

[ad50gusb-manual (Whirlpool dehumidifier).pdf](https://github.com/paperless-ngx/paperless-ngx/files/11138166/ad50gusb-manual.Whirlpool.dehumidifier.pdf)

### Steps to reproduce

1. Try to upload the above file via a consume directory or the web UI.
2. See the following exception logged.

### Webserver logs

```bash
paperless-paperless-webserver-1  | [2023-04-03 08:14:33,218] [INFO] [celery.worker.strategy] Task documents.tasks.consume_file[ee97f0eb-f771-4c3c-848c-f23f7b3c907c] received
paperless-paperless-webserver-1  | [2023-04-03 08:14:33,280] [INFO] [paperless.consumer] Consuming ad50gusb-manual (Whirlpool dehumidifier).pdf
paperless-paperless-webserver-1  | [2023-04-03 08:14:35,628] [ERROR] [paperless.consumer] Error while consuming document ad50gusb-manual (Whirlpool dehumidifier).pdf: TypeError: 'NoneType' object is not subscriptable
paperless-paperless-webserver-1  | Traceback (most recent call last):
paperless-paperless-webserver-1  |   File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 321, in parse
paperless-paperless-webserver-1  |     ocrmypdf.ocr(**args)
paperless-paperless-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/api.py", line 332, in ocr
paperless-paperless-webserver-1  |     return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)
paperless-paperless-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 378, in run_pipeline
paperless-paperless-webserver-1  |     pdfinfo = get_pdfinfo(
paperless-paperless-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 165, in get_pdfinfo
paperless-paperless-webserver-1  |     return PdfInfo(
paperless-paperless-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 932, in __init__
paperless-paperless-webserver-1  |     self._pages = _pdf_pageinfo_concurrent(
paperless-paperless-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 709, in _pdf_pageinfo_concurrent
paperless-paperless-webserver-1  |     executor(
paperless-paperless-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_concurrent.py", line 87, in __call__
paperless-paperless-webserver-1  |     self._execute(
paperless-paperless-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/builtin_plugins/concurrency.py", line 141, in _execute
paperless-paperless-webserver-1  |     result = future.result()
paperless-paperless-webserver-1  |   File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result
paperless-paperless-webserver-1  |     return self.__get_result()
paperless-paperless-webserver-1  |   File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
paperless-paperless-webserver-1  |     raise self._exception
paperless-paperless-webserver-1  |   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
paperless-paperless-webserver-1  |     result = self.fn(*self.args, **self.kwargs)
paperless-paperless-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 666, in _pdf_pageinfo_sync
paperless-paperless-webserver-1  |     page = PageInfo(pdf, pageno, infile, check_pages, detailed_analysis)
paperless-paperless-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 746, in __init__
paperless-paperless-webserver-1  |     self._gather_pageinfo(pdf, pageno, infile, check_pages, detailed_analysis)
paperless-paperless-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 792, in _gather_pageinfo
paperless-paperless-webserver-1  |     for info in _process_content_streams(
paperless-paperless-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 594, in _process_content_streams
paperless-paperless-webserver-1  |     yield from _find_form_xobject_images(pdf, container, contentsinfo)
paperless-paperless-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 528, in _find_form_xobject_images
paperless-paperless-webserver-1  |     if candidate['/Subtype'] != '/Form':
paperless-paperless-webserver-1  | TypeError: 'NoneType' object is not subscriptable
paperless-paperless-webserver-1  |
paperless-paperless-webserver-1  | The above exception was the direct cause of the following exception:
paperless-paperless-webserver-1  |
paperless-paperless-webserver-1  | Traceback (most recent call last):
paperless-paperless-webserver-1  |   File "/usr/src/paperless/src/documents/consumer.py", line 385, in try_consume_file
paperless-paperless-webserver-1  |     document_parser.parse(self.path, mime_type, self.filename)
paperless-paperless-webserver-1  |   File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 379, in parse
paperless-paperless-webserver-1  |     raise ParseError(f"{e.__class__.__name__}: {str(e)}") from e
paperless-paperless-webserver-1  | documents.parsers.ParseError: TypeError: 'NoneType' object is not subscriptable
paperless-paperless-webserver-1  | [2023-04-03 08:14:35,643] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[ee97f0eb-f771-4c3c-848c-f23f7b3c907c] raised unexpected: ConsumerError("ad50gusb-manual (Whirlpool dehumidifier).pdf: Error while consuming document ad50gusb-manual (Whirlpool dehumidifier).pdf: TypeError: 'NoneType' object is not subscriptable")
paperless-paperless-webserver-1  | Traceback (most recent call last):
paperless-paperless-webserver-1  |   File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 321, in parse
paperless-paperless-webserver-1  |     ocrmypdf.ocr(**args)
paperless-paperless-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/api.py", line 332, in ocr
paperless-paperless-webserver-1  |     return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)
paperless-paperless-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 378, in run_pipeline
paperless-paperless-webserver-1  |     pdfinfo = get_pdfinfo(
paperless-paperless-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 165, in get_pdfinfo
paperless-paperless-webserver-1  |     return PdfInfo(
paperless-paperless-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 932, in __init__
paperless-paperless-webserver-1  |     self._pages = _pdf_pageinfo_concurrent(
paperless-paperless-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 709, in _pdf_pageinfo_concurrent
paperless-paperless-webserver-1  |     executor(
paperless-paperless-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_concurrent.py", line 87, in __call__
paperless-paperless-webserver-1  |     self._execute(
paperless-paperless-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/builtin_plugins/concurrency.py", line 141, in _execute
paperless-paperless-webserver-1  |     result = future.result()
paperless-paperless-webserver-1  |   File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result
paperless-paperless-webserver-1  |     return self.__get_result()
paperless-paperless-webserver-1  |   File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
paperless-paperless-webserver-1  |     raise self._exception
paperless-paperless-webserver-1  |   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
paperless-paperless-webserver-1  |     result = self.fn(*self.args, **self.kwargs)
paperless-paperless-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 666, in _pdf_pageinfo_sync
paperless-paperless-webserver-1  |     page = PageInfo(pdf, pageno, infile, check_pages, detailed_analysis)
paperless-paperless-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 746, in __init__
paperless-paperless-webserver-1  |     self._gather_pageinfo(pdf, pageno, infile, check_pages, detailed_analysis)
paperless-paperless-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 792, in _gather_pageinfo
paperless-paperless-webserver-1  |     for info in _process_content_streams(
paperless-paperless-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 594, in _process_content_streams
paperless-paperless-webserver-1  |     yield from _find_form_xobject_images(pdf, container, contentsinfo)
paperless-paperless-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 528, in _find_form_xobject_images
paperless-paperless-webserver-1  |     if candidate['/Subtype'] != '/Form':
paperless-paperless-webserver-1  | TypeError: 'NoneType' object is not subscriptable
paperless-paperless-webserver-1  |
paperless-paperless-webserver-1  | The above exception was the direct cause of the following exception:
paperless-paperless-webserver-1  |
paperless-paperless-webserver-1  | Traceback (most recent call last):
paperless-paperless-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 302, in main_wrap
paperless-paperless-webserver-1  |     raise exc_info[1]
paperless-paperless-webserver-1  |   File "/usr/src/paperless/src/documents/consumer.py", line 385, in try_consume_file
paperless-paperless-webserver-1  |     document_parser.parse(self.path, mime_type, self.filename)
paperless-paperless-webserver-1  |   File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 379, in parse
paperless-paperless-webserver-1  |     raise ParseError(f"{e.__class__.__name__}: {str(e)}") from e
paperless-paperless-webserver-1  | documents.parsers.ParseError: TypeError: 'NoneType' object is not subscriptable
paperless-paperless-webserver-1  |
paperless-paperless-webserver-1  | The above exception was the direct cause of the following exception:
paperless-paperless-webserver-1  |
paperless-paperless-webserver-1  | Traceback (most recent call last):
paperless-paperless-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
paperless-paperless-webserver-1  |     R = retval = fun(*args, **kwargs)
paperless-paperless-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
paperless-paperless-webserver-1  |     return self.run(*args, **kwargs)
paperless-paperless-webserver-1  |   File "/usr/src/paperless/src/documents/tasks.py", line 199, in consume_file
paperless-paperless-webserver-1  |     document = Consumer().try_consume_file(
paperless-paperless-webserver-1  |   File "/usr/src/paperless/src/documents/consumer.py", line 405, in try_consume_file
paperless-paperless-webserver-1  |     self._fail(
paperless-paperless-webserver-1  |   File "/usr/src/paperless/src/documents/consumer.py", line 96, in _fail
paperless-paperless-webserver-1  |     raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
paperless-paperless-webserver-1  | documents.consumer.ConsumerError: ad50gusb-manual (Whirlpool dehumidifier).pdf: Error while consuming document ad50gusb-manual (Whirlpool dehumidifier).pdf: TypeError: 'NoneType' object is not subscriptable
```

### Paperless-ngx version

1.13.0

### Host OS

Ubuntu 20.04 amd64

### Installation method

Docker - official image

### Configuration changes

I renamed the paperless service to avoid a DNS conflict

**Comment by deviantintegral** [comment]
```
paperless-paperless-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 528, in _find_form_xobject_images
paperless-paperless-webserver-1  |     if candidate['/Subtype'] != '/Form':
paperless-paperless-webserver-1  | TypeError: 'NoneType' object is not subscriptable
```

I'm guessing this is fixed by https://github.com/ocrmypdf/OCRmyPDF/pull/1066 which is in the v14.0.4 release: https://ocrmypdf.readthedocs.io/en/latest/release_notes.html

`main` is still locked to 14.0.2: https://github.com/paperless-ngx/paperless-ngx/blob/main/Pipfile.lock#L949-L955

Ah! But the beta PR that's open has the upgrade: https://github.com/paperless-ngx/paperless-ngx/pull/2997

I'm a first-time user, so it's no big deal for me to switch to the beta right now. Can someone mark this as confirmed, and then close it?
