### ISSUE TITLE
[BUG] Document completely gone after import

### ISSUE THREAD

**Issue by psla** [paperless-ngx/paperless-ngx#3077]
### Description

Repro steps (the bug doesn't really repro):

1. Add document to the consume folder
2. Document is consumed (disappeared from the folder)

Expect: document show up in paperless-ngx / can be found
Actual behavior: transient (?) sql issue - document is gone. Nowhere to be found

I don't know why `MySQL server has gone away`, but I would ask to consider the following behavior: if the file is removed from the 'consume' folder, then it is successfully consumed. If the document failed to be consumed, then it should not disappear from the 'consume' folder

### Steps to reproduce

1. Add document to the consume folder
2. Document is consumed (disappeared from the folder)

### Webserver logs

```bash
[2023-04-11 16:03:00,333] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/CCF_000011.pdf to the task queue.

[2023-04-11 16:03:00,335] [ERROR] [paperless.handlers] Creating PaperlessTask failed: (2006, 'MySQL server has gone away')

Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute

    return self.cursor.execute(sql, params)

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute

    return self.cursor.execute(query, args)

  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute

    res = self._query(query)

  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query

    db.query(q)

  File "/usr/local/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query

    _mysql.connection.query(self, query)

MySQLdb.OperationalError: (2006, 'MySQL server has gone away')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/signals/handlers.py", line 548, in before_task_publish_handler

    PaperlessTask.objects.create(

  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method

    return getattr(self.get_queryset(), name)(*args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 671, in create

    obj.save(force_insert=True, using=self.db)

  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 812, in save

    self.save_base(

  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 863, in save_base

    updated = self._save_table(

  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 1006, in _save_table

    results = self._do_insert(

  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 1047, in _do_insert

    return manager._insert(

  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method

    return getattr(self.get_queryset(), name)(*args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1791, in _insert

    return query.get_compiler(using=using).execute_sql(returning_fields)

  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1660, in execute_sql

    cursor.execute(sql, params)

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute

    return self._execute_with_wrappers(

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers

    return executor(sql, params, many, context)

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute

    return self.cursor.execute(sql, params)

  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__

    raise dj_exc_value.with_traceback(traceback) from exc_value

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute

    return self.cursor.execute(sql, params)

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute

    return self.cursor.execute(query, args)

  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute

    res = self._query(query)

  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query

    db.query(q)

  File "/usr/local/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query

    _mysql.connection.query(self, query)

django.db.utils.OperationalError: (2006, 'MySQL server has gone away')

[2023-04-11 16:03:00,431] [INFO] [paperless.consumer] Consuming CCF_000011.pdf

[2023-04-11 16:03:00,743] [DEBUG] [paperless.consumer] Detected mime type: application/pdf

[2023-04-11 16:03:00,752] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser

[2023-04-11 16:03:00,758] [DEBUG] [paperless.consumer] Parsing CCF_000011.pdf...

[2023-04-11 16:03:01,422] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-ngx553b8743/CCF_000011.pdf'), 'output_file': PosixPath('/tmp/paperless/paperless-ouagukqo/archive.pdf'), 'use_threads': True, 'jobs': 4, 'language': 'eng', 'output_type': 'pdfa', 'progress_bar': False, 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-ouagukqo/sidecar.txt')}

[2023-04-11 16:03:18,100] [DEBUG] [paperless.parsing.tesseract] Using text from sidecar file

[2023-04-11 16:03:18,101] [DEBUG] [paperless.consumer] Generating thumbnail for CCF_000011.pdf...

[2023-04-11 16:03:18,105] [DEBUG] [paperless.parsing] Execute: convert -density 300 -scale 500x5000> -alpha remove -strip -auto-orient /tmp/paperless/paperless-ouagukqo/archive.pdf[0] /tmp/paperless/paperless-ouagukqo/convert.webp

[2023-04-11 16:03:20,616] [DEBUG] [paperless.consumer] Saving record to database

[2023-04-11 16:03:20,616] [DEBUG] [paperless.consumer] Creation date from parse_date: 1976-04-11 00:00:00-08:00

[2023-04-11 16:03:20,950] [DEBUG] [paperless.consumer] Deleting file /tmp/paperless/paperless-ngx553b8743/CCF_000011.pdf

[2023-04-11 16:03:20,952] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-ouagukqo

[2023-04-11 16:03:20,982] [INFO] [paperless.consumer] Document 1976-04-11 CCF_000011 consumption finished

[2023-04-11 16:06:01,484] [DEBUG] [paperless.classifier] Gathering data from database...

[2023-04-11 16:06:02,243] [DEBUG] [paperless.tasks] Training data unchanged.
```

### Browser logs

```bash
not applicable, I guess
```

### Paperless-ngx version

Paperless-ngx 1.13.0

### Host OS

Debian with Docker

### Installation method

Docker - official image

### Browser

n/a (Chrome)

### Configuration changes

Not using mysql from the docker. MariaDB is hosted on the host (outside of docker).

**Comment by psla** [comment]
Actually. User error I guess... The document was imported.  It was imported with "1976" date. Sorry about that.

```
1976-04-11
```
