### ISSUE TITLE
[BUG] If barcode ASNs are a duplicate, the import fails instead of not setting the ASN

### ISSUE THREAD

**Issue by zimjjan** [paperless-ngx/paperless-ngx#3082]
### Description

If multiple documents with the same ASN are imported and ASN is set via barcode, for duplicates, an error is thrown instead of a warning as mentioned here [1].

[1] https://docs.paperless-ngx.com/configuration/#barcodes

### Steps to reproduce

Import document with same ASN barcode twice.

### Webserver logs

```bash
[2023-04-12 10:37:19,854] [ERROR] [paperless.consumer] The following error occurred while consuming test2.pdf: UNIQUE constraint failed: documents_document.archive_serial_number

Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute

    return self.cursor.execute(sql, params)

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute

    return Database.Cursor.execute(self, query, params)

sqlite3.IntegrityError: UNIQUE constraint failed: documents_document.archive_serial_number

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/consumer.py", line 427, in try_consume_file

    document = self._store(text=text, date=date, mime_type=mime_type)

  File "/usr/src/paperless/src/documents/consumer.py", line 561, in _store

    document.save()

  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 812, in save

    self.save_base(

  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 863, in save_base

    updated = self._save_table(

  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 976, in _save_table

    updated = self._do_update(

  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 1040, in _do_update

    return filtered._update(values) > 0

  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1216, in _update

    return query.get_compiler(self.db).execute_sql(CURSOR)

  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql

    cursor = super().execute_sql(result_type)

  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1398, in execute_sql

    cursor.execute(sql, params)

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute

    return self._execute_with_wrappers(

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers

    return executor(sql, params, many, context)

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute

    return self.cursor.execute(sql, params)

  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__

    raise dj_exc_value.with_traceback(traceback) from exc_value

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute

    return self.cursor.execute(sql, params)

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute

    return Database.Cursor.execute(self, query, params)

django.db.utils.IntegrityError: UNIQUE constraint failed: documents_document.archive_serial_number
```

### Paperless-ngx version

1.13.0

### Host OS

docker

### Installation method

Docker - official image

**Comment by stumpylog** [comment]
An error is expected, if you're importing the same document multiple times at once.  It's a little bit the nature of multiple processes.  

Some additional checks could be added, but it would always run the risk of a race condition I think.

**Comment by zimjjan** [comment]
The documentation says that a warning is logged and the document is just not assigned the duplicate ASN, which simply is not, what actually happens. 

If you think about it, this behavior makes more sense, as you might not be able to remove a ASN sticker from the original paper copy anymore. 

The other option could be to make this behavior configurable.

**Comment by shamoon** [comment]
I don't really use this feature personally but looking into this I think its the documentation thats correct (I think the PR initially worked that way but perhaps the documentation wasn't changed), see https://github.com/paperless-ngx/paperless-ngx/pull/2437/commits/fe4026427514b553d34ef1144670b60a3392574a

I'll update the docs, please feel free to make a FR for this though.

**Comment by shamoon** [comment]
(sorry *incorrect)
