### ISSUE TITLE
[BUG] gotenberg:latest throwing http 404 converting .eml file

### ISSUE THREAD

**Issue by roadrunnerjb** [paperless-ngx/paperless-ngx#3118]
### Description

I have an issue converting mails (.eml) to pdf similar to #2285 running a fresh setup docker container with paperless.

Attachements get converted but not the mail body.
 
.odt and .ods files dropped to the webui are converted without error.

The only difference I found in docker-compose.yml was my file uses gotenberg:latest while current version here in the repo uses gotenberg:7.8. I tried using 7.8 but same behaviour.

`[2023-04-17 13:15:35,427] [ERROR] [paperless.consumer] Error while consuming document Fwd RE23-25621 +25620.eml: Error while converting document to PDF: 404 Client Error: Not Found for url: http://gotenberg:3000/forms/chromium/convert/html`

Any Idea on how to proceed or make more tests ?

### Steps to reproduce

- copy mail with attachemnt to configured folder
- Paperless consumes the mail
- extracts attachements and handles them
- but for .eml thows the errror wich is statte in the task queue

same if I store the mail as .eml file and do drag & drop to webui...

### Webserver logs

```bash
[2023-04-17 13:15:35,427] [ERROR] [paperless.consumer] Error while consuming document Fwd RE23-25621 +25620.eml: Error while converting document to PDF: 404 Client Error: Not Found for url: http://gotenberg:3000/forms/chromium/convert/html
Traceback (most recent call last):
  File "/usr/src/paperless/src/paperless_mail/parsers.py", line 291, in generate_pdf_from_mail
    response.raise_for_status()  # ensure we notice bad responses
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://gotenberg:3000/forms/chromium/convert/html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/consumer.py", line 385, in try_consume_file
    document_parser.parse(self.path, mime_type, self.filename)
  File "/usr/src/paperless/src/paperless_mail/parsers.py", line 145, in parse
    self.archive_path = self.generate_pdf(document_path)
  File "/usr/src/paperless/src/paperless_mail/parsers.py", line 168, in generate_pdf
    pdf_collection.append(("1_mail.pdf", self.generate_pdf_from_mail(mail)))
  File "/usr/src/paperless/src/paperless_mail/parsers.py", line 293, in generate_pdf_from_mail
    raise ParseError(f"Error while converting document to PDF: {err}")
documents.parsers.ParseError: Error while converting document to PDF: 404 Client Error: Not Found for url: http://gotenberg:3000/forms/chromium/convert/html
```

### Browser logs

```bash
n.a.
```

### Paperless-ngx version

1.13.0

### Host OS

debain 11 lxc container with docker 

### Installation method

Docker - official image

### Browser

chrome

### Configuration changes

settings for pre and post consume

**Comment by stumpylog** [comment]
For starters, I would make sure you have the container running with the correct command:
https://github.com/paperless-ngx/paperless-ngx/blob/edf4f98d41574192c4ab9fb45c8908647296b2a8/docker/compose/docker-compose.postgres-tika.yml#L79-L88
