### ISSUE TITLE
[BUG] 503 Server Error: Service Unavailable for url: http://gotenberg:3000/forms/libreoffice/convert

### ISSUE THREAD

**Issue by mdangst** [paperless-ngx/paperless-ngx#3181]
### Description

Upload of MS Word document failed (.docx).
Error message: 503 Server Error: Service Unavailable for url: http://gotenberg:3000/forms/libreoffice/convert
This error exists since Paperless-ngx was updated to version 1.13.0.

I did an research in depth and tried almost all the hint tips received so far but nothing fixed the issue. So it appears that the issue has something to do with paperless-ngx version 1.13.0 and up.

### Steps to reproduce

1. Drag and drop the applicable MS Word document to the new document upload pan.
2. Paperless started with the upload processs
3. After a while the error message (see above) was triggered

### Webserver logs

```bash
[2023-04-25 20:05:07,172] [DEBUG] [paperless.classifier] Gathering data from database...

[2023-04-25 20:05:12,815] [DEBUG] [paperless.tasks] Training data unchanged.

[2023-04-25 20:24:15,786] [INFO] [paperless.consumer] Consuming Disposition.docx

[2023-04-25 20:24:15,879] [DEBUG] [paperless.consumer] Detected mime type: application/vnd.openxmlformats-officedocument.wordprocessingml.document

[2023-04-25 20:24:16,784] [DEBUG] [paperless.consumer] Parser: TikaDocumentParser

[2023-04-25 20:24:16,789] [DEBUG] [paperless.consumer] Parsing Disposition.docx...

[2023-04-25 20:24:16,789] [INFO] [paperless.parsing.tika] Sending /tmp/paperless/paperless-ngxwxz0wf4f/Disposition.docx to Tika server

[2023-04-25 20:24:51,921] [WARNING] [paperless.parsing.tika] Unable to extract date for document /tmp/paperless/paperless-ngxwxz0wf4f/Disposition.docx: 'Creation-Date'

[2023-04-25 20:24:51,973] [INFO] [paperless.parsing.tika] Converting /tmp/paperless/paperless-ngxwxz0wf4f/Disposition.docx to PDF as /tmp/paperless/paperless-dugg6bef/convert.pdf

[2023-04-25 20:25:03,144] [DEBUG] [paperless.parsing.tika] Deleting directory /tmp/paperless/paperless-dugg6bef

[2023-04-25 20:25:04,962] [ERROR] [paperless.consumer] Error while consuming document Disposition.docx: Error while converting document to PDF: 503 Server Error: Service Unavailable for url: http://gotenberg:3000/forms/libreoffice/convert

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_tika/parsers.py", line 111, in convert_to_pdf

    response.raise_for_status()  # ensure we notice bad responses

  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status

    raise HTTPError(http_error_msg, response=self)

requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://gotenberg:3000/forms/libreoffice/convert

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/consumer.py", line 389, in try_consume_file

    document_parser.parse(self.path, mime_type, self.filename)

  File "/usr/src/paperless/src/paperless_tika/parsers.py", line 82, in parse

    self.archive_path = self.convert_to_pdf(document_path, file_name)

  File "/usr/src/paperless/src/paperless_tika/parsers.py", line 113, in convert_to_pdf

    raise ParseError(

documents.parsers.ParseError: Error while converting document to PDF: 503 Server Error: Service Unavailable for url: http://gotenberg:3000/forms/libreoffice/convert
```

### Paperless-ngx version

1.14.0

### Host OS

Synology DSM 7.1.1-42962 Update 5

### Installation method

Docker - official image

### Browser

Chrome

### Configuration changes

No

**Comment by stumpylog** [comment]
This is a duplicate of #2753, #747 and probably others.

An http 503 means the server cannot handle the request.  The server is Gotenberg, not paperless.  I also cannot reproduce this with either docx or odt.

I would suggest recreating your Gotenberg container, ensuring you have set the command as per the example and then looking to the Gotenberg issues: gotenberg/gotenberg/issues
