### ISSUE TITLE
[BUG] Autocomplete Search not working after migration from paperless-ng with sqlite to -ngx with postgres

### ISSUE THREAD

**Issue by mptr8956** [paperless-ngx/paperless-ngx#320]
**Describe the bug**
I upgraded from paperless-ng (linuxserver io with sqlite) to -ngx (with postgres) and migrated the database. Everything is up and running, except the search function in the top bar. I can enter something here, but it will never find anything. Searching in the documents section is working flawlessly (also full text search). Error log see below. 

**Webserver logs**
[2022-03-13 20:58:30,403] [ERROR] [django.request] Internal Server Error: /api/search/autocomplete/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 451, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
  File "/usr/local/lib/python3.9/site-packages/asgiref/current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/src/paperless/src/documents/views.py", line 595, in get
    return Response(index.autocomplete(ix, term, limit))
  File "/usr/src/paperless/src/documents/index.py", line 268, in autocomplete
    for (score, t) in reader.most_distinctive_terms(
  File "/usr/local/lib/python3.9/site-packages/whoosh/reading.py", line 560, in most_distinctive_terms
    return nlargest(number, gen)
  File "/usr/local/lib/python3.9/heapq.py", line 546, in nlargest
    result = [(elem, i) for i, elem in zip(range(0, -n, -1), it)]
  File "/usr/local/lib/python3.9/heapq.py", line 546, in <listcomp>
    result = [(elem, i) for i, elem in zip(range(0, -n, -1), it)]
  File "/usr/local/lib/python3.9/site-packages/whoosh/reading.py", line 558, in <genexpr>
    gen = ((terminfo.weight() * log(N / terminfo.doc_frequency()), text)
ValueError: math domain error

**Relevant information**
 - Host OS of the machine running paperless: Synology with Docker
 - Browser Edge
 - Installation method: docker with postgres and tika

**Comment by mptr8956** [comment]
after leaving the system alone this night, todays logs dont show any errors when searching via the top search bar, but still zero search results and auto completion not working.

**Comment by mptr8956** [comment]
I think i found the problem & the solution: If i search in the upper search box, it uses the "extended search" option in the dropdown (see screenshot). 

![image](https://user-images.githubusercontent.com/73469840/158210893-6241e80e-02b7-4b29-9f44-6fc2d59d3d08.png)

If i search directly in the documents section, the standard option is usually "Title & Content". With title & content, it found everything properly. With the extended search it doesnt. 

After changing a document & saving it again, Autocomplete showed up for those documents again and extended search worked again. That lead me to rebuild the complete OCR-database with the bash command 

`document_archiver --overwrite`

et voila: everything is working again. The error in the log above appeared once and never again. TBH: I really do not understand why this happens, because from my point of view, extended search should search the same content as "Title & Content" and even more. Or what is extended search doing differently?

Thanks anyways.
