### ISSUE TITLE
[ERROR] [paperless.consumer]  Content type for given perms and klass differs.

### ISSUE THREAD

**Issue by piscinas** [paperless-ngx/paperless-ngx#3213]
### Description

After import document i receive this error:

`[2023-04-27 17:17:28,487] [ERROR] [paperless.consumer] The following error occurred while consuming Document1.pdf: Content type for given perms and klass differ`

### Steps to reproduce

Import pdf file.

### Webserver logs

```bash
[2023-04-27 17:17:28,487] [ERROR] [paperless.consumer] The following error occurred while consuming Document1.pdf: Content type for given perms and klass differs

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/consumer.py", line 434, in try_consume_file

    document_consumption_finished.send(

  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 176, in send

    return [

  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>

    (receiver, receiver(signal=self, sender=sender, **named))

  File "/usr/src/paperless/src/documents/signals/handlers.py", line 38, in add_inbox_tags

    tags = get_objects_for_user_owner_aware(

  File "/usr/src/paperless/src/documents/permissions.py", line 111, in get_objects_for_user_owner_aware

    objects_with_perms = get_objects_for_user(

  File "/usr/local/lib/python3.9/site-packages/guardian/shortcuts.py", line 534, in get_objects_for_user

    raise MixedContentTypeError("Content type for given perms and "

guardian.exceptions.MixedContentTypeError: Content type for given perms and klass differs
```

### Paperless-ngx version

1.14.1

### Host OS

Debian 11

### Installation method

Docker - official image

### Browser

Edge

**Comment by max-slamchest** [comment]
Same issue, logs included: 

```
[2023-04-27 11:33:10,893] [ERROR] [paperless.consumer] The following error occurred while consuming document.pdf: Content type for given perms and klass differs

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/consumer.py", line 434, in try_consume_file

    document_consumption_finished.send(

  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 176, in send

    return [

  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>

    (receiver, receiver(signal=self, sender=sender, **named))

  File "/usr/src/paperless/src/documents/signals/handlers.py", line 38, in add_inbox_tags

    tags = get_objects_for_user_owner_aware(

  File "/usr/src/paperless/src/documents/permissions.py", line 111, in get_objects_for_user_owner_aware

    objects_with_perms = get_objects_for_user(

  File "/usr/local/lib/python3.9/site-packages/guardian/shortcuts.py", line 534, in get_objects_for_user

    raise MixedContentTypeError("Content type for given perms and "

guardian.exceptions.MixedContentTypeError: Content type for given perms and klass differs
```
### Paperless-ngx version

1.14.1
### Host OS

Ubuntu 22.04.2
### Installation method

Docker - official image
### Browser

Firefox

**Comment by p11sam1** [comment]
Same issue, log below.

```
[2023-04-27 19:35:23,554] [ERROR] [paperless.consumer] The following error occurred while consuming Scanned Document.pdf: Content type for given perms and klass differs

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/consumer.py", line 434, in try_consume_file

    document_consumption_finished.send(

  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 176, in send

    return [

  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>

    (receiver, receiver(signal=self, sender=sender, **named))

  File "/usr/src/paperless/src/documents/signals/handlers.py", line 38, in add_inbox_tags

    tags = get_objects_for_user_owner_aware(

  File "/usr/src/paperless/src/documents/permissions.py", line 111, in get_objects_for_user_owner_aware

    objects_with_perms = get_objects_for_user(

  File "/usr/local/lib/python3.9/site-packages/guardian/shortcuts.py", line 534, in get_objects_for_user

    raise MixedContentTypeError("Content type for given perms and "

guardian.exceptions.MixedContentTypeError: Content type for given perms and klass differs
```

### Paperless-ngx version
1.14.1

### Host OS
Ubuntu 22.04.2

### Installation method
Docker - official image

### Browser
Firefox

**Comment by shamoon** [comment]
Thanks, we'll release .2 soon to fix this

**Comment by am93** [comment]
> Thanks, we'll release .2 soon to fix this

When is this new release expected ? Latest release is currently completely broken due to this issue. Next time I suggest leaving issues open until they are released to prevent duplicate issues (as mine),

**Comment by stumpylog** [comment]
It's already building.
