### ISSUE TITLE
[BUG] I upgrade to 1.14.1 and now i can't upload any pdf

### ISSUE THREAD

**Issue by Mike710Shine** [paperless-ngx/paperless-ngx#3217]
### Description

I have upgrade my paperless-ngx instance to 1.14.1 and now i can't upload pdf successfuly. I get always the Error "The following error occurred while consuming Eingangsbestätigung_Familienfragebogen.pdf: Content type for given perms and klass differs". 

### Steps to reproduce

1. Load a pdf up
2. Get the Error

### Webserver logs

```bash
This is the whole log.

Paperless-ngx docker container starting...
Mapping UID and GID for paperless:paperless to 1001:100
Creating directory /tmp/paperless
Adjusting permissions of paperless files. This may take a while.
Waiting for PostgreSQL to start...
Waiting for Redis...
Connected to Redis broker.
Apply database migrations...
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, django_celery_results, documents, guardian, paperless_mail, sessions
Running migrations:
  Applying documents.1031_remove_savedview_user_correspondent_owner_and_more... OK
  Applying documents.1032_alter_correspondent_matching_algorithm_and_more... OK
  Applying documents.1033_alter_documenttype_options_alter_tag_options_and_more... OK
  Applying documents.1034_alter_savedviewfilterrule_rule_type... OK
  Applying documents.1035_rename_comment_note... OK
  Applying guardian.0001_initial... OK
  Applying guardian.0002_generic_permissions_index... OK
  Applying paperless_mail.0017_mailaccount_owner_mailrule_owner... OK
  Applying paperless_mail.0018_processedmail... OK
  Applying paperless_mail.0019_mailrule_filter_to... OK
  Applying paperless_mail.0020_mailaccount_is_token... OK
  Applying paperless_mail.0021_alter_mailaccount_password... OK
Running Django checks
System check identified no issues (0 silenced).
Search index out of date. Updating...
Did not create superuser, a user mike710shine already exists
Executing /usr/local/bin/paperless_cmd.sh
2023-04-27 17:38:13,903 INFO Set uid to user 0 succeeded
2023-04-27 17:38:13,911 INFO supervisord started with pid 1
2023-04-27 17:38:14,915 INFO spawned: 'gunicorn' with pid 116
2023-04-27 17:38:14,918 INFO spawned: 'celery' with pid 117
2023-04-27 17:38:14,922 INFO spawned: 'celery-beat' with pid 118
2023-04-27 17:38:14,925 INFO spawned: 'consumer' with pid 119
2023-04-27 17:38:14,937 INFO spawned: 'celery-flower' with pid 120
Checking if we should start flower...
Not starting flower
2023-04-27 17:38:14,982 INFO success: celery-flower entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2023-04-27 17:38:14,982 INFO exited: celery-flower (exit status 0; expected)
2023-04-27 17:38:15,988 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-04-27 17:38:15,989 INFO success: celery entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-04-27 17:38:15,990 INFO success: celery-beat entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-04-27 17:38:15,990 INFO success: consumer entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[2023-04-27 19:38:19,912] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: /usr/src/paperless/consume
[2023-04-27 19:38:20 +0200] [116] [INFO] Starting gunicorn 20.1.0
[2023-04-27 19:38:20 +0200] [116] [INFO] Listening at: http://[::]:8000 (116)
[2023-04-27 19:38:20 +0200] [116] [INFO] Using worker: paperless.workers.ConfigurableWorker
[2023-04-27 19:38:20 +0200] [116] [INFO] Server is ready. Spawning workers
[2023-04-27 19:38:21,077] [INFO] [celery.beat] beat: Starting...
[2023-04-27 19:38:21,390] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
[2023-04-27 19:38:21,508] [INFO] [celery.beat] Scheduler: Sending due task Train the classifier (documents.tasks.train_classifier)
 
 -------------- celery@6f348a9e404a v5.2.7 (dawn-chorus)
--- ***** ----- 
-- ******* ---- Linux-5.10.60-qnap-x86_64-with-glibc2.31 2023-04-27 19:38:21
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         paperless:0x7fa5ab49d2b0
- ** ---------- .> transport:   redis://redis:6379//
- ** ---------- .> results:     
- *** --- * --- .> concurrency: 1 (prefork)
-- ******* ---- .> task events: ON
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . documents.tasks.bulk_update_documents
  . documents.tasks.consume_file
  . documents.tasks.index_optimize
  . documents.tasks.sanity_check
  . documents.tasks.train_classifier
  . documents.tasks.update_document_archive_file
  . paperless_mail.mail.apply_mail_action
  . paperless_mail.mail.error_callback
  . paperless_mail.tasks.process_mail_accounts

[2023-04-27 19:38:21,926] [INFO] [celery.worker.consumer.connection] Connected to redis://redis:6379//
[2023-04-27 19:38:21,966] [INFO] [celery.apps.worker] celery@6f348a9e404a ready.
[2023-04-27 19:38:22,036] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[6a98d68e-5973-4e49-8fbc-899e53be532f] received
[2023-04-27 19:38:22,042] [INFO] [celery.worker.strategy] Task documents.tasks.train_classifier[27dcddaa-b988-440d-8f65-3df6e1d48154] received
[2023-04-27 19:38:22,308] [INFO] [celery.app.trace] Task paperless_mail.tasks.process_mail_accounts[6a98d68e-5973-4e49-8fbc-899e53be532f] succeeded in 0.2615096670015191s: 'No new documents were added.'
[2023-04-27 19:38:22,775] [INFO] [celery.app.trace] Task documents.tasks.train_classifier[27dcddaa-b988-440d-8f65-3df6e1d48154] succeeded in 0.154226661001303s: None
/usr/local/lib/python3.9/site-packages/rest_framework/pagination.py:200: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'documents.models.Document'> QuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
[2023-04-27 19:40:00,090] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
[2023-04-27 19:40:00,096] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[42114ff2-b46c-4a14-a2a7-0189de685b18] received
[2023-04-27 19:40:00,242] [INFO] [celery.app.trace] Task paperless_mail.tasks.process_mail_accounts[42114ff2-b46c-4a14-a2a7-0189de685b18] succeeded in 0.1407881749983062s: 'No new documents were added.'
[2023-04-27 19:44:15,011] [INFO] [celery.worker.strategy] Task documents.tasks.bulk_update_documents[7bbe9fee-254b-4dfc-9d2d-401dee79a8e7] received
[2023-04-27 19:44:15,459] [INFO] [celery.app.trace] Task documents.tasks.bulk_update_documents[7bbe9fee-254b-4dfc-9d2d-401dee79a8e7] succeeded in 0.44215127600182313s: None
[2023-04-27 19:44:38,902] [INFO] [celery.worker.strategy] Task documents.tasks.consume_file[28204899-b0d3-4f67-9712-690ea17f2154] received
[2023-04-27 19:44:39,032] [INFO] [paperless.consumer] Consuming 2023-03-09 Eingangsbestätigung_Familienfragebogen.pdf
[2023-04-27 19:44:40,163] [INFO] [ocrmypdf._sync] Start processing 2 pages concurrently
[2023-04-27 19:44:40,171] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-04-27 19:44:40,172] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-04-27 19:44:40,182] [INFO] [ocrmypdf._sync] Postprocessing...
[2023-04-27 19:44:41,567] [WARNING] [ocrmypdf._pipeline] Some input metadata could not be copied because it is not permitted in PDF/A. You may wish to examine the output PDF's XMP metadata.
[2023-04-27 19:44:42,569] [INFO] [ocrmypdf._pipeline] Optimize ratio: 1.00 savings: 0.0%
[2023-04-27 19:44:42,576] [INFO] [ocrmypdf._sync] Output file is a PDF/A-2B (as expected)
[2023-04-27 19:44:46,370] [ERROR] [paperless.consumer] The following error occurred while consuming 2023-03-09 Eingangsbestätigung_Familienfragebogen.pdf: Content type for given perms and klass differs
Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/consumer.py", line 434, in try_consume_file
    document_consumption_finished.send(
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/usr/src/paperless/src/documents/signals/handlers.py", line 38, in add_inbox_tags
    tags = get_objects_for_user_owner_aware(
  File "/usr/src/paperless/src/documents/permissions.py", line 111, in get_objects_for_user_owner_aware
    objects_with_perms = get_objects_for_user(
  File "/usr/local/lib/python3.9/site-packages/guardian/shortcuts.py", line 534, in get_objects_for_user
    raise MixedContentTypeError("Content type for given perms and "
guardian.exceptions.MixedContentTypeError: Content type for given perms and klass differs
[2023-04-27 19:44:46,463] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[28204899-b0d3-4f67-9712-690ea17f2154] raised unexpected: ConsumerError('2023-03-09 Eingangsbestätigung_Familienfragebogen.pdf: The following error occurred while consuming 2023-03-09 Eingangsbestätigung_Familienfragebogen.pdf: Content type for given perms and klass differs')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 302, in main_wrap
    raise exc_info[1]
  File "/usr/src/paperless/src/documents/consumer.py", line 434, in try_consume_file
    document_consumption_finished.send(
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/usr/src/paperless/src/documents/signals/handlers.py", line 38, in add_inbox_tags
    tags = get_objects_for_user_owner_aware(
  File "/usr/src/paperless/src/documents/permissions.py", line 111, in get_objects_for_user_owner_aware
    objects_with_perms = get_objects_for_user(
  File "/usr/local/lib/python3.9/site-packages/guardian/shortcuts.py", line 534, in get_objects_for_user
    raise MixedContentTypeError("Content type for given perms and "
guardian.exceptions.MixedContentTypeError: Content type for given perms and klass differs

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/paperless/src/documents/tasks.py", line 190, in consume_file
    document = Consumer().try_consume_file(
  File "/usr/src/paperless/src/documents/consumer.py", line 493, in try_consume_file
    self._fail(
  File "/usr/src/paperless/src/documents/consumer.py", line 96, in _fail
    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
documents.consumer.ConsumerError: 2023-03-09 Eingangsbestätigung_Familienfragebogen.pdf: The following error occurred while consuming 2023-03-09 Eingangsbestätigung_Familienfragebogen.pdf: Content type for given perms and klass differs
[2023-04-27 19:46:17,602] [INFO] [celery.worker.strategy] Task documents.tasks.consume_file[6c6ef199-4115-431c-b8ed-83c8f09c7cb0] received
[2023-04-27 19:46:17,761] [INFO] [paperless.consumer] Consuming 2023-03-09 Eingangsbestätigung_Familienfragebogen.pdf
[2023-04-27 19:46:18,822] [INFO] [ocrmypdf._sync] Start processing 2 pages concurrently
[2023-04-27 19:46:18,828] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-04-27 19:46:18,830] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-04-27 19:46:18,838] [INFO] [ocrmypdf._sync] Postprocessing...
[2023-04-27 19:46:20,245] [WARNING] [ocrmypdf._pipeline] Some input metadata could not be copied because it is not permitted in PDF/A. You may wish to examine the output PDF's XMP metadata.
[2023-04-27 19:46:21,241] [INFO] [ocrmypdf._pipeline] Optimize ratio: 1.00 savings: 0.0%
[2023-04-27 19:46:21,248] [INFO] [ocrmypdf._sync] Output file is a PDF/A-2B (as expected)
[2023-04-27 19:46:25,108] [ERROR] [paperless.consumer] The following error occurred while consuming 2023-03-09 Eingangsbestätigung_Familienfragebogen.pdf: Content type for given perms and klass differs
Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/consumer.py", line 434, in try_consume_file
    document_consumption_finished.send(
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/usr/src/paperless/src/documents/signals/handlers.py", line 38, in add_inbox_tags
    tags = get_objects_for_user_owner_aware(
  File "/usr/src/paperless/src/documents/permissions.py", line 111, in get_objects_for_user_owner_aware
    objects_with_perms = get_objects_for_user(
  File "/usr/local/lib/python3.9/site-packages/guardian/shortcuts.py", line 534, in get_objects_for_user
    raise MixedContentTypeError("Content type for given perms and "
guardian.exceptions.MixedContentTypeError: Content type for given perms and klass differs
[2023-04-27 19:46:25,205] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[6c6ef199-4115-431c-b8ed-83c8f09c7cb0] raised unexpected: ConsumerError('2023-03-09 Eingangsbestätigung_Familienfragebogen.pdf: The following error occurred while consuming 2023-03-09 Eingangsbestätigung_Familienfragebogen.pdf: Content type for given perms and klass differs')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 302, in main_wrap
    raise exc_info[1]
  File "/usr/src/paperless/src/documents/consumer.py", line 434, in try_consume_file
    document_consumption_finished.send(
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/usr/src/paperless/src/documents/signals/handlers.py", line 38, in add_inbox_tags
    tags = get_objects_for_user_owner_aware(
  File "/usr/src/paperless/src/documents/permissions.py", line 111, in get_objects_for_user_owner_aware
    objects_with_perms = get_objects_for_user(
  File "/usr/local/lib/python3.9/site-packages/guardian/shortcuts.py", line 534, in get_objects_for_user
    raise MixedContentTypeError("Content type for given perms and "
guardian.exceptions.MixedContentTypeError: Content type for given perms and klass differs

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/paperless/src/documents/tasks.py", line 190, in consume_file
    document = Consumer().try_consume_file(
  File "/usr/src/paperless/src/documents/consumer.py", line 493, in try_consume_file
    self._fail(
  File "/usr/src/paperless/src/documents/consumer.py", line 96, in _fail
    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
documents.consumer.ConsumerError: 2023-03-09 Eingangsbestätigung_Familienfragebogen.pdf: The following error occurred while consuming 2023-03-09 Eingangsbestätigung_Familienfragebogen.pdf: Content type for given perms and klass differs
[2023-04-27 19:50:00,196] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
[2023-04-27 19:50:00,215] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[c753360b-6114-429e-ba39-2735c26fba52] received
[2023-04-27 19:50:00,389] [INFO] [celery.app.trace] Task paperless_mail.tasks.process_mail_accounts[c753360b-6114-429e-ba39-2735c26fba52] succeeded in 0.15515839400177356s: 'No new documents were added.'
[2023-04-27 19:50:18,078] [INFO] [celery.worker.strategy] Task documents.tasks.consume_file[2b07057d-c619-4884-ad82-b5bddcb174a0] received
[2023-04-27 19:50:18,254] [INFO] [paperless.consumer] Consuming Eingangsbestätigung_Familienfragebogen.pdf
[2023-04-27 19:50:19,252] [INFO] [ocrmypdf._sync] Start processing 2 pages concurrently
[2023-04-27 19:50:19,265] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-04-27 19:50:19,266] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-04-27 19:50:19,275] [INFO] [ocrmypdf._sync] Postprocessing...
[2023-04-27 19:50:22,761] [INFO] [ocrmypdf._pipeline] Optimize ratio: 1.00 savings: 0.0%
[2023-04-27 19:50:22,768] [INFO] [ocrmypdf._sync] Output file is a PDF/A-2B (as expected)
[2023-04-27 19:50:26,486] [ERROR] [paperless.consumer] The following error occurred while consuming Eingangsbestätigung_Familienfragebogen.pdf: Content type for given perms and klass differs
Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/consumer.py", line 434, in try_consume_file
    document_consumption_finished.send(
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/usr/src/paperless/src/documents/signals/handlers.py", line 38, in add_inbox_tags
    tags = get_objects_for_user_owner_aware(
  File "/usr/src/paperless/src/documents/permissions.py", line 111, in get_objects_for_user_owner_aware
    objects_with_perms = get_objects_for_user(
  File "/usr/local/lib/python3.9/site-packages/guardian/shortcuts.py", line 534, in get_objects_for_user
    raise MixedContentTypeError("Content type for given perms and "
guardian.exceptions.MixedContentTypeError: Content type for given perms and klass differs
[2023-04-27 19:50:26,599] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[2b07057d-c619-4884-ad82-b5bddcb174a0] raised unexpected: ConsumerError('Eingangsbestätigung_Familienfragebogen.pdf: The following error occurred while consuming Eingangsbestätigung_Familienfragebogen.pdf: Content type for given perms and klass differs')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 302, in main_wrap
    raise exc_info[1]
  File "/usr/src/paperless/src/documents/consumer.py", line 434, in try_consume_file
    document_consumption_finished.send(
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/usr/src/paperless/src/documents/signals/handlers.py", line 38, in add_inbox_tags
    tags = get_objects_for_user_owner_aware(
  File "/usr/src/paperless/src/documents/permissions.py", line 111, in get_objects_for_user_owner_aware
    objects_with_perms = get_objects_for_user(
  File "/usr/local/lib/python3.9/site-packages/guardian/shortcuts.py", line 534, in get_objects_for_user
    raise MixedContentTypeError("Content type for given perms and "
guardian.exceptions.MixedContentTypeError: Content type for given perms and klass differs

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/paperless/src/documents/tasks.py", line 190, in consume_file
    document = Consumer().try_consume_file(
  File "/usr/src/paperless/src/documents/consumer.py", line 493, in try_consume_file
    self._fail(
  File "/usr/src/paperless/src/documents/consumer.py", line 96, in _fail
    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
documents.consumer.ConsumerError: Eingangsbestätigung_Familienfragebogen.pdf: The following error occurred while consuming Eingangsbestätigung_Familienfragebogen.pdf: Content type for given perms and klass differs
[2023-04-27 19:50:58,529] [INFO] [celery.worker.strategy] Task documents.tasks.consume_file[aa89682a-99ea-40b9-bb32-2886452f6ca0] received
[2023-04-27 19:50:58,691] [INFO] [paperless.consumer] Consuming Finanzamtsbescheinigung 2015.pdf
[2023-04-27 19:50:59,688] [INFO] [ocrmypdf._sync] Start processing 2 pages concurrently
[2023-04-27 19:50:59,705] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-04-27 19:50:59,706] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-04-27 19:50:59,716] [INFO] [ocrmypdf._sync] Postprocessing...
[2023-04-27 19:51:00,944] [INFO] [ocrmypdf._pipeline] Optimize ratio: 1.03 savings: 2.6%
[2023-04-27 19:51:00,951] [WARNING] [ocrmypdf._sync] Output file is okay but is not PDF/A (seems to be No PDF/A metadata in XMP)
[2023-04-27 19:51:12,662] [ERROR] [paperless.consumer] The following error occurred while consuming Finanzamtsbescheinigung 2015.pdf: Content type for given perms and klass differs
Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/consumer.py", line 434, in try_consume_file
    document_consumption_finished.send(
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/usr/src/paperless/src/documents/signals/handlers.py", line 38, in add_inbox_tags
    tags = get_objects_for_user_owner_aware(
  File "/usr/src/paperless/src/documents/permissions.py", line 111, in get_objects_for_user_owner_aware
    objects_with_perms = get_objects_for_user(
  File "/usr/local/lib/python3.9/site-packages/guardian/shortcuts.py", line 534, in get_objects_for_user
    raise MixedContentTypeError("Content type for given perms and "
guardian.exceptions.MixedContentTypeError: Content type for given perms and klass differs
[2023-04-27 19:51:12,815] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[aa89682a-99ea-40b9-bb32-2886452f6ca0] raised unexpected: ConsumerError('Finanzamtsbescheinigung 2015.pdf: The following error occurred while consuming Finanzamtsbescheinigung 2015.pdf: Content type for given perms and klass differs')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 302, in main_wrap
    raise exc_info[1]
  File "/usr/src/paperless/src/documents/consumer.py", line 434, in try_consume_file
    document_consumption_finished.send(
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/usr/src/paperless/src/documents/signals/handlers.py", line 38, in add_inbox_tags
    tags = get_objects_for_user_owner_aware(
  File "/usr/src/paperless/src/documents/permissions.py", line 111, in get_objects_for_user_owner_aware
    objects_with_perms = get_objects_for_user(
  File "/usr/local/lib/python3.9/site-packages/guardian/shortcuts.py", line 534, in get_objects_for_user
    raise MixedContentTypeError("Content type for given perms and "
guardian.exceptions.MixedContentTypeError: Content type for given perms and klass differs

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/paperless/src/documents/tasks.py", line 190, in consume_file
    document = Consumer().try_consume_file(
  File "/usr/src/paperless/src/documents/consumer.py", line 493, in try_consume_file
    self._fail(
  File "/usr/src/paperless/src/documents/consumer.py", line 96, in _fail
    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
documents.consumer.ConsumerError: Finanzamtsbescheinigung 2015.pdf: The following error occurred while consuming Finanzamtsbescheinigung 2015.pdf: Content type for given perms and klass differs
[2023-04-27 19:52:51,198] [INFO] [celery.worker.strategy] Task documents.tasks.consume_file[37b25111-fb6c-4d16-a48a-d591611005ee] received
[2023-04-27 19:52:51,324] [INFO] [paperless.consumer] Consuming Eingangsbestätigung_Familienfragebogen.pdf
[2023-04-27 19:52:52,315] [INFO] [ocrmypdf._sync] Start processing 2 pages concurrently
[2023-04-27 19:52:52,328] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-04-27 19:52:52,329] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-04-27 19:52:52,338] [INFO] [ocrmypdf._sync] Postprocessing...
[2023-04-27 19:52:55,780] [INFO] [ocrmypdf._pipeline] Optimize ratio: 1.00 savings: 0.0%
[2023-04-27 19:52:55,789] [INFO] [ocrmypdf._sync] Output file is a PDF/A-2B (as expected)
[2023-04-27 19:52:59,599] [ERROR] [paperless.consumer] The following error occurred while consuming Eingangsbestätigung_Familienfragebogen.pdf: Content type for given perms and klass differs
Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/consumer.py", line 434, in try_consume_file
    document_consumption_finished.send(
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/usr/src/paperless/src/documents/signals/handlers.py", line 38, in add_inbox_tags
    tags = get_objects_for_user_owner_aware(
  File "/usr/src/paperless/src/documents/permissions.py", line 111, in get_objects_for_user_owner_aware
    objects_with_perms = get_objects_for_user(
  File "/usr/local/lib/python3.9/site-packages/guardian/shortcuts.py", line 534, in get_objects_for_user
    raise MixedContentTypeError("Content type for given perms and "
guardian.exceptions.MixedContentTypeError: Content type for given perms and klass differs
[2023-04-27 19:52:59,725] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[37b25111-fb6c-4d16-a48a-d591611005ee] raised unexpected: ConsumerError('Eingangsbestätigung_Familienfragebogen.pdf: The following error occurred while consuming Eingangsbestätigung_Familienfragebogen.pdf: Content type for given perms and klass differs')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 302, in main_wrap
    raise exc_info[1]
  File "/usr/src/paperless/src/documents/consumer.py", line 434, in try_consume_file
    document_consumption_finished.send(
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/usr/src/paperless/src/documents/signals/handlers.py", line 38, in add_inbox_tags
    tags = get_objects_for_user_owner_aware(
  File "/usr/src/paperless/src/documents/permissions.py", line 111, in get_objects_for_user_owner_aware
    objects_with_perms = get_objects_for_user(
  File "/usr/local/lib/python3.9/site-packages/guardian/shortcuts.py", line 534, in get_objects_for_user
    raise MixedContentTypeError("Content type for given perms and "
guardian.exceptions.MixedContentTypeError: Content type for given perms and klass differs

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/paperless/src/documents/tasks.py", line 190, in consume_file
    document = Consumer().try_consume_file(
  File "/usr/src/paperless/src/documents/consumer.py", line 493, in try_consume_file
    self._fail(
  File "/usr/src/paperless/src/documents/consumer.py", line 96, in _fail
    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
documents.consumer.ConsumerError: Eingangsbestätigung_Familienfragebogen.pdf: The following error occurred while consuming Eingangsbestätigung_Familienfragebogen.pdf: Content type for given perms and klass differs
```

### Paperless-ngx version

1.14.1

### Host OS

Linux / Qnap / Docker

### Installation method

Docker - official image

### Browser

Opera

### Configuration changes

no

**Comment by shamoon** [comment]
We're releasing .2 now which fixes this
