### ISSUE TITLE
[BUG] Unknown argument X-GM-LABELS error while fetching mails via IMAP

### ISSUE THREAD

**Issue by goxxi** [paperless-ngx/paperless-ngx#3233]
### Description

The issue from https://github.com/paperless-ngx/paperless-ngx/issues/1753 seems to occur again in 1.14.2

### Steps to reproduce

1. Configure a mail account with a non-gmail mailserver (f.e. dovecot)
2. Create a rule with action "Tag" (5)
3. Let paperless try to fetch mails

### Webserver logs

```bash
[2023-04-28 19:00:00,318] [DEBUG] [paperless_mail] Processing mail account xxx
[2023-04-28 19:00:00,490] [DEBUG] [paperless_mail] GMAIL Label Support: False
[2023-04-28 19:00:00,492] [DEBUG] [paperless_mail] AUTH=PLAIN Support: True
[2023-04-28 19:00:00,530] [DEBUG] [paperless_mail] Account xxx: Processing 2 rule(s)
[2023-04-28 19:00:00,540] [DEBUG] [paperless_mail] Rule xxx: Selecting folder INBOX
[2023-04-28 19:00:00,553] [DEBUG] [paperless_mail] Rule xxx: Searching folder with criteria ((NOT (X-GM-LABELS "paperless") UNKEYWORD paperless) SINCE 14-Apr-2023)
[2023-04-28 19:00:00,565] [ERROR] [paperless_mail] Rule xxx: Error while processing rule: SEARCH command error: BAD [b'Error in IMAP command SEARCH: Unknown argument X-GM-LABELS (0.000 + 0.000 secs).']
Traceback (most recent call last):
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 490, in handle_mail_account
    total_processed_files += self._handle_mail_rule(
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 561, in _handle_mail_rule
    for message in messages:
  File "/usr/local/lib/python3.9/site-packages/imap_tools/mailbox.py", line 170, in fetch
    nums = tuple((reversed if reverse else iter)(self.numbers(criteria, charset)))[limit_range]
  File "/usr/local/lib/python3.9/site-packages/imap_tools/mailbox.py", line 108, in numbers
    search_result = self.client.search(charset, encoded_criteria)
  File "/usr/local/lib/python3.9/imaplib.py", line 732, in search
    typ, dat = self._simple_command(name, 'CHARSET', charset, *criteria)
  File "/usr/local/lib/python3.9/imaplib.py", line 1230, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/local/lib/python3.9/imaplib.py", line 1055, in _command_complete
    raise self.error('%s command error: %s %s' % (name, typ, data))
imaplib.IMAP4.error: SEARCH command error: BAD [b'Error in IMAP command SEARCH: Unknown argument X-GM-LABELS (0.000 + 0.000 secs).']
```

### Paperless-ngx version

1.14.2

### Host OS

Debian

### Installation method

Docker - official image

**Comment by stumpylog** [comment]
Most servers must ignore the unknown argument, but not all.  Likely easy to fix, it's possible to know if a server supports the Gmail extensions
