### ISSUE TITLE
[BUG] File system permissions error in 1.14.2 prevents uploading or editing documents

### ISSUE THREAD

**Issue by bee-san** [paperless-ngx/paperless-ngx#3253]
### Description

Upgraded to 1.14.2 from 1.12, and I am now getting permissions errors.

When trying to save a document I get:

```
Error saving document: Http failure response for http://XXXX/api/documents/718/: 500 Internal Server Error
```

When consuming:

```
A-74821ED2-94224222-1.pdf: The following error occurred while consuming A-74821ED2-94224222-1.pdf: [Errno 1] Operation not permitted: 68
```

The logs says:

```
[2023-04-30 08:02:02,800] [ERROR] [paperless.consumer] The following error occurred while consuming A-74821ED2-65832652-1.pdf: [Errno 1] Operation not permitted: 68

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/consumer.py", line 443, in try_consume_file

    with FileLock(settings.MEDIA_LOCK):

  File "/usr/local/lib/python3.9/site-packages/filelock/_api.py", line 227, in __enter__

    self.acquire()

  File "/usr/local/lib/python3.9/site-packages/filelock/_api.py", line 182, in acquire

    self._acquire()

  File "/usr/local/lib/python3.9/site-packages/filelock/_unix.py", line 36, in _acquire

    os.chmod(fd, self._mode)

PermissionError: [Errno 1] Operation not permitted: 68
```

This worked fine before I upgraded, so I am assuming it is a Paperless issue 🤔  It can't be that the consume folder has different perms now because I also cannot edit any documents (I also have not changed any perms lately, it was all working fine on 1.12 until I upgraded to 1.14.2)

### Steps to reproduce

Use 1.14.2

Upload files or try to edit a file and I get a permissions error

### Webserver logs

```bash
[2023-04-30 08:01:57,601] [ERROR] [paperless.consumer] The following error occurred while consuming A-74821ED2-66540805-1.pdf: [Errno 1] Operation not permitted: 68

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/consumer.py", line 443, in try_consume_file

    with FileLock(settings.MEDIA_LOCK):

  File "/usr/local/lib/python3.9/site-packages/filelock/_api.py", line 227, in __enter__

    self.acquire()

  File "/usr/local/lib/python3.9/site-packages/filelock/_api.py", line 182, in acquire

    self._acquire()

  File "/usr/local/lib/python3.9/site-packages/filelock/_unix.py", line 36, in _acquire

    os.chmod(fd, self._mode)

PermissionError: [Errno 1] Operation not permitted: 68
```
```


### Browser logs

```bash
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
ap
```

### Paperless-ngx version

1.14.2

### Host OS

Ubuntu Server 20.04

### Installation method

Docker - official image

**Comment by bee-san** [comment]
Saw this:
https://github.com/paperless-ngx/paperless-ngx/issues/3213

I am definitely using 1.14.2

```
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:1.14.2
```

**Comment by bee-san** [comment]
Same issue as https://github.com/paperless-ngx/paperless-ngx/discussions/3195

I am not using NFS, I have re-created all volumes etc.

**Comment by bee-san** [comment]
Here's an error from docker logs:

```
[2023-04-30 08:54:57,618] [ERROR] [paperless.consumer] The following error occurred while consuming A-74821ED2-90209445-1.pdf: [Errno 1] Operation not permitted: 68
Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/consumer.py", line 443, in try_consume_file
    with FileLock(settings.MEDIA_LOCK):
  File "/usr/local/lib/python3.9/site-packages/filelock/_api.py", line 227, in __enter__
    self.acquire()
  File "/usr/local/lib/python3.9/site-packages/filelock/_api.py", line 182, in acquire
    self._acquire()
  File "/usr/local/lib/python3.9/site-packages/filelock/_unix.py", line 36, in _acquire
    os.chmod(fd, self._mode)
PermissionError: [Errno 1] Operation not permitted: 68
[2023-04-30 08:54:57,655] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[ad6bee0d-bb28-4c5d-8d62-79055b0be00e] raised unexpected: ConsumerError('A-74821ED2-90209445-1.pdf: The following error occurred while consuming A-74821ED2-90209445-1.pdf: [Errno 1] Operation not permitted: 68')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 302, in main_wrap
    raise exc_info[1]
  File "/usr/src/paperless/src/documents/consumer.py", line 443, in try_consume_file
    with FileLock(settings.MEDIA_LOCK):
  File "/usr/local/lib/python3.9/site-packages/filelock/_api.py", line 227, in __enter__
    self.acquire()
  File "/usr/local/lib/python3.9/site-packages/filelock/_api.py", line 182, in acquire
    self._acquire()
  File "/usr/local/lib/python3.9/site-packages/filelock/_unix.py", line 36, in _acquire
    os.chmod(fd, self._mode)
PermissionError: [Errno 1] Operation not permitted: 68

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/paperless/src/documents/tasks.py", line 190, in consume_file
    document = Consumer().try_consume_file(
  File "/usr/src/paperless/src/documents/consumer.py", line 493, in try_consume_file
    self._fail(
  File "/usr/src/paperless/src/documents/consumer.py", line 96, in _fail
    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
documents.consumer.ConsumerError: A-74821ED2-90209445-1.pdf: The following error occurred while consuming A-74821ED2-90209445-1.pdf: [Errno 1] Operation not permitted: 68
[2023-04-30 08:55:02,972] [INFO] [celery.worker.strategy] Task documents.tasks.consume_file[86aa297c-d60a-47e8-84f8-5e7a0cf417bc] received
[2023-04-30 08:55:14,237] [ERROR] [django.request] Internal Server Error: /api/documents/718/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 486, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = await get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
  File "/usr/local/lib/python3.9/site-packages/asgiref/current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/src/paperless/src/documents/views.py", line 288, in update
    response = super().update(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/mixins.py", line 78, in perform_update
    serializer.save()
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 207, in save
    self.instance = self.update(self.instance, validated_data)
  File "/usr/src/paperless/src/documents/serialisers.py", line 436, in update
    instance.save()
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 812, in save
    self.save_base(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 878, in save_base
    post_save.send(
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/usr/src/paperless/src/documents/signals/handlers.py", line 398, in update_filename_and_move_files
    with FileLock(settings.MEDIA_LOCK):
  File "/usr/local/lib/python3.9/site-packages/filelock/_api.py", line 227, in __enter__
    self.acquire()
  File "/usr/local/lib/python3.9/site-packages/filelock/_api.py", line 182, in acquire
    self._acquire()
  File "/usr/local/lib/python3.9/site-packages/filelock/_unix.py", line 36, in _acquire
    os.chmod(fd, self._mode)
PermissionError: [Errno 1] Operation not permitted: 58
```

Here's an error from editing an existing document:

```
[2023-04-30 08:57:21,727] [ERROR] [django.request] Internal Server Error: /api/documents/718/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 486, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = await get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
  File "/usr/local/lib/python3.9/site-packages/asgiref/current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/src/paperless/src/documents/views.py", line 288, in update
    response = super().update(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/mixins.py", line 78, in perform_update
    serializer.save()
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 207, in save
    self.instance = self.update(self.instance, validated_data)
  File "/usr/src/paperless/src/documents/serialisers.py", line 436, in update
    instance.save()
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 812, in save
    self.save_base(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 878, in save_base
    post_save.send(
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/usr/src/paperless/src/documents/signals/handlers.py", line 398, in update_filename_and_move_files
    with FileLock(settings.MEDIA_LOCK):
  File "/usr/local/lib/python3.9/site-packages/filelock/_api.py", line 227, in __enter__
    self.acquire()
  File "/usr/local/lib/python3.9/site-packages/filelock/_api.py", line 182, in acquire
    self._acquire()
  File "/usr/local/lib/python3.9/site-packages/filelock/_unix.py", line 36, in _acquire
    os.chmod(fd, self._mode)
PermissionError: [Errno 1] Operation not permitted: 62
```

**Comment by bee-san** [comment]
Here's my Docker compose, it's similar to the docs https://github.com/paperless-ngx/paperless-ngx/blob/main/docker/compose/docker-compose.sqlite.yml

```
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:1.14.2
    container_name: paperless
    hostname: paperless
    restart: unless-stopped
    depends_on:
      - broker
      - gotenberg
      - tika
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /home/autumn/paperless-ngx/export:/usr/src/paperless/export
      - data:/usr/src/paperless/data
      - /mnt/ssd/paperless-ngx/media:/usr/src/paperless/media
      - /mnt/ssd/paperless-ngx/consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.8
    restart: unless-stopped

    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped


volumes:
  data:
  redisdata:
```

What's strange to me is that everything is pointing to some sort of setup issue, but this only happened when I upgraded to 1.14.2 from 1.12 🤔

**Comment by bee-san** [comment]
I added `user` in:

```
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:1.14.2
    user: "1000"
```

My host user is `1000, 1000` and I have it in the `.env` too:

```
PAPERLESS_TIME_ZONE=Europe/London
PAPERLESS_OCR_LANGUAGE=eng
USERMAP_UID=1000
USERMAP_GID=1000
```

```
id -g
1000
id -u
1000
```

Still not working for me :(

**Comment by bee-san** [comment]
When I start paperless it attempts to chown:

```
Creating directory /tmp/paperless
Adjusting permissions of paperless files. This may take a while.
chown: changing ownership of '/usr/src/paperless/media': Operation not permitted
```

If I inspect, paperless has changed the ownership of my files from `autumn` (my root user) to `100999` for some reason.

**Comment by stumpylog** [comment]
Try using the provided method to change the user id and group id, instead of using Docker's `user:` directive.

**Comment by mandrepont** [comment]
I need to try and debug this further, but I am out of town. I can say that after upgrade from 1.13 to 1.14.2 I am experiencing the same issue in my kubernetes cluster where the data is a SMB share. Nothing else changed in my cluster otherwise.

**Comment by jchue** [comment]
> * Try using the provided method to change the user id and group id, instead of using Docker's `user:` directive, and not together (no idea how those would interact).

@stumpylog The documentation is a little confusing in this regard:

![image](https://user-images.githubusercontent.com/5141427/235477518-403703b2-a654-44af-b337-c271f5a41272.png)

**Comment by stumpylog** [comment]
Those instructions are only relevant if trying to run rootless.  Though there's some documentation on trying that, like a lot of containers, it won't always be a smooth transition.

**Comment by rbrownwsws** [comment]
I'm in the same situation as @mandrepont.

I'm using a kubernetes cluster with data on a SMB share.

1.13.0 worked fine for me.

I upgraded from 1.13.0 -> 1.14.2.
I start getting the "[Errno 1] Operation not permitted: 68" errors when I attempt to consume a PDF.

I downgraded from 1.14.2 -> 1.13.0.
It starts working again.

In case it helps anyone else here is how I downgraded:

```sh
# Stop paperless v1.14.2 pod

# Roll back v1.14.2 db migrations
kubectl run downgrade-paperless -n <PAPERLESS_NAMESPACE> \
    --image=ghcr.io/paperless-ngx/paperless-ngx:1.14.2 \
    --restart=Never \
    --env="PAPERLESS_REDIS=redis://<REDIS_HOST>:6379" \
    --env="PAPERLESS_DBHOST=<POSTGRESQL_HOST>" \
    --command -- python3 manage.py migrate documents 1030

# Start paperless v1.13.0 pod
```

**Comment by stumpylog** [comment]
Between [1.13 and 1.14](https://github.com/paperless-ngx/paperless-ngx/compare/v1.13.0...v1.14.2) the Dockerfile only saw updated dependencies, and the other Docker related scripts only saw an updated index version.

So we didn't make changes relating to permissions.  At a guess, something else on your system (like Docker or containerd) updated around the same time and are actually the cause.

**Comment by rbrownwsws** [comment]
@stumpylog I don't think that's right because downgrading to 1.13.0 makes paperless start working again. If it something else had messed up permissions I would expect it to still be broken after downgrading paperless.

I'm not familiar with the Paperless codebase but my initial suspicion is something may have changed with the `filelock` package as I notice it was updated from 3.9.0 -> 3.10.2

**Comment by stumpylog** [comment]
I don't see anything relevant in their [changelog](https://github.com/tox-dev/py-filelock/blob/main/docs/changelog.rst).  It would be easy to test with a custom startup script to replace the version of filelock installed and see if the issue persists.  

Something like `pip3 install --force-reinstall filelock==3.9.0`

**Comment by rbrownwsws** [comment]
There is the rather suspicious line for v3.10.3 though:

> ## v3.10.3 (2023-03-23)
> - Fix permission issue - by [:user:`jahrules`](https://github.com/tox-dev/py-filelock/blob/main/docs/changelog.rst#id7).

**Comment by rbrownwsws** [comment]
@stumpylog It's definitely the `filelock` package

I tried force-reinstalling it with a different version as you said and got the following results (all using paperless-ngx v1.14.2):

| `filelock` version | Works? |
|--|--|
| 3.9.0 (paperless-ngx v1.13.0) | Works|
| 3.10.2 (paperless-ngx v 1.14.2) | Broken |
| 3.12.0 (latest) | Works |

**Comment by bee-san** [comment]
👋🏻  I am not in kubernetes but I have also set up an SMB share for the `consume` folder

**Comment by rbrownwsws** [comment]
Simply bumping `filelock` to the latest version seems to have fixed the issue for me.

I've pushed an updated docker image if you want to see if it fixes the issue for you too @bee-san:

`ghcr.io/rbrownwsws/paperless-ngx:1.14.2-fix_buggy_filelock`

N.B. the image is based on the `dev` branch not `main` so there are other differences from the 1.14.2 release
