### ISSUE TITLE
[BUG] DB migration fails: constraint "sqlite_autoindex_documents_correspondent_1" of relation "documents_correspondent" does not exist

### ISSUE THREAD

**Issue by Eckii24** [paperless-ngx/paperless-ngx#3266]
### Description

After updating paperless-ngx via Docker from version 1.9.2 to 1.14.2 I got the following migration error:

```
paperless-ngx-webserver-1  |   Applying documents.1033_alter_documenttype_options_alter_tag_options_and_more...Traceback (most recent call last):
paperless-ngx-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
paperless-ngx-webserver-1  |     return self.cursor.execute(sql, params)
paperless-ngx-webserver-1  | psycopg2.errors.UndefinedObject: constraint "sqlite_autoindex_documents_correspondent_1" of relation "documents_correspondent" does not exist
```

I use paperless with a Postgres DB. Therefore I really do not understand the issue. I also can not see something in the referenced migration related to an auto index.

What can I do to successfully update to the latest version?

### Steps to reproduce

1. Have the version 1.9.2 running with some data
2. Update to version 1.14.2
3. Try to start the server
4. Hopefully the issue will occur...

### Webserver logs

```bash
paperless-ngx-broker-1     | 1:C 01 May 2023 18:41:49.049 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
paperless-ngx-broker-1     | 1:C 01 May 2023 18:41:49.049 # Redis version=6.0.19, bits=64, commit=00000000, modified=0, pid=1, just started
paperless-ngx-broker-1     | 1:C 01 May 2023 18:41:49.049 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
paperless-ngx-broker-1     | 1:M 01 May 2023 18:41:49.050 * Running mode=standalone, port=6379.
paperless-ngx-broker-1     | 1:M 01 May 2023 18:41:49.050 # Server initialized
paperless-ngx-broker-1     | 1:M 01 May 2023 18:41:49.066 * Loading RDB produced by version 6.0.19
paperless-ngx-broker-1     | 1:M 01 May 2023 18:41:49.066 * RDB age 89 seconds
paperless-ngx-broker-1     | 1:M 01 May 2023 18:41:49.066 * RDB memory usage when created 0.77 Mb
paperless-ngx-broker-1     | 1:M 01 May 2023 18:41:49.066 * DB loaded from disk: 0.016 seconds
paperless-ngx-broker-1     | 1:M 01 May 2023 18:41:49.066 * Ready to accept connections
paperless-ngx-adminer-1    | [Mon May  1 18:41:49 2023] PHP 7.4.33 Development Server (http://[::]:8080) started
paperless-ngx-webserver-1  | Paperless-ngx docker container starting...
paperless-ngx-webserver-1  | Creating directory /tmp/paperless
paperless-ngx-webserver-1  | Adjusting permissions of paperless files. This may take a while.
paperless-ngx-db-1         | 
paperless-ngx-db-1         | PostgreSQL Database directory appears to contain a database; Skipping initialization
paperless-ngx-db-1         | 
paperless-ngx-db-1         | 2023-05-01 18:41:50.856 UTC [1] LOG:  starting PostgreSQL 13.10 (Debian 13.10-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
paperless-ngx-db-1         | 2023-05-01 18:41:50.856 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
paperless-ngx-db-1         | 2023-05-01 18:41:50.856 UTC [1] LOG:  listening on IPv6 address "::", port 5432
paperless-ngx-db-1         | 2023-05-01 18:41:50.862 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
paperless-ngx-db-1         | 2023-05-01 18:41:50.891 UTC [28] LOG:  database system was shut down at 2023-05-01 18:40:20 UTC
paperless-ngx-db-1         | 2023-05-01 18:41:50.956 UTC [1] LOG:  database system is ready to accept connections
paperless-ngx-webserver-1  | Waiting for PostgreSQL to start...
paperless-ngx-webserver-1  | Waiting for Redis...
paperless-ngx-webserver-1  | Connected to Redis broker.
paperless-ngx-webserver-1  | Apply database migrations...
paperless-ngx-webserver-1  | Operations to perform:
paperless-ngx-webserver-1  |   Apply all migrations: admin, auth, authtoken, contenttypes, django_celery_results, documents, guardian, paperless_mail, sessions
paperless-ngx-webserver-1  | Running migrations:
paperless-ngx-webserver-1  |   Applying django_celery_results.0001_initial... OK
paperless-ngx-webserver-1  |   Applying django_celery_results.0002_add_task_name_args_kwargs... OK
paperless-ngx-webserver-1  |   Applying django_celery_results.0003_auto_20181106_1101... OK
paperless-ngx-webserver-1  |   Applying django_celery_results.0004_auto_20190516_0412... OK
paperless-ngx-webserver-1  |   Applying django_celery_results.0005_taskresult_worker... OK
paperless-ngx-webserver-1  |   Applying django_celery_results.0006_taskresult_date_created... OK
paperless-ngx-webserver-1  |   Applying django_celery_results.0007_remove_taskresult_hidden... OK
paperless-ngx-webserver-1  |   Applying django_celery_results.0008_chordcounter... OK
paperless-ngx-webserver-1  |   Applying django_celery_results.0009_groupresult... OK
paperless-ngx-webserver-1  |   Applying django_celery_results.0010_remove_duplicate_indices... OK
paperless-ngx-webserver-1  |   Applying django_celery_results.0011_taskresult_periodic_task_name... OK
paperless-ngx-webserver-1  |   Applying documents.1026_transition_to_celery... OK
paperless-ngx-webserver-1  |   Applying documents.1027_remove_paperlesstask_attempted_task_and_more... OK
paperless-ngx-webserver-1  |   Applying documents.1028_remove_paperlesstask_task_args_and_more... OK
paperless-ngx-webserver-1  |   Applying documents.1029_alter_document_archive_serial_number... OK
paperless-ngx-webserver-1  |   Applying documents.1030_alter_paperlesstask_task_file_name... OK
paperless-ngx-webserver-1  |   Applying documents.1031_remove_savedview_user_correspondent_owner_and_more... OK
paperless-ngx-webserver-1  |   Applying documents.1032_alter_correspondent_matching_algorithm_and_more... OK
paperless-ngx-db-1         | 2023-05-01 18:41:53.635 UTC [36] ERROR:  constraint "sqlite_autoindex_documents_correspondent_1" of relation "documents_correspondent" does not exist
paperless-ngx-db-1         | 2023-05-01 18:41:53.635 UTC [36] STATEMENT:  ALTER TABLE "documents_correspondent" DROP CONSTRAINT "sqlite_autoindex_documents_correspondent_1"
paperless-ngx-webserver-1  |   Applying documents.1033_alter_documenttype_options_alter_tag_options_and_more...Traceback (most recent call last):
paperless-ngx-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
paperless-ngx-webserver-1  |     return self.cursor.execute(sql, params)
paperless-ngx-webserver-1  | psycopg2.errors.UndefinedObject: constraint "sqlite_autoindex_documents_correspondent_1" of relation "documents_correspondent" does not exist
paperless-ngx-webserver-1  | 
paperless-ngx-webserver-1  | 
paperless-ngx-webserver-1  | The above exception was the direct cause of the following exception:
paperless-ngx-webserver-1  | 
paperless-ngx-webserver-1  | Traceback (most recent call last):
paperless-ngx-webserver-1  |   File "/usr/src/paperless/src/manage.py", line 10, in <module>
paperless-ngx-webserver-1  |     execute_from_command_line(sys.argv)
paperless-ngx-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
paperless-ngx-webserver-1  |     utility.execute()
paperless-ngx-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
paperless-ngx-webserver-1  |     self.fetch_command(subcommand).run_from_argv(self.argv)
paperless-ngx-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 402, in run_from_argv
paperless-ngx-webserver-1  |     self.execute(*args, **cmd_options)
paperless-ngx-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 448, in execute
paperless-ngx-webserver-1  |     output = self.handle(*args, **options)
paperless-ngx-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 96, in wrapped
paperless-ngx-webserver-1  |     res = handle_func(*args, **kwargs)
paperless-ngx-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 349, in handle
paperless-ngx-webserver-1  |     post_migrate_state = executor.migrate(
paperless-ngx-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 135, in migrate
paperless-ngx-webserver-1  |     state = self._migrate_all_forwards(
paperless-ngx-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
paperless-ngx-webserver-1  |     state = self.apply_migration(
paperless-ngx-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
paperless-ngx-webserver-1  |     state = migration.apply(state, schema_editor)
paperless-ngx-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/migration.py", line 130, in apply
paperless-ngx-webserver-1  |     operation.database_forwards(
paperless-ngx-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/operations/fields.py", line 235, in database_forwards
paperless-ngx-webserver-1  |     schema_editor.alter_field(from_model, from_field, to_field)
paperless-ngx-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 788, in alter_field
paperless-ngx-webserver-1  |     self._alter_field(
paperless-ngx-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/schema.py", line 245, in _alter_field
paperless-ngx-webserver-1  |     super()._alter_field(
paperless-ngx-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 858, in _alter_field
paperless-ngx-webserver-1  |     self.execute(self._delete_unique_sql(model, constraint_name))
paperless-ngx-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 199, in execute
paperless-ngx-webserver-1  |     cursor.execute(sql, params)
paperless-ngx-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
paperless-ngx-webserver-1  |     return self._execute_with_wrappers(
paperless-ngx-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
paperless-ngx-webserver-1  |     return executor(sql, params, many, context)
paperless-ngx-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
paperless-ngx-webserver-1  |     return self.cursor.execute(sql, params)
paperless-ngx-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
paperless-ngx-webserver-1  |     raise dj_exc_value.with_traceback(traceback) from exc_value
paperless-ngx-webserver-1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
paperless-ngx-webserver-1  |     return self.cursor.execute(sql, params)
paperless-ngx-webserver-1  | django.db.utils.ProgrammingError: constraint "sqlite_autoindex_documents_correspondent_1" of relation "documents_correspondent" does not exist
```

### Paperless-ngx version

1.14.2

### Host OS

Debian GNU/Linux 11 (bullseye) x86_64

### Installation method

Docker - official image

### Browser

Safari

**Comment by stumpylog** [comment]
The migration for 1.9 to 1.14 using Postgres worked without issue for me.  All the migrations for 1026 to 1033 are automatic ones, made by Django, and so unlikely to have issues.

That is a very large jump in versions.  I would try going version by version and see if it works that way.

Otherwise, I would export 1.9, create 1.9 fresh and import, before trying the upgrade.

**Comment by stumpylog** [comment]
The fact the message mentions sqlite is odd as well.  Did you transition from sqlite at some point?  It makes me lean towards recreating 1.9 again from an import

**Comment by Eckii24** [comment]
Thanks for your answers @stumpylog.

I tried the suggestion to export and import my data again. After this I could upgrade to version 1.14.2 directly.
The issue is therefore solved, thanks!

You're right, I used a sqlite database before. Not sure, if I just changed the underlaying database or also restarted to whole instance...
