### ISSUE TITLE
[BUG] unable to see and clear tasks via UI

### ISSUE THREAD

**Issue by nodecentral** [paperless-ngx/paperless-ngx#3279]
### Description

I have an instance of paperless running where it is scanning multiple mail boxes for attachments , but as it’s found many instances of the same files there is now a very high failure count, and  I’m not able to access the detailed view (stuck on refresh symbol whirling) and more importantly have the ability to dismiss them. I’ve left it running for 15+mins and still not loaded.

### Steps to reproduce

Perhaps not surprisingly this can be reproduced by recreating lots of failed task 7000 +

### Webserver logs

```bash
Nothing but the 10min cycle of checking email inbox

01/05/2023 22:30:17
AttributeError: 'NoneType' object has no attribute 'lower'
01/05/2023 22:30:17
[2023-05-01 22:30:17,561] [INFO] [celery.app.trace] Task paperless_mail.tasks.process_mail_accounts[c564a71e-31df-4c3b-9153-633332402cb3] succeeded in 1.793279871926643s: 'No new documents were added.'
01/05/2023 22:40:00
[2023-05-01 22:40:00,137] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
01/05/2023 22:40:00
[2023-05-01 22:40:00,147] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[2e74bdcc-732c-417c-9f07-f54298b2d49d] received
01/05/2023 22:40:01
[2023-05-01 22:40:01,932] [ERROR] [paperless_mail] Rule Mandy.All mail: Error while processing rule: 'NoneType' object has no attribute 'lower'
01/05/2023 22:40:01
Traceback (most recent call last):
01/05/2023 22:40:01
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 290, in handle_mail_account
01/05/2023 22:40:01
    total_processed_files += self.handle_mail_rule(
01/05/2023 22:40:01
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 344, in handle_mail_rule
01/05/2023 22:40:01
    criterias = make_criterias(rule)
01/05/2023 22:40:01
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 173, in make_criterias
01/05/2023 22:40:01
    return {**criterias, **get_rule_action(rule).get_criteria()}
01/05/2023 22:40:01
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 156, in get_rule_action
01/05/2023 22:40:01
    return TagMailAction(rule.action_parameter)
01/05/2023 22:40:01
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 94, in __init__
01/05/2023 22:40:01
    if "apple:" in parameter.lower():
01/05/2023 22:40:01
AttributeError: 'NoneType' object has no attribute 'lower'
01/05/2023 22:40:02
[2023-05-01 22:40:02,020] [INFO] [celery.app.trace] Task paperless_mail.tasks.process_mail_accounts[2e74bdcc-732c-417c-9f07-f54298b2d49d] succeeded in 1.8679781469982117s: 'No new documents were added.'
01/05/2023 22:50:00
[2023-05-01 22:50:00,144] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
01/05/2023 22:50:00
[2023-05-01 22:50:00,160] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[b230ba91-ca0f-4f46-bd17-4808131a3885] received
01/05/2023 22:50:01
[2023-05-01 22:50:01,850] [ERROR] [paperless_mail] Rule.All mail: Error while processing rule: 'NoneType' object has no attribute 'lower'
01/05/2023 22:50:01
Traceback (most recent call last):
01/05/2023 22:50:01
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 290, in handle_mail_account
01/05/2023 22:50:01
    total_processed_files += self.handle_mail_rule(
01/05/2023 22:50:01
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 344, in handle_mail_rule
01/05/2023 22:50:01
    criterias = make_criterias(rule)
01/05/2023 22:50:01
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 173, in make_criterias
01/05/2023 22:50:01
    return {**criterias, **get_rule_action(rule).get_criteria()}
01/05/2023 22:50:01
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 156, in get_rule_action
01/05/2023 22:50:01
    return TagMailAction(rule.action_parameter)
01/05/2023 22:50:01
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 94, in __init__
01/05/2023 22:50:01
    if "apple:" in parameter.lower():
01/05/2023 22:50:01
AttributeError: 'NoneType' object has no attribute 'lower'
01/05/2023 22:50:01
[2023-05-01 22:50:01,935] [INFO] [celery.app.trace] Task paperless_mail.tasks.process_mail_accounts[b230ba91-ca0f-4f46-bd17-4808131a3885] succeeded in 1.7635480540338904s: 'No new documents were added.'
01/05/2023 23:00:00
[2023-05-01 23:00:00,154] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
01/05/2023 23:00:00
[2023-05-01 23:00:00,161] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[c66bc7ce-e96f-4967-8593-1969136e06ee] received
01/05/2023 23:00:01
[2023-05-01 23:00:01,988] [ERROR] [paperless_mail] Rule Mandy.All mail: Error while processing rule: 'NoneType' object has no attribute 'lower'
01/05/2023 23:00:01
Traceback (most recent call last):
01/05/2023 23:00:01
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 290, in handle_mail_account
01/05/2023 23:00:01
    total_processed_files += self.handle_mail_rule(
01/05/2023 23:00:01
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 344, in handle_mail_rule
01/05/2023 23:00:01
    criterias = make_criterias(rule)
01/05/2023 23:00:01
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 173, in make_criterias
01/05/2023 23:00:01
    return {**criterias, **get_rule_action(rule).get_criteria()}
01/05/2023 23:00:01
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 156, in get_rule_action
01/05/2023 23:00:01
    return TagMailAction(rule.action_parameter)
01/05/2023 23:00:01
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 94, in __init__
01/05/2023 23:00:01
    if "apple:" in parameter.lower():
01/05/2023 23:00:01
AttributeError: 'NoneType' object has no attribute 'lower'
01/05/2023 23:00:02
[2023-05-01 23:00:02,079] [INFO] [celery.app.trace] Task paperless_mail.tasks.process_mail_accounts[c66bc7ce-e96f-4967-8593-1969136e06ee] succeeded in 1.9123839569510892s: 'No new documents were added.'

```

### Paperless-ngx version

1.13

### Host OS

QNAPLinux

### Installation method

Docker - official image

### Browser

Safari

**Comment by shamoon** [comment]
Im not really sure what to say here, it may in fact be the case but I dont see it affecting enough users to prioritize working on.  Its not really 'expected use', I'd suggest changing your workflow to avoid generating 7k failed tasks...

**Comment by stumpylog** [comment]
You can manually remove tasks from the database:
```python
python3 manage.py shell
from documents.models import PaperlessTask
PaperlessTask.objects.all().delete()
```

Or from the admin pages.

**Comment by shamoon** [comment]
Thanks for mentioning that stumpy, I shouldn't have assumed OP knew that. Yes, for now that's the solution.

**Comment by nodecentral** [comment]
Thanks @stumpylog / @shamoon  - agreed, i wasn’t expecting this to be a regular experience , but being a community I wanted to log it because it seems when you hits a certain threshold you can lose the ability to see the progress of and clear the tasks via the UI. 

Just an idea, as i like anything to avoid going into the command line; to address this sort of issue, simply having that script available via a button on the admin page somewhere, could be a good task based [troubleshooting](**[url](https://docs.paperless-ngx.com/troubleshooting/)**) option on your page

**Comment by nodecentral** [comment]
> I’ll try to select all and delete….

OK, seems I can’t delete them all via the UI, i left it running for quite a while, but it didn’t seem to delete any .. I can do one by one, or select 100, but not select all …

**Comment by nodecentral** [comment]
It looks like it worked via the command line.
````
[~] # docker exec -it paperlessngx /bin/sh

# ls
docker  documents  locale  manage.py  paperless  paperless_mail  paperless_tesseract  paperless_text  paperless_tika  requirements.txt  setup.cfg

# python3 manage.py shell
Python 3.9.16 (main, Apr 12 2023, 06:58:15) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from documents.models import PaperlessTask
>>> PaperlessTask.objects.all().delete()
(150867, {'documents.PaperlessTask': 150867})
>>>
````
