### ISSUE TITLE
[BUG] Importing 1.13.0 export into 1.14.2 fails

### ISSUE THREAD

**Issue by Boostflow** [paperless-ngx/paperless-ngx#3288]
### Description

I currently cannot move from my 1.13 envirionment into the new 1.14.2. When I run the importer I'm thrown with the following error:

`Version mismatch: Currently 1.14.2, importing 1.13.0. Continuing, but import may fail.
Checking the manifest
Database import failed
Version mismatch: Currently 1.14.2, importing 1.13.0
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/models/options.py", line 669, in get_field
    return self.fields_map[field_name]
KeyError: 'user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/serializers/json.py", line 70, in Deserializer
    yield from PythonDeserializer(objects, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/serializers/python.py", line 130, in Deserializer
    field = Model._meta.get_field(field_name)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/options.py", line 671, in get_field
    raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: SavedView has no field named 'user'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/usr/src/paperless/src/documents/management/commands/document_importer.py", line 134, in handle
    raise e
  File "/usr/src/paperless/src/documents/management/commands/document_importer.py", line 120, in handle
    call_command("loaddata", manifest_path)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 198, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/loaddata.py", line 102, in handle
    self.loaddata(fixture_labels)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/loaddata.py", line 163, in loaddata
    self.load_label(fixture_label)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/loaddata.py", line 251, in load_label
    for obj in objects:
  File "/usr/local/lib/python3.9/site-packages/django/core/serializers/json.py", line 74, in Deserializer
    raise DeserializationError() from exc
django.core.serializers.base.DeserializationError: Problem installing fixture '/media/backup/manifest.json': 
# `

I cannot upgrade the current 1.13 deployment as truecharts on truenas has decided to create an entire new image so I have export and import.

### Steps to reproduce

1. run exporter in 1.13 `document_exporter /backup`
2. move folder over to new machine with new version installed
3. run importer in 1.14.2 envirionment `document_importer /backup`
4. error is thrown

### Webserver logs

```bash
see description
```

### Paperless-ngx version

1.13 to 1.14.2

### Host OS

Truenas Scale

### Installation method

Other (please describe above)

### Browser

Chrome

### Configuration changes

no changes

### Other

no changes

**Comment by stumpylog** [comment]
That's the reason for a message like `Version mismatch: Currently 1.14.2, importing 1.13.0. Continuing, but import may fail.`

I don't know what truecharts means, but even it's a new image, can't you simply point `image:` to the new one?
