### ISSUE TITLE
issue UnicodeEncodeError: 'utf-8' codec can't encode character '\udcb7' in position 18: surrogates not allowed

### ISSUE THREAD

**Issue by BoBBer446** [paperless-ngx/paperless-ngx#3338]
### Description

My Docker-compose file is:
```
root@rene:~# cat paperless-compose.yml
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/postgres:13
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - "8010:8000"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - /mnt/paperless_smb:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      USERMAP_UID: 1000
      USERMAP_GID: 100
      PAPERLESS_TIME_ZONE: Europe/Berlin
      PAPERLESS_SECRET_KEY: "a-secret-key"
      PAPERLESS_URL: http://localhost:8010
      PAPERLESS_CSRF_TRUSTED_ORIGINS: http://localhost:8010
      PAPERLESS_CORS_ALLOWED_HOSTS: http://localhost:8010
      PAPERLESS_ADMIN_USER: admin
      PAPERLESS_ADMIN_PASSWORD: admin
      PAPERLESS_ADMIN_MAIL: my-mail@domain.de
volumes:
  data:
  media:
  pgdata:
  redisdata:
```

on  - /mnt/paperless_smb is my nas content mountebd about fstab:
# UNCONFIGURED FSTAB FOR BASE SYSTEM
//192.168.178.146/home/Drive/Dokumente /mnt/paperless_smb cifs credentials=/etc/smb_credentials,uid=100

paperless didt search recursive, cant activate it

### Steps to reproduce

after each restart the issue on log

### Webserver logs

```bash
[2023-05-07 11:45:08,428] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/Scan 07 Apr. 23 083731.pdf to the task queue.

[2023-05-07 11:45:08,567] [ERROR] [paperless.handlers] Creating PaperlessTask failed

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/signals/handlers.py", line 535, in before_task_publish_handler

    PaperlessTask.objects.create(

  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method

    return getattr(self.get_queryset(), name)(*args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 671, in create

    obj.save(force_insert=True, using=self.db)

  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 812, in save

    self.save_base(

  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 863, in save_base

    updated = self._save_table(

  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 1006, in _save_table

    results = self._do_insert(

  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 1047, in _do_insert

    return manager._insert(

  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method

    return getattr(self.get_queryset(), name)(*args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1791, in _insert

    return query.get_compiler(using=using).execute_sql(returning_fields)

  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1660, in execute_sql

    cursor.execute(sql, params)

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute

    return self._execute_with_wrappers(

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers

    return executor(sql, params, many, context)

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute

    return self.cursor.execute(sql, params)

UnicodeEncodeError: 'utf-8' codec can't encode character '\udcb7' in position 18: surrogates not allowed

[2023-05-07 11:45:08,575] [WARNING] [paperless.management.consumer] Not consuming file /usr/src/paperless/consume/ER.xlsx: Unknown file extension.

[2023-05-07 11:45:08,575] [WARNING] [paperless.management.consumer] Not consuming file /usr/src/paperless/consume/Mappe.xlsx: Unknown file extension.

[2023-05-07 11:45:08,576] [WARNING] [paperless.management.consumer] Not consuming file /usr/src/paperless/consume/Dokument (1).docx: Unknown file extension.

[2023-05-07 11:45:08,576] [WARNING] [paperless.management.consumer] Not consuming file /usr/src/paperless/consume/Dokument.docx: Unknown file extension.

[2023-05-07 11:45:08,576] [WARNING] [paperless.management.consumer] Not consuming file /usr/src/paperless/consume/Kndigung.docx: Unknown file extension.

[2023-05-07 11:45:08,581] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: /usr/src/paperless/consume
```

### Paperless-ngx version

lastest

### Host OS

Ubuntu WSL2

### Installation method

Docker - official image

### Browser

Chrome

### Configuration changes

see above docker compose

**Comment by stumpylog** [comment]
Highly likely to be something about using WSL.  But without a sample for generating the error to look into it more, there's not much I can think of

**Comment by BoBBer446** [comment]
I don't know what information you need? paperless-ngx runs in a docker container on the wsl2. Whether it's wsl2 or a root server doesn't matter, does it? my paperless-ngx doesn't support .doc files either. I can't find a config file in the container under /usr/ to enable .doc support either. It is a bit confusing

**Comment by stumpylog** [comment]
A sample file that produces the error

**Comment by BoBBer446** [comment]
Es ist gar nicht so leicht eine Datei zu finden. ich habe 1464 Fehler beim import.
zum Beispiel hunderte Fehler:
'utf-8' codec can't encode character
die Datei ist eine .txt Datei....

Auch viele "normale" .pdf dateien können nicht eingelesen werden.

![image](https://github.com/paperless-ngx/paperless-ngx/assets/10163536/7cbe96b2-2cba-4604-a302-e669ee0f974e)
[bildquellen.txt](https://github.com/paperless-ngx/paperless-ngx/files/11455831/bildquellen.txt)

**Comment by BoBBer446** [comment]
![image](https://github.com/paperless-ngx/paperless-ngx/assets/10163536/f9f944b1-d9c5-44fc-b5a2-07ecce700b0c)

This can't be normal. So many .pdf files and .doc files and .txt files. How can it have problems? How can I retrofit this? Is there something wrong with the compose file?

**Comment by stumpylog** [comment]
The same file you provided isn't valid UTF-8.  For example on lines 5, 48 and 59, a text editor will show a ? symbol, owing to the partial symbol.  It looks like this:
![image](https://github.com/paperless-ngx/paperless-ngx/assets/797416/134fddba-f84f-4055-95b5-206846b27b47)

Looking at the bytes of the file, it looks like `Pantothens\xe4ure`, which isn't valid.

At a guess, whatever is producing this files is attempting to insert some sort of symbol, but only doing part of it, resulting in an invalid string.

Do you happen to have a PDF which also exhibits the error?
