### ISSUE TITLE
Post-Processing Script Fails Pull on Email Attachment processesing

### ISSUE THREAD

**Issue by jasper-186** [paperless-ngx/paperless-ngx#3373]
### Description

Paperless Post-Processing script cannot fetch info from the API for the consumed document, when the document is an email Attachment. 

### Steps to reproduce

A) apply post-processing script to paperless
[paperless-post-processing.py.txt](https://github.com/paperless-ngx/paperless-ngx/files/11442918/paperless-post-processing.py.txt)

1) Go to Settings>Mail
2) Add Mail Account (I'm using Gmail)
3) Add new Mail Rule
![image](https://github.com/paperless-ngx/paperless-ngx/assets/2180413/948d96f9-a410-46f1-9b55-2126360eac3a)

4) Wait for mail to fit the rule defined above, that also has an attachment.

### Webserver logs

```bash
[2023-05-09 14:20:18,584] [INFO] [paperless.consumer] Consuming Estimate 14683 from The Tree Guys, LLC.eml

[2023-05-09 14:20:18,606] [DEBUG] [paperless.consumer] Detected mime type: message/rfc822

[2023-05-09 14:20:18,713] [DEBUG] [paperless.consumer] Parser: MailDocumentParser

[2023-05-09 14:20:18,727] [DEBUG] [paperless.consumer] Parsing Estimate 14683 from The Tree Guys, LLC.eml...

[2023-05-09 14:20:18,749] [INFO] [paperless.parsing.mail] Sending content to Tika server

[2023-05-09 14:20:18,776] [INFO] [paperless.parsing.mail] Converting mail to PDF

[2023-05-09 14:20:21,265] [INFO] [paperless.parsing.mail] Converting html to PDF

[2023-05-09 14:20:23,461] [DEBUG] [paperless.consumer] Generating thumbnail for Estimate 14683 from The Tree Guys, LLC.eml...

[2023-05-09 14:20:23,493] [DEBUG] [paperless.parsing] Execute: convert -density 300 -scale 500x5000> -alpha remove -strip -auto-orient /tmp/paperless/paperless-0c_r1fc5/merged.pdf[0] /tmp/paperless/paperless-0c_r1fc5/convert.webp

[2023-05-09 14:20:24,450] [DEBUG] [paperless.classifier] Document classification model does not exist (yet), not performing automatic matching.

[2023-05-09 14:20:24,485] [DEBUG] [paperless.consumer] Saving record to database

[2023-05-09 14:20:24,530] [DEBUG] [paperless.consumer] Creation date from parse_date: 2022-05-20 16:09:14-05:00

[2023-05-09 14:20:25,997] [DEBUG] [paperless.consumer] Deleting file /tmp/paperless/paperless-ngx9gv3o76b/Estimate 14683 from The Tree Guys, LLC.eml

[2023-05-09 14:20:26,018] [DEBUG] [paperless.parsing.mail] Deleting directory /tmp/paperless/paperless-0c_r1fc5

[2023-05-09 14:20:26,028] [INFO] [paperless.consumer] Executing post-consume script /scripts/post-processing.py

[2023-05-09 14:20:26,233] [INFO] [paperless.consumer] /scripts/post-processing.py exited 0

[2023-05-09 14:20:26,245] [INFO] [paperless.consumer] Script stdout:

[2023-05-09 14:20:26,260] [INFO] [paperless.consumer] Debug Log Info

[2023-05-09 14:20:26,270] [INFO] [paperless.consumer] Document Id: 683

[2023-05-09 14:20:26,278] [INFO] [paperless.consumer] Generated File Name: 2022-05-20 office at lincolntreeguys.com Estimate 14683 from The Tree Guys, LLC.eml

[2023-05-09 14:20:26,286] [INFO] [paperless.consumer] Archive Path: /usr/src/paperless/media/documents/archive/2022/none/Estimate 14683 from The Tree Guys, LLC.pdf

[2023-05-09 14:20:26,295] [INFO] [paperless.consumer] Source Path: /usr/src/paperless/media/documents/originals/2022/none/Estimate 14683 from The Tree Guys, LLC.eml

[2023-05-09 14:20:26,303] [INFO] [paperless.consumer] Created: 2022-05-20 21:09:14+00:00

[2023-05-09 14:20:26,312] [INFO] [paperless.consumer] Added: 2023-05-09 19:20:24.559473+00:00

[2023-05-09 14:20:26,320] [INFO] [paperless.consumer] Modified: 2023-05-09 19:20:25.951566+00:00

[2023-05-09 14:20:26,328] [INFO] [paperless.consumer] Thumbnail Path: /usr/src/paperless/media/documents/thumbnails/0000683.webp

[2023-05-09 14:20:26,337] [INFO] [paperless.consumer] Download URL: /api/documents/683/download/

[2023-05-09 14:20:26,345] [INFO] [paperless.consumer] Thumbnail URL: /api/documents/683/thumb/

[2023-05-09 14:20:26,354] [INFO] [paperless.consumer] Correspondent: office at lincolntreeguys.com

[2023-05-09 14:20:26,362] [INFO] [paperless.consumer] Tags:

[2023-05-09 14:20:26,371] [INFO] [paperless.consumer] It was consumed with the passphrase None

[2023-05-09 14:20:26,379] [INFO] [paperless.consumer] Document 2022-05-20 office at lincolntreeguys.com Estimate 14683 from The Tree Guys, LLC consumption finished

[2023-05-09 14:20:26,897] [INFO] [paperless.consumer] Consuming Est_14683_from_The_Tree_Guys_LLC_11836.pdf

[2023-05-09 14:20:26,929] [DEBUG] [paperless.consumer] Detected mime type: application/pdf

[2023-05-09 14:20:26,939] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser

[2023-05-09 14:20:26,949] [DEBUG] [paperless.consumer] Parsing Est_14683_from_The_Tree_Guys_LLC_11836.pdf...

[2023-05-09 14:20:27,105] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-ngxwea5nblg/Est_14683_from_The_Tree_Guys_LLC_11836.pdf'), 'output_file': PosixPath('/tmp/paperless/paperless-qyr3rvyw/archive.pdf'), 'use_threads': True, 'jobs': 8, 'language': 'eng', 'output_type': 'pdfa', 'progress_bar': False, 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-qyr3rvyw/sidecar.txt')}

[2023-05-09 14:20:27,739] [DEBUG] [paperless.parsing.tesseract] Incomplete sidecar file: discarding.

[2023-05-09 14:20:27,813] [DEBUG] [paperless.consumer] Generating thumbnail for Est_14683_from_The_Tree_Guys_LLC_11836.pdf...

[2023-05-09 14:20:27,843] [DEBUG] [paperless.parsing] Execute: convert -density 300 -scale 500x5000> -alpha remove -strip -auto-orient /tmp/paperless/paperless-qyr3rvyw/archive.pdf[0] /tmp/paperless/paperless-qyr3rvyw/convert.webp

[2023-05-09 14:20:29,460] [DEBUG] [paperless.classifier] Document classification model does not exist (yet), not performing automatic matching.

[2023-05-09 14:20:29,491] [DEBUG] [paperless.consumer] Saving record to database

[2023-05-09 14:20:29,514] [DEBUG] [paperless.consumer] Creation date from parse_date: 2022-05-17 00:00:00-05:00

[2023-05-09 14:20:30,380] [DEBUG] [paperless.consumer] Deleting file /tmp/paperless/paperless-ngxwea5nblg/Est_14683_from_The_Tree_Guys_LLC_11836.pdf

[2023-05-09 14:20:30,402] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-qyr3rvyw

[2023-05-09 14:20:30,412] [INFO] [paperless.consumer] Executing post-consume script /scripts/post-processing.py

[2023-05-09 14:20:41,189] [INFO] [paperless.consumer] /scripts/post-processing.py exited 1

[2023-05-09 14:20:41,223] [INFO] [paperless.consumer] Script stdout:

[2023-05-09 14:20:41,250] [INFO] [paperless.consumer] Debug Log Info

[2023-05-09 14:20:41,274] [INFO] [paperless.consumer] Document Id: 684

[2023-05-09 14:20:41,292] [INFO] [paperless.consumer] Generated File Name: 2022-05-17 office at lincolntreeguys.com Est_14683_from_The_Tree_Guys_LLC_11836.pdf

[2023-05-09 14:20:41,324] [INFO] [paperless.consumer] Archive Path: /usr/src/paperless/media/documents/archive/2022/none/Est_14683_from_The_Tree_Guys_LLC_11836.pdf

[2023-05-09 14:20:41,342] [INFO] [paperless.consumer] Source Path: /usr/src/paperless/media/documents/originals/2022/none/Est_14683_from_The_Tree_Guys_LLC_11836.pdf

[2023-05-09 14:20:41,374] [INFO] [paperless.consumer] Created: 2022-05-17 05:00:00+00:00

[2023-05-09 14:20:41,393] [INFO] [paperless.consumer] Added: 2023-05-09 19:20:29.546016+00:00

[2023-05-09 14:20:41,424] [INFO] [paperless.consumer] Modified: 2023-05-09 19:20:30.327759+00:00

[2023-05-09 14:20:41,442] [INFO] [paperless.consumer] Thumbnail Path: /usr/src/paperless/media/documents/thumbnails/0000684.webp

[2023-05-09 14:20:41,474] [INFO] [paperless.consumer] Download URL: /api/documents/684/download/

[2023-05-09 14:20:41,493] [INFO] [paperless.consumer] Thumbnail URL: /api/documents/684/thumb/

[2023-05-09 14:20:41,525] [INFO] [paperless.consumer] Correspondent: office at lincolntreeguys.com

[2023-05-09 14:20:41,543] [INFO] [paperless.consumer] Tags:

[2023-05-09 14:20:41,575] [INFO] [paperless.consumer] It was consumed with the passphrase None

[2023-05-09 14:20:41,594] [INFO] [paperless.consumer] parsed env document id 684

[2023-05-09 14:20:41,625] [WARNING] [paperless.consumer] Script stderr:

[2023-05-09 14:20:41,635] [WARNING] [paperless.consumer] Traceback (most recent call last):

[2023-05-09 14:20:41,650] [WARNING] [paperless.consumer]   File "/scripts/post-processing.py", line 107, in <module>

[2023-05-09 14:20:41,660] [WARNING] [paperless.consumer]     doc_info_resp.raise_for_status()

[2023-05-09 14:20:41,675] [WARNING] [paperless.consumer]   File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status

[2023-05-09 14:20:41,685] [WARNING] [paperless.consumer]     raise HTTPError(http_error_msg, response=self)

[2023-05-09 14:20:41,693] [WARNING] [paperless.consumer] requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://localhost:8000/api/documents/684/

[2023-05-09 14:20:41,708] [ERROR] [paperless.consumer] Error while executing post-consume script: Command '['/scripts/post-processing.py', '684', '2022-05-17 office at lincolntreeguys.com Est_14683_from_The_Tree_Guys_LLC_11836.pdf', '/usr/src/paperless/media/documents/originals/2022/none/Est_14683_from_The_Tree_Guys_LLC_11836.pdf', '/usr/src/paperless/media/documents/thumbnails/0000684.webp', '/api/documents/684/download/', '/api/documents/684/thumb/', 'office at lincolntreeguys.com', '']' returned non-zero exit status 1.

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/consumer.py", line 274, in run_post_consume_script

    completed_proc.check_returncode()

  File "/usr/local/lib/python3.9/subprocess.py", line 460, in check_returncode

    raise CalledProcessError(self.returncode, self.args, self.stdout,

subprocess.CalledProcessError: Command '['/scripts/post-processing.py', '684', '2022-05-17 office at lincolntreeguys.com Est_14683_from_The_Tree_Guys_LLC_11836.pdf', '/usr/src/paperless/media/documents/originals/2022/none/Est_14683_from_The_Tree_Guys_LLC_11836.pdf', '/usr/src/paperless/media/documents/thumbnails/0000684.webp', '/api/documents/684/download/', '/api/documents/684/thumb/', 'office at lincolntreeguys.com', '']' returned non-zero exit status 1.
```

### Paperless-ngx version

1.14.4

### Host OS

Linux 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux

### Installation method

Docker - official image

### Configuration changes

Environment Vars:

**Comment by jasper-186** [comment]
Configuration Changes:
Environment Variables:
 # Paperless Configs
  - name: PAPERLESS_DATE_ORDER
    value: "MDY"
  - name: PAPERLESS_FILENAME_DATE_ORDER
    value: "YMD"
  - name: PAPERLESS_FILENAME_FORMAT
    value: "{created_year}/{document_type}/{title}"
  - name: PAPERLESS_POST_CONSUME_SCRIPT
    value: "/scripts/post-processing.py"

  # Dont use inotify as the Consume folder is SMB based, instead poll for the documents
  - name: PAPERLESS_CONSUMER_POLLING
    value: "60"         
  - name: PAPERLESS_CONSUMER_DELETE_DUPLICATES
    value: "1"         
  - name: PAPERLESS_CONSUMER_RECURSIVE
    value: "1"
  - name: PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS
    value: "1"
    
 PS. Sorry meant to put this in the ticket, but accidentally hit "enter" and submitted before completing that field
