### ISSUE TITLE
[BUG] 500 internal server error when frontend requests `GET /api/documents/1240/suggestions/`

### ISSUE THREAD

**Issue by MarcelBochtler** [paperless-ngx/paperless-ngx#3392]
### Description

When first accessing a document after restarting Paperless, the UI displays this error:
![image](https://github.com/paperless-ngx/paperless-ngx/assets/4022103/f663c77b-96d1-4188-bd10-251da15b2f14)

One request failed:
![image](https://github.com/paperless-ngx/paperless-ngx/assets/4022103/c8f05b5c-5ec0-4968-bf55-26abda1ab737)

I can reproduce this with multiple different documents, every time I restart the container.
After seeing this error once, this document and others can be opened without any error message.

I've only seen this error occur in paperless-ngx 1.14.4, It did not exist in versions before.

### Steps to reproduce

1. Navigate to the Paperless dashboard
2. Restart the Paperless Docker container. I can only reproduce this when the container started fresh.
3. Wait until Paperless started.
4. Change to the documents list in the UI.
5. Open any document from the list.
6. You'll get the UI error message, and a 500 response from `GET /api/documents/1240/suggestions/`

### Webserver logs

```bash
2023-05-14 14:33:29,785 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-05-14 14:33:29,785 INFO success: celery entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-05-14 14:33:29,785 INFO success: celery-beat entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-05-14 14:33:29,785 INFO success: consumer entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[2023-05-14 14:33:43,669] [ERROR] [django.request] Internal Server Error: /api/documents/1240/suggestions/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 486, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = await get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
  File "/usr/local/lib/python3.9/site-packages/asgiref/current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/src/paperless/src/documents/views.py", line 434, in suggestions
    c.id for c in match_correspondents(doc, classifier, request.user)
  File "/usr/src/paperless/src/documents/matching.py", line 23, in match_correspondents
    pred_id = classifier.predict_correspondent(document.content) if classifier else None
  File "/usr/src/paperless/src/documents/classifier.py", line 363, in predict_correspondent
    X = self.data_vectorizer.transform([self.preprocess_content(content)])
  File "/usr/src/paperless/src/documents/classifier.py", line 348, in preprocess_content
    self._stop_words = set(stopwords.words(settings.NLTK_LANGUAGE))
  File "/usr/local/lib/python3.9/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/usr/local/lib/python3.9/site-packages/nltk/corpus/util.py", line 95, in __load
    args, kwargs = self.__args, self.__kwargs
AttributeError: 'WordListCorpusReader' object has no attribute '_LazyCorpusLoader__args'
```

### Paperless-ngx version

1.14.4

### Host OS

unRAID 6.11.5 behind an nginx reverse proxy

### Installation method

Docker - official image

### Browser

Firefox

### Configuration changes

PAPERLESS_OCR_LANGUAGE, PAPERLESS_FILENAME_FORMAT, PAPERLESS_TIME_ZONE, URL, PAPERLESS_EMAIL_TASK_CRON

**Comment by shamoon** [comment]
Hmm, I cant reproduce this. There looks to be an issue with nltk data, have you tried re-creating (not just restarting) the container? It should download the data automatically, perhaps there was an issue there. And what does `ls /usr/share/nltk_data` show?

**Comment by MarcelBochtler** [comment]
Yes, I also tried to re-create the container. Same result.

> And what does `ls /usr/share/nltk_data` show?

```
root@56a8c02f52bd:/usr/src/paperless/src# ls /usr/share/nltk_data
corpora  stemmers  tokenizers
```

**Comment by shamoon** [comment]
The only information I can find about something like this online has to do with concurrent threads using the nltk data. Im not entirely clear why that would be happening and odd this seems isolated.

Does running `document_create_classifier` make a difference?

Disabling NLTK would fix this for you https://docs.paperless-ngx.com/configuration/#software_tweaks (`PAPERLESS_ENABLE_NLTK=0`) which obviously just disables that feature.

**Comment by stumpylog** [comment]
Hm, no changes between .4 and the earlier versions about the NLTK processing.  All the image data is still baked into the image at build time.

**Comment by MarcelBochtler** [comment]
> Does running document_create_classifier make a difference?

Unfortunately, it doesn't.
What I tried:
- Restart the paperless container
- Wait until paperless is started
- run `docker exec -i paperless-ngx document_create_classifier`
- Do the same steps as described above, and it causes the same issue.


> Disabling NLTK would fix this for you https://docs.paperless-ngx.com/configuration/#software_tweaks (`PAPERLESS_ENABLE_NLTK=0`) which obviously just disables that feature.

Yes that fixes it. But I'd like to keep the feature.

I additionally set up a completely fresh Paperless-ngx instance with a different `media` and `data` directory.
I uploaded a single document, and I cannot reproduce this issue on that instance.

**Comment by MarcelBochtler** [comment]
Same issue on 1.14.5, but the error message in the UI gets more verbose:
![image](https://github.com/paperless-ngx/paperless-ngx/assets/4022103/ed8c29a5-0934-4810-915f-e53bd6732587)

**Comment by MarcelBochtler** [comment]
> I additionally set up a completely fresh Paperless-ngx instance with a different media and data directory.
I uploaded a single document, and I cannot reproduce this issue on that instance.

Pointing that new instance to the existing `media` and `data` directory, causes the error to reappear.

**Comment by stumpylog** [comment]
Very strange indeed.  All I can image is some sort of corrupted data, either in the classifier model or the saved data, which some how persisted.  Glad it seems to be alright now.

**Comment by MarcelBochtler** [comment]
Unfortunately, the issue is back today :(
