### ISSUE TITLE
[BUG] ImportError: cannot import name 'IpWare' from 'ipware'

### ISSUE THREAD

**Issue by amo13** [paperless-ngx/paperless-ngx#3403]
### Description

Upgrading to the just released version 1.14.5 throws this error when trying to run the migrations. 

```
Traceback (most recent call last):
  File "/usr/bin/paperless-manage", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.11/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.11/site-packages/django/core/management/__init__.py", line 420, in execute
    django.setup()
  File "/usr/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/python3.11/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/django/apps/config.py", line 123, in create
    mod = import_module(mod_path)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/share/paperless/src/paperless/apps.py", line 4, in <module>
    from paperless.signals import handle_failed_login
  File "/usr/share/paperless/src/paperless/signals.py", line 4, in <module>
    from ipware import IpWare
ImportError: cannot import name 'IpWare' from 'ipware' (/usr/lib/python3.11/site-packages/ipware/__init__.py)
```

I downgrade back to 1.14.4 (nothing else changed, no changes with installed dependencies) and the migration command runs fine.

### Steps to reproduce

1. Run migration command: everything is fine
2. Upgrade paperless-ngx to 1.14.5
3. Run migration command again: missing ipware dependency somehow

### Webserver logs

```bash
irrelevant
```

### Browser logs

```bash
irrelevant
```

### Paperless-ngx version

1.14.5

### Host OS

Archlinux

### Installation method

Bare metal

### Browser

Terminal

### Configuration changes

no changes

**Comment by stumpylog** [comment]
I'd suggest re-creating your virtual environment.  Or pruning unused libraries from it, before installing the upgrade.  This is because django-ipware calls itself ipware and ipware calls itself ipware.  Removing django-ipware will resolve it.

**Comment by stumpylog** [comment]
I've added a note to the bare metal upgrade instruction about this being a possible case to encounter.

**Comment by amo13** [comment]
Good idea! Just out of curiosity: why moving ipware out of django?

**Comment by stumpylog** [comment]
django-ipware is being deprecated, the author created ipware to replace it more generally instead.  It also wasn't returning the correct IP, at least in some setups, while the new one looked correct in more configurations
