### ISSUE TITLE
[BUG] Storing SQLite on SMB Share results in locked Database

### ISSUE THREAD

**Issue by Gandalf1783** [paperless-ngx/paperless-ngx#3492]
### Description

It seems like if you put the directory to Store the SQLite Database onto a SMB share, it fails with the following log:

```
Pulling broker    ... done
Pulling webserver ... done
Starting paperless_broker_1 ... done
Paperless-ngx docker container starting...
Creating directory /usr/src/paperless/data/index
Creating directory /usr/src/paperless/media/documents
Creating directory /usr/src/paperless/media/documents/originals
Creating directory /usr/src/paperless/media/documents/thumbnails
Creating directory /tmp/paperless
Adjusting permissions of paperless files. This may take a while.
Waiting for Redis...
Connected to Redis broker.
Apply database migrations...
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, django_celery_results, documents, guardian, paperless_mail, sessions
Running migrations:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 306, in _commit
    return self.connection.commit()
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 70, in ensure_schema
    editor.create_model(self.Migration)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/sqlite3/schema.py", line 39, in __exit__
    super().__exit__(exc_type, exc_value, traceback)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 166, in __exit__
    self.atomic.__exit__(exc_type, exc_value, traceback)
  File "/usr/local/lib/python3.9/site-packages/django/db/transaction.py", line 262, in __exit__
    connection.commit()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 330, in commit
    self._commit()
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 306, in _commit
    return self.connection.commit()
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 306, in _commit
    return self.connection.commit()
django.db.utils.OperationalError: database is locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 349, in handle
    post_migrate_state = executor.migrate(
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 107, in migrate
    self.recorder.ensure_schema()
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 72, in ensure_schema
    raise MigrationSchemaMissing(
django.db.migrations.exceptions.MigrationSchemaMissing: Unable to create the django_migrations table (database is locked)
```

### Steps to reproduce

1. Docker and Docker-Compose are preinstalled as needed.
2. Mount a smb share (in my case at /home/pi/paperless-store/)
3. I have used the Docker install script on a Raspi 4 running default Debian Bullseye.
4. Run the script (My Options: https://[redacted].[tld]/, Port 8000, Timezone: Europe/Berlin, sqlite as DB, Dont use Apache Tika, OCR Lang: deu, UID and GID: 1000)
5. Folder Configuration:
5.1. Target-Folder: /home/pi/paperless-store/
5.2. Consume-Folder: /home/pi/paperless-store/consume
5.3. Media-Folder: /home/pi/paperless-store/media
5.4. Data-Folder: /home/pi/paperless-store/data
6. Provide the credentials for an account
7. Let the Script install
8. Boom - Fails with a locked database

There were no directory except "consume" in my paperless-store directory.

### Webserver logs

```bash
None
```

### Browser logs

```bash
None
```

### Paperless-ngx version

? - Could not install

### Host OS

Raspi 4 - Debian (aarch64)

### Installation method

Other (please describe above)

**Comment by shamoon** [comment]
SQLite is not reliable over network share, this isn’t really a bug in our code, I don’t think.

See https://github.com/paperless-ngx/paperless-ngx/discussions/736

**Comment by stumpylog** [comment]
You may be able to resolve it with certain mount options (such as `nobrl`), but you'll always be running the risk of data corruption and contention.

If you want your database to live elsewhere, I would suggest using Postgres or Mariadb on the server, rather than attempting SQLite
