### ISSUE TITLE
[BUG] Docker might not wait long enough for Postgres first time setup

### ISSUE THREAD

**Issue by rotten777** [paperless-ngx/paperless-ngx#3568]
### Description

Running through the docker compose setup, I left the default (pgsql) db backend as the option and it fails. Same exact options elsewhere but choosing sqlite and it functions flawlessly. 

Running in a container on Ubuntu 22.04

### Steps to reproduce

# container setup
lxc launch images:ubuntu/22.04 paperless-ngx
lxc config set paperless-ngx security.nesting=true security.syscalls.intercept.mknod=true security.syscalls.intercept.setxattr=true
lxc exec paperless-ngx bash

hostnamectl set-hostname paperless.domain.internal
apt update && apt install -y ca-certificates curl gnupg wget

install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
chmod a+r /etc/apt/keyrings/docker.gpg

echo \
  "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
  tee /etc/apt/sources.list.d/docker.list > /dev/null

apt update && apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

useradd -m paperless
usermod -aG docker paperless
cd /home/paperless/

sudo -u paperless bash -c "$(curl -L https://raw.githubusercontent.com/paperless-ngx/paperless-ngx/main/install-paperless-ngx.sh)"

### Webserver logs

```bash
#############################################
###   paperless-ngx docker installation   ###
#############################################

This script will download, configure and start paperless-ngx.

1. Application configuration
============================

The URL paperless will be available at. This is required if the
installation will be accessible via the web, otherwise can be left blank.
Example: https://paperless.example.com

URL []:

The port on which the paperless webserver will listen for incoming
connections.

Port [8000]:

Paperless requires you to configure the current time zone correctly.
Otherwise, the dates of your documents may appear off by one day,
depending on where you are on earth.
Example: Europe/Berlin
See here for a list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

Current time zone [Etc/UTC]: America/New_York

Database backend: PostgreSQL, MariaDB, and SQLite are available. Use PostgreSQL
if unsure. If you're running on a low-power device such as Raspberry
Pi, use SQLite to save resources.

Database backend (postgres sqlite mariadb) [postgres]:

Paperless is able to use Apache Tika to support Office documents such as
Word, Excel, Powerpoint, and Libreoffice equivalents. This feature
requires more resources due to the required services.

Enable Apache Tika? (yes no) [no]:

Specify the default language that most of your documents are written in.
Use ISO 639-2, (T) variant language codes:
https://www.loc.gov/standards/iso639-2/php/code_list.php
Common values: eng (English) deu (German) nld (Dutch) fra (French)
This can be a combination of multiple languages such as deu+eng

OCR language [eng]:

Specify the user id and group id you wish to run paperless as.
Paperless will also change ownership on the data, media and consume
folder to the specified values, so it's a good idea to supply the user id
and group id of your unix user account.
If unsure, leave default.

User ID [1001]:
Group ID [1001]:

2. Folder configuration
=======================

The target folder is used to store the configuration files of
paperless. You can move this folder around after installing paperless.
You will need this folder whenever you want to start, stop, update or
maintain your paperless instance.

Target folder [/home/paperless/paperless-ngx]:

The consume folder is where paperless will search for new documents.
Point this to a folder where your scanner is able to put your scanned
documents.

CAUTION: You must specify an absolute path starting with / or a relative
path starting with ./ here. Examples:
  /mnt/consume
  ./consume

Consume folder [/home/paperless/paperless-ngx/consume]:

The media folder is where paperless stores your documents.
Leave empty and docker will manage this folder for you.
Docker usually stores managed folders in /var/lib/docker/volumes.

CAUTION: If specified, you must specify an absolute path starting with /
or a relative path starting with ./ here.

Media folder []:

The data folder is where paperless stores other data, such as your
search index and other data.
As with the media folder, leave empty to have this managed by docker.

CAUTION: If specified, you must specify an absolute path starting with /
or a relative path starting with ./ here.

Data folder []:

The database folder, where your database stores its data.
Leave empty to have this managed by docker.

CAUTION: If specified, you must specify an absolute path starting with /
or a relative path starting with ./ here.

Database folder []:

3. Login credentials
====================

Specify initial login credentials. You can change these later.
A mail address is required, however it is not used in paperless. You don't
need to provide an actual mail address.

Paperless username [paperless]:
Paperless password:
Paperless password (again):
Email [paperless@localhost]:

Summary
=======

Target folder: /home/paperless/paperless-ngx
Consume folder: /home/paperless/paperless-ngx/consume
Media folder: Managed by docker
Data folder: Managed by docker
Database folder: Managed by docker

URL:
Port: 8000
Database: postgres
Tika enabled: no
OCR language: eng
User id: 1001
Group id: 1001

Paperless username: paperless
Paperless email: paperless@localhost

Press any key to install.

Installing paperless...

--2023-06-10 14:50:34--  https://raw.githubusercontent.com/paperless-ngx/paperless-ngx/main/docker/compose/docker-compose.postgres.yml
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2221 (2.2K) [text/plain]
Saving to: ‘docker-compose.yml’

docker-compose.yml     100%[==========================>]   2.17K  --.-KB/s    in 0s

2023-06-10 14:50:34 (8.59 MB/s) - ‘docker-compose.yml’ saved [2221/2221]

--2023-06-10 14:50:34--  https://raw.githubusercontent.com/paperless-ngx/paperless-ngx/main/docker/compose/.env
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.109.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 31 [text/plain]
Saving to: ‘.env’

.env                   100%[==========================>]      31  --.-KB/s    in 0s

2023-06-10 14:50:34 (949 KB/s) - ‘.env’ saved [31/31]

[+] Pulling 38/38
 ✔ webserver 18 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                  60.3s
   ✔ f03b40093957 Pull complete                                                      8.2s
   ✔ 05c2151a829c Pull complete                                                      9.0s
   ✔ 413e4e4760ae Pull complete                                                     12.0s
   ✔ 92ec8b395aa1 Pull complete                                                     12.2s
   ✔ 295d2f1818b0 Pull complete                                                     13.9s
   ✔ b133fa728c50 Pull complete                                                     28.7s
   ✔ d72f3abf55de Pull complete                                                     29.2s
   ✔ 029ca5b5aff5 Pull complete                                                     29.2s
   ✔ 7c03b6f293a0 Pull complete                                                     29.3s
   ✔ 52da515747fe Pull complete                                                     29.4s
   ✔ d0bbb4240ec5 Pull complete                                                     29.5s
   ✔ 2bc9b38f173a Pull complete                                                     30.8s
   ✔ 4f4fb700ef54 Pull complete                                                     30.9s
   ✔ f4fc884f62b0 Pull complete                                                     31.0s
   ✔ 4cf2f6a4d1c9 Pull complete                                                     52.7s
   ✔ e0ce1990bbe2 Pull complete                                                     53.9s
   ✔ a4fc609c12db Pull complete                                                     56.2s
   ✔ 36442043454e Pull complete                                                     59.1s
 ✔ db 12 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                               25.8s
   ✔ 9d674c93414d Pull complete                                                      8.9s
   ✔ de781e8e259a Pull complete                                                     10.2s
   ✔ 5ea6efaf51f6 Pull complete                                                     10.5s
   ✔ b078d5f4ac82 Pull complete                                                     12.7s
   ✔ 97f84fb2a918 Pull complete                                                     13.2s
   ✔ 5a6bf2f43fb8 Pull complete                                                     13.3s
   ✔ f1a40e88fea4 Pull complete                                                     13.3s
   ✔ 753543888088 Pull complete                                                     23.5s
   ✔ 58c8d2771e3b Pull complete                                                     24.2s
   ✔ 7eaef0c50f45 Pull complete                                                     24.3s
   ✔ 336b5ddd23ec Pull complete                                                     24.4s
   ✔ f6e00973c54b Pull complete                                                     24.5s
 ✔ broker 5 layers [⣿⣿⣿⣿⣿]      0B/0B      Pulled                                   11.6s
   ✔ 8db26c5e8435 Pull complete                                                      8.4s
   ✔ 37e84c7a626f Pull complete                                                      8.7s
   ✔ 806c192e0375 Pull complete                                                     10.0s
   ✔ 08769906aa59 Pull complete                                                     10.1s
   ✔ 635073d8ccd5 Pull complete                                                     10.2s
[+] Building 0.0s (0/0)
[+] Creating 7/7
 ✔ Network paperless_default     Created                                             0.2s
 ✔ Volume "paperless_redisdata"  Created                                             0.0s
 ✔ Volume "paperless_pgdata"     Created                                             0.0s
 ✔ Volume "paperless_data"       Created                                             0.0s
 ✔ Volume "paperless_media"      Created                                             0.0s
 ✔ Container paperless-broker-1  Created                                             0.1s
 ✔ Container paperless-db-1      Created                                             0.1s
[+] Running 2/2
 ✔ Container paperless-broker-1  Started                                             0.8s
 ✔ Container paperless-db-1      Started                                             0.8s
[+] Building 0.0s (0/0)
Paperless-ngx docker container starting...
Mapping UID and GID for paperless:paperless to 1001:1001
Creating directory /usr/src/paperless/data/index
Creating directory /usr/src/paperless/media/documents
Creating directory /usr/src/paperless/media/documents/originals
Creating directory /usr/src/paperless/media/documents/thumbnails
Creating directory /tmp/paperless
Adjusting permissions of paperless files. This may take a while.
Waiting for PostgreSQL to start...
Waiting for Redis...
Connected to Redis broker.
Apply database migrations...
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 263, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 215, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
        Is the server running on host "db" (172.18.0.2) and accepting
        TCP/IP connections on port 5432?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 114, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/loader.py", line 58, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/loader.py", line 235, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 81, in applied_migrations
    if self.has_table():
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 57, in has_table
    with self.connection.cursor() as cursor:
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 323, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 299, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 263, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 215, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not connect to server: Connection refused
        Is the server running on host "db" (172.18.0.2) and accepting
        TCP/IP connections on port 5432?

root@paperless-ngx:/home/paperless# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:f3:7f:43:52 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
3: br-5174ea71d538: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:8b:3f:7d:25 brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.1/16 brd 172.18.255.255 scope global br-5174ea71d538
       valid_lft forever preferred_lft forever
    inet6 fe80::42:8bff:fe3f:7d25/64 scope link
       valid_lft forever preferred_lft forever
5: veth5a00886@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-5174ea71d538 state UP group default
    link/ether 0a:03:2e:55:20:e2 brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::803:2eff:fe55:20e2/64 scope link
       valid_lft forever preferred_lft forever
7: veth0165e7d@if6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-5174ea71d538 state UP group default
    link/ether f6:c3:e0:92:14:b7 brd ff:ff:ff:ff:ff:ff link-netnsid 2
    inet6 fe80::f4c3:e0ff:fe92:14b7/64 scope link
       valid_lft forever preferred_lft forever
47: eth0@if48: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:16:3e:8f:be:7d brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 192.168.1.133/24 metric 100 brd 192.168.1.255 scope global dynamic eth0
       valid_lft 6801sec preferred_lft 6801sec
    inet6 fe80::216:3eff:fe8f:be7d/64 scope link
       valid_lft forever preferred_lft forever
```

### Paperless-ngx version

1.15.1

### Host OS

Ubuntu 22.04

### Installation method

Docker - official image

**Comment by shamoon** [comment]
Seems this is a docker networking issue specific to your setup, perhaps something to do with lxc? But you can see there it can’t reach the db container.

In general, this works for most but our compose / script can’t account for every single setup.

**Comment by stumpylog** [comment]
I see no logs from the db container itself.  It's probably doing something at startup still and not really ready, even if it reported so once.  Variations from the disks to cpu might affect how long it's going to take

  I'd wager simply starting the containers again would work totally fine

**Comment by stumpylog** [comment]
It's probably just from this: docker-library/postgres/issues/146

The webserver will restart momentarily and find the DB is now initialized and truly ready, and I don't know that I like adding extra startup time for a problem which only will happen once on a fresh startup.

**Comment by hdodenhof** [comment]
This also happened to me with a fairly standard setup, not using lxc.

> I'd wager simply starting the containers again would work totally fine

It did in my case. However, the initial user creation from the install script never succeeded, so I ended up with a running system but no user account. Running `createsuperuser` myself did the trick, but being in a broken state after running the install script was a bit of a bummer.

**Comment by stumpylog** [comment]
Hm, I can see how that would happen.  I typically let the auto user create handle things, which happens later in the startup and so the DB is ready.

**Comment by jmarchewka** [comment]
I am having a similar issue - Fresh Ubuntu 22.04 minimized serve, cloned paperless-nix from repo, ran install-paperless-ngx.sh. Install seemed to go alright but it doesn't seem to start. The webserver container and db container keep restarting. I am getting this error from the db container:

initdb: error: could not change permissions of directory "/var/lib/postgresql/data": Operation not permitted.

$ docker --version
Docker version 20.10.21, build 20.10.21-0ubuntu1~22.04.3
$ docker-compose --version
docker-compose version 1.29.2, build unknown

**Comment by stumpylog** [comment]
> initdb: error: could not change permissions of directory "/var/lib/postgresql/data": Operation not permitted.

That's a different issue and related to your permissions.  It's not something paperless does anything with.

**Comment by stumpylog** [comment]
I have been looking at this more, but it's a somewhat complex timing issue.  

Just adding additional waiting isn't always enough, since the DB can take a long enough time depending on the hardware it may still be in the first startup when the second wait is hit.

There's also no way to start and then restart that container alone to ensure the DB is initialized first.

Really, it's a bit of a chicken and egg
