### ISSUE TITLE
[BUG] Unexpected exception in receive task

### ISSUE THREAD

**Issue by ginkel** [paperless-ngx/paperless-ngx#3594]
### Description

Paperless stops consuming files from the consume directory with the following exception:

```
[2023-06-15 17:18:48,327] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/20230615_171844.pdf to the task queue.
[2023-06-15 17:18:48,329] [ERROR] [paperless.handlers] Creating PaperlessTask failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 301, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 269, in create_cursor
    cursor = self.connection.cursor()
psycopg2.InterfaceError: connection already closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/signals/handlers.py", line 535, in before_task_publish_handler
    PaperlessTask.objects.create(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 671, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 812, in save
    self.save_base(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 863, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 1006, in _save_table
    results = self._do_insert(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 1047, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1791, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1658, in execute_sql
    with self.connection.cursor() as cursor:
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 323, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 301, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 301, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 269, in create_cursor
    cursor = self.connection.cursor()
django.db.utils.InterfaceError: connection already closed
[2023-06-15 17:19:43,997] [ERROR] [channels_redis.pubsub] Unexpected exception in receive task
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/channels_redis/pubsub.py", line 297, in _do_receiving
    message = await self._pubsub.get_message(
  File "/usr/local/lib/python3.9/site-packages/redis/asyncio/client.py", line 927, in get_message
    response = await self.parse_response(block=(timeout is None), timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/redis/asyncio/client.py", line 804, in parse_response
    response = await self._execute(
  File "/usr/local/lib/python3.9/site-packages/redis/asyncio/client.py", line 784, in _execute
    return await conn.retry.call_with_retry(
  File "/usr/local/lib/python3.9/site-packages/redis/asyncio/retry.py", line 62, in call_with_retry
    await fail(error)
  File "/usr/local/lib/python3.9/site-packages/redis/asyncio/client.py", line 773, in _disconnect_raise_connect
    raise error
  File "/usr/local/lib/python3.9/site-packages/redis/asyncio/retry.py", line 59, in call_with_retry
    return await do()
  File "/usr/local/lib/python3.9/site-packages/redis/asyncio/connection.py", line 861, in read_response
    raise ConnectionError(
redis.exceptions.ConnectionError: Error while reading from redis:6379 : (32, 'Broken pipe')
```

This has been reported before in https://github.com/paperless-ngx/paperless-ngx/discussions/2787.

Today I have figured out what triggered the issue. I am running Paperless-ngx in Docker with Postgres and Redis in sidecar containers. The issue popped up after the Redis container had been updated to a new version and consequently restarted. Paperless seems to fail re-establishing a new connection in that case.

### Steps to reproduce

1. Deploy Paperless-ngx as Docker container w/ Postgres and Redis as sidecar containers
2. Update the redis container
3. Watch Paperless fail consuming new files

### Webserver logs

```bash
See description
```

### Paperless-ngx version

1.15.1

### Host OS

Ubuntu 20.04

### Installation method

Docker - official image

**Comment by stumpylog** [comment]
I can't say I see this as a bug.  If you're updating and restarting other containers, I wouldn't expect another container to "just know" about that and handle it.  I would expect a restart of the paperless container as well.

I'd also point out we're not the code that handles connections, either to the DB or to Redis.  The tracebacks are all into other libraries...

**Comment by ginkel** [comment]
I (and many others) use [watchtower](https://github.com/containrrr/watchtower) to auto-update Docker containers, so no manual operation is involved in the update.

Apart from that most software I know handles a temporary database outage gracefully. Patterns to achieve this are:

1) Detect that the connection is bad and reconnect
2) Detect that the connection is bad and exit (to be automatically restarted by Docker/systemd/...)

**Comment by stumpylog** [comment]
An exception when creating the paperless is task [is handled](https://github.com/paperless-ngx/paperless-ngx/blob/ee88140fdd8bceb0f82db03ed723fae9a7beaf0b/src/documents/signals/handlers.py#L515).  It's merely logged for information.  Paperless continues the consumption as normal.

**Comment by ginkel** [comment]
Unfortunately, this does not seem to be the case for me. The PDFs just sit in the consumption directory forever until I manually restart its Docker container.

So, somehow the bad connection probably needs to be invalidated or it will be reused over and over again.

https://stackoverflow.com/a/62632743/43575 may have hints for a possible solution/workaround, but I didn't yet have a look at the Paperless implementation yet.

**Comment by shamoon** [comment]
I cant actually recreate this though. Destroying, re-creating, updating my redis or Postgres containers doesn't seem to be a problem as long as they're up and running at the correct hostname when tasks are sent over.

Also, this isn't really something we control directly, db abstraction is handled by Django and nothing in their docs makes me think we're doing things in a way that would prevent typical behavior. https://docs.djangoproject.com/en/dev/ref/databases/#persistent-connections

> In detail, Django automatically opens a connection to the database whenever it needs one and doesn’t have one already — either because this is the first connection, or because the previous connection was closed.

Perhaps its something specific to your deployment or even the platform

**Comment by ginkel** [comment]
I'll see if I can come up with a docker-compose-based reproducer. Please give me a few days...

**Comment by flo741** [comment]
I can confirm the issue. I am using Watchtower to update the containers, too. The file stays in the consume folder after updating the side containers. Not sure if it is redis or the db container.

**Comment by DimitriDR** [comment]
I have a related problem, I don't have these errors but the app put documents in queue and do nothing after that. I'm using the web UI but the result is the same.

**Comment by DnlKI** [comment]
Deleting `dump.rdb` in the redis volume fixed the problem for me.
