### ISSUE TITLE
After Update to 1.16.0, webserver thread crashes

### ISSUE THREAD

**Issue by LordMyschkin** [paperless-ngx/paperless-ngx#3596]
### Description

with the previous version, everything ran smoothly.
but docker-compose up never finishes because it seems that django checks crashes repeatedly
running docker-compose with tika and postgres.

### Steps to reproduce

update from 1.15.1 to 1.16.0 via docker-compose down; docker-compose pull; docker-compose up

### Webserver logs

```bash
webserver_1  | Running Django checks
webserver_1  | Traceback (most recent call last):
webserver_1  |   File "/usr/src/paperless/src/manage.py", line 10, in <module>
webserver_1  |     execute_from_command_line(sys.argv)
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
webserver_1  |     utility.execute()
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
webserver_1  |     self.fetch_command(subcommand).run_from_argv(self.argv)
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 402, in run_from_argv
webserver_1  |     self.execute(*args, **cmd_options)
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 448, in execute
webserver_1  |     output = self.handle(*args, **options)
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/check.py", line 76, in handle
webserver_1  |     self.check(
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 475, in check
webserver_1  |     all_issues = checks.run_checks(
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/checks/registry.py", line 88, in run_checks
webserver_1  |     new_errors = check(app_configs=app_configs, databases=databases)
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/checks/urls.py", line 42, in check_url_namespaces_unique
webserver_1  |     all_namespaces = _load_all_namespaces(resolver)
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/checks/urls.py", line 61, in _load_all_namespaces
webserver_1  |     url_patterns = getattr(resolver, "url_patterns", [])
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
webserver_1  |     res = instance.__dict__[self.name] = self.func(instance)
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns
webserver_1  |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
webserver_1  |     res = instance.__dict__[self.name] = self.func(instance)
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
webserver_1  |     return import_module(self.urlconf_name)
webserver_1  |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
webserver_1  |     return _bootstrap._gcd_import(name[level:], package, level)
webserver_1  |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
webserver_1  |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
webserver_1  |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
webserver_1  |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
webserver_1  |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
webserver_1  |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
webserver_1  |   File "/usr/src/paperless/src/paperless/urls.py", line 13, in <module>
webserver_1  |     from documents.views import AcknowledgeTasksView
webserver_1  |   File "/usr/src/paperless/src/documents/views.py", line 62, in <module>
webserver_1  |     from documents.tasks import consume_file
webserver_1  |   File "/usr/src/paperless/src/documents/tasks.py", line 21, in <module>
webserver_1  |     from documents.barcodes import BarcodeReader
webserver_1  |   File "/usr/src/paperless/src/documents/barcodes.py", line 12, in <module>
webserver_1  |     import img2pdf
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/img2pdf.py", line 25, in <module>
webserver_1  |     from PIL import Image, TiffImagePlugin, GifImagePlugin
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/PIL/Image.py", line 103, in <module>
webserver_1  |     from . import _imaging as core
webserver_1  | ImportError: libtiff.so.5: cannot open shared object file: No such file or directory
paperless_webserver_1 exited with code 1
webserver_1  | Creating directory /tmp/paperless
webserver_1  | Adjusting permissions of paperless files. This may take a while.
webserver_1  | chown: changing ownership of '/usr/src/paperless/consume': Operation not permitted
```

### Paperless-ngx version

1.16.0

### Host OS

rasbian os bullseye

### Installation method

Docker - official image

### Browser

firefox

### Configuration changes

none

**Comment by stumpylog** [comment]
Interesting.  I tested barcodes with the update to bookworm, but I think this is from the TIFF -> PDF conversion.  Or it's something with aarch64/armv7.  What is the architecture of your OS?

**Comment by stumpylog** [comment]
I made some assumptions about your setup, and I think `feature-fix-armv7-pillow` will fix it, but you'll have to test the fix on your setup.

It's database compatible, etc, but it's still a good idea o grab a backup first.

**Comment by dugite-code** [comment]
I'm not sure if I'm seeing the exact same issue or not. I have a slightly different traceback but the error is from the manage.py. 

I'm on an Intel celeron NUC and not an ARM board so that may be the difference?

<details>
<summary>Webserver logs</summary>

```
paperless_app        | Apply database migrations...
paperless_app        | Traceback (most recent call last):
paperless_app        |   File "/usr/src/paperless/src/manage.py", line 10, in <module>
paperless_app        |     execute_from_command_line(sys.argv)
paperless_app        |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
paperless_app        |     utility.execute()
paperless_app        |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 386, in execute
paperless_app        |     settings.INSTALLED_APPS
paperless_app        |   File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 92, in __getattr__
paperless_app        |     self._setup(name)
paperless_app        |   File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 79, in _setup
paperless_app        |     self._wrapped = Settings(settings_module)
paperless_app        |   File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 190, in __init__
paperless_app        |     mod = importlib.import_module(self.SETTINGS_MODULE)
paperless_app        |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
paperless_app        |     return _bootstrap._gcd_import(name[level:], package, level)
paperless_app        |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
paperless_app        |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
paperless_app        |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
paperless_app        |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
paperless_app        |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
paperless_app        |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
paperless_app        |   File "/usr/src/paperless/src/paperless/settings.py", line 605, in <module>
paperless_app        |     setup_logging_queues()
paperless_app        |   File "/usr/local/lib/python3.9/site-packages/concurrent_log_handler/queue.py", line 108, in setup_logging_queues
paperless_app        |     listener.start()
paperless_app        |   File "/usr/local/lib/python3.9/logging/handlers.py", line 1497, in start
paperless_app        |     t.start()
paperless_app        |   File "/usr/local/lib/python3.9/threading.py", line 899, in start
paperless_app        |     _start_new_thread(self._bootstrap, ())
paperless_app        | RuntimeError: can't start new thread
paperless_app        | Paperless-ngx docker container starting...
paperless_app        | userdel: user 'www-data' does not exist
```
</details>

**Host OS**
Debian x86_64

**Installation method:**
Docker - Official Image

**Configuration changes:**
Added custom fonts by script in `custom-cont-init.d` https://github.com/paperless-ngx/paperless-ngx/issues/277#issuecomment-1396512363 and added custom ImageMagik `policy.xml`

**Comment by stumpylog** [comment]
No, that's something else.

**Comment by stumpylog** [comment]
That looks like https://github.com/docker-library/python/issues/835.  Their suggestion is updating some libraries and/or Docker

**Comment by LordMyschkin** [comment]
thanks for this quick reaction! It will be quite a task for me to apply that fix, paperless-ngx is my very first try with docker-compose...
i'am on Linux rpi3 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
I'll give it a try this weekend!

**Comment by tom666-debug** [comment]
I am facing the same issue here:
```
Paperless-ngx docker container starting...
Creating directory /tmp/paperless
Adjusting permissions of paperless files. This may take a while.
Waiting for PostgreSQL to start...
Waiting for Redis...
Connected to Redis broker.
Apply database migrations...
Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 386, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 92, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 79, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/src/paperless/src/paperless/settings.py", line 605, in <module>
    setup_logging_queues()
  File "/usr/local/lib/python3.9/site-packages/concurrent_log_handler/queue.py", line 108, in setup_logging_queues
    listener.start()
  File "/usr/local/lib/python3.9/logging/handlers.py", line 1497, in start
    t.start()
  File "/usr/local/lib/python3.9/threading.py", line 899, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Paperless-ngx docker container starting...
Creating directory /tmp/paperless
Adjusting permissions of paperless files. This may take a while.
```

**Comment by tom666-debug** [comment]
Any idea for how to fix it for Docker on linux, amd64?

**Comment by stumpylog** [comment]
If you are seeing a `RuntimeError` about starting threads, please refer to the upstream issue for possible suggestions:https://github.com/docker-library/python/issues/835.  I've marked those as off topic to this thread.

If you're experiencing an `ImportError` related to, libtiff, please try the Docker tag `:feature-fix-armv7-pillow`.  If that doesn't work, please let me know the host architecture (`uname -a`) and any other details

**Comment by tobiasschuerg** [comment]
Can confirm that [feature-fix-armv7-pillow](https://github.com/paperless-ngx/paperless-ngx/pkgs/container/paperless-ngx/102025293?tag=feature-fix-armv7-pillow) fixes the issue on a armv7 raspberry.

**Comment by stumpylog** [comment]
Given this seems to resolve things for armv7l at least, I'm creating a 1.16.1 with the fix included.

**Comment by LordMyschkin** [comment]
I can confirm the fix works for me - thank you a thousand times for the quick fix!
