### ISSUE TITLE
[BUG] Paperless does not consume Word file ('BaseResponse' object has no attribute 'content')

### ISSUE THREAD

**Issue by leo-022** [paperless-ngx/paperless-ngx#3614]
### Description

A consumed Word file will not be passed on to Gotenberg. This error occurs after updating to version 1.16.0, with version 1.16.1 the behavior is unchanged. - A downgrade to version 1.15.1 eliminates the problem.

### Steps to reproduce

1. Docker update to Paperless NGX 1.16.0 or 1.16.1
1. Copy a Word file to consume directory
1. Result failed in File Tasks: 'BaseResponse' object has no attribute 'content'

### Webserver logs

```bash
2023-06-17T21:39:40.156450809Z [2023-06-17 23:39:40,155] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/yyy.doc to the task queue.
2023-06-17T21:39:40.198374101Z [2023-06-17 23:39:40,196] [INFO] [celery.worker.strategy] Task documents.tasks.consume_file[9b3796c2-e77d-403d-907d-e9d039c23e18] received
2023-06-17T21:39:40.254113883Z [2023-06-17 23:39:40,252] [WARNING] [paperless.barcodes] Unsupported file format for barcode reader: application/msword
2023-06-17T21:39:40.255892299Z [2023-06-17 23:39:40,254] [WARNING] [paperless.barcodes] Exception during barcode scanning: 'NoneType' object has no attribute 'name'
2023-06-17T21:39:40.366714534Z [2023-06-17 23:39:40,364] [INFO] [paperless.consumer] Consuming yyy.doc
2023-06-17T21:39:40.678834755Z [2023-06-17 23:39:40,677] [INFO] [paperless.parsing.tika] Sending /tmp/paperless/paperless-ngxu20164qy/yyy.doc to Tika server
2023-06-17T21:39:40.971540790Z [2023-06-17 23:39:40,969] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[9b3796c2-e77d-403d-907d-e9d039c23e18] raised unexpected: AttributeError("'BaseResponse' object has no attribute 'content'")
2023-06-17T21:39:40.971808472Z Traceback (most recent call last):
2023-06-17T21:39:40.971895454Z   File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 477, in trace_task
2023-06-17T21:39:40.971956328Z     R = retval = fun(*args, **kwargs)
2023-06-17T21:39:40.972011965Z   File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 760, in __protected_call__
2023-06-17T21:39:40.972064051Z     return self.run(*args, **kwargs)
2023-06-17T21:39:40.972111524Z   File "/usr/src/paperless/src/documents/tasks.py", line 133, in consume_file
2023-06-17T21:39:40.972163329Z     document = Consumer().try_consume_file(
2023-06-17T21:39:40.972211144Z   File "/usr/src/paperless/src/documents/consumer.py", line 382, in try_consume_file
2023-06-17T21:39:40.972262882Z     document_parser.parse(self.path, mime_type, self.filename)
2023-06-17T21:39:40.972310896Z   File "/usr/src/paperless/src/paperless_tika/parsers.py", line 61, in parse
2023-06-17T21:39:40.972359728Z     self.text = parsed.content.strip()
2023-06-17T21:39:40.972404697Z AttributeError: 'BaseResponse' object has no attribute 'content'
```

### Paperless-ngx version

1.16.0 or 1.16.1

### Host OS

Docker container on Synology NAS

### Installation method

Docker - official image

**Comment by stumpylog** [comment]
That's Tika, not Gotenberg, but should be easy enough to fix

**Comment by stumpylog** [comment]
Having a sample file would be helpful, as our testing does consume a docx and odt document without issue

**Comment by leo-022** [comment]
A docx document works. The attached doc document doesn't work.
[yyy.zip](https://github.com/paperless-ngx/paperless-ngx/files/11780214/yyy.zip)

**Comment by stumpylog** [comment]
Ah, that's the problem then.  I never tested an older format.
