### ISSUE TITLE
[BUG] High Ram Usage while idle

### ISSUE THREAD

**Issue by Jopo-JP** [paperless-ngx/paperless-ngx#3616]
### Description

It's seems, that paperless-ngx never releases the ram or let's say, the workers.
I've seen the other issues like #2074 but it has never been resolved.

Is there any reason why this happens?

Before:
![image](https://github.com/paperless-ngx/paperless-ngx/assets/21254390/81fd12db-21f8-4ee9-b668-fd662223512a)
(i can even scroll for quite a bit)

After restart of the stack:
![image](https://github.com/paperless-ngx/paperless-ngx/assets/21254390/cb901361-3b75-4ac9-b70d-86a72865bbb8)
I got my 10 Gig RAM back.

Paperless-ngx run for roughly 3 days and in my setup i have about 1000+ documents. No new documents since a week or so.

### Steps to reproduce

1. Start paperless-ngx
2. Wait quite some time
3. paperless doesn't release the workers

### Webserver logs

```bash
2023-06-18 00:31:18,820 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-06-18 00:31:18,820 INFO success: celery entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-06-18 00:31:18,820 INFO success: celery-beat entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-06-18 00:31:18,820 INFO success: consumer entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[2023-06-18 02:31:18,863] [INFO] [celery.worker.consumer.connection] Connected to redis://broker:6379//
[2023-06-18 02:31:18,871] [INFO] [celery.apps.worker] celery@afd484037f25 ready.
[2023-06-18 02:35:00,094] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
[2023-06-18 02:35:00,115] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[7fadc0fb-9030-4961-8f96-271da509e4db] received
[2023-06-18 02:35:00,721] [INFO] [celery.app.trace] Task paperless_mail.tasks.process_mail_accounts[7fadc0fb-9030-4961-8f96-271da509e4db] succeeded in 0.6048778229742311s: 'No new documents were added.'
```

### Paperless-ngx version

1.16.0

### Host OS

Ubuntu 22.04

### Installation method

Docker - official image

**Comment by shamoon** [comment]
As noted in the other thread, this might be a gunicorn issue but this isn't what Im seeing. My container idles at ~4-500mb with a low single-digit number of gunicorn threads

<img width="1087" alt="Screenshot 2023-06-17 at 7 57 18 PM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/f217085f-d340-40a0-a9f3-b5acb349bf3f">
<img width="1070" alt="Screenshot 2023-06-17 at 7 53 56 PM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/672de2a6-d130-4899-bd3e-50fae06fa086">

**Comment by stumpylog** [comment]
my own production instance has been up only 13 hours, but it's idling at around 550 MB.  Entering the container, I don't see very many gunicorn threads.  The default configuration is a single worker, and I assume gunicorn decides/creates threads as needed and should be cleaning any up.

I don't see anything obvious in their issues, but there's a large number to look through

**Comment by Psychi1** [comment]
Hello, 

I confirm the high ram usage. 
![paperless_1 6 5](https://github.com/paperless-ngx/paperless-ngx/assets/35874716/f194e8f0-60af-46f0-b16b-9849edf37be1)

Around 1.5 GB of RAM is consumed by a process on gunicorn `gunicorn: worker [paperless.asgi:application]`

**Comment by blue-kaleidoscope** [comment]
I run V1.16.2.
When firing up the docker containers it idles at ~500 MB RAM usage. I sequentially opened a couple of bigger documents and now it idles at 2.1 GB RAM since the last 10 minutes. No idea whether this is ever released again. I will post again to give an update.

**Comment by Olaf65** [comment]
I have exactly the same problem like Jopo-JP. 
![Bildschirmfoto-20230704212217-633x319](https://github.com/paperless-ngx/paperless-ngx/assets/49076120/66ae99ff-1d66-4353-bff2-b03cd380a3b1)
![Bildschirmfoto-20230704212239-631x329](https://github.com/paperless-ngx/paperless-ngx/assets/49076120/89360a95-5be4-4264-83a0-b00ed9337358)
![Bildschirmfoto-20230704212311-633x325](https://github.com/paperless-ngx/paperless-ngx/assets/49076120/7cd0389f-602f-470b-9223-91d34b78d0de)
![Bildschirmfoto-20230704212328-636x339](https://github.com/paperless-ngx/paperless-ngx/assets/49076120/9742333b-70bb-44bf-97c9-35934c395eab)
After one hour it reaches the time limit:
[2023-07-04 20:30:00,135] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)

[2023-07-04 20:30:00,138] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[b42b19bc-18d6-4498-99fe-071c4e70356d] received

[2023-07-04 20:40:00,233] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)

[2023-07-04 20:40:00,254] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[ab0c3b9a-3d6b-4420-9f70-061ea34e3445] received

[2023-07-04 20:50:00,277] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)

[2023-07-04 21:00:00,203] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)

[2023-07-04 21:05:00,944] [INFO] [celery.beat] Scheduler: Sending due task Train the classifier (documents.tasks.train_classifier)

[2023-07-04 21:10:00,387] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)

[2023-07-04 21:12:59,948] [ERROR] [celery.worker.request] Task handler raised error: TimeLimitExceeded(3600)

Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/billiard/pool.py", line 683, in on_hard_timeout

    raise TimeLimitExceeded(job._timeout)

billiard.einfo.ExceptionWithTraceback: 

"""

Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/billiard/pool.py", line 683, in on_hard_timeout

    raise TimeLimitExceeded(job._timeout)

billiard.exceptions.TimeLimitExceeded: TimeLimitExceeded(3600,)

"""

[2023-07-04 21:13:00,324] [ERROR] [celery.worker.request] Hard time limit (3600s) exceeded for documents.tasks.train_classifier[a6cf1609-0e2a-482b-abb8-4f5805d31917]

[2023-07-04 21:13:03,422: ERROR/MainProcess] Process 'ForkPoolWorker-4' pid:654 exited with 'signal 9 (SIGKILL)'

[2023-07-04 21:13:11,373] [INFO] [celery.worker.request] Discarding revoked task: paperless_mail.tasks.process_mail_accounts[b42b19bc-18d6-4498-99fe-071c4e70356d]

[2023-07-04 21:13:11,787] [INFO] [celery.worker.request] Discarding revoked task: paperless_mail.tasks.process_mail_accounts[ab0c3b9a-3d6b-4420-9f70-061ea34e3445]

[2023-07-04 21:13:12,013] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[1c15651b-c0d0-4d38-acbb-a4c18745c626] received

And then it starts again and consumes all memory.

**Comment by tripplet** [comment]
I can report the same problem ~1.3GB for only 64 documents.
Guincorn worker seems to consume more RAM over time never going down.
For me it seems to be related to usage of the website.
After restart the gunicorn worker stays at ~77MB until I use the website again.

**Comment by shamoon** [comment]
Again, this sounds like a gunicorn (or perhaps Django) issue, not a paperless one

**Comment by blue-kaleidoscope** [comment]
I am not an expert at all in this, but a quick google revealed in a different project: [Unexplained High RAM Usage in Worker Servers](https://awstip.com/tackling-unexplained-high-ram-and-cpu-usage-in-django-redis-celery-server-2b2ec5fe0068)

The solution was to add ```stopasgroup=true``` to the gunicorn configuration. Could this help here as well? I do not know how to test that.

**Comment by lodex2** [comment]
Having the same issues as well. After starting paperless, everything runs smoothly until I start using the website a bit. The gunicorn processes fill up the entire RAM until the OOM killer kicks in:
```
Out of memory: Killed process 692182 (gunicorn: worke) total-vm:19615708kB, anon-rss:14726488kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:31760kB oom_score_adj:0
```

**Comment by shamoon** [comment]
Presumably yes. Again, this isn't reproducible in all environments and I'm not aware that we're explicitly doing anything to control (ie cause) this

**Comment by blue-kaleidoscope** [comment]
> I am not an expert at all in this, but a quick google revealed in a different project: [Unexplained High RAM Usage in Worker Servers](https://awstip.com/tackling-unexplained-high-ram-and-cpu-usage-in-django-redis-celery-server-2b2ec5fe0068)
> 
> The solution was to add `stopasgroup=true` to the gunicorn configuration. Could this help here as well? I do not know how to test that.

So, I built my own docker container based on v1.16.5 and before building it, I added the `stopasgroup=true` to the gunicorn configuration. However, this did not solve the problem. The RAM is never released after having closed documents.

**Comment by stumpylog** [comment]
#3842 will update `gunicorn` after quite a gap in releases, though nothing in the somewhat sparse release notes indicates a fix for workers not dying off when they presumably should be.  But one can always hope.

**Comment by lodex2** [comment]
Gonna take a look once I find the time. In the meantime I'm still trying to find a way to reproduce the issue reliably. While my instance at home works perfectly fine, the instance at work starts to spawn more and more gunicorn processes once you open only a small amount of documents.

**Comment by blue-kaleidoscope** [comment]
I felt adventurous and tried the dev image. ;-)
However, the issue still exists. Unfortunately I cannot use or install `htop` (QNAP NAS with very limited Linux capabilities and no chance to install it). But I can see with `docker stats` that the memory increases with each document I am opening but is never released.

**Comment by stumpylog** [comment]
You can install it in the container.  Just exec into a shell, docker exec -it <name> /bin/bash.

**Comment by blue-kaleidoscope** [comment]
OK. Didn‘t know `apt` is available inside the container. So here are my observations: the `gunicorn` processes indeed get closed. The tree in `htop` grows when accessing documents and shrinks when closing them. However, the memory percentage grows for the group of remaining `gunicorn` processes and `docker stats` on the host shows increasing memory consumption. Strange.

**Comment by alexgrahamuk** [comment]
Has to be a memory leak, sits steady but over a few days it does degrade. Loads of ways to fix ie but just a reboot / snapshot restore early morning seems to negate

**Comment by blue-kaleidoscope** [comment]
That's how I do it... I let a python script regularly check the memory consumption and once a threshold was reached it waits until the memory is not changing anymore (means probably nobody is using paperless-ngx at the moment). Then another 3 minutes later it restarts the paperless-ngx webserver. Better than nothing. ^^
