### ISSUE TITLE
[BUG] 1.16.3: Tika error ascii' codec can't encode character '\xfc' 

### ISSUE THREAD

**Issue by alpha197** [paperless-ngx/paperless-ngx#3686]
### Description

Consuming a specific MS Word 365 document fails with this error message:

`20230625 LBV Antrag Kostenerstattung für Meldebescheinigung Familienzuschlag.docx: Error while consuming document 20230625 LBV Antrag Kostenerstattung für Meldebescheinigung Familienzuschlag.docx: Could not parse /tmp/paperless/paperless-ngx6efyyzjg/20230625 LBV Antrag Kostenerstattung für Meldebescheinigung Familienzuschlag.docx with tika server at http://tika:9998: 'ascii' codec can't encode character '\xfc' in position 59: ordinal not in range(128)`

Unfortunately I cannot attach the document because it contains personal infos, sorry!

### Steps to reproduce

Upload MS Word docx into consume directory.

### Webserver logs

```bash
[2023-06-25 19:13:14,318] [ERROR] [paperless.consumer] Error while consuming document 20230625 LBV Antrag Kostenerstattung für Meldebescheinigung Familienzuschlag.docx: Could not parse /tmp/paperless/paperless-ngxk4ony929/20230625 LBV Antrag Kostenerstattung für Meldebescheinigung Familienzuschlag.docx with tika server at http://tika:9998: 'ascii' codec can't encode character '\xfc' in position 59: ordinal not in range(128)

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_tika/parsers.py", line 55, in parse

    parsed = client.tika.as_text.from_file(document_path, mime_type)

  File "/usr/local/lib/python3.9/site-packages/tika_client/_resource_tika.py", line 36, in from_file

    return self._decoded_response(self._put_multipart(self.MULTI_PART_PLAIN_TEXT_CONTENT, filepath, mime_type))

  File "/usr/local/lib/python3.9/site-packages/tika_client/_utils.py", line 34, in _put_multipart

    resp = self.client.post(

  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1132, in post

    return self.request(

  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 801, in request

    request = self.build_request(

  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 347, in build_request

    headers = self._merge_headers(headers)

  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 414, in _merge_headers

    merged_headers.update(headers)

  File "/usr/local/lib/python3.9/site-packages/httpx/_models.py", line 200, in update

    headers = Headers(headers)

  File "/usr/local/lib/python3.9/site-packages/httpx/_models.py", line 71, in __init__

    self._list = [

  File "/usr/local/lib/python3.9/site-packages/httpx/_models.py", line 75, in <listcomp>

    normalize_header_value(v, encoding),

  File "/usr/local/lib/python3.9/site-packages/httpx/_utils.py", line 53, in normalize_header_value

    return value.encode(encoding or "ascii")

UnicodeEncodeError: 'ascii' codec can't encode character '\xfc' in position 59: ordinal not in range(128)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/consumer.py", line 382, in try_consume_file

    document_parser.parse(self.path, mime_type, self.filename)

  File "/usr/src/paperless/src/paperless_tika/parsers.py", line 57, in parse

    raise ParseError(

documents.parsers.ParseError: Could not parse /tmp/paperless/paperless-ngxk4ony929/20230625 LBV Antrag Kostenerstattung für Meldebescheinigung Familienzuschlag.docx with tika server at http://tika:9998: 'ascii' codec can't encode character '\xfc' in position 59: ordinal not in range(128)
```

### Paperless-ngx version

1.6.3

### Host OS

Debian 11

### Installation method

Docker - official image

### Browser

Chrome

**Comment by shamoon** [comment]
Without a sample this will be tough to deal with. Moreover it may be an upstream issue with tika itself, which is not our software. If you can float the file, can you try to run it directly against tika and post the results of that?

**Comment by alpha197** [comment]
The problem seems to be the umlaut "ü" in the filename ("für"). The attached document (containing just the word "Test") brings up the error. After changing the filename in  "20230625 LBV Antrag Kostenerstattung fuer Meldebescheinigung Familienzuschlag.docx" everything works fine.
[20230625 LBV Antrag Kostenerstattung für Meldebescheinigung Familienzuschlag.docx](https://github.com/paperless-ngx/paperless-ngx/files/11860530/20230625.LBV.Antrag.Kostenerstattung.fur.Meldebescheinigung.Familienzuschlag.docx)

**Comment by stumpylog** [comment]
I might need to normalize or convert headers in my client.  I'll have to look at it more when possible

**Comment by vinc32** [comment]
same issue here wir "ä", "ü", "ö" etc
