### ISSUE TITLE
[BUG] HTTP 500 in Tika for some OpenDocument Documents

### ISSUE THREAD

**Issue by a17t** [paperless-ngx/paperless-ngx#3757]
### Description

When recreating my local paperless instance, I had to rerun the document archival and thumbnail jobs for all documents.

Those failed for all OpenDocument Documents from my originals. 

I noticed this being related to the latest changes in paperless_tika/parser.py. After testing the parser.py from 1.15 all worked.

I am already working on further investigation on my fork and will start the corresponding pull request.

### Steps to reproduce

upload ODT document -> parsing fails

### Webserver logs

```bash
---TIKA---
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:190)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:191)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.IOException: Stream Closed
	at java.base/java.io.FileInputStream.available0(Native Method)
	at java.base/java.io.FileInputStream.available(FileInputStream.java:415)
	at org.apache.cxf.attachment.DelegatingInputStream.available(DelegatingInputStream.java:75)
	at org.apache.cxf.helpers.IOUtils.consume(IOUtils.java:382)
	at org.apache.cxf.attachment.DelegatingInputStream.close(DelegatingInputStream.java:46)
	at org.apache.tika.server.core.resource.TikaResource.parse(TikaResource.java:374)
	at org.apache.tika.server.core.resource.TikaResource.parseToMetadata(TikaResource.java:611)
	at org.apache.tika.server.core.resource.TikaResource.getJsonFromMultipart(TikaResource.java:564)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	... 28 more

---PAPERLESS---
[2023-07-06 17:57:46,034] [INFO] [paperless.consumer] Consuming 2023-03-28 Johannes Gutenberg-Universität Mainz Datenbank Praktikum Gruppe 3.odt
[2023-07-06 17:57:46,112] [INFO] [paperless.parsing.tika] Sending /tmp/paperless/paperless-ngxzed2cbo7/2023-03-28 Johannes Gutenberg-Universität Mainz Datenbank Praktikum Gruppe 3.odt to Tika server
[2023-07-06 17:57:47,289] [ERROR] [paperless.consumer] Error while consuming document 2023-03-28 Johannes Gutenberg-Universität Mainz Datenbank Praktikum Gruppe 3.odt: Could not parse /tmp/paperless/paperless-ngxzed2cbo7/2023-03-28 Johannes Gutenberg-Universität Mainz Datenbank Praktikum Gruppe 3.odt with tika server at http://localhost:9998: Server error '500 Server Error' for url 'http://localhost:9998/tika/form/text'
For more information check: https://httpstatuses.com/500
Traceback (most recent call last):
  File "/usr/src/paperless/src/paperless_tika/parsers.py", line 54, in parse
    parsed = client.tika.as_text.from_file(document_path, mime_type)
  File "/usr/local/lib/python3.9/site-packages/tika_client/_resource_tika.py", line 36, in from_file
    return self._decoded_response(self._put_multipart(self.MULTI_PART_PLAIN_TEXT_CONTENT, filepath, mime_type))
  File "/usr/local/lib/python3.9/site-packages/tika_client/_utils.py", line 46, in _put_multipart
    resp.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/httpx/_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '500 Server Error' for url 'http://localhost:9998/tika/form/text'
For more information check: https://httpstatuses.com/500

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/consumer.py", line 382, in try_consume_file
    document_parser.parse(self.path, mime_type, self.filename)
  File "/usr/src/paperless/src/paperless_tika/parsers.py", line 56, in parse
    raise ParseError(
documents.parsers.ParseError: Could not parse /tmp/paperless/paperless-ngxzed2cbo7/2023-03-28 Johannes Gutenberg-Universität Mainz Datenbank Praktikum Gruppe 3.odt with tika server at http://localhost:9998: Server error '500 Server Error' for url 'http://localhost:9998/tika/form/text'
For more information check: https://httpstatuses.com/500
[2023-07-06 17:57:47,309] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[1a0c8479-65a4-4de7-a431-29ecb537a030] raised unexpected: ConsumerError("2023-03-28 Johannes Gutenberg-Universität Mainz Datenbank Praktikum Gruppe 3.odt: Error while consuming document 2023-03-28 Johannes Gutenberg-Universität Mainz Datenbank Praktikum Gruppe 3.odt: Could not parse /tmp/paperless/paperless-ngxzed2cbo7/2023-03-28 Johannes Gutenberg-Universität Mainz Datenbank Praktikum Gruppe 3.odt with tika server at http://localhost:9998: Server error '500 Server Error' for url 'http://localhost:9998/tika/form/text'\nFor more information check: https://httpstatuses.com/500")
Traceback (most recent call last):
  File "/usr/src/paperless/src/paperless_tika/parsers.py", line 54, in parse
    parsed = client.tika.as_text.from_file(document_path, mime_type)
  File "/usr/local/lib/python3.9/site-packages/tika_client/_resource_tika.py", line 36, in from_file
    return self._decoded_response(self._put_multipart(self.MULTI_PART_PLAIN_TEXT_CONTENT, filepath, mime_type))
  File "/usr/local/lib/python3.9/site-packages/tika_client/_utils.py", line 46, in _put_multipart
    resp.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/httpx/_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '500 Server Error' for url 'http://localhost:9998/tika/form/text'
For more information check: https://httpstatuses.com/500
```

### Paperless-ngx version

1.16.5

### Host OS

Truenas

### Installation method

Docker - official image

**Comment by a17t** [comment]
The cause seems to be the switch from the tika client library to tika-client. The later does not work for all document types. Was there a specific reason for the switch?

**Comment by a17t** [comment]
THanks for the info @shamoon , going a different route then, than my first PR... for me the issue is actually quite major, as no Open Document files can be parsed by paperless anymore..

**Comment by stumpylog** [comment]
The new library includes testing with odt files and works there without issue.  Is this some other document type?  Can you send a sample?

And just to note, a 500 is Tika crashing internally, so it might be something in there.  But with a sample, I'll look at it in a couple weeks or so

**Comment by stumpylog** [comment]
You can search/report Tika issues here: https://issues.apache.org/jira/projects/TIKA/issues/

I'll also get the paperless image updated to v2.8.0 at some point this week, in case it's something already fixed.

**Comment by stumpylog** [comment]
The paperless Tika image is updated to 2.8.0, you can give that a shot.

**Comment by stumpylog** [comment]
I haven't been able to reproduce this with ODT files from LibreOffice or Google Docs nor DOCX from Google Docs or Microsoft Word.  I tried spreadsheets as well and against 1.16 and dev images.

**Comment by stumpylog** [comment]
That's a different error and already fixed.

**Comment by stumpylog** [comment]
That's useful to know, though it's still Tika crashing in this case.  And using the broken file via basic `curl` also returns a 500 error, so it's not something `httpx` is doing wrong either.  Somehow, content vs multi-part breaks tika.  I'll jump through the hoops to report it upstream there.

**Comment by stumpylog** [comment]
Not particularly easy to get an account, but I've created an upstream for this: https://issues.apache.org/jira/browse/TIKA-4110

**Comment by stumpylog** [comment]
No fixes with Tika 2.9.0.  And no comments or updates on the created bug report

**Comment by siancu** [comment]
With the current GitHub checkout of the main branch of tika, I cannot reproduce this issue anymore. Even the second command, with the form, works:

Request: 

`curl -H "Accept: application/json" --form file=@sample.odt http://localhost:9998/tika/form`

Response:

`{"X-TIKA:Parsed-By":"org.apache.tika.parser.EmptyParser","X-TIKA:Parsed-By-Full-Set":"org.apache.tika.parser.EmptyParser","X-TIKA:content":"<html xmlns=\"http://www.w3.org/1999/xhtml\">\n<head>\n<meta name=\"X-TIKA:Parsed-By\" content=\"org.apache.tika.parser.EmptyParser\" />\n<meta name=\"Content-Length\" content=\"130012\" />\n<meta name=\"Content-Type\" content=\"application/vnd.oasis.opendocument.text\" />\n<title></title>\n</head>\n<body /></html>","Content-Length":"130012","Content-Type":"application/vnd.oasis.opendocument.text"}`

**Comment by siancu** [comment]
Ah, now I see, I don't seem to be having any parser configured ... probably that's why it works.
