### ISSUE TITLE
[BUG] Tika client returns Invalid isoformat string.

### ISSUE THREAD

**Issue by locutus13** [paperless-ngx/paperless-ngx#3780]
### Description

Paperless-ngx 1.16.5
docker container installed with 
bash -c "$(curl -L https://raw.githubusercontent.com/paperless-ngx/paperless-ngx/main/install-paperless-ngx.sh)"

When I try to consume any ODT (libreoffice text document) paperless.consumer returns the following error:
[ERROR] [paperless.consumer] Error while consuming document test.odt: Could not parse /tmp/paperless/paperless-ngxckamnq_l/test.odt with tika server at http://tika:9998: Invalid isoformat string: '2022-10-10T09:52:32.164746686'

Full error-log:

### Steps to reproduce

1) upload any ODT file into the consume directory
2) error appears

### Webserver logs

```bash
[2023-07-11 08:54:05,231] [ERROR] [paperless.consumer] Error while consuming document test.odt: Could not parse /tmp/paperless/paperless-ngxckamnq_l/test.odt with tika server at http://tika:9998: Invalid isoformat string: '2022-10-10T09:52:32.164746686'
Traceback (most recent call last):
  File "/usr/src/paperless/src/paperless_tika/parsers.py", line 54, in parse
    parsed = client.tika.as_text.from_file(document_path, mime_type)
  File "/usr/local/lib/python3.9/site-packages/tika_client/_resource_tika.py", line 36, in from_file
    return self._decoded_response(self._put_multipart(self.MULTI_PART_PLAIN_TEXT_CONTENT, filepath, mime_type))
  File "/usr/local/lib/python3.9/site-packages/tika_client/_utils.py", line 81, in _decoded_response
    return TikaResponse(resp_json)
  File "/usr/local/lib/python3.9/site-packages/tika_client/data_models.py", line 68, in __init__
    self.created = self.get_optional_datetime(DublinCoreKey.Created)
  File "/usr/local/lib/python3.9/site-packages/tika_client/data_models.py", line 100, in get_optional_datetime
    return datetime.fromisoformat(self.data[key].replace("Z", "+00:00"))
ValueError: Invalid isoformat string: '2022-10-10T09:52:32.164746686'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/consumer.py", line 382, in try_consume_file
    document_parser.parse(self.path, mime_type, self.filename)
  File "/usr/src/paperless/src/paperless_tika/parsers.py", line 56, in parse
    raise ParseError(
documents.parsers.ParseError: Could not parse /tmp/paperless/paperless-ngxckamnq_l/test.odt with tika server at http://tika:9998: Invalid isoformat string: '2022-10-10T09:52:32.164746686'
```

### Paperless-ngx version

1.16.5

### Host OS

Ubuntu 22.04 LTS

### Installation method

Docker - official image

### Configuration changes

custom variables: PAPERLESS_TIME_ZONE=Europe/Berlin PAPERLESS_OCR_LANGUAGE=deu PAPERLESS_BIND_ADDR=0.0.0.0 PAPERLESS_CONSUMER_RECURSIVE=true

**Comment by shamoon** [comment]
#3757

**Comment by locutus13** [comment]
I am sorry but this is not a duplicate.
The issue is that the expected ISO-8601 string is supposed to be only 26charaters + timezone and for some reason I do not yet understand I get a 29character timestamp without timezone indicator...

Here is a workaround hack on how to fix this in my specific case:
File: "/usr/local/lib/python3.9/site-packages/tika_client/data_models.py", line 100

change from:
    return datetime.fromisoformat(self.data[key].replace("Z", "+00:00"))
to:
    return datetime.fromisoformat(self.data[key][:26]+"+00:00")

and now it works ... just a bit too "hacky"....

**Comment by shamoon** [comment]
Tracked in https://github.com/stumpylog/tika-client/issues/4

If you have a test file to post there it could be helpful

**Comment by sbrunsch2024** [comment]
[20170402-Computertext.odt](https://github.com/paperless-ngx/paperless-ngx/files/12028701/20170402-Computertext.odt)

**Comment by sbrunsch2024** [comment]
Testfile
