### ISSUE TITLE
[BUG] document_importer not working with fresh backup

### ISSUE THREAD

**Issue by iph0nege3k** [paperless-ngx/paperless-ngx#3789]
### Description

Hi all,

I wanted to move my paperless instance between hosts using the document_exporter/importer. The export was written nicely, however the import no longer works.

>docker-compose exec -T webserver document_importer ../export
```
Checking the manifest
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.ForeignKeyViolation: insert or update on table "auth_group_permissions" violates foreign key constraint "auth_group_permissio_permission_id_84c5c92e_fk_auth_perm"
DETAIL:  Key (permission_id)=(117) is not present in table "auth_permission".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/usr/src/paperless/src/documents/management/commands/document_importer.py", line 120, in handle
    call_command("loaddata", manifest_path)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 198, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/loaddata.py", line 102, in handle
    self.loaddata(fixture_labels)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/loaddata.py", line 171, in loaddata
    connection.check_constraints(table_names=table_names)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 314, in check_constraints
    cursor.execute("SET CONSTRAINTS ALL IMMEDIATE")
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
django.db.utils.IntegrityError: Problem installing fixtures: insert or update on table "auth_group_permissions" violates foreign key constraint "auth_group_permissio_permission_id_84c5c92e_fk_auth_perm"
DETAIL:  Key (permission_id)=(117) is not present in table "auth_permission".
```

### Steps to reproduce

1. `docker-compose exec -T webserver document_importer ../export`
2. `mv export /path/to/somewhere/else`
3. create fresh and completely new paperless instance
4. `docker-compose exec -T webserver document_importer ../export`

### Webserver logs

```bash
As seen above
```

### Paperless-ngx version

1.16.5

### Host OS

Debian bullseye, x86_64

### Installation method

Docker - official image

### Browser

Chrome

### Other

I'm guessing this bug might have been introduced when multi-user support came?

**Comment by shamoon** [comment]
This is https://github.com/paperless-ngx/paperless-ngx/discussions/3671, https://github.com/paperless-ngx/paperless-ngx/discussions/3333

will be closed by #3672
