### ISSUE TITLE
[BUG] Paperless UI won't load without 500 Server Errors

### ISSUE THREAD

**Issue by amrap030** [paperless-ngx/paperless-ngx#3863]
### Description

Hello together, 

I have a very strange behavior in my deployment of paperless via Kustomize into my local K3S Kubernetes Cluster.

https://github.com/paperless-ngx/paperless-ngx/assets/35061229/f5ac4e91-9abf-43a4-a682-24f52489f860

Please have a look at the video. I finally managed to deploy the app after lots of `"Access denied for user 'paperless'@'10.42.4.201' (using password: YES)"` errors. Now when I access the UI, on the first load you can see, paperless doesn't load. Then I refresh the page but I am getting a 500 Server Error. This goes back and forth a couple of times until it suddenly loads. Then I am trying to do a change in the settings, sometimes it saves and sometimes it throws errors on saving. In the logs of the browser I am seeing lots of 500 errors and in the logs of the paperless pod, I am seeing lots of `"Access denied for user 'paperless'@'10.42.4.201' (using password: YES)"` messages again, as shown below.

Can you please have a look at it? No matter what I do, I can't get it to work.

### Steps to reproduce

Deploy the following manifests to a Kubernetes Cluster via Kustomize. 

https://github.com/amrap030/k3s-gitops/tree/main/cluster/apps/services/paperless

> May not fully work because of persistent volume claims. To test it, you have to modify the pvc's according to your environment.

### Webserver logs

```bash
Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/signals/handlers.py", line 561, in task_prerun_handler
    task_instance = PaperlessTask.objects.filter(task_id=task_id).first()
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1047, in first
    for obj in (self if self.ordered else self.order_by("pk"))[:1]:
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 394, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1867, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 87, in __iter__
    results = compiler.execute_sql(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1396, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 323, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 299, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 263, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 247, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/__init__.py", line 123, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
django.db.utils.OperationalError: (1045, "Access denied for user 'paperless'@'10.42.4.201' (using password: YES)")
[2023-07-25 11:10:00,137] [INFO] [celery.app.trace] Task paperless_mail.tasks.process_mail_accounts[d3b759bf-006a-40ca-b965-49e6fbc84d41] succeeded in 0.04232989800220821s: 'No new documents were added.'
[2023-07-25 11:20:00,070] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
[2023-07-25 11:20:00,079] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[7bd5cce7-10b0-4f6a-80df-30014f4b5051] received
[2023-07-25 11:20:00,103] [ERROR] [paperless.handlers] Setting PaperlessTask started failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 263, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 247, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/__init__.py", line 123, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (1045, "Access denied for user 'paperless'@'10.42.4.201' (using password: YES)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/signals/handlers.py", line 561, in task_prerun_handler
    task_instance = PaperlessTask.objects.filter(task_id=task_id).first()
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1047, in first
    for obj in (self if self.ordered else self.order_by("pk"))[:1]:
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 394, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1867, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 87, in __iter__
    results = compiler.execute_sql(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1396, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 323, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 299, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 263, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 247, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/__init__.py", line 123, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
django.db.utils.OperationalError: (1045, "Access denied for user 'paperless'@'10.42.4.201' (using password: YES)")
```
```


### Browser logs

```bash
lockdown-install.js:1 Removing intrinsics.JSON.rawJSON
visitProperties @ lockdown-install.js:1
isAllowedPropertyValue @ lockdown-install.js:1
isAllowedProperty @ lockdown-install.js:1
visitProperties @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
repairIntrinsics @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
(anonymous) @ lockdown-run.js:4
lockdown-install.js:1 Removing intrinsics.JSON.isRawJSON
visitProperties @ lockdown-install.js:1
isAllowedPropertyValue @ lockdown-install.js:1
isAllowedProperty @ lockdown-install.js:1
visitProperties @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
repairIntrinsics @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
(anonymous) @ lockdown-run.js:4
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.toReversed
visitProperties @ lockdown-install.js:1
isAllowedPropertyValue @ lockdown-install.js:1
isAllowedProperty @ lockdown-install.js:1
visitProperties @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
repairIntrinsics @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
(anonymous) @ lockdown-run.js:4
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.toSorted
visitProperties @ lockdown-install.js:1
isAllowedPropertyValue @ lockdown-install.js:1
isAllowedProperty @ lockdown-install.js:1
visitProperties @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
repairIntrinsics @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
(anonymous) @ lockdown-run.js:4
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.toSpliced
visitProperties @ lockdown-install.js:1
isAllowedPropertyValue @ lockdown-install.js:1
isAllowedProperty @ lockdown-install.js:1
visitProperties @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
repairIntrinsics @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
(anonymous) @ lockdown-run.js:4
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.with
visitProperties @ lockdown-install.js:1
isAllowedPropertyValue @ lockdown-install.js:1
isAllowedProperty @ lockdown-install.js:1
visitProperties @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
repairIntrinsics @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
(anonymous) @ lockdown-run.js:4
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.@@unscopables.toReversed
visitProperties @ lockdown-install.js:1
isAllowedPropertyValue @ lockdown-install.js:1
isAllowedProperty @ lockdown-install.js:1
visitProperties @ lockdown-install.js:1
isAllowedPropertyValue @ lockdown-install.js:1
isAllowedProperty @ lockdown-install.js:1
visitProperties @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
repairIntrinsics @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
(anonymous) @ lockdown-run.js:4
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.@@unscopables.toSorted
visitProperties @ lockdown-install.js:1
isAllowedPropertyValue @ lockdown-install.js:1
isAllowedProperty @ lockdown-install.js:1
visitProperties @ lockdown-install.js:1
isAllowedPropertyValue @ lockdown-install.js:1
isAllowedProperty @ lockdown-install.js:1
visitProperties @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
repairIntrinsics @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
(anonymous) @ lockdown-run.js:4
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.@@unscopables.toSpliced
visitProperties @ lockdown-install.js:1
isAllowedPropertyValue @ lockdown-install.js:1
isAllowedProperty @ lockdown-install.js:1
visitProperties @ lockdown-install.js:1
isAllowedPropertyValue @ lockdown-install.js:1
isAllowedProperty @ lockdown-install.js:1
visitProperties @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
repairIntrinsics @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
(anonymous) @ lockdown-run.js:4
lockdown-install.js:1 Removing intrinsics.%ArrayBufferPrototype%.transferToFixedLength
visitProperties @ lockdown-install.js:1
isAllowedPropertyValue @ lockdown-install.js:1
isAllowedProperty @ lockdown-install.js:1
visitProperties @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
repairIntrinsics @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
(anonymous) @ lockdown-run.js:4
lockdown-install.js:1 Removing intrinsics.%ArrayBufferPrototype%.detached
visitProperties @ lockdown-install.js:1
isAllowedPropertyValue @ lockdown-install.js:1
isAllowedProperty @ lockdown-install.js:1
visitProperties @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
repairIntrinsics @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
(anonymous) @ lockdown-run.js:4
lockdown-install.js:1 Removing intrinsics.%StringPrototype%.isWellFormed
visitProperties @ lockdown-install.js:1
isAllowedPropertyValue @ lockdown-install.js:1
isAllowedProperty @ lockdown-install.js:1
visitProperties @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
repairIntrinsics @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
(anonymous) @ lockdown-run.js:4
lockdown-install.js:1 Removing intrinsics.%StringPrototype%.toWellFormed
visitProperties @ lockdown-install.js:1
isAllowedPropertyValue @ lockdown-install.js:1
isAllowedProperty @ lockdown-install.js:1
visitProperties @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
repairIntrinsics @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
(anonymous) @ lockdown-run.js:4
lockdown-install.js:1 Removing intrinsics.%RegExpPrototype%.unicodeSets
visitProperties @ lockdown-install.js:1
isAllowedPropertyValue @ lockdown-install.js:1
isAllowedProperty @ lockdown-install.js:1
visitProperties @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
repairIntrinsics @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
(anonymous) @ lockdown-run.js:4
lockdown-install.js:1 Removing intrinsics.%TypedArrayPrototype%.toReversed
visitProperties @ lockdown-install.js:1
isAllowedPropertyValue @ lockdown-install.js:1
isAllowedProperty @ lockdown-install.js:1
visitProperties @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
repairIntrinsics @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
(anonymous) @ lockdown-run.js:4
lockdown-install.js:1 Removing intrinsics.%TypedArrayPrototype%.toSorted
visitProperties @ lockdown-install.js:1
isAllowedPropertyValue @ lockdown-install.js:1
isAllowedProperty @ lockdown-install.js:1
visitProperties @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
repairIntrinsics @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
(anonymous) @ lockdown-run.js:4
lockdown-install.js:1 Removing intrinsics.%TypedArrayPrototype%.with
visitProperties @ lockdown-install.js:1
isAllowedPropertyValue @ lockdown-install.js:1
isAllowedProperty @ lockdown-install.js:1
visitProperties @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
repairIntrinsics @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
(anonymous) @ lockdown-run.js:4
favicon.ico:1     GET https://paperless.amrap030.home/favicon.ico 500
Image (async)
(anonymous) @ inpage.js:1
e @ polyfills.js:1
u @ inpage.js:1
a @ inpage.js:1
(anonymous) @ inpage.js:1
r.sendSiteMetadata @ inpage.js:1
e @ inpage.js:1
polyfills.js:1     GET https://paperless.amrap030.home/api/ui_settings/ 500
z @ polyfills.js:1
scheduleTask @ polyfills.js:1
onScheduleTask @ polyfills.js:1
scheduleTask @ polyfills.js:1
scheduleTask @ polyfills.js:1
scheduleMacroTask @ polyfills.js:1
Me @ polyfills.js:1
(anonymous) @ polyfills.js:1
o.<computed> @ polyfills.js:1
(anonymous) @ main.js:3
_trySubscribe @ main.js:3
(anonymous) @ main.js:3
z @ main.js:3
subscribe @ main.js:3
Y @ main.js:3
F @ main.js:3
_next @ main.js:3
next @ main.js:3
(anonymous) @ main.js:3
_trySubscribe @ main.js:3
(anonymous) @ main.js:3
z @ main.js:3
subscribe @ main.js:3
tR @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
z @ main.js:3
subscribe @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
z @ main.js:3
subscribe @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
z @ main.js:3
subscribe @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
z @ main.js:3
subscribe @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
z @ main.js:3
subscribe @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
z @ main.js:3
subscribe @ main.js:3
(anonymous) @ main.js:3
e @ polyfills.js:1
runInitializers @ main.js:3
(anonymous) @ main.js:3
ly @ main.js:3
(anonymous) @ main.js:3
invoke @ polyfills.js:1
onInvoke @ main.js:3
invoke @ polyfills.js:1
run @ polyfills.js:1
run @ main.js:3
bootstrapModuleFactory @ main.js:3
(anonymous) @ main.js:3
invoke @ polyfills.js:1
run @ polyfills.js:1
(anonymous) @ polyfills.js:1
invokeTask @ polyfills.js:1
runTask @ polyfills.js:1
_ @ polyfills.js:1
Promise.then (async)
z @ polyfills.js:1
R @ polyfills.js:1
scheduleTask @ polyfills.js:1
scheduleTask @ polyfills.js:1
scheduleMicroTask @ polyfills.js:1
ee @ polyfills.js:1
then @ polyfills.js:1
bootstrapModule @ main.js:3
708 @ main.js:3
f @ runtime.js:1
(anonymous) @ main.js:3
t @ runtime.js:1
(anonymous) @ main.js:3
main.js:3 ERROR cI {headers: Ca, status: 500, statusText: 'OK', url: 'https://paperless.amrap030.home/api/ui_settings/', ok: false, …}
handleError @ main.js:3
(anonymous) @ main.js:3
invoke @ polyfills.js:1
run @ polyfills.js:1
runOutsideAngular @ main.js:3
(anonymous) @ main.js:3
invoke @ polyfills.js:1
onInvoke @ main.js:3
invoke @ polyfills.js:1
run @ polyfills.js:1
(anonymous) @ polyfills.js:1
invokeTask @ polyfills.js:1
onInvokeTask @ main.js:3
invokeTask @ polyfills.js:1
runTask @ polyfills.js:1
_ @ polyfills.js:1
invokeTask @ polyfills.js:1
Z @ polyfills.js:1
N @ polyfills.js:1
F @ polyfills.js:1
load (async)
J.e @ polyfills.js:1
scheduleTask @ polyfills.js:1
onScheduleTask @ polyfills.js:1
scheduleTask @ polyfills.js:1
scheduleTask @ polyfills.js:1
scheduleEventTask @ polyfills.js:1
(anonymous) @ polyfills.js:1
(anonymous) @ main.js:3
_trySubscribe @ main.js:3
(anonymous) @ main.js:3
z @ main.js:3
subscribe @ main.js:3
Y @ main.js:3
F @ main.js:3
_next @ main.js:3
next @ main.js:3
(anonymous) @ main.js:3
_trySubscribe @ main.js:3
(anonymous) @ main.js:3
z @ main.js:3
subscribe @ main.js:3
tR @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
z @ main.js:3
subscribe @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
z @ main.js:3
subscribe @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
z @ main.js:3
subscribe @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
z @ main.js:3
subscribe @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
z @ main.js:3
subscribe @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
z @ main.js:3
subscribe @ main.js:3
(anonymous) @ main.js:3
e @ polyfills.js:1
runInitializers @ main.js:3
(anonymous) @ main.js:3
ly @ main.js:3
(anonymous) @ main.js:3
invoke @ polyfills.js:1
onInvoke @ main.js:3
invoke @ polyfills.js:1
run @ polyfills.js:1
run @ main.js:3
bootstrapModuleFactory @ main.js:3
(anonymous) @ main.js:3
invoke @ polyfills.js:1
run @ polyfills.js:1
(anonymous) @ polyfills.js:1
invokeTask @ polyfills.js:1
runTask @ polyfills.js:1
_ @ polyfills.js:1
Promise.then (async)
z @ polyfills.js:1
R @ polyfills.js:1
scheduleTask @ polyfills.js:1
scheduleTask @ polyfills.js:1
scheduleMicroTask @ polyfills.js:1
ee @ polyfills.js:1
then @ polyfills.js:1
bootstrapModule @ main.js:3
708 @ main.js:3
f @ runtime.js:1
(anonymous) @ main.js:3
t @ runtime.js:1
(anonymous) @ main.js:3
main.js:3 cI {headers: Ca, status: 500, statusText: 'OK', url: 'https://paperless.amrap030.home/api/ui_settings/', ok: false, …}
(anonymous) @ main.js:3
invoke @ polyfills.js:1
run @ polyfills.js:1
(anonymous) @ polyfills.js:1
invokeTask @ polyfills.js:1
runTask @ polyfills.js:1
_ @ polyfills.js:1
invokeTask @ polyfills.js:1
Z @ polyfills.js:1
N @ polyfills.js:1
F @ polyfills.js:1
load (async)
J.e @ polyfills.js:1
scheduleTask @ polyfills.js:1
onScheduleTask @ polyfills.js:1
scheduleTask @ polyfills.js:1
scheduleTask @ polyfills.js:1
scheduleEventTask @ polyfills.js:1
(anonymous) @ polyfills.js:1
(anonymous) @ main.js:3
_trySubscribe @ main.js:3
(anonymous) @ main.js:3
z @ main.js:3
subscribe @ main.js:3
Y @ main.js:3
F @ main.js:3
_next @ main.js:3
next @ main.js:3
(anonymous) @ main.js:3
_trySubscribe @ main.js:3
(anonymous) @ main.js:3
z @ main.js:3
subscribe @ main.js:3
tR @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
z @ main.js:3
subscribe @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
z @ main.js:3
subscribe @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
z @ main.js:3
subscribe @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
z @ main.js:3
subscribe @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
z @ main.js:3
subscribe @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
z @ main.js:3
subscribe @ main.js:3
(anonymous) @ main.js:3
e @ polyfills.js:1
runInitializers @ main.js:3
(anonymous) @ main.js:3
ly @ main.js:3
(anonymous) @ main.js:3
invoke @ polyfills.js:1
onInvoke @ main.js:3
invoke @ polyfills.js:1
run @ polyfills.js:1
run @ main.js:3
bootstrapModuleFactory @ main.js:3
(anonymous) @ main.js:3
invoke @ polyfills.js:1
run @ polyfills.js:1
(anonymous) @ polyfills.js:1
invokeTask @ polyfills.js:1
runTask @ polyfills.js:1
_ @ polyfills.js:1
Promise.then (async)
z @ polyfills.js:1
R @ polyfills.js:1
scheduleTask @ polyfills.js:1
scheduleTask @ polyfills.js:1
scheduleMicroTask @ polyfills.js:1
ee @ polyfills.js:1
then @ polyfills.js:1
bootstrapModule @ main.js:3
708 @ main.js:3
f @ runtime.js:1
(anonymous) @ main.js:3
t @ runtime.js:1
(anonymous) @ main.js:3
favicon.ico:1     GET https://paperless.amrap030.home/favicon.ico 500
```
```


### Paperless-ngx version

ghcr.io/paperless-ngx/paperless-ngx:latest

### Host OS

Ubuntu 20.04, Kubernetes v1.25.9+k3s1

### Installation method

Other (please describe above)

### Browser

Chrome

### Configuration changes

_No response_

### Other

_No response_

**Comment by amrap030** [comment]
> I tested normal Docker with Maria DB and a password, it works fine. Make sure you are setting `PAPERLESS_DBPASS` and `PAPERLESS_DBUSER` to the values used to create the database. This seems like a problem with your configuration and/or k3s, not paperless.

But I already declared all of the environment variables. Here you can see the secret variables which are included in mariadb deployment and paperless deployment:

https://github.com/amrap030/k3s-gitops/blob/main/cluster/argocd/secrets/paperless-mariadb-secrets.sops.yaml

And here you can see the other environment variables I am using für mariadb and paperless:

- https://github.com/amrap030/k3s-gitops/blob/main/cluster/apps/services/paperless/maria-db/base/deployment.yaml
- https://github.com/amrap030/k3s-gitops/blob/main/cluster/apps/services/paperless/base/deployment.yaml

I have another mariadb instance running under the same namespace. I am wondering if that might be the problem?

**Comment by stumpylog** [comment]
I don't know anything about Kubernetes and what all these YAML files end up doing or what a namespace is.  If the container has the environment variables set, it uses it correctly, so I would focus your efforts on determining if it is set, set correctly, etc by your setup.
