### ISSUE TITLE
[BUG] Can not upload LibreOffice files

### ISSUE THREAD

**Issue by romanbr2** [paperless-ngx/paperless-ngx#3934]
### Description

I receive the following error message:

```
muster.odt
Error while converting document to PDF: Client error '400 Bad Request' for url 'http://gotenberg:3000/forms/libreoffice/convert' For more information check: https://httpstatuses.com/400
```
I am runnig paperless 1.17 on http://localhost:9000 

### Steps to reproduce

1. upload a LibreOffice .odt file
2. see error

### Webserver logs

```bash
[2023-08-06 10:39:59,264] [ERROR] [paperless.consumer] Error while consuming document muster.odt: Error while converting document to PDF: Client error '400 Bad Request' for url 'http://gotenberg:3000/forms/libreoffice/convert'

For more information check: https://httpstatuses.com/400

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_tika/parsers.py", line 105, in convert_to_pdf

    response.raise_for_status()  # ensure we notice bad responses

  File "/usr/local/lib/python3.9/site-packages/httpx/_models.py", line 749, in raise_for_status

    raise HTTPStatusError(message, request=request, response=self)

httpx.HTTPStatusError: Client error '400 Bad Request' for url 'http://gotenberg:3000/forms/libreoffice/convert'

For more information check: https://httpstatuses.com/400

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/consumer.py", line 424, in try_consume_file

    document_parser.parse(self.path, mime_type, self.filename)

  File "/usr/src/paperless/src/paperless_tika/parsers.py", line 70, in parse

    self.archive_path = self.convert_to_pdf(document_path, file_name)

  File "/usr/src/paperless/src/paperless_tika/parsers.py", line 107, in convert_to_pdf

    raise ParseError(

documents.parsers.ParseError: Error while converting document to PDF: Client error '400 Bad Request' for url 'http://gotenberg:3000/forms/libreoffice/convert'

For more information check: https://httpstatuses.com/400
```

### Paperless-ngx version

1.17

### Host OS

ubuntu 22.04

### Installation method

Docker - official image

### Browser

Chrome

**Comment by romanbr2** [comment]
It was my error:

After change my docker-compose.yml from:

```
gotenberg:
    image: docker.io/gotenberg/gotenberg:7.4
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-routes=true"
    ports:
      - 3000:3000

```
to

```
gotenberg:
    image: docker.io/gotenberg/gotenberg:7.8
    restart: unless-stopped

    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp
```
everything works fine.

Maybe you could add a note in the release notes if the docker-compose.yml file needs to be changed.
