### ISSUE TITLE
[BUG] Concise description of the issue

### ISSUE THREAD

**Issue by Alexander-Wilms** [paperless-ngx/paperless-ngx#3938]
### Description

Using the Docker install script, I still seem to encounter https://github.com/paperless-ngx/paperless-ngx/issues/3568

<details>
<summary>Terminal output</summary>

```
alexander@PC:~> bash -c "$(curl -L https://raw.githubusercontent.com/paperless-ngx/paperless-ngx/main/install-paperless-ngx.sh)"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11417  100 11417    0     0  56944      0 --:--:-- --:--:-- --:--:-- 57085
/usr/bin/docker-compose

#############################################
###   paperless-ngx docker installation   ###
#############################################

This script will download, configure and start paperless-ngx.

1. Application configuration
============================

The URL paperless will be available at. This is required if the
installation will be accessible via the web, otherwise can be left blank.
Example: https://paperless.example.com

URL []: 

The port on which the paperless webserver will listen for incoming
connections.

Port [8000]: 

Paperless requires you to configure the current time zone correctly.
Otherwise, the dates of your documents may appear off by one day,
depending on where you are on earth.
Example: Europe/Berlin
See here for a list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

Current time zone [Europe/Berlin]: 

Database backend: PostgreSQL, MariaDB, and SQLite are available. Use PostgreSQL
if unsure. If you're running on a low-power device such as Raspberry
Pi, use SQLite to save resources.

Database backend (postgres sqlite mariadb) [postgres]: 

Paperless is able to use Apache Tika to support Office documents such as
Word, Excel, Powerpoint, and Libreoffice equivalents. This feature
requires more resources due to the required services.

Enable Apache Tika? (yes no) [no]: 

Specify the default language that most of your documents are written in.
Use ISO 639-2, (T) variant language codes: 
https://www.loc.gov/standards/iso639-2/php/code_list.php
Common values: eng (English) deu (German) nld (Dutch) fra (French)
This can be a combination of multiple languages such as deu+eng

OCR language [eng]: deu

Specify the user id and group id you wish to run paperless as.
Paperless will also change ownership on the data, media and consume
folder to the specified values, so it's a good idea to supply the user id
and group id of your unix user account.
If unsure, leave default.

User ID [1000]: 
Group ID [1000]: 

2. Folder configuration
=======================

The target folder is used to store the configuration files of 
paperless. You can move this folder around after installing paperless.
You will need this folder whenever you want to start, stop, update or 
maintain your paperless instance.

Target folder [/home/alexander/paperless-ngx]: 

The consume folder is where paperless will search for new documents.
Point this to a folder where your scanner is able to put your scanned
documents.

CAUTION: You must specify an absolute path starting with / or a relative 
path starting with ./ here. Examples:
  /mnt/consume
  ./consume

Consume folder [/home/alexander/paperless-ngx/consume]: 

The media folder is where paperless stores your documents.
Leave empty and docker will manage this folder for you.
Docker usually stores managed folders in /var/lib/docker/volumes.

CAUTION: If specified, you must specify an absolute path starting with /
or a relative path starting with ./ here.

Media folder []: 

The data folder is where paperless stores other data, such as your
search index and other data.
As with the media folder, leave empty to have this managed by docker.

CAUTION: If specified, you must specify an absolute path starting with /
or a relative path starting with ./ here.

Data folder []: 

The database folder, where your database stores its data.
Leave empty to have this managed by docker.

CAUTION: If specified, you must specify an absolute path starting with /
or a relative path starting with ./ here.

Database folder []: 

3. Login credentials
====================

Specify initial login credentials. You can change these later.
A mail address is required, however it is not used in paperless. You don't
need to provide an actual mail address.

Paperless username [alexander]: 
Paperless password: 
Paperless password (again): 
Email [alexander@localhost]: 

Summary
=======

Target folder: /home/alexander/paperless-ngx
Consume folder: /home/alexander/paperless-ngx/consume
Media folder: Managed by docker
Data folder: Managed by docker
Database folder: Managed by docker

URL: 
Port: 8000
Database: postgres
Tika enabled: no
OCR language: deu
User id: 1000
Group id: 1000

Paperless username: alexander
Paperless email: alexander@localhost

Press any key to install.

Installing paperless...

--2023-08-06 15:10:35--  https://raw.githubusercontent.com/paperless-ngx/paperless-ngx/main/docker/compose/docker-compose.postgres.yml
Auflösen des Hostnamens raw.githubusercontent.com (raw.githubusercontent.com)… 2606:50c0:8000::154, 2606:50c0:8002::154, 2606:50c0:8003::154, ...
Verbindungsaufbau zu raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8000::154|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 200 OK
Länge: 2221 (2,2K) [text/plain]
Wird in »docker-compose.yml« gespeichert.

docker-compose.yml                           100%[============================================================================================>]   2,17K  --.-KB/s    in 0s      

2023-08-06 15:10:35 (41,2 MB/s) - »docker-compose.yml« gespeichert [2221/2221]

--2023-08-06 15:10:35--  https://raw.githubusercontent.com/paperless-ngx/paperless-ngx/main/docker/compose/.env
Auflösen des Hostnamens raw.githubusercontent.com (raw.githubusercontent.com)… 2606:50c0:8000::154, 2606:50c0:8002::154, 2606:50c0:8003::154, ...
Verbindungsaufbau zu raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8000::154|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 200 OK
Länge: 31 [text/plain]
Wird in ».env« gespeichert.

.env                                         100%[============================================================================================>]      31  --.-KB/s    in 0s      

2023-08-06 15:10:35 (2,73 MB/s) - ».env« gespeichert [31/31]

[+] Pulling 3/3
 ✔ db Pulled                                                                                                                                                                 1.3s 
 ✔ webserver Pulled                                                                                                                                                          0.6s 
 ✔ broker Pulled                                                                                                                                                             1.4s 
Starting DB first for initilzation
[+] Running 1/0
 ✔ Container paperless-db-1  Started                                                                                                                                         0.0s 
[+] Stopping 2/2
 ✔ Container paperless-broker-1  Stopped                                                                                                                                     0.5s 
 ✔ Container paperless-db-1      Stopped                                                                                                                                     0.0s 
[+] Creating 2/0
 ✔ Container paperless-db-1      Created                                                                                                                                     0.0s 
 ✔ Container paperless-broker-1  Created                                                                                                                                     0.0s 
[+] Running 2/2
 ✔ Container paperless-db-1      Started                                                                                                                                     0.6s 
 ✔ Container paperless-broker-1  Started                                                                                                                                     0.6s 
Paperless-ngx docker container starting...
Creating directory /tmp/paperless
Adjusting permissions of paperless files. This may take a while.
Waiting for PostgreSQL to start...
Waiting for Redis...
Connected to Redis broker.
Apply database migrations...
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 263, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 215, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "db" (172.20.0.2), port 5432 failed: No route to host
        Is the server running on that host and accepting TCP/IP connections?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 114, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/loader.py", line 58, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/loader.py", line 235, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 81, in applied_migrations
    if self.has_table():
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 57, in has_table
    with self.connection.cursor() as cursor:
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 323, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 299, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 263, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 215, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: connection to server at "db" (172.20.0.2), port 5432 failed: No route to host
        Is the server running on that host and accepting TCP/IP connections?
alexander@PC:~> docker ps
CONTAINER ID   IMAGE         COMMAND                  CREATED        STATUS                          PORTS      NAMES
e4a63e251b42   redis:7       "docker-entrypoint.s…"   23 hours ago   Up 5 minutes                    6379/tcp   paperless-broker-1
e0b7d1121540   postgres:15   "docker-entrypoint.s…"   23 hours ago   Restarting (1) 49 seconds ago              paperless-db-1
alexander@PC:~> docker --version
Docker version 24.0.5-ce, build a61e2b4c9
alexander@PC:~> docker image ls
REPOSITORY                            TAG       IMAGE ID       CREATED        SIZE
ghcr.io/paperless-ngx/paperless-ngx   latest    8bc90ab7f1a1   43 hours ago   1.41GB
redis                                 7         e0ce02f88e58   8 days ago     130MB
postgres                              15        8769343ac885   9 days ago     412MB
```
</details>

### Steps to reproduce

1. Use an up to date openSUSE Tumbleweed
2. Run `bash -c "$(curl -L https://raw.githubusercontent.com/paperless-ngx/paperless-ngx/main/install-paperless-ngx.sh)"`

### Webserver logs

```bash
ghcr.io/paperless-ngx/paperless-ngx:latest

Paperless-ngx docker container starting...
Creating directory /usr/src/paperless/data/index
Creating directory /usr/src/paperless/media/documents
Creating directory /usr/src/paperless/media/documents/originals
Creating directory /usr/src/paperless/media/documents/thumbnails
Creating directory /tmp/paperless
Adjusting permissions of paperless files. This may take a while.
Waiting for Redis...
Redis ping #0 failed.
Error: Error 99 connecting to localhost:6379. Cannot assign requested address..
Waiting 5s
Redis ping #1 failed.
Error: Error 99 connecting to localhost:6379. Cannot assign requested address..
Waiting 5s
Redis ping #2 failed.
Error: Error 99 connecting to localhost:6379. Cannot assign requested address..
Waiting 5s
Redis ping #3 failed.
Error: Error 99 connecting to localhost:6379. Cannot assign requested address..
Waiting 5s
Redis ping #4 failed.
Error: Error 99 connecting to localhost:6379. Cannot assign requested address..
Waiting 5s
Failed to connect to redis using environment variable PAPERLESS_REDIS.
Paperless-ngx docker container starting...
Creating directory /tmp/paperless
Adjusting permissions of paperless files. This may take a while.
Waiting for Redis...
Redis ping #0 failed.
Error: Error 99 connecting to localhost:6379. Cannot assign requested address..
Waiting 5s
Redis ping #1 failed.
Error: Error 99 connecting to localhost:6379. Cannot assign requested address..
Waiting 5s
Redis ping #2 failed.
Error: Error 99 connecting to localhost:6379. Cannot assign requested address..
Waiting 5s
Redis ping #3 failed.
Error: Error 99 connecting to localhost:6379. Cannot assign requested address..
Waiting 5s
Redis ping #4 failed.
Error: Error 99 connecting to localhost:6379. Cannot assign requested address..
Waiting 5s
Failed to connect to redis using environment variable PAPERLESS_REDIS.
Paperless-ngx docker container starting...
Creating directory /tmp/paperless
Adjusting permissions of paperless files. This may take a while.
Waiting for Redis...
Redis ping #0 failed.
Error: Error 99 connecting to localhost:6379. Cannot assign requested address..
Waiting 5s
Redis ping #1 failed.
Error: Error 99 connecting to localhost:6379. Cannot assign requested address..
Waiting 5s
Redis ping #2 failed.
Error: Error 99 connecting to localhost:6379. Cannot assign requested address..
Waiting 5s
Redis ping #3 failed.
Error: Error 99 connecting to localhost:6379. Cannot assign requested address..
Waiting 5s
Redis ping #4 failed.
Error: Error 99 connecting to localhost:6379. Cannot assign requested address..
Waiting 5s
Failed to connect to redis using environment variable PAPERLESS_REDIS.
```

docker.io/library/redis:7
```
1:C 05 Aug 2023 14:24:21.376 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 05 Aug 2023 14:24:21.376 # Redis version=7.0.12, bits=64, commit=00000000, modified=0, pid=1, just started
�1:C 05 Aug 2023 14:24:21.376 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
1:M 05 Aug 2023 14:24:21.376 * monotonic clock: POSIX clock_gettime
1:M 05 Aug 2023 14:24:21.377 * Running mode=standalone, port=6379.
1:M 05 Aug 2023 14:24:21.377 # Server initialized
�1:M 05 Aug 2023 14:24:21.377 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 05 Aug 2023 14:24:21.378 * Loading RDB produced by version 7.0.10
1:M 05 Aug 2023 14:24:21.378 * RDB age 9499975 seconds
1:M 05 Aug 2023 14:24:21.378 * RDB memory usage when created 1.39 Mb
1:M 05 Aug 2023 14:24:21.378 * Done loading RDB, keys loaded: 3, keys expired: 0.
1:M 05 Aug 2023 14:24:21.378 * DB loaded from disk: 0.001 seconds
1:M 05 Aug 2023 14:24:21.378 * Ready to accept connections
1:C 06 Aug 2023 01:40:41.860 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 06 Aug 2023 01:40:41.861 # Redis version=7.0.12, bits=64, commit=00000000, modified=0, pid=1, just started
�1:C 06 Aug 2023 01:40:41.861 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
1:M 06 Aug 2023 01:40:41.863 * monotonic clock: POSIX clock_gettime
1:M 06 Aug 2023 01:40:41.864 * Running mode=standalone, port=6379.
1:M 06 Aug 2023 01:40:41.864 # Server initialized
�1:M 06 Aug 2023 01:40:41.864 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 06 Aug 2023 01:40:41.866 * Loading RDB produced by version 7.0.10
1:M 06 Aug 2023 01:40:41.866 * RDB age 9540555 seconds
1:M 06 Aug 2023 01:40:41.866 * RDB memory usage when created 1.39 Mb
1:M 06 Aug 2023 01:40:41.866 * Done loading RDB, keys loaded: 3, keys expired: 0.
1:M 06 Aug 2023 01:40:41.866 * DB loaded from disk: 0.001 seconds
1:M 06 Aug 2023 01:40:41.866 * Ready to accept connections
1:C 06 Aug 2023 03:06:25.631 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 06 Aug 2023 03:06:25.631 # Redis version=7.0.12, bits=64, commit=00000000, modified=0, pid=1, just started
�1:C 06 Aug 2023 03:06:25.631 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
1:M 06 Aug 2023 03:06:25.632 * monotonic clock: POSIX clock_gettime
1:M 06 Aug 2023 03:06:25.633 * Running mode=standalone, port=6379.
1:M 06 Aug 2023 03:06:25.633 # Server initialized
�1:M 06 Aug 2023 03:06:25.633 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 06 Aug 2023 03:06:25.634 * Loading RDB produced by version 7.0.10
1:M 06 Aug 2023 03:06:25.634 * RDB age 9545699 seconds
1:M 06 Aug 2023 03:06:25.634 * RDB memory usage when created 1.39 Mb
1:M 06 Aug 2023 03:06:25.634 * Done loading RDB, keys loaded: 3, keys expired: 0.
1:M 06 Aug 2023 03:06:25.634 * DB loaded from disk: 0.001 seconds
1:M 06 Aug 2023 03:06:25.634 * Ready to accept connections
1:signal-handler (1691327452) Received SIGTERM scheduling shutdown...
1:M 06 Aug 2023 13:10:52.465 # User requested shutdown...
1:M 06 Aug 2023 13:10:52.465 * Saving the final RDB snapshot before exiting.
1:M 06 Aug 2023 13:10:52.514 * DB saved on disk
1:M 06 Aug 2023 13:10:52.514 # Redis is now ready to exit, bye bye...
1:C 06 Aug 2023 13:10:53.477 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 06 Aug 2023 13:10:53.477 # Redis version=7.0.12, bits=64, commit=00000000, modified=0, pid=1, just started
�1:C 06 Aug 2023 13:10:53.477 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
1:M 06 Aug 2023 13:10:53.477 * monotonic clock: POSIX clock_gettime
1:M 06 Aug 2023 13:10:53.478 * Running mode=standalone, port=6379.
1:M 06 Aug 2023 13:10:53.478 # Server initialized
�1:M 06 Aug 2023 13:10:53.478 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 06 Aug 2023 13:10:53.506 * Loading RDB produced by version 7.0.12
1:M 06 Aug 2023 13:10:53.506 * RDB age 1 seconds
1:M 06 Aug 2023 13:10:53.506 * RDB memory usage when created 0.83 Mb
1:M 06 Aug 2023 13:10:53.506 * Done loading RDB, keys loaded: 3, keys expired: 0.
1:M 06 Aug 2023 13:10:53.506 * DB loaded from disk: 0.028 seconds
1:M 06 Aug 2023 13:10:53.506 * Ready to accept connections
```

docker.io/library/postgres:15:
```
PostgreSQL Database directory appears to contain a database; Skipping initialization

2023-08-06 02:25:01.508 UTC [1] FATAL:  database files are incompatible with server
�2023-08-06 02:25:01.508 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 13, which is not compatible with this version 15.3 (Debian 15.3-1.pgdg120+1).
```
```


### Browser logs

_No response_

### Paperless-ngx version

1.17.0

### Host OS

openSUSE Tumbleweed

### Installation method

Docker - official image

### Browser

_No response_

### Configuration changes

_No response_

### Other

_No response_

**Comment by shamoon** [comment]
Generally speaking there’s only so much an install script can do to get a working setup, there will always potentially be issues on different distros / setups etc. so if your other containers aren’t running you’ll need to troubleshoot them
