### ISSUE TITLE
[BUG] SubprocessOutputError 

### ISSUE THREAD

**Issue by jensfr1** [paperless-ngx/paperless-ngx#3974]
### Description

I am using the service from Deutsche Post Postscan. Donwloaded files (and only those) go into error. When I open and print the dowloaded pdf into a new pdf all works well. 

### Steps to reproduce

Download my Post from Deutsche Post.
Just upload and wait.

### Webserver logs

```bash
[2023-08-11 08:21:16,197] [ERROR] [paperless.consumer] Error while consuming document Postscan_230811_MA23221-002497.pdf: SubprocessOutputError:

Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_exec/tesseract.py", line 220, in get_deskew

    p = run(args_tesseract, stdout=PIPE, stderr=STDOUT, timeout=timeout, check=True)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/subprocess/__init__.py", line 62, in run

    proc = subprocess_run(args, env=env, check=check, **kwargs)

  File "/usr/local/lib/python3.9/subprocess.py", line 528, in run

    raise CalledProcessError(retcode, process.args,

subprocess.CalledProcessError: Command '['tesseract', '-l', 'deu', '--psm', '2', '/tmp/ocrmypdf.io.mmgsvt14/000008_rasterize.png', 'stdout']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 320, in parse

    ocrmypdf.ocr(**args)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/api.py", line 347, in ocr

    return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 391, in run_pipeline

    optimize_messages = exec_concurrent(context, executor)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 279, in exec_concurrent

    executor(

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_concurrent.py", line 85, in __call__

    self._execute(

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/builtin_plugins/concurrency.py", line 141, in _execute

    result = future.result()

  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result

    return self.__get_result()

  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result

    raise self._exception

  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run

    result = self.fn(*self.args, **self.kwargs)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 196, in exec_page_sync

    ocr_image, preprocess_out = make_intermediate_images(

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 139, in make_intermediate_images

    preprocess_out = preprocess(

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 110, in preprocess

    image = preprocess_deskew(image, page_context)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 530, in preprocess_deskew

    deskew_angle_degrees = ocr_engine.get_deskew(input_file, page_context.options)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/builtin_plugins/tesseract_ocr.py", line 227, in get_deskew

    return tesseract.get_deskew(

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_exec/tesseract.py", line 231, in get_deskew

    raise SubprocessOutputError() from e

ocrmypdf.exceptions.SubprocessOutputError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/consumer.py", line 424, in try_consume_file

    document_parser.parse(self.path, mime_type, self.filename)

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 377, in parse

    raise ParseError(f"{e.__class__.__name__}: {e!s}") from e

documents.parsers.ParseError: SubprocessOutputError:
```

### Paperless-ngx version

1.17

### Host OS

Debian

### Installation method

Docker - official image

### Browser

Chrome

### Configuration changes

Fresh install with the install script. 

### Other

Related to this issue: https://github.com/paperless-ngx/paperless-ngx/issues/3933

**Comment by jensfr1** [comment]
Maybe it can be due to compressed pdf files? Once I have printed that PDF the file size increases from 550 kb to 20MB.

**Comment by jensfr1** [comment]
I found the problem. The PDF had empty pages which caused the issue. @stumpylog

**Comment by stumpylog** [comment]
ocrmypdf/OCRmyPDF/issues/868 most likely then.  As suggested, you can disable deskew for consuming this document.  Nothing else we can do from our side.
