### ISSUE TITLE
[BUG] Ghostscript PDF/A rendering failed

### ISSUE THREAD

**Issue by nunoqv** [paperless-ngx/paperless-ngx#4004]
### Description

Adding a PDF file return this error.

### Steps to reproduce

Add a PDF file.

### Webserver logs

```bash
[2023-08-16 11:51:17,306] [ERROR] [paperless.consumer] Error while consuming document FADT2301166.pdf: SubprocessOutputError: Ghostscript PDF/A rendering failed

Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_exec/ghostscript.py", line 232, in generate_pdfa

    p = run_polling_stderr(

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/subprocess/__init__.py", line 114, in run_polling_stderr

    raise CalledProcessError(proc.returncode, args, output=None, stderr=stderr)

subprocess.CalledProcessError: Command '['gs', '-dBATCH', '-dNOPAUSE', '-dSAFER', '-dCompatibilityLevel=1.6', '-sDEVICE=pdfwrite', '-dAutoRotatePages=/None', '-sColorConversionStrategy=LeaveColorUnchanged', '-dPDFSTOPONERROR', '-dAutoFilterColorImages=true', '-dAutoFilterGrayImages=true', '-dJPEGQ=95', '-dPDFA=2', '-dPDFACompatibilityPolicy=1', '-o', '-', '-sstdout=%stderr', '/tmp/ocrmypdf.io.3j16w58d/fix_docinfo.pdf', '/tmp/ocrmypdf.io.3j16w58d/pdfa.ps']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 320, in parse

    ocrmypdf.ocr(**args)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/api.py", line 347, in ocr

    return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 391, in run_pipeline

    optimize_messages = exec_concurrent(context, executor)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 308, in exec_concurrent

    pdf, messages = post_process(pdf, context, executor)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 239, in post_process

    pdf_out = convert_to_pdfa(pdf_out, ps_stub_out, context)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 789, in convert_to_pdfa

    context.plugin_manager.hook.generate_pdfa(

  File "/usr/local/lib/python3.9/site-packages/pluggy/_hooks.py", line 433, in __call__

    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)

  File "/usr/local/lib/python3.9/site-packages/pluggy/_manager.py", line 112, in _hookexec

    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)

  File "/usr/local/lib/python3.9/site-packages/pluggy/_callers.py", line 116, in _multicall

    raise exception.with_traceback(exception.__traceback__)

  File "/usr/local/lib/python3.9/site-packages/pluggy/_callers.py", line 80, in _multicall

    res = hook_impl.function(*args)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/builtin_plugins/ghostscript.py", line 77, in generate_pdfa

    ghostscript.generate_pdfa(

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_exec/ghostscript.py", line 246, in generate_pdfa

    raise SubprocessOutputError('Ghostscript PDF/A rendering failed') from e

ocrmypdf.exceptions.SubprocessOutputError: Ghostscript PDF/A rendering failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/consumer.py", line 425, in try_consume_file

    document_parser.parse(self.path, mime_type, self.filename)

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 377, in parse

    raise ParseError(f"{e.__class__.__name__}: {e!s}") from e

documents.parsers.ParseError: SubprocessOutputError: Ghostscript PDF/A rendering failed
```

### Browser logs

```bash
FADT2301166.pdf: Error while consuming document FADT2301166.pdf: SubprocessOutputError: Ghostscript PDF/A rendering failed
```

### Paperless-ngx version

1.17.1

### Host OS

Debian 12

### Installation method

Docker - official image

### Browser

Edge

**Comment by piscinas** [comment]
Sorry i have created the error with old account...
