### ISSUE TITLE
[BUG] Webserver database migration failed after Update to 1.17.1

### ISSUE THREAD

**Issue by bmBenmayer** [paperless-ngx/paperless-ngx#4034]
### Description

After standard update and start via docker-compose up, the "apply database migrations" task failed. Webserver is not working.

### Steps to reproduce

1. docker-compose down
2. docker-compose pull
3. docker-compose up

### Webserver logs

```bash
webserver_1  | Creating directory /tmp/paperless
webserver_1  | Adjusting permissions of paperless files. This may take a while.
webserver_1  | Waiting for PostgreSQL to start...
webserver_1  | Waiting for Redis...
webserver_1  | Connected to Redis broker.
webserver_1  | Apply database migrations...
webserver_1  | Traceback (most recent call last):
webserver_1  |   File "/usr/src/paperless/src/manage.py", line 10, in <module>
webserver_1  |     execute_from_command_line(sys.argv)
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
webserver_1  |     utility.execute()
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 386, in execute
webserver_1  |     settings.INSTALLED_APPS
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 92, in __getattr__
webserver_1  |     self._setup(name)
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 79, in _setup
webserver_1  |     self._wrapped = Settings(settings_module)
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 190, in __init__
webserver_1  |     mod = importlib.import_module(self.SETTINGS_MODULE)
webserver_1  |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
webserver_1  |     return _bootstrap._gcd_import(name[level:], package, level)
webserver_1  |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
webserver_1  |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
webserver_1  |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
webserver_1  |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
webserver_1  |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
webserver_1  |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
webserver_1  |   File "/usr/src/paperless/src/paperless/settings.py", line 696, in <module>
webserver_1  |     CELERY_BEAT_SCHEDULE = _parse_beat_schedule()
webserver_1  |   File "/usr/src/paperless/src/paperless/settings.py", line 206, in _parse_beat_schedule
webserver_1  |     minute, hour, day_month, month, day_week = value.split(" ")
webserver_1  | ValueError: too many values to unpack (expected 5)
```

### Paperless-ngx version

1.17.1

### Host OS

Debian 12

### Installation method

Docker - official image

### Browser

Chrome

### Configuration changes

Update

**Comment by shamoon** [comment]
Can you try removing the `data/celerybeat-schedule.db` file and re-creating the container

**Comment by bmBenmayer** [comment]
I tried, but did not help :-(
Still the same error and the celeryeat-schedule.db was recreated

**Comment by bmBenmayer** [comment]
Correction: celerybeat-schedule.db was not recreated. It is still deleted

**Comment by stumpylog** [comment]
- The error has nothing to do with migrations, I updated the title to reflect that
- You must be setting one or more of the `*_CRON` configuration values and it must be incorrectly formatted.  See the `crontab(5)` format

**Comment by bmBenmayer** [comment]
You are absolutely right. I removed the Mail polling cron setting in docker-composer.env. After that it runs normal.
Tanks for you help.
