### ISSUE TITLE
[BUG] Invoice from internet provider not consumed

### ISSUE THREAD

**Issue by pocelka** [paperless-ngx/paperless-ngx#4056]
### Description

I've been trying to add PDF invoice from my internet provider, but it was not processed from consume folder. Please see attached error log.

### Steps to reproduce

n/a

### Webserver logs

```bash
[2023-08-23 19:05:15,869] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/Orange_doklad_CN0197210594_20230821_FR39037200073052.pdf to the task queue.

[2023-08-23 19:05:15,900] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: /usr/src/paperless/consume

[2023-08-23 19:05:16,150] [INFO] [paperless.consumer] Consuming Orange_doklad_CN0197210594_20230821_FR39037200073052.pdf

[2023-08-23 19:05:16,151] [DEBUG] [paperless.consumer] Detected mime type: application/pdf

[2023-08-23 19:05:16,151] [INFO] [paperless.consumer] Executing pre-consume script /usr/src/paperless/scripts/remove_password.py

[2023-08-23 19:05:16,237] [INFO] [paperless.consumer] /usr/src/paperless/scripts/remove_password.py exited 0

[2023-08-23 19:05:16,237] [INFO] [paperless.consumer] Script stdout:

[2023-08-23 19:05:16,237] [INFO] [paperless.consumer] Script Debug: Reading passwords

[2023-08-23 19:05:16,237] [WARNING] [paperless.consumer] Script stderr:

[2023-08-23 19:05:16,238] [WARNING] [paperless.consumer] /usr/local/lib/python3.9/site-packages/pikepdf/_methods.py:833: UserWarning: A password was provided, but no password was needed to open this PDF.

[2023-08-23 19:05:16,238] [WARNING] [paperless.consumer]   pdf = Pdf._open(

[2023-08-23 19:05:16,238] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser

[2023-08-23 19:05:16,240] [DEBUG] [paperless.consumer] Parsing Orange_doklad_CN0197210594_20230821_FR39037200073052.pdf...

[2023-08-23 19:05:16,315] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-ngxr2o4e1h0/Orange_doklad_CN0197210594_20230821_FR39037200073052.pdf'), 'output_file': PosixPath('/tmp/paperless/paperless-f4fqfg3g/archive.pdf'), 'use_threads': True, 'jobs': 12, 'language': 'slk+eng', 'output_type': 'pdfa', 'progress_bar': False, 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-f4fqfg3g/sidecar.txt')}

[2023-08-23 19:05:16,531] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-f4fqfg3g

[2023-08-23 19:05:16,534] [ERROR] [paperless.consumer] Error while consuming document Orange_doklad_CN0197210594_20230821_FR39037200073052.pdf: SubprocessOutputError: Ghostscript PDF/A rendering failed

Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_exec/ghostscript.py", line 232, in generate_pdfa

    p = run_polling_stderr(

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/subprocess/__init__.py", line 114, in run_polling_stderr

    raise CalledProcessError(proc.returncode, args, output=None, stderr=stderr)

subprocess.CalledProcessError: Command '['gs', '-dBATCH', '-dNOPAUSE', '-dSAFER', '-dCompatibilityLevel=1.6', '-sDEVICE=pdfwrite', '-dAutoRotatePages=/None', '-sColorConversionStrategy=LeaveColorUnchanged', '-dPDFSTOPONERROR', '-dAutoFilterColorImages=true', '-dAutoFilterGrayImages=true', '-dJPEGQ=95', '-dPDFA=2', '-dPDFACompatibilityPolicy=1', '-o', '-', '-sstdout=%stderr', '/tmp/ocrmypdf.io.rrhqy396/fix_docinfo.pdf', '/tmp/ocrmypdf.io.rrhqy396/pdfa.ps']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 320, in parse

    ocrmypdf.ocr(**args)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/api.py", line 347, in ocr

    return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 391, in run_pipeline

    optimize_messages = exec_concurrent(context, executor)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 308, in exec_concurrent

    pdf, messages = post_process(pdf, context, executor)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 239, in post_process

    pdf_out = convert_to_pdfa(pdf_out, ps_stub_out, context)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 789, in convert_to_pdfa

    context.plugin_manager.hook.generate_pdfa(

  File "/usr/local/lib/python3.9/site-packages/pluggy/_hooks.py", line 433, in __call__

    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)

  File "/usr/local/lib/python3.9/site-packages/pluggy/_manager.py", line 112, in _hookexec

    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)

  File "/usr/local/lib/python3.9/site-packages/pluggy/_callers.py", line 116, in _multicall

    raise exception.with_traceback(exception.__traceback__)

  File "/usr/local/lib/python3.9/site-packages/pluggy/_callers.py", line 80, in _multicall

    res = hook_impl.function(*args)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/builtin_plugins/ghostscript.py", line 77, in generate_pdfa

    ghostscript.generate_pdfa(

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_exec/ghostscript.py", line 246, in generate_pdfa

    raise SubprocessOutputError('Ghostscript PDF/A rendering failed') from e

ocrmypdf.exceptions.SubprocessOutputError: Ghostscript PDF/A rendering failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/consumer.py", line 424, in try_consume_file

    document_parser.parse(self.path, mime_type, self.filename)

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 377, in parse

    raise ParseError(f"{e.__class__.__name__}: {e!s}") from e

documents.parsers.ParseError: SubprocessOutputError: Ghostscript PDF/A rendering failed
```

### Paperless-ngx version

1.17.0

### Host OS

Fedora 38

### Installation method

Docker - official image

**Comment by stumpylog** [comment]
It's quite clearly coming from inside `ocrmypdf`, and deeper down in there from Ghostscript itself.  See also #3933 and #4004.  We provide some settings you can adjust, but we can't fix an error either in particular PDFs, OCRmyPDF or Ghostscript.

If you don't need the PDF/A output, you could change that output.  Or not produce an archive for this file.  Or try cleaning the file with QPDF.  There's a lot of settings for controlling OCR that are passed to `ocrmypdf`.  Some combination of those may work for this PDF.
