### ISSUE TITLE
Paperless bare Metall update issue

### ISSUE THREAD

**Issue by MrThiemann** [paperless-ngx/paperless-ngx#4261]
### Description

When I try to update paperless (from 1.13.0 to 1.17.4) I end up getting the error: subprocess-exited-with-error

<img width="1258" alt="Bildschirm­foto 2023-09-25 um 14 35 24" src="https://github.com/paperless-ngx/paperless-ngx/assets/54147030/afa8758f-a8af-471d-807f-07c027252fd0">

### Steps to reproduce

sudo apt update -y
sudo apt upgrade -y
sudo -Hu paperless pip3 install --upgrade pip

download latest [Paperless-ngx v1.17.4](https://github.com/paperless-ngx/paperless-ngx/releases/tag/v1.17.4)
tar xf paperless-ngx-v1.17.4.tar.xz
mv paperless-ngx paperless
cp paperless /opt

cd /opt/paperless
sudo -Hu paperless pip3 install --upgrade -r requirements.txt

(The upgrade starts and the necessary packages are downloaded.)

### Webserver logs

```bash
`  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      /bin/sh: 1: pkg-config: not found
      /bin/sh: 1: pkg-config: not found
      Trying pkg-config --exists mysqlclient
      Command 'pkg-config --exists mysqlclient' returned non-zero exit status 127.
      Trying pkg-config --exists mariadb
      Command 'pkg-config --exists mariadb' returned non-zero exit status 127.
      Traceback (most recent call last):
        File "/opt/paperless/.local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/paperless/.local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/paperless/.local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-pg1r_uo8/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-pg1r_uo8/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-pg1r_uo8/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 154, in <module>
        File "<string>", line 48, in get_config_posix
        File "<string>", line 27, in find_package_name
      Exception: Can not find valid pkg-config name.
      Specify MYSQLCLIENT_CFLAGS and MYSQLCLIENT_LDFLAGS env vars manually
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
`
```

### Paperless-ngx version

1.13.0

### Host OS

root@paperless:/opt/paperless# uname -m x86_64

### Installation method

Bare metal

**Comment by stumpylog** [comment]
You're missing `pkg-config` or the equivalent name for your system.  This is listed in the bare metal dependencies documentation.

**Comment by MrThiemann** [comment]
Thank you, that has brought me quite a bit further.
However, now I get another error message.
can you help with that too?

![Bildschirm­foto 2023-09-25 um 17 34 17](https://github.com/paperless-ngx/paperless-ngx/assets/54147030/f059c6af-88fe-4ce1-9e8b-a4978d55993d)

**Comment by stumpylog** [comment]
`django-q` hasn't been a dependency for many many versions.  You should remove packages not required or re-create the virtual environment
