### ISSUE TITLE
[BUG] Processing frequently fails, but sometimes works...

### ISSUE THREAD

**Issue by 2600box** [paperless-ngx/paperless-ngx#429]
**Describe the bug**
Processing of new files frequently fails.

**To Reproduce**
Copy a file to consume directory - appears to randomly not process...

**Expected behavior**
Process files normally.

**Webserver logs**
```
scan_20220318095033.pdf

[HISTORY](http://10.0.0.50:8000/admin/django_q/failure/bab2ca01d22a4468879a3957d8b20187/history/?_changelist_filters=q%3Dscan_20220318095033.pdf)

Id:
bab2ca01d22a4468879a3957d8b20187
Name:
scan_20220318095033.pdf
Func:
documents.tasks.consume_file
Hook:
-
Args:
/tmp/paperless/paperless-upload-rpm12730
Kwargs:
{'override_filename': 'scan_20220318095033.pdf', 'override_title': None, 'override_correspondent_id': None, 'override_document_type_id': None, 'override_tag_ids': None, 'task_id': '19bd9a40-959d-4b65-a1f5-efa2ece0b0f0'}
Result:
scan_20220318095033.pdf: Error while consuming document scan_20220318095033.pdf: SubprocessOutputError: : Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_exec/tesseract.py", line 226, in get_deskew
p = run(args_tesseract, stdout=PIPE, stderr=STDOUT, timeout=timeout, check=True)
File "/usr/local/lib/python3.9/site-packages/ocrmypdf/subprocess/__init__.py", line 53, in run
proc = subprocess_run(args, env=env, **kwargs)
File "/usr/local/lib/python3.9/subprocess.py", line 528, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['tesseract', '-l', 'eng', '--psm', '2', '/tmp/ocrmypdf.io.ny_ea_s_/000001_rasterize.png', 'stdout']' died with <Signals.SIGKILL: 9>.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 249, in parse
ocrmypdf.ocr(**args)
File "/usr/local/lib/python3.9/site-packages/ocrmypdf/api.py", line 337, in ocr
return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)
File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 385, in run_pipeline
exec_concurrent(context, executor)
File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 274, in exec_concurrent
executor(
File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_concurrent.py", line 82, in __call__
self._execute(
File "/usr/local/lib/python3.9/site-packages/ocrmypdf/builtin_plugins/concurrency.py", line 135, in _execute
result = future.result()
File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result
return self.__get_result()
File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
raise self._exception
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 192, in exec_page_sync
ocr_image, preprocess_out = make_intermediate_images(
File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 135, in make_intermediate_images
preprocess_out = preprocess(
File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 106, in preprocess
image = preprocess_deskew(image, page_context)
File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 481, in preprocess_deskew
deskew_angle_degrees = ocr_engine.get_deskew(input_file, page_context.options)
File "/usr/local/lib/python3.9/site-packages/ocrmypdf/builtin_plugins/tesseract_ocr.py", line 167, in get_deskew
return tesseract.get_deskew(
File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_exec/tesseract.py", line 237, in get_deskew
raise SubprocessOutputError() from e
ocrmypdf.exceptions.SubprocessOutputError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 266, in main_wrap
raise exc_info[1]
File "/usr/src/paperless/src/documents/consumer.py", line 245, in try_consume_file
document_parser.parse(self.path, mime_type, self.filename)
File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 301, in parse
raise ParseError(f"{e.__class__.__name__}: {str(e)}")
documents.parsers.ParseError: SubprocessOutputError: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/django_q/cluster.py", line 432, in worker
res = f(*task["args"], **task["kwargs"])
File "/usr/src/paperless/src/documents/tasks.py", line 70, in consume_file
document = Consumer().try_consume_file(
File "/usr/src/paperless/src/documents/consumer.py", line 262, in try_consume_file
self._fail(
File "/usr/src/paperless/src/documents/consumer.py", line 69, in _fail
raise ConsumerError(f"{self.filename}: {log_message or message}")
documents.consumer.ConsumerError: scan_20220318095033.pdf: Error while consuming document scan_20220318095033.pdf: SubprocessOutputError: 
Group:
-
Started:
18 Mar 2022, 10:45 a.m.
Stopped:
18 Mar 2022, 10:46 a.m.
Success:
False
Attempt count: 1
```

**Relevant information**
 - Host OS of the machine running paperless: [Ubuntu 20.04]
 - Browser N/A
 - Version 1.6
 - Installation method: [docker-compose]
 

```
version: "3.4"
services:
  broker:
    image: redis:6.0
    restart: unless-stopped

  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

  gotenberg:
      image: gotenberg/gotenberg:7
      restart: unless-stopped
      command:
        - "gotenberg"
        - "--chromium-disable-routes=true"




  tika:
    image: apache/tika
    restart: unless-stopped

volumes:
  data:
  media:
  pgdata:
```

**Comment by qcasey** [comment]
How much memory/RAM do you have available on this system? This looks like an oom-kill to me.

If you did a `sudo dmesg | grep kill` it might confirm that theory.

**Comment by qcasey** [comment]
If that's the case should there be the same `[WARNING]` message?

**Comment by 2600box** [comment]
> `sudo dmesg | grep kill`

```
root@docker ~# sudo dmesg | grep kill
dmesg: read kernel buffer failed: Operation not permitted
```

```
root@docker ~# free
              total        used        free      shared  buff/cache   available
Mem:        2097152      832592      220836      903172     1043724     1264560
Swap:             0           0           0
```

**Comment by 2600box** [comment]
> If that's the case should there be the same `[WARNING]` message?
> 
> Edit: it also looks like the [default timeout](https://ocrmypdf.readthedocs.io/en/latest/advanced.html#time-and-image-size-limits) is 180 seconds, this ran for a minute:
> 
> ```
> Started:
> 18 Mar 2022, 10:45 a.m.
> Stopped:
> 18 Mar 2022, 10:46 a.m.
> Success:
> False
> Attempt count: 1
> ```
Is this the correct way to user the OCR config?

```
docker_user@docker ~/paperless-ng$ cat docker-compose.env
PAPERLESS_OCR_USER_ARGS={"tesseract_timeout": 180}
PAPERLESS_TIME_ZONE=Europe/Paris
PAPERLESS_OCR_LANGUAGE=eng
PAPERLESS_SECRET_KEY=
```
