### ISSUE TITLE
Using rsync with the exporter and importer doesn't work as documented

### ISSUE THREAD

**Issue by ndw** [paperless-ngx/paperless-ngx#4384]
### Description

Attempting to import an updated export directory fails.

The documentation asserts that this is possible:

> The document exporter is also able to update an already existing export. Therefore, incremental backups with rsync are entirely possible.

but it doesn't seem to work:

```
docker compose exec -T webserver document_importer ../export -v 3
Checking the manifest
Installed 19764 object(s) from 1 fixture(s)
Copy files into paperless...
  0%|          | 0/5026 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/usr/src/paperless/src/documents/management/commands/document_importer.py", line 149, in handle
    self._import_files_from_manifest(options["no_progress_bar"])
  File "/usr/src/paperless/src/documents/management/commands/document_importer.py", line 245, in _import_files_from_manifest
    raise FileExistsError(document.source_path)
FileExistsError: /usr/src/paperless/media/documents/originals/0000001.pdf
```

### Steps to reproduce

1. Install paperless (using the standard Docker containers) on host1.
2. Add some documents to it
3. Export those documents
4. Install paperless on host2.
5. Import the documents from host1.
6. Add some more documents on host2.
7. Export the documents on host2.
8. Use `rsync` to update the `../export` directory on host1 with the exported files from host2.
9. Attempt to import the updated `../export` directory on host1.

I imagine that if I deleted all the documents on host1 and then re-imported, it would work. But it would be nice if that wasn't the case.

### Webserver logs

```bash
Irrelevant, I think.
```

### Paperless-ngx version

1.17.4 on both hosts

### Host OS

Debian/12 and MacOS

### Installation method

Docker - official image

**Comment by stumpylog** [comment]
The document importer is not the document exporter.  The exporter will update an existing export as documented.  The import always requires a fresh installation.  It is not intended to be a method for syncing to installations.

**Comment by ndw** [comment]
Fair enough. The docs could be clearer on that point, though.
