### ISSUE TITLE
[BUG] exception when trying to add new file from observed folder

### ISSUE THREAD

**Issue by Kosta-Github** [paperless-ngx/paperless-ngx#4398]
### Description

I am using the following workflow:

1. scanning a PDF via `ScanSnap`
2. `ScanSnap` uploads the file to a `OneDrive` folder in the Cloud
3. the `OneDriver` folder gets sync'ed from the Cloud to the local system
4. `paperless` on the local system is observing this local `OneDrive` folder
5. `paperless` processes the new file from the `OneDrive` folder

However, most of the time `paperless` is running into an `exception` when trying to process the file uploaded by `ScanSnap` (error log see below).

When copying PDFs manually into the `OneDrive` folder on the local machine, this workflow is functioning flawlessly.

Maybe an additional retry could be added for this case?

### Steps to reproduce

1. scanning a PDF via `ScanSnap`
2. `ScanSnap` uploads the file to a `OneDrive` folder in the Cloud
3. the `OneDriver` folder gets sync'ed from the Cloud to the local system
4. `paperless` on the local system is observing this local `OneDrive` folder
5. `paperless` processes the new file from the `OneDrive` folder
6. see error log below

### Webserver logs

```bash
[2023-10-19 08:05:04,123] [DEBUG] [paperless.tasks] Training data unchanged.

[2023-10-19 08:34:11,614] [DEBUG] [paperless.management.consumer] Waiting for file /usr/src/paperless/consume/2023-10-19-08-33-28.pdf to remain unmodified

[2023-10-19 08:34:16,632] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/2023-10-19-08-33-28.pdf to the task queue.

[2023-10-19 08:34:16,645] [ERROR] [paperless.management.consumer] Error while consuming document

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 130, in _consume

    ConsumableDocument(

  File "<string>", line 5, in __init__

  File "/usr/src/paperless/src/documents/data_models.py", line 62, in __post_init__

    self.mime_type = magic.from_file(self.original_file, mime=True)

  File "/usr/local/lib/python3.9/site-packages/magic/__init__.py", line 179, in from_file

    return m.from_file(filename)

  File "/usr/local/lib/python3.9/site-packages/magic/__init__.py", line 119, in from_file

    return self._handle509Bug(e)

  File "/usr/local/lib/python3.9/site-packages/magic/__init__.py", line 135, in _handle509Bug

    raise e

  File "/usr/local/lib/python3.9/site-packages/magic/__init__.py", line 117, in from_file

    return maybe_decode(magic_file(self.cookie, filename))

  File "/usr/local/lib/python3.9/site-packages/magic/__init__.py", line 297, in magic_file

    return _magic_file(cookie, coerce_filename(filename))

  File "/usr/local/lib/python3.9/site-packages/magic/__init__.py", line 217, in errorcheck_null

    raise MagicException(err)

magic.MagicException: b"cannot read `/usr/src/paperless/consume/2023-10-19-08-33-28.pdf' (Resource deadlock avoided)"
```

### Paperless-ngx version

1.17.4

### Host OS

MacOS - arm64

### Installation method

Docker - official image

### Browser

Chrome

### Configuration changes

none

**Comment by stumpylog** [comment]
Sounds like a better report for python-magic, not paperless.
