### ISSUE TITLE
[BUG] PermissionError with collate double-sided scan function

### ISSUE THREAD

**Issue by amo13** [paperless-ngx/paperless-ngx#4483]
### Description

My scanner sends the scanned documents to the paperless consume folder using ftp and automatic import by paperless works without issue.
Since my scanner only does simplex scans, I use the fantastic collate-double-sided feature. I created the `double-sided` folder inside the consume folder and tell my scanner to upload the documents there. When I scan the front-side, the PDF lands in the `double-sided` folder. Then paperless adds it to the task queue and throws the `PermissionError` exception (see logs below). After that, I scan the back-side, my scanners uploads it to `double-sided` and paperless consumes it. The result is fine and the pages are collated to one document. The `double-sided` folder is empty afterwards.
The owner and permissions on the scan files in `double-sided` are exactly the same as for simplex scans landing in `consume` which also get imported correctly but throw no error in the logs. 
Not sure if this is a real bug since nothing is actually broken, but seeing the exception in the logs made me think that at least I should report it. 

### Steps to reproduce

1. set PAPERLESS_CONSUMER_ENABLE_COLLATE_DOUBLE_SIDED=true and restart paperless
2. create the `double-sided` folder inside `consume`
3. drop a page into `double-sided`
4. wait for the task queue to add it and notice the exception in the logs
5. drop another page into `double-sided`
6. watch paperless consume and collate the document

### Webserver logs

```bash
Nov 01 15:31:10 server paperless-manage[609158]: [2023-11-01 14:31:10,719] [INFO] [paperless.management.consumer] Adding /var/lib/paperless/consume/double-sided/Rechnung_Unibuch_1863092.pdf to the task queue.
Nov 01 15:31:10 server celery[609160]: [2023-11-01 14:31:10,836] [INFO] [celery.worker.strategy] Task documents.tasks.consume_file[5e041c0d-5d1b-4070-8b3f-c13de2a4af10] received
Nov 01 15:31:11 server celery[609569]: [2023-11-01 14:31:11,233] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[5e041c0d-5d1b-4070-8b3f-c13de2a4af10] raised unexpected: PermissionError(1, 'Operation not permitted')
Nov 01 15:31:11 server celery[609569]: Traceback (most recent call last):
Nov 01 15:31:11 server celery[609569]:   File "/usr/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
Nov 01 15:31:11 server celery[609569]:     R = retval = fun(*args, **kwargs)
Nov 01 15:31:11 server celery[609569]:                  ^^^^^^^^^^^^^^^^^^^^
Nov 01 15:31:11 server celery[609569]:   File "/usr/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
Nov 01 15:31:11 server celery[609569]:     return self.run(*args, **kwargs)
Nov 01 15:31:11 server celery[609569]:            ^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 01 15:31:11 server celery[609569]:   File "/usr/share/paperless/src/documents/tasks.py", line 126, in consume_file
Nov 01 15:31:11 server celery[609569]:     msg = collate(input_doc)
Nov 01 15:31:11 server celery[609569]:           ^^^^^^^^^^^^^^^^^^
Nov 01 15:31:11 server celery[609569]:   File "/usr/share/paperless/src/documents/double_sided.py", line 123, in collate
Nov 01 15:31:11 server celery[609569]:     os.utime(str(staging), (dt.datetime.now().timestamp(),) * 2)
Nov 01 15:31:11 server celery[609569]: PermissionError: [Errno 1] Operation not permitted
Nov 01 15:31:40 server paperless-manage[609158]: [2023-11-01 14:31:40,721] [INFO] [paperless.management.consumer] Adding /var/lib/paperless/consume/double-sided/Rechnung_Unibuch_1865052.pdf to the task queue.
Nov 01 15:31:40 server celery[609160]: [2023-11-01 14:31:40,838] [INFO] [celery.worker.strategy] Task documents.tasks.consume_file[2ef52eba-ec8f-466c-922b-239d25bee236] received
Nov 01 15:31:41 server celery[609587]: [2023-11-01 14:31:41,114] [INFO] [paperless.double_sided] Collated documents into new file /var/lib/paperless/consume/Rechnung_Unibuch_1865052-collated.pdf
Nov 01 15:31:41 server celery[609587]: [2023-11-01 14:31:41,239] [INFO] [celery.app.trace] Task documents.tasks.consume_file[2ef52eba-ec8f-466c-922b-239d25bee236] succeeded in 0.39213239995297045s: 'Success. Even numbered pages of double sided scan collated with odd pages'
Nov 01 15:31:50 server paperless-manage[609158]: [2023-11-01 14:31:50,722] [INFO] [paperless.management.consumer] Adding /var/lib/paperless/consume/Rechnung_Unibuch_1865052-collated.pdf to the task queue.
Nov 01 15:31:50 server celery[609160]: [2023-11-01 14:31:50,836] [INFO] [celery.worker.strategy] Task documents.tasks.consume_file[8cc6a23d-4435-40cc-8436-5d450aa2cf75] received
Nov 01 15:31:52 server celery[609592]: [2023-11-01 14:31:52,241] [WARNING] [paperless.barcodes] No pages to split on!
Nov 01 15:31:52 server celery[609592]: [2023-11-01 14:31:52,260] [INFO] [paperless.consumer] Consuming Rechnung_Unibuch_1865052-collated.pdf
Nov 01 15:31:52 server celery[609592]: [2023-11-01 14:31:52,683] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
Nov 01 15:31:52 server celery[609592]: [2023-11-01 14:31:52,684] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
Nov 01 15:31:52 server celery[609592]: [2023-11-01 14:31:52,688] [INFO] [ocrmypdf._sync] Postprocessing...
Nov 01 15:31:52 server celery[609592]: [2023-11-01 14:31:52,997] [INFO] [ocrmypdf._pipeline] Image optimization ratio: 1.00 savings: 0.0%
Nov 01 15:31:52 server celery[609592]: [2023-11-01 14:31:52,997] [INFO] [ocrmypdf._pipeline] Total file size ratio: 1.48 savings: 32.6%
Nov 01 15:31:53 server celery[609592]: [2023-11-01 14:31:53,001] [INFO] [ocrmypdf._sync] Output file is a PDF/A-2B (as expected)
Nov 01 15:32:00 server celery[609592]: [2023-11-01 14:32:00,865] [INFO] [paperless.handlers] Assigning document type Bescheid to 2018-08-06 Rechnung_Unibuch_1865052-collated
Nov 01 15:32:01 server celery[609592]: [2023-11-01 14:32:01,047] [INFO] [paperless.consumer] Document 2018-08-06 Rechnung_Unibuch_1865052-collated consumption finished
Nov 01 15:32:01 server celery[609592]: [2023-11-01 14:32:01,157] [INFO] [celery.app.trace] Task documents.tasks.consume_file[8cc6a23d-4435-40cc-8436-5d450aa2cf75] succeeded in 10.311631891992874s: 'Success. New document id 56 created'
```

### Browser logs

```bash
not applicable
```

### Paperless-ngx version

1.17.4

### Host OS

Archlinux

### Installation method

Bare metal

### Browser

Firefox

### Configuration changes

PAPERLESS_CONSUMER_ENABLE_COLLATE_DOUBLE_SIDED=true

### Other

I use PAPERLESS_CONSUMER_POLLING=5 because of the old bug where one CPU core would keep a constant 100% load if using inotify. (Polling was suggested as workaround - has the root cause been found/fixed?)

**Comment by stumpylog** [comment]
What are the permissions on the relevant folders and files?

**Comment by stumpylog** [comment]
It also doesn't appear to have stopped consuming. The task succeeded

**Comment by stumpylog** [comment]
See also #1597

**Comment by amo13** [comment]
Thank you for your reply.
The permissions are:
```
-rw-r--r-- 1 ftp  ftp   86K Nov  1 15:29 Rechnung_Unibuch_1863092.pdf
-rw-r--r-- 1 ftp  ftp   86K Nov  1 15:29 Rechnung_Unibuch_1865052.pdf
```
and `groups ftp` returns `paperless ftp`. Also:
```
$ sudo ls -lah /var/lib/paperless/consume
total 0
drwxrwx--- 1 paperless paperless 24 Nov  1 20:39 .
drwxrwx--- 1 paperless paperless 72 Jun 19  2021 ..
drwxrwx--- 1 paperless paperless  0 Nov  1 20:31 double-sided
```
and additionally I have set `PAPERLESS_SCRATCH_DIR=/var/lib/paperless/uploads`, but again, it works fine and the permissions should be ok:
```
$ sudo ls -lah /var/lib/paperless/
total 24K
drwxrwx--- 1 paperless paperless  72 Jun 19  2021 .
drwxr-xr-x 1 root      root      308 Oct 25 00:01 ..
drwxrwx--- 1 paperless paperless  24 Nov  1 20:39 consume
drwxr-x--- 1 paperless paperless   0 Jun 19  2021 data
drwxr-xr-x 1 paperless paperless 172 Nov  2 07:50 data-media
drwxr-x--- 1 paperless paperless   0 Jun 19  2021 media
drwxr-x--- 1 paperless paperless   0 Nov  1 20:39 tmp
drwxr-x--- 1 paperless paperless 21K Nov  1 20:39 uploads
```

The odd thing is that consuming does work and that other than the thrown exception, there is no difference to consuming a simplex scan landing in `consume`. Unfortunately, I don't know what the PermissionError is exactly. The logs don't say what operation was not permitted...

**Comment by stumpylog** [comment]
Your filesystem or os isn't supporting os.utime.  That's a basic Python function which we use and can't do anything about failing.

**Comment by amo13** [comment]
Thanks for your answer.
My OS is Archlinux and the filesystem is BTRFS. They both should support os.utime. And even if not, that does not explain why the exception is thrown on for the first file in `double-sided` and not for the second or for normal import in `consume`.

Is there anything that comes to mind for testing or narrowing down what is going on here?

**Comment by stumpylog** [comment]
No
