### ISSUE TITLE
[BUG] celery-beat unpickle error

### ISSUE THREAD

**Issue by StackNeverFlow** [paperless-ngx/paperless-ngx#4512]
### Description

Paperless spits out `celery-beat` error. Happens everytime paperless-ngx is running.

### Steps to reproduce

No steps to reproduce, error started happining. CPU usage goes up to 45%

### Webserver logs

```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/shelve.py", line 111, in __getitem__
    value = self.cache[key]
KeyError: 'entries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/apps/beat.py", line 113, in start_scheduler
    service.start()
  File "/usr/local/lib/python3.9/site-packages/celery/beat.py", line 631, in start
    humanize_seconds(self.scheduler.max_interval))
  File "/usr/local/lib/python3.9/site-packages/kombu/utils/objects.py", line 32, in __get__
    return super().__get__(instance, owner)
  File "/usr/local/lib/python3.9/functools.py", line 993, in __get__
    val = self.func(instance)
  File "/usr/local/lib/python3.9/site-packages/celery/beat.py", line 674, in scheduler
    return self.get_scheduler()
  File "/usr/local/lib/python3.9/site-packages/celery/beat.py", line 665, in get_scheduler
    return symbol_by_name(self.scheduler_cls, aliases=aliases)(
  File "/usr/local/lib/python3.9/site-packages/celery/beat.py", line 510, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/beat.py", line 264, in __init__
    self.setup_schedule()
  File "/usr/local/lib/python3.9/site-packages/celery/beat.py", line 538, in setup_schedule
    self._create_schedule()
  File "/usr/local/lib/python3.9/site-packages/celery/beat.py", line 567, in _create_schedule
    self._store['entries']
  File "/usr/local/lib/python3.9/shelve.py", line 114, in __getitem__
    value = Unpickler(f).load()
_pickle.UnpicklingError: pickle data was truncated
[2023-10-22 03:12:54,455] [WARNING] [celery.redirected] Traceback (most recent call last):
[2023-10-22 03:12:54,455] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/shelve.py", line 111, in __getitem__
[2023-10-22 03:12:54,456] [WARNING] [celery.redirected]     
[2023-10-22 03:12:54,457] [WARNING] [celery.redirected] value = self.cache[key]
[2023-10-22 03:12:54,457] [WARNING] [celery.redirected] KeyError
[2023-10-22 03:12:54,458] [WARNING] [celery.redirected] : 
[2023-10-22 03:12:54,458] [WARNING] [celery.redirected] 'entries'
[2023-10-22 03:12:54,459] [WARNING] [celery.redirected] 
During handling of the above exception, another exception occurred:
[2023-10-22 03:12:54,460] [WARNING] [celery.redirected] Traceback (most recent call last):
[2023-10-22 03:12:54,460] [WARNING] [celery.redirected]   File "/usr/local/bin/celery", line 8, in <module>
[2023-10-22 03:12:54,461] [WARNING] [celery.redirected]     
[2023-10-22 03:12:54,462] [WARNING] [celery.redirected] sys.exit(main())
[2023-10-22 03:12:54,463] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/site-packages/celery/__main__.py", line 15, in main
[2023-10-22 03:12:54,464] [WARNING] [celery.redirected]     
[2023-10-22 03:12:54,464] [WARNING] [celery.redirected] sys.exit(_main())
[2023-10-22 03:12:54,465] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/site-packages/celery/bin/celery.py", line 235, in main
[2023-10-22 03:12:54,466] [WARNING] [celery.redirected]     
[2023-10-22 03:12:54,467] [WARNING] [celery.redirected] return celery(auto_envvar_prefix="CELERY")
[2023-10-22 03:12:54,467] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
[2023-10-22 03:12:54,470] [WARNING] [celery.redirected]     
[2023-10-22 03:12:54,471] [WARNING] [celery.redirected] return self.main(*args, **kwargs)
[2023-10-22 03:12:54,471] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1078, in main
[2023-10-22 03:12:54,473] [WARNING] [celery.redirected]     
[2023-10-22 03:12:54,473] [WARNING] [celery.redirected] rv = self.invoke(ctx)
[2023-10-22 03:12:54,474] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
[2023-10-22 03:12:54,475] [WARNING] [celery.redirected]     
[2023-10-22 03:12:54,476] [WARNING] [celery.redirected] return _process_result(sub_ctx.command.invoke(sub_ctx))
[2023-10-22 03:12:54,477] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
[2023-10-22 03:12:54,478] [WARNING] [celery.redirected]     
[2023-10-22 03:12:54,478] [WARNING] [celery.redirected] return ctx.invoke(self.callback, **ctx.params)
[2023-10-22 03:12:54,479] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 783, in invoke
[2023-10-22 03:12:54,480] [WARNING] [celery.redirected]     
[2023-10-22 03:12:54,481] [WARNING] [celery.redirected] return __callback(*args, **kwargs)
[2023-10-22 03:12:54,481] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
[2023-10-22 03:12:54,482] [WARNING] [celery.redirected]     
[2023-10-22 03:12:54,482] [WARNING] [celery.redirected] return f(get_current_context(), *args, **kwargs)
[2023-10-22 03:12:54,483] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/site-packages/celery/bin/base.py", line 134, in caller
[2023-10-22 03:12:54,484] [WARNING] [celery.redirected]     
[2023-10-22 03:12:54,484] [WARNING] [celery.redirected] return f(ctx, *args, **kwargs)
[2023-10-22 03:12:54,485] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/site-packages/celery/bin/beat.py", line 72, in beat
[2023-10-22 03:12:54,485] [WARNING] [celery.redirected]     
[2023-10-22 03:12:54,486] [WARNING] [celery.redirected] return beat().run()
[2023-10-22 03:12:54,486] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/site-packages/celery/apps/beat.py", line 84, in run
[2023-10-22 03:12:54,487] [WARNING] [celery.redirected]     
[2023-10-22 03:12:54,488] [WARNING] [celery.redirected] self.start_scheduler()
[2023-10-22 03:12:54,488] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/site-packages/celery/apps/beat.py", line 113, in start_scheduler
[2023-10-22 03:12:54,489] [WARNING] [celery.redirected]     
[2023-10-22 03:12:54,489] [WARNING] [celery.redirected] service.start()
[2023-10-22 03:12:54,490] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/site-packages/celery/beat.py", line 631, in start
[2023-10-22 03:12:54,491] [WARNING] [celery.redirected]     
[2023-10-22 03:12:54,491] [WARNING] [celery.redirected] humanize_seconds(self.scheduler.max_interval))
[2023-10-22 03:12:54,492] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/site-packages/kombu/utils/objects.py", line 32, in __get__
[2023-10-22 03:12:54,493] [WARNING] [celery.redirected]     
[2023-10-22 03:12:54,493] [WARNING] [celery.redirected] return super().__get__(instance, owner)
[2023-10-22 03:12:54,494] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/functools.py", line 993, in __get__
[2023-10-22 03:12:54,495] [WARNING] [celery.redirected]     
[2023-10-22 03:12:54,495] [WARNING] [celery.redirected] val = self.func(instance)
[2023-10-22 03:12:54,496] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/site-packages/celery/beat.py", line 674, in scheduler
[2023-10-22 03:12:54,497] [WARNING] [celery.redirected]     
[2023-10-22 03:12:54,497] [WARNING] [celery.redirected] return self.get_scheduler()
[2023-10-22 03:12:54,498] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/site-packages/celery/beat.py", line 665, in get_scheduler
[2023-10-22 03:12:54,499] [WARNING] [celery.redirected]     
[2023-10-22 03:12:54,499] [WARNING] [celery.redirected] return symbol_by_name(self.scheduler_cls, aliases=aliases)(
[2023-10-22 03:12:54,500] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/site-packages/celery/beat.py", line 510, in __init__
[2023-10-22 03:12:54,500] [WARNING] [celery.redirected]     
[2023-10-22 03:12:54,501] [WARNING] [celery.redirected] super().__init__(*args, **kwargs)
[2023-10-22 03:12:54,502] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/site-packages/celery/beat.py", line 264, in __init__
[2023-10-22 03:12:54,502] [WARNING] [celery.redirected]     
[2023-10-22 03:12:54,503] [WARNING] [celery.redirected] self.setup_schedule()
[2023-10-22 03:12:54,503] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/site-packages/celery/beat.py", line 538, in setup_schedule
[2023-10-22 03:12:54,504] [WARNING] [celery.redirected]     
[2023-10-22 03:12:54,505] [WARNING] [celery.redirected] self._create_schedule()
[2023-10-22 03:12:54,505] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/site-packages/celery/beat.py", line 567, in _create_schedule
[2023-10-22 03:12:54,506] [WARNING] [celery.redirected]     
[2023-10-22 03:12:54,507] [WARNING] [celery.redirected] self._store['entries']
[2023-10-22 03:12:54,507] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/shelve.py", line 114, in __getitem__
[2023-10-22 03:12:54,508] [WARNING] [celery.redirected]     
[2023-10-22 03:12:54,508] [WARNING] [celery.redirected] value = Unpickler(f).load()
[2023-10-22 03:12:54,509] [WARNING] [celery.redirected] _pickle
[2023-10-22 03:12:54,509] [WARNING] [celery.redirected] .
[2023-10-22 03:12:54,510] [WARNING] [celery.redirected] UnpicklingError
[2023-10-22 03:12:54,510] [WARNING] [celery.redirected] : 
[2023-10-22 03:12:54,511] [WARNING] [celery.redirected] pickle data was truncated
celery beat v5.3.1 (emerald-rush) is starting.
__    -    ... __   -        _
LocalTime -> 2023-10-22 03:12:54
Configuration ->
    . broker -> redis://broker:6379//
    . loader -> celery.loaders.app.AppLoader
    . scheduler -> celery.beat.PersistentScheduler
    . db -> /usr/src/paperless/data/celerybeat-schedule.db
    . logfile -> [stderr]@%INFO
    . maxinterval -> 5.00 minutes (300s)
2023-10-22 01:12:55,035 WARN exited: celery-beat (exit status 1; not expected)
2023-10-22 01:12:56,039 INFO spawned: 'celery-beat' with pid 29281
2023-10-22 01:12:57,041 INFO success: celery-beat entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[2023-10-22 03:12:58,528] [INFO] [celery.beat] beat: Starting...
[2023-10-22 03:12:58,636] [CRITICAL] [celery.beat] beat raised exception <class '_pickle.UnpicklingError'>: UnpicklingError('pickle data was truncated')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/shelve.py", line 111, in __getitem__
    value = self.cache[key]
KeyError: 'entries'
```

### Paperless-ngx version

1.17.4

### Host OS

Ubuntu 22.04.3 LTS

### Installation method

Docker - official image

**Comment by stumpylog** [comment]
Remove `celerybeat-schedule.db` from your DATA_DIR.
