### ISSUE TITLE
Not able to import files

### ISSUE THREAD

**Issue by klatscher4** [paperless-ngx/paperless-ngx#455]
Hi dudes,
at first im totally new to paperless and made yesterday my frist installation.
I used the Docker Installation Script from the Documentation and set alll Options to the default one.
After the Script was finished, the Paperless-ngx Login-page apears and im able to login.
When i try to upload Files through the Start-Page, the files are processed but i got an Error after this:
![grafik](https://user-images.githubusercontent.com/59533868/159174119-cf4d6312-af52-4b96-8aa3-0dd0d14deef8.png)

The Log:
```
[2022-03-20 17:06:36,049] [INFO] [paperless.consumer] Consuming 2021_06_Wartung_Motorrad.pdf

[2022-03-20 17:06:36,052] [DEBUG] [paperless.consumer] Detected mime type: application/pdf

[2022-03-20 17:06:36,064] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser

[2022-03-20 17:06:36,070] [DEBUG] [paperless.consumer] Parsing 2021_06_Wartung_Motorrad.pdf...

[2022-03-20 17:06:36,257] [DEBUG] [paperless.parsing.tesseract] Extracted text from PDF file /tmp/paperless/paperless-upload-2_z6q1uv

[2022-03-20 17:06:36,442] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': '/tmp/paperless/paperless-upload-2_z6q1uv', 'output_file': '/tmp/paperless/paperless-um48cibf/archive.pdf', 'use_threads': True, 'jobs': 2, 'language': 'deu+eng', 'output_type': 'pdfa', 'progress_bar': False, 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': '/tmp/paperless/paperless-um48cibf/sidecar.txt'}

[2022-03-20 17:07:46,410] [DEBUG] [paperless.parsing.tesseract] Using text from sidecar file

[2022-03-20 17:07:46,411] [DEBUG] [paperless.consumer] Generating thumbnail for 2021_06_Wartung_Motorrad.pdf...

[2022-03-20 17:07:46,419] [DEBUG] [paperless.parsing] Execute: convert -density 300 -scale 500x5000> -alpha remove -strip -auto-orient /tmp/paperless/paperless-um48cibf/archive.pdf[0] /tmp/paperless/paperless-um48cibf/convert.png

[2022-03-20 17:07:49,587] [DEBUG] [paperless.parsing.tesseract] Execute: optipng -silent -o5 /tmp/paperless/paperless-um48cibf/convert.png -out /tmp/paperless/paperless-um48cibf/thumb_optipng.png

[2022-03-20 17:08:04,883] [DEBUG] [paperless.classifier] Document classification model does not exist (yet), not performing automatic matching.

[2022-03-20 17:08:04,890] [DEBUG] [paperless.consumer] Saving record to database

[2022-03-20 17:08:04,953] [ERROR] [paperless.consumer] The following error occured while consuming 2021_06_Wartung_Motorrad.pdf: ''

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/consumer.py", line 288, in try_consume_file

    document_consumption_finished.send(

  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 180, in send

    return [

  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>

    (receiver, receiver(signal=self, sender=sender, **named))

  File "/usr/src/paperless/src/documents/signals/handlers.py", line 418, in set_log_entry

    object_repr=document.__str__(),

  File "/usr/src/paperless/src/documents/models.py", line 206, in __str__

    created = timezone.localdate(self.created).isoformat()

  File "/usr/local/lib/python3.9/site-packages/django/utils/timezone.py", line 193, in localdate

    return localtime(value, timezone).date()

  File "/usr/local/lib/python3.9/site-packages/django/utils/timezone.py", line 176, in localtime

    timezone = get_current_timezone()

  File "/usr/local/lib/python3.9/site-packages/django/utils/timezone.py", line 66, in get_current_timezone

    return getattr(_active, "value", get_default_timezone())

  File "/usr/local/lib/python3.9/site-packages/django/utils/timezone.py", line 52, in get_default_timezone

    return pytz.timezone(settings.TIME_ZONE)

  File "/usr/local/lib/python3.9/site-packages/pytz/__init__.py", line 188, in timezone

    raise UnknownTimeZoneError(zone)

pytz.exceptions.UnknownTimeZoneError: ''

[2022-03-20 17:08:04,955] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-um48cibf
```
the same error occurs when I use the cunsume folder and pleace Files there.
Can someone help me please?
Do i have made a Mistake or do i need to change some permissions or what ever?

**Comment by PhilippMT** [comment]
I had the same problem. Docker has issues to get the timezone from the host, thats why the timezone is empty `pytz.exceptions.UnknownTimeZoneError: ''` You have to set the the value in the install script or in the `docker-compose.env` file with `PAPERLESS_TIME_ZONE=Europe/Berlin`

**Comment by shamoon** [comment]
The install script does correctly require this setting, see https://github.com/paperless-ngx/paperless-ngx/blob/0979f3c5c3e4275820c7c7fd394b5b0d159304a8/install-paperless-ngx.sh#L100 , did you say you used the script?

**Comment by klatscher4** [comment]
> I had the same problem. Docker has issues to get the timezone from the host, thats why the timezone is empty `pytz.exceptions.UnknownTimeZoneError: ''` You have to set the the value in the install script or in the `docker-compose.env` file with `PAPERLESS_TIME_ZONE=Europe/Berlin`

Thanks a lot. It is now working!
Had added the Timezone a few times but the Script told me always that i use a wrong one. So i decided to leave it empty

**Comment by klatscher4** [comment]
Thanks to @PhilippMT its now working.
Maybe i not smart enough but i was not able to insert the Timezone in the right format.
If someone is facing the same Issue, just copy the Timezone from his Answer :-)
