### ISSUE TITLE
[BUG] `python3 manage.py createsuperuser` fails to load `_FILE` env vars

### ISSUE THREAD

**Issue by coaxial** [paperless-ngx/paperless-ngx#4570]
### Description

When setting the database password using a Docker secret with `PAPERLESS_DBPASS_FILE=/run/secrets/paperless_db_password`, the `python3 manage.py createsuperuser` doesn't pick it up and uses the default `paperless` password insteead.

### Steps to reproduce

0. Create Docker secret `db_pass` with value `mypassword`
1. Set the `PAPERLESS_DBPASS_FILE` env var to `/run/secrets/db_pass`
2. Inside the webserver container, run `python3 manage.py createsuperuser`
3. Get an error that it can't connect to the database

### Webserver logs

```bash
root@25c65f05cef6:/usr/src/paperless/src# env | grep PAPERLESS_DBPASS_FILE
PAPERLESS_DBPASS_FILE=/run/secrets/paperless_db_password

root@25c65f05cef6:/usr/src/paperless/src# python3 manage.py createsuperuser
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 263, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 215, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "db" (10.0.7.5), port 5432 failed: FATAL:  password authentication failed for user "paperless"


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 88, in execute
    return super().execute(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 447, in execute
    self.check_migrations()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 564, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/loader.py", line 58, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/loader.py", line 235, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 81, in applied_migrations
    if self.has_table():
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 57, in has_table
    with self.connection.cursor() as cursor:
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 323, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 299, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 263, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 215, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: connection to server at "db" (10.0.7.5), port 5432 failed: FATAL:  password authentication failed for user "paperless"
```
```


### Browser logs

_No response_

### Paperless-ngx version

1.17.4

### Host OS

Whatever the official docker container uses

### Installation method

Docker - official image

### Browser

_No response_

### Configuration changes

See https://github.com/coaxial/docker-services/blob/a39e6277572172804d6e0ae9d5ad1d04162c21c4/paperless-ngx/docker-compose.yml

### Other

_No response_

**Comment by stumpylog** [comment]
I mean, that's just a [Django command](https://docs.djangoproject.com/en/4.2/ref/django-admin/#createsuperuser), so why would it?

**Comment by stumpylog** [comment]
`manage_superuser` would, that's the command we provide in the container.

**Comment by coaxial** [comment]
This worked: `PAPERLESS_ADMIN_PASSWORD=admin manage_superuser`.

**Comment by stumpylog** [comment]
That's not necessary, but also another way to set it.  The script will read environment from files before execution
