### ISSUE TITLE
mail import error in 2.00 beta rc1

### ISSUE THREAD

**Issue by muecke6** [paperless-ngx/paperless-ngx#4593]
### Description

mails with pdf attachments are not processed. have not changed anything since the last version
![error](https://github.com/paperless-ngx/paperless-ngx/assets/123741690/383e605d-f34e-4639-bd3a-5fbb155cb488)

### Steps to reproduce

send mail with attachment pdf
![email](https://github.com/paperless-ngx/paperless-ngx/assets/123741690/04fe1f19-c85d-40e7-a6c1-42ed72f20048)

### Webserver logs

```bash
[2023-11-15 07:00:01,496] [DEBUG] [paperless_mail] Account paperless@elgabo.ch: Processing 1 rule(s)

[2023-11-15 07:00:01,501] [DEBUG] [paperless_mail] Rule paperless@elgabo.ch.Paperless: Selecting folder INBOX

[2023-11-15 07:00:01,536] [DEBUG] [paperless_mail] Rule paperless@elgabo.ch.Paperless: Searching folder with criteria (SINCE 16-Oct-2023)

[2023-11-15 07:00:02,006] [DEBUG] [paperless_mail] Skipping mail <imap_tools.message.MailMessage object at 0x7f5cd177fe90>, already processed.

[2023-11-15 07:00:03,710] [DEBUG] [paperless_mail] Skipping mail <imap_tools.message.MailMessage object at 0x7f5cd1773f10>, already processed.

[2023-11-15 07:00:04,648] [DEBUG] [paperless_mail] Skipping mail <imap_tools.message.MailMessage object at 0x7f5cd149a510>, already processed.

[2023-11-15 07:00:05,025] [DEBUG] [paperless_mail] Rule paperless@elgabo.ch.Paperless: Processing mail Fwd: Abholschein 67074 - Gebäudebeschriftung from gabriel.wehle@elgabo.ch with 1 attachment(s)

[2023-11-15 07:00:05,539] [INFO] [paperless_mail] Rule paperless@elgabo.ch.Paperless: Consuming attachment Abholschein 67074 - Gebäudebeschriftung.pdf from mail Fwd: Abholschein 67074 - Gebäudebeschriftung from gabriel.wehle@elgabo.ch

[2023-11-15 07:00:06,596] [DEBUG] [paperless_mail] Rule paperless@elgabo.ch.Paperless: Processed 1 matching mail(s)

[2023-11-15 07:10:00,848] [DEBUG] [paperless_mail] Processing mail account paperless@elgabo.ch
```

### Paperless-ngx version

2.00 beta rc1

### Host OS

synology

### Installation method

Docker - official image

### Browser

Firefox

**Comment by shamoon** [comment]
I cant reproduce this. Does the celery result give more info? Under the Django admin e.g. /admin/django_celery_results/taskresult/

**Comment by leutnantlurch** [comment]
Unfortunately I have rhe dame issue. 
For me the django log says:

![image](https://github.com/paperless-ngx/paperless-ngx/assets/129696204/74d18814-11f2-4493-989d-825faef028c0)

**Comment by shamoon** [comment]
Thanks for the help, just trying to track down where this is. one more and if not then I’ll let the backend team take a look, how about the processedmail eg /admin/paperless_mail/processedmail/ ?

**Comment by leutnantlurch** [comment]
Sure, glad I can help 😃 

The processedmail says:

`
Fehler:
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
R = retval = fun(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
return self.run(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/paperless/src/documents/tasks.py", line 164, in consume_file
overrides.update(template_overrides)
File "/usr/src/paperless/src/documents/data_models.py", line 56, in update
self.tag_ids.extend(other.tag_ids)
TypeError: 'NoneType' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/django_celery_results/backends/database.py", line 292, in trigger_callback
ret = j(timeout=app.conf.result_chord_join_timeout, propagate=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/celery/result.py", line 775, in join
value = result.get(
^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/celery/result.py", line 247, in get
self.maybe_throw(callback=callback)
File "/usr/local/lib/python3.11/site-packages/celery/result.py", line 365, in maybe_throw
self.throw(value, self._to_remote_traceback(tb))
File "/usr/local/lib/python3.11/site-packages/celery/result.py", line 358, in throw
self.on_ready.throw(*args, **kwargs)
File "/usr/local/lib/python3.11/site-packages/vine/promises.py", line 235, in throw
reraise(type(exc), exc, tb)
File "/usr/local/lib/python3.11/site-packages/vine/utils.py", line 27, in reraise
raise value
TypeError: 'NoneType' object is not iterable `
