### ISSUE TITLE
[BUG] E-Mail archiving fails in v2.0.0 beta

### ISSUE THREAD

**Issue by LarsK1** [paperless-ngx/paperless-ngx#4603]
### Description

When I send an mail to a paperless-ngx connected mailbox, it should automatically fetch the email and archive the content.

### Steps to reproduce

1. Send an mail to a connected inbox
2. wait and see 😄 

### Webserver logs

```bash
paperless-webserver-1  | [2023-11-16 08:41:00,206] [INFO] [paperless_mail] Rule Blumagine DMS.Sonstige Dokumente: Consuming attachment 9073621992503617-1.pdf from mail Google from info@blumagine.depaperless-webserver-1  | [2023-11-16 08:41:00,208] [WARNING] [py.warnings] /usr/local/lib/python3.11/site-packages/celery/canvas.py:2283: CPendingDeprecationWarning: task_allow_error_cb_on_chord_header=False is pending deprecation in a future release of Celery.
paperless-webserver-1  | Please test the new behavior by setting task_allow_error_cb_on_chord_header to True and report any concerns you might have in our issue tracker before we make a final decision regarding how errbacks should behave when used with chords.
paperless-webserver-1  |   warnings.warn(
paperless-webserver-1  | 
paperless-webserver-1  | [2023-11-16 08:41:00,221] [INFO] [celery.worker.strategy] Task documents.tasks.consume_file[d952765a-83e2-4f8b-aa1a-fefdeb08959f] received
paperless-webserver-1  | [2023-11-16 08:41:00,224] [INFO] [celery.app.trace] Task paperless_mail.tasks.process_mail_accounts[82da68ab-9f91-468e-895d-2c6719b7dd7f] succeeded in 0.2201696429401636s: 'Added 1 document(s).'
paperless-webserver-1  | [2023-11-16 08:41:00,246] [ERROR] [django_celery_results.backends.database] Chord '23fe01c6-76b8-4ebc-9bf8-ba969eb48566' raised: TypeError("'NoneType' object is not iterable")
paperless-webserver-1  | Traceback (most recent call last):
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
paperless-webserver-1  |     R = retval = fun(*args, **kwargs)
paperless-webserver-1  |                  ^^^^^^^^^^^^^^^^^^^^
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
paperless-webserver-1  |     return self.run(*args, **kwargs)
paperless-webserver-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-webserver-1  |   File "/usr/src/paperless/src/documents/tasks.py", line 164, in consume_file
paperless-webserver-1  |     overrides.update(template_overrides)
paperless-webserver-1  |   File "/usr/src/paperless/src/documents/data_models.py", line 56, in update
paperless-webserver-1  |     self.tag_ids.extend(other.tag_ids)
paperless-webserver-1  | TypeError: 'NoneType' object is not iterable
paperless-webserver-1  | 
paperless-webserver-1  | During handling of the above exception, another exception occurred:
paperless-webserver-1  | 
paperless-webserver-1  | Traceback (most recent call last):
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/django_celery_results/backends/database.py", line 292, in trigger_callback
paperless-webserver-1  |     ret = j(timeout=app.conf.result_chord_join_timeout, propagate=True)
paperless-webserver-1  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/celery/result.py", line 775, in join
paperless-webserver-1  |     value = result.get(
paperless-webserver-1  |             ^^^^^^^^^^^
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/celery/result.py", line 247, in get
paperless-webserver-1  |     self.maybe_throw(callback=callback)
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/celery/result.py", line 365, in maybe_throw
paperless-webserver-1  |     self.throw(value, self._to_remote_traceback(tb))
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/celery/result.py", line 358, in throw
paperless-webserver-1  |     self.on_ready.throw(*args, **kwargs)
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/vine/promises.py", line 235, in throw
paperless-webserver-1  |     reraise(type(exc), exc, tb)
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/vine/utils.py", line 27, in reraise
paperless-webserver-1  |     raise value
paperless-webserver-1  | TypeError: 'NoneType' object is not iterable
paperless-webserver-1  | [2023-11-16 08:41:00,261] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[d952765a-83e2-4f8b-aa1a-fefdeb08959f] raised unexpected: TypeError("'NoneType' object is not iterable")
paperless-webserver-1  | Traceback (most recent call last):
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
paperless-webserver-1  |     R = retval = fun(*args, **kwargs)
paperless-webserver-1  |                  ^^^^^^^^^^^^^^^^^^^^
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
paperless-webserver-1  |     return self.run(*args, **kwargs)
paperless-webserver-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-webserver-1  |   File "/usr/src/paperless/src/documents/tasks.py", line 164, in consume_file
paperless-webserver-1  |     overrides.update(template_overrides)
paperless-webserver-1  |   File "/usr/src/paperless/src/documents/data_models.py", line 56, in update
paperless-webserver-1  |     self.tag_ids.extend(other.tag_ids)
paperless-webserver-1  | TypeError: 'NoneType' object is not iterable
paperless-webserver-1  | [2023-11-16 08:42:00,000] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
paperless-webserver-1  | [2023-11-16 08:42:00,002] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[520456f9-4595-4b8c-9281-833a3d043a7f] received
paperless-webserver-1  | [2023-11-16 08:42:00,156] [INFO] [celery.app.trace] Task paperless_mail.tasks.process_mail_accounts[520456f9-4595-4b8c-9281-833a3d043a7f] succeeded in 0.15214027976617217s:
```

### Paperless-ngx version

2.0.0-beta.rc1

### Host OS

Debian

### Installation method

Bare metal

**Comment by shamoon** [comment]
This was already fixed. The docker container gets automatically rebuilt but bare metal the archive isn’t updated

https://github.com/paperless-ngx/paperless-ngx/issues/4593
