### ISSUE TITLE
[BUG] no logs in case of ghostscript error

### ISSUE THREAD

**Issue by hydrargyrum** [paperless-ngx/paperless-ngx#4625]
### Description

Yes, yet another ticket about the `Ghostscript PDF/A rendering failed. See logs for more information.` problem. But this one is about logs being useless.

The logs say "See logs for more information" but the only logs are paperless' logs, I expect to see ghostscript logs to find out, for example:
- what's wrong with my documents
- what bug to report to ghostscript (because ghostscript seems to reject **a lot** of files, it's **very** picky, because my documents come from very diverse sources, and regular PDF viewers like `evince` open these documents without an issue, so I guess the problem really is ghostscript)

### Steps to reproduce

1. upload a file not recognized by ghostscript
2. go to `<paperless url>/logs`

### Webserver logs

```bash
[2023-11-18 12:44:34,455] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-ngxr0vkmr3e/lol.pdf'), 'output_file': PosixPath('/tmp/paperless/paperless-_8e7c4ju/archive.pdf'), 'use_threads': True, 'jobs': 12, 'language': 'eng', 'output_type': 'pdfa', 'progress_bar': False, 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-_8e7c4ju/sidecar.txt')}

[2023-11-18 12:44:36,321] [WARNING] [paperless.parsing.tesseract] Ghostscript PDF/A rendering failed, consider setting PAPERLESS_OCR_USER_ARGS: '{"continue_on_soft_render_error": true}'

[2023-11-18 12:44:36,342] [ERROR] [paperless.consumer] Error occurred while consuming document lol.pdf: SubprocessOutputError: Ghostscript PDF/A rendering failed. See logs for more information.

Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_exec/ghostscript.py", line 232, in generate_pdfa

    p = run_polling_stderr(

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/subprocess/__init__.py", line 114, in run_polling_stderr

    raise CalledProcessError(proc.returncode, args, output=None, stderr=stderr)

subprocess.CalledProcessError: Command '['gs', '-dBATCH', '-dNOPAUSE', '-dSAFER', '-dCompatibilityLevel=1.6', '-sDEVICE=pdfwrite', '-dAutoRotatePages=/None', '-sColorConversionStrategy=LeaveColorUnchanged', '-dPDFSTOPONERROR', '-dAutoFilterColorImages=true', '-dAutoFilterGrayImages=true', '-dJPEGQ=95', '-dPDFA=2', '-dPDFACompatibilityPolicy=1', '-o', '-', '-sstdout=%stderr', '/tmp/ocrmypdf.io.whm0tpzu/fix_docinfo.pdf', '/tmp/ocrmypdf.io.whm0tpzu/pdfa.ps']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 321, in parse

    ocrmypdf.ocr(**args)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/api.py", line 347, in ocr

    return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 391, in run_pipeline

    optimize_messages = exec_concurrent(context, executor)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 308, in exec_concurrent

    pdf, messages = post_process(pdf, context, executor)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 239, in post_process

    pdf_out = convert_to_pdfa(pdf_out, ps_stub_out, context)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 789, in convert_to_pdfa

    context.plugin_manager.hook.generate_pdfa(

  File "/usr/local/lib/python3.9/site-packages/pluggy/_hooks.py", line 433, in __call__

    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)

  File "/usr/local/lib/python3.9/site-packages/pluggy/_manager.py", line 112, in _hookexec

    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)

  File "/usr/local/lib/python3.9/site-packages/pluggy/_callers.py", line 116, in _multicall

    raise exception.with_traceback(exception.__traceback__)

  File "/usr/local/lib/python3.9/site-packages/pluggy/_callers.py", line 80, in _multicall

    res = hook_impl.function(*args)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/builtin_plugins/ghostscript.py", line 77, in generate_pdfa

    ghostscript.generate_pdfa(

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_exec/ghostscript.py", line 246, in generate_pdfa

    raise SubprocessOutputError('Ghostscript PDF/A rendering failed') from e

ocrmypdf.exceptions.SubprocessOutputError: Ghostscript PDF/A rendering failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/consumer.py", line 425, in try_consume_file

    document_parser.parse(self.path, mime_type, self.filename)

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 344, in parse

    raise ParseError(

documents.parsers.ParseError: SubprocessOutputError: Ghostscript PDF/A rendering failed. See logs for more information.
```

### Paperless-ngx version

1.17.4

### Host OS

docker image

### Installation method

Docker - official image

**Comment by shamoon** [comment]
We don’t control Ghostscript and our docs specifically for this issue, I’m not sure what the purpose is of this bug report

https://docs.paperless-ngx.com/troubleshooting/#consumption-fails-with-ghostscript-pdfa-rendering-failed

**Comment by hydrargyrum** [comment]
@shamoon the bug is that "see logs" is wrong as there are no logs. no logs = worthless. how to fix it: display the logs of ghostscript so we know what's wrong in the end.

**Comment by shamoon** [comment]
Well, I’d say that opening a “bug report” for something that has many other issues / discussions and is specifically mentioned in our docs is not a great use of the time of the maintainers of this project.

But there is log output… that’s what you’ve pasted above? “See the logs” is also pointing you to the second line of the output above which tells you potentially how to fix it. The docs further clarify this

**Comment by hydrargyrum** [comment]
> Well, I’d say that opening a “bug report” for something that has many other issues / discussions and is specifically mentioned in our docs is not a great use of the time of the maintainers of this project.

I may not have read all bugs but for those I've read, the real subject was "file can't be parsed", but my subject is "useful logs are missing", so it's a different issue.

> But there is log output… that’s what you’ve pasted above? “See the logs” is also pointing you to the second line of the output above which tells you potentially how to fix it. The docs further clarify this

That's paperless' log that just suggests a workaround. It's merely a workaround. The real fix would be in ghostscript. But for that I expect paperless to tell more info on the ghostscript problem (just let ghostscript log in paperless logs, that'd still be better than currently).

**Comment by shamoon** [comment]
Sounds like a feature request

**Comment by hydrargyrum** [comment]
Ok, then can you convert it into a feature request?
