### ISSUE TITLE
[BUG] Import fails if tika processing fails

### ISSUE THREAD

**Issue by noseshimself** [paperless-ngx/paperless-ngx#4640]
### Description

For some (yet) unknown reason tika processing is failing with longer .odt files and leading to files not being imported instead of considering that step as optional (and adding UI elements to redi it later).

### Steps to reproduce

1. Drop a .odt file into the import directory.
2. Find this
``
[2023-11-19 20:42:33,281] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[cc8488d9-4967-462d-b574-0ea5e82c7bd7] raised unexpected: ConsumerError
Traceback (most recent call last):
  File "/usr/src/paperless/src/paperless_tika/parsers.py", line 55, in parse
    parsed = client.tika.as_text.from_file(document_path, mime_type)
  File "/usr/local/lib/python3.9/site-packages/tika_client/_resource_tika.py", line 36, in from_file
    return self._decoded_response(self._put_multipart(self.MULTI_PART_PLAIN_TEXT_CONTENT, filepath, mime_type))
  File "/usr/local/lib/python3.9/site-packages/tika_client/_utils.py", line 46, in _put_multipart
    resp.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/httpx/_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '500 Server Error' for url 'http://tika.app.bnc.net:9998/tika/form/text'
For more information check: https://httpstatuses.com/500

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 349, in main_wrap
    raise exc_info[1]
  File "/usr/src/paperless/src/documents/consumer.py", line 425, in try_consume_file
    document_parser.parse(self.path, mime_type, self.filename)
  File "/usr/src/paperless/src/paperless_tika/parsers.py", line 57, in parse
    raise ParseError(
documents.parsers.ParseError: Could not parse /tmp/paperless/paperless-ngxav6c3r0c/20210721 Flutschaden (Inventar) v1.odt with tika server at http://tika.app
For more information check: https://httpstatuses.com/500
``
in the log.
3. Importing is refused.

### Webserver logs

```bash
see above
```

### Paperless-ngx version

1.17.4

### Host OS

Debian 12

### Installation method

Docker - official image

**Comment by stumpylog** [comment]
Not seeing how this is a bug?  Tika can't process the file, so it fails, why would paperless not also fail?  Tika is a _requirement_ to gather anything about an office type format.
