### ISSUE TITLE
[BUG] Importing duplicates is leaving documents in the input queue

### ISSUE THREAD

**Issue by noseshimself** [paperless-ngx/paperless-ngx#4642]
### Description

Under certain conditions a duplicate input file is not shown under "Error" but remains in the input queue without further processing.

### Steps to reproduce

1. Add a file by putting it into the import directory
2. Add the same file
3. watch .../path

```
    environment:
      # application service
      - PAPERLESS_PORT=8000
      - PAPERLESS_URL=https://test-dms.
      ## - PAPERLESS_CSRF_TRUSTED_ORIGINS=<comma-separated-list> A list of trusted origins for unsafe requests
      ## - PAPERLESS_ALLOWED_HOSTS=<comma-separated-list> If you're planning on putting Paperless on the open internet, then you really should set this value to the domain name you're using.
      ## - PAPERLESS_CORS_ALLOWED_HOSTS=<comma-separated-list> You need to add your servers to the list of allowed hosts that can do CORS calls. Set this to your public domain name. Can also be set using PAPERLESS_URL (see above).
      ## - PAPERLESS_TRUSTED_PROXIES=<comma-separated-list> This may be needed to prevent IP address spoofing if you are using e.g. fail2ban with log entries for failed authorization attempts. Value should be IP address(es).
      - PAPERLESS_TIME_ZONE=Etc/UTC
      - PAPERLESS_OCR_LANGUAGE=deu+eng
      - PAPERLESS_SECRET_KEY=will-remain-a-secret
      - PAPERLESS_ADMIN_USER=docmaster
      - PAPERLESS_ADMIN_MAIL=docmaster@local
      - PAPERLESS_ADMIN_PASSWORD=stays secret.too
      -     ## - PAPERLESS_LOGGING_DIR=
      ## - PAPERLESS_LOGROTATE_MAX_SIZE=<num>
      ## - PAPERLESS_LOGROTATE_MAX_BACKUPS=<num>
      # OCR options
      - PAPERLESS_OCR_MODE=skip
      - PAPERLESS_OCR_CLEAN=clean-final
      - PAPERLESS_OCR_DESKEW=true
      - PAPERLESS_OCR_ROTATE_PAGES=true
      - PAPERLESS_OCR_ROTATE_PAGES_THRESHOLD=10 # default 12
      - PAPERLESS_OCR_OUTPUT_TYPE=pdfa-3
      - PAPERLESS_ENABLE_NLTK=1
      - PAPERLESS_CONSUMER_RECURSIVE=true
      - PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS=true
      - PAPERLESS_CONSUMER_IGNORE_PATTERNS=[".*~", ".directory"]
      - PAPERLESS_FILENAME_FORMAT="{created_year}/{title}"
      ## - PAPERLESS_FILENAME_DATE_ORDER=
      - PAPERLESS_NUMBER_OF_SUGGESTED_DATES=5
      - PAPERLESS_CONSUMER_ENABLE_BARCODES=true
      - PAPERLESS_CONSUMER_BARCODE_TIFF_SUPPORT=true
      - PAPERLESS_CONSUMER_ENABLE_ASN_BARCODE=true
      ## - PAPERLESS_CONSUMER_ENABLE_COLLATE_DOUBLE_SIDED=true better not
      # Redis redis://<username>:<password>@<host>:<port>/DB index>
      - PAPERLESS_REDIS=redis://:pass@redis:6379/3
      # Database
      ## - PAPERLESS_DBENGINE=postgresql
      ## - PAPERLESS_DBHOST=postgres
      - PAPERLESS_DBENGINE=mariadb
      - PAPERLESS_DBHOST=mariadb
      - PAPERLESS_DBNAME=dms_test
      - PAPERLESS_DBUSER=dms-test
      - PAPERLESS_DBPASS=ffsffeaasdddasd
      # Apache tika
      - PAPERLESS_TIKA_ENABLED=1
      - PAPERLESS_TIKA_GOTENBERG_ENDPOINT=http://gotenberg:3000
      - PAPERLESS_TIKA_ENDPOINT=http://tika:9998


### Webserver logs

```bash
[2023-11-20 00:45:42,903] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[96aae08a-77ad-440d-aac7-e2c70d09e2cb] raised unexpected: ConsumerError('20100115 Entgeltabrechnung.pdf: Not consuming 20100115 Entgeltabrechnung Patzner, Achim
2010-01.pdf: It is a duplicate of 20100115 Entgeltabrechnung (#419)')

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/paperless/src/documents/tasks.py", line 156, in consume_file
    document = Consumer().try_consume_file(
  File "/usr/src/paperless/src/documents/consumer.py", line 352, in try_consume_file
    self.pre_check_duplicate()
  File "/usr/src/paperless/src/documents/consumer.py", line 148, in pre_check_duplicate
    self._fail(
  File "/usr/src/paperless/src/documents/consumer.py", line 109, in _fail
    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception documents.consumer.ConsumerError: 20100115 Entgeltabrechnung.pdf: Not consuming 20100115 Entgeltabrechnung.pdf: It is a duplicate of 20100115 Entgeltabrechnung (#419)
```

### Paperless-ngx version

1.17.4

### Host OS

Debian 12

### Installation method

Docker - official image

### Browser

Chrome

**Comment by shamoon** [comment]
You’re saying the “bug” is that paperless is not deleting the duplicate?

**Comment by noseshimself** [comment]
It is a duplicate but just remains in the input queue while some other duplicates are moved to the error tab.

**Comment by stumpylog** [comment]
I can't reproduce that at all.  Which makes sense, a task is a task, with the same callbacks to update status on failure or success.  It would require something with celery or django-celery-results (I forget which one sends the signals).

**Comment by noseshimself** [comment]
I found some more pre-conditions around it; it seems that as soon as tika is failing on an unrelated job further processing of the rest of the waiting queue stops. After removing all .odt jobs from the import directory tree PDF files were processed.

I'm still checking why tika is failing on the odt files.

**Comment by stumpylog** [comment]
Tasks in the queue are independent, so that doesn't make sense either.  Even if a worker dies, it will be recreated.  And an exception isn't enough the kill a worker

**Comment by heiner73** [comment]
same issue here. It started after I clicked "Dismiss all"... After that click all queues stay empty except "Queued", which has completely wrong amount of files...

**Comment by noseshimself** [comment]
> Tasks in the queue are independent, so that doesn't make sense either. Even if a worker dies, it will be recreated. And an exception isn't enough the kill a worker

I'm probably bad at explaining what is disturbing me here. There are of course error states that require reprocessing a file but detecting a duplicate is certainly not one of these cases. Nevertheless files that were not added to the DMS are moved to the "failed" list and the files remain in the consumption directory.

I can understand being careful and not removing anything that has not been imported into the DMS but in this case they should at least be moved to another directory which should be appropriately be named (in this case "is a duplicate").

Right now I have to check the output in "failed" whether there was anything that was not a duplicate and manually delete all the duplicates. That's why there have been those feature requests for additional UI elements for retrying or deleting entreis from the consumption directory.

**Comment by shamoon** [comment]
Well that does sound like a feature request. In general yes, we assume safer to not delete people’s data

**Comment by heiner73** [comment]
okay, after removing all files from queue and waiting until all "tasks" were finished, the "tasks-view" seems to work as expected again...

**Comment by ppuschmann** [comment]
I'd only suspect that there shouldn't be an exception thrown for a duplicate import of a file.

```
[2023-12-31 15:38:02,533] [ERROR] [paperless.consumer] Not consuming <freshly-added-filename>: It is a duplicate of <already-existing-document-name> (#442)
[2023-12-31 15:38:02,622] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[857bd9fd-fc58-44a6-8a15-8c5c2838a315] raised unexpected: ConsumerError('<freshly-added-filename>: Not consuming <freshly-added-filename>: It is a duplicate of <already-existing-document-name> (#442)')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/paperless/src/documents/tasks.py", line 167, in consume_file
    document = Consumer().try_consume_file(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/paperless/src/documents/consumer.py", line 373, in try_consume_file
    self.pre_check_duplicate()
  File "/usr/src/paperless/src/documents/consumer.py", line 155, in pre_check_duplicate
    self._fail(
  File "/usr/src/paperless/src/documents/consumer.py", line 115, in _fail
    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
documents.consumer.ConsumerError: <freshly-added-filename>: Not consuming <freshly-added-filename>: It is a duplicate of <already-existing-document-name> (#442)
```

On the other hand I'm very glad there's some detection for duplicate content.
