### ISSUE TITLE
[BUG] Getting MissingDependencyError: gs when consuming after upgrade to 2.0.0

### ISSUE THREAD

**Issue by cestes** [paperless-ngx/paperless-ngx#4698]
### Description

throwing exception when attempting to consume new pdf.  Was working fine before upgrade (bare metal).

### Steps to reproduce

drag pdf to dashboard

### Webserver logs

```bash
[2023-11-29 14:47:06,252] [ERROR] [paperless.consumer] Error occurred while consuming document xyz.pdf: MissingDependencyError: gs
Traceback (most recent call last):
  File "/opt/paperless/src/paperless_tesseract/parsers.py", line 321, in parse
    ocrmypdf.ocr(**args)
  File "/opt/paperless/.local/lib/python3.9/site-packages/ocrmypdf/api.py", line 374, in ocr
    check_options(options, plugin_manager)
  File "/opt/paperless/.local/lib/python3.9/site-packages/ocrmypdf/_validation.py", line 248, in check_options
    _check_plugin_options(options, plugin_manager)
  File "/opt/paperless/.local/lib/python3.9/site-packages/ocrmypdf/_validation.py", line 241, in _check_plugin_options
    plugin_manager.hook.check_options(options=options)
  File "/opt/paperless/.local/lib/python3.9/site-packages/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "/opt/paperless/.local/lib/python3.9/site-packages/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/opt/paperless/.local/lib/python3.9/site-packages/pluggy/_callers.py", line 113, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/opt/paperless/.local/lib/python3.9/site-packages/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
  File "/opt/paperless/.local/lib/python3.9/site-packages/ocrmypdf/builtin_plugins/ghostscript.py", line 51, in check_options
    check_external_program(
  File "/opt/paperless/.local/lib/python3.9/site-packages/ocrmypdf/subprocess/__init__.py", line 341, in check_external_program
    raise MissingDependencyError(program)
ocrmypdf.exceptions.MissingDependencyError: gs
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/paperless/src/documents/consumer.py", line 441, in try_consume_file
    document_parser.parse(self.path, mime_type, self.filename)
  File "/opt/paperless/src/paperless_tesseract/parsers.py", line 388, in parse
    raise ParseError(f"{e.__class__.__name__}: {e!s}") from e
documents.parsers.ParseError: MissingDependencyError: gs
```
```


### Browser logs

_No response_

### Paperless-ngx version

2.0.0

### Host OS

Debian 11

### Installation method

Bare metal

### Browser

Chrome

### Configuration changes

_No response_

### Other

updated requirements from requirements.txt - "sudo -Hu paperless gs" starts GhostScript cli.

**Comment by shamoon** [comment]
See https://github.com/paperless-ngx/paperless-ngx/issues/4696

**Comment by epcos71** [comment]
Upgrade to Debian 12, then GS has the right version
