### ISSUE TITLE
[BUG] v2.0.0 "ERROR unusual color space"  but  OK  v1.7.4

### ISSUE THREAD

**Issue by ctout76** [paperless-ngx/paperless-ngx#4707]
### Description

Conversion error only with version 2.0.0.
Conversion with the same file is OK in version 1.17.4

Error message:
_ColorConversionNeededError: The input PDF has an unusual color space. Use
--color-conversion-strategy to convert to a common color space
such as RGB, or use --output-type pdf to skip PDF/A conversion
and retain the original color space._

### Steps to reproduce

1: PDF selected for the upload (PDF file https://www.westermo.com/-/media/Files/User-guides/westermo_ug_6618-2202_td-36_revh.pdf) Paperless-ngx v2.0.0
2: Paperless start with processing the PDF document
3: Then after a few second the process stopped and the error message below was shown "ColorConversionNeededError: The input PDF has an unusual color space. Use
--color-conversion-strategy to convert to a common color space
such as RGB, or use --output-type pdf to skip PDF/A conversion
and retain the original color space."

### Webserver logs

```bash
[2023-11-29 19:28:41,767] [INFO] [paperless.consumer] Consuming westermo_ug_6618-2202_td-36_revh.pdf

[2023-11-29 19:28:41,773] [DEBUG] [paperless.consumer] Detected mime type: application/pdf

[2023-11-29 19:28:41,774] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser

[2023-11-29 19:28:41,777] [DEBUG] [paperless.consumer] Parsing westermo_ug_6618-2202_td-36_revh.pdf...

[2023-11-29 19:28:43,522] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-ngxqzq9up9n/westermo_ug_6618-2202_td-36_revh.pdf'), 'output_file': PosixPath('/tmp/paperless/paperless-kpv5t4f9/archive.pdf'), 'use_threads': True, 'jobs': 2, 'language': 'fra', 'output_type': 'pdfa', 'progress_bar': False, 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-kpv5t4f9/sidecar.txt')}

[2023-11-29 19:28:55,244] [ERROR] [paperless.consumer] Error occurred while consuming document westermo_ug_6618-2202_td-36_revh.pdf: ColorConversionNeededError: The input PDF has an unusual color space. Use

--color-conversion-strategy to convert to a common color space

such as RGB, or use --output-type pdf to skip PDF/A conversion

and retain the original color space.

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 321, in parse

    ocrmypdf.ocr(**args)

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/api.py", line 375, in ocr

    return run_pipeline(options=options, plugin_manager=plugin_manager)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 225, in run_pipeline

    return _run_pipeline(options, plugin_manager)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 192, in _run_pipeline

    optimize_messages = exec_concurrent(context, executor)

                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 148, in exec_concurrent

    pdf, messages = postprocess(pdf, context, executor)

                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/_common.py", line 420, in postprocess

    pdf_out = convert_to_pdfa(pdf_out, ps_stub_out, context)

              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipeline.py", line 814, in convert_to_pdfa

    context.plugin_manager.hook.generate_pdfa(

  File "/usr/local/lib/python3.11/site-packages/pluggy/_hooks.py", line 493, in __call__

    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/pluggy/_manager.py", line 115, in _hookexec

    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/pluggy/_callers.py", line 113, in _multicall

    raise exception.with_traceback(exception.__traceback__)

  File "/usr/local/lib/python3.11/site-packages/pluggy/_callers.py", line 77, in _multicall

    res = hook_impl.function(*args)

          ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/builtin_plugins/ghostscript.py", line 119, in generate_pdfa

    ghostscript.generate_pdfa(

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_exec/ghostscript.py", line 296, in generate_pdfa

    raise ColorConversionNeededError()

ocrmypdf.exceptions.ColorConversionNeededError: The input PDF has an unusual color space. Use

--color-conversion-strategy to convert to a common color space

such as RGB, or use --output-type pdf to skip PDF/A conversion

and retain the original color space.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 349, in main_wrap

    raise exc_info[1]

  File "/usr/src/paperless/src/documents/consumer.py", line 441, in try_consume_file

    document_parser.parse(self.path, mime_type, self.filename)

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 388, in parse

    raise ParseError(f"{e.__class__.__name__}: {e!s}") from e

documents.parsers.ParseError: ColorConversionNeededError: The input PDF has an unusual color space. Use

--color-conversion-strategy to convert to a common color space

such as RGB, or use --output-type pdf to skip PDF/A conversion

and retain the original color space.
```

### Paperless-ngx version

2.0.0

### Host OS

Synology Docker - ghcr.io/paperless-ngx

### Installation method

Docker - official image

### Browser

Mozilla Firefox

**Comment by shamoon** [comment]
See https://github.com/paperless-ngx/paperless-ngx/issues/4702

**Comment by ctout76** [comment]
This change is not without consequences for users... Not a good idea... 🙁

**Comment by shamoon** [comment]
1. Im not sure of the purpose of your comment. Obviously, we do not aim to make things more difficult for users.
2. The change comes from a dependency we use and no one came across this in our beta release. But it seems to not be so rare, so:
3. This is a duplicate of another issue, if look at the one I linked we've already decided on a plan.
