### ISSUE TITLE
[BUG] unusual color space - need help investigating

### ISSUE THREAD

**Issue by amo13** [paperless-ngx/paperless-ngx#4720]
### Description

This issue is linked to an update in ocrmypdf. When trying to import the below PDF, ocrmypdf complains about "an unusual color space" and advises to use `--color-conversion-strategy`. The PDF has just a simple RBG profile though and it looks to me like it should be okay. 

I am trying to pinpoint the issue before reporting it upstream (if it is an upstream issue and no invocation issue). How exactly is ocrmypdf invoked on the file? What are the parameters used?

### Steps to reproduce

Drag and drop the following document onto the web UI.

[01_Schulbuchkopie_2020_Broschuere.pdf](https://github.com/paperless-ngx/paperless-ngx/files/13513932/01_Schulbuchkopie_2020_Broschuere.pdf)

### Webserver logs

```bash
Nov 30 15:16:24 archvm celery[76600]: [2023-11-30 14:16:24,621] [ERROR] [paperless.consumer] Error occurred while consuming document 01_Schulbuchkopie_2020_Broschuere.pdf: ColorConversionNeededError: The input PDF has an unusual color space. Use
Nov 30 15:16:24 archvm celery[76600]: --color-conversion-strategy to convert to a common color space
Nov 30 15:16:24 archvm celery[76600]: such as RGB, or use --output-type pdf to skip PDF/A conversion
Nov 30 15:16:24 archvm celery[76600]: and retain the original color space.
Nov 30 15:16:24 archvm celery[76600]: Traceback (most recent call last):
Nov 30 15:16:24 archvm celery[76600]:   File "/usr/share/paperless/src/paperless_tesseract/parsers.py", line 321, in parse
Nov 30 15:16:24 archvm celery[76600]:     ocrmypdf.ocr(**args)
Nov 30 15:16:24 archvm celery[76600]:   File "/usr/lib/python3.11/site-packages/ocrmypdf/api.py", line 375, in ocr
Nov 30 15:16:24 archvm celery[76600]:     return run_pipeline(options=options, plugin_manager=plugin_manager)
Nov 30 15:16:24 archvm celery[76600]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 30 15:16:24 archvm celery[76600]:   File "/usr/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 225, in run_pipeline
Nov 30 15:16:24 archvm celery[76600]:     return _run_pipeline(options, plugin_manager)
Nov 30 15:16:24 archvm celery[76600]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 30 15:16:24 archvm celery[76600]:   File "/usr/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 192, in _run_pipeline
Nov 30 15:16:24 archvm celery[76600]:     optimize_messages = exec_concurrent(context, executor)
Nov 30 15:16:24 archvm celery[76600]:                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 30 15:16:24 archvm celery[76600]:   File "/usr/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 148, in exec_concurrent
Nov 30 15:16:24 archvm celery[76600]:     pdf, messages = postprocess(pdf, context, executor)
Nov 30 15:16:24 archvm celery[76600]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 30 15:16:24 archvm celery[76600]:   File "/usr/lib/python3.11/site-packages/ocrmypdf/_pipelines/_common.py", line 420, in postprocess
Nov 30 15:16:24 archvm celery[76600]:     pdf_out = convert_to_pdfa(pdf_out, ps_stub_out, context)
Nov 30 15:16:24 archvm celery[76600]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 30 15:16:24 archvm celery[76600]:   File "/usr/lib/python3.11/site-packages/ocrmypdf/_pipeline.py", line 814, in convert_to_pdfa
Nov 30 15:16:24 archvm celery[76600]:     context.plugin_manager.hook.generate_pdfa(
Nov 30 15:16:24 archvm celery[76600]:   File "/usr/lib/python3.11/site-packages/pluggy/_hooks.py", line 493, in __call__
Nov 30 15:16:24 archvm celery[76600]:     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
Nov 30 15:16:24 archvm celery[76600]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 30 15:16:24 archvm celery[76600]:   File "/usr/lib/python3.11/site-packages/pluggy/_manager.py", line 115, in _hookexec
Nov 30 15:16:24 archvm celery[76600]:     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
Nov 30 15:16:24 archvm celery[76600]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 30 15:16:24 archvm celery[76600]:   File "/usr/lib/python3.11/site-packages/pluggy/_callers.py", line 113, in _multicall
Nov 30 15:16:24 archvm celery[76600]:     raise exception.with_traceback(exception.__traceback__)
Nov 30 15:16:24 archvm celery[76600]:   File "/usr/lib/python3.11/site-packages/pluggy/_callers.py", line 77, in _multicall
Nov 30 15:16:24 archvm celery[76600]:     res = hook_impl.function(*args)
Nov 30 15:16:24 archvm celery[76600]:           ^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 30 15:16:24 archvm celery[76600]:   File "/usr/lib/python3.11/site-packages/ocrmypdf/builtin_plugins/ghostscript.py", line 119, in generate_pdfa
Nov 30 15:16:24 archvm celery[76600]:     ghostscript.generate_pdfa(
Nov 30 15:16:24 archvm celery[76600]:   File "/usr/lib/python3.11/site-packages/ocrmypdf/_exec/ghostscript.py", line 296, in generate_pdfa
Nov 30 15:16:24 archvm celery[76600]:     raise ColorConversionNeededError()
Nov 30 15:16:24 archvm celery[76600]: ocrmypdf.exceptions.ColorConversionNeededError: The input PDF has an unusual color space. Use
Nov 30 15:16:24 archvm celery[76600]: --color-conversion-strategy to convert to a common color space
Nov 30 15:16:24 archvm celery[76600]: such as RGB, or use --output-type pdf to skip PDF/A conversion
Nov 30 15:16:24 archvm celery[76600]: and retain the original color space.
Nov 30 15:16:24 archvm celery[76600]: The above exception was the direct cause of the following exception:
Nov 30 15:16:24 archvm celery[76600]: Traceback (most recent call last):
Nov 30 15:16:24 archvm celery[76600]:   File "/usr/lib/python3.11/site-packages/asgiref/sync.py", line 349, in main_wrap
Nov 30 15:16:24 archvm celery[76600]:     raise exc_info[1]
Nov 30 15:16:24 archvm celery[76600]:   File "/usr/share/paperless/src/documents/consumer.py", line 441, in try_consume_file
Nov 30 15:16:24 archvm celery[76600]:     document_parser.parse(self.path, mime_type, self.filename)
Nov 30 15:16:24 archvm celery[76600]:   File "/usr/share/paperless/src/paperless_tesseract/parsers.py", line 388, in parse
Nov 30 15:16:24 archvm celery[76600]:     raise ParseError(f"{e.__class__.__name__}: {e!s}") from e
Nov 30 15:16:24 archvm celery[76600]: documents.parsers.ParseError: ColorConversionNeededError: The input PDF has an unusual color space. Use
Nov 30 15:16:24 archvm celery[76600]: --color-conversion-strategy to convert to a common color space
Nov 30 15:16:24 archvm celery[76600]: such as RGB, or use --output-type pdf to skip PDF/A conversion
Nov 30 15:16:24 archvm celery[76600]: and retain the original color space.
Nov 30 15:16:25 archvm celery[76600]: [2023-11-30 14:16:25,020] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[b731a907-41e4-4f18-958a-0eeaa4a0c577] raised unexpected: ConsumerError('01_Schulbuchkopie_2020_Broschuere.pdf: Error occurred while consuming document 01_Schulbuchkopie_2020_Broschuere.pdf: ColorConversionNeededError: The input PDF has an unusual color space. Use\n--color-conversion-strategy to convert to a common color space\nsuch as RGB, or use --output-type pdf to skip PDF/A conversion\nand retain the original color space.\n')
Nov 30 15:16:25 archvm celery[76600]: Traceback (most recent call last):
Nov 30 15:16:25 archvm celery[76600]:   File "/usr/share/paperless/src/paperless_tesseract/parsers.py", line 321, in parse
Nov 30 15:16:25 archvm celery[76600]:     ocrmypdf.ocr(**args)
Nov 30 15:16:25 archvm celery[76600]:   File "/usr/lib/python3.11/site-packages/ocrmypdf/api.py", line 375, in ocr
Nov 30 15:16:25 archvm celery[76600]:     return run_pipeline(options=options, plugin_manager=plugin_manager)
Nov 30 15:16:25 archvm celery[76600]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 30 15:16:25 archvm celery[76600]:   File "/usr/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 225, in run_pipeline
Nov 30 15:16:25 archvm celery[76600]:     return _run_pipeline(options, plugin_manager)
Nov 30 15:16:25 archvm celery[76600]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 30 15:16:25 archvm celery[76600]:   File "/usr/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 192, in _run_pipeline
Nov 30 15:16:25 archvm celery[76600]:     optimize_messages = exec_concurrent(context, executor)
Nov 30 15:16:25 archvm celery[76600]:                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 30 15:16:25 archvm celery[76600]:   File "/usr/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 148, in exec_concurrent
Nov 30 15:16:25 archvm celery[76600]:     pdf, messages = postprocess(pdf, context, executor)
Nov 30 15:16:25 archvm celery[76600]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 30 15:16:25 archvm celery[76600]:   File "/usr/lib/python3.11/site-packages/ocrmypdf/_pipelines/_common.py", line 420, in postprocess
Nov 30 15:16:25 archvm celery[76600]:     pdf_out = convert_to_pdfa(pdf_out, ps_stub_out, context)
Nov 30 15:16:25 archvm celery[76600]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 30 15:16:25 archvm celery[76600]:   File "/usr/lib/python3.11/site-packages/ocrmypdf/_pipeline.py", line 814, in convert_to_pdfa
Nov 30 15:16:25 archvm celery[76600]:     context.plugin_manager.hook.generate_pdfa(
Nov 30 15:16:25 archvm celery[76600]:   File "/usr/lib/python3.11/site-packages/pluggy/_hooks.py", line 493, in __call__
Nov 30 15:16:25 archvm celery[76600]:     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
Nov 30 15:16:25 archvm celery[76600]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 30 15:16:25 archvm celery[76600]:   File "/usr/lib/python3.11/site-packages/pluggy/_manager.py", line 115, in _hookexec
Nov 30 15:16:25 archvm celery[76600]:     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
Nov 30 15:16:25 archvm celery[76600]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 30 15:16:25 archvm celery[76600]:   File "/usr/lib/python3.11/site-packages/pluggy/_callers.py", line 113, in _multicall
Nov 30 15:16:25 archvm celery[76600]:     raise exception.with_traceback(exception.__traceback__)
Nov 30 15:16:25 archvm celery[76600]:   File "/usr/lib/python3.11/site-packages/pluggy/_callers.py", line 77, in _multicall
Nov 30 15:16:25 archvm celery[76600]:     res = hook_impl.function(*args)
Nov 30 15:16:25 archvm celery[76600]:           ^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 30 15:16:25 archvm celery[76600]:   File "/usr/lib/python3.11/site-packages/ocrmypdf/builtin_plugins/ghostscript.py", line 119, in generate_pdfa
Nov 30 15:16:25 archvm celery[76600]:     ghostscript.generate_pdfa(
Nov 30 15:16:25 archvm celery[76600]:   File "/usr/lib/python3.11/site-packages/ocrmypdf/_exec/ghostscript.py", line 296, in generate_pdfa
Nov 30 15:16:25 archvm celery[76600]:     raise ColorConversionNeededError()
Nov 30 15:16:25 archvm celery[76600]: ocrmypdf.exceptions.ColorConversionNeededError: The input PDF has an unusual color space. Use
Nov 30 15:16:25 archvm celery[76600]: --color-conversion-strategy to convert to a common color space
Nov 30 15:16:25 archvm celery[76600]: such as RGB, or use --output-type pdf to skip PDF/A conversion
Nov 30 15:16:25 archvm celery[76600]: and retain the original color space.
Nov 30 15:16:25 archvm celery[76600]: The above exception was the direct cause of the following exception:
Nov 30 15:16:25 archvm celery[76600]: Traceback (most recent call last):
Nov 30 15:16:25 archvm celery[76600]:   File "/usr/lib/python3.11/site-packages/asgiref/sync.py", line 349, in main_wrap
Nov 30 15:16:25 archvm celery[76600]:     raise exc_info[1]
Nov 30 15:16:25 archvm celery[76600]:   File "/usr/share/paperless/src/documents/consumer.py", line 441, in try_consume_file
Nov 30 15:16:25 archvm celery[76600]:     document_parser.parse(self.path, mime_type, self.filename)
Nov 30 15:16:25 archvm celery[76600]:   File "/usr/share/paperless/src/paperless_tesseract/parsers.py", line 388, in parse
Nov 30 15:16:25 archvm celery[76600]:     raise ParseError(f"{e.__class__.__name__}: {e!s}") from e
Nov 30 15:16:25 archvm celery[76600]: documents.parsers.ParseError: ColorConversionNeededError: The input PDF has an unusual color space. Use
Nov 30 15:16:25 archvm celery[76600]: --color-conversion-strategy to convert to a common color space
Nov 30 15:16:25 archvm celery[76600]: such as RGB, or use --output-type pdf to skip PDF/A conversion
Nov 30 15:16:25 archvm celery[76600]: and retain the original color space.
Nov 30 15:16:25 archvm celery[76600]: The above exception was the direct cause of the following exception:
Nov 30 15:16:25 archvm celery[76600]: Traceback (most recent call last):
Nov 30 15:16:25 archvm celery[76600]:   File "/usr/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
Nov 30 15:16:25 archvm celery[76600]:     R = retval = fun(*args, **kwargs)
Nov 30 15:16:25 archvm celery[76600]:                  ^^^^^^^^^^^^^^^^^^^^
Nov 30 15:16:25 archvm celery[76600]:   File "/usr/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
Nov 30 15:16:25 archvm celery[76600]:     return self.run(*args, **kwargs)
Nov 30 15:16:25 archvm celery[76600]:            ^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 30 15:16:25 archvm celery[76600]:   File "/usr/share/paperless/src/documents/tasks.py", line 167, in consume_file
Nov 30 15:16:25 archvm celery[76600]:     document = Consumer().try_consume_file(
Nov 30 15:16:25 archvm celery[76600]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 30 15:16:25 archvm celery[76600]:   File "/usr/share/paperless/src/documents/consumer.py", line 469, in try_consume_file
Nov 30 15:16:25 archvm celery[76600]:     self._fail(
Nov 30 15:16:25 archvm celery[76600]:   File "/usr/share/paperless/src/documents/consumer.py", line 113, in _fail
Nov 30 15:16:25 archvm celery[76600]:     raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
Nov 30 15:16:25 archvm celery[76600]: documents.consumer.ConsumerError: 01_Schulbuchkopie_2020_Broschuere.pdf: Error occurred while consuming document 01_Schulbuchkopie_2020_Broschuere.pdf: ColorConversionNeededError: The input PDF has an unusual color space. Use
Nov 30 15:16:25 archvm celery[76600]: --color-conversion-strategy to convert to a common color space
Nov 30 15:16:25 archvm celery[76600]: such as RGB, or use --output-type pdf to skip PDF/A conversion
Nov 30 15:16:25 archvm celery[76600]: and retain the original color space.
```

### Paperless-ngx version

2.0.0

### Host OS

Archlinux

### Installation method

Bare metal

### Browser

Firefox

**Comment by amo13** [comment]
Oh no... sorry about that =/ I confused the paperless and ocrmypdf repos when searching.
Thanks for the reminder and the reference to the other issue.
