### ISSUE TITLE
[BUG] Error ValueError: max object id is too high to create new objects

### ISSUE THREAD

**Issue by philsch85** [paperless-ngx/paperless-ngx#4810]
### Description

I recieve the Message "ValueError: max object id is too high to create new objects" while trying to upload a new pdf file via web-interface.

### Steps to reproduce

Upload File via Android-App results in the same error

### Webserver logs

```bash
[2023-12-04 18:46:14,224] [DEBUG] [paperless.consumer] Parsing 20230918_123_Vertragsinformationen_2647291.pdf...

[2023-12-04 18:46:14,521] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-ngxqivyvs47/20230918_123_Vertragsinformationen_2647291.pdf'), 'output_file': PosixPath('/tmp/paperless/paperless-cr83kc2m/archive.pdf'), 'use_threads': True, 'jobs': 4, 'language': 'deu', 'output_type': 'pdfa', 'progress_bar': False, 'color_conversion_strategy': 'RGB', 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-cr83kc2m/sidecar.txt')}

[2023-12-04 18:46:14,817] [ERROR] [paperless.consumer] Error occurred while consuming document 20230918_123_Vertragsinformationen_2647291.pdf: ValueError: max object id is too high to create new objects

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 330, in parse

    ocrmypdf.ocr(**args)

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/api.py", line 375, in ocr

    return run_pipeline(options=options, plugin_manager=plugin_manager)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 225, in run_pipeline

    return _run_pipeline(options, plugin_manager)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 192, in _run_pipeline

    optimize_messages = exec_concurrent(context, executor)

                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 142, in exec_concurrent

    pdf = ocrgraft.finalize()

          ^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_graft.py", line 203, in finalize

    self.pdf_base.save(self.output_file)

  File "/usr/local/lib/python3.11/site-packages/pikepdf/_methods.py", line 716, in save

    self._save(

  File "/usr/local/lib/python3.11/site-packages/pikepdf/_cpphelpers.py", line 25, in update_xmp_pdfversion

    with pdf.open_metadata(set_pikepdf_as_editor=False, update_docinfo=False) as meta:

  File "/usr/local/lib/python3.11/site-packages/pikepdf/models/metadata.py", line 505, in __exit__

    self._apply_changes()

  File "/usr/local/lib/python3.11/site-packages/pikepdf/models/metadata.py", line 580, in _apply_changes

    self._pdf.Root.Metadata = Stream(self._pdf, xml)

                              ^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/pikepdf/objects.py", line 292, in __new__

    stream = _core._new_stream(owner, data)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

ValueError: max object id is too high to create new objects

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 349, in main_wrap

    raise exc_info[1]

  File "/usr/src/paperless/src/documents/consumer.py", line 441, in try_consume_file

    document_parser.parse(self.path, mime_type, self.filename)

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 397, in parse

    raise ParseError(f"{e.__class__.__name__}: {e!s}") from e

documents.parsers.ParseError: ValueError: max object id is too high to create new objects
```

### Paperless-ngx version

2.0.1

### Host OS

Debian 12

### Installation method

Docker - official image

### Browser

Chrome Windows-based

**Comment by stumpylog** [comment]
The PDF is either corrupted or has some sort of loop in it and is trying to create millions of objects (roughly 2.1 million).  There's nothing we, pikepdf or qpdf can do about it.
