### ISSUE TITLE
Document Renamer fails 

### ISSUE THREAD

**Issue by MightyMirko** [paperless-ngx/paperless-ngx#4817]
### Description

Hello Folks,

i just pulled the newest version and tried out some features since i was already on the network:

I wanted to rename my files with

`docker exec -it casadepapel document_renamer`

```
Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/paperless/src/documents/management/commands/document_renamer.py", line 19, in handle
    logging.getLogger().handlers[0].level = logging.ERROR
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

```

### Steps to reproduce

compose.yml

```
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data
  db:
    image: mariadb:10.6.4-focal
    restart: unless-stopped
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MARIADB_HOST:          ${MARIADB_HOST}
      MARIADB_DATABASE:      ${MARIADB_DATABASE}
      MARIADB_USER:          ${MARIADB_USER}
      MARIADB_PASSWORD:      ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}

 webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    container_name: casadepapel
    depends_on:
      - db
      - broker
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - /opt/docker/matosin.de/2030_paperless/settings_ldap.py:/usr/src/paperless/src/paperless/settings_ldap.py:ro
      - /opt/docker/matosin.de/2030_paperless/export_paper:/usr/src/paperless/export
      - /opt/docker/matosin.de/2030_paperless/consumerfolder:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: ${MARIADB_HOST}
      USERMAP_UID: 1000
      USERMAP_GID: 100
      PAPERLESS_SECRET_KEY: ${PAPERLESS_SECRET_KEY}  # Set a very long sequence of random characters
      PAPERLESS_TIME_ZONE: Europe/Berlin  # Set your desired timezone
      PAPERLESS_OCR_LANGUAGE: ${LANG}  # Set the default language for OCR
      PAPERLESS_DBENGINE: ${DB_ENGINE}
      PAPERLESS_DBUSER: ${MARIADB_USER} # only needed if non-default username
      PAPERLESS_DBPASS: ${MARIADB_PASSWORD} # only needed if non-default password
      PAPERLESS_DBPORT: ${PORT}
      #PAPERLESS_ALLOWED_HOSTS: ${PAPERLESS_ALLOWED_HOSTS}
      PAPERLESS_TRUSTED_PROXIES: ${PAPERLESS_TRUSTED_PROXIES}
      USE_X_FORWARDED_HOST: true
      USE_X_FORWARD_PORT: true
      PAPERLESS_URL: ${PAPERLESS_URL}
      #PAPERLESS_CORS_ALLOWED_HOSTS: ${PAPERLESS_CORS_ALLOWED_HOSTS}
      PAPERLESS_CONSUMER_RECURSIVE: true
      PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: true
      PAPERLESS_FILENAME_FORMAT: ${FILENAMES}
      PAPERLESS_FILENAME_FORMAT_REMOVE_NONE: true
      PAPERLESS_OCR_PAGES: 20
      PAPERLESS_TASK_WORKERS: 2
      PAPERLESS_THREADS_PER_WORKER: 1
      DJANGO_SETTINGS_MODULE: "paperless.settings_ldap"
      PAPERLESS_LDAP_PIP_INSTALL: "true"
      #PAPERLESS_LDAP_LLDAP_FIX: true
    networks:
      - 2030-pub
      - 2030_paperless_ngx_default
        
  
  periodic-backup:
    #build: /opt/docker/matosin.de/periodicbackup/mysql-mariadb/periodic-backup/
    image: periodicdb_backup_dec2023
    container_name: database-backup-paperless
    environment:
      MYSQL_CONTAINER_NAME: ${MARIADB_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/backup:/opt/mysql/backup
    command: crond -f -d 8
    restart: always
    
networks:
  2030-pub:
    external: True
  2030_paperless_ngx_default:
    external: True
    
volumes:
  data:
  media:
  pgdata:
  redisdata:
  dbdata:
   
  
```

Environment 
FILENAMES={owner_username}/{created_year}/{created_year}{created_month}_{title}-{tag_list}
DB_ENGINE=mariadb
LANG=fra+eng+deu

Rest is irrelevant

### Webserver logs

```bash
[2023-12-04 22:22:38 +0100] [79] [INFO] Starting gunicorn 21.2.0

[2023-12-04 22:22:38 +0100] [79] [INFO] Listening at: http://[::]:8000 (79)

[2023-12-04 22:22:38 +0100] [79] [INFO] Using worker: paperless.workers.ConfigurableWorker

[2023-12-04 22:22:38 +0100] [79] [INFO] Server is ready. Spawning workers

[2023-12-04 22:22:38,507: INFO/MainProcess] beat: Starting...

 

 -------------- celery@ca87a7050b54 v5.3.6 (emerald-rush)

--- ***** ----- 

-- ******* ---- Linux-6.1.0-0.deb11.11-amd64-x86_64-with-glibc2.36 2023-12-04 22:22:38

- *** --- * --- 

- ** ---------- [config]

- ** ---------- .> app:         paperless:0x7ff6ef941bd0

- ** ---------- .> transport:   redis://broker:6379//

- ** ---------- .> results:     

- *** --- * --- .> concurrency: 2 (prefork)

-- ******* ---- .> task events: ON

--- ***** ----- 

 -------------- [queues]

                .> celery           exchange=celery(direct) key=celery

                

[tasks]

  . documents.tasks.bulk_update_documents

  . documents.tasks.consume_file

  . documents.tasks.index_optimize

  . documents.tasks.sanity_check

  . documents.tasks.train_classifier

  . documents.tasks.update_document_archive_file

  . paperless_mail.mail.apply_mail_action

  . paperless_mail.mail.error_callback

  . paperless_mail.tasks.process_mail_accounts

[2023-12-04 22:22:38,701: INFO/MainProcess] Connected to redis://broker:6379//

[2023-12-04 22:22:38,720: INFO/MainProcess] celery@ca87a7050b54 ready.
```

### Browser logs

```bash
terminal
```

### Paperless-ngx version

2.0.1

### Host OS

Proxmox, VM -> Debian -> Docker -> Compose ->     image: ghcr.io/paperless-ngx/paperless-ngx:latest

### Installation method

Docker - official image

**Comment by MightyMirko** [comment]
additional info by running it from the container

```
> docker exec -it casadepapel bash
root@2981ee167c8a:/usr/src/paperless/src#
root@2981ee167c8a:/usr/src/paperless/src#
root@2981ee167c8a:/usr/src/paperless/src# ls -l
total 60
drwxr-xr-x 1 paperless 1000 4096 Nov 29 19:17 docker
drwxr-xr-x 1 paperless 1000 4096 Nov 30 15:41 documents
drwxr-xr-x 1 paperless 1000 4096 Nov 30 15:40 locale
-rwxr-xr-x 1 paperless 1000  253 Nov 30 15:40 manage.py
drwxr-xr-x 1 paperless 1000 4096 Dec  4 21:33 paperless
drwxr-xr-x 1 paperless 1000 4096 Nov 30 15:41 paperless_mail
drwxr-xr-x 1 paperless 1000 4096 Nov 30 15:41 paperless_tesseract
drwxr-xr-x 1 paperless 1000 4096 Nov 30 15:41 paperless_text
drwxr-xr-x 2 paperless 1000 4096 Nov 30 15:40 paperless_tika
-rw-r--r-- 1 paperless 1000 4956 Nov 29 19:17 requirements.txt
-rw-r--r-- 1 paperless 1000  801 Nov 30 15:40 setup.cfg
root@2981ee167c8a:/usr/src/paperless/src# ./manage.py document_renamer
Attempting automatic installation of LDAP module...
Collecting django_python3_ldap
  Obtaining dependency information for django_python3_ldap from https://files.pythonhosted.org/packages/60/1d/931c3da92f35a092499779c64039fda47e03ea4b32a9abb86a286f4b828b/django_python3_ldap-0.15.5-py3-none-any.whl.metadata
  Downloading django_python3_ldap-0.15.5-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: django>=1.11 in /usr/local/lib/python3.11/site-packages (from django_python3_ldap) (4.2.7)
Collecting ldap3<3,>=2.5 (from django_python3_ldap)
  Downloading ldap3-2.9.1-py2.py3-none-any.whl (432 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 432.2/432.2 kB 3.9 MB/s eta 0:00:00
Collecting pyasn1<0.5,>=0.4.6 (from django_python3_ldap)
  Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.1/77.1 kB 5.3 MB/s eta 0:00:00
Requirement already satisfied: asgiref<4,>=3.6.0 in /usr/local/lib/python3.11/site-packages (from django>=1.11->django_python3_ldap) (3.7.2)
Requirement already satisfied: sqlparse>=0.3.1 in /usr/local/lib/python3.11/site-packages (from django>=1.11->django_python3_ldap) (0.4.4)
Downloading django_python3_ldap-0.15.5-py3-none-any.whl (18 kB)
Installing collected packages: pyasn1, ldap3, django_python3_ldap
Successfully installed django_python3_ldap-0.15.5 ldap3-2.9.1 pyasn1-0.4.8
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: pip install --upgrade pip
LDAP module was just installed - it will be available from the next Python execution.
Traceback (most recent call last):
  File "/usr/src/paperless/src/./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/paperless/src/documents/management/commands/document_renamer.py", line 19, in handle
    logging.getLogger().handlers[0].level = logging.ERROR
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
root@2981ee167c8a:/usr/src/paperless/src# ls -l

```

**Comment by stumpylog** [comment]
Strange, 4 commands include that same line and none of them fail for me.

I see you are installing some custom packages, namely `django_python3_ldap`.  Can you reproduce the issue without those?

**Comment by stumpylog** [comment]
You are presumably also doing some patching of settings.py to integrate django_python3_ldap, that will need to removed as well.  Or fixed to account for any changes we make.

Doing something custom like this isn't supported.

**Comment by MightyMirko** [comment]
I also assumed it was due to the ldap thing after running the function inside container bash.

Yep now i am able to run that! 

```
> docker exec -it casadepapel document_renamer
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 443/443 [00:04<00:00, 98.20it/s]
~ > 
```
