### ISSUE TITLE
[BUG] Concise description of the issue

### ISSUE THREAD

**Issue by Philippe-M** [paperless-ngx/paperless-ngx#4853]
### Description

Hello everyone, 

When I upload a PDF file that has already been imported into the "consume/" folder (to test duplicate detection), the import doesn't occur because Paperless detects the duplicate, but in the logs, I receive a error.

### Steps to reproduce

Import document in paperless;
copy file in consume directory;

### Webserver logs

```bash
webserver_1  | [2023-12-06 15:14:27,499] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[9f0730ba-3af7-49e5-852b-52c08de6f464] raised unexpected: ConsumerError('Bon_Commande_F00160_H25348_20231005.pdf: Not consuming Bon_Commande_F00160_H25348_20231005.pdf: It is a duplicate of H25348 (#174)')
webserver_1  | Traceback (most recent call last):
webserver_1  |   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
webserver_1  |     R = retval = fun(*args, **kwargs)
webserver_1  |                  ^^^^^^^^^^^^^^^^^^^^
webserver_1  |   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
webserver_1  |     return self.run(*args, **kwargs)
webserver_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
webserver_1  |   File "/usr/src/paperless/src/documents/tasks.py", line 167, in consume_file
webserver_1  |     document = Consumer().try_consume_file(
webserver_1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webserver_1  |   File "/usr/src/paperless/src/documents/consumer.py", line 373, in try_consume_file
webserver_1  |     self.pre_check_duplicate()
webserver_1  |   File "/usr/src/paperless/src/documents/consumer.py", line 155, in pre_check_duplicate
webserver_1  |     self._fail(
webserver_1  |   File "/usr/src/paperless/src/documents/consumer.py", line 115, in _fail
webserver_1  |     raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
```

### Paperless-ngx version

2.1

### Host OS

Fedora 39

### Installation method

Docker - official image

**Comment by shamoon** [comment]
That is expected behavior.
