### ISSUE TITLE
[BUG] Concise description of the issue

### ISSUE THREAD

**Issue by jwilczek** [paperless-ngx/paperless-ngx#4880]
### Description

Upgrading from 1.13 to 2.1 fails with database migration.

```
$ sudo -Hu paperless python3 manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/paperless/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/paperless/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 382, in execute
    settings.INSTALLED_APPS
  File "/opt/paperless/.local/lib/python3.8/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/opt/paperless/.local/lib/python3.8/site-packages/django/conf/__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/paperless/.local/lib/python3.8/site-packages/django/conf/__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/paperless/src/paperless/settings.py", line 85, in <module>
    default: Optional[list[str]] = None,
TypeError: 'type' object is not subscriptable
```

### Steps to reproduce

Upgrade to 2.1 from 1.13.

### Webserver logs

```bash
N/A
```

### Browser logs

```bash
N/A
```

### Paperless-ngx version

1.13, 2.1

### Host OS

Ubuntu 20.04

### Installation method

Bare metal

### Browser

N/A

**Comment by stumpylog** [comment]
Python 3.8 support was dropped, as noted in the breaking changes in the [release](https://github.com/paperless-ngx/paperless-ngx/releases/tag/v2.0.0)
