### ISSUE TITLE
[BUG] Cannot share link to document

### ISSUE THREAD

**Issue by christian-schlichtherle** [paperless-ngx/paperless-ngx#4882]
### Description

When I try to share a link to a document, it's not working as expected. There are two issues:

1) A toolbox appears to indicate that the link was copied to the clipboard ("Kopiert" - German for "copied"). However, the clipboard content has not changed. I tested this with Safari 17.1.2 on macOS Sonoma 14.1.2. Only when I click on the copy icon on the link again it gets copied to the clipboard, so there is a workaround for this issue.
2) When I open a new tab in my browser and paste the link, I get a page displaying only "Server Error (500)" and nothing else. When I check the logs of the container for the webserver, it's showing the following entry:

```
[2023-12-07 16:49:51,953] [ERROR] [django.request] Internal Server Error: /share/3qGdKIQTmHgdo6xc4Ve1yNTpjxl3Guwt2Xw08fVps9RHk3GH4q
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/paperless/src/documents/views.py", line 1259, in get
    return serve_file(
           ^^^^^^^^^^^
  File "/usr/src/paperless/src/documents/views.py", line 1268, in serve_file
    file_handle = doc.archive_file
                  ^^^^^^^^^^^^^^^^
  File "/usr/src/paperless/src/documents/models.py", line 322, in archive_file
    return open(self.archive_path, "rb")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

This is from Paperless-ngx 2.1.0.

### Steps to reproduce

See above

### Webserver logs

```bash
See above.
```

### Browser logs

```bash
None
```

### Paperless-ngx version

2.1.0

### Host OS

Synology DSM 7.2.1-69057 Update 3

### Installation method

Docker - official image

### Browser

Safari 17.1.2

**Comment by stumpylog** [comment]
You'll need to change the slider "share archive version" so it is deselected for the moment.  The frontend maybe can't tell if it has an archive version

**Comment by shamoon** [comment]
I can look at this in a bit. Do we think better to have the frontend disable the option if there is no archive file vs just have the backend serve the original. Both?

**Comment by christian-schlichtherle** [comment]
A bugfix in just one day?! Awesome - thanks!!!
