### ISSUE TITLE
[BUG] Using created: or added: searches in upper green search bar makes bad request and blocks subsequent requests.

### ISSUE THREAD

**Issue by akumiszcza** [paperless-ngx/paperless-ngx#4894]
### Description

If you search for created:20231206 in green search bar, the search is changed to created:2023
<img width="298" alt="image" src="https://github.com/paperless-ngx/paperless-ngx/assets/52917795/3ca624db-9bb7-46ce-8576-ac54cfc80686">

What's more, next searches in the green bar does not work at all, until reloading the webpage completely. The same applies to added: search.

### Steps to reproduce

1. Make a search in upper green search bar for tag:inbox,
2. You can see the search is made and works.
 
<img width="284" alt="image" src="https://github.com/paperless-ngx/paperless-ngx/assets/52917795/a5dc350d-72ec-44ba-849e-af01b2912046">

3. Make a search in upper green search bar for added:20231206
4. The search is changed to added:2023
 
<img width="286" alt="image" src="https://github.com/paperless-ngx/paperless-ngx/assets/52917795/46b92c3d-2b11-43ac-b23e-1f40857f3b42">

5. Make the same search as in point 1.
6. The search doesn't work at all.
<img width="266" alt="image" src="https://github.com/paperless-ngx/paperless-ngx/assets/52917795/8696bf65-b9fd-402e-affc-bb660752b270">

### Webserver logs

```bash
not checked
```

### Paperless-ngx version

2.1.1

### Host OS

Unraid 6.12.6 (Linux)

### Installation method

Docker - official image

### Browser

Brave (Chrome)

**Comment by shamoon** [comment]
Sounds like a frontend thing, at least partly. I can look at it in a bit

**Comment by akumiszcza** [comment]
> Logs please.

The 3rd step in "Steps to reproduce" gives the following error in console logs:
[2023-12-08 17:13:20,196] [ERROR] [django.request] Internal Server Error: /api/search/autocomplete/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 284, in _get_response_async
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/renderers.py", line 99, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/utils/encoders.py", line 50, in default
    return obj.decode()
           ^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 6: invalid start byte

**Comment by shamoon** [comment]
I need to track this down some more but that does seem to be the crux of it, when using the search field it'll start trying to auto-complete search and eventually hit http://localhost:8000/api/search/autocomplete/?term=created:2023 which breaks things as above, I assume its just in parsing that last part. I can dig in more later

**Comment by shamoon** [comment]
Ps. I'll open a PR with the above, we can move the discussion regarding a fix to there.

**Comment by akumiszcza** [comment]
Thanks. All the problems I wrote here are fixed now in 2.1.2. Thank you!
<img width="271" alt="image" src="https://github.com/paperless-ngx/paperless-ngx/assets/52917795/23dbf165-d785-4a46-a6c2-38b88ce80bc2">
