### ISSUE TITLE
[BUG] Import of very old paperless export doesn't run

### ISSUE THREAD

**Issue by nosebeggar** [paperless-ngx/paperless-ngx#4952]
### Description

I realize this is an edgecase but you might want to fix this anyway. I had a very old paperless-ngx instance I was running on a machine (1.14.5) that I needed to update. I simply ran the document exporter, deleted all old files and downloaded the newest version. Now the import is throwing errors, as seen below.

### Steps to reproduce

1. Run export on old 1.14.5 version
2. Import in 2.1.1

### Webserver logs

```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
Version mismatch: Currently 2.1.1, importing 1.14.5. Continuing, but import may fail.
Checking the manifest
Database import failed
Version mismatch: Currently 2.1.1, importing 1.14.5
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "auth_user_username_key"
DETAIL:  Key (username)=(AnonymousUser) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/paperless/src/documents/management/commands/document_importer.py", line 175, in handle
    raise e
  File "/usr/src/paperless/src/documents/management/commands/document_importer.py", line 161, in handle
    call_command("loaddata", manifest_path)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 194, in call_command
    return command.execute(*args, **defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/loaddata.py", line 102, in handle
    self.loaddata(fixture_labels)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/loaddata.py", line 163, in loaddata
    self.load_label(fixture_label)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/loaddata.py", line 253, in load_label
    if self.save_obj(obj):
       ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/loaddata.py", line 209, in save_obj
    obj.save(using=self.using)
  File "/usr/local/lib/python3.11/site-packages/django/core/serializers/base.py", line 288, in save
    models.Model.save_base(self.object, using=using, raw=True, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: Problem installing fixture '/usr/src/paperless/export/manifest.json': Could not load auth.User(pk=3): duplicate key value violates unique constraint "auth_user_username_key"
DETAIL:  Key (username)=(AnonymousUser) already exists.
```

### Paperless-ngx version

2.1.1

### Host OS

Ubuntu Server 22.04

### Installation method

Docker - official image

**Comment by smseidl** [comment]
The Document Exporter/Imported is documented to only work (or work best) when importing documents into the same version from which they were exported.  (See note here: https://docs.paperless-ngx.com/administration/#importer)

The upgrades, especially with Docker, are in place upgrades with all the documents in place.  The recommended upgrade process as I see it is:

1. Run document exported to ensure you have a backup.
2. Update docker compose file to new version (if not using `latest` tag)
3. Run docker pull & then docker compose up -d
4. The start will do all the needed to upgrade the DB/etc. to the newest version and all documents are still present.

For your current case, you would need to reinstall tags 1.14.5, then import your documents, then do the upgrade.  If you'd have any problems, you need to go back to a 1.14.5 version and start over.

Hope this helps.

**Comment by stumpylog** [comment]
I couldn't have put it better myself.

**Comment by nosebeggar** [comment]
Hi, sorry to other you guys again, but i have now reopened the issue because I am running a clean 1.14.5 now and I still cannot import, the issue seems the same:

https://pastebin.com/crf5WfwG

**Comment by bogdal** [comment]
@nosebeggar Try to remove `AnonymousUser` and `consumer` users (entire json blocks) from your `manifest.json`:
![2023-12-13 at 13 02](https://github.com/paperless-ngx/paperless-ngx/assets/1451824/19e9c9ce-24ce-445e-9abc-9049c3334ad3)

**Comment by nosebeggar** [comment]
> @nosebeggar Try to remove `AnonymousUser` and `consumer` users (entire json blocks) from your `manifest.json`: ![2023-12-13 at 13 02](https://private-user-images.githubusercontent.com/1451824/290183002-19e9c9ce-24ce-445e-9abc-9049c3334ad3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NzEzOTUsIm5iZiI6MTcwMjQ3MTA5NSwicGF0aCI6Ii8xNDUxODI0LzI5MDE4MzAwMi0xOWU5YzljZS0yNGNlLTQ0NWUtOWFiYy05MDQ5YzMzMzRhZDMuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTNUMTIzODE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzFiMzFlNzUyNDg1NjZiMzQwMTRkYzkzMWY1OTEyZWQyZjQ4NzY2YTU1NTBhNmM5ZDA1NTFhZmE1ODA4OGMyOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UR8TPQfTwH5sDzd3nv5eUeF2_wDqpfAaOCywuIanT0U)

Actually I did, but then I get assignment errors for tags. I assumed "pk": 3 would be the assignment for the user of id 3 so i changed that using sed but no dice

**Comment by bogdal** [comment]
The `AnonymousUser` pk from your `manifest.json` should match the `AnonymousUser` user id from your database. Looks like this user in your DB has different id than 3.

If you have `consumer` user in the `manifest.json` as well, change it's id in the file correspondly.

**Comment by stumpylog** [comment]
In 1.15, this was changed to no longer export those users, both of which are created by migrations.  

What tag related errors did you get with the AnonymousUser removed?  It may require changing some tag information, though I'm not sure why exactly.

**Comment by nosebeggar** [comment]
> In 1.15, this was changed to no longer export those users, both of which are created by migrations.
> 
> What tag related errors did you get with the AnonymousUser removed? It may require changing some tag information, though I'm not sure why exactly.

Thanks, I ended up removing all 3 users from the file, since the admin already exists, then the import ran on 1.14.5. I then changed back to latest, which migrated everything nicely, I then ran an export, removed all previous data and exchanged for a newer compose file that contains current psql and redis containers (migration didn't work otherwise) and imported from my 2.1.2 export.
