### ISSUE TITLE
[BUG] Concise description of the issue

### ISSUE THREAD

**Issue by DawidPietrykowski** [paperless-ngx/paperless-ngx#4968]
### Description

I tried to upload a document which has one page with text (actual text not raster) and also a digital signature, after uploading i received an error in the console: 
```
dokument_514b8cac779e84ebd411cdd66a7c60d7.pdf: Error occurred while consuming document dokument_514b8cac779e84ebd411cdd66a7c60d7.pdf: DigitalSignatureError: Input PDF has a digital signature. OCR would alter the document,
invalidating the signature.
```

From what I gathered, Paperless still keeps a separate version of the file with no alterations so I don't see how that's an issue.
However the error is coming from ocrmypdf so it seems probable that something has changed and now this case has to be handled.

Also, the default option is passed (skip) and the pdf already has text on that page so I wonder if that's a bug on ocrmypdf side since the file would not be altered anyway.

I have found the probable cause of this error, it is indeed a change in ocrmypdf version v14.4.0:
![image](https://github.com/paperless-ngx/paperless-ngx/assets/53954695/469725f6-ec51-4989-b0f0-a816b0dbb00a)

Seems like a simple fix, just add this flag to the arguments of ocrmypdf:
![image](https://github.com/paperless-ngx/paperless-ngx/assets/53954695/72bab8bb-f0fb-465e-9552-2685f1fb52ea)

I can make a PR with this change, but I would like someone to confirm that this case is covered by keeping the original file.

### Steps to reproduce

1. Upload file containing a digital signature

### Webserver logs

```bash
paperless-webserver-1  |   warnings.warn(
paperless-webserver-1  | [2023-12-13 15:33:02,709] [INFO] [celery.worker.strategy] Task documents.tasks.consume_file[74e95df7-8913-4ea7-8dbf-8a7ee17b776a] received
paperless-webserver-1  | [2023-12-13 15:33:02,794] [INFO] [paperless.consumer] Consuming dokument_514b8cac779e84ebd411cdd66a7c60d7.pdf
paperless-webserver-1  | [2023-12-13 15:33:02,961] [WARNING] [paperless.parsing.tesseract] Encountered an error while running OCR: Input PDF has a digital signature. OCR would alter the document,
paperless-webserver-1  | invalidating the signature.
paperless-webserver-1  | . Attempting force OCR to get the text.
paperless-webserver-1  | [2023-12-13 15:33:03,032] [ERROR] [paperless.consumer] Error occurred while consuming document dokument_514b8cac779e84ebd411cdd66a7c60d7.pdf: DigitalSignatureError: Input PDF has a digital signature. OCR would alter the document,
paperless-webserver-1  | invalidating the signature.
paperless-webserver-1  | Traceback (most recent call last):
paperless-webserver-1  |   File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 330, in parse
paperless-webserver-1  |     ocrmypdf.ocr(**args)
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/ocrmypdf/api.py", line 375, in ocr
paperless-webserver-1  |     return run_pipeline(options=options, plugin_manager=plugin_manager)
paperless-webserver-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 225, in run_pipeline
paperless-webserver-1  |     return _run_pipeline(options, plugin_manager)
paperless-webserver-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 189, in _run_pipeline
paperless-webserver-1  |     validate_pdfinfo_options(context)
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipeline.py", line 202, in validate_pdfinfo_options
paperless-webserver-1  |     raise DigitalSignatureError()
paperless-webserver-1  | ocrmypdf.exceptions.DigitalSignatureError: Input PDF has a digital signature. OCR would alter the document,
paperless-webserver-1  | invalidating the signature.
paperless-webserver-1  |
paperless-webserver-1  |
paperless-webserver-1  | During handling of the above exception, another exception occurred:
paperless-webserver-1  |
paperless-webserver-1  | Traceback (most recent call last):
paperless-webserver-1  |   File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 381, in parse
paperless-webserver-1  |     ocrmypdf.ocr(**args)
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/ocrmypdf/api.py", line 375, in ocr
paperless-webserver-1  |     return run_pipeline(options=options, plugin_manager=plugin_manager)
paperless-webserver-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 225, in run_pipeline
paperless-webserver-1  |     return _run_pipeline(options, plugin_manager)
paperless-webserver-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 189, in _run_pipeline
paperless-webserver-1  |     validate_pdfinfo_options(context)
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipeline.py", line 202, in validate_pdfinfo_options
paperless-webserver-1  |     raise DigitalSignatureError()
paperless-webserver-1  | ocrmypdf.exceptions.DigitalSignatureError: Input PDF has a digital signature. OCR would alter the document,
paperless-webserver-1  | invalidating the signature.
paperless-webserver-1  |
paperless-webserver-1  |
paperless-webserver-1  | The above exception was the direct cause of the following exception:
paperless-webserver-1  |
paperless-webserver-1  | Traceback (most recent call last):
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 349, in main_wrap
paperless-webserver-1  |     raise exc_info[1]
paperless-webserver-1  |   File "/usr/src/paperless/src/documents/consumer.py", line 446, in try_consume_file
paperless-webserver-1  |     document_parser.parse(self.path, mime_type, self.filename)
paperless-webserver-1  |   File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 393, in parse
paperless-webserver-1  |     raise ParseError(f"{e.__class__.__name__}: {e!s}") from e
paperless-webserver-1  | documents.parsers.ParseError: DigitalSignatureError: Input PDF has a digital signature. OCR would alter the document,
paperless-webserver-1  | invalidating the signature.
paperless-webserver-1  |
paperless-webserver-1  | [2023-12-13 15:33:03,088] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[74e95df7-8913-4ea7-8dbf-8a7ee17b776a] raised unexpected: ConsumerError('dokument_514b8cac779e84ebd411cdd66a7c60d7.pdf: Error occurred while consuming docume
paperless-webserver-1  | Traceback (most recent call last):
paperless-webserver-1  |   File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 330, in parse
paperless-webserver-1  |     ocrmypdf.ocr(**args)
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/ocrmypdf/api.py", line 375, in ocr
paperless-webserver-1  |     return run_pipeline(options=options, plugin_manager=plugin_manager)
paperless-webserver-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 225, in run_pipeline
paperless-webserver-1  |     return _run_pipeline(options, plugin_manager)
paperless-webserver-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 189, in _run_pipeline
paperless-webserver-1  |     validate_pdfinfo_options(context)
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipeline.py", line 202, in validate_pdfinfo_options
paperless-webserver-1  |     raise DigitalSignatureError()
paperless-webserver-1  | ocrmypdf.exceptions.DigitalSignatureError: Input PDF has a digital signature. OCR would alter the document,
paperless-webserver-1  | invalidating the signature.
paperless-webserver-1  |
paperless-webserver-1  |
paperless-webserver-1  | During handling of the above exception, another exception occurred:
paperless-webserver-1  |
paperless-webserver-1  | Traceback (most recent call last):
paperless-webserver-1  |   File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 381, in parse
paperless-webserver-1  |     ocrmypdf.ocr(**args)
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/ocrmypdf/api.py", line 375, in ocr
paperless-webserver-1  |     return run_pipeline(options=options, plugin_manager=plugin_manager)
paperless-webserver-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 225, in run_pipeline
paperless-webserver-1  |     return _run_pipeline(options, plugin_manager)
paperless-webserver-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 189, in _run_pipeline
paperless-webserver-1  |     validate_pdfinfo_options(context)
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipeline.py", line 202, in validate_pdfinfo_options
paperless-webserver-1  |     raise DigitalSignatureError()
paperless-webserver-1  | ocrmypdf.exceptions.DigitalSignatureError: Input PDF has a digital signature. OCR would alter the document,
paperless-webserver-1  | invalidating the signature.
paperless-webserver-1  |
paperless-webserver-1  |
paperless-webserver-1  | The above exception was the direct cause of the following exception:
paperless-webserver-1  |
paperless-webserver-1  | Traceback (most recent call last):
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 349, in main_wrap
paperless-webserver-1  |     raise exc_info[1]
paperless-webserver-1  |   File "/usr/src/paperless/src/documents/consumer.py", line 446, in try_consume_file
paperless-webserver-1  |     document_parser.parse(self.path, mime_type, self.filename)
paperless-webserver-1  |   File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 393, in parse
paperless-webserver-1  |     raise ParseError(f"{e.__class__.__name__}: {e!s}") from e
paperless-webserver-1  | documents.parsers.ParseError: DigitalSignatureError: Input PDF has a digital signature. OCR would alter the document,
paperless-webserver-1  | invalidating the signature.
paperless-webserver-1  |
paperless-webserver-1  |
paperless-webserver-1  | The above exception was the direct cause of the following exception:
paperless-webserver-1  |
paperless-webserver-1  | Traceback (most recent call last):
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
paperless-webserver-1  |     R = retval = fun(*args, **kwargs)
paperless-webserver-1  |                  ^^^^^^^^^^^^^^^^^^^^
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
paperless-webserver-1  |     return self.run(*args, **kwargs)
paperless-webserver-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-webserver-1  |   File "/usr/src/paperless/src/documents/tasks.py", line 167, in consume_file
paperless-webserver-1  |     document = Consumer().try_consume_file(
paperless-webserver-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-webserver-1  |   File "/usr/src/paperless/src/documents/consumer.py", line 474, in try_consume_file
paperless-webserver-1  |     self._fail(
paperless-webserver-1  |   File "/usr/src/paperless/src/documents/consumer.py", line 115, in _fail
paperless-webserver-1  |     raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
paperless-webserver-1  | documents.consumer.ConsumerError: dokument_514b8cac779e84ebd411cdd66a7c60d7.pdf: Error occurred while consuming document dokument_514b8cac779e84ebd411cdd66a7c60d7.pdf: DigitalSignatureError: Input PDF has a digital signature. OCR would alter the document,
paperless-webserver-1  | invalidating the signature.
```

### Paperless-ngx version

2.1.2

### Host OS

Archlinux

### Installation method

Docker - official image

### Browser

Firefox

### Configuration changes

PAPERLESS_OCR_LANGUAGE=pol, PAPERLESS_OCR_LANGUAGES=pol, PAPERLESS_OCR_USER_ARGS: '{"continue_on_soft_render_error": true}'

**Comment by shamoon** [comment]
Please search

**Comment by shamoon** [comment]
https://github.com/paperless-ngx/paperless-ngx/discussions/4705
