### ISSUE TITLE
[BUG] Unsupported mime type message/rfc822

### ISSUE THREAD

**Issue by bplajzer** [paperless-ngx/paperless-ngx#5022]
### Description

Hi,
I found an error while testing your application. After connecting the email and selecting parse .eml I get an error: `[celery.app.trace] Task documents.tasks.consume_file[f1e(...)c49b] raised unexpected: ConsumerError('email title .eml: Unsupported mime type message/rfc822')`. How can I fix it?

Thank you for your great work and this wonderful project!

![obraz](https://github.com/paperless-ngx/paperless-ngx/assets/9624712/542b41b3-00ae-4cdf-b2b8-ae5862e9d137)
![obraz](https://github.com/paperless-ngx/paperless-ngx/assets/9624712/27c91ff5-7a63-44d5-9cd1-62c1834ce0ca)
![obraz](https://github.com/paperless-ngx/paperless-ngx/assets/9624712/2fca3953-1863-4af4-a71c-05431f652d79)
[docker-compose.txt](https://github.com/paperless-ngx/paperless-ngx/files/13697305/docker-compose.txt)

### Steps to reproduce

1. Connect email account to instance.
2. Select index all INBOX with .eml content
3. Wait till indexing start

### Webserver logs

```bash
2023-12-17 18:54:50 During handling of the above exception, another exception occurred:
2023-12-17 18:54:50 
2023-12-17 18:54:50 Traceback (most recent call last):
2023-12-17 18:54:50   File "/usr/local/lib/python3.11/site-packages/django_celery_results/backends/database.py", line 292, in trigger_callback
2023-12-17 18:54:50     ret = j(timeout=app.conf.result_chord_join_timeout, propagate=True)
2023-12-17 18:54:50           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-17 18:54:50   File "/usr/local/lib/python3.11/site-packages/celery/result.py", line 775, in join
2023-12-17 18:54:50     value = result.get(
2023-12-17 18:54:50             ^^^^^^^^^^^
2023-12-17 18:54:50   File "/usr/local/lib/python3.11/site-packages/celery/result.py", line 247, in get
2023-12-17 18:54:50     self.maybe_throw(callback=callback)
2023-12-17 18:54:50   File "/usr/local/lib/python3.11/site-packages/celery/result.py", line 365, in maybe_throw
2023-12-17 18:54:50     self.throw(value, self._to_remote_traceback(tb))
2023-12-17 18:54:50   File "/usr/local/lib/python3.11/site-packages/celery/result.py", line 358, in throw
2023-12-17 18:54:50     self.on_ready.throw(*args, **kwargs)
2023-12-17 18:54:50   File "/usr/local/lib/python3.11/site-packages/vine/promises.py", line 235, in throw
2023-12-17 18:54:50     reraise(type(exc), exc, tb)
2023-12-17 18:54:50   File "/usr/local/lib/python3.11/site-packages/vine/utils.py", line 27, in reraise
2023-12-17 18:54:50     raise value
2023-12-17 18:54:50 documents.consumer.ConsumerError: {EMAIL_TITLE} .eml: Unsupported mime type message/rfc822
2023-12-17 18:54:50 [2023-12-17 18:54:50,627] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[f1e43545-3831-4657-bf2c-484b1e47c49b] raised unexpected: ConsumerError('{EMAIL_TITLE} .eml: Unsupported mime type message/rfc822')
2023-12-17 18:54:50 Traceback (most recent call last):
2023-12-17 18:54:50   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
2023-12-17 18:54:50     R = retval = fun(*args, **kwargs)
2023-12-17 18:54:50                  ^^^^^^^^^^^^^^^^^^^^
2023-12-17 18:54:50   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
2023-12-17 18:54:50     return self.run(*args, **kwargs)
2023-12-17 18:54:50            ^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-17 18:54:50   File "/usr/src/paperless/src/documents/tasks.py", line 167, in consume_file
2023-12-17 18:54:50     document = Consumer().try_consume_file(
2023-12-17 18:54:50                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-17 18:54:50   File "/usr/src/paperless/src/documents/consumer.py", line 399, in try_consume_file
2023-12-17 18:54:50     self._fail(
2023-12-17 18:54:50   File "/usr/src/paperless/src/documents/consumer.py", line 115, in _fail
2023-12-17 18:54:50     raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
2023-12-17 18:54:50 documents.consumer.ConsumerError: {EMAIL_TITLE} .eml: Unsupported mime type message/rfc822
2023-12-17 18:54:55 [2023-12-17 18:54:55,203] [INFO] [celery.worker.strategy] Task documents.tasks.consume_file[05c50b34-e046-4066-b9b7-8dc96e17ee24] received
2023-12-17 18:54:55 [2023-12-17 18:54:55,218] [INFO] [paperless.consumer] Consuming {EMAIL_TITLE}.eml
2023-12-17 18:54:55 [2023-12-17 18:54:55,227] [ERROR] [paperless.consumer] Unsupported mime type message/rfc822
2023-12-17 18:54:55 [2023-12-17 18:54:55,235] [ERROR] [django_celery_results.backends.database] Chord '005d3d9c-f46a-486b-b7e0-d1a35181b87f' raised: ConsumerError('{EMAIL_TITLE}.eml: Unsupported mime type message/rfc822')
```

### Paperless-ngx version

v2.1.3 aka latest

### Host OS

Macos arm

### Installation method

Docker - official image

### Configuration changes

Added PAPERLESS_ADMIN_USER, PAPERLESS_ADMIN_PASSWORD

**Comment by shamoon** [comment]
Please search before opening a bug report, as is required in the template

- https://github.com/paperless-ngx/paperless-ngx/discussions/2538
- https://github.com/paperless-ngx/paperless-ngx/discussions/2587
- https://github.com/paperless-ngx/paperless-ngx/discussions/4424
- https://github.com/paperless-ngx/paperless-ngx/discussions/3050
- https://github.com/paperless-ngx/paperless-ngx/issues/2315

**Comment by bplajzer** [comment]
@shamoon thank you so much for pointing out the right topics - have a nice day :)
