### ISSUE TITLE
[BUG] PDF consumtion of documents with unusual page format fails

### ISSUE THREAD

**Issue by Conspir3D** [paperless-ngx/paperless-ngx#5132]
### Description

Upload the PDF and consumption faild with error.

I'm not sure if i can upload the PDF here as it contains some legal rights. I can send it  by mail cause i don't want to risk a copyright issue here!

### Steps to reproduce

1. Upload the PDF
2. wait until consumption failed

### Webserver logs

```bash
Traceback (most recent call last): File "/usr/lo…
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python3.11/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/usr/local/lib/python3.11/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/worker/consumer/consumer.py", line 340, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.11/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/usr/local/lib/python3.11/site-packages/celery/worker/consumer/consumer.py", line 742, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.11/site-packages/celery/worker/loops.py", line 86, in asynloop
    state.maybe_shutdown()
  File "/usr/local/lib/python3.11/site-packages/celery/worker/state.py", line 93, in maybe_shutdown
    raise WorkerShutdown(should_stop)
celery.exceptions.WorkerShutdown: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/billiard/pool.py", line 1264, in mark_as_worker_lost
    raise WorkerLostError(
billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 15 (SIGTERM) Job: 104.
```

### Paperless-ngx version

2.1.3

### Host OS

Docker

### Installation method

Docker - official image

### Browser

Chrome

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
Sigterm means something external has killed the worker.  Likely it's due to memory.  You can check dmesg which might contain more

**Comment by Conspir3D** [comment]
Thank you for this hint ... will investigate further and come back if i got more informations.
