### ISSUE TITLE
[BUG] ValueError: overflow/underflow converting 

### ISSUE THREAD

**Issue by shuther** [paperless-ngx/paperless-ngx#5160]
### Description

I have few pdf that returned an error: ValueError: overflow/underflow converting

### Steps to reproduce

1. Latest version of docker compose/new install
2. Upload .pdf file

Specific env I am using:
```
PAPERLESS_CONSUMER_RECURSIVE=true
PAPERLESS_CONSUMER_DELETE_DUPLICATES=true
PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS=true
PAPERLESS_CONSUMER_INOTIFY_DELAY=10

# https://github.com/paperless-ngx/paperless-ngx/discussions/4047#discussioncomment-7019544
# https://docs.paperless-ngx.com/troubleshooting/
PAPERLESS_OCR_USER_ARGS={"invalidate_digital_signatures": true, "continue_on_soft_render_error": true}

#merge from https://github.com/jonaswinkler/paperless-ng/blob/master/paperless.conf.example
PAPERLESS_CONSUMER_IGNORE_PATTERNS=[".*~", ".directory",".DS_STORE/*", "._*", ".stfolder/*"]

#i.e.
#PAPERLESS_FILENAME_FORMAT={created_year}/{correspondent}/{document_type}_{created_year}{created_month}_{correspondent}_{tag_list}
PAPERLESS_FILENAME_FORMAT={created_year}/{correspondent}/{created_month}_{original_name}
#If we rename, we need to run docker-compose exec webserver document_renamer
PAPERLESS_OCR_COLOR_CONVERSION_STRATEGY=LeaveColorUnchanged

```

### Webserver logs

```bash
File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 349, in main_wrap
    raise exc_info[1]
  File "/usr/src/paperless/src/documents/consumer.py", line 446, in try_consume_file
    document_parser.parse(self.path, mime_type, self.filename)
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 397, in parse
    raise ParseError(f"{e.__class__.__name__}: {e!s}") from e
 -67413490548258257961605456244286751932488567828666626215942277363556312796335701245807746045257510352439446031604288022271066970891889922072678664582536019864975141417378607199211846361157709784043353113990147575952011060054909426185709877131030446268188856225724459951776232684500341238408566850233269485568 to 64-bit integer
[2023-12-29 12:02:47,353] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[8b3040e0-7241-4ffd-b0a3-129e7d09ab21] raised unexpected: ConsumerError('confirmation email 20230406.pdf: Error occurred while consuming document confirmation email 20230406.pdf: ValueError: overflow/underflow converting -67413490548258257961605456244286751932488567828666626215942277363556312796335701245807746045257510352439446031604288022271066970891889922072678664582536019864975141417378607199211846361157709784043353113990147575952011060054909426185709877131030446268188856225724459951776232684500341238408566850233269485568 to 64-bit integer')
Traceback (most recent call last):
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 330, in parse
    ocrmypdf.ocr(**args)
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/api.py", line 375, in ocr
    return run_pipeline(options=options, plugin_manager=plugin_manager)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 225, in run_pipeline
    return _run_pipeline(options, plugin_manager)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 176, in _run_pipeline
    pdfinfo = get_pdfinfo(
              ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipeline.py", line 173, in get_pdfinfo
    return PdfInfo(
           ^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/pdfinfo/info.py", line 1103, in __init__
    self._pages = _pdf_pageinfo_concurrent(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/pdfinfo/info.py", line 778, in _pdf_pageinfo_concurrent
    executor(
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_concurrent.py", line 74, in __call__
    self._execute(
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/builtin_plugins/concurrency.py", line 141, in _execute
    result = future.result()
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/pdfinfo/info.py", line 727, in _pdf_pageinfo_sync
    return PageInfo(pdf, pageno, infile, check_pages, detailed_analysis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/pdfinfo/info.py", line 842, in __init__
    self._gather_pageinfo(pdf, pageno, infile, check_pages, detailed_analysis)
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/pdfinfo/info.py", line 887, in _gather_pageinfo
    for info in _process_content_streams(
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/pdfinfo/info.py", line 631, in _process_content_streams
    contentsinfo = _interpret_contents(container, initial_shorthand)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/pdfinfo/info.py", line 224, in _interpret_contents
    _normalize_stack(parse_content_stream(contentstream, operator_whitelist))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pikepdf/models/_content_stream.py", line 105, in parse_content_stream
    page._parse_page_contents_grouped(operators),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: overflow/underflow converting -67413490548258257961605456244286751932488567828666626215942277363556312796335701245807746045257510352439446031604288022271066970891889922072678664582536019864975141417378607199211846361157709784043353113990147575952011060054909426185709877131030446268188856225724459951776232684500341238408566850233269485568 to 64-bit integer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 349, in main_wrap
    raise exc_info[1]
  File "/usr/src/paperless/src/documents/consumer.py", line 446, in try_consume_file
    document_parser.parse(self.path, mime_type, self.filename)
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 397, in parse
    raise ParseError(f"{e.__class__.__name__}: {e!s}") from e
documents.parsers.ParseError: ValueError: overflow/underflow converting -67413490548258257961605456244286751932488567828666626215942277363556312796335701245807746045257510352439446031604288022271066970891889922072678664582536019864975141417378607199211846361157709784043353113990147575952011060054909426185709877131030446268188856225724459951776232684500341238408566850233269485568 to 64-bit integer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/paperless/src/documents/tasks.py", line 167, in consume_file
    document = Consumer().try_consume_file(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/paperless/src/documents/consumer.py", line 474, in try_consume_file
    self._fail(
  File "/usr/src/paperless/src/documents/consumer.py", line 115, in _fail
    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
documents.consumer.ConsumerError: confirmation email 20230406.pdf: Error occurred while consuming document confirmation email 20230406.pdf: ValueError: overflow/underflow converting -67413490548258257961605456244286751932488567828666626215942277363556312796335701245807746045257510352439446031604288022271066970891889922072678664582536019864975141417378607199211846361157709784043353113990147575952011060054909426185709877131030446268188856225724459951776232684500341238408566850233269485568 to 64-bit integer
[2023-12-29 12:02:47,557] [INFO] [celery.worker.strategy] Task documents.tasks.consume_file[2bd7c463-1b93-41d4-a42e-c804d9a1092d] received
```

### Paperless-ngx version

2.2.0

### Host OS

Ubuntu 20.04

### Installation method

Docker - official image

### Configuration changes

see above

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
It's an issue with your particular PDF file.  You can attempt to repair it with something like qpdf or print to PDF but this isn't a paperless issue.
