### ISSUE TITLE
[BUG] E-Mail attachement will not be imported (file

### ISSUE THREAD

**Issue by dimmenhau** [paperless-ngx/paperless-ngx#5162]
### Description

When I try to import a mail into the system, the error message "file not found" is displayed

i have set in docker-compose.env
`USERMAP_UID=1001
USERMAP_GID=1002`

and her are the Mail Rule:
![Screenshot_20231229_150431](https://github.com/paperless-ngx/paperless-ngx/assets/59511540/f027b51d-9053-4798-9372-efbc19662c0e)

### Steps to reproduce

- add mail into a mail folder
- start mail_fetcher
`root@2c62a88e6f16:/usr/src/paperless/src# python3 manage.py mail_fetcher
[2023-12-29 13:56:11,655] [INFO] [paperless_mail] Rule MS-Exchange.MS-Exchange: Consuming attachment Rechnung 1020627892.PDF from mail Rechnung zu Ihrem Frankonia Auftrag 58532786 from mail@frankonia.de`
 - mail not imported

### Webserver logs

```bash
paperless  | [2023-12-29 13:53:09,884] [INFO] [celery.worker.consumer.connection] Connected to redis://redis:6379//
paperless  | [2023-12-29 13:53:09,898] [INFO] [celery.apps.worker] celery@2c62a88e6f16 ready.
paperless  | [2023-12-29 13:56:11,695] [INFO] [celery.worker.strategy] Task documents.tasks.consume_file[06acac30-613c-43dd-8b89-935937b15a55] received
paperless  | [2023-12-29 13:56:11,738] [WARNING] [paperless.barcodes] File is likely password protected, not checking for barcodes: Unable to get page count.
paperless  | I/O Error: Couldn't open file '/tmp/paperless/paperless-mail-_nohlqap/Rechnung 1020627892.PDF': Permission denied.
paperless  | 
paperless  | [2023-12-29 13:56:11,742] [INFO] [paperless.matching] Document did not match template Arztrechnung
paperless  | [2023-12-29 13:56:11,743] [INFO] [paperless.matching] Document did not match template Überweisungsauftrag
paperless  | [2023-12-29 13:56:11,743] [INFO] [paperless.matching] Document did not match template Rechnung
paperless  | [2023-12-29 13:56:11,743] [INFO] [paperless.matching] Document did not match template Schriftwechsel
paperless  | [2023-12-29 13:56:11,744] [INFO] [paperless.matching] Document did not match template Zahlungserinnerung
paperless  | [2023-12-29 13:56:11,744] [INFO] [paperless.matching] Document did not match template Mahnung
paperless  | [2023-12-29 13:56:11,752] [ERROR] [paperless.consumer] Cannot consume /tmp/paperless/paperless-mail-_nohlqap/Rechnung 1020627892.PDF: File not found.
paperless  | [2023-12-29 13:56:11,762] [ERROR] [django_celery_results.backends.database] Chord '06a50ead-8d09-4624-931e-4c20d3940220' raised: ConsumerError('Rechnung 1020627892.PDF: Cannot consume /tmp/paperless/paperless-mail-_nohlqap/Rechnung 1020627892.PDF: File not found.')
paperless  | Traceback (most recent call last):
paperless  |   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
paperless  |     R = retval = fun(*args, **kwargs)
paperless  |                  ^^^^^^^^^^^^^^^^^^^^
paperless  |   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
paperless  |     return self.run(*args, **kwargs)
paperless  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
paperless  |   File "/usr/src/paperless/src/documents/tasks.py", line 167, in consume_file
paperless  |     document = Consumer().try_consume_file(
paperless  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless  |   File "/usr/src/paperless/src/documents/consumer.py", line 371, in try_consume_file
paperless  |     self.pre_check_file_exists()
paperless  |   File "/usr/src/paperless/src/documents/consumer.py", line 138, in pre_check_file_exists
paperless  |     self._fail(
paperless  |   File "/usr/src/paperless/src/documents/consumer.py", line 115, in _fail
paperless  |     raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
paperless  | documents.consumer.ConsumerError: Rechnung 1020627892.PDF: Cannot consume /tmp/paperless/paperless-mail-_nohlqap/Rechnung 1020627892.PDF: File not found.
paperless  | 
paperless  | During handling of the above exception, another exception occurred:
paperless  | 
paperless  | Traceback (most recent call last):
paperless  |   File "/usr/local/lib/python3.11/site-packages/django_celery_results/backends/database.py", line 292, in trigger_callback
paperless  |     ret = j(timeout=app.conf.result_chord_join_timeout, propagate=True)
paperless  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless  |   File "/usr/local/lib/python3.11/site-packages/celery/result.py", line 775, in join
paperless  |     value = result.get(
paperless  |             ^^^^^^^^^^^
paperless  |   File "/usr/local/lib/python3.11/site-packages/celery/result.py", line 247, in get
paperless  |     self.maybe_throw(callback=callback)
paperless  |   File "/usr/local/lib/python3.11/site-packages/celery/result.py", line 365, in maybe_throw
paperless  |     self.throw(value, self._to_remote_traceback(tb))
paperless  |   File "/usr/local/lib/python3.11/site-packages/celery/result.py", line 358, in throw
paperless  |     self.on_ready.throw(*args, **kwargs)
paperless  |   File "/usr/local/lib/python3.11/site-packages/vine/promises.py", line 235, in throw
paperless  |     reraise(type(exc), exc, tb)
paperless  |   File "/usr/local/lib/python3.11/site-packages/vine/utils.py", line 27, in reraise
paperless  |     raise value
paperless  | documents.consumer.ConsumerError: Rechnung 1020627892.PDF: Cannot consume /tmp/paperless/paperless-mail-_nohlqap/Rechnung 1020627892.PDF: File not found.
paperless  | [2023-12-29 13:56:11,787] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[06acac30-613c-43dd-8b89-935937b15a55] raised unexpected: ConsumerError('Rechnung 1020627892.PDF: Cannot consume /tmp/paperless/paperless-mail-_nohlqap/Rechnung 1020627892.PDF: File not found.')
paperless  | Traceback (most recent call last):
paperless  |   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
paperless  |     R = retval = fun(*args, **kwargs)
paperless  |                  ^^^^^^^^^^^^^^^^^^^^
paperless  |   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
paperless  |     return self.run(*args, **kwargs)
paperless  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
paperless  |   File "/usr/src/paperless/src/documents/tasks.py", line 167, in consume_file
paperless  |     document = Consumer().try_consume_file(
paperless  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless  |   File "/usr/src/paperless/src/documents/consumer.py", line 371, in try_consume_file
paperless  |     self.pre_check_file_exists()
paperless  |   File "/usr/src/paperless/src/documents/consumer.py", line 138, in pre_check_file_exists
paperless  |     self._fail(
paperless  |   File "/usr/src/paperless/src/documents/consumer.py", line 115, in _fail
paperless  |     raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
paperless  | documents.consumer.ConsumerError: Rechnung 1020627892.PDF: Cannot consume /tmp/paperless/paperless-mail-_nohlqap/Rechnung 1020627892.PDF: File not found.
```

### Browser logs

```bash
Log from directory:
`root@2c62a88e6f16:/tmp# ls -l
total 8
drwxr-xr-x 3 paperless paperless 4096 Dec 29 13:56 paperless
drwx------ 2 paperless paperless 4096 Dec 29 13:53 pymp-s9udao8f
root@2c62a88e6f16:/tmp# ls -ltR
.:
total 8
drwxr-xr-x 3 paperless paperless 4096 Dec 29 13:56 paperless
drwx------ 2 paperless paperless 4096 Dec 29 13:53 pymp-s9udao8f

./paperless:
total 4
drwx------ 2 root root 4096 Dec 29 13:56 paperless-mail-_nohlqap

./paperless/paperless-mail-_nohlqap:
total 244
-rw-r--r-- 1 root root 247860 Dec 29 13:56 'Rechnung 1020627892.PDF'`
```

### Paperless-ngx version

2.2.1

### Host OS

Ubuntu 22.04

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
Does the listed path exist?  What are it's permissions if it does?

**Comment by dimmenhau** [comment]
see Browser log

**Comment by stumpylog** [comment]
That does not answer my question

**Comment by dimmenhau** [comment]
yes the path is exist....

the path and the authorizations are listed exactly in the browser log. I have retrieved this information from the Docker container

**Comment by stumpylog** [comment]
I see you are running the mail fetcher as `root`, directly using the `manage.py` file.  That causes the directory to be created as owned by `root` and no permissions for other users.

If you want to do that, you should properly use `gosu paperless <my command>`.  The existing command `mail_fetcher` will already do this for you, that's why it is there.
