### ISSUE TITLE
[BUG] Exception if filter by permissions "Shared by me"

### ISSUE THREAD

**Issue by marvinwankersteen** [paperless-ngx/paperless-ngx#5189]
### Description

Hello,

the error is - at least for me - pretty clear. The `Shared by me` filter does not work and generates an exception. All other filters work as expected.
I thought that it might still be due to the old Postgres 13. But I have also updated Postgres to 15 and the error persists.
I have created four users and shared several documents with one user. This user can also see the documents I have shared.
I can only guess whether the problem only affects me. I have been using Paperless since version 1.13.0 and have updated to all intermediate versions when they were released.

Kind regards

### Steps to reproduce

1. Open `http://paperless/documents`
2. Click `Permissions` --> `Shared by me`
3. Error is printed and logged

### Webserver logs

```bash
db_1         | 2023-12-31 11:14:18.589 UTC [333] ERROR:  operator does not exist: character varying = integer at character 826
db_1         | 2023-12-31 11:14:18.589 UTC [333] HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
db_1         | 2023-12-31 11:14:18.589 UTC [333] STATEMENT:  SELECT DISTINCT "documents_document"."id", "documents_document"."owner_id", "documents_document"."correspondent_id", "documents_document"."storage_path_id", "documents_document"."title", "documents_document"."document_type_id", "documents_document"."content", "documents_document"."mime_type", "documents_document"."checksum", "documents_document"."archive_checksum", "documents_document"."created", "documents_document"."modified", "documents_document"."storage_type", "documents_document"."added", "documents_document"."filename", "documents_document"."archive_filename", "documents_document"."original_filename", "documents_document"."archive_serial_number", COUNT("documents_note"."id") AS "num_notes", COUNT((SELECT U0."user_id" FROM "guardian_userobjectpermission" U0 WHERE (U0."content_type_id" = 6 AND U0."object_pk" = ("documents_document"."id")))) AS "num_shared_users", COUNT((SELECT U0."group_id" FROM "guardian_groupobjectpermission" U0 WHERE (U0."content_type_id" = 6 AND U0."object_pk" = ("documents_document"."id")))) AS "num_shared_groups", "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined", "documents_correspondent"."id", "documents_correspondent"."owner_id", "documents_correspondent"."name", "documents_correspondent"."match", "documents_correspondent"."matching_algorithm", "documents_correspondent"."is_insensitive", "documents_storagepath"."id", "documents_storagepath"."owner_id", "documents_storagepath"."name", "documents_storagepath"."match", "documents_storagepath"."matching_algorithm", "documents_storagepath"."is_insensitive", "documents_storagepath"."path", "documents_documenttype"."id", "documents_documenttype"."owner_id", "documents_documenttype"."name", "documents_documenttype"."match", "documents_documenttype"."matching_algorithm", "documents_documenttype"."is_insensitive" FROM "documents_document" LEFT OUTER JOIN "documents_note" ON ("documents_document"."id" = "documents_note"."document_id") INNER JOIN "auth_user" ON ("documents_document"."owner_id" = "auth_user"."id") LEFT OUTER JOIN "documents_correspondent" ON ("documents_document"."correspondent_id" = "documents_correspondent"."id") LEFT OUTER JOIN "documents_storagepath" ON ("documents_document"."storage_path_id" = "documents_storagepath"."id") LEFT OUTER JOIN "documents_documenttype" ON ("documents_document"."document_type_id" = "documents_documenttype"."id") GROUP BY "documents_document"."id", "auth_user"."id", "documents_correspondent"."id", "documents_storagepath"."id", "documents_documenttype"."id", "documents_document"."owner_id" HAVING (("documents_document"."owner_id" = 2 AND (COUNT((SELECT U0."user_id" FROM "guardian_userobjectpermission" U0 WHERE (U0."content_type_id" = 6 AND U0."object_pk" = ("documents_document"."id")))) > 0 OR COUNT((SELECT U0."group_id" FROM "guardian_groupobjectpermission" U0 WHERE (U0."content_type_id" = 6 AND U0."object_pk" = ("documents_document"."id")))) > 0)) OR ("documents_document"."owner_id" = 2 AND (COUNT((SELECT U0."user_id" FROM "guardian_userobjectpermission" U0 WHERE (U0."content_type_id" = 6 AND U0."object_pk" = ("documents_document"."id")))) > 0 OR COUNT((SELECT U0."group_id" FROM "guardian_groupobjectpermission" U0 WHERE (U0."content_type_id" = 6 AND U0."object_pk" = ("documents_document"."id")))) > 0) AND "documents_document"."owner_id" = 2) OR ("documents_document"."owner_id" = 2 AND (COUNT((SELECT U0."user_id" FROM "guardian_userobjectpermission" U0 WHERE (U0."content_type_id" = 6 AND U0."object_pk" = ("documents_document"."id")))) > 0 OR COUNT((SELECT U0."group_id" FROM "guardian_groupobjectpermission" U0 WHERE (U0."content_type_id" = 6 AND U0."object_pk" = ("documents_document"."id")))) > 0) AND "documents_document"."owner_id" IS NULL)) ORDER BY "documents_document"."created" DESC LIMIT 21
webserver_1  | [2023-12-31 12:14:18,546] [ERROR] [django.request] Internal Server Error: /api/documents/
webserver_1  | Traceback (most recent call last):
webserver_1  |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
webserver_1  |     return self.cursor.execute(sql, params)
webserver_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webserver_1  | psycopg2.errors.UndefinedFunction: operator does not exist: character varying = integer
webserver_1  | LINE 1: ...HERE (U0."content_type_id" = 6 AND U0."object_pk" = ("docume...
webserver_1  |                                                              ^
webserver_1  | HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
webserver_1  | 
webserver_1  | 
webserver_1  | The above exception was the direct cause of the following exception:
webserver_1  | 
webserver_1  | Traceback (most recent call last):
webserver_1  |   File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
webserver_1  |     raise exc_info[1]
webserver_1  |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 42, in inner
webserver_1  |     response = await get_response(request)
webserver_1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
webserver_1  |   File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
webserver_1  |     raise exc_info[1]
webserver_1  |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
webserver_1  |     response = await wrapped_callback(
webserver_1  |                ^^^^^^^^^^^^^^^^^^^^^^^
webserver_1  |   File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 479, in __call__
webserver_1  |     ret: _R = await loop.run_in_executor(
webserver_1  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
webserver_1  |   File "/usr/local/lib/python3.11/site-packages/asgiref/current_thread_executor.py", line 40, in run
webserver_1  |     result = self.fn(*self.args, **self.kwargs)
webserver_1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webserver_1  |   File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 538, in thread_handler
webserver_1  |     return func(*args, **kwargs)
webserver_1  |            ^^^^^^^^^^^^^^^^^^^^^
webserver_1  |   File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
webserver_1  |     return view_func(*args, **kwargs)
webserver_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
webserver_1  |   File "/usr/local/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
webserver_1  |     return self.dispatch(request, *args, **kwargs)
webserver_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webserver_1  |   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
webserver_1  |     response = self.handle_exception(exc)
webserver_1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
webserver_1  |   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
webserver_1  |     self.raise_uncaught_exception(exc)
webserver_1  |   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
webserver_1  |     raise exc
webserver_1  |   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
webserver_1  |     response = handler(request, *args, **kwargs)
webserver_1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webserver_1  |   File "/usr/src/paperless/src/documents/views.py", line 726, in list
webserver_1  |     return super().list(request)
webserver_1  |            ^^^^^^^^^^^^^^^^^^^^^
webserver_1  |   File "/usr/local/lib/python3.11/site-packages/rest_framework/mixins.py", line 40, in list
webserver_1  |     page = self.paginate_queryset(queryset)
webserver_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webserver_1  |   File "/usr/local/lib/python3.11/site-packages/rest_framework/generics.py", line 171, in paginate_queryset
webserver_1  |     return self.paginator.paginate_queryset(queryset, self.request, view=self)
webserver_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webserver_1  |   File "/usr/local/lib/python3.11/site-packages/rest_framework/pagination.py", line 204, in paginate_queryset
webserver_1  |     self.page = paginator.page(page_number)
webserver_1  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
webserver_1  |   File "/usr/local/lib/python3.11/site-packages/django/core/paginator.py", line 72, in page
webserver_1  |     number = self.validate_number(number)
webserver_1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webserver_1  |   File "/usr/local/lib/python3.11/site-packages/django/core/paginator.py", line 53, in validate_number
webserver_1  |     if number > self.num_pages:
webserver_1  |                 ^^^^^^^^^^^^^^
webserver_1  |   File "/usr/local/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
webserver_1  |     res = instance.__dict__[self.name] = self.func(instance)
webserver_1  |                                          ^^^^^^^^^^^^^^^^^^^
webserver_1  |   File "/usr/local/lib/python3.11/site-packages/django/core/paginator.py", line 99, in num_pages
webserver_1  |     if self.count == 0 and not self.allow_empty_first_page:
webserver_1  |        ^^^^^^^^^^
webserver_1  |   File "/usr/local/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
webserver_1  |     res = instance.__dict__[self.name] = self.func(instance)
webserver_1  |                                          ^^^^^^^^^^^^^^^^^^^
webserver_1  |   File "/usr/local/lib/python3.11/site-packages/django/core/paginator.py", line 93, in count
webserver_1  |     return c()
webserver_1  |            ^^^
webserver_1  |   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 608, in count
webserver_1  |     return self.query.get_count(using=self.db)
webserver_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webserver_1  |   File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/query.py", line 568, in get_count
webserver_1  |     return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
webserver_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webserver_1  |   File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/query.py", line 554, in get_aggregation
webserver_1  |     result = compiler.execute_sql(SINGLE)
webserver_1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webserver_1  |   File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
webserver_1  |     cursor.execute(sql, params)
webserver_1  |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
webserver_1  |     return self._execute_with_wrappers(
webserver_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webserver_1  |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
webserver_1  |     return executor(sql, params, many, context)
webserver_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webserver_1  |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
webserver_1  |     with self.db.wrap_database_errors:
webserver_1  |   File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
webserver_1  |     raise dj_exc_value.with_traceback(traceback) from exc_value
webserver_1  |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
webserver_1  |     return self.cursor.execute(sql, params)
webserver_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webserver_1  | django.db.utils.ProgrammingError: operator does not exist: character varying = integer
webserver_1  | LINE 1: ...HERE (U0."content_type_id" = 6 AND U0."object_pk" = ("docume...
webserver_1  |                                                              ^
webserver_1  | HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
```

### Browser logs

```bash
Error while loading documents: <!doctype html> <html lang="en"> <head> <title>Server Error (500)</title> </head> <body> <h1>Server Error (500)</h1><p></p> </body> </html>
```

### Paperless-ngx version

2.2.1

### Host OS

Debian 12, x86_64

### Installation method

Docker - official image

### Browser

Firefox, Chrome

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
#5152
