### ISSUE TITLE
[BUG] DigitalSignatureError leads to data loss, since the file will not be stored at all.

### ISSUE THREAD

**Issue by tmaier** [paperless-ngx/paperless-ngx#5215]
### Description

Given I have an invoice from AWS and want to store it in Paperless-ngx
I import it into Paperless, the processing starts and fails with a `DigitalSignatureError ` error.

The file is discarded entirely. Not stored in Paperless-ngx.
The error message in the log is also not clear about it, that this is going to happen.

Note: The author is aware of #4705

Expected behaviour:

- When there is a signature in a PDF file, skip the OCR step. Do not try to alter/OCR the PDF. Just import it.
- Provide a clear message in the logs, that the file will not be stored in Paperless to warn about the risk of data loss.
  Compare this to the red message for duplicate files: `[ERROR] [paperless.consumer] Not consuming 2023-11-30 4865395855.pdf: It is a duplicate of 2023-11-30 4865395855 (#192)`
- The exception itself should be handled more gracefully. Digitally signed files are to be expected.

### Steps to reproduce

1. Upload a digitally signed file
2. Watch the inbox and realize it never appears there
3. Check the log and notice the exception

### Webserver logs

```log
[2024-01-03 02:25:47,486] [DEBUG] [paperless.consumer] Parsing 2023-03-02 EUINDE23-415949.pdf...
[2024-01-03 02:25:47,733] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-ngxk05kne_6/2023-03-02 EUINDE23-415949.pdf'), 'output_file': PosixPath('/tmp/paperless/paperless-cs6wwudl/archive.pdf'), 'use_threads': True, 'jobs': 4, 'language': 'deu', 'output_type': 'pdfa', 'progress_bar': False, 'color_conversion_strategy': 'RGB', 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-cs6wwudl/sidecar.txt')}
[2024-01-03 02:25:48,293] [WARNING] [paperless.parsing.tesseract] Encountered an error while running OCR: Input PDF has a digital signature. OCR would alter the document,
invalidating the signature.
. Attempting force OCR to get the text.
[2024-01-03 02:25:48,294] [DEBUG] [paperless.parsing.tesseract] Fallback: Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-ngxk05kne_6/2023-03-02 EUINDE23-415949.pdf'), 'output_file': PosixPath('/tmp/paperless/paperless-cs6wwudl/archive-fallback.pdf'), 'use_threads': True, 'jobs': 4, 'language': 'deu', 'output_type': 'pdfa', 'progress_bar': False, 'color_conversion_strategy': 'RGB', 'force_ocr': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-cs6wwudl/sidecar-fallback.txt')}
[2024-01-03 02:25:48,661] [ERROR] [paperless.consumer] Error occurred while consuming document 2023-03-02 EUINDE23-415949.pdf: DigitalSignatureError: Input PDF has a digital signature. OCR would alter the document,
invalidating the signature.
Traceback (most recent call last):
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 330, in parse
    ocrmypdf.ocr(**args)
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/api.py", line 375, in ocr
    return run_pipeline(options=options, plugin_manager=plugin_manager)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 225, in run_pipeline
    return _run_pipeline(options, plugin_manager)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 189, in _run_pipeline
    validate_pdfinfo_options(context)
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipeline.py", line 202, in validate_pdfinfo_options
    raise DigitalSignatureError()
ocrmypdf.exceptions.DigitalSignatureError: Input PDF has a digital signature. OCR would alter the document,
invalidating the signature.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 381, in parse
    ocrmypdf.ocr(**args)
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/api.py", line 375, in ocr
    return run_pipeline(options=options, plugin_manager=plugin_manager)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 225, in run_pipeline
    return _run_pipeline(options, plugin_manager)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 189, in _run_pipeline
    validate_pdfinfo_options(context)
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipeline.py", line 202, in validate_pdfinfo_options
    raise DigitalSignatureError()
ocrmypdf.exceptions.DigitalSignatureError: Input PDF has a digital signature. OCR would alter the document,
invalidating the signature.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 349, in main_wrap
    raise exc_info[1]
  File "/usr/src/paperless/src/documents/consumer.py", line 446, in try_consume_file
    document_parser.parse(self.path, mime_type, self.filename)
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 393, in parse
    raise ParseError(f"{e.__class__.__name__}: {e!s}") from e
documents.parsers.ParseError: DigitalSignatureError: Input PDF has a digital signature. OCR would alter the document,
invalidating the signature.
```

### Paperless-ngx version

2.2.1

### Host OS

synology

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
It's always been up to the user to know if they need or want to invalidate signatures.  That's not a bug.  If you'd like to make a feature request or find and vote on an existing one to either improve the message or something.

**Comment by tmaier** [comment]
So it invalidates the signature only for the archive version (PDF/A) it generates, not for the original document. I can live with that.

However, not being clear on what is happening is not a feature, but a bug. Especially when it is about data loss.

**Comment by tzepter** [comment]
I'm sorry, but I don't understand your way of thinking here. It is both important: (a) to take the document under management and (b) to do OCR on it. Both are possible if you do the OCR on the archive copy and leave the original untouched. Since more and more signed documents are on the way (- this is being pushed for invoices -), I believe that it devalues your software if you cannot do this. As a last fallback, you could skip the OCR for signed documents, okay. That's how many other archive products do it. But you don't even have to do that because I have - very wisely - decided to keep two representations of a document. 

So why?

**Comment by tmaier** [comment]
@tzepter, @drhirn, @Panzer1119 I opened now a feature request for this at #5542 please vote for it, if you think this makes sense.
