### ISSUE TITLE
[BUG] UI setting paperless setting for  Pages aka "PAPERLESS_OCR_PAGES" error

### ISSUE THREAD

**Issue by Bloodpack** [paperless-ngx/paperless-ngx#5266]
### Description

if i edit the settings from configuration page in the UI and leave the settings for the pages blank, it throws up an error and will not process the document

![Pages blank setting](https://github.com/paperless-ngx/paperless-ngx/assets/26135135/4cd37122-261d-4c7c-810a-e15aeadfc3e3)

this is the error from the log

```
[2024-01-06 09:48:39,057] [INFO] [paperless.consumer] Consuming Phone stand.pdf

[2024-01-06 09:48:39,060] [DEBUG] [paperless.consumer] Detected mime type: application/pdf

[2024-01-06 09:48:39,068] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser

[2024-01-06 09:48:39,072] [DEBUG] [paperless.consumer] Parsing Phone stand.pdf...

[2024-01-06 09:48:39,270] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-ngxjf2r5htb/Phone stand.pdf'), 'output_file': PosixPath('/tmp/paperless/paperless-h_g1bzpk/archive.pdf'), 'use_threads': True, 'jobs': '4', 'language': 'deu', 'output_type': 'pdfa', 'progress_bar': False, 'color_conversion_strategy': 'RGB', 'redo_ocr': True, 'clean': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'pages': '1-0'}

[2024-01-06 09:48:39,341] [ERROR] [paperless.consumer] Error occurred while consuming document Phone stand.pdf: BadArgsError: invalid page subrange '1-0'

Traceback (most recent call last):

  File "/opt/paperless-ngx/src/paperless_tesseract/parsers.py", line 353, in parse

    ocrmypdf.ocr(**args)

  File "/opt/paperless-ngx/.local/lib/python3.10/site-packages/ocrmypdf/api.py", line 374, in ocr

    check_options(options, plugin_manager)

  File "/opt/paperless-ngx/.local/lib/python3.10/site-packages/ocrmypdf/_validation.py", line 247, in check_options

    _check_plugin_invariant_options(options)

  File "/opt/paperless-ngx/.local/lib/python3.10/site-packages/ocrmypdf/_validation.py", line 236, in _check_plugin_invariant_options

    check_options_ocr_behavior(options)

  File "/opt/paperless-ngx/.local/lib/python3.10/site-packages/ocrmypdf/_validation.py", line 207, in check_options_ocr_behavior

    options.pages = _pages_from_ranges(options.pages)

  File "/opt/paperless-ngx/.local/lib/python3.10/site-packages/ocrmypdf/_validation.py", line 174, in _pages_from_ranges

    raise BadArgsError(

ocrmypdf.exceptions.BadArgsError: invalid page subrange '1-0'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/opt/paperless-ngx/src/documents/consumer.py", line 446, in try_consume_file

    document_parser.parse(self.working_copy, mime_type, self.filename)

  File "/opt/paperless-ngx/src/paperless_tesseract/parsers.py", line 420, in parse

    raise ParseError(f"{e.__class__.__name__}: {e!s}") from e

documents.parsers.ParseError: BadArgsError: invalid page subrange '1-0'

[2024-01-06 09:50:44,501] [INFO] [paperless.consumer] Consuming Phone stand.pdf

[2024-01-06 09:50:44,504] [DEBUG] [paperless.consumer] Detected mime type: application/pdf

[2024-01-06 09:50:44,512] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser

[2024-01-06 09:50:44,516] [DEBUG] [paperless.consumer] Parsing Phone stand.pdf...

[2024-01-06 09:50:44,705] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-ngxtmofm0eo/Phone stand.pdf'), 'output_file': PosixPath('/tmp/paperless/paperless-2y_osmqi/archive.pdf'), 'use_threads': True, 'jobs': '4', 'language': 'deu', 'output_type': 'pdfa', 'progress_bar': False, 'color_conversion_strategy': 'RGB', 'redo_ocr': True, 'clean': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'pages': '1-0'}

[2024-01-06 09:50:44,775] [ERROR] [paperless.consumer] Error occurred while consuming document Phone stand.pdf: BadArgsError: invalid page subrange '1-0'

Traceback (most recent call last):

  File "/opt/paperless-ngx/src/paperless_tesseract/parsers.py", line 353, in parse

    ocrmypdf.ocr(**args)

  File "/opt/paperless-ngx/.local/lib/python3.10/site-packages/ocrmypdf/api.py", line 374, in ocr

    check_options(options, plugin_manager)

  File "/opt/paperless-ngx/.local/lib/python3.10/site-packages/ocrmypdf/_validation.py", line 247, in check_options

    _check_plugin_invariant_options(options)

  File "/opt/paperless-ngx/.local/lib/python3.10/site-packages/ocrmypdf/_validation.py", line 236, in _check_plugin_invariant_options

    check_options_ocr_behavior(options)

  File "/opt/paperless-ngx/.local/lib/python3.10/site-packages/ocrmypdf/_validation.py", line 207, in check_options_ocr_behavior

    options.pages = _pages_from_ranges(options.pages)

  File "/opt/paperless-ngx/.local/lib/python3.10/site-packages/ocrmypdf/_validation.py", line 174, in _pages_from_ranges

    raise BadArgsError(

ocrmypdf.exceptions.BadArgsError: invalid page subrange '1-0'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/opt/paperless-ngx/src/documents/consumer.py", line 446, in try_consume_file

    document_parser.parse(self.working_copy, mime_type, self.filename)

  File "/opt/paperless-ngx/src/paperless_tesseract/parsers.py", line 420, in parse

    raise ParseError(f"{e.__class__.__name__}: {e!s}") from e

documents.parsers.ParseError: BadArgsError: invalid page subrange '1-0'
```

if i set it manually to `0` i can not save and get this error

![Pages 0 setting](https://github.com/paperless-ngx/paperless-ngx/assets/26135135/fcf70e6e-fcb5-4d71-a996-e14302dfc91c)

here the error:
`{"headers":{"normalizedNames":{},"lazyUpdate":null},"status":400,"statusText":"Bad Request","url":"http://10.10.20.199:8000/api/config/1/","ok":false,"name":"HttpErrorResponse","message":"Http failure response for http://10.10.20.199:8000/api/config/1/: 400 Bad Request","error":{"pages":["Stelle sicher, dass dieser Wert größer oder gleich 1 ist."]}}`

### Steps to reproduce

1. go to UI / Configuration
2. change settings on page

### Webserver logs

```bash
log with blank settings:

[2024-01-06 09:48:39,057] [INFO] [paperless.consumer] Consuming Phone stand.pdf

[2024-01-06 09:48:39,060] [DEBUG] [paperless.consumer] Detected mime type: application/pdf

[2024-01-06 09:48:39,068] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser

[2024-01-06 09:48:39,072] [DEBUG] [paperless.consumer] Parsing Phone stand.pdf...

[2024-01-06 09:48:39,270] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-ngxjf2r5htb/Phone stand.pdf'), 'output_file': PosixPath('/tmp/paperless/paperless-h_g1bzpk/archive.pdf'), 'use_threads': True, 'jobs': '4', 'language': 'deu', 'output_type': 'pdfa', 'progress_bar': False, 'color_conversion_strategy': 'RGB', 'redo_ocr': True, 'clean': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'pages': '1-0'}

[2024-01-06 09:48:39,341] [ERROR] [paperless.consumer] Error occurred while consuming document Phone stand.pdf: BadArgsError: invalid page subrange '1-0'

Traceback (most recent call last):

  File "/opt/paperless-ngx/src/paperless_tesseract/parsers.py", line 353, in parse

    ocrmypdf.ocr(**args)

  File "/opt/paperless-ngx/.local/lib/python3.10/site-packages/ocrmypdf/api.py", line 374, in ocr

    check_options(options, plugin_manager)

  File "/opt/paperless-ngx/.local/lib/python3.10/site-packages/ocrmypdf/_validation.py", line 247, in check_options

    _check_plugin_invariant_options(options)

  File "/opt/paperless-ngx/.local/lib/python3.10/site-packages/ocrmypdf/_validation.py", line 236, in _check_plugin_invariant_options

    check_options_ocr_behavior(options)

  File "/opt/paperless-ngx/.local/lib/python3.10/site-packages/ocrmypdf/_validation.py", line 207, in check_options_ocr_behavior

    options.pages = _pages_from_ranges(options.pages)

  File "/opt/paperless-ngx/.local/lib/python3.10/site-packages/ocrmypdf/_validation.py", line 174, in _pages_from_ranges

    raise BadArgsError(

ocrmypdf.exceptions.BadArgsError: invalid page subrange '1-0'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/opt/paperless-ngx/src/documents/consumer.py", line 446, in try_consume_file

    document_parser.parse(self.working_copy, mime_type, self.filename)

  File "/opt/paperless-ngx/src/paperless_tesseract/parsers.py", line 420, in parse

    raise ParseError(f"{e.__class__.__name__}: {e!s}") from e

documents.parsers.ParseError: BadArgsError: invalid page subrange '1-0'

[2024-01-06 09:50:44,501] [INFO] [paperless.consumer] Consuming Phone stand.pdf

[2024-01-06 09:50:44,504] [DEBUG] [paperless.consumer] Detected mime type: application/pdf

[2024-01-06 09:50:44,512] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser

[2024-01-06 09:50:44,516] [DEBUG] [paperless.consumer] Parsing Phone stand.pdf...

[2024-01-06 09:50:44,705] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-ngxtmofm0eo/Phone stand.pdf'), 'output_file': PosixPath('/tmp/paperless/paperless-2y_osmqi/archive.pdf'), 'use_threads': True, 'jobs': '4', 'language': 'deu', 'output_type': 'pdfa', 'progress_bar': False, 'color_conversion_strategy': 'RGB', 'redo_ocr': True, 'clean': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'pages': '1-0'}

[2024-01-06 09:50:44,775] [ERROR] [paperless.consumer] Error occurred while consuming document Phone stand.pdf: BadArgsError: invalid page subrange '1-0'

Traceback (most recent call last):

  File "/opt/paperless-ngx/src/paperless_tesseract/parsers.py", line 353, in parse

    ocrmypdf.ocr(**args)

  File "/opt/paperless-ngx/.local/lib/python3.10/site-packages/ocrmypdf/api.py", line 374, in ocr

    check_options(options, plugin_manager)

  File "/opt/paperless-ngx/.local/lib/python3.10/site-packages/ocrmypdf/_validation.py", line 247, in check_options

    _check_plugin_invariant_options(options)

  File "/opt/paperless-ngx/.local/lib/python3.10/site-packages/ocrmypdf/_validation.py", line 236, in _check_plugin_invariant_options

    check_options_ocr_behavior(options)

  File "/opt/paperless-ngx/.local/lib/python3.10/site-packages/ocrmypdf/_validation.py", line 207, in check_options_ocr_behavior

    options.pages = _pages_from_ranges(options.pages)

  File "/opt/paperless-ngx/.local/lib/python3.10/site-packages/ocrmypdf/_validation.py", line 174, in _pages_from_ranges

    raise BadArgsError(

ocrmypdf.exceptions.BadArgsError: invalid page subrange '1-0'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/opt/paperless-ngx/src/documents/consumer.py", line 446, in try_consume_file

    document_parser.parse(self.working_copy, mime_type, self.filename)

  File "/opt/paperless-ngx/src/paperless_tesseract/parsers.py", line 420, in parse

    raise ParseError(f"{e.__class__.__name__}: {e!s}") from e

documents.parsers.ParseError: BadArgsError: invalid page subrange '1-0'
```

### Paperless-ngx version

Paperless-ngx 2.3.0

### Host OS

Ubuntu 22.04

### Installation method

Bare metal

### Browser

Chrome

### Configuration changes

none

### Other

-

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
When you save it blank, what does the json payload sent look like?

**Comment by Bloodpack** [comment]
> json payload

how can i see that, can you guide me?

**Comment by stumpylog** [comment]
The browser network tools, usually under F12.  Then the network tab and a request to the settings endpoint.

**Comment by Bloodpack** [comment]
is that what you need?
![payload](https://github.com/paperless-ngx/paperless-ngx/assets/26135135/3cc7b42a-1c93-465c-baa1-57ab6329abf5)

here the output:

```
{id: 1, output_type: "pdfa", language: "deu", pages: null, mode: "redo", skip_archive_file: "never",…}
color_conversion_strategy
: 
null
deskew
: 
true
id
: 
1
image_dpi
: 
null
language
: 
"deu"
max_image_pixels
: 
null
mode
: 
"redo"
output_type
: 
"pdfa"
pages
: 
null
rotate_pages
: 
true
rotate_pages_threshold
: 
12
skip_archive_file
: 
"never"
unpaper_clean
: 
"clean-final"
user_args
: 
null
```

**Comment by Bloodpack** [comment]
@stumpylog 

i think i found the problem....

i had to manually add an `#` in my `paperless.conf` before the `PAPERLESS_OCR_PAGES=0`

```
# OCR settings

PAPERLESS_OCR_LANGUAGE=deu
PAPERLESS_OCR_MODE=skip
#PAPERLESS_OCR_SKIP_ARCHIVE_FILE=never
PAPERLESS_OCR_OUTPUT_TYPE=pdfa
#PAPERLESS_OCR_PAGES=0
#PAPERLESS_OCR_IMAGE_DPI=300
PAPERLESS_OCR_CLEAN=clean-final
PAPERLESS_OCR_DESKEW=true
PAPERLESS_OCR_ROTATE_PAGES=true
PAPERLESS_OCR_ROTATE_PAGES_THRESHOLD=12.0
#PAPERLESS_OCR_USER_ARGS={}
#PAPERLESS_CONVERT_MEMORY_LIMIT=0
PAPERLESS_CONVERT_TMPDIR=/var/tmp/paperless
```
should i add an `#` on all lines that are now configurable with the UI?

**Comment by stumpylog** [comment]
The frontend settings will fall back to environment settings if not set.  So back to zero in this case.  It's up to you where you'd like to set it, but if you don't set the frontend and comment out all the lines, you'll end up with only defaults

**Comment by Bloodpack** [comment]
> The frontend settings will fall back to environment settings if not set. So back to zero in this case. It's up to you where you'd like to set it, but if you don't set the frontend and comment out all the lines, you'll end up with only defaults

thank you for the help......

i will comment out all lines that are configured from the UI.
for the empty fields i did not set i am using the "defaults"
