### ISSUE TITLE
[BUG] Updating to 2.3.0 fails with PAPERLESS_OCR_IMAGE_DPI set to "none" - workaround possible

### ISSUE THREAD

**Issue by Adrian-Grimm** [paperless-ngx/paperless-ngx#5271]
### Description

I tried to upgrade to version 2.3.0 and had the PAPERLESS_OCR_IMAGE_DPI set to "none" in docker variables which caused a failed start:

### Workaround

Removing the "PAPERLESS_OCR_IMAGE_DPI" completly from docker environment variables helped.

### Suggested Fix

- may inform about this breaking change
- fix the usage of "PAPERLESS_OCR_IMAGE_DPI=none"

### Steps to reproduce

Just upgrade the docker image to 2.3.0 from the previous latest version v2.2.1.

### Webserver logs

```bash
Paperless-ngx docker container starting...
 Creating directory /tmp/paperless
 Adjusting permissions of paperless files. This may take a while.
 Waiting for PostgreSQL to start...
 Apply database migrations...
 Traceback (most recent call last):
   File "/usr/src/paperless/src/manage.py", line 10, in <module>
     execute_from_command_line(sys.argv)
   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
     utility.execute()
   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 382, in execute
     settings.INSTALLED_APPS
   File "/usr/local/lib/python3.11/site-packages/django/conf/__init__.py", line 102, in __getattr__
     self._setup(name)
   File "/usr/local/lib/python3.11/site-packages/django/conf/__init__.py", line 89, in _setup
     self._wrapped = Settings(settings_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/django/conf/__init__.py", line 217, in __init__
     mod = importlib.import_module(self.SETTINGS_MODULE)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
     return _bootstrap._gcd_import(name[level:], package, level)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
   File "/usr/src/paperless/src/paperless/settings.py", line 862, in <module>
     OCR_IMAGE_DPI = __get_optional_int("PAPERLESS_OCR_IMAGE_DPI")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/src/paperless/src/paperless/settings.py", line 65, in __get_optional_int
     return __get_int(key, -1)  # pragma: no cover
            ^^^^^^^^^^^^^^^^^^
   File "/usr/src/paperless/src/paperless/settings.py", line 57, in __get_int
     return int(os.getenv(key, default))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 ValueError: invalid literal for int() with base 10: 'none'
```

### Paperless-ngx version

2.3.0

### Host OS

Linux

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
None is not a valid number.  The documentation says if you are setting this, it must be a number.  So it's not a breaking change at all.

**Comment by Adrian-Grimm** [comment]
previously it was working ... till 2.3.0

But if this is like it should be - OK.

**Comment by stumpylog** [comment]
If anything, the fact that was accepted at all was a bug which has now been fixed by something.

**Comment by Adrian-Grimm** [comment]
@stumpylog But it's also broken on UI:

<img width="649" alt="image" src="https://github.com/paperless-ngx/paperless-ngx/assets/5657002/6914ed91-62a2-4e3e-812c-1c43e1aaab21">

Documentation tells 0 is allowed for unlimeted pages:
https://docs.paperless-ngx.com/configuration/#PAPERLESS_OCR_PAGES

<img width="1203" alt="image" src="https://github.com/paperless-ngx/paperless-ngx/assets/5657002/9c47c19e-3cd9-4d47-ba71-fde5c441338d">

But UI also doesn't accept it.

**Comment by stumpylog** [comment]
I'm updating the documentation on that variable to remove the "default is none" wording, which I can see as being odd wording.  it will now say "defaults to unset", etc
