### ISSUE TITLE
[BUG] Wrong placeholder use in workflow may cause deletion of file

### ISSUE THREAD

**Issue by towadroid** [paperless-ngx/paperless-ngx#5277]
### Description

When using placeholders in a workflow but accidentally misspelling them as `{created_year]` instead of `{created_year}`, it seems difficult/impossible to retrieve the document afterwards. The user gets notified about an invalid token `{` in the filename and an error is shown under file tasks. After that I also restarted the application and performed a reindex.

### Steps to reproduce

1. Create workflow and type `{created_year]` in the assign title field.
2. Upload document which matches the workflow.

### Webserver logs

```bash
[2024-01-06 18:10:30,699] [INFO] [paperless.consumer] Consuming filename.pdf
[2024-01-06 18:10:30,702] [DEBUG] [paperless.consumer] Detected mime type: application/pdf
[2024-01-06 18:10:30,706] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser
[2024-01-06 18:10:30,709] [DEBUG] [paperless.consumer] Parsing filename.pdf...
[2024-01-06 18:10:30,932] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-ngxm_5gu8vf/filename.pdf'), 'output_file': PosixPath('/tmp/paperless/paperless-pajtklp0/archive.pdf'), 'use_threads': True, 'jobs': 2, 'language': 'deu+eng', 'output_type': 'pdfa', 'progress_bar': False, 'color_conversion_strategy': 'RGB', 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-pajtklp0/sidecar.txt')}
[2024-01-06 18:10:31,366] [DEBUG] [paperless.parsing.tesseract] Incomplete sidecar file: discarding.
[2024-01-06 18:10:31,504] [DEBUG] [paperless.consumer] Generating thumbnail for filename.pdf...
[2024-01-06 18:10:31,507] [DEBUG] [paperless.parsing] Execute: convert -density 300 -scale 500x5000> -alpha remove -strip -auto-orient /tmp/paperless/paperless-pajtklp0/archive.pdf[0] /tmp/paperless/paperless-pajtklp0/convert.webp
[2024-01-06 18:10:32,790] [DEBUG] [paperless.consumer] Saving record to database
[2024-01-06 18:10:32,791] [DEBUG] [paperless.consumer] Creation date from parse_date: 2023-11-30 00:00:00+01:00
[2024-01-06 18:10:32,913] [INFO] [paperless.matching] Document matched WorkflowTrigger 2 from Workflow: workflowname
[2024-01-06 18:10:32,915] [INFO] [paperless.handlers] Applying WorkflowAction 2 from Workflow: workflowname
[2024-01-06 18:10:32,922] [ERROR] [paperless.consumer] The following error occurred while storing document filename.pdf after parsing: unexpected '{' in field name
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 349, in main_wrap
    raise exc_info[1]
  File "/usr/src/paperless/src/documents/consumer.py", line 514, in try_consume_file
    document_consumption_finished.send(
  File "/usr/local/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
           ^
  File "/usr/local/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/paperless/src/documents/signals/handlers.py", line 523, in run_workflow_added
    run_workflow(
  File "/usr/src/paperless/src/documents/signals/handlers.py", line 573, in run_workflow
    document.title = parse_doc_title_w_placeholders(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/paperless/src/documents/consumer.py", line 891, in parse_doc_title_w_placeholders
    return title.format(**formatting).strip()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: unexpected '{' in field name
[2024-01-06 18:10:32,924] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-pajtklp0
[2024-01-06 18:11:32,028] [WARNING] [paperless.api] An error occurred listing search results: Document matching query does not exist.
```

### Paperless-ngx version

2.3.0

### Host OS

Debian 12

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
If you would like to create a feature request to better protect against user error that would be fine, I agree it could more feedback earlier could prevent this, but this certainly is a user error, no?

**Comment by towadroid** [comment]
I agree it is a user error. However, I personally consider it a bug if a simple user error leads to (accidental) deletion of a file. A "bug fix" for me would include just not performing the deletion task. If you still think I should create a feature request instead, I am also happy to do that. Please let me know.

**Comment by stumpylog** [comment]
If you have uploaded the file, then you still have a copy.  Uploads are inherently ephemeral, unlike consumption directory.  It does come down to the user to keep the file until they know it has been safely stored.

(And on a technical side, are you really going to be digging in `/tmp` to find the file and upload it again?)
