### ISSUE TITLE
[BUG] Filename on filesystem has Problems with umlauts

### ISSUE THREAD

**Issue by ProgTiger** [paperless-ngx/paperless-ngx#5289]
### Description

When uploading a file with umlauts (eg. Ä, ä) the File on the Filesystem seams to be in ISO 8859-1 (Latin-1). 

**Setup**

| Docker with paperless-ngx + mariadb |    -- SMB (driver_opts: type: cifs) --> | NAS (consume, media, export) |

DB:
```
MariaDB [paperless]> SELECT @@character_set_database, @@collation_database;
+--------------------------+----------------------+
| @@character_set_database | @@collation_database |
+--------------------------+----------------------+
| utf8mb4                  | utf8mb4_unicode_ci   |
+--------------------------+----------------------+
```

**Upload within Web-UI**

![grafik](https://github.com/paperless-ngx/paperless-ngx/assets/131643191/4277afc8-865d-4f5f-9709-e45f035079f2)

or Rename a File:

![grafik](https://github.com/paperless-ngx/paperless-ngx/assets/131643191/502f41b3-794d-45c8-bf95-a1d498ed7d1e)

Results in:

```
MariaDB [paperless]> select id, title, filename, original_filename from documents_document where id = 18 OR id = 27;
+----+------------------------+--------------------------------------+-----------------------+
| id | title                  | filename                             | original_filename     |
+----+------------------------+--------------------------------------+-----------------------+
| 18 | Liste_von_Bäckern_NEU  | 2024/none/Liste_von_Bäckern_NEU.pdf  | Test 6.pdf            |
| 27 | Liste_von_Bäcker       | 2024/none/Liste_von_Bäcker.odt       | Liste_von_Bäcker.odt  |
+----+------------------------+--------------------------------------+-----------------------+
```

Filesystem (archived):
![grafik](https://github.com/paperless-ngx/paperless-ngx/assets/131643191/eddd6f25-75ea-410e-b91c-28e78e287957)

Filesystem (originals):
![grafik](https://github.com/paperless-ngx/paperless-ngx/assets/131643191/823c6ce1-54e9-4c42-b421-72211898fcce)

**Uploading in consume folder**

![grafik](https://github.com/paperless-ngx/paperless-ngx/assets/131643191/3fdbfb7e-c07f-415a-b81b-05eadfeb2ea9)

leads to error Message (see Logs)

**change in docker-compose.yml**
```
volumes:
    data:   
    dbdata:
    redisdata:
    consume:
      # driver: local
      driver_opts:
        type: cifs 
        o: "username=xxxxxxxxx,password=xxxxxxxxx,uid=1000,gid=1000,vers=3.0"
        device: "//xxx.xxx.xxx.xxx/dms/consume"  
    export:
      # driver: local
      driver_opts:
        type: cifs 
        o: "username=xxxxxxxxx,password=xxxxxxxxx,uid=1000,gid=1000,vers=3.0"
        device: "//xxx.xxx.xxx.xxx/dms/export"
    media:
      # driver: local
      driver_opts:
        type: cifs 
        o: "username=xxxxxxxxx,password=xxxxxxxxx,uid=1000,gid=1000,vers=3.0"
        device: "//xxx.xxx.xxx.xxx/dms/media"
```
Maybe related to:  #898

### Steps to reproduce

**Upload within Web-UI**
1. Upload File with umlauts in Web-UI

**Rename within Web-UI**
1. Rename File without umlauts to one with umlauts

**Uploading in consume folder**
1. Copy file with umlauts to the consume folder (by SMB)

### Webserver logs

```bash
paperless-webserver-1  | [2024-01-07 12:27:46,618] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/Liste_von_B\udce4cker_ALT.odt to the task queue.
paperless-webserver-1  | [2024-01-07 12:27:46,653] [ERROR] [paperless.handlers] Creating PaperlessTask failed
paperless-webserver-1  | Traceback (most recent call last):
paperless-webserver-1  |   File "/usr/src/paperless/src/documents/signals/handlers.py", line 644, in before_task_publish_handler
paperless-webserver-1  |     PaperlessTask.objects.create(
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
paperless-webserver-1  |     return getattr(self.get_queryset(), name)(*args, **kwargs)
paperless-webserver-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 658, in create
paperless-webserver-1  |     obj.save(force_insert=True, using=self.db)
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 814, in save
paperless-webserver-1  |     self.save_base(
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 877, in save_base
paperless-webserver-1  |     updated = self._save_table(
paperless-webserver-1  |               ^^^^^^^^^^^^^^^^^
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 1020, in _save_table
paperless-webserver-1  |     results = self._do_insert(
paperless-webserver-1  |               ^^^^^^^^^^^^^^^^
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 1061, in _do_insert
paperless-webserver-1  |     return manager._insert(
paperless-webserver-1  |            ^^^^^^^^^^^^^^^^
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
paperless-webserver-1  |     return getattr(self.get_queryset(), name)(*args, **kwargs)
paperless-webserver-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1805, in _insert
paperless-webserver-1  |     return query.get_compiler(using=using).execute_sql(returning_fields)
paperless-webserver-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
paperless-webserver-1  |     cursor.execute(sql, params)
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
paperless-webserver-1  |     return self._execute_with_wrappers(
paperless-webserver-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
paperless-webserver-1  |     return executor(sql, params, many, context)
paperless-webserver-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
paperless-webserver-1  |     return self.cursor.execute(sql, params)
paperless-webserver-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 75, in execute
paperless-webserver-1  |     return self.cursor.execute(query, args)
paperless-webserver-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 176, in execute
paperless-webserver-1  |     mogrified_query = self._mogrify(query, args)
paperless-webserver-1  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 198, in _mogrify
paperless-webserver-1  |     args = tuple(map(db.literal, args))
paperless-webserver-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/MySQLdb/connections.py", line 278, in literal
paperless-webserver-1  |     s = self.string_literal(o.encode(self.encoding))
paperless-webserver-1  |                             ^^^^^^^^^^^^^^^^^^^^^^^
paperless-webserver-1  | UnicodeEncodeError: 'utf-8' codec can't encode character '\udce4' in position 11: surrogates not allowed
paperless-webserver-1  | [2024-01-07 12:27:46,673] [INFO] [celery.worker.strategy] Task documents.tasks.consume_file[462897c7-fbf9-4152-9a4f-35166c7f50f0] received
paperless-webserver-1  | [2024-01-07 12:27:46,692] [WARNING] [paperless.barcodes] Unsupported file format for barcode reader: application/vnd.oasis.opendocument.text
paperless-webserver-1  | [2024-01-07 12:27:46,712] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[462897c7-fbf9-4152-9a4f-35166c7f50f0] raised unexpected: UnicodeEncodeError('utf-8', 'Liste_von_B\udce4cker_ALT.odt', 11, 12, 'surrogates not allowed')
paperless-webserver-1  | Traceback (most recent call last):
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
paperless-webserver-1  |     R = retval = fun(*args, **kwargs)
paperless-webserver-1  |                  ^^^^^^^^^^^^^^^^^^^^
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
paperless-webserver-1  |     return self.run(*args, **kwargs)
paperless-webserver-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-webserver-1  |   File "/usr/src/paperless/src/documents/tasks.py", line 171, in consume_file
paperless-webserver-1  |     document = Consumer().try_consume_file(
paperless-webserver-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-webserver-1  |   File "/usr/src/paperless/src/documents/consumer.py", line 363, in try_consume_file
paperless-webserver-1  |     self._send_progress(
paperless-webserver-1  |   File "/usr/src/paperless/src/documents/consumer.py", line 102, in _send_progress
paperless-webserver-1  |     async_to_sync(self.channel_layer.group_send)(
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 277, in __call__
paperless-webserver-1  |     return call_result.result()
paperless-webserver-1  |            ^^^^^^^^^^^^^^^^^^^^
paperless-webserver-1  |   File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
paperless-webserver-1  |     return self.__get_result()
paperless-webserver-1  |            ^^^^^^^^^^^^^^^^^^^
paperless-webserver-1  |   File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
paperless-webserver-1  |     raise self._exception
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 353, in main_wrap
paperless-webserver-1  |     result = await self.awaitable(*args, **kwargs)
paperless-webserver-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/channels_redis/pubsub.py", line 18, in _async_proxy
paperless-webserver-1  |     return await getattr(layer, name)(*args, **kwargs)
paperless-webserver-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/channels_redis/pubsub.py", line 226, in group_send
paperless-webserver-1  |     await shard.publish(group_channel, self.channel_layer.serialize(message))
paperless-webserver-1  |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/channels_redis/pubsub.py", line 45, in serialize
paperless-webserver-1  |     return msgpack.packb(message)
paperless-webserver-1  |            ^^^^^^^^^^^^^^^^^^^^^^
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/msgpack/__init__.py", line 36, in packb
paperless-webserver-1  |     return Packer(**kwargs).pack(o)
paperless-webserver-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^
paperless-webserver-1  |   File "msgpack/_packer.pyx", line 294, in msgpack._cmsgpack.Packer.pack
paperless-webserver-1  |   File "msgpack/_packer.pyx", line 300, in msgpack._cmsgpack.Packer.pack
paperless-webserver-1  |   File "msgpack/_packer.pyx", line 297, in msgpack._cmsgpack.Packer.pack
paperless-webserver-1  |   File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
paperless-webserver-1  |   File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
paperless-webserver-1  | UnicodeEncodeError: 'utf-8' codec can't encode character '\udce4' in position 11: surrogates not allowed
paperless-tika-1       | INFO  [qtp310212872-58] 11:29:20,358 org.apache.tika.server.core.resource.MetadataResource /meta (application/vnd.oasis.opendocument.text)
paperless-tika-1       | INFO  [qtp310212872-30] 11:29:20,376 org.apache.tika.server.core.resource.MetadataResource /meta (application/vnd.oasis.opendocument.text)
paperless-webserver-1  | [2024-01-07 12:30:00,000] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
paperless-webserver-1  | [2024-01-07 12:30:00,004] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[1af24882-b16d-450c-a6c4-7657747eb0d0] received
paperless-webserver-1  | [2024-01-07 12:30:00,034] [INFO] [celery.app.trace] Task paperless_mail.tasks.process_mail_accounts[1af24882-b16d-450c-a6c4-7657747eb0d0] succeeded in 0.027176700001291465s: 'No new documents were added.'
```

### Paperless-ngx version

2.3.1

### Host OS

Windows 11 / WSL / Docker-Desktop + Synology NAS

### Installation method

Docker - official image

### Browser

Firefox

### Configuration changes

docker-compose.yml

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by alexmaret** [comment]
Looks like your CIFS configuration is incorrect. It uses some non-UTF8 character set. That's why you see garbled output for your media folders and the filenames of your consumption documents cannot be decoded.

Try to add `iocharset=utf8` to the "o" line of your CIFS configuration.

**Comment by ProgTiger** [comment]
Hi @alexmaret,

thanks for the fast response. This fixed my issue.
