### ISSUE TITLE
Import fails if file is still being written while task is run

### ISSUE THREAD

**Issue by repvik** [paperless-ngx/paperless-ngx#531]
I'm using a ADS-1700W over wifi, and when scanning >5 double pages, writing the file to the import samba share is so slow takes long enough to guarantee that an import job will be run before the file is fully written.

The import job will then fail, and the file will be ignored until I manually remove and re-add it.

```
[2022-03-25` 13:45:52,985] [DEBUG] [paperless.management.consumer] Waiting for file /usr/src/paperless/src/../consume/E79222G1X113223_03252022_134412_000033.pdf to remain unmodified
[2022-03-25 13:45:57,988] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/src/../consume/E79222G1X113223_03252022_134412_000033.pdf to the task queue.
[2022-03-25 13:45:58,137] [INFO] [paperless.consumer] Consuming E79222G1X113223_03252022_134412_000033.pdf
[2022-03-25 13:45:58,140] [DEBUG] [paperless.consumer] Detected mime type: application/pdf
[2022-03-25 13:45:58,153] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser
[2022-03-25 13:45:58,157] [DEBUG] [paperless.consumer] Parsing E79222G1X113223_03252022_134412_000033.pdf...
[2022-03-25 13:45:58,282] [WARNING] [paperless.parsing.tesseract] Error while getting text from PDF document with pdfminer.six
Traceback (most recent call last):
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 116, in extract_text
    stripped = post_process_text(pdfminer_extract_text(pdf_file))
  File "/usr/local/lib/python3.9/site-packages/pdfminer/high_level.py", line 146, in extract_text
    for page in PDFPage.get_pages(
  File "/usr/local/lib/python3.9/site-packages/pdfminer/pdfpage.py", line 147, in get_pages
    doc = PDFDocument(parser, password=password, caching=caching)
  File "/usr/local/lib/python3.9/site-packages/pdfminer/pdfdocument.py", line 701, in __init__
    newxref.load(parser)
  File "/usr/local/lib/python3.9/site-packages/pdfminer/pdfdocument.py", line 194, in load
    (_, obj) = parser.nextobject()
  File "/usr/local/lib/python3.9/site-packages/pdfminer/psparser.py", line 604, in nextobject
    (pos, token) = self.nexttoken()
  File "/usr/local/lib/python3.9/site-packages/pdfminer/psparser.py", line 518, in nexttoken
    self.fillbuf()
  File "/usr/local/lib/python3.9/site-packages/pdfminer/psparser.py", line 233, in fillbuf
    raise PSEOF('Unexpected EOF')
pdfminer.psparser.PSEOF: Unexpected EOF
[2022-03-25 13:45:58,437] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': '/usr/src/paperless/src/../consume/E79222G1X113223_03252022_134412_000033.pdf', 'output_file': '/tmp/paperless/paperless-aytqjzrt/archive.pdf', 'use_threads': True, 'jobs': 1, 'language': 'nor+eng', 'output_type': 'pdfa', 'progress_bar': False, 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': '/tmp/paperless/paperless-aytqjzrt/sidecar.txt'}
[2022-03-25 13:45:59,594] [WARNING] [paperless.parsing.tesseract] Encountered an error while running OCR: . Attempting force OCR to get the text.
[2022-03-25 13:45:59,595] [DEBUG] [paperless.parsing.tesseract] Fallback: Calling OCRmyPDF with args: {'input_file': '/usr/src/paperless/src/../consume/E79222G1X113223_03252022_134412_000033.pdf', 'output_file': '/tmp/paperless/paperless-aytqjzrt/archive-fallback.pdf', 'use_threads': True, 'jobs': 1, 'language': 'nor+eng', 'output_type': 'pdfa', 'progress_bar': False, 'force_ocr': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': '/tmp/paperless/paperless-aytqjzrt/sidecar-fallback.txt'}
[2022-03-25 13:46:00,944] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-aytqjzrt
[2022-03-25 13:46:00,949] [ERROR] [paperless.consumer] Error while consuming document E79222G1X113223_03252022_134412_000033.pdf: InputFileError:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 156, in get_pdfinfo
    return PdfInfo(
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 901, in __init__
    with Pdf.open(infile) as pdf:
  File "/usr/local/lib/python3.9/site-packages/pikepdf/_methods.py", line 923, in open
    pdf = Pdf._open(
pikepdf._qpdf.PdfError: /tmp/ocrmypdf.io.iq4w3lcf/origin.pdf: unable to find trailer dictionary while recovering damaged file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 249, in parse
    ocrmypdf.ocr(**args)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/api.py", line 337, in ocr
    return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 370, in run_pipeline
    pdfinfo = get_pdfinfo(
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 167, in get_pdfinfo
    raise InputFileError() from e
ocrmypdf.exceptions.InputFileError

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 156, in get_pdfinfo
    return PdfInfo(
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 901, in __init__
    with Pdf.open(infile) as pdf:
  File "/usr/local/lib/python3.9/site-packages/pikepdf/_methods.py", line 923, in open
    pdf = Pdf._open(
pikepdf._qpdf.PdfError: /tmp/ocrmypdf.io.xid44n_l/origin.pdf: unable to find trailer dictionary while recovering damaged file
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 286, in parse
    ocrmypdf.ocr(**args)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/api.py", line 337, in ocr
    return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 370, in run_pipeline
    pdfinfo = get_pdfinfo(
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 167, in get_pdfinfo
    raise InputFileError() from e
ocrmypdf.exceptions.InputFileError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/consumer.py", line 245, in try_consume_file
    document_parser.parse(self.path, mime_type, self.filename)
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 297, in parse
    raise ParseError(f"{e.__class__.__name__}: {str(e)}")
documents.parsers.ParseError: InputFileError:
```

**Comment by Tooa** [comment]
Maybe https://github.com/paperless-ngx/paperless-ngx/pull/483 will be a solution to your problem

**Comment by repvik** [comment]
That appears to be a good solution.

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/83f10167e51c13eb37ace691a34fa773ab6ba1a6
