### ISSUE TITLE
[BUG] Workflows: spaces inside placeholder tags break consumption

### ISSUE THREAD

**Issue by simon-lorenz** [paperless-ngx/paperless-ngx#5321]
### Description

Using e.g. `{ added_month }` instead of `{added_month}` inside a workflow action breaks the document consumption. Not a big issue, but maybe the placeholder name could be trimmed for more resilience.

### Steps to reproduce

1. Create a workflow like this:

![grafik](https://github.com/paperless-ngx/paperless-ngx/assets/34041551/f06bf983-88f0-47a6-9dbf-0cac8cae8982)

2. Trigger the workflow

### Webserver logs

```bash
[2024-01-08 16:48:49,231] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[3cdf6c1b-eb66-47bf-9cf8-3d9959ff970c] raised unexpecte │
│ Traceback (most recent call last):                                                                                                            │
│   File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 349, in main_wrap                                                      │
│     raise exc_info[1]                                                                                                                         │
│   File "/usr/src/paperless/src/documents/consumer.py", line 514, in try_consume_file                                                          │
│     document_consumption_finished.send(                                                                                                       │
│   File "/usr/local/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 176, in send                                             │
│     return [                                                                                                                                  │
│            ^                                                                                                                                  │
│   File "/usr/local/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>                                       │
│     (receiver, receiver(signal=self, sender=sender, **named))                                                                                 │
│                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                  │
│   File "/usr/src/paperless/src/documents/signals/handlers.py", line 523, in run_workflow_added                                                │
│     run_workflow(                                                                                                                             │
│   File "/usr/src/paperless/src/documents/signals/handlers.py", line 573, in run_workflow                                                      │
│     document.title = parse_doc_title_w_placeholders(                                                                                          │
│                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                          │
│   File "/usr/src/paperless/src/documents/consumer.py", line 891, in parse_doc_title_w_placeholders                                            │
│     return title.format(**formatting).strip()                                                                                                 │
│            ^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                         │
│ KeyError: ' added_month '                                                                                                                     │
│                                                                                                                                               │
│ The above exception was the direct cause of the following exception:                                                                          │
│                                                                                                                                               │
│ Traceback (most recent call last):                                                                                                            │
│   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task                                                 │
│     R = retval = fun(*args, **kwargs)                                                                                                         │
│                  ^^^^^^^^^^^^^^^^^^^^                                                                                                         │
│   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__                                         │
│     return self.run(*args, **kwargs)                                                                                                          │
│            ^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                          │
│   File "/usr/src/paperless/src/documents/tasks.py", line 171, in consume_file                                                                 │
│     document = Consumer().try_consume_file(                                                                                                   │
│                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                   │
│   File "/usr/src/paperless/src/documents/consumer.py", line 577, in try_consume_file                                                          │
│     self._fail(                                                                                                                               │
│   File "/usr/src/paperless/src/documents/consumer.py", line 116, in _fail                                                                     │
│     raise ConsumerError(f"{self.filename}: {log_message or message}") from exception                                                          │
│ documents.consumer.ConsumerError: Test.pdf: The following error occurred while storing document Test.pdf after parsing: ' added_month '       │
```

### Paperless-ngx version

2.3.2

### Host OS

Docker

### Installation method

Docker - official image

### Browser

Firefox

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Similar to the other one, I do not think this is a true bug, more like a change request.

But, turns out that #5282 will also solve this.
