### ISSUE TITLE
Error occurred while consuming document: InputFileError

### ISSUE THREAD

**Issue by tomac01** [paperless-ngx/paperless-ngx#5323]
### Description

Hello,
I received the following error while paperless consuming two documents  ->see web server log

I don't understand this, because the documents were consumed correctly after they were copied again into the consume directory.

The error does not occur permanently. 95% of documents are processed correctly.

The documents are created by a scanner and consist of two pages that are scanned one after the other and saved into a PDF by the scanner.
It would therefore be possible that paperless-ngx would like to access a PDF that is still being processed.

### Steps to reproduce

1. scanning a two-sided document

### Webserver logs

```bash
[2024-01-08 14:10:47,177] [ERROR] [paperless.consumer] Error occurred while consuming document Dok0001.pdf: InputFileError:

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipeline.py", line 173, in get_pdfinfo

    return PdfInfo(

           ^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/pdfinfo/info.py", line 1100, in __init__

    with Pdf.open(infile) as pdf:

         ^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/pikepdf/_methods.py", line 394, in open

    pdf = Pdf._open(

          ^^^^^^^^^^

pikepdf._core.PdfError: /tmp/ocrmypdf.io.3kdor70c/origin.pdf: unable to find trailer dictionary while recovering damaged file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 353, in parse

    ocrmypdf.ocr(**args)

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/api.py", line 375, in ocr

    return run_pipeline(options=options, plugin_manager=plugin_manager)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 225, in run_pipeline

    return _run_pipeline(options, plugin_manager)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 176, in _run_pipeline

    pdfinfo = get_pdfinfo(

              ^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipeline.py", line 185, in get_pdfinfo

    raise InputFileError() from e

ocrmypdf.exceptions.InputFileError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipeline.py", line 173, in get_pdfinfo

    return PdfInfo(

           ^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/pdfinfo/info.py", line 1100, in __init__

    with Pdf.open(infile) as pdf:

         ^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/pikepdf/_methods.py", line 394, in open

    pdf = Pdf._open(

          ^^^^^^^^^^

pikepdf._core.PdfError: /tmp/ocrmypdf.io.vrue66z9/origin.pdf: unable to find trailer dictionary while recovering damaged file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 404, in parse

    ocrmypdf.ocr(**args)

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/api.py", line 375, in ocr

    return run_pipeline(options=options, plugin_manager=plugin_manager)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 225, in run_pipeline

    return _run_pipeline(options, plugin_manager)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 176, in _run_pipeline

    pdfinfo = get_pdfinfo(

              ^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipeline.py", line 185, in get_pdfinfo

    raise InputFileError() from e

ocrmypdf.exceptions.InputFileError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 349, in main_wrap

    raise exc_info[1]

  File "/usr/src/paperless/src/documents/consumer.py", line 446, in try_consume_file

    document_parser.parse(self.working_copy, mime_type, self.filename)

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 416, in parse

    raise ParseError(f"{e.__class__.__name__}: {e!s}") from e

documents.parsers.ParseError: InputFileError:
```

### Paperless-ngx version

2.3.1

### Host OS

 Ubuntu 22.04.3 LTS

### Installation method

Docker - official image

### Browser

Safari, Chrome

### Configuration changes

PAPERLESS_FILENAME_FORMAT={created_year}/{created_year_short}{created_month}{created_day}_{title}_{doc_pk} PAPERLESS_OCR_SKIP_ARCHIVE_FILE=always PAPERLESS_OCR_PAGES=10 PAPERLESS_OCR_IMAGE_DPI=300 PAPERLESS_TASK_WORKERS=1 PAPERLESS_WORKER_TIMEOUT=2400 PAPERLESS_EMAIL_TASK_CRON=*/5 * * * * PAPERLESS_CONSUMER_DELETE_DUPLICATES=true PAPERLESS_CONSUMER_RECURSIVE=true PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS=true PAPERLESS_FILENAME_DATE_ORDER=DMY PAPERLESS_DATE_ORDER=DMY #PAPERLESS_CONSUMER_INOTIFY_DELAY=5 PAPERLESS_CONSUMER_POLLING=15 PAPERLESS_CONSUMER_POLLING_RETRY_COUNT=10 PAPERLESS_CONSUMER_POLLING_DELAY=10

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
> pikepdf._core.PdfError: /tmp/ocrmypdf.io.3kdor70c/origin.pdf: unable to find trailer dictionary while recovering damaged file

The PDF file is either not valid, damaged or otherwise borked.  There is nothing we are able to do.

**Comment by tomac01** [comment]
many thanks for the quick response!

As I said, the documents were processed correctly after being copied out and back in again. The PDF can therefore actually not be damaged.

Could it be that the PDF was still locked due to scan-write access and could not be read by paperless?

I thought I could do this through the settings
PAPERLESS_CONSUMER_POLLING=15 PAPERLESS_CONSUMER_POLLING_RETRY_COUNT=10 PAPERLESS_CONSUMER_POLLING_DELAY=10
can handle.
Have I set something wrong here?

Best regards

**Comment by shamoon** [comment]
He's saying the PDF is malformed, e.g. https://www.google.com/search?q=unable+to+find+trailer+dictionary+while+recovering+damaged+file --> https://github.com/ocrmypdf/OCRmyPDF/issues/306 etc

**Comment by tomac01** [comment]
thx!
