### ISSUE TITLE
[BUG] import of docx files with cyrillic (ukraine) names doesn't work.

### ISSUE THREAD

**Issue by slookin** [paperless-ngx/paperless-ngx#5361]
### Description

[error.log](https://github.com/paperless-ngx/paperless-ngx/files/13919678/error.log)

Most informaton visible in attachend log file.
Just want to add, if I rename with "Тестовий документ.docx" into "Test doc.docx" it works very well.

So, problem only in cyrillic name of doc. 

PS. I doesn't affect .pdf files, problem appears only with .docx 

-----
PPS. I have build my own docker file for paperless, becasue need to extend tesseract-ocr packages.
also below changes in docker-compose.env

PAPERLESS_OCR_LANGUAGE=deu+eng+rus
PAPERLESS_CONSUMER_POLLING=30
PAPERLESS_CONSUMER_RECURSIVE=true
PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS=true
PAPERLESS_FILENAME_FORMAT_REMOVE_NONE=true
PAPERLESS_OCR_USER_ARGS='{"continue_on_soft_render_error": true}'

### Steps to reproduce

[Тестовий документ.docx](https://github.com/paperless-ngx/paperless-ngx/files/13919703/default.docx)

document for reproduce problem

### Webserver logs

```bash
[2024-01-12 13:38:50,513] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/test/Тестовий документ.docx to the task queue.
2024-01-12 14:38:50 [2024-01-12 13:38:50,578] [INFO] [celery.worker.strategy] Task documents.tasks.consume_file[e04e9aab-5e08-4364-921b-767688081c31] received
2024-01-12 14:38:50 [2024-01-12 13:38:50,743] [INFO] [paperless.matching] Document did not match template folder Sergei
2024-01-12 14:38:50 [2024-01-12 13:38:50,760] [INFO] [paperless.matching] Document did not match template folder Dmitrii
2024-01-12 14:38:50 [2024-01-12 13:38:50,972] [INFO] [paperless.consumer] Consuming Тестовий документ.docx
2024-01-12 14:38:51 [2024-01-12 13:38:51,171] [INFO] [paperless.parsing.tika] Sending /tmp/paperless/paperless-ngx19kytm3k/Тестовий документ.docx to Tika server
2024-01-12 14:38:51 [2024-01-12 13:38:51,233] [INFO] [paperless.parsing.tika] Converting /tmp/paperless/paperless-ngx19kytm3k/Тестовий документ.docx to PDF as /tmp/paperless/paperless-rum0q9p9/convert.pdf
2024-01-12 14:38:51 [2024-01-12 13:38:51,376] [ERROR] [paperless.consumer] Error occurred while consuming document Тестовий документ.docx: Error while converting document to PDF: Server error '500 Internal Server Error' for url 'http://gotenberg:3000/forms/libreoffice/convert'
2024-01-12 14:38:51 For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500
2024-01-12 14:38:51 Traceback (most recent call last):
2024-01-12 14:38:51   File "/usr/src/paperless/src/paperless_tika/parsers.py", line 104, in convert_to_pdf
2024-01-12 14:38:51     response = route.run()
2024-01-12 14:38:51                ^^^^^^^^^^^
2024-01-12 14:38:51   File "/usr/local/lib/python3.11/site-packages/gotenberg_client/_base.py", line 74, in run
2024-01-12 14:38:51     resp.raise_for_status()
2024-01-12 14:38:51   File "/usr/local/lib/python3.11/site-packages/httpx/_models.py", line 758, in raise_for_status
2024-01-12 14:38:51     raise HTTPStatusError(message, request=request, response=self)
2024-01-12 14:38:51 httpx.HTTPStatusError: Server error '500 Internal Server Error' for url 'http://gotenberg:3000/forms/libreoffice/convert'
2024-01-12 14:38:51 For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500
2024-01-12 14:38:51 
2024-01-12 14:38:51 The above exception was the direct cause of the following exception:
2024-01-12 14:38:51 
2024-01-12 14:38:51 Traceback (most recent call last):
2024-01-12 14:38:51   File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 349, in main_wrap
2024-01-12 14:38:51     raise exc_info[1]
2024-01-12 14:38:51   File "/usr/src/paperless/src/documents/consumer.py", line 446, in try_consume_file
2024-01-12 14:38:51     document_parser.parse(self.path, mime_type, self.filename)
2024-01-12 14:38:51   File "/usr/src/paperless/src/paperless_tika/parsers.py", line 82, in parse
2024-01-12 14:38:51     self.archive_path = self.convert_to_pdf(document_path, file_name)
2024-01-12 14:38:51                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-12 14:38:51   File "/usr/src/paperless/src/paperless_tika/parsers.py", line 111, in convert_to_pdf
2024-01-12 14:38:51     raise ParseError(
2024-01-12 14:38:51 documents.parsers.ParseError: Error while converting document to PDF: Server error '500 Internal Server Error' for url 'http://gotenberg:3000/forms/libreoffice/convert'
2024-01-12 14:38:51 For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500
2024-01-12 14:38:51 [2024-01-12 13:38:51,508] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[e04e9aab-5e08-4364-921b-767688081c31] raised unexpected: ConsumerError("Тестовий документ.docx: Error occurred while consuming document Тестовий документ.docx: Error while converting document to PDF: Server error '500 Internal Server Error' for url 'http://gotenberg:3000/forms/libreoffice/convert'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500")
2024-01-12 14:38:51 Traceback (most recent call last):
2024-01-12 14:38:51   File "/usr/src/paperless/src/paperless_tika/parsers.py", line 104, in convert_to_pdf
2024-01-12 14:38:51     response = route.run()
2024-01-12 14:38:51                ^^^^^^^^^^^
2024-01-12 14:38:51   File "/usr/local/lib/python3.11/site-packages/gotenberg_client/_base.py", line 74, in run
2024-01-12 14:38:51     resp.raise_for_status()
2024-01-12 14:38:51   File "/usr/local/lib/python3.11/site-packages/httpx/_models.py", line 758, in raise_for_status
2024-01-12 14:38:51     raise HTTPStatusError(message, request=request, response=self)
2024-01-12 14:38:51 httpx.HTTPStatusError: Server error '500 Internal Server Error' for url 'http://gotenberg:3000/forms/libreoffice/convert'
2024-01-12 14:38:51 For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500
2024-01-12 14:38:51 
2024-01-12 14:38:51 The above exception was the direct cause of the following exception:
2024-01-12 14:38:51 
2024-01-12 14:38:51 Traceback (most recent call last):
2024-01-12 14:38:51   File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 349, in main_wrap
2024-01-12 14:38:51     raise exc_info[1]
2024-01-12 14:38:51   File "/usr/src/paperless/src/documents/consumer.py", line 446, in try_consume_file
2024-01-12 14:38:51     document_parser.parse(self.path, mime_type, self.filename)
2024-01-12 14:38:51   File "/usr/src/paperless/src/paperless_tika/parsers.py", line 82, in parse
2024-01-12 14:38:51     self.archive_path = self.convert_to_pdf(document_path, file_name)
2024-01-12 14:38:51                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-12 14:38:51   File "/usr/src/paperless/src/paperless_tika/parsers.py", line 111, in convert_to_pdf
2024-01-12 14:38:51     raise ParseError(
2024-01-12 14:38:51 documents.parsers.ParseError: Error while converting document to PDF: Server error '500 Internal Server Error' for url 'http://gotenberg:3000/forms/libreoffice/convert'
2024-01-12 14:38:51 For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500
2024-01-12 14:38:51 
2024-01-12 14:38:51 The above exception was the direct cause of the following exception:
2024-01-12 14:38:51 
2024-01-12 14:38:51 Traceback (most recent call last):
2024-01-12 14:38:51   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
2024-01-12 14:38:51     R = retval = fun(*args, **kwargs)
2024-01-12 14:38:51                  ^^^^^^^^^^^^^^^^^^^^
2024-01-12 14:38:51   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
2024-01-12 14:38:51     return self.run(*args, **kwargs)
2024-01-12 14:38:51            ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-12 14:38:51   File "/usr/src/paperless/src/documents/tasks.py", line 167, in consume_file
2024-01-12 14:38:51     document = Consumer().try_consume_file(
2024-01-12 14:38:51                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-12 14:38:51   File "/usr/src/paperless/src/documents/consumer.py", line 474, in try_consume_file
2024-01-12 14:38:51     self._fail(
2024-01-12 14:38:51   File "/usr/src/paperless/src/documents/consumer.py", line 115, in _fail
2024-01-12 14:38:51     raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
2024-01-12 14:38:51 documents.consumer.ConsumerError: Тестовий документ.docx: Error occurred while consuming document Тестовий документ.docx: Error while converting document to PDF: Server error '500 Internal Server Error' for url 'http://gotenberg:3000/forms/libreoffice/convert'
2024-01-12 14:38:51 For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500
2024-01-12 14:40:00 [2024-01-12 13:40:00,026] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
2024-01-12 14:40:00 [2024-01-12 13:40:00,041] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[4b523828-0717-414c-9ab5-6d539514a52d] received
2024-01-12 14:40:00 [2024-01-12 13:40:00,334] [INFO] [celery.app.trace] Task paperless_mail.tasks.process_mail_accounts[4b523828-0717-414c-9ab5-6d539514a52d] succeeded in 0.21159710000210907s: 'No new documents were added.'
```

### Paperless-ngx version

based on latest but rebuild for support 

### Host OS

docker desktop on windows wsl

### Installation method

Docker - official image

### Configuration changes

changes ub docker file (added tesseract-ocr packages) and small changes in docker-compose.env (see above)

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by alexmaret** [comment]
This seems to be a Gotenberg problem. You need to check the logs of your Gotenberg container.

**Comment by stumpylog** [comment]
An http 500 is gotenberg failing, not paperless. I know they just released v8, which had some changes for file name handling.  You could try that, or search their issues.
