### ISSUE TITLE
[BUG] consuming of pdf fails during OCR for no obvious reason 

### ISSUE THREAD

**Issue by s-martin** [paperless-ngx/paperless-ngx#539]
**Describe the bug**
When I add a PDF consumption fails with the following error.
The file isn’t anything special and similar files were consumed without errors. It’s an insurance statement, so I can’t share it.

```
[2022-03-26 22:43:31,705] [ERROR] [paperless.consumer] Error while consuming document IMG_20131208_0004-neux.pdf: SubprocessOutputError:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_exec/tesseract.py", line 226, in get_deskew
    p = run(args_tesseract, stdout=PIPE, stderr=STDOUT, timeout=timeout, check=True)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/subprocess/__init__.py", line 53, in run
    proc = subprocess_run(args, env=env, **kwargs)
  File "/usr/local/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['tesseract', '-l', 'deu', '--psm', '2', '/tmp/ocrmypdf.io.bftnfu_p/000004_rasterize.png', 'stdout']' returned non-zero exit status 1.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 249, in parse
    ocrmypdf.ocr(**args)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/api.py", line 337, in ocr
    return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 385, in run_pipeline
    exec_concurrent(context, executor)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 274, in exec_concurrent
    executor(
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_concurrent.py", line 82, in __call__
    self._execute(
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/builtin_plugins/concurrency.py", line 135, in _execute
    result = future.result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 192, in exec_page_sync
    ocr_image, preprocess_out = make_intermediate_images(
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 135, in make_intermediate_images
    preprocess_out = preprocess(
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 106, in preprocess
    image = preprocess_deskew(image, page_context)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 481, in preprocess_deskew
    deskew_angle_degrees = ocr_engine.get_deskew(input_file, page_context.options)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/builtin_plugins/tesseract_ocr.py", line 167, in get_deskew
    return tesseract.get_deskew(
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_exec/tesseract.py", line 237, in get_deskew
    raise SubprocessOutputError() from e
ocrmypdf.exceptions.SubprocessOutputError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/consumer.py", line 245, in try_consume_file
    document_parser.parse(self.path, mime_type, self.filename)
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 301, in parse
    raise ParseError(f"{e.__class__.__name__}: {str(e)}")
documents.parsers.ParseError: SubprocessOutputError:
```

**To Reproduce**
1. Add PDF to consumption directory 
2. See error in log

**Expected behavior**
Consumption should work without error.

**Relevant information**
 - Host OS of the machine running paperless: Raspian Bullseye 
 - Browser: Firefox 
 - Version 1.6.0
 - Installation method: docker
 - Any configuration changes you made in `docker-compose.yml`, `docker-compose.env` or `paperless.conf`: OCR language is deu

**Comment by qcasey** [comment]
Possibly similar to #429. Although this process here wasn't killed.

**Comment by s-martin** [comment]
Addition: most of the PDFs work just fine, this is really the only file of over 200, which doesn't work.

**Comment by qcasey** [comment]
I wonder if tesseract gives an error output we could capture, that might prepare us to fix this in the future.

**Comment by stumpylog** [comment]
> I wonder if tesseract gives an error output we could capture, that might prepare us to fix this in the future.

If `settings.DEBUG` is set, we could use (ocrmypdf.Verbosity)[https://ocrmypdf.readthedocs.io/en/latest/api.html#ocrmypdf.Verbosity] to maybe gather more information, though it's unclear what more we'd get.

This might be ocrmypdf/OCRmyPDF#868, as the error is raised during de-skewing, with the same options as that issue.  @s-martin could you tell us if there are blank pages?

**Comment by s-martin** [comment]
Actually yes the last page is blank.

**Comment by stumpylog** [comment]
If I run the file attached to the above ocrmypdf issue, it generates the same traceback.  

For the moment, I think a solution is removing the blank page

**Comment by s-martin** [comment]
> If I run the file attached to the above ocrmypdf issue, it generates the same traceback.
> 
> For the moment, I think a solution is removing the blank page

Thanks, removing the blank page at the end of the document helped.

**Comment by jase31** [comment]
I find with paperless NG that certain files just will not consume. Tried compressing to a smaller pdf. Loading a "reprinting" to a pdf etc, but just will not consume. Other files consume just fine! Never got the bottom of it.
