### ISSUE TITLE
[BUG] Email - outlook365 - socket error: unterminated line: b'* BYE Connection closed.'

### ISSUE THREAD

**Issue by Ruplahlava** [paperless-ngx/paperless-ngx#5427]
### Description

Moved to new server (and version 2.2.1 => 2.3.3) and used importer. Mail functionality is not working now, even after recreating the rule and mail, using microsoft outlook mail with those params:
![image](https://github.com/paperless-ngx/paperless-ngx/assets/4836841/f75fbc34-d8fc-4ada-af91-a888a11de744)
![image](https://github.com/paperless-ngx/paperless-ngx/assets/4836841/35f296e8-dd72-4608-8388-98aa839ac625)

### Steps to reproduce

Set up live/microsoft free account with parameters from screenshot.
Mails are not consumed and there is an error in log

### Webserver logs

```bash
[2024-01-16 14:50:00,006] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
[2024-01-16 14:50:00,035] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[e4caeca7-0271-43ce-bbf9-d2576879f339] received
[2024-01-16 14:50:03,090] [ERROR] [paperless_mail] Rule Ruplahlava.Global: Error while processing rule: UID command error: BAD [b'Command Error. 10']
Traceback (most recent call last):
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 514, in handle_mail_account
    total_processed_files += self._handle_mail_rule(
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 582, in _handle_mail_rule
    for message in messages:
  File "/usr/local/lib/python3.11/site-packages/imap_tools/mailbox.py", line 161, in fetch
    for fetch_item in (self._fetch_in_bulk if bulk else self._fetch_by_one)(uids, message_parts, reverse):  # noqa
  File "/usr/local/lib/python3.11/site-packages/imap_tools/mailbox.py", line 134, in _fetch_in_bulk
    fetch_result = self.client.uid('fetch', ','.join(uid_list), message_parts)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/imaplib.py", line 890, in uid
    typ, dat = self._simple_command(name, command, *args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/imaplib.py", line 1230, in _simple_command
    return self._command_complete(name, self._command(name, *args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/imaplib.py", line 1055, in _command_complete
    raise self.error('%s command error: %s %s' % (name, typ, data))
imaplib.IMAP4.error: UID command error: BAD [b'Command Error. 10']
[2024-01-16 14:50:03,101] [ERROR] [paperless_mail] Error while retrieving mailbox Ruplahlava: command: LOGOUT => socket error: unterminated line: b'* BYE Connection closed.'
[2024-01-16 14:50:03,150] [INFO] [celery.app.trace] Task paperless_mail.tasks.process_mail_accounts[e4caeca7-0271-43ce-bbf9-d2576879f339] succeeded in 3.088049043995852s: 'No new documents were added.'
```

### Paperless-ngx version

2.3.3

### Host OS

unraid/amd64

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
Nothing about mail importing or the base library used for it has changed in any signifcant way recently.  That rather looks like the server has decided to terminate the connection.  I can't reproduce this error.

I know Microsoft/Office email has been the source of a lot of issues.  They really don't appear to support standards,  In my opinion, to force people into the web app for tracking.

**Comment by Ruplahlava** [comment]
ok, so i just downgraded to 2.2.1 again and its working fine there

**Comment by stumpylog** [comment]
They must not support fetching many messages at once.  I would suggest you look at your filters to restrict what messages are being fetched at once.  Microsoft might have some limit they decided on

**Comment by Ruplahlava** [comment]
I have one filter - the one shared in original message. I cant see any concurrency limitation mentioned in the setup. Do you mean the number of days, or there is something i am missing?

**Comment by stumpylog** [comment]
I don't know what limits Microsoft may be applying.  But 720 days is going to be a lot of messages, probably more than Microsoft or anyone will support grabbing at once.  I would suggest filtering by the from, to or subject at minimum.
