### ISSUE TITLE
[BUG] DigitalSignatureError when processing documents

### ISSUE THREAD

**Issue by clemensrieder** [paperless-ngx/paperless-ngx#5505]
### Description

I am adding invoices from Uber. Unfortunately, the invoices seem to be digitally signed because I am getting an error when the documents are consumed. I have looked for the error in the OCRmyPDF repository, but there seem to be [no issues](https://github.com/ocrmypdf/OCRmyPDF/issues?q=DigitalSignatureError+).

When uploading files to paperless, I do not care about any invalid signatures. So maybe there is a fix to override the error and force the document to be consumed? This would be really helpful!

### Steps to reproduce

Try to consume a signed document.

### Webserver logs

```bash
[2024-01-22 21:33:17,504] [INFO] [paperless.consumer] Consuming 75dafd8a-e7a7-59e1-adfe-c9b243ad63c1_8348dbba-bbac-59fe-8982-b24b749fc80a.pdf

[2024-01-22 21:33:17,507] [DEBUG] [paperless.consumer] Detected mime type: application/pdf

[2024-01-22 21:33:17,510] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser

[2024-01-22 21:33:17,514] [DEBUG] [paperless.consumer] Parsing 75dafd8a-e7a7-59e1-adfe-c9b243ad63c1_8348dbba-bbac-59fe-8982-b24b749fc80a.pdf...

[2024-01-22 21:33:17,662] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-ngxut41afa9/75dafd8a-e7a7-59e1-adfe-c9b243ad63c1_8348dbba-bbac-59fe-8982-b24b749fc80a.pdf'), 'output_file': PosixPath('/tmp/paperless/paperless-tj23xze4/archive.pdf'), 'use_threads': True, 'jobs': 4, 'language': 'deu+eng', 'output_type': 'pdf', 'progress_bar': False, 'skip_text': True, 'clean': True, 'deskew': True, 'sidecar': PosixPath('/tmp/paperless/paperless-tj23xze4/sidecar.txt')}

[2024-01-22 21:33:17,839] [WARNING] [paperless.parsing.tesseract] Encountered an error while running OCR: Input PDF has a digital signature. OCR would alter the document,

invalidating the signature.

. Attempting force OCR to get the text.

[2024-01-22 21:33:17,839] [DEBUG] [paperless.parsing.tesseract] Fallback: Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-ngxut41afa9/75dafd8a-e7a7-59e1-adfe-c9b243ad63c1_8348dbba-bbac-59fe-8982-b24b749fc80a.pdf'), 'output_file': PosixPath('/tmp/paperless/paperless-tj23xze4/archive-fallback.pdf'), 'use_threads': True, 'jobs': 4, 'language': 'deu+eng', 'output_type': 'pdf', 'progress_bar': False, 'force_ocr': True, 'clean': True, 'deskew': True, 'sidecar': PosixPath('/tmp/paperless/paperless-tj23xze4/sidecar-fallback.txt')}

[2024-01-22 21:33:18,012] [ERROR] [paperless.consumer] Error occurred while consuming document 75dafd8a-e7a7-59e1-adfe-c9b243ad63c1_8348dbba-bbac-59fe-8982-b24b749fc80a.pdf: DigitalSignatureError: Input PDF has a digital signature. OCR would alter the document,

invalidating the signature.

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 353, in parse

    ocrmypdf.ocr(**args)

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/api.py", line 375, in ocr

    return run_pipeline(options=options, plugin_manager=plugin_manager)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 225, in run_pipeline

    return _run_pipeline(options, plugin_manager)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 189, in _run_pipeline

    validate_pdfinfo_options(context)

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipeline.py", line 202, in validate_pdfinfo_options

    raise DigitalSignatureError()

ocrmypdf.exceptions.DigitalSignatureError: Input PDF has a digital signature. OCR would alter the document,

invalidating the signature.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 404, in parse

    ocrmypdf.ocr(**args)

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/api.py", line 375, in ocr

    return run_pipeline(options=options, plugin_manager=plugin_manager)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 225, in run_pipeline

    return _run_pipeline(options, plugin_manager)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 189, in _run_pipeline

    validate_pdfinfo_options(context)

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipeline.py", line 202, in validate_pdfinfo_options

    raise DigitalSignatureError()

ocrmypdf.exceptions.DigitalSignatureError: Input PDF has a digital signature. OCR would alter the document,

invalidating the signature.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 349, in main_wrap

    raise exc_info[1]

  File "/usr/src/paperless/src/documents/consumer.py", line 516, in try_consume_file

    document_parser.parse(self.working_copy, mime_type, self.filename)

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 416, in parse

    raise ParseError(f"{e.__class__.__name__}: {e!s}") from e

documents.parsers.ParseError: DigitalSignatureError: Input PDF has a digital signature. OCR would alter the document,

invalidating the signature.
```

### Paperless-ngx version

2.4.0

### Host OS

Debian

### Installation method

Docker - official image

### Configuration changes

No relevant changes to configuration

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Please search

**Comment by clemensrieder** [comment]
Uff sorry - I forgot to remove the is:open filter 🙈

**Comment by benley** [comment]
breadcrumb trail for posterity: https://github.com/paperless-ngx/paperless-ngx/discussions/4705
