### ISSUE TITLE
[BUG] Server Error 500 while trying to sign in with 3rd party idp

### ISSUE THREAD

**Issue by alxvlkr** [paperless-ngx/paperless-ngx#5837]
### Description

When i try to sign in with a configured idp...
![1](https://github.com/paperless-ngx/paperless-ngx/assets/108154895/a1b401f6-2d66-4a89-92b9-9bb8128c2e05)
![2](https://github.com/paperless-ngx/paperless-ngx/assets/108154895/562ecffd-95ad-4fe7-a363-7b81a312fed0)
![3](https://github.com/paperless-ngx/paperless-ngx/assets/108154895/bab73679-84ad-4eb5-9053-9a655047f306)

I get a server error 500
![4](https://github.com/paperless-ngx/paperless-ngx/assets/108154895/8ea6d9dc-64af-4100-baa1-c21dd5c5aee8)

paperless.conf changes:
```
PAPERLESS_REDIS=redis://localhost:6379
PAPERLESS_DBHOST=localhost
PAPERLESS_DBPORT=5432
PAPERLESS_DBNAME=paperlessdb
PAPERLESS_DBUSER=paperless
PAPERLESS_DBPASS=xxxxxxxxxxxxxxxx

PAPERLESS_CONSUMPTION_DIR=/mnt/paperless/consume
PAPERLESS_DATA_DIR=/opt/paperless/data
PAPERLESS_MEDIA_ROOT=/mnt/paperless/media

PAPERLESS_SECRET_KEY=xxxxxxxxxxxxxxx
PAPERLESS_URL=https://dms.alxvlkr.xyz

PAPERLESS_AUDIT_LOG_ENABLED=false

PAPERLESS_EMAIL_HOST=xxxxxxxxx
PAPERLESS_EMAIL_PORT=465
PAPERLESS_EMAIL_HOST_USER=xxxxxxxxxxx
PAPERLESS_EMAIL_HOST_PASSWORD=xxxxxxxx
PAPERLESS_EMAIL_USE_TLS=false
PAPERLESS_EMAIL_USE_SSL=true

PAPERLESS_ENABLE_HTTP_REMOTE_USER=false

PAPERLESS_APPS=allauth.socialaccount.providers.openid_connect,allauth.socialaccount.providers.google
PAPERLESS_SOCIALACCOUNT_PROVIDERS={"openid_connect": {"APPS": [{"provider_id": "zitadel","name": "Zitadel","client_id": "xxxxxxxxxxxxxx","secret": "xxxxxxxxxxxxxxx","settings": { "server_url": "https://auth.xxxxx.xxx/.well-known/openid-configuration"}}]}}

PAPERLESS_SOCIALACCOUNT_ALLOW_SIGNUPS=false
PAPERLESS_PROXY_SSL_HEADER='["HTTP_X_FORWARDED_PROTO", "https"]'

PAPERLESS_CONSUMER_POLLING=10
PAPERLESS_CONSUMER_POLLING_RETRY_COUNT=20
```

### Steps to reproduce

1. set up a custom idp (openid connect or google in my case)
2. try to connect your 3rd party account to your existing paperless account

### Webserver logs

```bash
Zitadel error:

Feb 20 21:17:01 paperless-ngx gunicorn[78106]: [2024-02-20 20:17:01,132] [ERROR] [django.request] Internal Server Error: /accounts/oidc/zitadel/login/callback/
Feb 20 21:17:01 paperless-ngx gunicorn[78106]: Traceback (most recent call last):
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/django/db/backends/utils.py", line 89, in _execute
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:     return self.cursor.execute(sql, params)
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 20 21:17:01 paperless-ngx gunicorn[78106]: psycopg2.errors.FeatureNotSupported: conversion between UTF8 and SQL_ASCII is not supported
Feb 20 21:17:01 paperless-ngx gunicorn[78106]: LINE 1: ... '2024-02-20T20:17:01.130519+00:00'::timestamptz, '{"sub": "...
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:                                                              ^
Feb 20 21:17:01 paperless-ngx gunicorn[78106]: The above exception was the direct cause of the following exception:
Feb 20 21:17:01 paperless-ngx gunicorn[78106]: Traceback (most recent call last):
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/asgiref/sync.py", line 534, in thread_handler
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:     raise exc_info[1]
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/django/core/handlers/exception.py", line 42, in inner
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:     response = await get_response(request)
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/asgiref/sync.py", line 534, in thread_handler
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:     raise exc_info[1]
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/django/core/handlers/base.py", line 253, in _get_response_async
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:     response = await wrapped_callback(
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:                ^^^^^^^^^^^^^^^^^^^^^^^
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/asgiref/sync.py", line 479, in __call__
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:     ret: _R = await loop.run_in_executor(
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/asgiref/current_thread_executor.py", line 40, in run
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:     result = self.fn(*self.args, **self.kwargs)
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/asgiref/sync.py", line 538, in thread_handler
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:     return func(*args, **kwargs)
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:            ^^^^^^^^^^^^^^^^^^^^^
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/allauth/socialaccount/providers/openid_connect/views.py", line 74, in callback
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:     return view(request)
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:            ^^^^^^^^^^^^^
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/allauth/socialaccount/providers/oauth2/views.py", line 87, in view
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:     return self.dispatch(request, *args, **kwargs)
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/allauth/socialaccount/providers/oauth2/views.py", line 171, in dispatch
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:     return complete_social_login(request, login)
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/allauth/socialaccount/helpers.py", line 218, in complete_social_login
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:     return _add_social_account(request, sociallogin)
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/allauth/socialaccount/helpers.py", line 193, in _add_social_account
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:     sociallogin.connect(request, request.user)
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/allauth/socialaccount/models.py", line 212, in connect
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:     self.save(request, connect=True)
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/allauth/socialaccount/models.py", line 267, in save
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:     self.account.save()
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/django/db/models/base.py", line 814, in save
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:     self.save_base(
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/django/db/models/base.py", line 877, in save_base
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:     updated = self._save_table(
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:               ^^^^^^^^^^^^^^^^^
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/django/db/models/base.py", line 1020, in _save_table
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:     results = self._do_insert(
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:               ^^^^^^^^^^^^^^^^
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/django/db/models/base.py", line 1061, in _do_insert
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:     return manager._insert(
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:            ^^^^^^^^^^^^^^^^
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/django/db/models/manager.py", line 87, in manager_method
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:     return getattr(self.get_queryset(), name)(*args, **kwargs)
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/django/db/models/query.py", line 1805, in _insert
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:     return query.get_compiler(using=using).execute_sql(returning_fields)
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:     cursor.execute(sql, params)
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/django/db/backends/utils.py", line 67, in execute
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:     return self._execute_with_wrappers(
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:     return executor(sql, params, many, context)
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/django/db/backends/utils.py", line 84, in _execute
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:     with self.db.wrap_database_errors:
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/django/db/utils.py", line 91, in __exit__
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:     raise dj_exc_value.with_traceback(traceback) from exc_value
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/django/db/backends/utils.py", line 89, in _execute
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:     return self.cursor.execute(sql, params)
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 20 21:17:01 paperless-ngx gunicorn[78106]: django.db.utils.NotSupportedError: conversion between UTF8 and SQL_ASCII is not supported
Feb 20 21:17:01 paperless-ngx gunicorn[78106]: LINE 1: ... '2024-02-20T20:17:01.130519+00:00'::timestamptz, '{"sub": "...
Feb 20 21:17:01 paperless-ngx gunicorn[78106]:    

Google error:
Feb 20 20:44:49 paperless-ngx gunicorn[78106]: [2024-02-20 19:44:49,062] [ERROR] [django.request] Internal Server Error: /accounts/google/login/callback/
Feb 20 20:44:49 paperless-ngx gunicorn[78106]: Traceback (most recent call last):
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/django/db/backends/utils.py", line 89, in _execute
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:     return self.cursor.execute(sql, params)
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 20 20:44:49 paperless-ngx gunicorn[78106]: psycopg2.errors.FeatureNotSupported: conversion between UTF8 and SQL_ASCII is not supported
Feb 20 20:44:49 paperless-ngx gunicorn[78106]: LINE 1: ... '2024-02-20T19:44:49.058972+00:00'::timestamptz, '{"iss": "...
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:                                                              ^
Feb 20 20:44:49 paperless-ngx gunicorn[78106]: The above exception was the direct cause of the following exception:
Feb 20 20:44:49 paperless-ngx gunicorn[78106]: Traceback (most recent call last):
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/asgiref/sync.py", line 534, in thread_handler
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:     raise exc_info[1]
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/django/core/handlers/exception.py", line 42, in inner
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:     response = await get_response(request)
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/asgiref/sync.py", line 534, in thread_handler
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:     raise exc_info[1]
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/django/core/handlers/base.py", line 253, in _get_response_async
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:     response = await wrapped_callback(
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:                ^^^^^^^^^^^^^^^^^^^^^^^
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/asgiref/sync.py", line 479, in __call__
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:     ret: _R = await loop.run_in_executor(
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/asgiref/current_thread_executor.py", line 40, in run
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:     result = self.fn(*self.args, **self.kwargs)
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/asgiref/sync.py", line 538, in thread_handler
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:     return func(*args, **kwargs)
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:            ^^^^^^^^^^^^^^^^^^^^^
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/allauth/socialaccount/providers/oauth2/views.py", line 87, in view
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:     return self.dispatch(request, *args, **kwargs)
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/allauth/socialaccount/providers/oauth2/views.py", line 171, in dispatch
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:     return complete_social_login(request, login)
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/allauth/socialaccount/helpers.py", line 218, in complete_social_login
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:     return _add_social_account(request, sociallogin)
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/allauth/socialaccount/helpers.py", line 193, in _add_social_account
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:     sociallogin.connect(request, request.user)
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/allauth/socialaccount/models.py", line 212, in connect
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:     self.save(request, connect=True)
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/allauth/socialaccount/models.py", line 267, in save
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:     self.account.save()
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/django/db/models/base.py", line 814, in save
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:     self.save_base(
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/django/db/models/base.py", line 877, in save_base
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:     updated = self._save_table(
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:               ^^^^^^^^^^^^^^^^^
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/django/db/models/base.py", line 1020, in _save_table
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:     results = self._do_insert(
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:               ^^^^^^^^^^^^^^^^
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/django/db/models/base.py", line 1061, in _do_insert
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:     return manager._insert(
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:            ^^^^^^^^^^^^^^^^
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/django/db/models/manager.py", line 87, in manager_method
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:     return getattr(self.get_queryset(), name)(*args, **kwargs)
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/django/db/models/query.py", line 1805, in _insert
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:     return query.get_compiler(using=using).execute_sql(returning_fields)
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:     cursor.execute(sql, params)
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/django/db/backends/utils.py", line 67, in execute
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:     return self._execute_with_wrappers(
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:     return executor(sql, params, many, context)
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/django/db/backends/utils.py", line 84, in _execute
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:     with self.db.wrap_database_errors:
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/django/db/utils.py", line 91, in __exit__
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:     raise dj_exc_value.with_traceback(traceback) from exc_value
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:   File "/usr/local/lib/python3.11/dist-packages/django/db/backends/utils.py", line 89, in _execute
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:     return self.cursor.execute(sql, params)
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 20 20:44:49 paperless-ngx gunicorn[78106]: django.db.utils.NotSupportedError: conversion between UTF8 and SQL_ASCII is not supported
Feb 20 20:44:49 paperless-ngx gunicorn[78106]: LINE 1: ... '2024-02-20T19:44:49.058972+00:00'::timestamptz, '{"iss": "...
Feb 20 20:44:49 paperless-ngx gunicorn[78106]:
```

### Paperless-ngx version

2.5.3

### Host OS

Debian 12

### Installation method

Bare metal

### Browser

Chrome

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
This looks like an allauth issue, not paperless. Our code isnt even in that traceback.

Perhaps its related to your db encoding

**Comment by alxvlkr** [comment]
@shamoon Any advice how to get it working?
I deployed paperless with this script: https://raw.githubusercontent.com/tteck/Proxmox/main/ct/paperless-ngx.sh

**Comment by shamoon** [comment]
that’s not our script. I’d be googling it just the same as you. Maybe using utf8 for the db

since others aren’t experiencing this it must be related to your specific setup

**Comment by alxvlkr** [comment]
@shamoon i've just converted my db to utf8 and now everything works :)

**Comment by shamoon** [comment]
Glad to hear, appreciate the follow-up in case others run into it
