### ISSUE TITLE
[BUG] [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by sjau** [paperless-ngx/paperless-ngx#5892]
### Description

When I put pdfs into the consumption folder, paperless-ngx does start to process them but fails immediately with above error.

```
[2024-02-25 17:51:01,781] [INFO] [celery.worker.strategy] Task documents.tasks.consume_file[f843f1a5-9751-4e53-a250-766012e0692d] received
[2024-02-25 17:51:01,783] [DEBUG] [celery.pool] TaskPool: Apply <function fast_trace_task at 0x7f52b5ebdda0> (args:('documents.tasks.consume_file', 'f843f1a5-9751-4e53-a250-766012e0692d', {'lang': 'py', 'task': 'documents.tasks.consume_file', 'id': 'f843f1a5-9751-4e53-a250-766012e0692d', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'f843f1a5-9751-4e53-a250-766012e0692d', 'parent_id': None, 'argsrepr': "(ConsumableDocument(source=<DocumentSource.ConsumeFolder: 1>, original_file=PosixPath('/data/samba/VPN-Scanner/Paperless/QR_Klientengeldkonto_generisch.pdf'), mailrule_id=None, mime_type='application/pdf'), DocumentMetadataOverrides(filename=None, title=None, correspondent_id=None, document_type_id=None, tag_ids=None, storage_path_id=None, created=None, asn=None, owner_id=None, view_users=None, view_groups=None, change_users=None, change_groups=None, custom_field_ids=None))", 'kwargsrepr': '{}', 'origin': 'gen4432@server', 'ignore_result': False, 'replaced_task_nesting': 0, 'stamped_headers': None, 'stamps': {}, 'properties':... kwargs:{})
[2024-02-25 17:51:01,986] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[f843f1a5-9751-4e53-a250-766012e0692d] raised unexpected: FileNotFoundError(2, 'No such file or directory')
Traceback (most recent call last):
  File "/nix/store/3wjw39szdw31dxqhibb3253n5c7jxy1f-python3.11-celery-5.3.6/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/3wjw39szdw31dxqhibb3253n5c7jxy1f-python3.11-celery-5.3.6/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/nvhadwy11j9phwxmy8qw00pbly2npdks-paperless-ngx-2.5.2/lib/paperless-ngx/src/documents/tasks.py", line 122, in consume_file
    ) as status_mgr, TemporaryDirectory(dir=settings.SCRATCH_DIR) as tmp_dir:
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/y027d3bvlaizbri04c1bzh28hqd6lj01-python3-3.11.7/lib/python3.11/tempfile.py", line 854, in __init__
    self.name = mkdtemp(suffix, prefix, dir)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/y027d3bvlaizbri04c1bzh28hqd6lj01-python3-3.11.7/lib/python3.11/tempfile.py", line 368, in mkdtemp
    _os.mkdir(file, 0o700)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/paperless/tmpy0xyeph2'
```

### Steps to reproduce

1. Put file in the consumption dir.
2. Error appears in paperless-ngx gui and log excerpt is above.

### Webserver logs

```bash
QR_Klientengeldkonto_generisch.pdf	Feb 25, 2024	
[Errno 2] No such file or directory: '/tmp/paperle…
[Errno 2] No such file or directory: '/tmp/paperless/tmpy0xyeph2'
```

### Paperless-ngx version

2.5.2

### Host OS

NixOS x861_64

### Installation method

Bare metal

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
This has been reported before, often by nix users.  The services must share the same filesystem, especially the temporary directory. 
Hardening and security things seem to often prevent that and you will need to figure out which thing is preventing it.

**Comment by sjau** [comment]
So you can't use zfs with a dataset for permanent storage on /data and use a different dataset for /tmp ?

**Comment by stumpylog** [comment]
That's fine. The services just need to have the same temporary directory

**Comment by sjau** [comment]
I did not set any different temporary directory....

**Comment by sjau** [comment]
It used to work and since I updated, it doesn't work anymore.
