### ISSUE TITLE
[BUG] ASN recognition crash with ZXing when EAN barcode is present

### ISSUE THREAD

**Issue by BenoitAnastay** [paperless-ngx/paperless-ngx#5936]
### Description

Barcode recognition crash when EAN code is present (ZXing backend)

When there is an ASN QR Code the document is imported correctly 

I haven't tried to replicate this with PYZBAR

### Steps to reproduce

1. enable ASN bacodes with ZXingx
2. Consume a file with EAN barcode
[European.Article.Number.Wikipedia.pdf](https://github.com/paperless-ngx/paperless-ngx/files/14433535/European.Article.Number.Wikipedia.pdf)

### Webserver logs

```bash
[2024-02-28 12:02:23,479] [INFO] [celery.worker.strategy] Task documents.tasks.consume_file[be7e5db2-26aa-43d0-949c-99c151c2428b] received
 celery@44849f5f-paperless-ngx:ForkPoolWorker-2]: ./core/src/Result.cpp:140: bool ZXing::Result::operator==(const ZXing::Result&) const: Assertion `lineCount() == 1' failed.
[2024-02-28 12:02:28,757: ERROR/MainProcess] Process 'ForkPoolWorker-2' pid:5188 exited with 'signal 6 (SIGABRT)'
[2024-02-28 12:02:28,807] [ERROR] [celery.worker.request] Task handler raised error: WorkerLostError('Worker exited prematurely: signal 6 (SIGABRT) Job: 1.')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/billiard/pool.py", line 1264, in mark_as_worker_lost
    raise WorkerLostError(
billiard.einfo.ExceptionWithTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/billiard/pool.py", line 1264, in mark_as_worker_lost
    raise WorkerLostError(
billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 6 (SIGABRT) Job: 1.
"""
```

### Paperless-ngx version

2.5.4

### Host OS

Home Assistant OS ARM64

### Installation method

Other (please describe above)

### Configuration changes

PAPERLESS_CONSUMER_BARCODE_SCANNER=ZXing

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
Feel free to open an issue upstream: https://github.com/zxing-cpp/zxing-cpp/issues
