### ISSUE TITLE
[BUG] Adding a correspondent - duplicate key value violates unique constraint "documents_sender_pkey"

### ISSUE THREAD

**Issue by rust84** [paperless-ngx/paperless-ngx#5983]
### Description

I am using paperless-ngx for some time. I am currently running the latest release (2.5.4 at time of writing) and use Postgres 16 for the database. Has been working well for the last 18 months.

Today when I went to add a new correspondent I encountered the error below. 

I've tried multiple correspondent names including random letters to be absolutely sure they do not already exist. I am not sure when this error started occurring to be honest. I briefly tried downgrading to 2.5.1 and encounter the same issue.

### Steps to reproduce

1. Navigate to Correspondents
2. Click create
3. Enter a name and leave rest as defaults
4. Click Save

### Webserver logs

```bash
paperless-597d8fb6bb-rdflq paperless [2024-03-03 11:17:20,908] [ERROR] [django.request] Internal Server Error: /api/correspondents/
paperless-597d8fb6bb-rdflq paperless Traceback (most recent call last):
paperless-597d8fb6bb-rdflq paperless   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
paperless-597d8fb6bb-rdflq paperless     return self.cursor.execute(sql, params)
paperless-597d8fb6bb-rdflq paperless            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-597d8fb6bb-rdflq paperless psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "documents_sender_pkey"
paperless-597d8fb6bb-rdflq paperless DETAIL:  Key (id)=(9) already exists.
paperless-597d8fb6bb-rdflq paperless
paperless-597d8fb6bb-rdflq paperless
paperless-597d8fb6bb-rdflq paperless The above exception was the direct cause of the following exception:
paperless-597d8fb6bb-rdflq paperless
paperless-597d8fb6bb-rdflq paperless Traceback (most recent call last):
paperless-597d8fb6bb-rdflq paperless   File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
paperless-597d8fb6bb-rdflq paperless     raise exc_info[1]
paperless-597d8fb6bb-rdflq paperless   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 42, in inner
paperless-597d8fb6bb-rdflq paperless     response = await get_response(request)
paperless-597d8fb6bb-rdflq paperless                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-597d8fb6bb-rdflq paperless   File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
paperless-597d8fb6bb-rdflq paperless     raise exc_info[1]
paperless-597d8fb6bb-rdflq paperless   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
paperless-597d8fb6bb-rdflq paperless     response = await wrapped_callback(
paperless-597d8fb6bb-rdflq paperless                ^^^^^^^^^^^^^^^^^^^^^^^
paperless-597d8fb6bb-rdflq paperless   File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 479, in __call__
paperless-597d8fb6bb-rdflq paperless     ret: _R = await loop.run_in_executor(
paperless-597d8fb6bb-rdflq paperless               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-597d8fb6bb-rdflq paperless   File "/usr/local/lib/python3.11/site-packages/asgiref/current_thread_executor.py", line 40, in run
paperless-597d8fb6bb-rdflq paperless     result = self.fn(*self.args, **self.kwargs)
paperless-597d8fb6bb-rdflq paperless              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-597d8fb6bb-rdflq paperless   File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 538, in thread_handler
paperless-597d8fb6bb-rdflq paperless     return func(*args, **kwargs)
paperless-597d8fb6bb-rdflq paperless            ^^^^^^^^^^^^^^^^^^^^^
paperless-597d8fb6bb-rdflq paperless   File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
paperless-597d8fb6bb-rdflq paperless     return view_func(*args, **kwargs)
paperless-597d8fb6bb-rdflq paperless            ^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-597d8fb6bb-rdflq paperless   File "/usr/local/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
paperless-597d8fb6bb-rdflq paperless     return self.dispatch(request, *args, **kwargs)
paperless-597d8fb6bb-rdflq paperless            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-597d8fb6bb-rdflq paperless   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
paperless-597d8fb6bb-rdflq paperless     response = self.handle_exception(exc)
paperless-597d8fb6bb-rdflq paperless                ^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-597d8fb6bb-rdflq paperless   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
paperless-597d8fb6bb-rdflq paperless     self.raise_uncaught_exception(exc)
paperless-597d8fb6bb-rdflq paperless   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
paperless-597d8fb6bb-rdflq paperless     raise exc
paperless-597d8fb6bb-rdflq paperless   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
paperless-597d8fb6bb-rdflq paperless     response = handler(request, *args, **kwargs)
paperless-597d8fb6bb-rdflq paperless                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-597d8fb6bb-rdflq paperless   File "/usr/local/lib/python3.11/site-packages/rest_framework/mixins.py", line 19, in create
paperless-597d8fb6bb-rdflq paperless     self.perform_create(serializer)
paperless-597d8fb6bb-rdflq paperless   File "/usr/local/lib/python3.11/site-packages/rest_framework/mixins.py", line 24, in perform_create
paperless-597d8fb6bb-rdflq paperless     serializer.save()
paperless-597d8fb6bb-rdflq paperless   File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 212, in save
paperless-597d8fb6bb-rdflq paperless     self.instance = self.create(validated_data)
paperless-597d8fb6bb-rdflq paperless                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-597d8fb6bb-rdflq paperless   File "/usr/src/paperless/src/documents/serialisers.py", line 256, in create
paperless-597d8fb6bb-rdflq paperless     instance = super().create(validated_data)
paperless-597d8fb6bb-rdflq paperless                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-597d8fb6bb-rdflq paperless   File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 962, in create
paperless-597d8fb6bb-rdflq paperless     instance = ModelClass._default_manager.create(**validated_data)
paperless-597d8fb6bb-rdflq paperless                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-597d8fb6bb-rdflq paperless   File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
paperless-597d8fb6bb-rdflq paperless     return getattr(self.get_queryset(), name)(*args, **kwargs)
paperless-597d8fb6bb-rdflq paperless            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-597d8fb6bb-rdflq paperless   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 658, in create
paperless-597d8fb6bb-rdflq paperless     obj.save(force_insert=True, using=self.db)
paperless-597d8fb6bb-rdflq paperless   File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 814, in save
paperless-597d8fb6bb-rdflq paperless     self.save_base(
paperless-597d8fb6bb-rdflq paperless   File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 877, in save_base
paperless-597d8fb6bb-rdflq paperless     updated = self._save_table(
paperless-597d8fb6bb-rdflq paperless               ^^^^^^^^^^^^^^^^^
paperless-597d8fb6bb-rdflq paperless   File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 1020, in _save_table
paperless-597d8fb6bb-rdflq paperless     results = self._do_insert(
paperless-597d8fb6bb-rdflq paperless               ^^^^^^^^^^^^^^^^
paperless-597d8fb6bb-rdflq paperless   File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 1061, in _do_insert
paperless-597d8fb6bb-rdflq paperless     return manager._insert(
paperless-597d8fb6bb-rdflq paperless            ^^^^^^^^^^^^^^^^
paperless-597d8fb6bb-rdflq paperless   File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
paperless-597d8fb6bb-rdflq paperless     return getattr(self.get_queryset(), name)(*args, **kwargs)
paperless-597d8fb6bb-rdflq paperless            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-597d8fb6bb-rdflq paperless   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1805, in _insert
paperless-597d8fb6bb-rdflq paperless     return query.get_compiler(using=using).execute_sql(returning_fields)
paperless-597d8fb6bb-rdflq paperless            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-597d8fb6bb-rdflq paperless   File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
paperless-597d8fb6bb-rdflq paperless     cursor.execute(sql, params)
paperless-597d8fb6bb-rdflq paperless   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
paperless-597d8fb6bb-rdflq paperless     return self._execute_with_wrappers(
paperless-597d8fb6bb-rdflq paperless            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-597d8fb6bb-rdflq paperless   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
paperless-597d8fb6bb-rdflq paperless     return executor(sql, params, many, context)
paperless-597d8fb6bb-rdflq paperless            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-597d8fb6bb-rdflq paperless   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
paperless-597d8fb6bb-rdflq paperless     with self.db.wrap_database_errors:
paperless-597d8fb6bb-rdflq paperless   File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
paperless-597d8fb6bb-rdflq paperless     raise dj_exc_value.with_traceback(traceback) from exc_value
paperless-597d8fb6bb-rdflq paperless   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
paperless-597d8fb6bb-rdflq paperless     return self.cursor.execute(sql, params)
paperless-597d8fb6bb-rdflq paperless            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-597d8fb6bb-rdflq paperless django.db.utils.IntegrityError: duplicate key value violates unique constraint "documents_sender_pkey"
paperless-597d8fb6bb-rdflq paperless DETAIL:  Key (id)=(9) already exists.
```
```


### Browser logs

```bash
{"headers":{"normalizedNames":{},"lazyUpdate":null},"status":500,"statusText":"OK","url":"https://paperless.microserver.space/api/correspondents/","ok":false,"name":"HttpErrorResponse","message":"Http failure response for https://paperless.microserver.space/api/correspondents/: 500 OK","error":"\n<!doctype html>\n<html lang=\"en\">\n<head>\n  <title>Server Error (500)</title>\n</head>\n<body>\n  <h1>Server Error (500)</h1><p></p>\n</body>\n</html>\n"}
```
```


### Paperless-ngx version

2.5.4

### Host OS

Talos OS

### Installation method

Docker - official image

### Browser

Chrome

### Configuration changes

n/a

### Other

n/a

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by rust84** [comment]
It looks as though it might be more general. Adding a tag:

```
{"headers":{"normalizedNames":{},"lazyUpdate":null},"status":400,"statusText":"OK","url":"https://paperless.microserver.space/api/tags/","ok":false,"name":"HttpErrorResponse","message":"Http failure response for https://paperless.microserver.space/api/tags/: 400 OK","error":{"error":["Object violates owner / name unique constraint"]}}
```

**Comment by stumpylog** [comment]
It's not something I can reproduce.  Perhaps database corruption?

You can view the database objects from the admin pages or look at an export to see what is in the database.  But it sounds specific to your install.

**Comment by stumpylog** [comment]
Sender is a very old name for correspondent.  I think your database has some problem here, as it appears to be trying to create a new correspondent with an existing ID.  That's very odd and very out of our hands.  Something basic like an auto-incrementing primary key is probably handled by the database, and _maybe_ Django (but I think the database is more likely).

So a fresh creation is what I would do.  Export your existing data, wipe the database, and hope it fixes its issues.
