### ISSUE TITLE
[BUG] When worker container crashes, all pending documents are lost

### ISSUE THREAD

**Issue by coaxial** [paperless-ngx/paperless-ngx#5984]
### Description

Using docker swarm, and when the worker crashes because it choked on a file in the queue, then all pending files are deleted and stay stuck in the queue.

I believe this is because the uploaded and pending files are put in `/tmp` in the worker's container. When it crashes, it is re-created, but the contents of `/tmp` are gone.

The result is that the paperless queue is stuck, doesn't process new files, and loses all the already uploaded files waiting to be processed.

It is easily triggered with barcode parsing enabled and a large PDF document, but it also happens when uploading hundreds of documents at once. Either way the worker crashes.

### Steps to reproduce

1. Enable barcode parsing
2. Upload a few "small" documents (couple of pages)
3. Upload a large document with barcodes in it (on my machine, 25 pages is enough, YMMV)
4. Upload a few more "small" documents
5. Watch the worker choke on the large document because it is runs out of memory
6. See that the worker restarted, the queue still shows the previous documents as pending/processing
7. It stays like that forever, and `/tmp` is empty on the new worker

### Webserver logs

This error repeats many times. I don't know if it's the error that triggered the crash because the logs don't go back beyond this.

```bash
[2024-03-02 16:35:56,145] [ERROR] [paperless.handlers] Setting PaperlessTask started failed

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 289, in ensure_connection

    self.connect()

  File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner

    return func(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 270, in connect

    self.connection = self.get_new_connection(conn_params)

                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner

    return func(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/db/backends/postgresql/base.py", line 275, in get_new_connection

    connection = self.Database.connect(**conn_params)

                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect

    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

psycopg2.OperationalError: connection to server at "db" (10.0.7.9), port 5432 failed: FATAL:  sorry, too many clients already

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/signals/handlers.py", line 695, in task_prerun_handler

    task_instance = PaperlessTask.objects.filter(task_id=task_id).first()

                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1057, in first

    for obj in queryset[:1]:

  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 398, in __iter__

    self._fetch_all()

  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all

    self._result_cache = list(self._iterable_class(self))

                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__

    results = compiler.execute_sql(

              ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1560, in execute_sql

    cursor = self.connection.cursor()

             ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner

    return func(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 330, in cursor

    return self._cursor()

           ^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 306, in _cursor

    self.ensure_connection()

  File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner

    return func(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 288, in ensure_connection

    with self.wrap_database_errors:

  File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__

    raise dj_exc_value.with_traceback(traceback) from exc_value

  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 289, in ensure_connection

    self.connect()

  File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner

    return func(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 270, in connect

    self.connection = self.get_new_connection(conn_params)

                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner

    return func(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/db/backends/postgresql/base.py", line 275, in get_new_connection

    connection = self.Database.connect(**conn_params)

                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect

    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

django.db.utils.OperationalError: connection to server at "db" (10.0.7.9), port 5432 failed: FATAL:  sorry, too many clients already
```

### Paperless-ngx version

2.5.3

### Host OS

What the official docker container uses

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
You can change the folder used as the temporary directory to something napped external to the container.

**Comment by coaxial** [comment]
What is the right way to do it: change paperless' config (I couldn't find an env var matching this setting), or mount `/tmp/paperless` within the container to an external volume/dir?

**Comment by stumpylog** [comment]
Uploaded files are written to a directory created insider PAPERLESS_SCRATCH_DIR, which defaults to `/tmp/paperless` (assuming the system temporary directory is indeed `/tmp`)
