### ISSUE TITLE
[BUG] Classifier not loaded

### ISSUE THREAD

**Issue by meifi** [paperless-ngx/paperless-ngx#6009]
### Description

After Update to 2.6.0 the classifier isn't loaded after restart

### Steps to reproduce

1. Update your paperless ngx to 2.6.0
2. Restart your system
3. Check your logs

### Webserver logs

```bash
[2024-03-05 08:42:38,270] [ERROR] [paperless.api] System status error loading classifier: Classifier not loaded

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/views.py", line 1625, in get

    raise Exception("Classifier not loaded")

Exception: Classifier not loaded

[2024-03-05 08:42:39,388] [DEBUG] [paperless.classifier] Document classification model does not exist (yet), not performing automatic matching.

[2024-03-05 08:42:39,397] [ERROR] [paperless.api] System status error loading classifier: Classifier not loaded

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/views.py", line 1625, in get

    raise Exception("Classifier not loaded")

Exception: Classifier not loaded
```

### Paperless-ngx version

2.6.0

### Host OS

Windows Server 2022 / Docker

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
#6007
