### ISSUE TITLE
[BUG] Failure to import PDF

### ISSUE THREAD

**Issue by cruzzoe** [paperless-ngx/paperless-ngx#6041]
### Description

SubprocessOutputError: Ghostscript PDF/A rendering failed. See logs for more information.

Failure occurs when trying to upload a file. See logs attached full traceback

### Steps to reproduce

Step 1. From Paperless NGX dashboard --> Attempt to upload a file by dragging the pdf from finder into the browser
Upload Completes sucessfully
Failure message appears:

SubprocessOutputError: Ghostscript PDF/A rendering failed. See logs for more information.

Ive never seen this issue before (have been using PNGX for 1 year or so). I suspect the OCR is failing due to kanji in the pdf.

Installed via docker:
  image: ghcr.io/paperless-ngx/paperless-ngx:latest

### Webserver logs

```bash
[2024-03-07 08:24:41,654] [INFO] [paperless.consumer] Consuming REDACTED.pdf

[2024-03-07 08:24:41,658] [DEBUG] [paperless.consumer] Detected mime type: application/pdf

[2024-03-07 08:24:41,662] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser

[2024-03-07 08:24:41,665] [DEBUG] [paperless.consumer] Parsing REDACTED.pdf...

[2024-03-07 08:24:41,906] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-ngx3wchpa05/REDACTED.pdf'), 'output_file': PosixPath('/tmp/paperless/paperless-ehepzu37/archive.pdf'), 'use_threads': True, 'jobs': 16, 'language': 'eng', 'output_type': 'pdfa', 'progress_bar': False, 'color_conversion_strategy': 'RGB', 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-ehepzu37/sidecar.txt')}

[2024-03-07 08:24:42,897] [WARNING] [paperless.parsing.tesseract] Ghostscript PDF/A rendering failed, consider setting PAPERLESS_OCR_USER_ARGS: '{"continue_on_soft_render_error": true}'

[2024-03-07 08:24:42,900] [ERROR] [paperless.consumer] Error occurred while consuming document RREDACTED.pdf: SubprocessOutputError: Ghostscript PDF/A rendering failed. See logs for more information.

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_exec/ghostscript.py", line 269, in generate_pdfa

    p = run_polling_stderr(

        ^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/subprocess/__init__.py", line 115, in run_polling_stderr

    raise CalledProcessError(proc.returncode, args, output=None, stderr=stderr)

subprocess.CalledProcessError: Command '['gs', '-dBATCH', '-dNOPAUSE', '-dSAFER', '-dCompatibilityLevel=1.6', '-sDEVICE=pdfwrite', '-dAutoRotatePages=/None', '-sColorConversionStrategy=RGB', '-dPDFSTOPONERROR', '-dAutoFilterColorImages=true', '-dAutoFilterGrayImages=true', '-dJPEGQ=95', '-dPDFA=2', '-dPDFACompatibilityPolicy=1', '-o', '-', '-sstdout=%stderr', '/tmp/ocrmypdf.io.eudrtc2_/fix_docinfo.pdf', '/tmp/ocrmypdf.io.eudrtc2_/pdfa.ps']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 353, in parse

    ocrmypdf.ocr(**args)

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/api.py", line 375, in ocr

    return run_pipeline(options=options, plugin_manager=plugin_manager)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 225, in run_pipeline

    return _run_pipeline(options, plugin_manager)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 192, in _run_pipeline

    optimize_messages = exec_concurrent(context, executor)

                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 148, in exec_concurrent

    pdf, messages = postprocess(pdf, context, executor)

                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/_common.py", line 420, in postprocess

    pdf_out = convert_to_pdfa(pdf_out, ps_stub_out, context)

              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipeline.py", line 814, in convert_to_pdfa

    context.plugin_manager.hook.generate_pdfa(

  File "/usr/local/lib/python3.11/site-packages/pluggy/_hooks.py", line 493, in __call__

    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/pluggy/_manager.py", line 115, in _hookexec

    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/pluggy/_callers.py", line 113, in _multicall

    raise exception.with_traceback(exception.__traceback__)

  File "/usr/local/lib/python3.11/site-packages/pluggy/_callers.py", line 77, in _multicall

    res = hook_impl.function(*args)

          ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/builtin_plugins/ghostscript.py", line 128, in generate_pdfa

    ghostscript.generate_pdfa(

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_exec/ghostscript.py", line 283, in generate_pdfa

    raise SubprocessOutputError('Ghostscript PDF/A rendering failed') from e

ocrmypdf.exceptions.SubprocessOutputError: Ghostscript PDF/A rendering failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 349, in main_wrap

    raise exc_info[1]

  File "/usr/src/paperless/src/documents/consumer.py", line 446, in try_consume_file

    document_parser.parse(self.working_copy, mime_type, self.filename)

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 376, in parse

    raise ParseError(

documents.parsers.ParseError: SubprocessOutputError: Ghostscript PDF/A rendering failed. See logs for more information.

[2024-03-07 08:25:19,696] [INFO] [paperless.consumer] Consuming REDACTED.pdf

[2024-03-07 08:25:19,699] [DEBUG] [paperless.consumer] Detected mime type: application/pdf

[2024-03-07 08:25:19,702] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser

[2024-03-07 08:25:19,705] [DEBUG] [paperless.consumer] Parsing REDATED.pdf...

[2024-03-07 08:25:19,912] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-ngx7svzvhyn/, REDACTED.pdf'), 'output_file': PosixPath('/tmp/paperless/paperless-j_ecx3ow/archive.pdf'), 'use_threads': True, 'jobs': 16, 'language': 'eng', 'output_type': 'pdfa', 'progress_bar': False, 'color_conversion_strategy': 'RGB', 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-j_ecx3ow/sidecar.txt')}

[2024-03-07 08:25:20,770] [WARNING] [paperless.parsing.tesseract] Ghostscript PDF/A rendering failed, consider setting PAPERLESS_OCR_USER_ARGS: '{"continue_on_soft_render_error": true}'

[2024-03-07 08:25:20,773] [ERROR] [paperless.consumer] Error occurred while consuming document REDACTED.pdf: SubprocessOutputError: Ghostscript PDF/A rendering failed. See logs for more information.

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_exec/ghostscript.py", line 269, in generate_pdfa

    p = run_polling_stderr(

        ^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/subprocess/__init__.py", line 115, in run_polling_stderr

    raise CalledProcessError(proc.returncode, args, output=None, stderr=stderr)

subprocess.CalledProcessError: Command '['gs', '-dBATCH', '-dNOPAUSE', '-dSAFER', '-dCompatibilityLevel=1.6', '-sDEVICE=pdfwrite', '-dAutoRotatePages=/None', '-sColorConversionStrategy=RGB', '-dPDFSTOPONERROR', '-dAutoFilterColorImages=true', '-dAutoFilterGrayImages=true', '-dJPEGQ=95', '-dPDFA=2', '-dPDFACompatibilityPolicy=1', '-o', '-', '-sstdout=%stderr', '/tmp/ocrmypdf.io.hryiqb4x/fix_docinfo.pdf', '/tmp/ocrmypdf.io.hryiqb4x/pdfa.ps']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 353, in parse

    ocrmypdf.ocr(**args)

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/api.py", line 375, in ocr

    return run_pipeline(options=options, plugin_manager=plugin_manager)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 225, in run_pipeline

    return _run_pipeline(options, plugin_manager)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 192, in _run_pipeline

    optimize_messages = exec_concurrent(context, executor)

                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 148, in exec_concurrent

    pdf, messages = postprocess(pdf, context, executor)

                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/_common.py", line 420, in postprocess

    pdf_out = convert_to_pdfa(pdf_out, ps_stub_out, context)

              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipeline.py", line 814, in convert_to_pdfa

    context.plugin_manager.hook.generate_pdfa(

  File "/usr/local/lib/python3.11/site-packages/pluggy/_hooks.py", line 493, in __call__

    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/pluggy/_manager.py", line 115, in _hookexec

    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/pluggy/_callers.py", line 113, in _multicall

    raise exception.with_traceback(exception.__traceback__)

  File "/usr/local/lib/python3.11/site-packages/pluggy/_callers.py", line 77, in _multicall

    res = hook_impl.function(*args)

          ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/builtin_plugins/ghostscript.py", line 128, in generate_pdfa

    ghostscript.generate_pdfa(

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_exec/ghostscript.py", line 283, in generate_pdfa

    raise SubprocessOutputError('Ghostscript PDF/A rendering failed') from e

ocrmypdf.exceptions.SubprocessOutputError: Ghostscript PDF/A rendering failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 349, in main_wrap

    raise exc_info[1]

  File "/usr/src/paperless/src/documents/consumer.py", line 446, in try_consume_file

    document_parser.parse(self.working_copy, mime_type, self.filename)

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 376, in parse

    raise ParseError(

documents.parsers.ParseError: SubprocessOutputError: Ghostscript PDF/A rendering failed. See logs for more information.
Drop files to begin upload
```

### Browser logs

```bash
NA
```

### Paperless-ngx version

Paperless-ngx 2.3.3 

### Host OS

Ubuntu

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
There are many discussions about this and a suggested fix is displayed directly in the log.

**Comment by cruzzoe** [comment]
@stumpylog  - I added the env var to be able to import the doc as the log suggested.
After doing this, when I attempt to set a tag, it won't & shows in the logs:

`[2024-03-08 04:16:34,353] [DEBUG] [paperless.classifier] Document classification model does not exist (yet), not performing automatic matching.`

I assume this is expected behaviour should the OCR fail and that I won't be able to tag this document until the OCR issues are resolved by the 3rd party lib?

**Comment by stumpylog** [comment]
This issue and that message are not related.  Nor is it related to tagging a document.
