### ISSUE TITLE
[BUG] Input File Error

### ISSUE THREAD

**Issue by haslinger** [paperless-ngx/paperless-ngx#6069]
### Description

Uploading a particular pdf, that can be successfully opened und displayed by Atril pdf viewer, results in a cryptic "Input File Error"

### Steps to reproduce

* Go to start page
* Select the file to upload
[Strom Jahresabrechnung.pdf](https://github.com/paperless-ngx/paperless-ngx/files/14549246/Strom.Jahresabrechnung.pdf)

### Webserver logs

```bash
[2024-03-10 07:59:23,636] [DEBUG] [paperless.tasks] Skipping plugin CollatePlugin
[2024-03-10 07:59:23,636] [DEBUG] [paperless.tasks] Skipping plugin BarcodePlugin
[2024-03-10 07:59:23,636] [DEBUG] [paperless.tasks] Executing plugin WorkflowTriggerPlugin
[2024-03-10 07:59:23,638] [INFO] [paperless.tasks] WorkflowTriggerPlugin completed with no message
[2024-03-10 07:59:23,644] [INFO] [paperless.consumer] Consuming Strom Jahresabrechnung.pdf
[2024-03-10 07:59:23,645] [DEBUG] [paperless.consumer] Detected mime type: application/pdf
[2024-03-10 07:59:23,648] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser
[2024-03-10 07:59:23,650] [DEBUG] [paperless.consumer] Parsing Strom Jahresabrechnung.pdf...
[2024-03-10 07:59:23,776] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-ngxj06g80az/Strom Jahresabrechnung.pdf'), 'output_file': PosixPath('/tmp/paperless/paperless-v7y_154e/archive.pdf'), 'use_threads': True, 'jobs': 12, 'language': 'deu', 'output_type': 'pdfa', 'progress_bar': False, 'color_conversion_strategy': 'RGB', 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-v7y_154e/sidecar.txt')}
[2024-03-10 07:59:23,895] [WARNING] [paperless.parsing.tesseract] Encountered an error while running OCR: . Attempting force OCR to get the text.

[2024-03-10 07:59:23,895] [DEBUG] [paperless.parsing.tesseract] Fallback: Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-ngxj06g80az/Strom Jahresabrechnung.pdf'), 'output_file': PosixPath('/tmp/paperless/paperless-v7y_154e/archive-fallback.pdf'), 'use_threads': True, 'jobs': 12, 'language': 'deu', 'output_type': 'pdfa', 'progress_bar': False, 'color_conversion_strategy': 'RGB', 'force_ocr': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-v7y_154e/sidecar-fallback.txt')}
[2024-03-10 07:59:24,010] [ERROR] [paperless.consumer] Error occurred while consuming document Strom Jahresabrechnung.pdf: InputFileError:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipeline.py", line 173, in get_pdfinfo
    return PdfInfo(
           ^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/pdfinfo/info.py", line 1103, in __init__
    self._pages = _pdf_pageinfo_concurrent(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/pdfinfo/info.py", line 778, in _pdf_pageinfo_concurrent
    executor(
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_concurrent.py", line 74, in __call__
    self._execute(
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/builtin_plugins/concurrency.py", line 141, in _execute
    result = future.result()
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/pdfinfo/info.py", line 727, in _pdf_pageinfo_sync
    return PageInfo(pdf, pageno, infile, check_pages, detailed_analysis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/pdfinfo/info.py", line 842, in __init__
    self._gather_pageinfo(pdf, pageno, infile, check_pages, detailed_analysis)
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/pdfinfo/info.py", line 887, in _gather_pageinfo
    for info in _process_content_streams(
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/pdfinfo/info.py", line 639, in _process_content_streams
    yield from _find_form_xobject_images(pdf, container, contentsinfo)
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/pdfinfo/info.py", line 584, in _find_form_xobject_images
    yield from _process_content_streams(
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/pdfinfo/info.py", line 631, in _process_content_streams
    contentsinfo = _interpret_contents(container, initial_shorthand)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/pdfinfo/info.py", line 224, in _interpret_contents
    _normalize_stack(parse_content_stream(contentstream, operator_whitelist))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pikepdf/models/_content_stream.py", line 116, in parse_content_stream
    raise e from e
  File "/usr/local/lib/python3.11/site-packages/pikepdf/models/_content_stream.py", line 111, in parse_content_stream
    Object._parse_stream_grouped(stream, operators),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pikepdf._core.PdfError: content stream (content stream object 14 0): errors while decoding content stream
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 404, in parse
    ocrmypdf.ocr(**args)
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/api.py", line 375, in ocr
    return run_pipeline(options=options, plugin_manager=plugin_manager)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 225, in run_pipeline
    return _run_pipeline(options, plugin_manager)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 176, in _run_pipeline
    pdfinfo = get_pdfinfo(
              ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipeline.py", line 185, in get_pdfinfo
    raise InputFileError() from e
ocrmypdf.exceptions.InputFileError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 349, in main_wrap
    raise exc_info[1]
  File "/usr/src/paperless/src/documents/consumer.py", line 516, in try_consume_file
    document_parser.parse(self.working_copy, mime_type, self.filename)
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 416, in parse
    raise ParseError(f"{e.__class__.__name__}: {e!s}") from e
documents.parsers.ParseError: InputFileError:
```

### Paperless-ngx version

2.4.2

### Host OS

Alpine Linux v3.19 on x86_64

### Installation method

Docker - official image

### Browser

Chrome

### Configuration changes

none

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Eg #4145

**Comment by haslinger** [comment]
For everybody else as puzzled as me on this, the  way to switch off ocr temporarily is:

* in "Configuration" at the sidebar select "OCR-Settings" choose "always" in OCR_SKIP_ARCHIVE_FILE-section
* Import the documents, that cannot be handled
* in "Configuration" at the sidebar select "OCR-Settings" choose "with_text" in OCR_SKIP_ARCHIVE_FILE-section
