### ISSUE TITLE
[BUG] Failed to import email 

### ISSUE THREAD

**Issue by emacsbliss** [paperless-ngx/paperless-ngx#6077]
### Description

I setup a mail rule (see screenshot), however for every email it processed, it encountered an error:

```
Could not parse content with tika server at http://tika:9998: <TikaKey.Parsers: 'X-TIKA:Parsed-By'>
```
![Screenshot 2024-03-10 at 3 53 57 PM](https://github.com/paperless-ngx/paperless-ngx/assets/65474902/248dcb95-74d7-4c4e-8f06-daddcd848558)

### Steps to reproduce

1. add a mail account
2. setup a mail rule as described in description
3. place a mail into folder which will trigger the criteria

this is the docker compose file I used to install it on my Synology NAS:

```
version: "3.4"
services:
  broker:
    image: library/redis:7
    restart: unless-stopped
    volumes:
      - /volume1/docker/paperless-ngx/redisdata:/data

  db:
    image: library/postgres:15
    restart: unless-stopped
    volumes:
      - /volume1/docker/paperless-ngx/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
      
  webserver:
    image: paperlessngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - 7300:8000
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /volume1/docker/paperless-ngx/data:/usr/src/paperless/data
      - /volume1/docker/paperless-ngx/media:/usr/src/paperless/media
      - /volume1/docker/paperless-ngx/export:/usr/src/paperless/export
      - /volume1/docker/paperless-ngx/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_OCR_LANGUAGES: chi-sim chi-tra
      PAPERLESS_OCR_LANGUAGE: eng+chi_sim
      USERMAP_UID: 0
      USERMAP_GID: 0
      PAPERLESS_TIME_ZONE: America/New_York
  
  gotenberg:
    image: gotenberg/gotenberg:7.10
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
  
  tika:
    image: apache/tika:latest
    restart: unless-stopped
```

### Webserver logs

```bash

[2024-03-10 15:50:03,902] [INFO] [paperless.tasks] WorkflowTriggerPlugin completed with:

[2024-03-10 15:50:03,926] [INFO] [paperless.consumer] Consuming Spring Forward with New Apparel, Patio and Appliances!.eml

[2024-03-10 15:50:03,937] [DEBUG] [paperless.consumer] Detected mime type: message/rfc822

[2024-03-10 15:50:04,466] [DEBUG] [paperless.consumer] Parser: MailDocumentParser

[2024-03-10 15:50:04,477] [DEBUG] [paperless.consumer] Parsing Spring Forward with New Apparel, Patio and Appliances!.eml...

[2024-03-10 15:50:04,478] [DEBUG] [paperless.parsing.mail] Parsing file Spring Forward with New Apparel, Patio and Appliances!.eml into an email

[2024-03-10 15:50:04,500] [DEBUG] [paperless.parsing.mail] Building formatted text from email

[2024-03-10 15:50:04,505] [INFO] [paperless.parsing.mail] Sending content to Tika server

[2024-03-10 15:50:04,928] [ERROR] [paperless.consumer] Error occurred while consuming document Spring Forward with New Apparel, Patio and Appliances!.eml: Could not parse content with tika server at http://tika:9998: <TikaKey.Parsers: 'X-TIKA:Parsed-By'>

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_mail/parsers.py", line 197, in tika_parse

    parsed = client.tika.as_text.from_buffer(html, "text/html")

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/tika_client/_resource_tika.py", line 42, in from_buffer

    return self._decoded_response(self._put_content(self.PLAIN_TEXT_CONTENT, content, mime_type))

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/tika_client/_utils.py", line 81, in _decoded_response

    return TikaResponse(resp_json)

           ^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/tika_client/data_models.py", line 79, in __init__

    self.parsers: List[str] = self.data[TikaKey.Parsers]

                              ~~~~~~~~~^^^^^^^^^^^^^^^^^

KeyError: <TikaKey.Parsers: 'X-TIKA:Parsed-By'>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 349, in main_wrap

    raise exc_info[1]

  File "/usr/src/paperless/src/documents/consumer.py", line 623, in try_consume_file

    document_parser.parse(self.working_copy, mime_type, self.filename)

  File "/usr/src/paperless/src/paperless_mail/parsers.py", line 163, in parse

    self.text = build_formatted_text(mail)

                ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/paperless/src/paperless_mail/parsers.py", line 153, in build_formatted_text

    fmt_text += "HTML content: " + strip_text(self.tika_parse(mail.html))

                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/paperless/src/paperless_mail/parsers.py", line 203, in tika_parse

    raise ParseError(

documents.parsers.ParseError: Could not parse content with tika server at http://tika:9998: <TikaKey.Parsers: 'X-TIKA:Parsed-By'>

```

### Paperless-ngx version

2.6.2

### Host OS

MacOS M1, 14.3.1

### Installation method

Other (please describe above)

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
Without a sample file, there is unlikely anything to do.

**Comment by stumpylog** [comment]
I confirmed with our sample emails, they all still import without issue, so this seems most likely to be a problem with a corrupted email.  Or invalid email.

**Comment by emacsbliss** [comment]
this issue happened to multiple different emails.. 

I also attached one of the email (the one log shows), but I had to zip it otherwise github won't allow me to upload it.

[test.eml.zip](https://github.com/paperless-ngx/paperless-ngx/files/14552832/test.eml.zip)

**Comment by stumpylog** [comment]
Imports without issue for me.  Perhaps your Tika container isn't running correctly.  I'd re-create it

**Comment by emacsbliss** [comment]
thanks for checking!!
do you see anything wrong with my docker compose file?

**Comment by stumpylog** [comment]
Nothing stands out to me.  Roughly, the error is that Tika is returning nothing parsed the file, which would I think only happen if it has failed.  Any logs from it?

**Comment by emacsbliss** [comment]
this is all I can get from the tika container log:

```
Mar 10, 2024 7:19:11 PM org.apache.tika.config.InitializableProblemHandler$3 handleInitializableProblem
WARNING: J2KImageReader not loaded. JPEG2000 files will not be processed.
See https://pdfbox.apache.org/2.0/dependencies.html#jai-image-io
for optional dependencies.
Mar 10, 2024 7:19:12 PM org.apache.tika.config.InitializableProblemHandler$3 handleInitializableProblem
WARNING: org.xerial's sqlite-jdbc is not loaded.
Please provide the jar on your classpath to parse sqlite files.
See tika-parsers/pom.xml for the correct version.
INFO  Starting Apache Tika 1.27 server
INFO  Setting the server's publish address to be http://0.0.0.0:9998/
INFO  Logging initialized @7510ms to org.eclipse.jetty.util.log.Slf4jLog
INFO  jetty-9.4.41.v20210516; built: 2021-05-16T23:56:28.993Z; git: 98607f93c7833e7dc59489b13f3cb0a114fb9f4c; jvm 14.0.2+12-Ubuntu-120.04
INFO  Started ServerConnector@b40bb6e{HTTP/1.1, (http/1.1)}{0.0.0.0:9998}
INFO  Started @7997ms
WARN  Empty contextPath
INFO  Started o.e.j.s.h.ContextHandler@7bf9b098{/,null,AVAILABLE}
INFO  Started Apache Tika server at http://0.0.0.0:9998/
INFO  tika/text (text/html)
INFO  tika/text (text/html)
```

**Comment by stumpylog** [comment]
> INFO  Starting Apache Tika 1.27 server

That's not the right version.  It should be 2.9.1, that's the latest

**Comment by emacsbliss** [comment]
but even with gotenberg 7, I'm still getting the same error, that's why I tried to upgrade to gotenberg 8

**Comment by stumpylog** [comment]
Per their documentation, you can increase timeouts with `--api-timeout`, that may avoid the "context deadline exceeded".  Otherwise, issues with Gotenberg should be reported to them.
