### ISSUE TITLE
[BUG]  TypeError: Only scalar types, arrays, and dictionaries are allowed in content streams.

### ISSUE THREAD

**Issue by lanbugs** [paperless-ngx/paperless-ngx#6090]
### Description

After uploading PDF files some files will not be processed, the following error occurs:

TypeError: Only scalar types, arrays, and dictionaries are allowed in content streams.

The PDF is viewable with any PDF reader, so i guess it is not a currupt file.

### Steps to reproduce

Some of my PDFs will produce the error, unfortunately i can not share the pdf because of sensitive data.

### Webserver logs

```bash
[2024-03-12 22:50:36,883] [ERROR] [paperless.consumer] Error occurred while consuming document 202381059020037621.pdf: TypeError: Only scalar types, arrays, and dictionaries are allowed in content streams.
Traceback (most recent call last):
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 366, in parse
    ocrmypdf.ocr(**args)
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/api.py", line 375, in ocr
    return run_pipeline(options=options, plugin_manager=plugin_manager)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 225, in run_pipeline
    return _run_pipeline(options, plugin_manager)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 176, in _run_pipeline
    pdfinfo = get_pdfinfo(
              ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipeline.py", line 173, in get_pdfinfo
    return PdfInfo(
           ^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/pdfinfo/info.py", line 1103, in __init__
    self._pages = _pdf_pageinfo_concurrent(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/pdfinfo/info.py", line 778, in _pdf_pageinfo_concurrent
    executor(
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_concurrent.py", line 74, in __call__
    self._execute(
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/builtin_plugins/concurrency.py", line 141, in _execute
    result = future.result()
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/pdfinfo/info.py", line 727, in _pdf_pageinfo_sync
    return PageInfo(pdf, pageno, infile, check_pages, detailed_analysis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/pdfinfo/info.py", line 842, in __init__
    self._gather_pageinfo(pdf, pageno, infile, check_pages, detailed_analysis)
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/pdfinfo/info.py", line 887, in _gather_pageinfo
    for info in _process_content_streams(
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/pdfinfo/info.py", line 639, in _process_content_streams
    yield from _find_form_xobject_images(pdf, container, contentsinfo)
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/pdfinfo/info.py", line 584, in _find_form_xobject_images
    yield from _process_content_streams(
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/pdfinfo/info.py", line 631, in _process_content_streams
    contentsinfo = _interpret_contents(container, initial_shorthand)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/pdfinfo/info.py", line 224, in _interpret_contents
    _normalize_stack(parse_content_stream(contentstream, operator_whitelist))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pikepdf/models/_content_stream.py", line 111, in parse_content_stream
    Object._parse_stream_grouped(stream, operators),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Only scalar types, arrays, and dictionaries are allowed in content streams.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 349, in main_wrap
    raise exc_info[1]
  File "/usr/src/paperless/src/documents/consumer.py", line 623, in try_consume_file
    document_parser.parse(self.working_copy, mime_type, self.filename)
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 433, in parse
    raise ParseError(f"{e.__class__.__name__}: {e!s}") from e
documents.parsers.ParseError: TypeError: Only scalar types, arrays, and dictionaries are allowed in content streams.
```

### Paperless-ngx version

2.6.2

### Host OS

Ubuntu 22.04

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
From the issue template:

> Also, note that Paperless-ngx does not perform OCR itself, that is handled by other tools. Problems with OCR of specific files should likely be raised 'upstream', see https://github.com/ocrmypdf/OCRmyPDF/issues or https://github.com/tesseract-ocr/tesseract/issues

PDFs are very messy, some folks have luck trying to 'clean them up' with something like e.g. https://qpdf.sourceforge.io
