### ISSUE TITLE
[BUG] getting "input file error" when document is consumed from "consume" Folder, works with GUI Upload

### ISSUE THREAD

**Issue by Nitsuj116** [paperless-ngx/paperless-ngx#6101]
### Description

Hello Team, 

im currently experiencing a strange error with Paperless-NGX. Im scanning documents via FTP to my SynologyNAS. NAS Folder is mounted via NFS to the Paperless-NGX (Ubuntu 22.04). Except the problem that inotify was not working everything worked like a charme. 

Since yesterday i suddenly have problems with some PDFs scanned with getting the error "input file error" after paperless started consuming the pdf. Even if i try 5-6 times its not working. When manually uploading the pdf over GUI it works without any errors including correct OCR of the Document. I didnt change anything anywhere, error just started to occur yesterday. 

Most of the Documents are Docs from the government but without any digital Signatures or something. Also, as the import over GUI works OCR should be usable. If you need the document for Troubleshooting feel free to contact me, but because of personal details i cant post them here. 

### Steps to reproduce

1. Scan Document with Scan2Folder (FTP)
2. Wait 10 Seconds till Paperless starts Consuming the Document
3. Get the Error

### Webserver logs

```bash
[2024-03-14 08:59:49,232] [DEBUG] [paperless.management.consumer] Waiting for file /usr/src/paperless/consume/20240314_085857.pdf to remain unmodified

[2024-03-14 08:59:54,238] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/20240314_085857.pdf to the task queue.

[2024-03-14 08:59:54,315] [DEBUG] [paperless.tasks] Skipping plugin CollatePlugin

[2024-03-14 08:59:54,315] [DEBUG] [paperless.tasks] Skipping plugin BarcodePlugin

[2024-03-14 08:59:54,315] [DEBUG] [paperless.tasks] Executing plugin WorkflowTriggerPlugin

[2024-03-14 08:59:54,317] [INFO] [paperless.tasks] WorkflowTriggerPlugin completed with:

[2024-03-14 08:59:54,328] [INFO] [paperless.consumer] Consuming 20240314_085857.pdf

[2024-03-14 08:59:54,331] [DEBUG] [paperless.consumer] Detected mime type: application/pdf

[2024-03-14 08:59:54,337] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser

[2024-03-14 08:59:54,341] [DEBUG] [paperless.consumer] Parsing 20240314_085857.pdf...

[2024-03-14 08:59:54,507] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-ngxqco8tjrt/20240314_085857.pdf'), 'output_file': PosixPath('/tmp/paperless/paperless-8l3rlxhl/archive.pdf'), 'use_threads': True, 'jobs': 1, 'language': 'deu', 'output_type': 'pdfa', 'progress_bar': False, 'color_conversion_strategy': 'RGB', 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-8l3rlxhl/sidecar.txt')}

[2024-03-14 08:59:54,627] [WARNING] [paperless.parsing.tesseract] Encountered an error while running OCR: . Attempting force OCR to get the text.

[2024-03-14 08:59:54,628] [DEBUG] [paperless.parsing.tesseract] Fallback: Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-ngxqco8tjrt/20240314_085857.pdf'), 'output_file': PosixPath('/tmp/paperless/paperless-8l3rlxhl/archive-fallback.pdf'), 'use_threads': True, 'jobs': 1, 'language': 'deu', 'output_type': 'pdfa', 'progress_bar': False, 'color_conversion_strategy': 'RGB', 'force_ocr': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-8l3rlxhl/sidecar-fallback.txt')}

[2024-03-14 08:59:54,739] [ERROR] [paperless.consumer] Error occurred while consuming document 20240314_085857.pdf: InputFileError:

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipeline.py", line 173, in get_pdfinfo

    return PdfInfo(

           ^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/pdfinfo/info.py", line 1100, in __init__

    with Pdf.open(infile) as pdf:

         ^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/pikepdf/_methods.py", line 400, in open

    pdf = Pdf._open(

          ^^^^^^^^^^

pikepdf._core.PdfError: /tmp/ocrmypdf.io.6u_3bguc/origin.pdf: unable to find trailer dictionary while recovering damaged file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 366, in parse

    ocrmypdf.ocr(**args)

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/api.py", line 375, in ocr

    return run_pipeline(options=options, plugin_manager=plugin_manager)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 225, in run_pipeline

    return _run_pipeline(options, plugin_manager)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 176, in _run_pipeline

    pdfinfo = get_pdfinfo(

              ^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipeline.py", line 185, in get_pdfinfo

    raise InputFileError() from e

ocrmypdf.exceptions.InputFileError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipeline.py", line 173, in get_pdfinfo

    return PdfInfo(

           ^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/pdfinfo/info.py", line 1100, in __init__

    with Pdf.open(infile) as pdf:

         ^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/pikepdf/_methods.py", line 400, in open

    pdf = Pdf._open(

          ^^^^^^^^^^

pikepdf._core.PdfError: /tmp/ocrmypdf.io.aaed40ow/origin.pdf: unable to find trailer dictionary while recovering damaged file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 417, in parse

    ocrmypdf.ocr(**args)

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/api.py", line 375, in ocr

    return run_pipeline(options=options, plugin_manager=plugin_manager)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 225, in run_pipeline

    return _run_pipeline(options, plugin_manager)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 176, in _run_pipeline

    pdfinfo = get_pdfinfo(

              ^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipeline.py", line 185, in get_pdfinfo

    raise InputFileError() from e

ocrmypdf.exceptions.InputFileError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 349, in main_wrap

    raise exc_info[1]

  File "/usr/src/paperless/src/documents/consumer.py", line 623, in try_consume_file

    document_parser.parse(self.working_copy, mime_type, self.filename)

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 429, in parse

    raise ParseError(f"{e.__class__.__name__}: {e!s}") from e

documents.parsers.ParseError: InputFileError:
```

### Paperless-ngx version

2.6.2

### Host OS

Ubuntu 22.04 

### Installation method

Docker - official image

### Browser

Chrome, Opera, Firefox

### Configuration changes

PAPERLESS_CONSUMER_POLLING=60,  - /var/scaninput:/usr/src/paperless/consume

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
All documents go through the same process.  You are presumably running into issues due to the file not yet being fully transferred.

We already provide a lot of setting to help alleviate this
