### ISSUE TITLE
[BUG] This writer is closed

### ISSUE THREAD

**Issue by Stuart4** [paperless-ngx/paperless-ngx#6108]
### Description

I'm receiving the error "This writer is closed" when trying to upload new documents to Paperless. This began occurring after attempting to use the consume folder for the first time.

<img width="1427" alt="Screenshot 2024-03-14 at 8 08 27 PM" src="https://github.com/paperless-ngx/paperless-ngx/assets/1891384/266c1a95-c7b9-420b-9d80-6f8de22b03d5">

### Steps to reproduce

1. Add any document to the consume folder.
2. Upload any document by the UI or the consume folder.

### Webserver logs

```bash
[2024-03-14 20:27:47,691] [ERROR] [paperless.index] unpack requires a buffer of 8 bytes

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/index.py", line 103, in open_index_writer

    yield writer

  File "/usr/src/paperless/src/documents/index.py", line 189, in add_or_update_document

    update_document(writer, document)

  File "/usr/src/paperless/src/documents/index.py", line 145, in update_document

    writer.update_document(

  File "/usr/local/lib/python3.11/site-packages/whoosh/writing.py", line 1024, in update_document

    self._record("update_document", args, kwargs)

  File "/usr/local/lib/python3.11/site-packages/whoosh/writing.py", line 1001, in _record

    getattr(self.writer, method)(*args, **kwargs)

  File "/usr/local/lib/python3.11/site-packages/whoosh/writing.py", line 483, in update_document

    with self.searcher() as s:

         ^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/whoosh/writing.py", line 297, in searcher

    return Searcher(self.reader(), **kwargs)

                    ^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/whoosh/writing.py", line 638, in reader

    return FileIndex._reader(self.storage, self.schema, self.segments,

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/whoosh/index.py", line 529, in _reader

    return segreader(segments[0])

           ^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/whoosh/index.py", line 523, in segreader

    return SegmentReader(storage, schema, segment,

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/whoosh/reading.py", line 610, in __init__

    files = segment.open_compound_file(storage)

            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/whoosh/codec/base.py", line 570, in open_compound_file

    return CompoundStorage(dbfile, use_mmap=storage.supports_mmap)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/whoosh/filedb/compound.py", line 58, in __init__

    self._diroffset = self._file.read_long()

                      ^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/whoosh/filedb/structfile.py", line 302, in read_long

    return unpack_long(self.read(_LONG_SIZE))[0]

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

struct.error: unpack requires a buffer of 8 bytes

[2024-03-14 20:27:47,697] [ERROR] [paperless.consumer] The following error occurred while storing document brady.pdf after parsing: This writer is closed

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/index.py", line 103, in open_index_writer

    yield writer

  File "/usr/src/paperless/src/documents/index.py", line 189, in add_or_update_document

    update_document(writer, document)

  File "/usr/src/paperless/src/documents/index.py", line 145, in update_document

    writer.update_document(

  File "/usr/local/lib/python3.11/site-packages/whoosh/writing.py", line 1024, in update_document

    self._record("update_document", args, kwargs)

  File "/usr/local/lib/python3.11/site-packages/whoosh/writing.py", line 1001, in _record

    getattr(self.writer, method)(*args, **kwargs)

  File "/usr/local/lib/python3.11/site-packages/whoosh/writing.py", line 483, in update_document

    with self.searcher() as s:

         ^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/whoosh/writing.py", line 297, in searcher

    return Searcher(self.reader(), **kwargs)

                    ^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/whoosh/writing.py", line 638, in reader

    return FileIndex._reader(self.storage, self.schema, self.segments,

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/whoosh/index.py", line 529, in _reader

    return segreader(segments[0])

           ^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/whoosh/index.py", line 523, in segreader

    return SegmentReader(storage, schema, segment,

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/whoosh/reading.py", line 610, in __init__

    files = segment.open_compound_file(storage)

            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/whoosh/codec/base.py", line 570, in open_compound_file

    return CompoundStorage(dbfile, use_mmap=storage.supports_mmap)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/whoosh/filedb/compound.py", line 58, in __init__

    self._diroffset = self._file.read_long()

                      ^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/whoosh/filedb/structfile.py", line 302, in read_long

    return unpack_long(self.read(_LONG_SIZE))[0]

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

struct.error: unpack requires a buffer of 8 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 349, in main_wrap

    raise exc_info[1]

  File "/usr/src/paperless/src/documents/consumer.py", line 691, in try_consume_file

    document_consumption_finished.send(

  File "/usr/local/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 176, in send

    return [

           ^

  File "/usr/local/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>

    (receiver, receiver(signal=self, sender=sender, **named))

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/paperless/src/documents/signals/handlers.py", line 510, in add_to_index

    index.add_or_update_document(document)

  File "/usr/src/paperless/src/documents/index.py", line 188, in add_or_update_document

    with open_index_writer() as writer:

  File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__

    self.gen.throw(typ, value, traceback)

  File "/usr/src/paperless/src/documents/index.py", line 108, in open_index_writer

    writer.commit(optimize=optimize)

  File "/usr/local/lib/python3.11/site-packages/whoosh/writing.py", line 1037, in commit

    self.writer.commit(*args, **kwargs)

  File "/usr/local/lib/python3.11/site-packages/whoosh/writing.py", line 920, in commit

    self._check_state()

  File "/usr/local/lib/python3.11/site-packages/whoosh/writing.py", line 555, in _check_state

    raise IndexingError("This writer is closed")

whoosh.writing.IndexingError: This writer is closed
```

### Paperless-ngx version

2.6.2

### Host OS

Unraid 6.12.6

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
https://github.com/paperless-ngx/paperless-ngx/issues/1721
https://github.com/paperless-ngx/paperless-ngx/discussions/5627
https://github.com/paperless-ngx/paperless-ngx/issues/2573
