### ISSUE TITLE
[BUG] Acces denied error #13 when using subdirs in consume folder (/usr/share/hassio/share/paperless/consume)

### ISSUE THREAD

**Issue by wfa001** [paperless-ngx/paperless-ngx#6112]
### Description

when copying files (pdf) with WinSCP into the consume folder (tree with folders) paperless gives an error 13 access denied for the files in the subfolders. Files in the root folder /usr/share/hassio/share/paperless/consume are 'consumed' without any problems

### Steps to reproduce

copy files in subfolders to the /usr/share/hassio/share/paperless/consume

### Webserver logs

```bash
PermissionError: [Errno 13] Permission denied: '/share/paperless/consume/Informationen/2022-07-04 Betriebsanleitung Notstromaggregat.pdf'
[2024-03-16 15:02:53,171] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[1e6e0659-9383-4930-bebf-46140a851511] raised unexpected: ConsumerError("2022-07-04 Betriebsanleitung Notstromaggregat.pdf: The following error occurred while storing document 2022-07-04 Betriebsanleitung Notstromaggregat.pdf after parsing: [Errno 13] Permission denied: '/share/paperless/consume/Informationen/2022-07-04 Betriebsanleitung Notstromaggregat.pdf'")
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/asgiref/sync.py", line 349, in main_wrap
    raise exc_info[1]
  File "/usr/src/paperless/src/documents/consumer.py", line 740, in try_consume_file
    self.original_path.unlink()
  File "/usr/lib/python3.11/pathlib.py", line 1148, in unlink
    os.unlink(self)
PermissionError: [Errno 13] Permission denied: '/share/paperless/consume/Informationen/2022-07-04 Betriebsanleitung Notstromaggregat.pdf'
```

### Paperless-ngx version

1.2.9

### Host OS

debian 12

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
How would a permissions error in your copied files be a paperless bug?
