### ISSUE TITLE
Django error when starting installation script

### ISSUE THREAD

**Issue by dudomatik** [paperless-ngx/paperless-ngx#6212]
### Description

installation fails with the install script.
I run Debian 12.5 in a Proxmox VM. Target folder is mounted via SAMBA to user "paperless" UID 1010.

I have tried with all 3 kinds of databases, none work (different error messages are produced though)

### Steps to reproduce

1. Create Debian VM
2. Install Docker & Docker Compose
3. set up user paperless ( UID 1010, group ID 1010, password, home dir, add to sudo and docker group)
4. mount zpool to /home/paperless/paperless-ngx
5. run script

### Webserver logs

```bash
Summary
=======

Target folder: /home/paperless/paperless-ngx
Consume folder: /home/paperless/paperless-ngx/consume
Media folder: /home/paperless/paperless-ngx/media
Data folder: /home/paperless/paperless-ngx/data
Database folder: /home/paperless/paperless-ngx/database

URL: https://paperless.test.com
Port: 8000
Database: postgres
Tika enabled: yes
OCR language: deu+eng
User id: 1010
Group id: 1010

Paperless username: test
Paperless email: test@test.com

Press any key to install.

Installing paperless...

--2024-03-28 19:14:43--  https://raw.githubusercontent.com/paperless-ngx/paperless-ngx/main/docker/compose/docker-compose.postgres-tika.yml
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2946 (2.9K) [text/plain]
Saving to: ‘docker-compose.yml’

docker-compose.yml  100%[===================>]   2.88K  --.-KB/s    in 0s      

2024-03-28 19:14:43 (29.9 MB/s) - ‘docker-compose.yml’ saved [2946/2946]

--2024-03-28 19:14:43--  https://raw.githubusercontent.com/paperless-ngx/paperless-ngx/main/docker/compose/.env
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 31 [text/plain]
Saving to: ‘.env’

.env                100%[===================>]      31  --.-KB/s    in 0s      

2024-03-28 19:14:43 (1.20 MB/s) - ‘.env’ saved [31/31]

WARN[0000] /home/paperless/paperless-ngx/docker-compose.yml: `version` is obsolete 
[+] Pulling 5/5
 ✔ broker Pulled                                                           1.5s 
 ✔ db Pulled                                                               1.5s 
 ✔ webserver Pulled                                                        1.0s 
 ✔ gotenberg Pulled                                                        1.5s 
 ✔ tika Pulled                                                             1.0s 
Starting DB first for initialization
WARN[0000] /home/paperless/paperless-ngx/docker-compose.yml: `version` is obsolete 
[+] Running 1/1
 ✔ Container paperless-db-1  Started                                       0.3s 
WARN[0000] /home/paperless/paperless-ngx/docker-compose.yml: `version` is obsolete 
[+] Stopping 1/0
 ✔ Container paperless-db-1  Stopped                                       0.0s 
WARN[0000] /home/paperless/paperless-ngx/docker-compose.yml: `version` is obsolete 
[+] Creating 4/0
 ✔ Container paperless-gotenberg-1  C...                                   0.1s 
 ✔ Container paperless-tika-1       Create...                              0.1s 
 ✔ Container paperless-broker-1     Crea...                                0.1s 
 ✔ Container paperless-db-1         Created                                0.0s 
[+] Running 4/4
 ✔ Container paperless-broker-1     Star...                                0.8s 
 ✔ Container paperless-db-1         Started                                0.8s 
 ✔ Container paperless-gotenberg-1  S...                                   0.7s 
 ✔ Container paperless-tika-1       Starte...                              0.5s 
Paperless-ngx docker container starting...
Mapping UID and GID for paperless:paperless to 1010:1010
Creating directory /usr/src/paperless/data/index
Creating directory /usr/src/paperless/media/documents
Creating directory /usr/src/paperless/media/documents/originals
Creating directory /usr/src/paperless/media/documents/thumbnails
Creating directory scratch directory /tmp/paperless
Adjusting permissions of paperless files. This may take a while.
Waiting for PostgreSQL to start...
Waiting for Redis...
Connected to Redis broker.
Apply database migrations...
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 289, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 270, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/postgresql/base.py", line 275, in get_new_connection
    connection = self.Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "db" to address: Name or service not known


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 117, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/loader.py", line 58, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/loader.py", line 235, in build_graph
    self.applied_migrations = recorder.applied_migrations()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/recorder.py", line 81, in applied_migrations
    if self.has_table():
       ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/recorder.py", line 57, in has_table
    with self.connection.cursor() as cursor:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 330, in cursor
    return self._cursor()
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 306, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 288, in ensure_connection
    with self.wrap_database_errors:
  File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 289, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 270, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/postgresql/base.py", line 275, in get_new_connection
    connection = self.Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: could not translate host name "db" to address: Name or service not known
```

### Paperless-ngx version

2.6.3

### Host OS

Debian 12.5

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by dudomatik** [comment]
solved it by doubling my RAM from 2 GB to 4 GB on my virtual machine
