### ISSUE TITLE
[BUG] export and import don't work with audit log

### ISSUE THREAD

**Issue by trunneml** [paperless-ngx/paperless-ngx#6244]
### Description

When setting PAPERLESS_AUDIT_LOG_ENABLED=True, the next `docker compose -f paperless.yml exec webserver document_importer ../export` returns an error:

```
# docker compose -f paperlessyml exec webserver document_importer ../export
Checking the manifest
Database import failed
No version information present
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "django_content_type_app_label_model_76bd3d3b_uniq"
DETAIL:  Key (app_label, model)=(documents, tag) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/paperless/src/documents/management/commands/document_importer.py", line 180, in handle
    raise e
  File "/usr/src/paperless/src/documents/management/commands/document_importer.py", line 161, in handle
    call_command("loaddata", manifest_path)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 194, in call_command
    return command.execute(*args, **defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/loaddata.py", line 102, in handle
    self.loaddata(fixture_labels)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/loaddata.py", line 163, in loaddata
    self.load_label(fixture_label)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/loaddata.py", line 253, in load_label
    if self.save_obj(obj):
       ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/loaddata.py", line 209, in save_obj
    obj.save(using=self.using)
  File "/usr/local/lib/python3.11/site-packages/django/core/serializers/base.py", line 288, in save
    models.Model.save_base(self.object, using=using, raw=True, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: Problem installing fixture '/usr/src/paperless/export/manifest.json': Could not load contenttypes.ContentType(pk=7): duplicate key value violates unique constraint "django_content_type_app_label_model_76bd3d3b_uniq"
DETAIL:  Key (app_label, model)=(documents, tag) already exists.
```

### Steps to reproduce

1. Start with an existing Paperless
2. activate PAPERLESS_AUDIT_LOG_ENABLED
3. export via `document_exporter`
4. import into empty/new paplerless-ngx instance via `document_importer`

### Webserver logs

```bash
webserver-1  | Paperless-ngx docker container starting...
webserver-1  | Mapping UID and GID for paperless:paperless to 1024:100
webserver-1  | Creating directory /usr/src/paperless/data/index
webserver-1  | Creating directory /usr/src/paperless/media/documents
webserver-1  | Creating directory /usr/src/paperless/media/documents/originals
webserver-1  | Creating directory /usr/src/paperless/media/documents/thumbnails
webserver-1  | Creating directory scratch directory /tmp/paperless
webserver-1  | Adjusting permissions of paperless files. This may take a while.
webserver-1  | Waiting for PostgreSQL to start...
webserver-1  | Waiting for Redis...
webserver-1  | Connected to Redis broker.
webserver-1  | Apply database migrations...
webserver-1  | Operations to perform:
webserver-1  |   Apply all migrations: account, admin, auditlog, auth, authtoken, contenttypes, django_celery_results, documents, guardian, paperless, paperless_mail, sessions, socialaccount
webserver-1  | Running migrations:
webserver-1  |   Applying contenttypes.0001_initial... OK
webserver-1  |   Applying auth.0001_initial... OK
webserver-1  |   Applying account.0001_initial... OK
webserver-1  |   Applying account.0002_email_max_length... OK
webserver-1  |   Applying account.0003_alter_emailaddress_create_unique_verified_email... OK
webserver-1  |   Applying account.0004_alter_emailaddress_drop_unique_email... OK
webserver-1  |   Applying account.0005_emailaddress_idx_upper_email... OK
webserver-1  |   Applying admin.0001_initial... OK
webserver-1  |   Applying admin.0002_logentry_remove_auto_add... OK
webserver-1  |   Applying admin.0003_logentry_add_action_flag_choices... OK
webserver-1  |   Applying auditlog.0001_initial... OK
webserver-1  |   Applying auditlog.0002_auto_support_long_primary_keys... OK
webserver-1  |   Applying auditlog.0003_logentry_remote_addr... OK
webserver-1  |   Applying auditlog.0004_logentry_detailed_object_repr... OK
webserver-1  |   Applying auditlog.0005_logentry_additional_data_verbose_name... OK
webserver-1  |   Applying auditlog.0006_object_pk_index... OK
webserver-1  |   Applying auditlog.0007_object_pk_type... OK
webserver-1  |   Applying auditlog.0008_action_index... OK
webserver-1  |   Applying auditlog.0009_alter_logentry_additional_data... OK
webserver-1  |   Applying auditlog.0010_alter_logentry_timestamp... OK
webserver-1  |   Applying auditlog.0011_logentry_serialized_data... OK
webserver-1  |   Applying auditlog.0012_add_logentry_action_access... OK
webserver-1  |   Applying contenttypes.0002_remove_content_type_name... OK
webserver-1  |   Applying auth.0002_alter_permission_name_max_length... OK
webserver-1  |   Applying auth.0003_alter_user_email_max_length... OK
webserver-1  |   Applying auth.0004_alter_user_username_opts... OK
webserver-1  |   Applying auth.0005_alter_user_last_login_null... OK
webserver-1  |   Applying auth.0006_require_contenttypes_0002... OK
webserver-1  |   Applying auth.0007_alter_validators_add_error_messages... OK
webserver-1  |   Applying auth.0008_alter_user_username_max_length... OK
webserver-1  |   Applying auth.0009_alter_user_last_name_max_length... OK
webserver-1  |   Applying auth.0010_alter_group_name_max_length... OK
webserver-1  |   Applying auth.0011_update_proxy_permissions... OK
webserver-1  |   Applying auth.0012_alter_user_first_name_max_length... OK
webserver-1  |   Applying authtoken.0001_initial... OK
webserver-1  |   Applying authtoken.0002_auto_20160226_1747... OK
webserver-1  |   Applying authtoken.0003_tokenproxy... OK
webserver-1  |   Applying django_celery_results.0001_initial... OK
webserver-1  |   Applying django_celery_results.0002_add_task_name_args_kwargs... OK
webserver-1  |   Applying django_celery_results.0003_auto_20181106_1101... OK
webserver-1  |   Applying django_celery_results.0004_auto_20190516_0412... OK
webserver-1  |   Applying django_celery_results.0005_taskresult_worker... OK
webserver-1  |   Applying django_celery_results.0006_taskresult_date_created... OK
webserver-1  |   Applying django_celery_results.0007_remove_taskresult_hidden... OK
webserver-1  |   Applying django_celery_results.0008_chordcounter... OK
webserver-1  |   Applying django_celery_results.0009_groupresult... OK
webserver-1  |   Applying django_celery_results.0010_remove_duplicate_indices... OK
webserver-1  |   Applying django_celery_results.0011_taskresult_periodic_task_name... OK
webserver-1  |   Applying documents.0001_initial... OK
webserver-1  |   Applying documents.0002_auto_20151226_1316... OK
webserver-1  |   Applying documents.0003_sender... OK
webserver-1  |   Applying documents.0004_auto_20160114_1844... OK
webserver-1  |   Applying documents.0005_auto_20160123_0313... OK
webserver-1  |   Applying documents.0006_auto_20160123_0430... OK
webserver-1  |   Applying documents.0007_auto_20160126_2114... OK
webserver-1  |   Applying documents.0008_document_file_type... OK
webserver-1  |   Applying documents.0009_auto_20160214_0040... OK
webserver-1  |   Applying documents.0010_log... OK
webserver-1  |   Applying documents.0011_auto_20160303_1929... OK
webserver-1  |   Applying documents.0012_auto_20160305_0040... OK
webserver-1  |   Applying documents.0013_auto_20160325_2111... OK
webserver-1  |   Applying documents.0014_document_checksum... OK
webserver-1  |   Applying documents.0015_add_insensitive_to_match... OK
webserver-1  |   Applying documents.0016_auto_20170325_1558... OK
webserver-1  |   Applying documents.0017_auto_20170512_0507... OK
webserver-1  |   Applying documents.0018_auto_20170715_1712... OK
webserver-1  |   Applying documents.0019_add_consumer_user... OK
webserver-1  |   Applying documents.0020_document_added... OK
webserver-1  |   Applying documents.0021_document_storage_type... OK
webserver-1  |   Applying documents.0022_auto_20181007_1420... OK
webserver-1  |   Applying documents.0023_document_current_filename... OK
webserver-1  |   Applying documents.1000_update_paperless_all... OK
webserver-1  |   Applying documents.1001_auto_20201109_1636... OK
webserver-1  |   Applying documents.1002_auto_20201111_1105... OK
webserver-1  |   Applying paperless_mail.0001_initial... OK
webserver-1  |   Applying paperless_mail.0002_auto_20201117_1334... OK
webserver-1  |   Applying paperless_mail.0003_auto_20201118_1940... OK
webserver-1  |   Applying paperless_mail.0004_mailrule_order... OK
webserver-1  |   Applying paperless_mail.0005_help_texts... OK
webserver-1  |   Applying documents.1003_mime_types... OK
webserver-1  |   Applying documents.1004_sanity_check_schedule... OK
webserver-1  |   Applying documents.1005_checksums... OK
webserver-1  |   Applying documents.1006_auto_20201208_2209... OK
webserver-1  |   Applying documents.1007_savedview_savedviewfilterrule... OK
webserver-1  |   Applying documents.1008_auto_20201216_1736... OK
webserver-1  |   Applying documents.1009_auto_20201216_2005... OK
webserver-1  |   Applying documents.1010_auto_20210101_2159... OK
webserver-1  |   Applying documents.1011_auto_20210101_2340... OK
webserver-1  |   Applying paperless_mail.0006_auto_20210101_2340... OK
webserver-1  |   Applying paperless_mail.0007_auto_20210106_0138... OK
webserver-1  |   Applying paperless_mail.0008_auto_20210516_0940... OK
webserver-1  |   Applying paperless_mail.0009_mailrule_assign_tags... OK
webserver-1  |   Applying paperless_mail.0010_auto_20220311_1602... OK
webserver-1  |   Applying paperless_mail.0011_remove_mailrule_assign_tag... OK
webserver-1  |   Applying paperless_mail.0012_alter_mailrule_assign_tags... OK
webserver-1  |   Applying paperless_mail.0009_alter_mailrule_action_alter_mailrule_folder... OK
webserver-1  |   Applying paperless_mail.0013_merge_20220412_1051... OK
webserver-1  |   Applying paperless_mail.0014_alter_mailrule_action... OK
webserver-1  |   Applying paperless_mail.0015_alter_mailrule_action... OK
webserver-1  |   Applying paperless_mail.0016_mailrule_consumption_scope... OK
webserver-1  |   Applying paperless_mail.0017_mailaccount_owner_mailrule_owner... OK
webserver-1  |   Applying paperless_mail.0018_processedmail... OK
webserver-1  |   Applying paperless_mail.0019_mailrule_filter_to... OK
webserver-1  |   Applying paperless_mail.0020_mailaccount_is_token... OK
webserver-1  |   Applying paperless_mail.0021_alter_mailaccount_password... OK
webserver-1  |   Applying paperless_mail.0022_mailrule_assign_owner_from_rule_and_more... OK
webserver-1  |   Applying paperless_mail.0023_remove_mailrule_filter_attachment_filename_and_more... OK
webserver-1  |   Applying documents.1012_fix_archive_files... OK
webserver-1  |   Applying documents.1013_migrate_tag_colour... OK
webserver-1  |   Applying documents.1014_auto_20210228_1614... OK
webserver-1  |   Applying documents.1015_remove_null_characters... OK
webserver-1  |   Applying documents.1016_auto_20210317_1351... OK
webserver-1  |   Applying documents.1017_alter_savedviewfilterrule_rule_type... OK
webserver-1  |   Applying documents.1018_alter_savedviewfilterrule_value... OK
webserver-1  |   Applying documents.1019_uisettings... OK
webserver-1  |   Applying documents.1019_storagepath_document_storage_path... OK
webserver-1  |   Applying documents.1020_merge_20220518_1839... OK
webserver-1  |   Applying documents.1021_webp_thumbnail_conversion... OK
webserver-1  |   Applying documents.1022_paperlesstask... OK
webserver-1  |   Applying documents.1023_add_comments... OK
webserver-1  |   Applying documents.1024_document_original_filename... OK
webserver-1  |   Applying documents.1025_alter_savedviewfilterrule_rule_type... OK
webserver-1  |   Applying documents.1026_transition_to_celery... OK
webserver-1  |   Applying documents.1027_remove_paperlesstask_attempted_task_and_more... OK
webserver-1  |   Applying documents.1028_remove_paperlesstask_task_args_and_more... OK
webserver-1  |   Applying documents.1029_alter_document_archive_serial_number... OK
webserver-1  |   Applying documents.1030_alter_paperlesstask_task_file_name... OK
webserver-1  |   Applying documents.1031_remove_savedview_user_correspondent_owner_and_more... OK
webserver-1  |   Applying documents.1032_alter_correspondent_matching_algorithm_and_more... OK
webserver-1  |   Applying documents.1033_alter_documenttype_options_alter_tag_options_and_more... OK
webserver-1  |   Applying documents.1034_alter_savedviewfilterrule_rule_type... OK
webserver-1  |   Applying documents.1035_rename_comment_note... OK
webserver-1  |   Applying documents.1036_alter_savedviewfilterrule_rule_type... OK
webserver-1  |   Applying documents.1037_webp_encrypted_thumbnail_conversion... OK
webserver-1  |   Applying documents.1038_sharelink... OK
webserver-1  |   Applying documents.1039_consumptiontemplate... OK
webserver-1  |   Applying documents.1040_customfield_customfieldinstance_and_more... OK
webserver-1  |   Applying documents.1041_alter_consumptiontemplate_sources... OK
webserver-1  |   Applying documents.1042_consumptiontemplate_assign_custom_fields_and_more... OK
webserver-1  |   Applying documents.1043_alter_savedviewfilterrule_rule_type... OK
webserver-1  |   Applying documents.1044_workflow_workflowaction_workflowtrigger_and_more... OK
webserver-1  |   Applying documents.1045_alter_customfieldinstance_value_monetary... OK
webserver-1  |   Applying documents.1046_workflowaction_remove_all_correspondents_and_more... OK
webserver-1  |   Applying guardian.0001_initial... OK
webserver-1  |   Applying guardian.0002_generic_permissions_index... OK
webserver-1  |   Applying paperless.0001_initial... OK
webserver-1  |   Applying paperless.0002_applicationconfiguration_app_logo_and_more... OK
webserver-1  |   Applying paperless.0003_alter_applicationconfiguration_max_image_pixels... OK
webserver-1  |   Applying sessions.0001_initial... OK
webserver-1  |   Applying socialaccount.0001_initial... OK
webserver-1  |   Applying socialaccount.0002_token_max_lengths... OK
webserver-1  |   Applying socialaccount.0003_extra_data_default_dict... OK
webserver-1  |   Applying socialaccount.0004_app_provider_id_settings... OK
webserver-1  |   Applying socialaccount.0005_socialtoken_nullable_app... OK
webserver-1  |   Applying socialaccount.0006_alter_socialaccount_extra_data... OK
webserver-1  | Running Django checks
webserver-1  | System check identified no issues (0 silenced).
webserver-1  | Search index out of date. Updating...
webserver-1  | Executing /usr/local/bin/paperless_cmd.sh
webserver-1  | 2024-04-01 19:11:52,662 INFO Set uid to user 0 succeeded
webserver-1  | 2024-04-01 19:11:52,665 INFO supervisord started with pid 1
webserver-1  | 2024-04-01 19:11:53,669 INFO spawned: 'gunicorn' with pid 202
webserver-1  | 2024-04-01 19:11:53,671 INFO spawned: 'celery' with pid 203
webserver-1  | 2024-04-01 19:11:53,674 INFO spawned: 'celery-beat' with pid 204
webserver-1  | 2024-04-01 19:11:53,677 INFO spawned: 'consumer' with pid 205
webserver-1  | 2024-04-01 19:11:53,679 INFO spawned: 'celery-flower' with pid 206
webserver-1  | Checking if we should start flower...
webserver-1  | Not starting flower
webserver-1  | 2024-04-01 19:11:53,689 INFO success: celery-flower entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
webserver-1  | 2024-04-01 19:11:53,689 INFO exited: celery-flower (exit status 0; expected)
webserver-1  | 2024-04-01 19:11:54,691 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
webserver-1  | 2024-04-01 19:11:54,691 INFO success: celery entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
webserver-1  | 2024-04-01 19:11:54,691 INFO success: celery-beat entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
webserver-1  | 2024-04-01 19:11:54,691 INFO success: consumer entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
webserver-1  | celery beat v5.3.6 (emerald-rush) is starting.
webserver-1  | [2024-04-01 21:11:57 +0200] [202] [INFO] Starting gunicorn 21.2.0
webserver-1  | [2024-04-01 21:11:57 +0200] [202] [INFO] Listening at: http://[::]:8000 (202)
webserver-1  | [2024-04-01 21:11:57 +0200] [202] [INFO] Using worker: paperless.workers.ConfigurableWorker
webserver-1  | [2024-04-01 21:11:57 +0200] [202] [INFO] Server is ready. Spawning workers
webserver-1  | [2024-04-01 21:11:57,431] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: /usr/src/paperless/consume
webserver-1  |  
webserver-1  |  -------------- celery@e9c07dcbaede v5.3.6 (emerald-rush)
webserver-1  | --- ***** ----- 
webserver-1  | -- ******* ---- Linux-6.1.0-18-amd64-x86_64-with-glibc2.36 2024-04-01 21:11:57
webserver-1  | - *** --- * --- 
webserver-1  | - ** ---------- [config]
webserver-1  | - ** ---------- .> app:         paperless:0x7fad288cae50
webserver-1  | - ** ---------- .> transport:   redis://broker:6379//
webserver-1  | - ** ---------- .> results:     
webserver-1  | - *** --- * --- .> concurrency: 1 (prefork)
webserver-1  | -- ******* ---- .> task events: ON
webserver-1  | --- ***** ----- 
webserver-1  |  -------------- [queues]
webserver-1  |                 .> celery           exchange=celery(direct) key=celery
webserver-1  |                 
webserver-1  | 
webserver-1  | [tasks]
webserver-1  |   . documents.tasks.bulk_update_documents
webserver-1  |   . documents.tasks.consume_file
webserver-1  |   . documents.tasks.index_optimize
webserver-1  |   . documents.tasks.sanity_check
webserver-1  |   . documents.tasks.train_classifier
webserver-1  |   . documents.tasks.update_document_archive_file
webserver-1  |   . paperless_mail.mail.apply_mail_action
webserver-1  |   . paperless_mail.mail.error_callback
webserver-1  |   . paperless_mail.tasks.process_mail_accounts
webserver-1  | 
webserver-1  | __    -    ... __   -        _
webserver-1  | LocalTime -> 2024-04-01 21:11:57
webserver-1  | Configuration ->
webserver-1  |     . broker -> redis://broker:6379//
webserver-1  |     . loader -> celery.loaders.app.AppLoader
webserver-1  |     . scheduler -> celery.beat.PersistentScheduler
webserver-1  |     . db -> /usr/src/paperless/data/celerybeat-schedule.db
webserver-1  |     . logfile -> [stderr]@%INFO
webserver-1  |     . maxinterval -> 5.00 minutes (300s)
webserver-1  | [2024-04-01 21:11:57,859] [INFO] [celery.beat] beat: Starting...
webserver-1  | [2024-04-01 21:11:57,879] [INFO] [celery.worker.consumer.connection] Connected to redis://broker:6379//
webserver-1  | [2024-04-01 21:11:57,906] [INFO] [celery.apps.worker] celery@e9c07dcbaede ready.
webserver-1  | [2024-04-01 21:20:00,003] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
webserver-1  | [2024-04-01 21:20:00,015] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[99248858-f29b-4f52-af0b-6abf16a527e6] received
webserver-1  | [2024-04-01 21:20:00,082] [INFO] [celery.app.trace] Task paperless_mail.tasks.process_mail_accounts[99248858-f29b-4f52-af0b-6abf16a527e6] succeeded in 0.06345375199452974s: 'No new documents were added.'
```

### Paperless-ngx version

v2.6.3

### Host OS

debian

### Installation method

Docker - official image

### Browser

CLI

### Configuration changes

PAPERLESS_AUDIT_LOG_ENABLED

### Other

started with paperless-ng and migrated to paperless-ngx

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
Not sure what you mean by "the next".  You cannot import to an existing installation.

**Comment by stumpylog** [comment]
I can reproduce this now, but I cannot figure out the root cause.

- All `ContentType` objects are deleted when an import starts: https://github.com/paperless-ngx/paperless-ngx/blob/129933ff3061e80ebd04762b66a6cb46c5992e31/src/documents/management/commands/document_importer.py#L158
- There is no duplicate value in the exported JSON for the pair `(app_label, model_name)`.  Or even just `model_name`
- So there simply isn't a way this unique constraint can be violated

**Comment by shamoon** [comment]
I think this is essentially the same as #6247, we dont support importing / exporting with audit log enabled.
