### ISSUE TITLE
[BUG] Uploading PNG file results in file not found

### ISSUE THREAD

**Issue by ronnyandre** [paperless-ngx/paperless-ngx#6264]
### Description

I have a screenshot file (PNG) that has a size of 38 MB and a dimension of 2560x27288, so a fairly big PNG.

After successful upload, Paperless starts consuming the file and suddenly quits with the following error: `chat.png: Error occurred while consuming document chat.png: InputFileError: File not found - /tmp/paperless/paperless-vfmktwuq/image-no-alpha`

### Steps to reproduce

1. Uploading file by dropping it in the GUI.
2. Wait until file is uploaded and Paperless to start consume.
3. Error pops up.

### Webserver logs

```bash
[2024-04-03 08:34:26,931] [DEBUG] [paperless.tasks] Skipping plugin CollatePlugin

[2024-04-03 08:34:26,931] [DEBUG] [paperless.tasks] Skipping plugin BarcodePlugin

[2024-04-03 08:34:26,931] [DEBUG] [paperless.tasks] Executing plugin WorkflowTriggerPlugin

[2024-04-03 08:34:26,959] [INFO] [paperless.tasks] WorkflowTriggerPlugin completed with no message

[2024-04-03 08:34:27,056] [INFO] [paperless.consumer] Consuming chat.png

[2024-04-03 08:34:27,082] [DEBUG] [paperless.consumer] Detected mime type: image/png

[2024-04-03 08:34:27,086] [INFO] [paperless.consumer] Executing pre-consume script /opt/paperless/scripts/removepassword.py

[2024-04-03 08:34:27,356] [INFO] [paperless.consumer] /opt/paperless/scripts/removepassword.py exited 0

[2024-04-03 08:34:27,405] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser

[2024-04-03 08:34:27,408] [DEBUG] [paperless.consumer] Parsing chat.png...

[2024-04-03 08:34:28,825] [WARNING] [paperless.parsing.tesseract] Error while getting DPI from image /tmp/paperless/paperless-ngxbpyj79li/chat.png: 'dpi'

[2024-04-03 08:34:28,825] [DEBUG] [paperless.parsing.tesseract] Estimated DPI 309 based on image width 2560

[2024-04-03 08:34:28,826] [INFO] [paperless.parsing.tesseract] Removing alpha layer from /tmp/paperless/paperless-ngxbpyj79li/chat.png for compatibility with img2pdf

[2024-04-03 08:34:29,648] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-vfmktwuq/image-no-alpha'), 'output_file': PosixPath('/tmp/paperless/paperless-vfmktwuq/archive.pdf'), 'use_threads': True, 'jobs': 2, 'language': 'eng', 'output_type': 'pdfa', 'progress_bar': False, 'color_conversion_strategy': 'RGB', 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-vfmktwuq/sidecar.txt'), 'image_dpi': 309}

[2024-04-03 08:34:32,947] [WARNING] [paperless.parsing.tesseract] Encountered an error while running OCR: File not found - /tmp/paperless/paperless-vfmktwuq/image-no-alpha. Attempting force OCR to get the text.

[2024-04-03 08:34:32,947] [WARNING] [paperless.parsing.tesseract] Error while getting DPI from image /tmp/paperless/paperless-ngxbpyj79li/chat.png: 'dpi'

[2024-04-03 08:34:32,947] [DEBUG] [paperless.parsing.tesseract] Estimated DPI 309 based on image width 2560

[2024-04-03 08:34:32,948] [INFO] [paperless.parsing.tesseract] Removing alpha layer from /tmp/paperless/paperless-ngxbpyj79li/chat.png for compatibility with img2pdf

[2024-04-03 08:34:32,954] [DEBUG] [paperless.parsing.tesseract] Fallback: Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-vfmktwuq/image-no-alpha'), 'output_file': PosixPath('/tmp/paperless/paperless-vfmktwuq/archive-fallback.pdf'), 'use_threads': True, 'jobs': 2, 'language': 'eng', 'output_type': 'pdfa', 'progress_bar': False, 'color_conversion_strategy': 'RGB', 'force_ocr': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-vfmktwuq/sidecar-fallback.txt'), 'image_dpi': 309}

[2024-04-03 08:34:33,057] [ERROR] [paperless.consumer] Error occurred while consuming document chat.png: InputFileError: File not found - /tmp/paperless/paperless-vfmktwuq/image-no-alpha

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/dist-packages/ocrmypdf/_validation.py", line 282, in create_input_file

    safe_symlink(options.input_file, target)

  File "/usr/local/lib/python3.11/dist-packages/ocrmypdf/helpers.py", line 171, in safe_symlink

    raise FileNotFoundError(f"trying to create a broken symlink to {input_file}")

FileNotFoundError: trying to create a broken symlink to /tmp/paperless/paperless-vfmktwuq/image-no-alpha

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/opt/paperless/src/paperless_tesseract/parsers.py", line 363, in parse

    ocrmypdf.ocr(**args)

  File "/usr/local/lib/python3.11/dist-packages/ocrmypdf/api.py", line 375, in ocr

    return run_pipeline(options=options, plugin_manager=plugin_manager)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/dist-packages/ocrmypdf/_pipelines/ocr.py", line 225, in run_pipeline

    return _run_pipeline(options, plugin_manager)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/dist-packages/ocrmypdf/_pipelines/ocr.py", line 168, in _run_pipeline

    start_input_file, original_filename = create_input_file(options, work_folder)

                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/dist-packages/ocrmypdf/_validation.py", line 305, in create_input_file

    raise InputFileError(msg) from e

ocrmypdf.exceptions.InputFileError: File not found - /tmp/paperless/paperless-vfmktwuq/image-no-alpha

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/dist-packages/ocrmypdf/_validation.py", line 282, in create_input_file

    safe_symlink(options.input_file, target)

  File "/usr/local/lib/python3.11/dist-packages/ocrmypdf/helpers.py", line 171, in safe_symlink

    raise FileNotFoundError(f"trying to create a broken symlink to {input_file}")

FileNotFoundError: trying to create a broken symlink to /tmp/paperless/paperless-vfmktwuq/image-no-alpha

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/opt/paperless/src/paperless_tesseract/parsers.py", line 414, in parse

    ocrmypdf.ocr(**args)

  File "/usr/local/lib/python3.11/dist-packages/ocrmypdf/api.py", line 375, in ocr

    return run_pipeline(options=options, plugin_manager=plugin_manager)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/dist-packages/ocrmypdf/_pipelines/ocr.py", line 225, in run_pipeline

    return _run_pipeline(options, plugin_manager)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/dist-packages/ocrmypdf/_pipelines/ocr.py", line 168, in _run_pipeline

    start_input_file, original_filename = create_input_file(options, work_folder)

                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/dist-packages/ocrmypdf/_validation.py", line 305, in create_input_file

    raise InputFileError(msg) from e

ocrmypdf.exceptions.InputFileError: File not found - /tmp/paperless/paperless-vfmktwuq/image-no-alpha

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/dist-packages/asgiref/sync.py", line 349, in main_wrap

    raise exc_info[1]

  File "/opt/paperless/src/documents/consumer.py", line 516, in try_consume_file

    document_parser.parse(self.working_copy, mime_type, self.filename)

  File "/opt/paperless/src/paperless_tesseract/parsers.py", line 426, in parse

    raise ParseError(f"{e.__class__.__name__}: {e!s}") from e

documents.parsers.ParseError: InputFileError: File not found - /tmp/paperless/paperless-vfmktwuq/image-no-alpha

Drop files to begin upload
```

### Paperless-ngx version

2.6.3

### Host OS

Debian 12 x86_64

### Installation method

Bare metal

### Other

Installed via Ttecks Proxmox helper scripts.

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
Without a sample file we cannot assist.  The test suite runs with PNG files just fine, so this is particular to your file or system.
