### ISSUE TITLE
[BUG] Documents view: Thumbnails not shown

### ISSUE THREAD

**Issue by eomanis** [paperless-ngx/paperless-ngx#629]
**Describe the bug**
Document thumbnails are not shown in the "Documents" view.
The browser indicates "image resource missing".

I found [this entry in the Paperless ArchWiki article](https://wiki.archlinux.org/title/Paperless#Thumbnail_generation_with_ImageMagick_fails), but it is not applicable to the current `imagemagick-7.1.0.29-1` package (the relevant section to be commented out does no longer exist in `/etc/ImageMagick-7/policy.xml`).
The paperless service user does **not** have any user-specific ImageMagick configuration.

Adding this directive to `/etc/ImageMagick-7/policy.xml` was not effective either:
`<policy domain="delegate" rights="all" pattern="gs" />`

**To Reproduce**
1. Log into paperless-ngx as administrator
2. Switch to the "Documents" view
3. Notice that the thumbnail pictures are missing

**Expected behavior**
The "Documents" view should display the documents' thumbnails, and there should be no related tracebacks in the server log.

**Screenshots**
![Screenshot from 2022-04-02 23-30-36](https://user-images.githubusercontent.com/5933155/161401991-3d9c79ac-1eaa-46d7-98e4-ae25da567e28.png)

**Webserver logs**
```
uwsgi[214625]: [2022-04-02 21:29:41,628] [ERROR] [django.request] Internal Server Error: /api/documents/279/thumb/
uwsgi[214625]: Traceback (most recent call last):
uwsgi[214625]:   File "/usr/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
uwsgi[214625]:     response = get_response(request)
uwsgi[214625]:   File "/usr/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
uwsgi[214625]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
uwsgi[214625]:   File "/usr/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
uwsgi[214625]:     return view_func(*args, **kwargs)
uwsgi[214625]:   File "/usr/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
uwsgi[214625]:     return self.dispatch(request, *args, **kwargs)
uwsgi[214625]:   File "/usr/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
uwsgi[214625]:     response = self.handle_exception(exc)
uwsgi[214625]:   File "/usr/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
uwsgi[214625]:     self.raise_uncaught_exception(exc)
uwsgi[214625]:   File "/usr/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
uwsgi[214625]:     raise exc
uwsgi[214625]:   File "/usr/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
uwsgi[214625]:     response = handler(request, *args, **kwargs)
uwsgi[214625]:   File "/usr/lib/python3.10/site-packages/django/views/decorators/cache.py", line 35, in _cache_controlled
uwsgi[214625]:     raise TypeError(
uwsgi[214625]: TypeError: cache_control didn't receive an HttpRequest. If you are decorating a classmethod, be sure to use @method_decorator.
uwsgi[214625]: [pid: 214625|app: 0|req: 687/687] 192.168.153.85 () {56 vars in 976 bytes} [Sat Apr  2 21:29:41 2022] GET /api/documents/279/thumb/ => generated 145 bytes in 9 msecs (HTTP/2.0 …switches on core 0)
```

**Relevant information**
 - Host OS: Arch Linux, most recently updated 2022-04-02 14:40 UTC, `paperless-ngx` and all its AUR dependencies have been clean-rebuilt with `yay -S --rebuildtree paperless-ngx`
 - Browser: Firefox 98.0.2 (64-bit)
 - Version: `paperless-ngx-1.6.0-1` `uwsgi-2.0.20-6` `uwsgi-plugin-python-2.0.20-6` `imagemagick-7.1.0.29-1` `python-django-4.0.3-1`
 - Installation method: Bare metal, nginx -> UNIX socket -> uwsgi-plugin-python

**paperless.conf**
```
PAPERLESS_REDIS=unix:///srv/paperless/redis/redis.sock

PAPERLESS_CONSUMPTION_DIR=/srv/paperless/add
PAPERLESS_DATA_DIR=/srv/paperless/data
PAPERLESS_MEDIA_ROOT=/srv/paperless/media
PAPERLESS_STATICDIR=/srv/paperless/webroot/static

PAPERLESS_SECRET_KEY="XXXXXXXXXXXXXXXXXX"
PAPERLESS_CORS_ALLOWED_HOSTS=http://localhost:8000
PAPERLESS_STATIC_URL=/static/

PAPERLESS_OCR_LANGUAGE=deu
PAPERLESS_CONVERT_TMPDIR=/srv/paperless/tmp

PAPERLESS_SCRATCH_DIR=/srv/paperless/uploads

PAPERLESS_TASK_WORKERS=2
PAPERLESS_CONSUMER_POLLING=10
```

**nginx.conf (excerpt)**
```
# ==== Paperless =================================================
server {
    listen                          6544 ssl http2;
    listen                          [::]:6544 ssl http2;
    server_name                     my-server;

    root                            /srv/paperless/webroot;

    # Use a generic unsigned certificate
    ssl_certificate                 /srv/certs/default.unsigned.cert.certificate.pem;
    ssl_certificate_key             /srv/certs/default.unsigned.cert.key.pem;

    # Allow uploads larger than the default 1m (MiB)
    client_max_body_size            30m;

    # Static content: Serve this directly
    # To generate static content, run as user "paperless" and if applicable in the paperless venv:
    #   /usr/share/paperless/src/manage.py collectstatic --clear --no-input
    location /static/ {
        expires                         1h;
        try_files                       $uri $uri/ =404;
    }
    # All other requests: Delegate to the application server
    location / {
        uwsgi_pass                      unix:/srv/paperless/socket/paperless.sock;
        include                         uwsgi_params;
    }
}
```

**nginx include "uwsgi_params"**
```
uwsgi_param  QUERY_STRING       $query_string;
uwsgi_param  REQUEST_METHOD     $request_method;
uwsgi_param  CONTENT_TYPE       $content_type;
uwsgi_param  CONTENT_LENGTH     $content_length;

uwsgi_param  REQUEST_URI        $request_uri;
uwsgi_param  PATH_INFO          $document_uri;
uwsgi_param  DOCUMENT_ROOT      $document_root;
uwsgi_param  SERVER_PROTOCOL    $server_protocol;
uwsgi_param  REQUEST_SCHEME     $scheme;
uwsgi_param  HTTPS              $https if_not_empty;

uwsgi_param  REMOTE_ADDR        $remote_addr;
uwsgi_param  REMOTE_PORT        $remote_port;
uwsgi_param  SERVER_PORT        $server_port;
uwsgi_param  SERVER_NAME        $server_name;
```

**Comment by stumpylog** [comment]
I'm not sure how Arch packaging works, but 1.6.0 wasn't ready for Django 4.  It used 3.2.12 still.  In dev, we've updated and fixed this issue.

Maybe this is an Arch or packaging issue?

**Comment by eomanis** [comment]
> Maybe this is an Arch or packaging issue?

Possibly, Arch is a challenging distribution to package for.

Seems like my options are
1. Stop using the AUR package and migrate to a virtual environment, having to mind future updates myself
2. Do nothing and sit this one out until the next release, continuing to mooch off the package maintainer's work

You do have it covered in dev, much appreciated.

**Comment by ForsakenNGS** [comment]
Same here on the Arch AUR build.

@stumpylog Could you point out the commit that fixed the issue or is it too complicated to cherry-pick?

**Comment by stumpylog** [comment]
The pull request was this one: https://github.com/paperless-ngx/paperless-ngx/pull/497

The only change to code was in src/documents/views.py
