### ISSUE TITLE
[BUG] Uploading a document using REST API results in error 500 about remove_inbox_tags

### ISSUE THREAD

**Issue by LordGaav** [paperless-ngx/paperless-ngx#6316]
### Description

When uploading a document using the REST API, an error 500 is thrown and the logs contain a message about a Django serializer trying to pass `remove_inbox_tags` to the model layer, where the field is not allowed.

The POST body is a multipart form data with the following contents, the PDF file is truncated:

```
Host:             paperless.xxx.nl
Accept-Encoding:  gzip, deflate
Connection:       keep-alive
User-Agent:       python-httpx/0.27.0
Authorization:    Token xxx
Accept:           application/json; version=4
Content-Length:   153606
Content-Type:     multipart/form-data; boundary=6d6916394b172f9cdadd8b60748ea613

--6d6916394b172f9cdadd8b60748ea613
Content-Disposition: form-data; name="title"

40 - Originele factuur - xxx.pdf
--6d6916394b172f9cdadd8b60748ea613
Content-Disposition: form-data; name="created"

2021-10-30T20:15:05.234987Z
--6d6916394b172f9cdadd8b60748ea613
Content-Disposition: form-data; name="storage_path"


--6d6916394b172f9cdadd8b60748ea613
Content-Disposition: form-data; name="document_type"

1
--6d6916394b172f9cdadd8b60748ea613
Content-Disposition: form-data; name="correspondent"

28
--6d6916394b172f9cdadd8b60748ea613
Content-Disposition: form-data; name="tags"

13
--6d6916394b172f9cdadd8b60748ea613
Content-Disposition: form-data; name="custom_fields"

2
--6d6916394b172f9cdadd8b60748ea613
Content-Disposition: form-data; name="custom_fields"

1
--6d6916394b172f9cdadd8b60748ea613
Content-Disposition: form-data; name="document"; filename="40 - Originele factuur - xxx.pdf"
Content-Type: application/pdf

%PDF-1.4
```

### Steps to reproduce

This is the most minimal case I can  reproduce the error with, substitute a PDF file, a token and an API endpoint:

```
$ curl -XPOST -H "Authorization: Token xxx" -H "Accept: application/json; version=4" -F title=foo -F correspondent= -F document_type= -F storage_path= -F document=@/tmp/xxx.pdf https://paperless.xxx.nl/api/documents/

<!doctype html>
<html lang="en">
<head>
  <title>Server Error (500)</title>
</head>
<body>
  <h1>Server Error (500)</h1><p></p>
</body>
```

### Webserver logs

```bash
[2024-04-07 16:06:53,075] [ERROR] [django.request] Internal Server Error: /api/documents/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 962, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 656, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 567, in __init__
    raise TypeError(
TypeError: Document() got unexpected keyword arguments: 'remove_inbox_tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/usr/local/lib/python3.11/site-packages/drf_writable_nested/mixins.py", line 233, in save
    return super(BaseNestedModelSerializer, self).save(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/paperless/src/documents/serialisers.py", line 257, in create
    instance = super().create(validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 981, in create
    raise TypeError(msg)
TypeError: Got a `TypeError` when calling `Document.objects.create()`. This may be because you have a writable field on the serializer class that is not a valid argument to `Document.objects.create()`. You may need to make the field read-only, or override the DocumentSerializer.create() method to handle this correctly.
Original exception was:
 Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 962, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 656, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 567, in __init__
    raise TypeError(
TypeError: Document() got unexpected keyword arguments: 'remove_inbox_tags'
```

### Paperless-ngx version

2.7.0

### Host OS

Debian GNU/Linux 12, Linux foo 6.1.0-18-cloud-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
That is not the correct endpoint, please review the documentation

**Comment by LordGaav** [comment]
You're correct, my bad. For others ending up in this issue after searching, the correct endpoint is `/api/documents/post_document/` and the docs are here https://docs.paperless-ngx.com/api/#file-uploads .
