### ISSUE TITLE
[BUG] [ERROR] [paperless.handlers] Setting PaperlessTask started failed

### ISSUE THREAD

**Issue by NetRat88** [paperless-ngx/paperless-ngx#6367]
### Description

During consumption of a large PDF file (20MB) and only 31 pages with 10 barcode splitting pages between I received the following error with a bad consumption duration:

[ERROR] [paperless.handlers] Setting PaperlessTask started failed

Consumption duration: 60 minutes        
Start consumption:                     22:11:06
Add to queue:                          22:11:36 (because of the setting PAPERLESS_CONSUMER_POLLING_DELAY=30)
Executing BarcodePlugin using PYZBAR:  22:11:37 (because of the setting PAPERLESS_CONSUMER_ENABLE_BARCODES=true)
Error accoured:                        22:20:41,858] [ERROR] [paperless.handlers] Setting PaperlessTask started failed
Barcode splitting complete:            22:54:09 **(34 minutes!)**
BarcodePlugin completed:               23:06:21 **(55 minutes!)**
WorkflowTriggerPlugin completed:       23:06:22
Saving record to database:             23:07:31
Consumption finished:                  23:07:33

In this #6366 Discussion I also described different examples for my bad performance on my Raspbery Pi 4 but in this case I receved the error as you can see in Webserver logs.

### Steps to reproduce

1. Upload large PDF File (20MB), with 31 pages and with 10 barcode split pages between

### Webserver logs

```bash
[2024-04-10 22:11:06,067] [DEBUG] [paperless.management.consumer] Waiting for file /usr/src/paperless/consume/UserA/scan_20240410_014344.pdf to remain unmodified

[2024-04-10 22:11:36,086] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/UserA/scan_20240410_014344.pdf to the task queue.

[2024-04-10 22:11:37,100] [DEBUG] [paperless.tasks] Skipping plugin CollatePlugin

[2024-04-10 22:11:37,104] [DEBUG] [paperless.tasks] Executing plugin BarcodePlugin

[2024-04-10 22:11:37,108] [DEBUG] [paperless.barcodes] Scanning for barcodes using PYZBAR

[2024-04-10 22:17:11,054] [DEBUG] [paperless.barcodes] Barcode of type CODE39 found: PATCHT

[2024-04-10 22:18:14,066] [DEBUG] [paperless.barcodes] Barcode of type CODE39 found: PATCHT

[2024-04-10 22:19:08,614] [DEBUG] [paperless.barcodes] Barcode of type CODE39 found: PATCHT

[2024-04-10 22:19:11,960] [DEBUG] [paperless.barcodes] Barcode of type CODE39 found: PATCHT

[2024-04-10 22:19:14,853] [DEBUG] [paperless.barcodes] Barcode of type CODE39 found: PATCHT

[2024-04-10 22:19:34,367] [DEBUG] [paperless.barcodes] Barcode of type CODE39 found: PATCHT

[2024-04-10 22:19:47,292] [DEBUG] [paperless.barcodes] Barcode of type I25 found: 0629145641

[2024-04-10 22:20:11,885] [DEBUG] [paperless.barcodes] Barcode of type I25 found: 0000000042

[2024-04-10 22:20:48,705] [DEBUG] [paperless.barcodes] Barcode of type CODE39 found: PATCHT

[2024-04-10 22:20:41,858] [ERROR] [paperless.handlers] Setting PaperlessTask started failed

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 289, in ensure_connection

    self.connect()

  File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner

    return func(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 270, in connect

    self.connection = self.get_new_connection(conn_params)

                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner

    return func(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 247, in get_new_connection

    connection = Database.connect(**conn_params)

                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/MySQLdb/__init__.py", line 121, in Connect

    return Connection(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/MySQLdb/connections.py", line 195, in __init__

    super().__init__(*args, **kwargs2)

MySQLdb.OperationalError: (2005, "Unknown server host 'db' (-3)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/signals/handlers.py", line 814, in task_prerun_handler

    task_instance = PaperlessTask.objects.filter(task_id=task_id).first()

                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1057, in first

    for obj in queryset[:1]:

  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 398, in __iter__

    self._fetch_all()

  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all

    self._result_cache = list(self._iterable_class(self))

                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__

    results = compiler.execute_sql(

              ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1560, in execute_sql

    cursor = self.connection.cursor()

             ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner

    return func(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 330, in cursor

    return self._cursor()

           ^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 306, in _cursor

    self.ensure_connection()

  File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner

    return func(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 288, in ensure_connection

    with self.wrap_database_errors:

  File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__

    raise dj_exc_value.with_traceback(traceback) from exc_value

  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 289, in ensure_connection

    self.connect()

  File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner

    return func(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 270, in connect

    self.connection = self.get_new_connection(conn_params)

                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner

    return func(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 247, in get_new_connection

    connection = Database.connect(**conn_params)

                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/MySQLdb/__init__.py", line 121, in Connect

    return Connection(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/MySQLdb/connections.py", line 195, in __init__

    super().__init__(*args, **kwargs2)

django.db.utils.OperationalError: (2005, "Unknown server host 'db' (-3)")

[2024-04-10 22:26:57,652] [DEBUG] [paperless.barcodes] Barcode of type CODE39 found: PATCHT

[2024-04-10 22:26:59,048] [DEBUG] [paperless.barcodes] Barcode of type I25 found: 40002104538142

[2024-04-10 22:27:00,229] [DEBUG] [paperless.barcodes] Barcode of type I25 found: 40002104538142

[2024-04-10 22:27:05,754] [DEBUG] [paperless.barcodes] Barcode of type CODE39 found: PATCHT

[2024-04-10 22:54:04,305] [DEBUG] [paperless.barcodes] Starting new document at idx 2

[2024-04-10 22:54:04,332] [DEBUG] [paperless.barcodes] Starting new document at idx 7

[2024-04-10 22:54:04,336] [DEBUG] [paperless.barcodes] Starting new document at idx 14

[2024-04-10 22:54:04,339] [DEBUG] [paperless.barcodes] Starting new document at idx 16

[2024-04-10 22:54:04,342] [DEBUG] [paperless.barcodes] Starting new document at idx 18

[2024-04-10 22:54:04,346] [DEBUG] [paperless.barcodes] Starting new document at idx 20

[2024-04-10 22:54:04,350] [DEBUG] [paperless.barcodes] Starting new document at idx 25

[2024-04-10 22:54:04,354] [DEBUG] [paperless.barcodes] Starting new document at idx 33

[2024-04-10 22:54:04,360] [DEBUG] [paperless.barcodes] Starting new document at idx 36

[2024-04-10 22:54:04,852] [DEBUG] [paperless.barcodes] Split into 10 new documents

[2024-04-10 22:54:04,965] [DEBUG] [paperless.barcodes] pdf no:0 has 2 pages

[2024-04-10 22:54:05,344] [DEBUG] [paperless.barcodes] pdf no:1 has 4 pages

[2024-04-10 22:54:05,443] [DEBUG] [paperless.barcodes] pdf no:2 has 6 pages

[2024-04-10 22:54:05,503] [DEBUG] [paperless.barcodes] pdf no:3 has 1 pages

[2024-04-10 22:54:05,516] [DEBUG] [paperless.barcodes] pdf no:4 has 1 pages

[2024-04-10 22:54:05,526] [DEBUG] [paperless.barcodes] pdf no:5 has 1 pages

[2024-04-10 22:54:05,554] [DEBUG] [paperless.barcodes] pdf no:6 has 4 pages

[2024-04-10 22:54:05,634] [DEBUG] [paperless.barcodes] pdf no:7 has 7 pages

[2024-04-10 22:54:05,674] [DEBUG] [paperless.barcodes] pdf no:8 has 2 pages

[2024-04-10 22:54:05,701] [DEBUG] [paperless.barcodes] pdf no:9 has 3 pages

[2024-04-10 22:54:09,148] [INFO] [paperless.barcodes] Created new task e4b86d82-7607-4437-a7a8-7c9f3d15727d for scan_20240410_014344_document_0.pdf

[2024-04-10 22:54:09,228] [INFO] [paperless.barcodes] Created new task 435cf86c-f7f6-41fc-a84d-a261f1c7e8f1 for scan_20240410_014344_document_1.pdf

[2024-04-10 22:54:09,303] [INFO] [paperless.barcodes] Created new task 5b045ccb-ab12-477c-9576-972eaddfe23c for scan_20240410_014344_document_2.pdf

[2024-04-10 22:54:09,382] [INFO] [paperless.barcodes] Created new task 331c1810-263a-47bf-ad26-8c8fc0cfd0a3 for scan_20240410_014344_document_3.pdf

[2024-04-10 22:54:09,437] [INFO] [paperless.barcodes] Created new task 3cc21ce6-e2df-4c3e-b9dc-b867cf1040f1 for scan_20240410_014344_document_4.pdf

[2024-04-10 22:54:09,469] [INFO] [paperless.barcodes] Created new task b644e639-47fb-477c-8600-874f4ec135f4 for scan_20240410_014344_document_5.pdf

[2024-04-10 22:54:09,498] [INFO] [paperless.barcodes] Created new task 5ae073d1-6386-4765-811b-d8e8118bb8e3 for scan_20240410_014344_document_6.pdf

[2024-04-10 22:54:09,537] [INFO] [paperless.barcodes] Created new task f651bb6d-4d72-41cb-ac95-3a2c0eb400a0 for scan_20240410_014344_document_7.pdf

[2024-04-10 22:54:09,714] [INFO] [paperless.barcodes] Created new task b0f7f02b-d963-4466-bd75-7a9f1a5e7e70 for scan_20240410_014344_document_8.pdf

[2024-04-10 22:54:09,735] [INFO] [paperless.barcodes] Created new task bd112602-2ae4-4338-bfd2-7a13af196f9f for scan_20240410_014344_document_9.pdf

[2024-04-10 22:54:09,884] [INFO] [paperless.tasks] BarcodePlugin requested task exit: Barcode splitting complete!
```

### Paperless-ngx version

2.7.2

### Host OS

Raspberry Pi 'arm 64'

### Installation method

Docker - official image

### Configuration changes

`PAPERLESS_REDIS=redis://broker:6379 PAPERLESS_DBENGINE=mariadb PAPERLESS_DBHOST=db PAPERLESS_DBUSER=***** PAPERLESS_DBPASS=**** PAPERLESS_DBPORT=**** PAPERLESS_TIKA_ENABLED=1 PAPERLESS_TIKA_GOTENBERG_ENDPOINT=http://gotenberg:3000 PAPERLESS_TIKA_ENDPOINT=http://tika:9998 PAPERLESS_ADMIN_USER=admin PAPERLESS_ADMIN_PASSWORD=***** PAPERLESS_UserAE_ZONE=Europe/Berlin PAPERLESS_OCR_LANGUAGE=deu PAPERLESS_SECRET_KEY=**** PAPERLESS_FILENAME_FORMAT="{created_year}/{correspondent}/{title}_{created_year}{created_month}{created_day}" PAPERLESS_FILENAME_FORMAT_REMOVE_NONE=true PAPERLESS_CONSUMER_POLLING=30 PAPERLESS_CONSUMER_POLLING_DELAY=30 PAPERLESS_CONSUMER_POLLING_RETRY_COUNT=20 PAPERLESS_OCR_USER_ARGS="{"invalidate_digital_signatures": true}" PAPERLESS_CONSUMER_RECURSIVE=true PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS=true PAPERLESS_POST_CONSUME_SCRIPT="/usr/src/paperless/scripts/post-consumption.sh" PAPERLESS_CONSUMER_ENABLE_BARCODES=true PAPERLESS_CONSUMER_ENABLE_ASN_BARCODE=true  #Performance settings siehe https://docs.paperless-ngx.com/setup/#less-powerful-devices PAPERLESS_OCR_PAGES=1 PAPERLESS_TASK_WORKERS=2 PAPERLESS_THREADS_PER_WORKER=1 PAPERLESS_OCR_CLEAN=none PAPERLESS_OCR_SKIP_ARCHIVE_FILE=with_text PAPERLESS_WEBSERVER_WORKERS=1 PAPERLESS_ENABLE_NLTK=false

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Your database crashed, certainly seems like a resource issue, not a software bug. Perhaps a RPi is not the right device for you to host with
