### ISSUE TITLE
[BUG] Exception: invalid png: 5068069 1024104657 5080249

### ISSUE THREAD

**Issue by Kuinox** [paperless-ngx/paperless-ngx#638]
**Describe the bug**
When I upload a certain document, I got this error, and I can see an exception in the log.
Document is uploaded fine through jpeg

This document has an high pixel count(2505x3507), maybe it cause the issue ?
I cannot share the png as it contain personal data, and censoring it make the error disapear.

**Expected behavior**

The document is uploaded.

**Screenshots**
![image](https://user-images.githubusercontent.com/18743295/161449939-09dde3a1-3fac-463b-8f83-a49506a81c68.png)

**Webserver logs**
```
21:25:41 [Q] ERROR Failed [Scan_20220403_2.png] - Scan_20220403_2.png: Error while consuming document Scan_20220403_2.png: Exception: invalid png: 5068069 1024104657 5080249 : Traceback (most recent call last):
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 249, in parse
    ocrmypdf.ocr(**args)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/api.py", line 337, in ocr
    return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 365, in run_pipeline
    origin_pdf = triage(
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 142, in triage
    triage_image_file(input_file, output_file, options)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 98, in triage_image_file
    img2pdf.convert(
  File "/usr/local/lib/python3.9/site-packages/img2pdf.py", line 2263, in convert
    ) in read_images(
  File "/usr/local/lib/python3.9/site-packages/img2pdf.py", line 1589, in read_images
    pngidat, palette = parse_png(rawdata)
  File "/usr/local/lib/python3.9/site-packages/img2pdf.py", line 1433, in parse_png
    raise Exception("invalid png: %d %d %d" % (i, n, len(rawdata)))
Exception: invalid png: 5068069 1024104657 5080249

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 266, in main_wrap
    raise exc_info[1]
  File "/usr/src/paperless/src/documents/consumer.py", line 245, in try_consume_file
    document_parser.parse(self.path, mime_type, self.filename)
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 301, in parse
    raise ParseError(f"{e.__class__.__name__}: {str(e)}")
documents.parsers.ParseError: Exception: invalid png: 5068069 1024104657 5080249

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django_q/cluster.py", line 432, in worker
    res = f(*task["args"], **task["kwargs"])
  File "/usr/src/paperless/src/documents/tasks.py", line 70, in consume_file
    document = Consumer().try_consume_file(
  File "/usr/src/paperless/src/documents/consumer.py", line 262, in try_consume_file
    self._fail(
  File "/usr/src/paperless/src/documents/consumer.py", line 69, in _fail
    raise ConsumerError(f"{self.filename}: {log_message or message}")
documents.consumer.ConsumerError: Scan_20220403_2.png: Error while consuming document Scan_20220403_2.png: Exception: invalid png: 5068069 1024104657 5080249
```

**Relevant information**
 - Debian Buster
 - Firefox
 - Version 1.6.0 
 - Installation method: Docker
 - Any configuration changes: added a reverse proxy on top of it, and changed static & base URL.

**Comment by stumpylog** [comment]
This looks like the scanner or creator of this file created a broken PNG, or at least one an upstream considers broken.  It's complaining because [`5068069 + 1024104657 > 5080249`](https://gitlab.mister-muffin.de/josch/img2pdf/src/commit/e8ca53738fb248de739c19ba426cf7569115a8c4/src/img2pdf.py#L1453).  I think that means the PNG is saying there's more data in the file than possible.

Could you try this with the file:
```
from PIL import Image

v_image = Image.open("Scan_20220403_2.png")
v_image.verify()
```

**Comment by Kuinox** [comment]
![image](https://user-images.githubusercontent.com/18743295/161647388-0779b907-3d35-4342-accb-52f73a37deb3.png)
Returns nothing. I guess no error ?
The image open fine in viewers.
It was scanned (with probably too high DPI), through the windows scanner app.
