### ISSUE TITLE
[BUG] Mail support not working for Outlook

### ISSUE THREAD

**Issue by amritanshu-pandey** [paperless-ngx/paperless-ngx#643]
### Description

I have configured an imap accont for Outlook.com (Exchange) in the Paperless-ngx app. It is not able to search the mailbox and I can see the following error in the logs:

```
[2022-04-04 21:57:52,564] [ERROR] [paperless_mail] Rule <RULE-NAME>: Error while processing rule: Response status "OK" expected, but "NO" received. Data: [b'[BADCHARSET (US-ASCII)] The specified charset is not supported.']
Traceback (most recent call last):
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 177, in handle_mail_account
    total_processed_files += self.handle_mail_rule(M, rule)
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 220, in handle_mail_rule
    for message in messages:
  File "/usr/local/lib/python3.9/site-packages/imap_tools/mailbox.py", line 145, in fetch
    nums = tuple((reversed if reverse else iter)(self.numbers(criteria, charset)))[limit_range]
  File "/usr/local/lib/python3.9/site-packages/imap_tools/mailbox.py", line 84, in numbers
    check_command_status(search_result, MailboxNumbersError)
  File "/usr/local/lib/python3.9/site-packages/imap_tools/utils.py", line 45, in check_command_status
    raise exception(command_result=command_result, expected=expected)
imap_tools.errors.MailboxNumbersError: Response status "OK" expected, but "NO" received. Data: [b'[BADCHARSET (US-ASCII)] The specified charset is not supported.']
```

### Expected behavior

Mailbox is scanned and relevant attachments are downloaded and tagged

### Steps to reproduce

1. Configure an Outlook.com mail account
2. Create a rule that uses account configured in step 1
3. Wait to see the error in logs

### Webserver logs

```bash
[2022-04-04 21:57:52,564] [ERROR] [paperless_mail] Rule amrit-paperless@outlook.com.Little Zak Deduction: Error while processing rule: Response status "OK" expected, but "NO" received. Data: [b'[BADCHARSET (US-ASCII)] The specified charset is not supported.']
Traceback (most recent call last):
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 177, in handle_mail_account
    total_processed_files += self.handle_mail_rule(M, rule)
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 220, in handle_mail_rule
    for message in messages:
  File "/usr/local/lib/python3.9/site-packages/imap_tools/mailbox.py", line 145, in fetch
    nums = tuple((reversed if reverse else iter)(self.numbers(criteria, charset)))[limit_range]
  File "/usr/local/lib/python3.9/site-packages/imap_tools/mailbox.py", line 84, in numbers
    check_command_status(search_result, MailboxNumbersError)
  File "/usr/local/lib/python3.9/site-packages/imap_tools/utils.py", line 45, in check_command_status
    raise exception(command_result=command_result, expected=expected)
imap_tools.errors.MailboxNumbersError: Response status "OK" expected, but "NO" received. Data: [b'[BADCHARSET (US-ASCII)] The specified charset is not supported.']
```

### Paperless-ngx version

1.6.0

### Host OS

Synology DSM 7

### Browser

Edge

### Installation method

Docker

**Comment by amritanshu-pandey** [comment]
Not a bug! Outlook supports US-ASCII character set instead of UTF8. It can be configured in the screen where email accounts are setup:

![image](https://user-images.githubusercontent.com/5570314/161668774-abe58b89-975e-4e78-808c-f087a36fb176.png)
