### ISSUE TITLE
Permission denied: '<PAPERLESS_CONSUMPTION_DIR>/__paperless_write_test_523__'

### ISSUE THREAD

**Issue by 0x6d61726b** [paperless-ngx/paperless-ngx#6458]
### Description

The path_check in checks.py fails with the following error message:
```
# sudo -Hu paperless ../.local/bin/python3 manage.py migrate
Traceback (most recent call last):
  File "/opt/paperless/src/paperless/checks.py", line 35, in path_check
    with open(test_file, "w"):
         ^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/mnt/scan01/__paperless_write_test_523__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/paperless/src/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/paperless/.local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/paperless/.local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/paperless/.local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/paperless/.local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/paperless/.local/lib/python3.11/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/paperless/.local/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 100, in handle
    self.check(databases=[database])
  File "/opt/paperless/.local/lib/python3.11/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "/opt/paperless/.local/lib/python3.11/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/paperless/src/paperless/checks.py", line 67, in paths_check
    + path_check("PAPERLESS_CONSUMPTION_DIR", settings.CONSUMPTION_DIR)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/paperless/src/paperless/checks.py", line 40, in path_check
    dir_owner = pwd.getpwuid(dir_stat.st_uid).pw_name
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'getpwuid(): uid not found: 1007'
```

It is understandable that the access to the specified directory fails, because access to the directory is limited;
```
# ls /mnt/
drwxr-xr-x  5 root      root          68 Feb 16 20:16 .
drwxr-xr-x 18 root      root        4.0K Feb 16 00:43 ..
drwxrwx---  2      1007 samba-users    6 Apr 20 09:26 scan01
```
... however the configuration works, because `paperless-consumer` runs with group rw access:
```
# cat /etc/systemd/system/paperless-consumer.service
...
[Service]
User=paperless
Group=samba-users
...
```

When using "default" access permissions, the paperless update procedure running `python3 manage.py migrate` works, however I think that I am not the only one that has non-default directory access permissions.

For a quick+bad workaround, I have commented out `with open(test_file, "w"):` in `checks.py` to pass this test and then the migration ran successful.

### Steps to reproduce

Run `python3 manage.py migrate` with non-standard access permissions described in the "Description" field.

### Webserver logs

```bash
none
```

### Paperless-ngx version

2.7.2

### Host OS

Debian 12.5

### Installation method

Bare metal

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
Paperless requires write access to the consume folder.  This is not a bug
