### ISSUE TITLE
[BUG] Document_Exporter crashes and needs to be started again.

### ISSUE THREAD

**Issue by haldi4803** [paperless-ngx/paperless-ngx#6478]
### Description

Hello,
I've moved my Docker Folders from a Synology System to a Windows System, everything started fine, web interface works and does its job.
So i've tried the [Document Exporter](https://docs.paperless-ngx.com/administration/#exporter) to get all those files to a Truenas System... because i can't use postgress 16 db there.

Running the Command `docker exec paperless-webserver-1 document_exporter  ../export` works until i hit a multipaged PDF file, then it crashes with this error:
```
C:\Users\VM\Desktop\paperless\config>docker exec paperless-webserver-1 document_exporter  ../export
 61%|██████    | 59/97 [00:18<00:11,  3.17it/s]
Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/paperless/src/documents/management/commands/document_exporter.py", line 206, in handle
    self.dump(options["no_progress_bar"])
  File "/usr/src/paperless/src/documents/management/commands/document_exporter.py", line 422, in dump
    self.check_and_copy(
  File "/usr/src/paperless/src/documents/management/commands/document_exporter.py", line 517, in check_and_copy
    copy_file_with_basic_stats(source, target)
  File "/usr/src/paperless/src/documents/utils.py", line 48, in copy_file_with_basic_stats
    shutil.copy(source, dest)
  File "/usr/local/lib/python3.11/shutil.py", line 431, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.11/shutil.py", line 269, in copyfile
    _fastcopy_sendfile(fsrc, fdst)
  File "/usr/local/lib/python3.11/shutil.py", line 164, in _fastcopy_sendfile
    raise err
  File "/usr/local/lib/python3.11/shutil.py", line 144, in _fastcopy_sendfile
    sent = os.sendfile(outfd, infd, offset, blocksize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 5] Input/output error: '/usr/src/paperless/media/documents/archive/0000061.pdf' -> '/usr/src/paperless/export/2022-10-01 Hans 2023 Police.pdf-archive.pdf'
```
the thing is, if you rund the exact same export command AGAIN it just continues with the next file. So to get it working you'd have to spam the command for every document that causes an issue.
until finally:
C:\Users\VM\Desktop\paperless\config>docker exec paperless-webserver-1 document_exporter  ../export
100%|██████████| 97/97 [00:06<00:00, 14.05it/s]

at least the import worked flawless.
```
root@paperless-ngx-5cb6665dcf-9r66k:/usr/src/paperless/data# document_importer /usr/src/paperless/data/export
Found existing user(s), this might indicate a non-empty installation
Checking the manifest
Installed 323 object(s) from 1 fixture(s)
Copy files into paperless...
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 97/97 [00:00<00:00, 203.03it/s]
Updating search index...
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 97/97 [00:00<00:00, 105.53it/s]
root@paperless-ngx-5cb6665dcf-9r66k:/usr/src/paperless/data# 
```

Docker Compose file:
```
# docker-compose file for running paperless from the docker container registry.
# This file contains everything paperless needs to run.
# Paperless supports amd64, arm and arm64 hardware.
#
# All compose files of paperless configure paperless in the following way:
#
# - Paperless is (re)started on system boot, if it was running before shutdown.
# - Docker volumes for storing data are managed by Docker.
# - Folders for importing and exporting files are created in the same directory
#   as this file and mounted to the correct folders inside the container.
# - Paperless listens on port 8000.
#
# In addition to that, this docker-compose file adds the following optional
# configurations:
#
# - Instead of SQLite (default), PostgreSQL is used as the database server.
# - Apache Tika and Gotenberg servers are started with paperless and paperless
#   is configured to use these services. These provide support for consuming
#   Office documents (Word, Excel, Power Point and their LibreOffice counter-
#   parts.
#
# To install and update paperless with this file, do the following:
#
# - Copy this file as 'docker-compose.yml' and the files 'docker-compose.env'
#   and '.env' into a folder.
# - Run 'docker-compose pull'.
# - Run 'docker-compose run --rm webserver createsuperuser' to create a user.
# - Run 'docker-compose up -d'.
#
# For more extensive installation and update instructions, refer to the
# documentation.

version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/postgres:16
    restart: unless-stopped
    volumes:
      - "C:/Users/VM/Desktop/paperless/db:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - "8008:8000"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - "C:/Users/VM/Desktop/paperless/data:/usr/src/paperless/data"
      - "C:/Users/VM/Desktop/paperless/media:/usr/src/paperless/media"
      - "C:/Users/VM/Desktop/paperless/export:/usr/src/paperless/export"
      - "C:/Users/VM/Desktop/paperless/consume:/usr/src/paperless/consume"
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.8
    restart: unless-stopped

    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped

volumes:
  redisdata:
```

Can anyone else reproduce this issue?
If not please close.

### Steps to reproduce

1. Export Documents on Windows

### Webserver logs

```bash
none
```

### Paperless-ngx version

2.7.2

### Host OS

Windows 10

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
The exporter does not care at all about the type of file, PDF, multi paged, etc.  This is something specific to your own setup.  If I had to guess, this is Windows related, given that is not a tested or officially supported host.
