### ISSUE TITLE
[BUG] aaa.pdf: Error occurred while consuming document aaa.pdf: SubprocessOutputError: Ghostscript rasterizing failed. See logs for more information.

### ISSUE THREAD

**Issue by sarnau** [paperless-ngx/paperless-ngx#6496]
### Description

Adding [aaa.pdf](https://github.com/paperless-ngx/paperless-ngx/files/15120080/aaa.pdf) to the consume folder, results in a failed import. It is a 7 page PDF, 2.2MB large.

### Steps to reproduce

Just add aaa.pdf to the consume folder.

### Webserver logs

```bash
[2024-04-25 20:02:36,386] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/aaa.pdf to the task queue.
[2024-04-25 20:02:37,473] [DEBUG] [paperless.tasks] Skipping plugin CollatePlugin
[2024-04-25 20:02:37,473] [DEBUG] [paperless.tasks] Executing plugin BarcodePlugin
[2024-04-25 20:02:37,474] [DEBUG] [paperless.barcodes] Scanning for barcodes using PYZBAR
[2024-04-25 20:02:41,170] [DEBUG] [paperless.barcodes] Scanning for barcodes using PYZBAR
[2024-04-25 20:02:44,778] [INFO] [paperless.tasks] BarcodePlugin completed with no message
[2024-04-25 20:02:44,830] [DEBUG] [paperless.tasks] Executing plugin WorkflowTriggerPlugin
[2024-04-25 20:02:44,832] [INFO] [paperless.tasks] WorkflowTriggerPlugin completed with: 
[2024-04-25 20:02:44,849] [INFO] [paperless.consumer] Consuming aaa.pdf
[2024-04-25 20:02:44,853] [DEBUG] [paperless.consumer] Detected mime type: application/pdf
[2024-04-25 20:02:44,861] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser
[2024-04-25 20:02:44,865] [DEBUG] [paperless.consumer] Parsing aaa.pdf...
[2024-04-25 20:02:45,519] [INFO] [paperless.parsing.tesseract] pdftotext exited 0
[2024-04-25 20:02:45,720] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-ngxrmcbbm1d/aaa.pdf'), 'output_file': PosixPath('/tmp/paperless/paperless-ihjsxc91/archive.pdf'), 'use_threads': True, 'jobs': '3', 'language': 'deu+eng', 'output_type': 'pdfa', 'progress_bar': False, 'color_conversion_strategy': 'RGB', 'force_ocr': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-ihjsxc91/sidecar.txt')}
[2024-04-25 20:02:46,589] [WARNING] [ocrmypdf._pipeline] This PDF is marked as a Tagged PDF. This often indicates that the PDF was generated from an office document and does not need OCR. PDF pages processed by OCRmyPDF may not be tagged correctly.
[2024-04-25 20:02:46,590] [INFO] [ocrmypdf._pipelines.ocr] Start processing 3 pages concurrently
[2024-04-25 20:02:46,594] [INFO] [ocrmypdf._pipeline] page already has text! - rasterizing text and running OCR anyway
[2024-04-25 20:02:46,595] [INFO] [ocrmypdf._pipeline] page already has text! - rasterizing text and running OCR anyway
[2024-04-25 20:02:46,595] [INFO] [ocrmypdf._pipeline] page already has text! - rasterizing text and running OCR anyway
[2024-04-25 20:02:46,936] [ERROR] [ocrmypdf._exec.ghostscript] Error: /typecheck in --runpdf--
Operand stack:   --nostringval--   --nostringval--   0
Execution stack:   %interp_exit   .runexec2   --nostringval--   runpdf   --nostringval--   2   %stopped_push   --nostringval--   runpdf   runpdf   false   1   %stopped_push   1944   1   3   %oparray_pop   1943   1   3   %oparray_pop   1928   1   3   %oparray_pop   1929   1   3   %oparray_pop   runpdf   runpdf   runpdf   2   1   1   runpdf   %for_pos_int_continue   runpdf
Dictionary stack:   --dict:752/1123(ro)(G)--   --dict:0/20(G)--   --dict:86/200(L)--   --dict:7/10(L)--
Current allocation mode is local
Last OS error: No such file or directoryGPL Ghostscript 10.02.1: Unrecoverable error, exit code 1

[2024-04-25 20:02:46,937] [INFO] [ocrmypdf._pipeline] page already has text! - rasterizing text and running OCR anyway
[2024-04-25 20:02:49,356] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 15.92 - rotation appears correct
[2024-04-25 20:02:49,437] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 20.31 - rotation appears correct
[2024-04-25 20:02:49,541] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 13.31 - rotation appears correct
[2024-04-25 20:03:23,452] [ERROR] [paperless.consumer] Error occurred while consuming document aaa.pdf: SubprocessOutputError: Ghostscript rasterizing failed. See logs for more information.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_exec/ghostscript.py", line 137, in rasterize_pdf
    p = run(args_gs, stdout=PIPE, stderr=PIPE, check=True)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/subprocess/__init__.py", line 63, in run
    proc = subprocess_run(args, env=env, check=check, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['gs', '-dQUIET', '-dSAFER', '-dBATCH', '-dNOPAUSE', '-dInterpolateControl=-1', '-sDEVICE=jpeggray', '-dFirstPage=1', '-dLastPage=1', '-r300.000000x300.000000', '-dPDFSTOPONERROR', '-o', '-', '-sstdout=%stderr', '-dAutoRotatePages=/None', '-f', '/tmp/ocrmypdf.io.pknh8i5w/origin.pdf']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 368, in parse
    ocrmypdf.ocr(**args)
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/api.py", line 375, in ocr
    return run_pipeline(options=options, plugin_manager=plugin_manager)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 225, in run_pipeline
    return _run_pipeline(options, plugin_manager)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 192, in _run_pipeline
    optimize_messages = exec_concurrent(context, executor)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 119, in exec_concurrent
    executor(
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_concurrent.py", line 74, in __call__
    self._execute(
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/builtin_plugins/concurrency.py", line 141, in _execute
    result = future.result()
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 79, in _exec_page_sync
    ocr_image_out, pdf_page_from_image_out, orientation_correction = process_page(
                                                                     ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/_common.py", line 386, in process_page
    rasterize_preview_out = rasterize_preview(page_context.origin, page_context)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipeline.py", line 371, in rasterize_preview
    page_context.plugin_manager.hook.rasterize_pdf_page(
  File "/usr/local/lib/python3.11/site-packages/pluggy/_hooks.py", line 501, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pluggy/_manager.py", line 119, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pluggy/_callers.py", line 138, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/local/lib/python3.11/site-packages/pluggy/_callers.py", line 102, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/builtin_plugins/ghostscript.py", line 102, in rasterize_pdf_page
    ghostscript.rasterize_pdf(
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_exec/ghostscript.py", line 140, in rasterize_pdf
    raise SubprocessOutputError('Ghostscript rasterizing failed') from e
ocrmypdf.exceptions.SubprocessOutputError: Ghostscript rasterizing failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 327, in main_wrap
    raise exc_info[1]
  File "/usr/src/paperless/src/documents/consumer.py", line 612, in try_consume_file
    document_parser.parse(self.working_copy, mime_type, self.filename)
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 391, in parse
    raise ParseError(
documents.parsers.ParseError: SubprocessOutputError: Ghostscript rasterizing failed. See logs for more information.
[2024-04-25 20:05:00,504] [DEBUG] [paperless.classifier] Gathering data from database...
[2024-04-25 20:05:01,197] [DEBUG] [paperless.classifier] 336 documents, 12 tag(s), 93 correspondent(s), 10 document type(s). 0 storage path(es)
[2024-04-25 20:05:01,197] [DEBUG] [paperless.classifier] Vectorizing data...
[2024-04-25 20:05:07,895] [DEBUG] [paperless.classifier] Training tags classifier...
[2024-04-25 20:05:11,439] [DEBUG] [paperless.classifier] Training correspondent classifier...
[2024-04-25 20:05:14,420] [DEBUG] [paperless.classifier] Training document type classifier...
[2024-04-25 20:05:16,676] [DEBUG] [paperless.classifier] There are no storage paths. Not training storage path classifier.
[2024-04-25 20:05:16,682] [INFO] [paperless.tasks] Saving updated classifier model to /usr/src/paperless/data/classification_model.pickle...
```

### Paperless-ngx version

2.7.2

### Host OS

Synology

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by sarnau** [comment]
If I optimize and flatten the PDF, the import as
[bbb.pdf](https://github.com/paperless-ngx/paperless-ngx/files/15120257/bbb.pdf) works. Which might point to an issue with Ghostscript.
