### ISSUE TITLE
[BUG] Not able to start system with docker compose "ImportError: cannot import name 'promise' from 'vine' (/usr/local/lib/python3.11/site-packages/vine/__init__.py)"

### ISSUE THREAD

**Issue by rockgobo** [paperless-ngx/paperless-ngx#6515]
### Description

I am running a windows machine and try to run paperless with docker compose. I follow the instructions in the docs but the webserver ends in the error "ImportError: cannot import name 'promise' from 'vine' (/usr/local/lib/python3.11/site-packages/vine/__init__.py)" while applying the database migrations.

### Steps to reproduce

1. Downloaded [docker-compose.postgres-tika.yml](https://github.com/paperless-ngx/paperless-ngx/blob/dev/docker/compose/docker-compose.postgres-tika.yml) and renamed it to docker-compose.yaml
2. Also downloaded .env and created a docker-compose.env file as discribed in the documentation
3. docker compose pull
4. docker compose up -d
5. The webserver container ends in the error "ImportError: cannot import name 'promise' from 'vine' (/usr/local/lib/python3.11/site-packages/vine/__init__.py)"

### Webserver logs

```bash
PS C:\docker> docker compose run --rm webserver createsuperuser
[+] Building 0.0s (0/0)                                                                                                                                                                       docker:default
[+] Creating 3/3
 ✔ Container paperless-broker-1     Running                                                                                                                                                             0.0s 
 ✔ Container paperless-tika-1       Running                                                                                                                                                             0.0s 
 ✔ Container paperless-gotenberg-1  Recreated                                                                                                                                                          10.5s 
[+] Running 2/2
 ✔ Container paperless-db-1         Started                                                                                                                                                             0.0s 
 ✔ Container paperless-gotenberg-1  Started                                                                                                                                                             0.6s 
[+] Building 0.0s (0/0)                                                                                                                                                                       docker:default
Paperless-ngx docker container starting...
Creating directory scratch directory /tmp/paperless
Adjusting permissions of paperless files. This may take a while.
Waiting for PostgreSQL to start...
Waiting for Redis...
Connected to Redis broker.
Apply database migrations...
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 103, in wrapper
    saved_locale = translation.get_language()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/translation/__init__.py", line 210, in get_language
    return _trans.get_language()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/translation/__init__.py", line 65, in __getattr__
    if settings.USE_I18N:
       ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.11/site-packages/django/conf/__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/conf/__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/src/paperless/src/paperless/__init__.py", line 1, in <module>
    from paperless.celery import app as celery_app
  File "/usr/src/paperless/src/paperless/celery.py", line 3, in <module>
    from celery import Celery
  File "/usr/local/lib/python3.11/site-packages/celery/local.py", line 460, in __getattr__
    module = __import__(self._object_origins[name], None, None,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/__init__.py", line 2, in <module>
    from celery import _state
  File "/usr/local/lib/python3.11/site-packages/celery/_state.py", line 15, in <module>
    from celery.utils.threads import LocalStack
  File "/usr/local/lib/python3.11/site-packages/celery/utils/__init__.py", line 6, in <module>
    from kombu.utils.objects import cached_property
  File "/usr/local/lib/python3.11/site-packages/kombu/utils/__init__.py", line 6, in <module>
    from .compat import fileno, maybe_fileno, nested, register_after_fork
  File "/usr/local/lib/python3.11/site-packages/kombu/utils/compat.py", line 12, in <module>
    from kombu.exceptions import reraise
  File "/usr/local/lib/python3.11/site-packages/kombu/exceptions.py", line 9, in <module>
    from amqp import ChannelError, ConnectionError, ResourceError
  File "/usr/local/lib/python3.11/site-packages/amqp/__init__.py", line 29, in <module>
    from .basic_message import Message  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/amqp/basic_message.py", line 3, in <module>
    from .serialization import GenericContent
  File "/usr/local/lib/python3.11/site-packages/amqp/serialization.py", line 16, in <module>
    from .utils import bytes_to_str as pstr_t
  File "/usr/local/lib/python3.11/site-packages/amqp/utils.py", line 6, in <module>
    from vine import promise  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'promise' from 'vine' (/usr/local/lib/python3.11/site-packages/vine/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 425, in run_from_argv
    connections.close_all()
  File "/usr/local/lib/python3.11/site-packages/django/utils/connection.py", line 84, in close_all
    for conn in self.all(initialized_only=True):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/connection.py", line 76, in all
    return [
           ^
  File "/usr/local/lib/python3.11/site-packages/django/utils/connection.py", line 73, in __iter__
    return iter(self.settings)
                ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/connection.py", line 45, in settings
    self._settings = self.configure_settings(self._settings)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 148, in configure_settings
    databases = super().configure_settings(databases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/connection.py", line 50, in configure_settings
    settings = getattr(django_settings, self.settings_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.11/site-packages/django/conf/__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/conf/__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/src/paperless/src/paperless/__init__.py", line 1, in <module>
    from paperless.celery import app as celery_app
  File "/usr/src/paperless/src/paperless/celery.py", line 3, in <module>
    from celery import Celery
  File "/usr/local/lib/python3.11/site-packages/celery/local.py", line 460, in __getattr__
    module = __import__(self._object_origins[name], None, None,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/__init__.py", line 2, in <module>
    from celery import _state
  File "/usr/local/lib/python3.11/site-packages/celery/_state.py", line 15, in <module>
    from celery.utils.threads import LocalStack
  File "/usr/local/lib/python3.11/site-packages/celery/utils/__init__.py", line 6, in <module>
    from kombu.utils.objects import cached_property
  File "/usr/local/lib/python3.11/site-packages/kombu/utils/__init__.py", line 6, in <module>
    from .compat import fileno, maybe_fileno, nested, register_after_fork
  File "/usr/local/lib/python3.11/site-packages/kombu/utils/compat.py", line 12, in <module>
    from kombu.exceptions import reraise
  File "/usr/local/lib/python3.11/site-packages/kombu/exceptions.py", line 9, in <module>
    from amqp import ChannelError, ConnectionError, ResourceError
  File "/usr/local/lib/python3.11/site-packages/amqp/__init__.py", line 29, in <module>
    from .basic_message import Message  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/amqp/basic_message.py", line 3, in <module>
    from .serialization import GenericContent
  File "/usr/local/lib/python3.11/site-packages/amqp/serialization.py", line 16, in <module>
    from .utils import bytes_to_str as pstr_t
  File "/usr/local/lib/python3.11/site-packages/amqp/utils.py", line 6, in <module>
    from vine import promise  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'promise' from 'vine' (/usr/local/lib/python3.11/site-packages/vine/__init__.py)
```

### Paperless-ngx version

latest

### Host OS

Windows

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
I cannot reproduce this.  All required Python packages are included and always have been.

Given you're trying to use a Windows host, which is not officially supported, I would suspect that is the source of your issue.
