### ISSUE TITLE
[BUG] UTF16 LE BOM files cannot be imported

### ISSUE THREAD

**Issue by wlfbck** [paperless-ngx/paperless-ngx#6548]
### Description

Title pretty much says it all. I just setup paperless ngx, and tried to upload some random patch file.
Made an example file for reproduction: [my utf16 le bom file.txt](https://github.com/paperless-ngx/paperless-ngx/files/15192115/my.utf16.le.bom.file.txt)

### Steps to reproduce

1. Download file above (check it's actually UTF16 LE BOM, if not, convert it. Notepad++ can both check and convert it)
2. Try to upload it 

### Webserver logs

```bash
[2024-05-02 17:42:57,942] [INFO] [paperless.consumer] Consuming my utf16 le bom file.txt

[2024-05-02 17:42:57,967] [DEBUG] [paperless.consumer] Detected mime type: text/plain

[2024-05-02 17:42:57,979] [DEBUG] [paperless.consumer] Parser: TextDocumentParser

[2024-05-02 17:42:57,989] [DEBUG] [paperless.consumer] Parsing my utf16 le bom file.txt...

[2024-05-02 17:42:57,990] [WARNING] [paperless.parsing.text] Unicode error during text reading, continuing: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

[2024-05-02 17:42:57,991] [DEBUG] [paperless.consumer] Generating thumbnail for my utf16 le bom file.txt...

[2024-05-02 17:42:58,001] [WARNING] [paperless.parsing.text] Unicode error during text reading, continuing: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

[2024-05-02 17:42:58,182] [DEBUG] [paperless.classifier] Document classification model does not exist (yet), not performing automatic matching.

[2024-05-02 17:42:58,194] [DEBUG] [paperless.consumer] Saving record to database

[2024-05-02 17:42:58,195] [DEBUG] [paperless.consumer] Creation date from st_mtime: 2024-05-02 17:42:57+00:00

[2024-05-02 17:42:58,207] [ERROR] [paperless.consumer] The following error occurred while storing document my utf16 le bom file.txt after parsing: A string literal cannot contain NUL (0x00) characters.

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 327, in main_wrap

    raise exc_info[1]

  File "/usr/src/paperless/src/documents/consumer.py", line 675, in try_consume_file

    document = self._store(text=text, date=date, mime_type=mime_type)

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/paperless/src/documents/consumer.py", line 840, in _store

    document = Document.objects.create(

               ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method

    return getattr(self.get_queryset(), name)(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 658, in create

    obj.save(force_insert=True, using=self.db)

  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 814, in save

    self.save_base(

  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 877, in save_base

    updated = self._save_table(

              ^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 1020, in _save_table

    results = self._do_insert(

              ^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 1061, in _do_insert

    return manager._insert(

           ^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method

    return getattr(self.get_queryset(), name)(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1805, in _insert

    return query.get_compiler(using=using).execute_sql(returning_fields)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql

    cursor.execute(sql, params)

  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute

    return self._execute_with_wrappers(

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers

    return executor(sql, params, many, context)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute

    return self.cursor.execute(sql, params)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

ValueError: A string literal cannot contain NUL (0x00) characters.

[2024-05-02 17:42:58,222] [DEBUG] [paperless.parsing.text] Deleting directory /tmp/paperless/paperless-5rz5do9n
```

### Paperless-ngx version

2.7.2

### Host OS

Raspberry PI (bullseye) with aarch64

### Installation method

Docker - official image

### Configuration changes

Irrelevant, specified specific folders for the named volumes

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
This doesn't seem like a bug to me.  We support UTF8 for everything, because that's what basically everything supports now.  It can handle any characters I know of.

**Comment by wlfbck** [comment]
Missing the point kind of. I mean, i expected paperless to handle basically any document i throw at it. It clearly cannot ;)

I'm aware UTF16 LE BOM is like... out there. But that file wasn't generated by me. It doesn't help that UTF8 can handle all chars, when somebody i have no control over decides to use UTF16.

**Comment by stumpylog** [comment]
So convert the file?  As you've pointed out, it's very easy to convert

**Comment by wlfbck** [comment]
Yes, i can do that. Other people wont even know whats wrong, because they don't even know what encoding is (and the error message doesn't reflect that).

I'm just trying to help you make this more userfriendly.
