### ISSUE TITLE
[BUG] Merging images fails

### ISSUE THREAD

**Issue by th3noname** [paperless-ngx/paperless-ngx#6599]
### Description

It is currently not possible to merge two documents, if the original document file is an image. It seems that paperless tries to use the original image as a pdf document.

### Steps to reproduce

1. Add two or more images as documents to paperless
2. Try to merge the documents

### Webserver logs

```bash
[2024-05-07 10:21:41,356] [INFO] [paperless.bulk_edit] Attempting to merge 2 documents into a single document.

[2024-05-07 10:21:41,369] [ERROR] [paperless.bulk_edit] Error merging document 177, it will not be included in the merge: /usr/src/paperless/media/documents/originals/0000177.jpg: unable to find trailer dictionary while recovering damaged file

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/bulk_edit.py", line 258, in merge

    with pikepdf.open(str(doc.source_path)) as pdf:

         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/pikepdf/_methods.py", line 398, in open

    pdf = Pdf._open(

          ^^^^^^^^^^

pikepdf._core.PdfError: /usr/src/paperless/media/documents/originals/0000177.jpg: unable to find trailer dictionary while recovering damaged file

[2024-05-07 10:21:41,379] [ERROR] [paperless.bulk_edit] Error merging document 178, it will not be included in the merge: /usr/src/paperless/media/documents/originals/0000178.jpg: unable to find trailer dictionary while recovering damaged file

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/bulk_edit.py", line 258, in merge

    with pikepdf.open(str(doc.source_path)) as pdf:

         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/pikepdf/_methods.py", line 398, in open

    pdf = Pdf._open(

          ^^^^^^^^^^

pikepdf._core.PdfError: /usr/src/paperless/media/documents/originals/0000178.jpg: unable to find trailer dictionary while recovering damaged file
```

### Paperless-ngx version

2.8.1

### Host OS

raspberry pi arm64

### Installation method

Docker - official image

### Browser

Firefox 125

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
only pdfs are supported
