### ISSUE TITLE
[BUG] Adding SAML auth

### ISSUE THREAD

**Issue by zgurea1** [paperless-ngx/paperless-ngx#6614]
### Description

Hi guys, i am trying to add the SAML auth as default login (https://docs.allauth.org/en/latest/socialaccount/providers/saml.html), and when i am trying to start the app, its looking for this (onelogin.saml) providers instead.

Can you tell what i am doing wrong?

Thx.

### Steps to reproduce

This are the file env parameters for SAML auth.

PAPERLESS_APPS="allauth.socialaccount.providers.saml"

PAPERLESS_SOCIALACCOUNT_PROVIDERS='{"saml":{"APPS":[{"name":"***","provider_id":"urn:***","client_id":"***","settings":{"idp":{"entity_id":"urn:***","metadata_url":"***","sso_url":"***","slo_url":"***","x509cert":"***"},"sp":{"entity_id":"***"}}}]}}'

And when start the container is crashing.

### Webserver logs

```bash
2024-05-07 19:14:33 Running Django checks
2024-05-07 19:14:34 Traceback (most recent call last):
2024-05-07 19:14:34   File "/usr/src/paperless/src/manage.py", line 10, in <module>
2024-05-07 19:14:34     execute_from_command_line(sys.argv)
2024-05-07 19:14:34   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
2024-05-07 19:14:34     utility.execute()
2024-05-07 19:14:34   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
2024-05-07 19:14:34     self.fetch_command(subcommand).run_from_argv(self.argv)
2024-05-07 19:14:34   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
2024-05-07 19:14:34     self.execute(*args, **cmd_options)
2024-05-07 19:14:34   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
2024-05-07 19:14:34     output = self.handle(*args, **options)
2024-05-07 19:14:34              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-07 19:14:34   File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/check.py", line 76, in handle
2024-05-07 19:14:34     self.check(
2024-05-07 19:14:34   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 485, in check
2024-05-07 19:14:34     all_issues = checks.run_checks(
2024-05-07 19:14:34                  ^^^^^^^^^^^^^^^^^^
2024-05-07 19:14:34   File "/usr/local/lib/python3.11/site-packages/django/core/checks/registry.py", line 88, in run_checks
2024-05-07 19:14:34     new_errors = check(app_configs=app_configs, databases=databases)
2024-05-07 19:14:34                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-07 19:14:34   File "/usr/local/lib/python3.11/site-packages/django/core/checks/urls.py", line 14, in check_url_config
2024-05-07 19:14:34     return check_resolver(resolver)
2024-05-07 19:14:34            ^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-07 19:14:34   File "/usr/local/lib/python3.11/site-packages/django/core/checks/urls.py", line 24, in check_resolver
2024-05-07 19:14:34     return check_method()
2024-05-07 19:14:34            ^^^^^^^^^^^^^^
2024-05-07 19:14:34   File "/usr/local/lib/python3.11/site-packages/django/urls/resolvers.py", line 494, in check
2024-05-07 19:14:34     for pattern in self.url_patterns:
2024-05-07 19:14:34                    ^^^^^^^^^^^^^^^^^
2024-05-07 19:14:34   File "/usr/local/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
2024-05-07 19:14:34     res = instance.__dict__[self.name] = self.func(instance)
2024-05-07 19:14:34                                          ^^^^^^^^^^^^^^^^^^^
2024-05-07 19:14:34   File "/usr/local/lib/python3.11/site-packages/django/urls/resolvers.py", line 715, in url_patterns
2024-05-07 19:14:34     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
2024-05-07 19:14:34                        ^^^^^^^^^^^^^^^^^^^
2024-05-07 19:14:34   File "/usr/local/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
2024-05-07 19:14:34     res = instance.__dict__[self.name] = self.func(instance)
2024-05-07 19:14:34                                          ^^^^^^^^^^^^^^^^^^^
2024-05-07 19:14:34   File "/usr/local/lib/python3.11/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
2024-05-07 19:14:34     return import_module(self.urlconf_name)
2024-05-07 19:14:34            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-07 19:14:34   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
2024-05-07 19:14:34     return _bootstrap._gcd_import(name[level:], package, level)
2024-05-07 19:14:34            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-07 19:14:34   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
2024-05-07 19:14:34   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
2024-05-07 19:14:34   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
2024-05-07 19:14:34   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
2024-05-07 19:14:34   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
2024-05-07 19:14:34   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-05-07 19:14:34   File "/usr/src/paperless/src/paperless/urls.py", line 211, in <module>
2024-05-07 19:14:34     path("accounts/", include("allauth.urls")),
2024-05-07 19:14:34                       ^^^^^^^^^^^^^^^^^^^^^^^
2024-05-07 19:14:34   File "/usr/local/lib/python3.11/site-packages/django/urls/conf.py", line 38, in include
2024-05-07 19:14:34     urlconf_module = import_module(urlconf_module)
2024-05-07 19:14:34                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-07 19:14:34   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
2024-05-07 19:14:34     return _bootstrap._gcd_import(name[level:], package, level)
2024-05-07 19:14:34            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-07 19:14:34   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
2024-05-07 19:14:34   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
2024-05-07 19:14:34   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
2024-05-07 19:14:34   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
2024-05-07 19:14:34   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
2024-05-07 19:14:34   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-05-07 19:14:34   File "/usr/local/lib/python3.11/site-packages/allauth/urls.py", line 32, in <module>
2024-05-07 19:14:34     prov_mod = import_module(provider_class.get_package() + ".urls")
2024-05-07 19:14:34                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-07 19:14:34   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
2024-05-07 19:14:34     return _bootstrap._gcd_import(name[level:], package, level)
2024-05-07 19:14:34            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-07 19:14:34   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
2024-05-07 19:14:34   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
2024-05-07 19:14:34   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
2024-05-07 19:14:34   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
2024-05-07 19:14:34   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
2024-05-07 19:14:34   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-05-07 19:14:34   File "/usr/local/lib/python3.11/site-packages/allauth/socialaccount/providers/saml/urls.py", line 3, in <module>
2024-05-07 19:14:34     from . import views
2024-05-07 19:14:34   File "/usr/local/lib/python3.11/site-packages/allauth/socialaccount/providers/saml/views.py", line 10, in <module>
2024-05-07 19:14:34     from onelogin.saml2.auth import OneLogin_Saml2_Auth, OneLogin_Saml2_Settings
2024-05-07 19:14:34 ModuleNotFoundError: No module named 'onelogin'
```

### Paperless-ngx version

1.8.1

### Host OS

Docker

### Installation method

Docker - official image

### Browser

Firefox

### Configuration changes

This are the file for SAML auth  PAPERLESS_APPS="allauth.socialaccount.providers.saml"  PAPERLESS_SOCIALACCOUNT_PROVIDERS='{"saml":{"APPS":[{"name":"***","provider_id":"urn:***","client_id":"***","settings":{"idp":{"entity_id":"urn:***","metadata_url":"***","sso_url":"***","slo_url":"***","x509cert":"***"},"sp":{"entity_id":"***"}}}]}}'

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
That basically is not supported because it requires an extra python package (see first part of docs about `pip install django-allauth[saml]`). Feel free to open a FR, but this would require including that package for all

**Comment by zgurea1** [comment]
@shamoon i saw in Pipfile that all providers are installed by deafault
django-allauth = "*"

**Comment by shamoon** [comment]
I believe that doesnt include extras, for example our current pipfile includes the socialaccount extra:

https://github.com/paperless-ngx/paperless-ngx/blob/3bd6a6fcfad29ca79e8ef2fa7af4a39ad950afbd/Pipfile#L11

**Comment by stumpylog** [comment]
You could also use [this](https://docs.paperless-ngx.com/advanced_usage/#custom-container-initialization) to install whatever dependencies allauth is looking for into the container

**Comment by zgurea1** [comment]
@stumpylog i added a script to install pip install django-allauth[saml], and its running, but when i add PAPERLESS_APPS="allauth.socialaccount.providers.saml" the script is not executed.

**Comment by darmiel** [comment]
> You could also use [this](https://docs.paperless-ngx.com/advanced_usage/#custom-container-initialization) to install whatever dependencies allauth is looking for into the container

Sadly this doesn't work because the `django_checks` run before the custom scripts:

https://github.com/paperless-ngx/paperless-ngx/blob/6fa35226181f9d178cc8b3ed3b010ecfda309642/docker/docker-entrypoint.sh#L109-L112

https://github.com/paperless-ngx/paperless-ngx/blob/6fa35226181f9d178cc8b3ed3b010ecfda309642/docker/docker-prepare.sh#L75-L79

**Comment by zgurea1** [comment]
@stumpylog do you have any ideas to try or what can be the problem?

**Comment by zgurea1** [comment]
@stumpylog is there a workaround for this problem?

**Comment by darmiel** [comment]
> @stumpylog is there a workaround for this problem?

The workaround _I_ use to inject dependencies for "plugins" is to mount a slightly modified [`docker-prepare.sh`](https://github.com/paperless-ngx/paperless-ngx/blob/dev/docker/docker-prepare.sh) script:

```yaml
webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    ...
    volumes:
      - ./apps/docker-prepare.sh:/sbin/docker-prepare.sh
      - ...
```

In the mounted script I've added the dependencies just above `migrations`:

```bash
do_work() {
		# ...
        wait_for_redis
 
        # install custom dependencies
        pip install openai transformers

        migrations
		# ...
}
```
