### ISSUE TITLE
Export/Import does not work > Import with errors

### ISSUE THREAD

**Issue by Kunibert-007** [paperless-ngx/paperless-ngx#6624]
### Description

I made an Export under Paperless-ngx 2.7.2 (non UTF-8 Progress-DB) and now I want to Import all Data with a fresh installation of Paperless-ngx 2.7.2 (UTF-8 SQLite embedded-DB).
90% of the Import were successful, but now I get error and it stops:

root@paperless-ngx272localdb:/# document_importer ../export
Found file 2022/Antrag/Rheinisch-Bergischer-Kreis/Förderantrag Lastenrad.pdf, this might indicate a non-empty installation
Found file 2022/Antrag/Rheinisch-Bergischer-Kreis/Förderantrag Lastenrad.pdf, this might indicate a non-empty installation
Found existing user(s), this might indicate a non-empty installation
Found existing documents(s), this might indicate a non-empty installation
Checking the manifest
Installed 12435 object(s) from 1 fixture(s)
Copy files into paperless...
  0%|                                                                                                                                           | 0/5513 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/paperless/src/documents/management/commands/document_importer.py", line 200, in handle
    self._import_files_from_manifest(options["no_progress_bar"])
  File "/usr/src/paperless/src/documents/management/commands/document_importer.py", line 296, in _import_files_from_manifest
    raise FileExistsError(document.source_path)
FileExistsError: /usr/src/paperless/media/documents/originals/2022/Antrag/Rheinisch-Bergischer-Kreis/Förderantrag Lastenrad.pdf

### Steps to reproduce

1. Import with command "document_importer ../export"
2. Tried to delete the file in the log in the Export-Dir > Error, that the manifest is not correct
3. Tried to delete the file in documents/originals... > then I get the error with another file

Don`t know what to do know. I thought Exporting from the old Container and Importing in a fresh one with embedded SQlite is the best option (had issues after the update tomorrow, see https://github.com/paperless-ngx/paperless-ngx/issues/6593).

### Webserver logs

```bash
see above
```

### Paperless-ngx version

2.7.2

### Host OS

Synology Docker

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
This is https://github.com/paperless-ngx/paperless-ngx/issues/5449

**Comment by Kunibert-007** [comment]
I understand the german charmap could be a problem.
But I have 5.500 documents in paperless, the last import stops at 90%. So when I want to fix the problem with one file I have to
1. Restarting the old paperless docker container from where I do the export
2. Rename/delete the file in the old paperless docker container
3. Do a new export
4. Create a new and clean paperless instance
5. New try for import (round about 4 hours)
and then I get another error...

So this could be weeks for me to import all my paperless documents. Do I have a chance to identify the potential files before exporting? Or can the importer still skip these files and generate an error log instead of interrupting the whole import?
-

**Comment by shamoon** [comment]
That sounds useful potentially but that’s essentially a feature request so not like it would happen immediately. But I agree enough users run into this it would be good to try to help somehow even if the problem isn’t technically on the paperless side. Since this side of things is out of my wheelhouse I’m not able to say what that would look like
