### ISSUE TITLE
[BUG] Error Handling Signed PDFs: OCR Process Invalidates Digital Signature

### ISSUE THREAD

**Issue by Friedjof** [paperless-ngx/paperless-ngx#6637]
### Description

When processing a digitally signed PDF, the OCR operation fails due to an error stating that the OCR would alter the document and invalidate its digital signature. This issue occurs during the consumption of the document after uploading or sending via email. It appears that the existing logic does not handle cases where the PDF is signed, potentially leading to unprocessed documents.

### Steps to reproduce

1. Create a PDF document.
2. Digitally sign the PDF document.
3. Upload the signed PDF to PaperlessNGX or send it via email to the system.
4. The system attempts to process the PDF through OCR.

### Webserver logs

```bash
[2024-05-08 15:20:11,825] [ERROR] [paperless.consumer] Error occurred while consuming document my-document.pdf: DigitalSignatureError: Input PDF has a digital signature. OCR would alter the document,

invalidating the signature.

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 330, in parse

    ocrmypdf.ocr(**args)

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/api.py", line 375, in ocr

    return run_pipeline(options=options, plugin_manager=plugin_manager)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 225, in run_pipeline

    return _run_pipeline(options, plugin_manager)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 189, in _run_pipeline

    validate_pdfinfo_options(context)

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipeline.py", line 202, in validate_pdfinfo_options

    raise DigitalSignatureError()

ocrmypdf.exceptions.DigitalSignatureError: Input PDF has a digital signature. OCR would alter the document,

invalidating the signature.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 381, in parse

    ocrmypdf.ocr(**args)

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/api.py", line 375, in ocr

    return run_pipeline(options=options, plugin_manager=plugin_manager)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 225, in run_pipeline

    return _run_pipeline(options, plugin_manager)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 189, in _run_pipeline

    validate_pdfinfo_options(context)

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipeline.py", line 202, in validate_pdfinfo_options

    raise DigitalSignatureError()

ocrmypdf.exceptions.DigitalSignatureError: Input PDF has a digital signature. OCR would alter the document,

invalidating the signature.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 349, in main_wrap

    raise exc_info[1]

  File "/usr/src/paperless/src/documents/consumer.py", line 446, in try_consume_file

    document_parser.parse(self.path, mime_type, self.filename)

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 393, in parse

    raise ParseError(f"{e.__class__.__name__}: {e!s}") from e

documents.parsers.ParseError: DigitalSignatureError: Input PDF has a digital signature. OCR would alter the document,

invalidating the signature.
```

### Paperless-ngx version

2.1.2

### Host OS

Docker on Synology DS923+

### Installation method

Docker - official image

### Browser

Firefox

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
There are numerous discussions which cover exactly this.  Please search.
