### ISSUE TITLE
[BUG] document exporter not working within container paperless-ngx:2.8.2

### ISSUE THREAD

**Issue by piecko** [paperless-ngx/paperless-ngx#6652]
### Description

The document exporter stopped working with the latest container image.
Running the command  results in an Import Error.
With the old 2.7.2-version it worked just fine.

### Steps to reproduce

1. open a shell into the container
2. execute `document_exporter`

### Webserver logs

```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/usr/local/lib/python3.11/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/usr/local/lib/python3.11/site-packages/numpy/core/overrides.py", line 8, in <module>
    from numpy.core._multiarray_umath import (
ImportError: lmbm.so.6: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/numpy/__init__.py", line 130, in <module>
    from numpy.__config__ import show as show_config
  File "/usr/local/lib/python3.11/site-packages/numpy/__config__.py", line 4, in <module>
    from numpy.core._multiarray_umath import (
  File "/usr/local/lib/python3.11/site-packages/numpy/core/__init__.py", line 50, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.11 from "/usr/local/bin/python3"
  * The NumPy version is: "1.26.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: lmbm.so.6: cannot open shared object file: No such file or directory


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/usr/local/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.11/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/usr/src/paperless/src/documents/apps.py", line 13, in ready
    from documents.signals.handlers import add_inbox_tags
  File "/usr/src/paperless/src/documents/signals/handlers.py", line 25, in <module>
    from documents import matching
  File "/usr/src/paperless/src/documents/matching.py", line 6, in <module>
    from documents.classifier import DocumentClassifier
  File "/usr/src/paperless/src/documents/classifier.py", line 17, in <module>
    from sklearn.exceptions import InconsistentVersionWarning
  File "/usr/local/lib/python3.11/site-packages/sklearn/__init__.py", line 87, in <module>
    from .base import clone
  File "/usr/local/lib/python3.11/site-packages/sklearn/base.py", line 14, in <module>
    import numpy as np
  File "/usr/local/lib/python3.11/site-packages/numpy/__init__.py", line 135, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
```

### Paperless-ngx version

2.8.2

### Host OS

Ubuntu 22.04

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
Pretty clear this is Numpy's problem, not paperless.  We simply install it as normal.

**Comment by stumpylog** [comment]
Confirmed I cannot reproduce this with AMD64 at least

**Comment by piecko** [comment]
I understand that the problem comes from numpy and it is only affecting the container-image.
But basically this seems broken in the image itself.

**Comment by stumpylog** [comment]
As I stated, cannot reproduce this.  I would suggest https://github.com/numpy/numpy/issues

**Comment by piecko** [comment]
I did not expect this.
After restarting my k3s-node, the problem disappeared. I never thought, this weird behaviour can come from my runtime.
No further actions needed of course.

Thx for your time.
