### ISSUE TITLE
[BUG] Message "Document classification model does not exist (yet)" after update

### ISSUE THREAD

**Issue by Mathias-Buder-Bose** [paperless-ngx/paperless-ngx#6678]
### Description

After updating from `v2.7.2` to `v2.8.3` I'm getting the error message:

```
Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/views.py", line 1967, in get
    raise FileNotFoundError(classifier_error)
FileNotFoundError: Classifier file does not exist (yet). Re-training may be pending.
[2024-05-11 10:10:21,722] [DEBUG] [paperless.classifier] Document classification model does not exist (yet), not performing automatic matching.
[2024-05-11 10:10:21,745] [ERROR] [paperless.api] System status detected a possible problem while loading the classifier: Classifier file does not exist (yet). Re-training may be pending.
```

![image](https://github.com/paperless-ngx/paperless-ngx/assets/108457337/d7042388-e3a7-48cf-b57a-cbf8281b1454)

Any ideas?

### Steps to reproduce

1. Update from `v2.7.2` to `v2.8.3`

### Webserver logs

```bash
[2024-05-11 00:05:00,888] [DEBUG] [paperless.classifier] Gathering data from database...

[2024-05-11 00:05:02,376] [INFO] [paperless.classifier] No updates since last training

[2024-05-11 00:05:02,382] [DEBUG] [paperless.tasks] Training data unchanged.

[2024-05-11 01:05:01,400] [DEBUG] [paperless.classifier] Gathering data from database...

[2024-05-11 01:05:03,044] [INFO] [paperless.classifier] No updates since last training

[2024-05-11 01:05:03,052] [DEBUG] [paperless.tasks] Training data unchanged.

[2024-05-11 02:05:00,427] [DEBUG] [paperless.classifier] Gathering data from database...

[2024-05-11 02:05:01,995] [INFO] [paperless.classifier] No updates since last training

[2024-05-11 02:05:02,004] [DEBUG] [paperless.tasks] Training data unchanged.

[2024-05-11 03:05:04,689] [DEBUG] [paperless.classifier] Gathering data from database...

[2024-05-11 03:05:06,563] [INFO] [paperless.classifier] No updates since last training

[2024-05-11 03:05:06,883] [DEBUG] [paperless.tasks] Training data unchanged.

[2024-05-11 04:05:02,299] [DEBUG] [paperless.classifier] Gathering data from database...

[2024-05-11 04:05:04,137] [INFO] [paperless.classifier] No updates since last training

[2024-05-11 04:05:04,144] [DEBUG] [paperless.tasks] Training data unchanged.

[2024-05-11 05:05:00,669] [DEBUG] [paperless.classifier] Gathering data from database...

[2024-05-11 05:05:02,183] [INFO] [paperless.classifier] No updates since last training

[2024-05-11 05:05:02,190] [DEBUG] [paperless.tasks] Training data unchanged.

[2024-05-11 06:05:00,425] [DEBUG] [paperless.classifier] Gathering data from database...

[2024-05-11 06:05:02,001] [INFO] [paperless.classifier] No updates since last training

[2024-05-11 06:05:02,009] [DEBUG] [paperless.tasks] Training data unchanged.

[2024-05-11 07:05:00,535] [DEBUG] [paperless.classifier] Gathering data from database...

[2024-05-11 07:05:02,078] [INFO] [paperless.classifier] No updates since last training

[2024-05-11 07:05:02,086] [DEBUG] [paperless.tasks] Training data unchanged.

[2024-05-11 08:05:00,452] [DEBUG] [paperless.classifier] Gathering data from database...

[2024-05-11 08:05:01,940] [INFO] [paperless.classifier] No updates since last training

[2024-05-11 08:05:01,947] [DEBUG] [paperless.tasks] Training data unchanged.

[2024-05-11 09:05:01,029] [DEBUG] [paperless.classifier] Gathering data from database...

[2024-05-11 09:05:02,531] [INFO] [paperless.classifier] No updates since last training

[2024-05-11 09:05:02,538] [DEBUG] [paperless.tasks] Training data unchanged.

[2024-05-11 09:59:40,801] [INFO] [paperless.management.consumer] Received SIGINT, stopping inotify

[2024-05-11 09:59:41,130] [DEBUG] [paperless.management.consumer] Consumer exiting.

[2024-05-11 10:08:24,312] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/paperless_double-collated.pdf to the task queue.

[2024-05-11 10:08:25,520] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: /usr/src/paperless/consume

[2024-05-11 10:08:27,712] [DEBUG] [paperless.tasks] Skipping plugin CollatePlugin

[2024-05-11 10:08:27,716] [DEBUG] [paperless.tasks] Executing plugin BarcodePlugin

[2024-05-11 10:08:27,717] [DEBUG] [paperless.barcodes] Scanning for barcodes using ZXING

[2024-05-11 10:09:16,643] [DEBUG] [paperless.barcodes] Barcode of type BarcodeFormat.QRCode found: ASN038

[2024-05-11 10:09:17,440] [DEBUG] [paperless.barcodes] Barcode of type BarcodeFormat.DataMatrix found: 400005300002246500000017000000540003003400000000000000423953

[2024-05-11 10:09:18,754] [DEBUG] [paperless.barcodes] Barcode of type BarcodeFormat.DataMatrix found: 400005300002246500000017000000540004003400000000000000423953

[2024-05-11 10:09:19,854] [DEBUG] [paperless.barcodes] Barcode of type BarcodeFormat.DataMatrix found: 400005300002246500000017000000540005003400000000000000423953

[2024-05-11 10:09:21,969] [DEBUG] [paperless.barcodes] Barcode of type BarcodeFormat.DataMatrix found: 400005300002246500000017000000540006003400000000000000423953

[2024-05-11 10:09:23,333] [DEBUG] [paperless.barcodes] Barcode of type BarcodeFormat.DataMatrix found: 400005300002246500000017000000540007003400000000000000423953

[2024-05-11 10:09:24,588] [DEBUG] [paperless.barcodes] Barcode of type BarcodeFormat.DataMatrix found: 400005300002246500000017000000540008003400000000000000423953

[2024-05-11 10:09:25,993] [DEBUG] [paperless.barcodes] Barcode of type BarcodeFormat.DataMatrix found: 400005300002246500000017000000540009003400000000000000423953

[2024-05-11 10:09:27,299] [DEBUG] [paperless.barcodes] Barcode of type BarcodeFormat.DataMatrix found: 400005300002246500000017000000540010003400000000000000423953

[2024-05-11 10:09:28,726] [DEBUG] [paperless.barcodes] Barcode of type BarcodeFormat.DataMatrix found: 400005300002246500000017000000540011003400000000000000423953

[2024-05-11 10:09:31,200] [DEBUG] [paperless.barcodes] Barcode of type BarcodeFormat.DataMatrix found: 400005300002246500000017000000540012003400000000000000423953

[2024-05-11 10:09:34,303] [DEBUG] [paperless.barcodes] Barcode of type BarcodeFormat.DataMatrix found: 400005300002246500000017000000540014003400000000000000423953

[2024-05-11 10:09:35,736] [DEBUG] [paperless.barcodes] Barcode of type BarcodeFormat.DataMatrix found: 400005300002246500000017000000540016003400000000000000423953

[2024-05-11 10:09:37,152] [DEBUG] [paperless.barcodes] Barcode of type BarcodeFormat.DataMatrix found: 400005300002246500000017000000540015003400000000000000423953

[2024-05-11 10:09:38,709] [DEBUG] [paperless.barcodes] Barcode of type BarcodeFormat.DataMatrix found: 400005300002246500000017000000540017003400000000000000423953

[2024-05-11 10:09:40,220] [DEBUG] [paperless.barcodes] Barcode of type BarcodeFormat.DataMatrix found: 400005300002246500000017000000540018003400000000000000423953

[2024-05-11 10:09:41,800] [DEBUG] [paperless.barcodes] Barcode of type BarcodeFormat.DataMatrix found: 400005300002246500000017000000540019003400000000000000423953

[2024-05-11 10:09:43,721] [DEBUG] [paperless.barcodes] Barcode of type BarcodeFormat.DataMatrix found: 400005300002246500000017000000540020003400000000000000423953

[2024-05-11 10:09:45,210] [DEBUG] [paperless.barcodes] Barcode of type BarcodeFormat.DataMatrix found: 400005300002246500000017000000540021003400000000000000423953

[2024-05-11 10:09:46,669] [DEBUG] [paperless.barcodes] Barcode of type BarcodeFormat.DataMatrix found: 400005300002246500000017000000540022003400000000000000423953

[2024-05-11 10:09:48,071] [DEBUG] [paperless.barcodes] Barcode of type BarcodeFormat.DataMatrix found: 400005300002246500000017000000540023003400000000000000423953

[2024-05-11 10:09:49,516] [DEBUG] [paperless.barcodes] Barcode of type BarcodeFormat.DataMatrix found: 400005300002246500000017000000540024003400000000000000423953

[2024-05-11 10:09:52,022] [DEBUG] [paperless.barcodes] Barcode of type BarcodeFormat.DataMatrix found: 400005300002246500000017000000540025003400000000000000423953

[2024-05-11 10:09:54,439] [DEBUG] [paperless.barcodes] Barcode of type BarcodeFormat.DataMatrix found: 400005300002246500000017000000540026003400000000000000423953

[2024-05-11 10:09:55,878] [DEBUG] [paperless.barcodes] Barcode of type BarcodeFormat.DataMatrix found: 400005300002246500000017000000540027003400000000000000423953

[2024-05-11 10:09:57,710] [DEBUG] [paperless.barcodes] Barcode of type BarcodeFormat.DataMatrix found: 400005300002246500000017000000540028003400000000000000423953

[2024-05-11 10:09:59,390] [DEBUG] [paperless.barcodes] Barcode of type BarcodeFormat.DataMatrix found: 400005300002246500000017000000540029003400000000000000423953

[2024-05-11 10:10:00,977] [DEBUG] [paperless.barcodes] Barcode of type BarcodeFormat.DataMatrix found: 400005300002246500000017000000540030003400000000000000423953

[2024-05-11 10:10:02,492] [DEBUG] [paperless.barcodes] Barcode of type BarcodeFormat.DataMatrix found: 400005300002246500000017000000540031003400000000000000423953

[2024-05-11 10:10:03,982] [DEBUG] [paperless.barcodes] Barcode of type BarcodeFormat.DataMatrix found: 400005300002246500000017000000540032003400000000000000423953

[2024-05-11 10:10:05,621] [DEBUG] [paperless.barcodes] Barcode of type BarcodeFormat.DataMatrix found: 400005300002246500000017000000540033003400000000000000423953

[2024-05-11 10:10:07,097] [DEBUG] [paperless.barcodes] Barcode of type BarcodeFormat.DataMatrix found: 400005300002246500000017000000540034003410000000000000423953

[2024-05-11 10:10:08,564] [DEBUG] [paperless.barcodes] Barcode of type BarcodeFormat.DataMatrix found: 400005300002246500000017000000540001003400000000000000423953

[2024-05-11 10:10:10,521] [DEBUG] [paperless.barcodes] Barcode of type BarcodeFormat.DataMatrix found: 400005300002246500000017000000540002003400000000000000423953

[2024-05-11 10:10:10,786] [DEBUG] [paperless.barcodes] Found ASN Barcode: ASN038

[2024-05-11 10:10:10,787] [INFO] [paperless.barcodes] Found ASN in barcode: 38

[2024-05-11 10:10:10,788] [INFO] [paperless.tasks] BarcodePlugin completed with no message

[2024-05-11 10:10:10,876] [DEBUG] [paperless.tasks] Executing plugin WorkflowTriggerPlugin

[2024-05-11 10:10:14,091] [INFO] [paperless.matching] Document matched WorkflowTrigger 1 from Workflow: HP Scan

[2024-05-11 10:10:14,165] [INFO] [paperless.matching] Document did not match Workflow: File Upload

[2024-05-11 10:10:14,167] [DEBUG] [paperless.matching] ("Document source ConsumeFolder not in ['ApiUpload']",)

[2024-05-11 10:10:14,174] [INFO] [paperless.matching] Document did not match Workflow: E-Mail

[2024-05-11 10:10:14,175] [DEBUG] [paperless.matching] ("Document source ConsumeFolder not in ['MailFetch']",)

[2024-05-11 10:10:14,176] [INFO] [paperless.tasks] WorkflowTriggerPlugin completed with: Applying WorkflowAction 1 from Workflow: HP Scan

[2024-05-11 10:10:14,177] [DEBUG] [paperless.tasks] Executing plugin ConsumeTaskPlugin

[2024-05-11 10:10:15,547] [INFO] [paperless.consumer] Consuming paperless_double-collated.pdf

[2024-05-11 10:10:15,784] [DEBUG] [paperless.consumer] Detected mime type: application/pdf

[2024-05-11 10:10:15,834] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser

[2024-05-11 10:10:15,842] [DEBUG] [paperless.consumer] Parsing paperless_double-collated.pdf...

[2024-05-11 10:10:16,533] [INFO] [paperless.parsing.tesseract] pdftotext exited 0

[2024-05-11 10:10:18,299] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-ngx687n1_wj/paperless_double-collated.pdf'), 'output_file': PosixPath('/tmp/paperless/paperless-enmk7ap9/archive.pdf'), 'use_threads': True, 'jobs': 2, 'language': 'deu+eng', 'output_type': 'pdfa', 'progress_bar': False, 'color_conversion_strategy': 'RGB', 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-enmk7ap9/sidecar.txt')}

[2024-05-11 10:10:19,265] [INFO] [paperless.classifier] Classifier version incompatible: sklearn version update, will re-train

[2024-05-11 10:10:19,292] [ERROR] [paperless.api] System status detected a possible problem while loading the classifier: Classifier file does not exist (yet). Re-training may be pending.

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/views.py", line 1967, in get

    raise FileNotFoundError(classifier_error)

FileNotFoundError: Classifier file does not exist (yet). Re-training may be pending.

[2024-05-11 10:10:20,605] [DEBUG] [paperless.classifier] Document classification model does not exist (yet), not performing automatic matching.

[2024-05-11 10:10:20,616] [ERROR] [paperless.api] System status detected a possible problem while loading the classifier: Classifier file does not exist (yet). Re-training may be pending.

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/views.py", line 1967, in get

    raise FileNotFoundError(classifier_error)

FileNotFoundError: Classifier file does not exist (yet). Re-training may be pending.

[2024-05-11 10:10:21,722] [DEBUG] [paperless.classifier] Document classification model does not exist (yet), not performing automatic matching.

[2024-05-11 10:10:21,745] [ERROR] [paperless.api] System status detected a possible problem while loading the classifier: Classifier file does not exist (yet). Re-training may be pending.

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/views.py", line 1967, in get

    raise FileNotFoundError(classifier_error)

FileNotFoundError: Classifier file does not exist (yet). Re-training may be pending.

[2024-05-11 10:10:22,848] [DEBUG] [paperless.classifier] Document classification model does not exist (yet), not performing automatic matching.

[2024-05-11 10:10:22,858] [ERROR] [paperless.api] System status detected a possible problem while loading the classifier: Classifier file does not exist (yet). Re-training may be pending.

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/views.py", line 1967, in get

    raise FileNotFoundError(classifier_error)

FileNotFoundError: Classifier file does not exist (yet). Re-training may be pending.

[2024-05-11 10:10:27,812] [INFO] [ocrmypdf._pipelines.ocr] Start processing 2 pages concurrently

[2024-05-11 10:10:34,161] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 18.86 - rotation appears correct

[2024-05-11 10:10:34,226] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 24.65 - rotation appears correct

[2024-05-11 10:11:13,026] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 23.00 - rotation appears correct

[2024-05-11 10:11:17,120] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 25.01 - rotation appears correct

[2024-05-11 10:11:20,988] [DEBUG] [paperless.classifier] Document classification model does not exist (yet), not performing automatic matching.

[2024-05-11 10:11:21,014] [ERROR] [paperless.api] System status detected a possible problem while loading the classifier: Classifier file does not exist (yet). Re-training may be pending.

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/views.py", line 1967, in get

    raise FileNotFoundError(classifier_error)

FileNotFoundError: Classifier file does not exist (yet). Re-training may be pending.

[2024-05-11 10:11:22,288] [DEBUG] [paperless.classifier] Document classification model does not exist (yet), not performing automatic matching.

[2024-05-11 10:11:22,303] [ERROR] [paperless.api] System status detected a possible problem while loading the classifier: Classifier file does not exist (yet). Re-training may be pending.

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/views.py", line 1967, in get

    raise FileNotFoundError(classifier_error)

FileNotFoundError: Classifier file does not exist (yet). Re-training may be pending.

[2024-05-11 10:11:29,848] [DEBUG] [paperless.classifier] Document classification model does not exist (yet), not performing automatic matching.

[2024-05-11 10:11:29,864] [ERROR] [paperless.api] System status detected a possible problem while loading the classifier: Classifier file does not exist (yet). Re-training may be pending.

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/views.py", line 1967, in get

    raise FileNotFoundError(classifier_error)

FileNotFoundError: Classifier file does not exist (yet). Re-training may be pending.

[2024-05-11 10:11:31,031] [DEBUG] [paperless.classifier] Document classification model does not exist (yet), not performing automatic matching.

[2024-05-11 10:11:31,044] [ERROR] [paperless.api] System status detected a possible problem while loading the classifier: Classifier file does not exist (yet). Re-training may be pending.

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/views.py", line 1967, in get

    raise FileNotFoundError(classifier_error)

FileNotFoundError: Classifier file does not exist (yet). Re-training may be pending.

[2024-05-11 10:11:44,307] [DEBUG] [paperless.classifier] Document classification model does not exist (yet), not performing automatic matching.

[2024-05-11 10:11:44,354] [ERROR] [paperless.api] System status detected a possible problem while loading the classifier: Classifier file does not exist (yet). Re-training may be pending.

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/views.py", line 1967, in get

    raise FileNotFoundError(classifier_error)

FileNotFoundError: Classifier file does not exist (yet). Re-training may be pending.

[2024-05-11 10:11:45,536] [DEBUG] [paperless.classifier] Document classification model does not exist (yet), not performing automatic matching.

[2024-05-11 10:11:45,555] [ERROR] [paperless.api] System status detected a possible problem while loading the classifier: Classifier file does not exist (yet). Re-training may be pending.

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/views.py", line 1967, in get

    raise FileNotFoundError(classifier_error)

FileNotFoundError: Classifier file does not exist (yet). Re-training may be pending.

[2024-05-11 10:12:07,543] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 20.14 - rotation appears correct

[2024-05-11 10:12:17,202] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 25.95 - rotation appears correct

[2024-05-11 10:12:53,575] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 24.54 - rotation appears correct

[2024-05-11 10:12:57,353] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 17.59 - rotation appears correct

[2024-05-11 10:13:44,001] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 15.81 - rotation appears correct

[2024-05-11 10:13:56,869] [INFO] [ocrmypdf._exec.tesseract] [tesseract] Too few characters. Skipping this page

[2024-05-11 10:13:56,870] [INFO] [ocrmypdf._exec.tesseract] [tesseract] Too few characters. Skipping this page

[2024-05-11 10:13:56,871] [ERROR] [ocrmypdf._exec.tesseract] [tesseract] Error during processing.

[2024-05-11 10:13:56,872] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 0.00 - no change

[2024-05-11 10:14:24,586] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 26.04 - rotation appears correct

[2024-05-11 10:14:27,025] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 24.00 - rotation appears correct

[2024-05-11 10:15:19,142] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 10.44 - no change

[2024-05-11 10:15:22,232] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 10.41 - no change

[2024-05-11 10:16:25,373] [INFO] [ocrmypdf._exec.tesseract] [tesseract] Too few characters. Skipping this page

[2024-05-11 10:16:25,374] [INFO] [ocrmypdf._exec.tesseract] [tesseract] Too few characters. Skipping this page

[2024-05-11 10:16:25,376] [ERROR] [ocrmypdf._exec.tesseract] [tesseract] Error during processing.

[2024-05-11 10:16:25,377] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 0.00 - no change

[2024-05-11 10:16:27,709] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 12.13 - rotation appears correct
```

### Paperless-ngx version

2.8.3

### Host OS

Linux-4.4.180+-x86_64-with-glibc2.36

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by OverDodo** [comment]
Had this too once, i just ran the document_create_classifier command.

**Comment by shamoon** [comment]
Above is the answer. The docker image takes care of scheduling this automatically but perhaps something about your setup prevented it from completing.

**Comment by Mathias-Buder-Bose** [comment]
Thank you, everyone. Your solution worked perfectly for me.
