### ISSUE TITLE
[BUG] ConsumeTaskPlugin failed: | Requires 2GB of memory within container 

### ISSUE THREAD

**Issue by bmsleight** [paperless-ngx/paperless-ngx#6773]
### Description

When running docker instance with less than 2048 MB of RAM within a container. 

(Wil close straight away)

### Steps to reproduce

1 - Set-up container within proxmox
2 - Set contain with 1024 MB of RAM
3 - Install docker inside debian container 
4 - Install paperless-ngx
5 - Upload documents 

### Webserver logs

```bash
[2024-05-19 16:59:16,590] [ERROR] [paperless.tasks] ConsumeTaskPlugin failed: 19420406000000-scan__001462.pdf: Error occurred while consuming document 19420406000000-scan__001462.pdf: SubprocessOutputError: . See logs for more information.

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_exec/tesseract.py", line 201, in get_deskew

    p = run(args_tesseract, stdout=PIPE, stderr=STDOUT, timeout=timeout, check=True)

        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/subprocess/__init__.py", line 63, in run

    proc = subprocess_run(args, env=env, check=check, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/subprocess.py", line 571, in run

    raise CalledProcessError(retcode, process.args,

subprocess.CalledProcessError: Command '['tesseract', '-l', 'eng', '--psm', '2', '/tmp/ocrmypdf.io.2hvpy7tg/000001_rasterize.png', 'stdout']' died with <Signals.SIGKILL: 9>.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 368, in parse

    ocrmypdf.ocr(**args)

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/api.py", line 375, in ocr

    return run_pipeline(options=options, plugin_manager=plugin_manager)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 225, in run_pipeline

    return _run_pipeline(options, plugin_manager)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 192, in _run_pipeline

    optimize_messages = exec_concurrent(context, executor)

                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 119, in exec_concurrent

    executor(

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_concurrent.py", line 74, in __call__

    self._execute(

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/builtin_plugins/concurrency.py", line 141, in _execute

    result = future.result()

             ^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result

    return self.__get_result()

           ^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result

    raise self._exception

  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run

    result = self.fn(*self.args, **self.kwargs)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 79, in _exec_page_sync

    ocr_image_out, pdf_page_from_image_out, orientation_correction = process_page(

                                                                     ^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/_common.py", line 391, in process_page

    ocr_image, preprocess_out = make_intermediate_images(

                                ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/_common.py", line 335, in make_intermediate_images

    ocr_image = preprocess_out = preprocess(

                                 ^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/_common.py", line 314, in preprocess

    image = preprocess_deskew(image, page_context)

            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipeline.py", line 569, in preprocess_deskew

    deskew_angle_degrees = ocr_engine.get_deskew(input_file, page_context.options)

                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/builtin_plugins/tesseract_ocr.py", line 239, in get_deskew

    return tesseract.get_deskew(

           ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_exec/tesseract.py", line 212, in get_deskew

    raise SubprocessOutputError() from e

ocrmypdf.exceptions.SubprocessOutputError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 327, in main_wrap

    raise exc_info[1]

  File "/usr/src/paperless/src/documents/consumer.py", line 568, in run

    document_parser.parse(self.working_copy, mime_type, self.filename)

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 391, in parse

    raise ParseError(

documents.parsers.ParseError: SubprocessOutputError: . See logs for more information.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/tasks.py", line 144, in consume_file

    msg = plugin.run()

          ^^^^^^^^^^^^

  File "/usr/src/paperless/src/documents/consumer.py", line 596, in run

    self._fail(

  File "/usr/src/paperless/src/documents/consumer.py", line 302, in _fail

    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception

documents.consumer.ConsumerError: 19420406000000-scan__001462.pdf: Error occurred while consuming document 19420406000000-scan__001462.pdf: SubprocessOutputError: . See logs for more information.
```

### Paperless-ngx version

Paperless-ngx 2.8.6 

### Host OS

proxmox 

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by bmsleight** [comment]
Upgrade container to 2048 MB of RAM

**Comment by shamoon** [comment]
> (Wil close straight away)

Sorry, so what was the point of this?

**Comment by bmsleight** [comment]
In case anyone had a similar error message and through the power of internet search could find a resolution. 
It was non-obvious to myself how to solve for a while. 
Apologies, if this was not seen as helpful.

**Comment by shamoon** [comment]
I think a discussion is a more appropriate place for something like this, thanks
