### ISSUE TITLE
[BUG] merging of .tif broken

### ISSUE THREAD

**Issue by qqq-jump** [paperless-ngx/paperless-ngx#6905]
### Description

It seems that merging of .tif documents is broken. No user facing message is shown and i cannot find a merged document.

i think that the function supports only pdf documents.
paperless.log entries support this.

### Steps to reproduce

1. Go to "Documents" tab / site
2. Select 2 or more documents which were uploaded as .tif
3. Select "Merge" under Actions drop down

### Webserver logs

```bash
[2024-06-03 20:56:52,393] [INFO] [paperless.bulk_edit] Attempting to merge 2 documents into a single document.

[2024-06-03 20:56:59,071] [ERROR] [paperless.bulk_edit] Error merging document 16, it will not be included in the merge: /usr/src/paperless/media/documents/originals/0000016.tif: unable to find trailer dictionary while recovering damaged file

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/bulk_edit.py", line 251, in merge

    with pikepdf.open(str(doc.source_path)) as pdf:

         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/pikepdf/_methods.py", line 398, in open

    pdf = Pdf._open(

          ^^^^^^^^^^

pikepdf._core.PdfError: /usr/src/paperless/media/documents/originals/0000016.tif: unable to find trailer dictionary while recovering damaged file

[2024-06-03 20:57:03,826] [ERROR] [paperless.bulk_edit] Error merging document 17, it will not be included in the merge: /usr/src/paperless/media/documents/originals/0000017.tif: unable to find trailer dictionary while recovering damaged file

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/bulk_edit.py", line 251, in merge

    with pikepdf.open(str(doc.source_path)) as pdf:

         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/pikepdf/_methods.py", line 398, in open

    pdf = Pdf._open(

          ^^^^^^^^^^

pikepdf._core.PdfError: /usr/src/paperless/media/documents/originals/0000017.tif: unable to find trailer dictionary while recovering damaged file

[2024-06-03 20:57:03,828] [WARNING] [paperless.bulk_edit] No documents were merged
```

### Paperless-ngx version

2.9.0

### Host OS

Ubuntu 22.04.4 LTS

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.9.0",
    "server_os": "Linux-5.15.0-107-generic-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 125668167680,
        "available": 53294133248
    },
    "database": {
        "type": "postgresql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "account.0009_emailaddress_unique_primary_email",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://broker:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-06-03T20:55:15.913838+02:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-06-03T19:05:06.827747Z",
        "classifier_error": null
    }
}
```

### Browser

Firefox

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
> i think that the function supports only pdf documents.
> paperless.log entries support this.

Correct.

https://docs.paperless-ngx.com/usage/#pdf-actions

**Comment by shamoon** [comment]
Also:

<img width="539" alt="Screenshot 2024-06-03 at 12 24 28 PM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/51c028bf-196b-49fa-8728-f545be7155df">
