### ISSUE TITLE
[possible BUG] Unsupported mime type inode/x-empty instead of application/pdf

### ISSUE THREAD

**Issue by revil-O** [paperless-ngx/paperless-ngx#6974]
### Description
Running paperless ngx 2.9.0 on Docker Desktop on Mac OS X Sonoma 14.5.
Docker Desktop: `Docker Desktop 4.30.0 (149282) is currently the newest version available.`

paperless recognizes some pdf files scanned with my ix1600 as node/x-empty.

e.g. 20240222_LIQUIDATION.pdf: Unsupported mime type inode/x-empty

console: `file --mime-type 20240222_LIQUIDATION.pdf `

gives me:
--> 20240222_LIQUIDATION.pdf: application/pdf

seems to be right -.-

### Steps to reproduce

1. scan my docs directly into consume-folder
2. watch the log
3. get the same error for over 90 single pdf documents
4. btw. randomly 5 pdf files can be processed without any error !?!?! (from the same scan process) *little bit confused*

I'm using paperless for over 7 months, this is the first time i faced that issue -- after over 6600 successful processed scans.

### Webserver logs

```bash
[2024-06-12 09:21:01,477] [INFO] [paperless.tasks] WorkflowTriggerPlugin completed with: 
[2024-06-12 09:21:01,499] [INFO] [paperless.consumer] Consuming 20240222_LIQUIDATION.pdf
[2024-06-12 09:21:01,522] [ERROR] [paperless.consumer] Unsupported mime type inode/x-empty
[2024-06-12 09:21:01,525] [ERROR] [paperless.tasks] ConsumeTaskPlugin failed: 20240222_LIQUIDATION.pdf: Unsupported mime type inode/x-empty
Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/tasks.py", line 147, in consume_file
    msg = plugin.run()
          ^^^^^^^^^^^^
  File "/usr/src/paperless/src/documents/consumer.py", line 524, in run
    self._fail(
  File "/usr/src/paperless/src/documents/consumer.py", line 302, in _fail
    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
documents.consumer.ConsumerError: 20240222_LIQUIDATION.pdf: Unsupported mime type inode/x-empty
[2024-06-12 09:21:01,569] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[9a827fcc-7c1e-4e1a-89b7-bb07d0c0d2db] raised unexpected: ConsumerError('20240222_LIQUIDATION.pdf: Unsupported mime type inode/x-empty')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 736, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 327, in main_wrap
    raise exc_info[1]
  File "/usr/src/paperless/src/documents/tasks.py", line 147, in consume_file
    msg = plugin.run()
          ^^^^^^^^^^^^
  File "/usr/src/paperless/src/documents/consumer.py", line 524, in run
    self._fail(
  File "/usr/src/paperless/src/documents/consumer.py", line 302, in _fail
    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
documents.consumer.ConsumerError: 20240222_LIQUIDATION.pdf: Unsupported mime type inode/x-empty
```

### Paperless-ngx version

2.9.0

### Host OS

MacOSX - Darwin 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:19:05 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8112 arm64

### Installation method

Docker - official image

### Browser

Safari

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
This is not a paperless bug.  The scanner is likely transferring files slowly and many settings existing to handle this.   You will have to find the best combination for your system.

**Comment by revil-O** [comment]
> This is not a paperless bug. The scanner is likely transferring files slowly and many settings existing to handle this. You will have to find the best combination for your system.

The system waits for 300 seconds to process new documents and when i copy a new or old pdf by hand into the consume folder, the same behavior happens. 

kind regards
