### ISSUE TITLE
Release 2.9.0 Ghostscript rasterizing failed

### ISSUE THREAD

**Issue by Johnnie390** [paperless-ngx/paperless-ngx#6992]
### Description

Scan has stopped working. Please see log.

### Steps to reproduce

Scan an A4 document. Worked on previous releases. Upgraded to Paperless-ngx 2.9.0 today. Scan "seesm" to work, however the document has not been ingested and the logs are reporting something else.

### Webserver logs

```bash
[2024-06-13 13:37:53,995] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/Pass-II.pdf to the task queue.
[2024-06-13 13:37:54,020] [INFO] [celery.worker.strategy] Task documents.tasks.consume_file[8bdf2cc0-c47c-44fa-bb7c-84ef51776202] received
[2024-06-13 13:37:54,050] [INFO] [paperless.tasks] WorkflowTriggerPlugin completed with: 
[2024-06-13 13:37:54,054] [INFO] [paperless.consumer] Consuming Pass-II.pdf
[2024-06-13 13:37:54,069] [INFO] [paperless.parsing.tesseract] pdftotext exited 0
[2024-06-13 13:37:54,240] [ERROR] [ocrmypdf._exec.ghostscript] Catalog dictionary not located in file, unable to proceed
Error: /syntaxerror in --runpdf--
Operand stack:   --nostringval--   --nostringval--   --nostringval--   --nostringval--
Execution stack:   %interp_exit   .runexec2   --nostringval--   runpdf   --nostringval--   2   %stopped_push   --nostringval--   runpdf   runpdf   false   1   %stopped_push   1949   1   3   %oparray_pop   1948   1   3   %oparray_pop   1933   1   3   %oparray_pop   1934   1   3   %oparray_pop   runpdf   runpdf   runpdf   runpdf
Dictionary stack:   --dict:754/1123(ro)(G)--   --dict:0/20(G)--   --dict:86/200(L)--   --dict:6/10(L)--
Current allocation mode is local
GPL Ghostscript 10.03.1: Unrecoverable error, exit code 1

[2024-06-13 13:37:54,243] [ERROR] [paperless.consumer] Error occurred while consuming document Pass-II.pdf: SubprocessOutputError: Ghostscript rasterizing failed. See logs for more information.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_exec/ghostscript.py", line 137, in rasterize_pdf
    p = run(args_gs, stdout=PIPE, stderr=PIPE, check=True)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/subprocess/__init__.py", line 63, in run
    proc = subprocess_run(args, env=env, check=check, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['gs', '-dQUIET', '-dSAFER', '-dBATCH', '-dNOPAUSE', '-dInterpolateControl=-1', '-sDEVICE=jpeggray', '-dFirstPage=1', '-dLastPage=1', '-r300.000000x300.000000', '-dPDFSTOPONERROR', '-o', '-', '-sstdout=%stderr', '-dAutoRotatePages=/None', '-f', '/tmp/ocrmypdf.io.mbhy63j3/origin.pdf']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 368, in parse
    ocrmypdf.ocr(**args)
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/api.py", line 375, in ocr
    return run_pipeline(options=options, plugin_manager=plugin_manager)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 225, in run_pipeline
    return _run_pipeline(options, plugin_manager)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 192, in _run_pipeline
    optimize_messages = exec_concurrent(context, executor)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 119, in exec_concurrent
    executor(
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_concurrent.py", line 74, in __call__
    self._execute(
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/builtin_plugins/concurrency.py", line 141, in _execute
    result = future.result()
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 79, in _exec_page_sync
    ocr_image_out, pdf_page_from_image_out, orientation_correction = process_page(
                                                                     ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/_common.py", line 386, in process_page
    rasterize_preview_out = rasterize_preview(page_context.origin, page_context)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipeline.py", line 371, in rasterize_preview
    page_context.plugin_manager.hook.rasterize_pdf_page(
  File "/usr/local/lib/python3.11/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pluggy/_callers.py", line 139, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/local/lib/python3.11/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/builtin_plugins/ghostscript.py", line 102, in rasterize_pdf_page
    ghostscript.rasterize_pdf(
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_exec/ghostscript.py", line 140, in rasterize_pdf
    raise SubprocessOutputError('Ghostscript rasterizing failed') from e
ocrmypdf.exceptions.SubprocessOutputError: Ghostscript rasterizing failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 327, in main_wrap
    raise exc_info[1]
  File "/usr/src/paperless/src/documents/consumer.py", line 568, in run
    document_parser.parse(self.working_copy, mime_type, self.filename)
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 391, in parse
    raise ParseError(
documents.parsers.ParseError: SubprocessOutputError: Ghostscript rasterizing failed. See logs for more information.
[2024-06-13 13:37:54,247] [ERROR] [paperless.tasks] ConsumeTaskPlugin failed: Pass-II.pdf: Error occurred while consuming document Pass-II.pdf: SubprocessOutputError: Ghostscript rasterizing failed. See logs for more information.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_exec/ghostscript.py", line 137, in rasterize_pdf
    p = run(args_gs, stdout=PIPE, stderr=PIPE, check=True)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/subprocess/__init__.py", line 63, in run
    proc = subprocess_run(args, env=env, check=check, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['gs', '-dQUIET', '-dSAFER', '-dBATCH', '-dNOPAUSE', '-dInterpolateControl=-1', '-sDEVICE=jpeggray', '-dFirstPage=1', '-dLastPage=1', '-r300.000000x300.000000', '-dPDFSTOPONERROR', '-o', '-', '-sstdout=%stderr', '-dAutoRotatePages=/None', '-f', '/tmp/ocrmypdf.io.mbhy63j3/origin.pdf']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 368, in parse
    ocrmypdf.ocr(**args)
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/api.py", line 375, in ocr
    return run_pipeline(options=options, plugin_manager=plugin_manager)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 225, in run_pipeline
    return _run_pipeline(options, plugin_manager)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 192, in _run_pipeline
    optimize_messages = exec_concurrent(context, executor)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 119, in exec_concurrent
    executor(
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_concurrent.py", line 74, in __call__
    self._execute(
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/builtin_plugins/concurrency.py", line 141, in _execute
    result = future.result()
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 79, in _exec_page_sync
    ocr_image_out, pdf_page_from_image_out, orientation_correction = process_page(
                                                                     ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/_common.py", line 386, in process_page
    rasterize_preview_out = rasterize_preview(page_context.origin, page_context)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipeline.py", line 371, in rasterize_preview
    page_context.plugin_manager.hook.rasterize_pdf_page(
  File "/usr/local/lib/python3.11/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pluggy/_callers.py", line 139, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/local/lib/python3.11/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/builtin_plugins/ghostscript.py", line 102, in rasterize_pdf_page
    ghostscript.rasterize_pdf(
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_exec/ghostscript.py", line 140, in rasterize_pdf
    raise SubprocessOutputError('Ghostscript rasterizing failed') from e
ocrmypdf.exceptions.SubprocessOutputError: Ghostscript rasterizing failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 327, in main_wrap
    raise exc_info[1]
  File "/usr/src/paperless/src/documents/consumer.py", line 568, in run
    document_parser.parse(self.working_copy, mime_type, self.filename)
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 391, in parse
    raise ParseError(
documents.parsers.ParseError: SubprocessOutputError: Ghostscript rasterizing failed. See logs for more information.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/tasks.py", line 147, in consume_file
    msg = plugin.run()
          ^^^^^^^^^^^^
  File "/usr/src/paperless/src/documents/consumer.py", line 596, in run
    self._fail(
  File "/usr/src/paperless/src/documents/consumer.py", line 302, in _fail
    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
documents.consumer.ConsumerError: Pass-II.pdf: Error occurred while consuming document Pass-II.pdf: SubprocessOutputError: Ghostscript rasterizing failed. See logs for more information.
[2024-06-13 13:37:54,272] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[8bdf2cc0-c47c-44fa-bb7c-84ef51776202] raised unexpected: ConsumerError('Pass-II.pdf: Error occurred while consuming document Pass-II.pdf: SubprocessOutputError: Ghostscript rasterizing failed. See logs for more information.')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_exec/ghostscript.py", line 137, in rasterize_pdf
    p = run(args_gs, stdout=PIPE, stderr=PIPE, check=True)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/subprocess/__init__.py", line 63, in run
    proc = subprocess_run(args, env=env, check=check, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['gs', '-dQUIET', '-dSAFER', '-dBATCH', '-dNOPAUSE', '-dInterpolateControl=-1', '-sDEVICE=jpeggray', '-dFirstPage=1', '-dLastPage=1', '-r300.000000x300.000000', '-dPDFSTOPONERROR', '-o', '-', '-sstdout=%stderr', '-dAutoRotatePages=/None', '-f', '/tmp/ocrmypdf.io.mbhy63j3/origin.pdf']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 368, in parse
    ocrmypdf.ocr(**args)
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/api.py", line 375, in ocr
    return run_pipeline(options=options, plugin_manager=plugin_manager)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 225, in run_pipeline
    return _run_pipeline(options, plugin_manager)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 192, in _run_pipeline
    optimize_messages = exec_concurrent(context, executor)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 119, in exec_concurrent
    executor(
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_concurrent.py", line 74, in __call__
    self._execute(
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/builtin_plugins/concurrency.py", line 141, in _execute
    result = future.result()
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 79, in _exec_page_sync
    ocr_image_out, pdf_page_from_image_out, orientation_correction = process_page(
                                                                     ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/_common.py", line 386, in process_page
    rasterize_preview_out = rasterize_preview(page_context.origin, page_context)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipeline.py", line 371, in rasterize_preview
    page_context.plugin_manager.hook.rasterize_pdf_page(
  File "/usr/local/lib/python3.11/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pluggy/_callers.py", line 139, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/local/lib/python3.11/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/builtin_plugins/ghostscript.py", line 102, in rasterize_pdf_page
    ghostscript.rasterize_pdf(
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_exec/ghostscript.py", line 140, in rasterize_pdf
    raise SubprocessOutputError('Ghostscript rasterizing failed') from e
ocrmypdf.exceptions.SubprocessOutputError: Ghostscript rasterizing failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 327, in main_wrap
    raise exc_info[1]
  File "/usr/src/paperless/src/documents/consumer.py", line 568, in run
    document_parser.parse(self.working_copy, mime_type, self.filename)
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 391, in parse
    raise ParseError(
documents.parsers.ParseError: SubprocessOutputError: Ghostscript rasterizing failed. See logs for more information.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 736, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 327, in main_wrap
    raise exc_info[1]
  File "/usr/src/paperless/src/documents/tasks.py", line 147, in consume_file
    msg = plugin.run()
          ^^^^^^^^^^^^
  File "/usr/src/paperless/src/documents/consumer.py", line 596, in run
    self._fail(
  File "/usr/src/paperless/src/documents/consumer.py", line 302, in _fail
    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
documents.consumer.ConsumerError: Pass-II.pdf: Error occurred while consuming document Pass-II.pdf: SubprocessOutputError: Ghostscript rasterizing failed. See logs for more information.
```

### Paperless-ngx version

2.9.0

### Host OS

Debian 

### Installation method

Docker - official image

### System status

```json
CONTAINER ID   IMAGE                                        COMMAND                  CREATED       STATUS                    PORTS                    NAMES
2080a8bcb1ac   ghcr.io/paperless-ngx/paperless-ngx:latest   "/sbin/docker-entryp…"   6 hours ago   Up 24 minutes (healthy)   0.0.0.0:8000->8000/tcp   paperless-ngx-webserver-1
711ed37d6781   gotenberg/gotenberg:7.10                     "/usr/bin/tini -- go…"   6 hours ago   Up 24 minutes             3000/tcp                 paperless-ngx-gotenberg-1
08def5bff2ee   ghcr.io/paperless-ngx/tika:latest            "/bin/sh -c 'exec ja…"   6 hours ago   Up 24 minutes             9998/tcp                 paperless-ngx-tika-1
29da197852d7   redis:7                                      "docker-entrypoint.s…"   6 hours ago   Up 24 minutes             6379/tcp                 paperless-ngx-broker-1
f4377b9a3d62   postgres:latest                              "docker-entrypoint.s…"   6 hours ago   Up 24 minutes             5432/tcp                 paperless-ngx-db-1
```

### Browser

Firefox

### Configuration changes

Nothing, have not changed the configs since the initial installation April/May 2024.

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by Johnnie390** [comment]
Any other information required, please let me know.

**Comment by stumpylog** [comment]
Errors with ocr and/or the commands it runs, be that Ghostscript, Tesseract, etc, are not problems we can assist with.

  PDFs can be invalid in any variety of ways and these appear to be missing information.  You can attempt cleaning via qpdf or printing to a PDF.  Fir any further help, you can always start a discussion at ocrmypdf

**Comment by Johnnie390** [comment]
Strange... why were things working yesterday. After the release upgrade to 2.9.0 things have stopped working???

**Comment by s256** [comment]
Same here. Stopped working for all scanned files. 

Outside docker:
![image](https://github.com/paperless-ngx/paperless-ngx/assets/1517486/fa805bdf-78cb-49e1-ab97-dc3ed3e2967e)


When I run the `gs` command in the container I get
```root@613ee447af2a:/usr/src/paperless/consume# gs -dQUIET -dSAFER -dBATCH -dNOPAUSE -dInterpolateControl=-1 -sDEVICE=jpeggray -dFirstPage=2 -dLastPage=2 -r300.000000x300.000000 -dPDFSTOPONERROR -o - -sstdout=%stderr -dAutoRotatePages=/None -f Scan-07-11-24_16-22-25.pdf
Catalog dictionary not located in file, unable to proceed
Error: /syntaxerror in --runpdf--
Operand stack:   --nostringval--   --nostringval--   --nostringval--   --nostringval--
Execution stack:   %interp_exit   .runexec2   --nostringval--   runpdf   --nostringval--   2   %stopped_push   --nostringval--   runpdf   runpdf   false   1   %stopped_push   1949   1   3   %oparray_pop   1948   1   3   %oparray_pop   1933   1   3   %oparray_pop   1934   1   3   %oparray_pop   runpdf   runpdf   runpdf   runpdf
Dictionary stack:   --dict:754/1123(ro)(G)--   --dict:0/20(G)--   --dict:86/200(L)--   --dict:6/10(L)--
Current allocation mode is local
GPL Ghostscript 10.03.1: Unrecoverable error, exit code 1
```
Of course I switched into the consume folder. 

Outside Docker: 
```gs --version                                                                                                                                                                                    Thu 11 Jul 2024 03:11:21 PM UTC
10.00.0
```

in Docker: 
```root@613ee447af2a:/usr/src/paperless/src# gs --version
10.03.1
```

**Comment by s256** [comment]
I just switched to `2.8.6` (Docker). The same files are now scanned correctly.
No changes on the files of course.

Workaround for now:
`docker compose down`
change tag in `docker-compose.yml` to `:2.8.6`

pull the changes

`docker compose pull`

start the container again
`docker compose up -d`

failed tasks will start again.

**Comment by shamoon** [comment]
The point is, as noted in the issue template, paperless doesn’t really handle the OCR, it’s those other tools so problems with particular pdfs should be reported there (linked in the template). In general we update the dependencies regularly (2.9 is not even our latest release) and sometimes they change how they handle malformed PDFs

**Comment by s256** [comment]
Sorry. I forgot to mention that the problem persist in the latest version which is currently `2.11.0`.

While I agree with you @shamoon , SBOM / Supply Chain issue is still there. I would never expect the team around paperless to fix or 3rd party tools. But the software supply chain is a matter of hygiene. So one might want the option to not use the latest version from the dependencies. 

I tried building the docker container myself with `ghostscript 10.00.0` , which unfortunately failed, as the packages seem to be hosted in the paperless github project and I only got a 404. 

I haven't checked if it's a bug in  `gs` in version 10.3, but at this point I am not even able to build the container with `10.2` for example. Maybe I just didn't use the right version in the ENV var. 

happy to built it and do further tests to resolve it upstream. In the meantime I would still like to use paperless with my scans, even if it's with an older version of `gs`.

Once I identify the root cause I'm also happy to provide a unit test with an example file.

**Comment by shamoon** [comment]
Well, I mostly agree with you about "hygiene" whatever that means but PDFs are an insanely messy format, it's not like the version of Ghostscript currently bundled just doesn't work with all PDFs, it's presumably malformed ones. Updating overall has benefits so we try to when we can
