### ISSUE TITLE
[BUG] When using document exporter, get Permission denied for manifest.json

### ISSUE THREAD

**Issue by nothing2obvi** [paperless-ngx/paperless-ngx#7050]
### Description

When I use document exporter to `/usr/src/paperless/backup` I get the following error:

```
PermissionError: [Errno 13] Permission denied: '/usr/src/paperless/backup/manifest.json'
```

### Steps to reproduce

1. Run document exporter
2. Get error

### Webserver logs

```bash
100%|██████████| 123/123 [00:00<00:00, 334.14it/s]
Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/paperless/src/documents/management/commands/document_exporter.py", line 215, in handle
    self.dump()
  File "/usr/src/paperless/src/documents/management/commands/document_exporter.py", line 357, in dump
    manifest_path.write_text(
  File "/usr/local/lib/python3.11/pathlib.py", line 1078, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors, newline=newline) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/usr/src/paperless/backup/manifest.json'
```

### Paperless-ngx version

2.10.1

### Host OS

MacOS Sonoma 14.5

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.10.1",
    "server_os": "Linux-6.9.3-orbstack-00146-g1a8d02c90788-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 17726616993792,
        "available": 2725606653952
    },
    "database": {
        "type": "mysql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "socialaccount.0006_alter_socialaccount_extra_data",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://broker:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-06-20T13:17:40-07:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-06-20T20:08:04.432459Z",
        "classifier_error": null
    }
}
```

### Browser

Opera

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
Well, what are the permissions of `/usr/src/paperless/backup/`?

I would also highly suggest not changing the permissions of `/usr/src/paperless/` ever

**Comment by shamoon** [comment]
> Steps to reproduce
> 
> Run document exporter
> Get error

Given the above is clearly not reproducible, I'll convert this to a discussion for now
