### ISSUE TITLE
Login works but no first page

### ISSUE THREAD

**Issue by aifrog** [paperless-ngx/paperless-ngx#7060]
### Description

I can login, and then the first page apears with "Paperless wird geladen" (loading). After a while the page points me to the documentation.

### Steps to reproduce

see above
I did regular updates using watchtower. This might caused the topic as it worked a couple of days ago.

### Webserver logs

```bash
Paperless-ngx docker container starting...
Mapping UID and GID for paperless:paperless to 1047:100
Creating directory scratch directory /tmp/paperless
Adjusting permissions of paperless files. This may take a while.
Waiting for PostgreSQL to start...
Waiting for Redis...
Connected to Redis broker.
Apply database migrations...
Operations to perform:
  Apply all migrations: account, admin, auditlog, auth, authtoken, contenttypes, django_celery_results, documents, guardian, paperless, paperless_mail, sessions, socialaccount
Running migrations:
  No migrations to apply.
Running Django checks
System check identified no issues (0 silenced).
Did not create superuser, a user admin already exists
Executing /usr/local/bin/paperless_cmd.sh
2024-06-22 07:58:41,448 INFO Set uid to user 0 succeeded
2024-06-22 07:58:41,480 INFO supervisord started with pid 1
2024-06-22 07:58:42,482 INFO spawned: 'gunicorn' with pid 154
2024-06-22 07:58:42,484 INFO spawned: 'celery' with pid 155
2024-06-22 07:58:42,486 INFO spawned: 'celery-beat' with pid 156
2024-06-22 07:58:42,487 INFO spawned: 'consumer' with pid 157
2024-06-22 07:58:42,489 INFO spawned: 'celery-flower' with pid 158
Checking if we should start flower...
Not starting flower
2024-06-22 07:58:42,497 INFO success: celery-flower entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2024-06-22 07:58:42,497 INFO exited: celery-flower (exit status 0; expected)
2024-06-22 07:58:43,498 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-06-22 07:58:43,499 INFO success: celery entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-06-22 07:58:43,499 INFO success: celery-beat entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-06-22 07:58:43,499 INFO success: consumer entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[2024-06-22 09:58:46,792] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/20240519_123032_Scan_001.pdf to the task queue.
[2024-06-22 09:58:47 +0200] [154] [INFO] Starting gunicorn 22.0.0
[2024-06-22 09:58:47 +0200] [154] [INFO] Listening at: http://[::]:8000 (154)
[2024-06-22 09:58:47 +0200] [154] [INFO] Using worker: paperless.workers.ConfigurableWorker
[2024-06-22 09:58:47 +0200] [154] [INFO] Server is ready. Spawning workers
celery beat v5.4.0 (opalescent) is starting.
[2024-06-22 09:58:51,093] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: /usr/src/paperless/consume
[2024-06-22 09:58:51,766] [INFO] [celery.beat] beat: Starting...
[2024-06-22 09:58:52,711] [INFO] [celery.worker.consumer.connection] Connected to redis://:**@paper-redis:6379//
__    -    ... __   -        _
LocalTime -> 2024-06-22 09:58:51
Configuration ->
    . broker -> redis://:**@paper-redis:6379//
    . loader -> celery.loaders.app.AppLoader
    . scheduler -> celery.beat.PersistentScheduler
    . db -> /usr/src/paperless/data/celerybeat-schedule.db
    . logfile -> [stderr]@%INFO
    . maxinterval -> 5.00 minutes (300s)
 
 -------------- celery@paperless-ngx v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- Linux-4.4.302+-x86_64-with-glibc2.36 2024-06-22 09:58:52
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         paperless:0x7fc2dcc9add0
- ** ---------- .> transport:   redis://:**@paper-redis:6379//
- ** ---------- .> results:     
- *** --- * --- .> concurrency: 1 (prefork)
-- ******* ---- .> task events: ON
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . documents.bulk_edit.delete
  . documents.tasks.bulk_update_documents
  . documents.tasks.consume_file
  . documents.tasks.empty_trash
  . documents.tasks.index_optimize
  . documents.tasks.sanity_check
  . documents.tasks.train_classifier
  . documents.tasks.update_document_archive_file
  . paperless_mail.mail.apply_mail_action
  . paperless_mail.mail.error_callback
  . paperless_mail.tasks.process_mail_accounts

[2024-06-22 09:58:53,012] [INFO] [celery.apps.worker] celery@paperless-ngx ready.
[2024-06-22 09:58:53,014] [INFO] [celery.worker.strategy] Task documents.tasks.consume_file[67578d50-8ae0-42f6-ba85-5df06c194e24] received
[2024-06-22 09:58:53,694] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
[2024-06-22 09:58:53,700] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[dfadd997-0ea1-49f3-8350-43a4a040c7c6] received
[2024-06-22 09:59:04,820] [INFO] [paperless.barcodes] Found ASN in barcode: 1
[2024-06-22 09:59:04,820] [INFO] [paperless.tasks] BarcodePlugin completed with no message
[2024-06-22 09:59:08,803] [INFO] [paperless.matching] Document matched WorkflowTrigger 4 from Workflow: perle
[2024-06-22 09:59:09,058] [INFO] [paperless.matching] Document did not match Workflow: hans-christian
[2024-06-22 09:59:09,060] [INFO] [paperless.matching] Document did not match Workflow: markus
[2024-06-22 09:59:09,063] [INFO] [paperless.matching] Document did not match Workflow: eva
[2024-06-22 09:59:09,066] [INFO] [paperless.matching] Document did not match Workflow: maximilian
[2024-06-22 09:59:09,068] [INFO] [paperless.matching] Document did not match Workflow: sebastian
[2024-06-22 09:59:09,070] [INFO] [paperless.matching] Document did not match Workflow: Rechnung
[2024-06-22 09:59:09,070] [INFO] [paperless.tasks] WorkflowTriggerPlugin completed with: Applying WorkflowAction 4 from Workflow: perle

[2024-06-22 09:59:09,122] [ERROR] [paperless.consumer] Not consuming 20240519_123032_Scan_001.pdf: Given ASN 1 already exists!
[2024-06-22 09:59:09,123] [ERROR] [paperless.tasks] ConsumeTaskPlugin failed: 20240519_123032_Scan_001.pdf: Not consuming 20240519_123032_Scan_001.pdf: Given ASN 1 already exists!
Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/tasks.py", line 151, in consume_file
    msg = plugin.run()
          ^^^^^^^^^^^^
  File "/usr/src/paperless/src/documents/consumer.py", line 503, in run
    self.pre_check_asn_value()
  File "/usr/src/paperless/src/documents/consumer.py", line 362, in pre_check_asn_value
    self._fail(
  File "/usr/src/paperless/src/documents/consumer.py", line 302, in _fail
    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
documents.consumer.ConsumerError: 20240519_123032_Scan_001.pdf: Not consuming 20240519_123032_Scan_001.pdf: Given ASN 1 already exists!
[2024-06-22 09:59:11,034] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[67578d50-8ae0-42f6-ba85-5df06c194e24] raised unexpected: ConsumerError('20240519_123032_Scan_001.pdf: Not consuming 20240519_123032_Scan_001.pdf: Given ASN 1 already exists!')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 736, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 327, in main_wrap
    raise exc_info[1]
  File "/usr/src/paperless/src/documents/tasks.py", line 151, in consume_file
    msg = plugin.run()
          ^^^^^^^^^^^^
  File "/usr/src/paperless/src/documents/consumer.py", line 503, in run
    self.pre_check_asn_value()
  File "/usr/src/paperless/src/documents/consumer.py", line 362, in pre_check_asn_value
    self._fail(
  File "/usr/src/paperless/src/documents/consumer.py", line 302, in _fail
    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
documents.consumer.ConsumerError: 20240519_123032_Scan_001.pdf: Not consuming 20240519_123032_Scan_001.pdf: Given ASN 1 already exists!
[2024-06-22 09:59:15,356] [INFO] [celery.app.trace] Task paperless_mail.tasks.process_mail_accounts[dfadd997-0ea1-49f3-8350-43a4a040c7c6] succeeded in 3.452742169611156s: 'No new documents were added.'
[2024-06-22 10:00:00,000] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
[2024-06-22 10:00:00,003] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[c50d90da-b5b3-450b-beff-fcb30f706c33] received
[2024-06-22 10:00:02,820] [INFO] [celery.app.trace] Task paperless_mail.tasks.process_mail_accounts[c50d90da-b5b3-450b-beff-fcb30f706c33] succeeded in 2.8148269774392247s: 'No new documents were added.'
[2024-06-22 10:05:01,350] [INFO] [celery.beat] Scheduler: Sending due task Train the classifier (documents.tasks.train_classifier)
[2024-06-22 10:05:01,353] [INFO] [celery.worker.strategy] Task documents.tasks.train_classifier[3a38890f-5814-4a25-ac3c-1e7ef55c9af1] received
[2024-06-22 10:05:05,740] [INFO] [paperless.classifier] No updates since last training
[2024-06-22 10:05:07,135] [INFO] [celery.app.trace] Task documents.tasks.train_classifier[3a38890f-5814-4a25-ac3c-1e7ef55c9af1] succeeded in 5.77971794269979s: None
[2024-06-22 10:10:00,813] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
[2024-06-22 10:10:00,816] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[8e90e461-6176-4e1c-9649-d81dc83778be] received
[2024-06-22 10:10:02,885] [INFO] [celery.app.trace] Task paperless_mail.tasks.process_mail_accounts[8e90e461-6176-4e1c-9649-d81dc83778be] succeeded in 2.06718647480011s: 'No new documents were added.'
[2024-06-22 10:19:28,772] [WARNING] [django.request] Forbidden: /api/ui_settings/
[2024-06-22 10:20:00,321] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
[2024-06-22 10:20:00,324] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[cc1278d9-521a-4c0f-b04f-b3bfc0248c31] received
[2024-06-22 10:20:02,055] [INFO] [celery.app.trace] Task paperless_mail.tasks.process_mail_accounts[cc1278d9-521a-4c0f-b04f-b3bfc0248c31] succeeded in 1.7288855342194438s: 'No new documents were added.'
[2024-06-22 10:20:28,333] [INFO] [paperless.auth] Login failed for user `hans-christian` from private IP `10.10.1.61`.
[2024-06-22 10:20:42,514] [WARNING] [django.request] Forbidden: /api/ui_settings/
[2024-06-22 10:27:41,552] [WARNING] [django.request] Forbidden: /api/ui_settings/
[2024-06-22 10:30:00,921] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
[2024-06-22 10:30:00,924] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[01c93453-49c1-4d22-87d6-747f2e9d6cf1] received
[2024-06-22 10:30:03,520] [INFO] [celery.app.trace] Task paperless_mail.tasks.process_mail_accounts[01c93453-49c1-4d22-87d6-747f2e9d6cf1] succeeded in 2.594495242461562s: 'No new documents were added.'
```

### Paperless-ngx version

latest

### Host OS

Linux

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by tommy077** [comment]
I have the same issue.
Login screen, then it freezes on the loading page.
Uploading of files thru scan4paperless still works, I am unable to load paperless-ngx web interface and the mobile app does not refresh the filelist.

**Comment by VidVidex** [comment]
I have the same issue. The problem seems to be related to the "UISettings" permission. If the user has this permission they can login just fine.

**Comment by sebingel** [comment]
It is a bug in user permissions.
I faced the same issue. Log in my docker container showed "[WARNING] [django.request] Forbidden: /api/ui_settings/"
I granted "view" to "UI Settings" and the affexted user was able to login again.
I even reproduced this with a new user.
There is a second warning "[WARNING] [django.request] Forbidden: /api/tasks/" whenever my non-admin users are loggin in. probably also a bug. but does not affect login.

**Comment by tommy077** [comment]
> It is a bug in user permissions.
> 
> When checking the log in my Docker container, I saw the following warning: "[WARNING] [django.request] Forbidden: /api/ui_settings/".
> 
> After granting the "view" permission to "UI Settings", the affected user was able to log in again. I was able to reproduce this issue with a new user.
> 
> There is also a second warning: "[WARNING] [django.request] Forbidden: /api/tasks/", which appears whenever non-admin users log in. This is probably also a bug but does not affect the login process.

thanks for the fix, I logged in as my admin account and enabled the UISettings: all for that user account and was able to login again. :-)

**Comment by shamoon** [comment]
It’s mentioned in the release notes. Also #7036
