### ISSUE TITLE
[BUG] Impossible to store high ASN values / wrong error message

### ISSUE THREAD

**Issue by mschiff** [paperless-ngx/paperless-ngx#7150]
### Description

When trying to save an ASN value of >4294967295 I get a nice inline error message saing that the number must be less or equal to 4294967295.

However: trying to save a number less than 4294967295, like 4294967294 leads to an internal server error:

```
{"headers":{"normalizedNames":{},"lazyUpdate":null},"status":500,"statusText":"Internal Server Error","url":"https://<redacted>/api/documents/75/","ok":false,"name":"HttpErrorResponse","message":"Http failure response for https://<redacted>/api/documents/75/: 500 Internal Server Error","error":"\n<!doctype html>\n<html lang=\"en\">\n<head>\n  <title>Server Error (500)</title>\n</head>\n<body>\n  <h1>Server Error (500)</h1><p></p>\n</body>\n</html>\n"}
```

In the logs, I can see that it gives an SQL error, so it seems data types do not match:

```
ERROR:  integer out of range
STATEMENT:  UPDATE "documents_document" SET "deleted_at" = NULL, "restored_at" = NULL, "owner_id" = 4, "correspondent_id" = 5, "storage_path_id" = NULL, "title" ....  "archive_seri
al_number" = 4294967295 WHERE "documents_document"."id" = ...
```

An postgres integer can only be -2147483647 to +2147483647 (serial 1 to 2147483647)
so the correct limit would be 2147483647.

Or you might change the type to bigint (or bigserial), then we would have more possibilities for number-ranges (up to 9223372036854775807)

### Steps to reproduce

Try to assign a ASN of 4294967295 to a document

### Webserver logs

```bash
paperless-webserver-1  | [2024-07-02 00:25:13,107] [ERROR] [django.request] Internal Server Error: /pngx/api/documents/75/
paperless-webserver-1  | Traceback (most recent call last):
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
paperless-webserver-1  |     return self.cursor.execute(sql, params)
paperless-webserver-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-webserver-1  |   File "/usr/local/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute
paperless-webserver-1  |     raise ex.with_traceback(None)
paperless-webserver-1  | psycopg.errors.NumericValueOutOfRange: integer out of range
paperless-webserver-1  |
```
```


### Browser logs

_No response_

### Paperless-ngx version

2.10.2

### Host OS

Gentoo

### Installation method

Docker - official image

### System status

_No response_

### Browser

_No response_

### Configuration changes

_No response_

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
The limit and the error message come directly from the database backend being used, for example in sqlite that number works fine.
