### ISSUE TITLE
[BUG] `document_importer` fails with `[Errno 36] File name too long`

### ISSUE THREAD

**Issue by coaxial** [paperless-ngx/paperless-ngx#7188]
### Description

I am running paperless 2.9.0 (this is the version I exported from). Running it in docker. I want to import my previous install's export, so I `docker exec webserver bash` and in there I run `document_importer ../export`.

When running it, I'm getting this error:

```
Checking the manifest
Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/paperless/src/documents/management/commands/document_importer.py", line 160, in handle
    self._check_manifest_files_valid()
  File "/usr/src/paperless/src/documents/management/commands/document_importer.py", line 264, in _check_manifest_files_valid
    if not doc_archive_path.exists():
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/pathlib.py", line 1235, in exists
    self.stat()
  File "/usr/local/lib/python3.11/pathlib.py", line 1013, in stat
    return os.stat(self, follow_symlinks=follow_symlinks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 36] File name too long: '/usr/src/paperless/export/2022-05-23 Fragebogen_zur_Erfassung_des_Motivprofils_nach_dem_Zuercher_Modell_MPZM_30_Fragen_REDACTED_NAME_23-05-2022_13-56-13-1.pdf-archive.pdf'
```

I'm stumped, because this comes straight from the previous install's export which was running on docker and is being imported into the new install which also runs on docker.

How did the filename become too long in the process? How can I import the documents?

### Steps to reproduce

1. Use paperless 2.9.0 (via image tags) in docker
2. Bind mount a directory to `/usr/src/paperless/export`
3. Import an export that has a long filename using `document_importer`
4. See it fail

### Webserver logs

```bash
Checking the manifest
Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/paperless/src/documents/management/commands/document_importer.py", line 160, in handle
    self._check_manifest_files_valid()
  File "/usr/src/paperless/src/documents/management/commands/document_importer.py", line 264, in _check_manifest_files_valid
    if not doc_archive_path.exists():
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/pathlib.py", line 1235, in exists
    self.stat()
  File "/usr/local/lib/python3.11/pathlib.py", line 1013, in stat
    return os.stat(self, follow_symlinks=follow_symlinks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 36] File name too long: '/usr/src/paperless/export/2022-05-23 Fragebogen_zur_Erfassung_des_Motivprofils_nach_dem_Zuercher_Modell_MPZM_30_Fragen_REDACTED_NAME_23-05-2022_13-56-13-1.pdf-archive.pdf'
```

I have found #5933 that seems related, albeit in another context.

Also happens with paperless 2.10.2
```


### Browser logs

_No response_

### Paperless-ngx version

2.9.0

### Host OS

x86_64

### Installation method

Docker - official image

### System status

_No response_

### Browser

Via bash CLI

### Configuration changes

_No response_

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by coaxial** [comment]
Not a paperless issue, apparently. This is a limitation of encrypted home directories on Linux: the file name limit is 143 chars down from 255 because the last 112 chars are used to store encryption metadata... See https://bugs.launchpad.net/ecryptfs/+bug/344878

Solution appears to be:

- don't encrypt your home dir (whole disk encryption doesn't seem affected)
- use a dir outside of encrypted home to store the files

**Comment by coaxial** [comment]
Not a paperless issue, apparently. This is a limitation of encrypted home directories on Linux: the file name limit is 143 chars down from 255 because the last 112 chars are used to store encryption metadata... See https://bugs.launchpad.net/ecryptfs/+bug/344878

Solution appears to be:

- don't encrypt your home dir (whole disk encryption doesn't seem affected)
- use a dir outside of encrypted home to store the files
