### ISSUE TITLE
[BUG] HTTP 500 due to AttributeError when calling /api/status

### ISSUE THREAD

**Issue by max-4711** [paperless-ngx/paperless-ngx#7210]
### Description

Hello,

i noticed that in version 2.10.2 when opening the settings menu, the spinner next to "System status" is indefinitely spinning. Having checked the logs, i suspect an HTTP 500 from /api/status/ being the reason for that. This HTTP 500 is being caused by an AttributeError, stating that the 'Settings' object has no attribute '_CHANNELS_REDIS_URL' (see the attached webserver log for details).

I've taken a look into the [source code](https://github.com/paperless-ngx/paperless-ngx/blob/ff4203938b954dbe4ea3f64333eeb03795887c55/src/paperless/settings.py#L401) and think that `_CHANNELS_REDIS_URL` is intended to be taken from the environment variable `PAPERLESS_REDIS` (which i have set). Also in the logs on startup it prints the redis URL out and it has the expected value, so i see no issue with the environment variable. (Apart from that, to my understanding from the code, even when the environment variable wouldn't be set, a default value would be used, so there shouldn't ever be a scenario where the settings entirely don't has the attribute `_CHANNELS_REDIS_URL`.) But why the attribute is then in fact missing [when it's being used](https://github.com/paperless-ngx/paperless-ngx/blob/ff4203938b954dbe4ea3f64333eeb03795887c55/src/documents/views.py#L1935) i can't tell.

Unfortunately, as i have skipped a few versions before, i can't really tell when this was introduced. What i can say is, that it even persists when i reset the container. It occurs reliably every time i open the settings page.

Thank you and regards

### Steps to reproduce

1. Go to settings menu
2. Notice the infinite spinner next to "System status" and see the AttributeError caused by API call /api/status (causing an HTTP 500 response)

![image](https://github.com/paperless-ngx/paperless-ngx/assets/13107562/02741545-48c9-48ff-850d-e1cd5ee4fcbf)

### Webserver logs

```bash
[2024-07-10 01:10:49,273] [ERROR] [django.request] Internal Server Error: /api/status/
AttributeError: 'Settings' object has no attribute '_CHANNELS_REDIS_URL'
          ^^^^^^^^^^^^^^^^^^^^^^^
    val = getattr(_wrapped, name)
  File "/usr/local/lib/python3.11/site-packages/django/conf/__init__.py", line 104, in __getattr__
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    redis_url = settings._CHANNELS_REDIS_URL
  File "/usr/src/paperless/src/documents/views.py", line 1928, in get
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    raise exc
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
           ^^^^^^^^^^^^^^^^^^^^^
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 522, in thread_handler
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.11/site-packages/asgiref/current_thread_executor.py", line 40, in run
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ret = await asyncio.shield(exec_coro)
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 468, in __call__
               ^^^^^^^^^^^^^^^^^^^^^^^
    response = await wrapped_callback(
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    raise exc_info[1]
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 518, in thread_handler
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    response = await get_response(request)
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 42, in inner
    raise exc_info[1]
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 518, in thread_handler
Traceback (most recent call last):
[2024-07-10 01:10:49,079] [ERROR] [django.request] Internal Server Error: /api/status/
[2024-07-10 01:10:01,064] [INFO] [celery.app.trace] Task paperless_mail.tasks.process_mail_accounts[066086fa-ed9a-449e-a524-36d66c8f76c2] succeeded in 0.8435392539995519s: 'No new documents were added.'
[2024-07-10 01:10:00,219] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[066086fa-ed9a-449e-a524-36d66c8f76c2] received
[2024-07-10 01:10:00,211] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
[2024-07-10 01:09:03,278] [INFO] [celery.apps.worker] celery@paperless_paperless ready.
[2024-07-10 01:09:03,264] [INFO] [celery.worker.consumer.connection] Connected to redis://paperless_redis:6379//

  . paperless_mail.tasks.process_mail_accounts
  . paperless_mail.mail.error_callback
  . paperless_mail.mail.apply_mail_action
  . documents.tasks.update_document_archive_file
  . documents.tasks.train_classifier
  . documents.tasks.sanity_check
  . documents.tasks.index_optimize
  . documents.tasks.empty_trash
  . documents.tasks.consume_file
  . documents.tasks.bulk_update_documents
  . documents.bulk_edit.delete
[tasks]

                
                .> celery           exchange=celery(direct) key=celery
 -------------- [queues]
--- ***** ----- 
-- ******* ---- .> task events: ON
- *** --- * --- .> concurrency: 1 (prefork)
- ** ---------- .> results:     
- ** ---------- .> transport:   redis://paperless_redis:6379//
- ** ---------- .> app:         paperless:0x7f113521add0
- ** ---------- [config]
- *** --- * --- 
-- ******* ---- Linux-4.4.302+-x86_64-with-glibc2.36 2024-07-10 01:09:03
--- ***** ----- 
 -------------- celery@paperless_paperless v5.4.0 (opalescent)
 
[2024-07-10 01:09:03,129] [INFO] [celery.beat] beat: Starting...
    . maxinterval -> 5.00 minutes (300s)
    . logfile -> [stderr]@%INFO
    . db -> /usr/src/paperless/data/celerybeat-schedule.db
    . scheduler -> celery.beat.PersistentScheduler
    . loader -> celery.loaders.app.AppLoader
    . broker -> redis://paperless_redis:6379//
Configuration ->
LocalTime -> 2024-07-10 01:09:03
__    -    ... __   -        _
[2024-07-10 01:09:03 +0200] [105] [INFO] Server is ready. Spawning workers
[2024-07-10 01:09:03 +0200] [105] [INFO] Using worker: paperless.workers.ConfigurableWorker
[2024-07-10 01:09:03 +0200] [105] [INFO] Listening at: http://[::]:8000 (105)
[2024-07-10 01:09:03 +0200] [105] [INFO] Starting gunicorn 22.0.0
[2024-07-10 01:09:02,917] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: /usr/src/paperless/consume
celery beat v5.4.0 (opalescent) is starting.
2024-07-09 23:08:59,262 INFO exited: celery-flower (exit status 0; expected)
2024-07-09 23:08:59,262 INFO success: consumer entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-07-09 23:08:59,262 INFO success: celery-beat entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-07-09 23:08:59,262 INFO success: celery entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-07-09 23:08:59,261 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Not starting flower
2024-07-09 23:08:58,260 INFO success: celery-flower entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
Checking if we should start flower...
2024-07-09 23:08:58,238 INFO spawned: 'celery-flower' with pid 109
2024-07-09 23:08:58,236 INFO spawned: 'consumer' with pid 108
2024-07-09 23:08:58,234 INFO spawned: 'celery-beat' with pid 107
2024-07-09 23:08:58,232 INFO spawned: 'celery' with pid 106
2024-07-09 23:08:58,230 INFO spawned: 'gunicorn' with pid 105
2024-07-09 23:08:57,227 INFO supervisord started with pid 1
2024-07-09 23:08:57,225 INFO Set uid to user 0 succeeded
Executing /usr/local/bin/paperless_cmd.sh
[31mDid not create superuser, the DB already contains superusers[0m
System check identified no issues (0 silenced).
Running Django checks
  No migrations to apply.
[36;1mRunning migrations:[0m
[1m  Apply all migrations: [0maccount, admin, auditlog, auth, authtoken, contenttypes, django_celery_results, documents, guardian, paperless, paperless_mail, sessions, socialaccount
[36;1mOperations to perform:[0m
Apply database migrations...
Connected to Redis broker.
Waiting for Redis...
Adjusting permissions of paperless files. This may take a while.
Creating directory scratch directory /tmp/paperless
Paperless-ngx docker container starting...
```

### Paperless-ngx version

2.10.2

### Host OS

Synology DSM 7.2.1-69057 Update 5 on an AMD Ryzen R1600

### Installation method

Docker - official image

### System status

```json
[Unavailable due to this error]
```

### Browser

MS Edge (Chromium), but probably not relevant

### Configuration changes

Using LDAP for auth i think i did that according to [this discussion](https://github.com/paperless-ngx/paperless-ngx/discussions/3228); so:
- DJANGO_SETTINGS_MODULE -> paperless.settings_ldap
- PAPERLESS_LDAP_PIP_INSTALL -> true
- Mounted a file settings_ldap.py to /usr/src/paperless/src/paperless/settings_ldap.py

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
So you have modified the settings file manually?  That's not something supported.  I will convert this to a discussion.
