### ISSUE TITLE
[BUG] Paperless cant subscribe/publish to redis with acl ruls set other then allow all

### ISSUE THREAD

**Issue by matthijsvdr** [paperless-ngx/paperless-ngx#7280]
### Description

Paperless is unable to subscribe/publish to redis when more restrictive acl rules are in place.

[ x ] I believe this issue is a bug that affects all users of Paperless-ngx `that use/want to use acl rules for a shared redis setup`, not something specific to my installation. *

### Steps to reproduce

Note: My setup is running on top of Kubernetes however the issue is in the connection with redis with acl rules
Im running the following redis deployment: https://bitnami.com/stack/redis/helm

**Setup**
1) Setup paperless
1.1) Set the `PAPERLESS_REDIS_PREFIX=paperless`
2) Set acl rules un redis using the following command: 
`ACL SETUSER paperless on >secretpassword ~paperless* &paperless* +@all`
3) this results in the following acl rule in redis: `user paperless on sanitize-payload #hashedpassword ~paperless* resetchannels &* +@all`

(note: `+@all` is to wide of a permissions but to make sure it does not interfere with anything)

4) start paperless and watch the log for errors
5) Change the user permissions to `&*` instead of `&paperless*` and there are now no errors in the log

**Manual test:**

1) Set paperless to allow all channels 
`ACL SETUSER paperless on >secretpassword ~paperless* & +@all`
2) Create a second user to test paperless permissions (note that the second user only has an acl for everything under the paperless channel): 
`ACL SETUSER mytestuser on >secretpassword ~paperless* &paperless* +@all`
3) make sure redis is restarted / loaded the new acl
4) start paperless
5) login to the redis-cli with the new user: `redis-cli -h redis-master --user mytestuser --pass secretpassword`
6) Try to subscribe: `subscribe paperless/1.celeryev/worker.heartbeat` you will get messages 
7) Try wildcard subscribe: `psubscribe paperless*` this will also get you messages

Without knowing the ins and outs, it looks like something is trying to subscribe/publish to paths that do not start with paperless even when the PAPERLESS_REDIS_PREFIX is defined. 

I have tried to look all over but i cant find a solution to this other then allow all. I tried finding in the code base where this happens, however im not familiar enough with it or the other libraries that are used to come up with anything that makes sense 😅 

Site note: I did find this: https://github.com/celery/celery/issues/8724 however that did not work for me (and even then it would not allow multiple applications to be run that all use celery)

### Webserver logs

```bash
Traceback (most recent call last):
2024-07-17T12:40:23.448024552+03:00   File "/usr/local/lib/python3.11/site-packages/celery/worker/consumer/consumer.py", line 340, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.11/site-packages/celery/bootsteps.py", line 116, in start
2024-07-17T12:40:23.448046278+03:00     step.start(parent)
  File "/usr/local/lib/python3.11/site-packages/celery/worker/consumer/consumer.py", line 746, in start
2024-07-17T12:40:23.448056485+03:00     c.loop(*c.loop_args())
2024-07-17T12:40:23.448060138+03:00   File "/usr/local/lib/python3.11/site-packages/celery/worker/loops.py", line 97, in asynloop
    next(loop)
2024-07-17T12:40:23.448067454+03:00   File "/usr/local/lib/python3.11/site-packages/kombu/asynchronous/hub.py", line 373, in create_loop
    cb(*cbargs)
2024-07-17T12:40:23.448074500+03:00   File "/usr/local/lib/python3.11/site-packages/kombu/transport/redis.py", line 1344, in on_readable
    self.cycle.on_readable(fileno)
  File "/usr/local/lib/python3.11/site-packages/kombu/transport/redis.py", line 569, in on_readable
    chan.handlers[type]()
  File "/usr/local/lib/python3.11/site-packages/kombu/transport/redis.py", line 962, in _brpop_read
    dest__item = self.client.parse_response(self.client.connection,
2024-07-17T12:40:23.448097465+03:00                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kombu/transport/redis.py", line 247, in parse_response
    ret = super().parse_response(connection, command_name, **options)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 562, in parse_response
    response = connection.read_response()
2024-07-17T12:40:23.448118788+03:00                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 512, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-17T12:40:23.448143998+03:00   File "/usr/local/lib/python3.11/site-packages/redis/_parsers/hiredis.py", line 124, in read_response
    self.read_from_socket()
  File "/usr/local/lib/python3.11/site-packages/redis/_parsers/hiredis.py", line 86, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
[2024-07-17 12:40:23,460] [WARNING] [py.warnings] /usr/local/lib/python3.11/site-packages/celery/worker/consumer/consumer.py:391: CPendingDeprecationWarning: 
2024-07-17T12:40:23.460573052+03:00 In Celery 5.1 we introduced an optional breaking change which
2024-07-17T12:40:23.460575573+03:00 on connection loss cancels all currently executed tasks with late acknowledgement enabled.
These tasks cannot be acknowledged as the connection is gone, and the tasks are automatically redelivered
back to the queue. You can enable this behavior using the worker_cancel_long_running_tasks_on_connection_loss
2024-07-17T12:40:23.460579533+03:00 setting. In Celery 5.1 it is set to False by default. The setting will be set to True by default in Celery 6.0.

2024-07-17T12:40:23.460582010+03:00   warnings.warn(CANCEL_TASKS_BY_DEFAULT, CPendingDeprecationWarning)
2024-07-17T12:40:23.460583135+03:00 
[2024-07-17 12:40:23,475] [INFO] [celery.worker.consumer.connection] Connected to redis://URL-HERE:6379
2024-07-17T12:40:23.496802400+03:00 [2024-07-17 12:40:23,495] [CRITICAL] [celery.worker] Unrecoverable error: NoPermissionError('No permissions to access a channel')
2024-07-17T12:40:23.496811963+03:00 Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python3.11/site-packages/celery/bootsteps.py", line 116, in start
2024-07-17T12:40:23.496821662+03:00     step.start(parent)
  File "/usr/local/lib/python3.11/site-packages/celery/bootsteps.py", line 365, in start
2024-07-17T12:40:23.496825487+03:00     return self.obj.start()
           ^^^^^^^^^^^^^^^^
```

### Paperless-ngx version

v2.11.0

### Host OS

Ubuntu

### Installation method

Other (please describe above)

### System status

```json
{
    "pngx_version": "2.11.0",
    "server_os": "Linux-5.15.0-113-generic-x86_64-with-glibc2.36",
    "install_type": "kubernetes",
    "storage": {
        "total": 1020702720,
        "available": 1002807296
    },
    "database": {
        "type": "postgresql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "socialaccount.0006_alter_socialaccount_extra_data",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis:///1:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "ERROR",
        "index_status": "OK",
        "index_last_modified": "2024-07-17T00:00:00.263381+03:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-07-17T10:05:00.511398Z",
        "classifier_error": null
    }
}
```

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by matthijsvdr** [comment]
For completeness here the kubernetes setup used (Does not include volumes/ingress/certificates/secrets) 

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless
  namespace: default
  labels:
    app: paperless
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 5
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: paperless
  template:
    metadata:
      labels:
        app: paperless
    spec:
      containers:
      - name: paperless
        image: ghcr.io/paperless-ngx/paperless-ngx:2.11
        imagePullPolicy: IfNotPresent
        env:
        - name: PAPERLESS_REDIS
          valueFrom:
            secretKeyRef:
              name: paperless
              key: redis-url
        - name: PAPERLESS_REDIS_PREFIX
          value: "paperless"
        - name: PAPERLESS_DBHOST
          value: "postgresql-postgresql-ha-pgpool.data.svc.cluster.local"
        - name: PAPERLESS_DBNAME
          value: "paperless"
        - name: PAPERLESS_DBUSER
          valueFrom:
            secretKeyRef:
              name: paperless
              key: db-user
        - name: PAPERLESS_DBPASS
          valueFrom:
            secretKeyRef:
              name: paperless
              key: db-password
        - name: PAPERLESS_URL
          value: "https://myURL"
        - name: PAPERLESS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: paperless
              key: secret-key
        - name: PAPERLESS_TIME_ZONE
          value: "myTimezone"
        - name: PAPERLESS_TRUSTED_PROXIES
          value: "proxyIP"
        - name: PAPERLESS_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: paperless
              key: admin-user
        - name: PAPERLESS_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: paperless
              key: admin-password
        - name: PAPERLESS_ADMIN_MAIL
          valueFrom:
            secretKeyRef:
              name: paperless
              key: admin-email
        - name: PAPERLESS_USE_X_FORWARD_HOST
          value: "true"
        - name: PAPERLESS_OCR_LANGUAGES
          value: "" #removed my languages
        - name: PAPERLESS_OCR_LANGUAGE
          value: "eng"
        - name: USERMAP_UID
          value: "1039"
        - name: USERMAP_GID
          value: "100"
        - name: PAPERLESS_PORT
          value: "8000"
        - name: PAPERLESS_FILENAME_FORMAT
          value: "{correspondent}/{created_year}/{title}"
        - name: PAPERLESS_DEBUG
          value: "false"
        volumeMounts:
        - name: paperless-consume
          mountPath: /usr/src/paperless/consume
        - name: paperless-export
          mountPath: /usr/src/paperless/export
        - name: paperless-data
          mountPath: /usr/src/paperless/data
        - name: paperless-media
          mountPath: /usr/src/paperless/media
      volumes:
      - name: paperless-consume
        nfs:
          path: /volume1/k8s-media/paperless/consume
          server: nfsServerIP
      - name: paperless-export
        nfs:
          path: /volume1/k8s-media/paperless/export
          server: nfsServerIP
      - name: paperless-data
        persistentVolumeClaim:
          claimName: paperless-data
      - name: paperless-media
        persistentVolumeClaim:
          claimName: paperless-media
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: paperless
  namespace: default
spec:
  selector:
    app: paperless
  ports:
  - name: http
    targetPort: 8000
    port: 8000

```

**Comment by stumpylog** [comment]
We are not the developers of celery.  You're welcome to request this upstream.

**Comment by stumpylog** [comment]
No, it's interpreted as, that's not our software, we cannot assist with it, please ask those who can.  With limited time and resources, that's quite reasonable. Your own response is unfortunate and not helpful for the community.

**Comment by matthijsvdr** [comment]
> No, it's interpreted as, that's not our software, we cannot assist with it, please ask those who can. 

No, that's how you interpret it, i might not be how other see it.

> With limited time and resources, that's quite reasonable. 

Try to look at it from someone else their perspective. A new user wants to try your project out, yes the setup is different then the default docker compose and they run into an issue. And instead of writing a 10 second reply, you could have also given a few pointers on where to look in codebase (in this case where and how celery is used). 
And then you might create a culture where people feel welcome and might contribute / help out giving you more resources and time. 

> Your own response is unfortunate and not helpful for the community.

Neither is yours sadly. But hey you reap what you sow.

Ill stop responding now as anything further is a waste of time and energy for everyone.
