### ISSUE TITLE
[BUG] Unable to log in with none-admin user

### ISSUE THREAD

**Issue by Mathias-Buder-Bose** [paperless-ngx/paperless-ngx#7304]
### Description

I created a user group named `User` with the privileges listed below (except the ones marked in red) and assigned it to a user (in my case called `Ela`).

![24-07-24_10-31-24](https://github.com/user-attachments/assets/dce59f8e-4334-4e4b-b4d9-3d92b8408535)

As I tried to log in as `Ela`, Paperless didn't complete the login but displayed the following screen:

![24-07-24_09-50-01](https://github.com/user-attachments/assets/c2e8302d-29cf-4e54-8222-06b4d4ad456e)

I analyzed the web server log and noticed that every time I attempted to log in as `Ela`, the following message was printed to the `stderr` stream.

`[2024-07-24 10:16:43,211] [WARNING] [django.request] Forbidden: /api/ui_settings/`

![24-07-24_10-24-49](https://github.com/user-attachments/assets/4755fba3-2d61-4801-bae0-0ab4cfd60b76)

I resolved the issue by enabling the `UISettings` privilege as shown above. I'm unsure if this is a bug or intended behavior, but it took me a while to figure this out.

### Steps to reproduce

1. Create a user group without allowing access to 'UISettings'
2. Create a user and assign them to the user group from step 1
3. Attempt to log in as this user

### Webserver logs

```bash
2024-07-24T08:40:05.409189865Z	stderr	[2024-07-24 10:40:05,407] [INFO] [celery.app.trace] Task paperless_mail.tasks.process_mail_accounts[07ec4789-2abb-47f2-895b-3df8e46be2fe] succeeded in 4.6659650187939405s: 'No new documents were added.'
2024-07-24T08:40:00.736810752Z	stderr	[2024-07-24 10:40:00,735] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[07ec4789-2abb-47f2-895b-3df8e46be2fe] received
2024-07-24T08:40:00.726830613Z	stderr	[2024-07-24 10:40:00,724] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
2024-07-24T08:30:03.446001215Z	stderr	[2024-07-24 10:30:03,444] [INFO] [celery.app.trace] Task paperless_mail.tasks.process_mail_accounts[741ce46c-b072-4560-80e6-707c6f4d84d2] succeeded in 3.351482117548585s: 'No new documents were added.'
2024-07-24T08:30:00.081074724Z	stderr	[2024-07-24 10:30:00,079] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[741ce46c-b072-4560-80e6-707c6f4d84d2] received
2024-07-24T08:30:00.072071602Z	stderr	[2024-07-24 10:30:00,071] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
2024-07-24T08:28:08.122894472Z	stderr	[2024-07-24 10:28:08,122] [WARNING] [django.request] Forbidden: /api/tasks/
2024-07-24T08:25:41.424438428Z	stderr	[2024-07-24 10:25:41,423] [WARNING] [django.request] Forbidden: /api/ui_settings/
2024-07-24T08:25:33.081336751Z	stderr	[2024-07-24 10:25:33,080] [WARNING] [django.request] Forbidden: /api/ui_settings/
2024-07-24T08:20:03.368563741Z	stderr	[2024-07-24 10:20:03,367] [INFO] [celery.app.trace] Task paperless_mail.tasks.process_mail_accounts[ebae3087-720f-47dc-81bb-e37b722dc4eb] succeeded in 3.283886831253767s: 'No new documents were added.'
2024-07-24T08:20:00.078790801Z	stderr	[2024-07-24 10:20:00,077] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[ebae3087-720f-47dc-81bb-e37b722dc4eb] received
2024-07-24T08:20:00.067531601Z	stderr	[2024-07-24 10:20:00,066] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
2024-07-24T08:16:43.211975594Z	stderr	[2024-07-24 10:16:43,211] [WARNING] [django.request] Forbidden: /api/ui_settings/
2024-07-24T08:16:26.693822474Z	stderr	[2024-07-24 10:16:26,693] [WARNING] [django.request] Forbidden: /api/ui_settings/
2024-07-24T08:14:06.909378449Z	stderr	[2024-07-24 10:14:06,908] [WARNING] [django.request] Forbidden: /api/ui_settings/
2024-07-24T08:10:03.332268183Z	stderr	[2024-07-24 10:10:03,331] [INFO] [celery.app.trace] Task paperless_mail.tasks.process_mail_accounts[1375eea2-2a70-4448-99f2-02b479646c35] succeeded in 3.2866915185004473s: 'No new documents were added.'
2024-07-24T08:10:00.041026969Z	stderr	[2024-07-24 10:10:00,038] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[1375eea2-2a70-4448-99f2-02b479646c35] received
2024-07-24T08:10:00.034579435Z	stderr	[2024-07-24 10:10:00,031] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
2024-07-24T08:05:36.421722053Z	stderr	[2024-07-24 10:05:36,420] [INFO] [celery.app.trace] Task documents.tasks.train_classifier[8d48c88c-613d-4fc9-a40c-b949b7fb1ac0] succeeded in 36.345254831016064s: None
2024-07-24T08:05:35.799536039Z	stderr	[2024-07-24 10:05:35,798] [INFO] [paperless.tasks] Saving updated classifier model to /usr/src/paperless/data/classification_model.pickle...
2024-07-24T08:05:00.066780997Z	stderr	[2024-07-24 10:05:00,065] [INFO] [celery.worker.strategy] Task documents.tasks.train_classifier[8d48c88c-613d-4fc9-a40c-b949b7fb1ac0] received
2024-07-24T08:05:00.060328484Z	stderr	[2024-07-24 10:05:00,059] [INFO] [celery.beat] Scheduler: Sending due task Train the classifier (documents.tasks.train_classifier)
2024-07-24T08:00:03.486792492Z	stderr	[2024-07-24 10:00:03,485] [INFO] [celery.app.trace] Task paperless_mail.tasks.process_mail_accounts[58de61cf-cd51-4177-90e1-f925effdc89a] succeeded in 3.34512191824615s: 'No new documents were added.'
2024-07-24T08:00:00.135457918Z	stderr	[2024-07-24 10:00:00,134] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[58de61cf-cd51-4177-90e1-f925effdc89a] received
2024-07-24T08:00:00.126101402Z	stderr	[2024-07-24 10:00:00,125] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
2024-07-24T07:50:03.439049920Z	stderr	[2024-07-24 09:50:03,435] [INFO] [celery.app.trace] Task paperless_mail.tasks.process_mail_accounts[b0e0a2c2-0312-4b0a-9e73-a5531bb9f18d] succeeded in 3.3439977802336216s: 'No new documents were added.'
2024-07-24T07:50:00.082980727Z	stderr	[2024-07-24 09:50:00,081] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[b0e0a2c2-0312-4b0a-9e73-a5531bb9f18d] received
2024-07-24T07:50:00.075294487Z	stderr	[2024-07-24 09:50:00,074] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
2024-07-24T07:49:46.923573354Z	stderr	[2024-07-24 09:49:46,922] [WARNING] [django.request] Forbidden: /api/ui_settings/
2024-07-24T07:49:18.202309030Z	stderr	[2024-07-24 09:49:18,201] [WARNING] [django.request] Forbidden: /api/ui_settings/
2024-07-24T07:49:09.379008757Z	stderr	[2024-07-24 09:49:09,378] [WARNING] [django.request] Forbidden: /api/ui_settings/
2024-07-24T07:48:31.111367527Z	stderr	[2024-07-24 09:48:31,110] [WARNING] [django.request] Forbidden: /api/ui_settings/
2024-07-24T07:47:12.404665454Z	stderr	[2024-07-24 09:47:12,403] [INFO] [paperless.auth] Login failed for user `ela` from private IP `172.31.0.1`.
2024-07-24T07:47:06.548839050Z	stderr	[2024-07-24 09:47:06,547] [INFO] [paperless.auth] Login failed for user `Ela` from private IP `172.31.0.1`.
2024-07-24T07:47:01.086330102Z	stderr	[2024-07-24 09:47:01,085] [INFO] [paperless.auth] Login failed for user `ela` from private IP `172.31.0.1`.
2024-07-24T07:46:28.303501431Z	stderr	FileNotFoundError: Classifier file does not exist (yet). Re-training may be pending.
2024-07-24T07:46:28.303460849Z	stderr	    raise FileNotFoundError(classifier_error)
2024-07-24T07:46:28.303408050Z	stderr	  File "/usr/src/paperless/src/documents/views.py", line 2006, in get
2024-07-24T07:46:28.303341671Z	stderr	Traceback (most recent call last):
2024-07-24T07:46:28.303157519Z	stderr	[2024-07-24 09:46:28,301] [ERROR] [paperless.api] System status detected a possible problem while loading the classifier: Classifier file does not exist (yet). Re-training may be pending.
2024-07-24T07:46:27.172766340Z	stderr	FileNotFoundError: Classifier file does not exist (yet). Re-training may be pending.
2024-07-24T07:46:27.172722954Z	stderr	    raise FileNotFoundError(classifier_error)
2024-07-24T07:46:27.172667637Z	stderr	  File "/usr/src/paperless/src/documents/views.py", line 2006, in get
2024-07-24T07:46:27.172590590Z	stderr	Traceback (most recent call last):
2024-07-24T07:46:27.171929086Z	stderr	[2024-07-24 09:46:27,170] [ERROR] [paperless.api] System status detected a possible problem while loading the classifier: Classifier file does not exist (yet). Re-training may be pending.
2024-07-24T07:45:40.296147965Z	stderr	FileNotFoundError: Classifier file does not exist (yet). Re-training may be pending.
2024-07-24T07:45:40.296099890Z	stderr	    raise FileNotFoundError(classifier_error)
2024-07-24T07:45:40.296053606Z	stderr	  File "/usr/src/paperless/src/documents/views.py", line 2006, in get
2024-07-24T07:45:40.295998231Z	stderr	Traceback (most recent call last):
2024-07-24T07:45:40.295756414Z	stderr	[2024-07-24 09:45:40,294] [ERROR] [paperless.api] System status detected a possible problem while loading the classifier: Classifier file does not exist (yet). Re-training may be pending.
2024-07-24T07:45:39.179369595Z	stderr	FileNotFoundError: Classifier file does not exist (yet). Re-training may be pending.
2024-07-24T07:45:39.179326478Z	stderr	    raise FileNotFoundError(classifier_error)
2024-07-24T07:45:39.179274280Z	stderr	  File "/usr/src/paperless/src/documents/views.py", line 2006, in get
2024-07-24T07:45:39.179183432Z	stderr	Traceback (most recent call last):
2024-07-24T07:45:39.169012348Z	stderr	[2024-07-24 09:45:39,167] [ERROR] [paperless.api] System status detected a possible problem while loading the classifier: Classifier file does not exist (yet). Re-training may be pending.
2024-07-24T07:45:37.501538759Z	stderr	FileNotFoundError: Classifier file does not exist (yet). Re-training may be pending.
2024-07-24T07:45:37.501496209Z	stderr	    raise FileNotFoundError(classifier_error)
2024-07-24T07:45:37.501439973Z	stderr	  File "/usr/src/paperless/src/documents/views.py", line 2006, in get
2024-07-24T07:45:37.501348038Z	stderr	Traceback (most recent call last):
2024-07-24T07:45:37.327553456Z	stderr	[2024-07-24 09:45:37,325] [ERROR] [paperless.api] System status detected a possible problem while loading the classifier: Classifier file does not exist (yet). Re-training may be pending.
2024-07-24T07:45:36.188081839Z	stderr	FileNotFoundError: Classifier file does not exist (yet). Re-training may be pending.
2024-07-24T07:45:36.188029319Z	stderr	    raise FileNotFoundError(classifier_error)
2024-07-24T07:45:36.187935344Z	stderr	  File "/usr/src/paperless/src/documents/views.py", line 2006, in get
2024-07-24T07:45:36.187879071Z	stderr	Traceback (most recent call last):
2024-07-24T07:45:36.187654320Z	stderr	[2024-07-24 09:45:36,184] [ERROR] [paperless.api] System status detected a possible problem while loading the classifier: Classifier file does not exist (yet). Re-training may be pending.
2024-07-24T07:45:36.158585943Z	stderr	[2024-07-24 09:45:36,157] [INFO] [paperless.classifier] Classifier version incompatible: sklearn version update, will re-train
2024-07-24T07:45:17.246424671Z	stderr	[2024-07-24 09:45:17,245] [INFO] [celery.app.trace] Task paperless_mail.tasks.process_mail_accounts[22d0fb27-c48e-4d6c-a18e-c6346c34ec08] succeeded in 4.840339140966535s: 'No new documents were added.'
2024-07-24T07:45:12.293626078Z	stderr	[2024-07-24 09:45:12,290] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[22d0fb27-c48e-4d6c-a18e-c6346c34ec08] received
2024-07-24T07:45:12.276284097Z	stderr	[2024-07-24 09:45:12,272] [INFO] [celery.apps.worker] celery@1b5fc008ba11 ready.
2024-07-24T07:45:12.232454250Z	stderr	[2024-07-24 09:45:12,231] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
2024-07-24T07:45:12.197103303Z	stderr	[2024-07-24 09:45:12,196] [INFO] [celery.worker.consumer.connection] Connected to redis://broker:6379//
2024-07-24T07:45:11.906858404Z	stdout	
2024-07-24T07:45:11.906761737Z	stdout	  . paperless_mail.tasks.process_mail_accounts
2024-07-24T07:45:11.906490980Z	stdout	  . paperless_mail.mail.error_callback
2024-07-24T07:45:11.906438718Z	stdout	  . paperless_mail.mail.apply_mail_action
2024-07-24T07:45:11.906394999Z	stdout	  . documents.tasks.update_document_archive_file
2024-07-24T07:45:11.906325481Z	stdout	  . documents.tasks.train_classifier
2024-07-24T07:45:11.906271059Z	stdout	  . documents.tasks.sanity_check
2024-07-24T07:45:11.905765525Z	stdout	  . documents.tasks.index_optimize
2024-07-24T07:45:11.905567616Z	stdout	  . documents.tasks.empty_trash
2024-07-24T07:45:11.905528907Z	stdout	  . documents.tasks.consume_file
2024-07-24T07:45:11.905470695Z	stdout	  . documents.tasks.bulk_update_documents
2024-07-24T07:45:11.905419446Z	stdout	  . documents.bulk_edit.delete
2024-07-24T07:45:11.905384422Z	stdout	[tasks]
2024-07-24T07:45:11.905341091Z	stdout	
2024-07-24T07:45:11.905306264Z	stdout	                
2024-07-24T07:45:11.905254760Z	stdout	                .> celery           exchange=celery(direct) key=celery
2024-07-24T07:45:11.905218557Z	stdout	 -------------- [queues]
2024-07-24T07:45:11.905175702Z	stdout	--- ***** ----- 
2024-07-24T07:45:11.905135807Z	stdout	-- ******* ---- .> task events: ON
2024-07-24T07:45:11.905085523Z	stdout	- *** --- * --- .> concurrency: 1 (prefork)
2024-07-24T07:45:11.905037852Z	stdout	- ** ---------- .> results:     
2024-07-24T07:45:11.904996395Z	stdout	- ** ---------- .> transport:   redis://broker:6379//
2024-07-24T07:45:11.904935288Z	stdout	- ** ---------- .> app:         paperless:0x7f3c9363ea90
2024-07-24T07:45:11.904888493Z	stdout	- ** ---------- [config]
2024-07-24T07:45:11.904832481Z	stdout	- *** --- * --- 
2024-07-24T07:45:11.904782851Z	stdout	-- ******* ---- Linux-4.4.180+-x86_64-with-glibc2.36 2024-07-24 09:45:11
2024-07-24T07:45:11.904734576Z	stdout	--- ***** ----- 
2024-07-24T07:45:11.904656891Z	stdout	 -------------- celery@1b5fc008ba11 v5.4.0 (opalescent)
2024-07-24T07:45:11.904496135Z	stdout	 
2024-07-24T07:45:11.660824948Z	stdout	    . maxinterval -> 5.00 minutes (300s)
2024-07-24T07:45:11.660783512Z	stdout	    . logfile -> [stderr]@%INFO
2024-07-24T07:45:11.660725343Z	stdout	    . db -> /usr/src/paperless/data/celerybeat-schedule.db
2024-07-24T07:45:11.660673255Z	stdout	    . scheduler -> celery.beat.PersistentScheduler
2024-07-24T07:45:11.660628589Z	stdout	    . loader -> celery.loaders.app.AppLoader
2024-07-24T07:45:11.660314082Z	stdout	    . broker -> redis://broker:6379//
2024-07-24T07:45:11.660006857Z	stderr	[2024-07-24 09:45:11,657] [INFO] [celery.beat] beat: Starting...
2024-07-24T07:45:11.660273346Z	stdout	Configuration ->
2024-07-24T07:45:11.660194638Z	stdout	LocalTime -> 2024-07-24 09:45:11
2024-07-24T07:45:11.659623911Z	stdout	__    -    ... __   -        _
2024-07-24T07:45:09.307339141Z	stderr	[2024-07-24 09:45:09 +0200] [115] [INFO] Server is ready. Spawning workers
2024-07-24T07:45:09.307280412Z	stderr	[2024-07-24 09:45:09 +0200] [115] [INFO] Using worker: paperless.workers.ConfigurableWorker
2024-07-24T07:45:09.307097149Z	stderr	[2024-07-24 09:45:09 +0200] [115] [INFO] Listening at: http://[::]:8000 (115)
2024-07-24T07:45:09.304765490Z	stderr	[2024-07-24 09:45:09 +0200] [115] [INFO] Starting gunicorn 22.0.0
2024-07-24T07:45:09.191408074Z	stderr	[2024-07-24 09:45:09,161] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: /usr/src/paperless/consume
2024-07-24T07:45:04.317318477Z	stdout	celery beat v5.4.0 (opalescent) is starting.
2024-07-24T07:44:57.645772069Z	stdout	2024-07-24 07:44:57,466 INFO exited: celery-flower (exit status 0; expected)
2024-07-24T07:44:57.645723121Z	stdout	2024-07-24 07:44:57,465 INFO success: consumer entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-07-24T07:44:57.645660924Z	stdout	2024-07-24 07:44:57,465 INFO success: celery-beat entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-07-24T07:44:57.645543062Z	stdout	2024-07-24 07:44:57,465 INFO success: celery entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-07-24T07:44:57.465364742Z	stdout	2024-07-24 07:44:57,465 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-07-24T07:44:56.462266223Z	stdout	Not starting flower
2024-07-24T07:44:56.461430662Z	stdout	2024-07-24 07:44:56,460 INFO success: celery-flower entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2024-07-24T07:44:56.461213692Z	stdout	Checking if we should start flower...
2024-07-24T07:44:56.431485048Z	stdout	2024-07-24 07:44:56,431 INFO spawned: 'celery-flower' with pid 119
2024-07-24T07:44:56.427687036Z	stdout	2024-07-24 07:44:56,427 INFO spawned: 'consumer' with pid 118
2024-07-24T07:44:56.423630077Z	stdout	2024-07-24 07:44:56,423 INFO spawned: 'celery-beat' with pid 117
2024-07-24T07:44:56.419786800Z	stdout	2024-07-24 07:44:56,419 INFO spawned: 'celery' with pid 116
2024-07-24T07:44:56.414943965Z	stdout	2024-07-24 07:44:56,414 INFO spawned: 'gunicorn' with pid 115
2024-07-24T07:44:55.411096285Z	stdout	2024-07-24 07:44:55,410 INFO supervisord started with pid 1
2024-07-24T07:44:55.402568880Z	stdout	2024-07-24 07:44:55,402 INFO Set uid to user 0 succeeded
2024-07-24T07:44:53.155118208Z	stdout	Executing /usr/local/bin/paperless_cmd.sh
2024-07-24T07:44:52.339246435Z	stdout	Did not create superuser, a user admin already exists
2024-07-24T07:44:45.680852845Z	stdout	System check identified no issues (0 silenced).
2024-07-24T07:44:35.772586377Z	stdout	Running Django checks
2024-07-24T07:44:32.422299056Z	stdout	  Applying paperless_mail.0025_alter_mailaccount_owner_alter_mailrule_owner_and_more... OK
2024-07-24T07:44:31.155814266Z	stdout	  Applying documents.1051_alter_correspondent_owner_alter_document_owner_and_more... OK
2024-07-24T07:44:27.655543136Z	stdout	  Applying documents.1050_customfield_extra_data_and_more... OK
2024-07-24T07:44:26.244039645Z	stdout	  Applying authtoken.0004_alter_tokenproxy_options... OK
2024-07-24T07:44:25.946093647Z	stdout	Running migrations:
2024-07-24T07:44:25.802293454Z	stdout	  Apply all migrations: account, admin, auditlog, auth, authtoken, contenttypes, django_celery_results, documents, guardian, paperless, paperless_mail, sessions, socialaccount
2024-07-24T07:44:25.801745018Z	stdout	Operations to perform:
2024-07-24T07:44:09.744226092Z	stdout	Apply database migrations...
2024-07-24T07:44:09.086158427Z	stdout	Connected to Redis broker.
2024-07-24T07:44:08.994539703Z	stdout	Waiting for Redis...
2024-07-24T07:44:06.113265341Z	stdout	Connected to PostgreSQL
2024-07-24T07:44:04.994671743Z	stdout	Waiting for PostgreSQL to start...
2024-07-24T07:44:04.876835761Z	stdout	Adjusting permissions of paperless files. This may take a while.
2024-07-24T07:44:04.876361406Z	stdout	mkdir: created directory '/tmp/paperless'
2024-07-24T07:44:04.852622830Z	stdout	Creating directory scratch directory /tmp/paperless
2024-07-24T07:43:58.591164931Z	stdout	Mapping UID and GID for paperless:paperless to 1026:100
2024-07-24T07:43:58.503040286Z	stdout	Paperless-ngx docker container starting...
```

### Paperless-ngx version

2.11.1

### Host OS

Linux-4.4.180+-x86_64-with-glibc2.36

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.11.1",
    "server_os": "Linux-4.4.180+-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 2875817492480,
        "available": 1658742829056
    },
    "database": {
        "type": "postgresql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "paperless_mail.0001_initial_squashed_0009_mailrule_assign_tags",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://broker:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-07-24T00:00:12.201771+02:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-07-24T08:05:35.866104Z",
        "classifier_error": null
    }
}
```

### Browser

Chrome

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by ignoreigor** [comment]
Same behaviour is mentioned here: https://github.com/astubenbord/paperless-mobile
No login via app for users with no rights to view user-settings.

**Comment by shamoon** [comment]
Correct, UIswttings are needed to login

**Comment by Mathias-Buder-Bose** [comment]
Thanks for the quick reply, @shamoon. I believe it would be beneficial to remove the option to set permissions for `UIsettings` if they are mandatory for every user to log in.

**Comment by shamoon** [comment]
People sometimes want to create users that can't access the webui
