### ISSUE TITLE
Unsupported mime type message/rfc822

### ISSUE THREAD

**Issue by cybernard** [paperless-ngx/paperless-ngx#7354]
### Description

Unsupported mime type message/rfc822

Traceback (most recent call last):

### Steps to reproduce

connect paperless-ngx to email account

many emails including but not limited to but including email orders receipts from amazon.com

### Webserver logs

```bash
2024-07-31 01:57:13,158] [DEBUG] [paperless.consumer] Detected mime type: message/rfc822

[2024-07-31 01:57:13,160] [ERROR] [paperless.consumer] Unsupported mime type message/rfc822

[2024-07-31 01:57:13,160] [ERROR] [paperless.tasks] ConsumeTaskPlugin failed: Delivered Your Amazon.com order #111-8070136-2637047.eml: Unsupported mime type message/rfc822

Traceback (most recent call last):

  File "/opt/paperless/src/documents/tasks.py", line 151, in consume_file

    msg = plugin.run()

          ^^^^^^^^^^^^

  File "/opt/paperless/src/documents/consumer.py", line 534, in run

    self._fail(

  File "/opt/paperless/src/documents/consumer.py", line 302, in _fail

    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception

documents.consumer.ConsumerError: Delivered Your Amazon.com order #111-8070136-2637047.eml: Unsupported mime type message/rfc822

[2024-07-31 01:57:13,447] [DEBUG] [paperless.tasks] Skipping plugin CollatePlugin

[2024-07-31 01:57:13,448] [DEBUG] [paperless.tasks] Skipping plugin BarcodePlugin

[2024-07-31 01:57:13,448] [DEBUG] [paperless.tasks] Executing plugin WorkflowTriggerPlugin

[2024-07-31 01:57:13,449] [INFO] [paperless.tasks] WorkflowTriggerPlugin completed with:

[2024-07-31 01:57:13,449] [DEBUG] [paperless.tasks] Executing plugin ConsumeTaskPlugin

[2024-07-31 01:57:13,454] [INFO] [paperless.consumer] Consuming Thank you for your Pizza Hut order.eml

[2024-07-31 01:57:13,456] [DEBUG] [paperless.consumer] Detected mime type: message/rfc822

[2024-07-31 01:57:13,458] [ERROR] [paperless.consumer] Unsupported mime type message/rfc822

[2024-07-31 01:57:13,458] [ERROR] [paperless.tasks] ConsumeTaskPlugin failed: Thank you for your Pizza Hut order.eml: Unsupported mime type message/rfc822

Traceback (most recent call last):

  File "/opt/paperless/src/documents/tasks.py", line 151, in consume_file

    msg = plugin.run()

          ^^^^^^^^^^^^

  File "/opt/paperless/src/documents/consumer.py", line 534, in run

    self._fail(

  File "/opt/paperless/src/documents/consumer.py", line 302, in _fail

    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception

documents.consumer.ConsumerError: Thank you for your Pizza Hut order.eml: Unsupported mime type message/rfc822
```

### Paperless-ngx version

newest 

### Host OS

proxmox

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.11.2",
    "server_os": "Linux-6.8.8-4-pve-x86_64-with-glibc2.36",
    "install_type": "bare-metal",
    "storage": {
        "total": 10464022528,
        "available": 3001741312
    },
    "database": {
        "type": "postgresql",
        "url": "paperlessdb",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "paperless_mail.0011_remove_mailrule_assign_tag_squashed_0024_alter_mailrule_name_and_more",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://localhost:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-07-31T01:54:26.947869Z",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-07-31T02:05:00.045898Z",
        "classifier_error": null
    }
}
```

### Browser

firefox

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
Consuming emails requires Tika and Gotenberg.

**Comment by cybernard** [comment]
I just installed this product and had the option to add my email account even without said packages.
Can I add these packages manually?  Will it work if I do?

**Comment by shamoon** [comment]
You can consume e.g. pdf attachments from emails without them but consuming actual emails / converting emails to PDF requires them. https://docs.paperless-ngx.com/configuration/#tika
