### ISSUE TITLE
[BUG] Not consuming file as it's a duplicate of a document in trash

### ISSUE THREAD

**Issue by umoenks** [paperless-ngx/paperless-ngx#7393]
### Description

Re-submitting a file **after** deleting it results in a file duplicate detection as long as it is still in Trash:
![grafik](https://github.com/user-attachments/assets/b3a2085f-e716-47b1-b399-0ffdc2fb3b23)

The error message is misleading. It points to a document index (`#3146`), which actually does not exist anymore (opening `/3146/details` results in a 404):
![grafik](https://github.com/user-attachments/assets/264451c0-62b5-431c-b883-763a7fbf9eec)
![grafik](https://github.com/user-attachments/assets/541d3b51-ce71-4ac0-97cf-59ff5b21f84d)

After deleting the document from Trash (e.g. by emptying Trash), the file can be submitted again successfully.

Yup, I know, it might raise questions why a person should **want** to first delete an already archived file and then resubmit the very same file. But there are cases, trust me.

Anyway, the return message is misleading by telling the user that the document already exist, but actually navigating to the document tells the user it's absent.

I suggest to exclude the Trash content from checking for duplicates.

### Steps to reproduce

1. Upload a file, e.g. [TEST PDF.pdf](https://github.com/user-attachments/files/16501243/TEST.PDF.pdf)
![grafik](https://github.com/user-attachments/assets/4f9cef1d-69a3-4276-8de7-fc9574ece78e)
2. Open the archived document once paperless-ngx finished processing it.
![grafik](https://github.com/user-attachments/assets/f7e9db07-fa61-40fc-8d05-10835c397df1)
3. Delete the file, i.e. move it to trash.
![grafik](https://github.com/user-attachments/assets/9361e8fd-21a5-43a6-9a84-8c74d7b33444)
![grafik](https://github.com/user-attachments/assets/60236076-3a71-4cf8-8a65-e24922d9f4d9)
4. Upload the same file from step 1 and see paperless-ngx report a duplicate.
![grafik](https://github.com/user-attachments/assets/cde3a254-e5f0-4727-8159-8bb90820c926)

### Webserver logs

```bash
[2024-08-05 18:16:35,466] [INFO] [paperless.consumer] Consuming TEST PDF.pdf

[2024-08-05 18:16:35,470] [DEBUG] [paperless.consumer] Detected mime type: application/pdf

[2024-08-05 18:16:35,484] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser

[2024-08-05 18:16:35,492] [DEBUG] [paperless.consumer] Parsing TEST PDF.pdf...

[2024-08-05 18:16:35,509] [INFO] [paperless.parsing.tesseract] pdftotext exited 0

[2024-08-05 18:16:35,828] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-ngx8yuqt_go/TEST PDF.pdf'), 'output_file': PosixPath('/tmp/paperless/paperless-qld5q61a/archive.pdf'), 'use_threads': True, 'jobs': '1', 'language': 'deu', 'output_type': 'pdfa', 'progress_bar': False, 'color_conversion_strategy': 'RGB', 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-qld5q61a/sidecar.txt')}

[2024-08-05 18:16:36,178] [WARNING] [ocrmypdf._pipeline] This PDF is marked as a Tagged PDF. This often indicates that the PDF was generated from an office document and does not need OCR. PDF pages processed by OCRmyPDF may not be tagged correctly.

[2024-08-05 18:16:36,182] [INFO] [ocrmypdf._pipeline] skipping all processing on this page

[2024-08-05 18:16:36,247] [INFO] [ocrmypdf._pipelines.ocr] Postprocessing...

[2024-08-05 18:16:36,845] [WARNING] [ocrmypdf._metadata] Some input metadata could not be copied because it is not permitted in PDF/A. You may wish to examine the output PDF's XMP metadata.

[2024-08-05 18:16:36,931] [INFO] [ocrmypdf._pipeline] Image optimization ratio: 1.00 savings: 0.0%

[2024-08-05 18:16:36,932] [INFO] [ocrmypdf._pipeline] Total file size ratio: 1.16 savings: 14.0%

[2024-08-05 18:16:36,936] [INFO] [ocrmypdf._pipelines._common] Output file is a PDF/A-2B (as expected)

[2024-08-05 18:16:36,949] [DEBUG] [paperless.parsing.tesseract] Incomplete sidecar file: discarding.

[2024-08-05 18:16:37,016] [INFO] [paperless.parsing.tesseract] pdftotext exited 0

[2024-08-05 18:16:37,017] [DEBUG] [paperless.consumer] Generating thumbnail for TEST PDF.pdf...

[2024-08-05 18:16:37,024] [DEBUG] [paperless.parsing] Execute: convert -density 300 -scale 500x5000> -alpha remove -strip -auto-orient -define pdf:use-cropbox=true /tmp/paperless/paperless-qld5q61a/archive.pdf[0] /tmp/paperless/paperless-qld5q61a/convert.webp

[2024-08-05 18:16:38,701] [INFO] [paperless.parsing] convert exited 0

[2024-08-05 18:16:38,869] [DEBUG] [paperless.consumer] Saving record to database

[2024-08-05 18:16:38,874] [DEBUG] [paperless.consumer] Creation date from st_mtime: 2024-08-05 18:16:34+02:00

[2024-08-05 18:16:39,591] [INFO] [paperless.handlers] Assigning correspondent Telekom Deutschland GmbH to 2024-08-05 TEST PDF

[2024-08-05 18:16:39,635] [INFO] [paperless.handlers] Assigning document type Rechnung to 2024-08-05 Telekom Deutschland GmbH TEST PDF

[2024-08-05 18:16:46,482] [DEBUG] [paperless.consumer] Deleting file /tmp/paperless/paperless-ngx8yuqt_go/TEST PDF.pdf

[2024-08-05 18:16:46,490] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-qld5q61a

[2024-08-05 18:16:46,493] [INFO] [paperless.consumer] Document 2024-08-05 Telekom Deutschland GmbH TEST PDF consumption finished

[2024-08-05 18:16:46,501] [INFO] [paperless.tasks] ConsumeTaskPlugin completed with: Success. New document id 3146 created

[2024-08-05 18:17:44,547] [DEBUG] [paperless.tasks] Skipping plugin CollatePlugin

[2024-08-05 18:17:44,549] [DEBUG] [paperless.tasks] Executing plugin BarcodePlugin

[2024-08-05 18:17:44,550] [DEBUG] [paperless.barcodes] Scanning for barcodes using PYZBAR

[2024-08-05 18:17:45,163] [INFO] [paperless.tasks] BarcodePlugin completed with no message

[2024-08-05 18:17:45,171] [DEBUG] [paperless.tasks] Executing plugin WorkflowTriggerPlugin

[2024-08-05 18:17:45,177] [INFO] [paperless.tasks] WorkflowTriggerPlugin completed with:

[2024-08-05 18:17:45,179] [DEBUG] [paperless.tasks] Executing plugin ConsumeTaskPlugin

[2024-08-05 18:17:45,210] [ERROR] [paperless.consumer] Not consuming TEST PDF.pdf: It is a duplicate of TEST PDF (#3146)

[2024-08-05 18:17:45,211] [ERROR] [paperless.tasks] ConsumeTaskPlugin failed: TEST PDF.pdf: Not consuming TEST PDF.pdf: It is a duplicate of TEST PDF (#3146)

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/tasks.py", line 151, in consume_file

    msg = plugin.run()

          ^^^^^^^^^^^^

  File "/usr/src/paperless/src/documents/consumer.py", line 507, in run

    self.pre_check_duplicate()

  File "/usr/src/paperless/src/documents/consumer.py", line 326, in pre_check_duplicate

    self._fail(

  File "/usr/src/paperless/src/documents/consumer.py", line 302, in _fail

    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception

documents.consumer.ConsumerError: TEST PDF.pdf: Not consuming TEST PDF.pdf: It is a duplicate of TEST PDF (#3146)

[2024-08-05 18:19:24,932] [DEBUG] [paperless.tasks] Skipping plugin CollatePlugin

[2024-08-05 18:19:24,934] [DEBUG] [paperless.tasks] Executing plugin BarcodePlugin

[2024-08-05 18:19:24,935] [DEBUG] [paperless.barcodes] Scanning for barcodes using PYZBAR

[2024-08-05 18:19:25,557] [INFO] [paperless.tasks] BarcodePlugin completed with no message

[2024-08-05 18:19:25,624] [DEBUG] [paperless.tasks] Executing plugin WorkflowTriggerPlugin

[2024-08-05 18:19:25,643] [INFO] [paperless.tasks] WorkflowTriggerPlugin completed with:

[2024-08-05 18:19:25,645] [DEBUG] [paperless.tasks] Executing plugin ConsumeTaskPlugin

[2024-08-05 18:19:25,676] [ERROR] [paperless.consumer] Not consuming TEST PDF.pdf: It is a duplicate of TEST PDF (#3146)

[2024-08-05 18:19:25,678] [ERROR] [paperless.tasks] ConsumeTaskPlugin failed: TEST PDF.pdf: Not consuming TEST PDF.pdf: It is a duplicate of TEST PDF (#3146)

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/tasks.py", line 151, in consume_file

    msg = plugin.run()

          ^^^^^^^^^^^^

  File "/usr/src/paperless/src/documents/consumer.py", line 507, in run

    self.pre_check_duplicate()

  File "/usr/src/paperless/src/documents/consumer.py", line 326, in pre_check_duplicate

    self._fail(

  File "/usr/src/paperless/src/documents/consumer.py", line 302, in _fail

    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception

documents.consumer.ConsumerError: TEST PDF.pdf: Not consuming TEST PDF.pdf: It is a duplicate of TEST PDF (#3146)
```

### Paperless-ngx version

2.11.2

### Host OS

Ubuntu 22.04.3 LTS x86_64

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.11.2",
    "server_os": "Linux-5.15.0-116-generic-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 685627145728,
        "available": 42762112000
    },
    "database": {
        "type": "postgresql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "paperless_mail.0011_remove_mailrule_assign_tag_squashed_0024_alter_mailrule_name_and_more",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://broker:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-08-05T20:13:35.537548+02:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-08-05T18:05:05.493685Z",
        "classifier_error": null
    }
}
```

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Not a bug. The document is in the trash as you said.

Also #7355

**Comment by umoenks** [comment]
Well, yes and no. The document is there, somewhere sitting in the trash. #7355 makes this fact a lot clearer than the current output. I'd still prefer exclusion of the trash when checking for ducplicates.

Not sure about the implications on other parts of paperless-ngx, but speaking from a John-Doe-user-perspective: telling that the document is a duplicate of some document, which is not accessible, is counter-intuitive and really confusing.

Happy to discuss this further!

**Comment by shamoon** [comment]
Allowing duplicates will cause problems in other ways (what happens if the duplicate is restored), thats why the solution is to make the problem clearer.

**Comment by umoenks** [comment]
Ack. Makes sense.
Looking forward seeing #7355 integrated in a new release.
Thanks for your efforts!
