### ISSUE TITLE
[BUG] Broken celery beat schedule path setting

### ISSUE THREAD

**Issue by tku137** [paperless-ngx/paperless-ngx#7430]
### Description

Since celery appends a ".db" to the beat_schedule_filename since Python 3 (https://docs.celeryq.dev/en/stable/userguide/configuration.html#beat-schedule-filename), this lead to a bug with `CELERY_BEAT_SCHEDULE_FILENAME` in `settings.py`. Since the default file name was set to `celerybeat-schedule.db` (https://github.com/paperless-ngx/paperless-ngx/blob/dev/src/paperless/settings.py#L826), celery created a file named `celerybeat-schedule.db.db` during startup, leading to a nun-functioning scheduler. 

I noticed this when mails no longer were automatically processed and after digging through the mail.log files, I found multiple `_dbm.error: cannot add item to database` critical errors.

Simple PR fixing the issue is on the way.

### Steps to reproduce

1. Install paperles-ngx from source
2. Set up mail account and rule
3. Mails are not processed
4. Look into `mail.log`

### Webserver logs

```bash
[2024-08-08 16:23:29,400] [CRITICAL] [celery.beat] beat raised exception <class '_dbm.error'>: error('cannot add item to database')
Traceback (most recent call last):
  File "/usr/lib/python3.11/shelve.py", line 111, in __getitem__
    value = self.cache[key]
            ~~~~~~~~~~^^^^^
KeyError: 'entries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/celery/beat.py", line 570, in _create_schedule
    self._store['entries']
    ~~~~~~~~~~~^^^^^^^^^^^
  File "/usr/lib/python3.11/shelve.py", line 113, in __getitem__
    f = BytesIO(self.dict[key.encode(self.keyencoding)])
                ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: b'entries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/celery/apps/beat.py", line 113, in start_scheduler
    service.start()
  File "/usr/local/lib/python3.11/dist-packages/celery/beat.py", line 634, in start
    humanize_seconds(self.scheduler.max_interval))
                     ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/kombu/utils/objects.py", line 40, in __get__
    return super().__get__(instance, owner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/celery/beat.py", line 677, in scheduler
    return self.get_scheduler()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/celery/beat.py", line 668, in get_scheduler
    return symbol_by_name(self.scheduler_cls, aliases=aliases)(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/celery/beat.py", line 513, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.11/dist-packages/celery/beat.py", line 264, in __init__
    self.setup_schedule()
  File "/usr/local/lib/python3.11/dist-packages/celery/beat.py", line 541, in setup_schedule
    self._create_schedule()
  File "/usr/local/lib/python3.11/dist-packages/celery/beat.py", line 574, in _create_schedule
    self._store['entries'] = {}
    ~~~~~~~~~~~^^^^^^^^^^^
  File "/usr/lib/python3.11/shelve.py", line 125, in __setitem__
    self.dict[key.encode(self.keyencoding)] = f.getvalue()
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_dbm.error: cannot add item to database



[2024-08-09 08:52:59,328] [ERROR] [celery.beat] Removing corrupted schedule file '/media/Vault1/data/celerybeat-schedule.db.db': error('db type could not be determined')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/celery/beat.py", line 531, in setup_schedule
    self._store = self._open_schedule()
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/celery/beat.py", line 521, in _open_schedule
    return self.persistence.open(self.schedule_filename, writeback=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
                         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/dbm/__init__.py", line 89, in open
    raise error[0]("db type could not be determined")
dbm.error: db type could not be determined
```

### Paperless-ngx version

2.11.2

### Host OS

Debian 12

### Installation method

Bare metal

### Browser

Safari

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
The filename is clearly not the issue, given it works fine and has since the transition to celery.  The actual problem seems more likely to be a corrupt file, which this "fixes" with a new file being created.

**Comment by tku137** [comment]
This was exactly my thought, but I could reproduce the behaviour by deleting the file and afterwards a new `celerybeat-schedule.db.db` got created and ultimately the same behaviour occured.

Also, I tried setting `CELERY_BEAT_SCHEDULE_FILENAME = os.path.join(DATA_DIR, "celerybeat-schedule.db.db")`, which created a `celerybeat-schedule.db.db.db` file. Setting `CELERY_BEAT_SCHEDULE_FILENAME = os.path.join(DATA_DIR, "celerybeat-schedule")` solved the issue and is in accordance with celery documentation.

**Comment by stumpylog** [comment]
If this was a big, then scheduled tasks wouldn't have been running for anyone since the transition some time ago. I think people would have noticed

**Comment by shamoon** [comment]
I’m not clear what the issue is but what you’re describing would mean celery just doesn’t work for about 2 years, which is clearly not the case.

`[2024-08-09 06:10:00,609] [DEBUG] [paperless_mail] Rule inbox@***.com.Incoming: Processed 0 matching mail(s)`

**Comment by tku137** [comment]
Well I could reproduce it on my installation, and found my solution after skimming through logs and celery docs. I can confirm it is not a corrupt database file or anything I have configured myself.

I may have inadvertently worked around another root cause and will investigate further. Apologies for any confusion.

**Comment by shamoon** [comment]
No problem at all, I would be curious to hear what else you find out, I do see your link to the celery docs. But I've checked on multiple machines. And again this is something that hasn't changed quite literally for [2 years](https://github.com/paperless-ngx/paperless-ngx/blame/dev/src/paperless/settings.py#L826)

<img width="699" alt="Screenshot 2024-08-09 at 6 58 28 AM" src="https://github.com/user-attachments/assets/2a4d03c2-f7ce-4c5f-a860-79ce360e385b">
<img width="705" alt="Screenshot 2024-08-09 at 6 58 45 AM" src="https://github.com/user-attachments/assets/75e1af66-8ec0-4a89-9c63-ed59298a8e07">

**Comment by tku137** [comment]
I indeed found something:

I had set some paperless folders to a smb mount. Thus I had this in `paperlesss.conf`: `PAPERLESS_DATA_DIR=/media/Vault1/data`. After migrating back to `PAPERLESS_DATA_DIR=/opt/paperless/data`, I still get a `celerybeat-schedule.db.db` (so still with double .db ending) file even after deleting and rebooting, BUT, fetching mails works:

`[2024-08-09 15:00:00,000] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)`

And they get correctly consumed:

`[2024-08-09 15:00:00,822] [DEBUG] [paperless_mail] Rule Mailbox.pdfs: Processing mail Test Dokument 2 from x with 1 attachment(s)
[2024-08-09 15:00:00,828] [INFO] [paperless_mail] Rule Mailbox. Mailbox.pdfs: Consuming attachment IMG_20191105_0001.pdf from mail Test Dokument 2 from x
[2024-08-09 15:00:00,854] [DEBUG] [paperless_mail] Rule Mailbox.Tpdfs: Processed 2 matching mail(s)`

So new observation: using smb share as data dir seems a bad idea?

**Comment by shamoon** [comment]
Yea there might be more specifics to it but I have heard people having issues with using network shares
