### ISSUE TITLE
[BUG] Uploading a Deutsche Telekom invoice fails with InputFileError

### ISSUE THREAD

**Issue by saschaspeidel** [paperless-ngx/paperless-ngx#7452]
### Description

Currently it is not possible to upload invoice of Deutsche Telekom. The workflow stops with an error. Other pdfs work just fine

### Steps to reproduce

1. Upload file
2. select invoice of Deutsche Telekom
3. get error in the bottom right corner: "Rechnung_08_2024_8513297801.pdf: Error occurred while consuming document Rechnung_08_2024_8513297801.pdf: InputFileError:"

### Webserver logs

```bash
[2024-08-12 14:11:28,058] [INFO] [paperless.consumer] Consuming Rechnung_08_2024_8513297801.pdf

[2024-08-12 14:11:28,061] [DEBUG] [paperless.consumer] Detected mime type: application/pdf

[2024-08-12 14:11:28,070] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser

[2024-08-12 14:11:28,076] [DEBUG] [paperless.consumer] Parsing Rechnung_08_2024_8513297801.pdf...

[2024-08-12 14:11:28,176] [INFO] [paperless.parsing.tesseract] pdftotext exited 0

[2024-08-12 14:11:28,543] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-ngxo3lqstjf/Rechnung_08_2024_8513297801.pdf'), 'output_file': PosixPath('/tmp/paperless/paperless-xeip5owd/archive.pdf'), 'use_threads': True, 'jobs': 2, 'language': 'deu+eng', 'output_type': 'pdfa', 'progress_bar': False, 'color_conversion_strategy': 'RGB', 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-xeip5owd/sidecar.txt')}

[2024-08-12 14:11:29,125] [WARNING] [paperless.parsing.tesseract] Encountered an error while running OCR: . Attempting force OCR to get the text.

[2024-08-12 14:11:29,125] [DEBUG] [paperless.parsing.tesseract] Fallback: Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-ngxo3lqstjf/Rechnung_08_2024_8513297801.pdf'), 'output_file': PosixPath('/tmp/paperless/paperless-xeip5owd/archive-fallback.pdf'), 'use_threads': True, 'jobs': 2, 'language': 'deu+eng', 'output_type': 'pdfa', 'progress_bar': False, 'color_conversion_strategy': 'RGB', 'force_ocr': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-xeip5owd/sidecar-fallback.txt')}

[2024-08-12 14:11:29,260] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-xeip5owd

[2024-08-12 14:11:29,266] [ERROR] [paperless.consumer] Error occurred while consuming document Rechnung_08_2024_8513297801.pdf: InputFileError:

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipeline.py", line 173, in get_pdfinfo

    return PdfInfo(

           ^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/pdfinfo/info.py", line 1100, in __init__

    with Pdf.open(infile) as pdf:

         ^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/pikepdf/_methods.py", line 398, in open

    pdf = Pdf._open(

          ^^^^^^^^^^

pikepdf._core.PdfError: /tmp/ocrmypdf.io.8j21jp58/origin.pdf: unable to find /Root dictionary

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 368, in parse

    ocrmypdf.ocr(**args)

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/api.py", line 375, in ocr

    return run_pipeline(options=options, plugin_manager=plugin_manager)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 225, in run_pipeline

    return _run_pipeline(options, plugin_manager)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 176, in _run_pipeline

    pdfinfo = get_pdfinfo(

              ^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipeline.py", line 185, in get_pdfinfo

    raise InputFileError() from e

ocrmypdf.exceptions.InputFileError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipeline.py", line 173, in get_pdfinfo

    return PdfInfo(

           ^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/pdfinfo/info.py", line 1100, in __init__

    with Pdf.open(infile) as pdf:

         ^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/pikepdf/_methods.py", line 398, in open

    pdf = Pdf._open(

          ^^^^^^^^^^

pikepdf._core.PdfError: /tmp/ocrmypdf.io.54jnoncr/origin.pdf: unable to find /Root dictionary

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 419, in parse

    ocrmypdf.ocr(**args)

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/api.py", line 375, in ocr

    return run_pipeline(options=options, plugin_manager=plugin_manager)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 225, in run_pipeline

    return _run_pipeline(options, plugin_manager)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 176, in _run_pipeline

    pdfinfo = get_pdfinfo(

              ^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipeline.py", line 185, in get_pdfinfo

    raise InputFileError() from e

ocrmypdf.exceptions.InputFileError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 327, in main_wrap

    raise exc_info[1]

  File "/usr/src/paperless/src/documents/consumer.py", line 582, in run

    document_parser.parse(self.working_copy, mime_type, self.filename)

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 431, in parse

    raise ParseError(f"{e.__class__.__name__}: {e!s}") from e

documents.parsers.ParseError: InputFileError:

[2024-08-12 14:11:29,284] [ERROR] [paperless.tasks] ConsumeTaskPlugin failed: Rechnung_08_2024_8513297801.pdf: Error occurred while consuming document Rechnung_08_2024_8513297801.pdf: InputFileError:

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipeline.py", line 173, in get_pdfinfo

    return PdfInfo(

           ^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/pdfinfo/info.py", line 1100, in __init__

    with Pdf.open(infile) as pdf:

         ^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/pikepdf/_methods.py", line 398, in open

    pdf = Pdf._open(

          ^^^^^^^^^^

pikepdf._core.PdfError: /tmp/ocrmypdf.io.8j21jp58/origin.pdf: unable to find /Root dictionary

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 368, in parse

    ocrmypdf.ocr(**args)

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/api.py", line 375, in ocr

    return run_pipeline(options=options, plugin_manager=plugin_manager)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 225, in run_pipeline

    return _run_pipeline(options, plugin_manager)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 176, in _run_pipeline

    pdfinfo = get_pdfinfo(

              ^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipeline.py", line 185, in get_pdfinfo

    raise InputFileError() from e

ocrmypdf.exceptions.InputFileError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipeline.py", line 173, in get_pdfinfo

    return PdfInfo(

           ^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/pdfinfo/info.py", line 1100, in __init__

    with Pdf.open(infile) as pdf:

         ^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/pikepdf/_methods.py", line 398, in open

    pdf = Pdf._open(

          ^^^^^^^^^^

pikepdf._core.PdfError: /tmp/ocrmypdf.io.54jnoncr/origin.pdf: unable to find /Root dictionary

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 419, in parse

    ocrmypdf.ocr(**args)

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/api.py", line 375, in ocr

    return run_pipeline(options=options, plugin_manager=plugin_manager)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 225, in run_pipeline

    return _run_pipeline(options, plugin_manager)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 176, in _run_pipeline

    pdfinfo = get_pdfinfo(

              ^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipeline.py", line 185, in get_pdfinfo

    raise InputFileError() from e

ocrmypdf.exceptions.InputFileError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 327, in main_wrap

    raise exc_info[1]

  File "/usr/src/paperless/src/documents/consumer.py", line 582, in run

    document_parser.parse(self.working_copy, mime_type, self.filename)

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 431, in parse

    raise ParseError(f"{e.__class__.__name__}: {e!s}") from e

documents.parsers.ParseError: InputFileError:

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/tasks.py", line 151, in consume_file

    msg = plugin.run()

          ^^^^^^^^^^^^

  File "/usr/src/paperless/src/documents/consumer.py", line 613, in run

    self._fail(

  File "/usr/src/paperless/src/documents/consumer.py", line 302, in _fail

    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception

documents.consumer.ConsumerError: Rechnung_08_2024_8513297801.pdf: Error occurred while consuming document Rechnung_08_2024_8513297801.pdf: InputFileError:
```

### Paperless-ngx version

2.11.2

### Host OS

Ubuntu 22.04

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.11.2",
    "server_os": "Linux-5.15.0-117-generic-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 71743148032,
        "available": 47645237248
    },
    "database": {
        "type": "postgresql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "paperless_mail.0011_remove_mailrule_assign_tag_squashed_0024_alter_mailrule_name_and_more",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://broker:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-08-12T14:11:22.359755+02:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-08-12T12:05:00.974969Z",
        "classifier_error": null
    }
}
```

### Browser

Chrome

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
Yeah ur PDF is not valid. You can search around here for some options to try, but this is not a paperless bug.

**Comment by saschaspeidel** [comment]
How is a pdf that has no issues in other applications not valid?

Only Issue was #1281 where it says that the issue should be resolved. Maybe I'm searching wrong?

**Comment by shamoon** [comment]
Friend, from the template you used above:

```
Also, note that Paperless-ngx does not perform OCR or archive file creation itself, those are handled by other tools. Problems with OCR or archive versions of specific files should likely be raised 'upstream', see https://github.com/ocrmypdf/OCRmyPDF/issues or https://github.com/tesseract-ocr/tesseract/issues
```

And Google, which does suggest the file is messed up: https://www.google.com/search?q=unable+to+find+%2FRoot+dictionary

PDF is a messy format, lots of companies generate invalid PDFs (is that really so surprising? 😅) and some PDF tools ignore these, but not always the OCR tool we use.
