### ISSUE TITLE
[BUG] Paperless tries to interpretjpg as pdf

### ISSUE THREAD

**Issue by praetorianer777** [paperless-ngx/paperless-ngx#746]
### Description

It seems that the processing tries to process a jpg file as a pdf file

### Expected behavior

Interpret as jpg

```
Apr 17 09:54:01 paperless python3[3586]: 11:54:01 [Q] ERROR Failed [Zimmer.jpg] - Unable to get page count.
Apr 17 09:54:01 paperless python3[3586]: Syntax Warning: May not be a PDF file (continuing anyway)
Apr 17 09:54:01 paperless python3[3586]: Syntax Error: Couldn't find trailer dictionary
Apr 17 09:54:01 paperless python3[3586]: Syntax Error: Couldn't find trailer dictionary
Apr 17 09:54:01 paperless python3[3586]: Syntax Error: Couldn't read xref table
Apr 17 09:54:01 paperless python3[3586]:  : Traceback (most recent call last):
Apr 17 09:54:01 paperless python3[3586]:   File "/opt/paperless/.local/lib/python3.8/site-packages/pdf2image/pdf2image.py", line 479, in pdfinfo_from_path
Apr 17 09:54:01 paperless python3[3586]:     raise ValueError
Apr 17 09:54:01 paperless python3[3586]: ValueError
Apr 17 09:54:01 paperless python3[3586]: During handling of the above exception, another exception occurred:
Apr 17 09:54:01 paperless python3[3586]: Traceback (most recent call last):
Apr 17 09:54:01 paperless python3[3586]:   File "/opt/paperless/.local/lib/python3.8/site-packages/django_q/cluster.py", line 432, in worker
Apr 17 09:54:01 paperless python3[3586]:     res = f(*task["args"], **task["kwargs"])
Apr 17 09:54:01 paperless python3[3586]:   File "/opt/paperless/src/documents/tasks.py", line 198, in consume_file
Apr 17 09:54:01 paperless python3[3586]:     separators = scan_file_for_separating_barcodes(path)
Apr 17 09:54:01 paperless python3[3586]:   File "/opt/paperless/src/documents/tasks.py", line 105, in scan_file_for_separating_barcodes
Apr 17 09:54:01 paperless python3[3586]:     pages_from_path = convert_from_path(filepath, output_folder=path)
Apr 17 09:54:01 paperless python3[3586]:   File "/opt/paperless/.local/lib/python3.8/site-packages/pdf2image/pdf2image.py", line 98, in convert_from_path
Apr 17 09:54:01 paperless python3[3586]:     page_count = pdfinfo_from_path(pdf_path, userpw, poppler_path=poppler_path)["Pages"]
Apr 17 09:54:01 paperless python3[3586]:   File "/opt/paperless/.local/lib/python3.8/site-packages/pdf2image/pdf2image.py", line 488, in pdfinfo_from_path
Apr 17 09:54:01 paperless python3[3586]:     raise PDFPageCountError(
Apr 17 09:54:01 paperless python3[3586]: pdf2image.exceptions.PDFPageCountError: Unable to get page count.
Apr 17 09:54:01 paperless python3[3586]: Syntax Warning: May not be a PDF file (continuing anyway)
Apr 17 09:54:01 paperless python3[3586]: Syntax Error: Couldn't find trailer dictionary
Apr 17 09:54:01 paperless python3[3586]: Syntax Error: Couldn't find trailer dictionary
Apr 17 09:54:01 paperless python3[3586]: Syntax Error: Couldn't read xref table
```

### Steps to reproduce

add jpg file to the consume directory

### Paperless-ngx version

1.7.0-rc1

### Host OS

Ubuntu 20.04

### Installation method

Bare metal

### Browser

Chrome

**Comment by praetorianer777** [comment]
Same error when uploading the file with the web-ui

**Comment by gador** [comment]
Do you have `PAPERLESS_CONSUMER_ENABLE_BARCODES` enabled?
How do you run paperless? Docker, bare-metal?

If Docker, please post your docker-compose file and the environment variables used.

If possible, please enable DEBUG mode and post the result. 

The problem seems to be associated with barcode detection.

**Comment by praetorianer777** [comment]
Yes I have enabled the barcode-option!
Is this parameter described in the docs or am I too stupid to find it?

**Comment by gador** [comment]
The documentation of beta [can be found here](https://paperless-ngx.readthedocs.io/en/beta/configuration.html)

Right now, the barcode detector can only work with pdfs.
I'm working on a file extension detection and tiff support. Other formats probably won't be needed, as TIFF and PDF's are (AFAIK) the only common multipage single file documents.
So the jpgs should throw a warning in the future but wont hinder archiving.

**Comment by praetorianer777** [comment]
Ah ok, then I will disable it for now, thanks!
