### ISSUE TITLE
[BUG] Server Error (500) entering Documents view

### ISSUE THREAD

**Issue by pippep** [paperless-ngx/paperless-ngx#7486]
### Description

The Documents view is not working. When I click on Documents, I receive a Server Error (500).

![Immagine incollata](https://github.com/user-attachments/assets/421e5bd3-3da5-431a-b441-88af935c2eb9)

Downgrading `python-django-soft-delete` from version 1.0.14 to 1.0.13 resolves the problem. This issue is reproducible, as I have tested it multiple times.

### Steps to reproduce

1. Update `python-django-soft-delete` to version 1.0.14
2. Click on Documents
3. Get Server Error (500)

### Webserver logs

```bash
[2024-08-17 07:21:17,600] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: /mnt/paperless/consume

[2024-08-17 07:21:34,863] [DEBUG] [paperless.classifier] Gathering data from database...

[2024-08-17 07:21:34,871] [WARNING] [paperless.tasks] Classifier error: no such column: documents_document.transaction_id

[2024-08-17 07:21:35,189] [ERROR] [paperless.tasks] Error while emptying trash: no such column: documents_document.transaction_id

Traceback (most recent call last):

  File "/usr/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute

    return self.cursor.execute(sql, params)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute

    return super().execute(query, params)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

sqlite3.OperationalError: no such column: documents_document.transaction_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/share/paperless/src/documents/tasks.py", line 321, in empty_trash

    documents.delete()  # this is effectively a hard delete

    ^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/django/db/models/query.py", line 1147, in delete

    collector.collect(del_query)

  File "/usr/lib/python3.12/site-packages/django/db/models/deletion.py", line 284, in collect

    new_objs = self.add(

               ^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/django/db/models/deletion.py", line 126, in add

    if not objs:

           ^^^^

  File "/usr/lib/python3.12/site-packages/django/db/models/query.py", line 412, in __bool__

    self._fetch_all()

  File "/usr/lib/python3.12/site-packages/django/db/models/query.py", line 1881, in _fetch_all

    self._result_cache = list(self._iterable_class(self))

                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__

    results = compiler.execute_sql(

              ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql

    cursor.execute(sql, params)

  File "/usr/lib/python3.12/site-packages/django/db/backends/utils.py", line 67, in execute

    return self._execute_with_wrappers(

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers

    return executor(sql, params, many, context)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/django/db/backends/utils.py", line 84, in _execute

    with self.db.wrap_database_errors:

  File "/usr/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__

    raise dj_exc_value.with_traceback(traceback) from exc_value

  File "/usr/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute

    return self.cursor.execute(sql, params)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute

    return super().execute(query, params)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

django.db.utils.OperationalError: no such column: documents_document.transaction_id

[2024-08-17 08:05:00,100] [DEBUG] [paperless.classifier] Gathering data from database...

[2024-08-17 08:05:00,106] [WARNING] [paperless.tasks] Classifier error: no such column: documents_document.transaction_id

[2024-08-17 12:50:12,083] [DEBUG] [paperless.classifier] Gathering data from database...

[2024-08-17 12:50:12,088] [WARNING] [paperless.tasks] Classifier error: no such column: documents_document.transaction_id

[2024-08-17 13:05:00,098] [DEBUG] [paperless.classifier] Gathering data from database...

[2024-08-17 13:05:00,103] [WARNING] [paperless.tasks] Classifier error: no such column: documents_document.transaction_id

[2024-08-17 16:45:44,710] [DEBUG] [paperless.classifier] Gathering data from database...

[2024-08-17 16:45:44,717] [WARNING] [paperless.tasks] Classifier error: no such column: documents_document.transaction_id

[2024-08-17 17:05:00,098] [DEBUG] [paperless.classifier] Gathering data from database...

[2024-08-17 17:05:00,102] [WARNING] [paperless.tasks] Classifier error: no such column: documents_document.transaction_id
```

### Paperless-ngx version

2.11.2

### Host OS

Archlinux x86_64

### Installation method

Bare metal

### Browser

Firefox 129.0.1

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
We don't yet support 1.0.14: https://github.com/paperless-ngx/paperless-ngx/blob/ad8c60d153dc2e4eb57883aa0fc34f574f5e1f81/Pipfile.lock#L544-L551
