### ISSUE TITLE
[BUG] Upload fails with NLTK issue after update to 2.11.5

### ISSUE THREAD

**Issue by esclear** [paperless-ngx/paperless-ngx#7519]
### Description

I just updated my paperless-ngx docker container to 2.11.5 from 2.11.0.
Since the update, I can no longer upload new documents.

During ingestion of the uploaded document, I am seeing the issue shown below.

I've found #2876 from some time ago, but for me, it doesn't seem to be dependent on the document, nor does it work with documents which were previously uploaded without issue.

### Steps to reproduce

1. Upload any PDF file, e.g. by dragging and dropping it

### Webserver logs

```bash
[2024-08-23 03:20:58,067] [ERROR] [paperless.tasks] ConsumeTaskPlugin failed: test_file.pdf: The following error occurred while storing document test_file.pdf after parsing:

**********************************************************************

  Resource [93mpunkt_tab[0m not found.

  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk

  >>> nltk.download('punkt_tab')

  [0m

  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt_tab/english/[0m

  Searched in:

    - PosixPath('/usr/share/nltk_data')

**********************************************************************

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 327, in main_wrap

    raise exc_info[1]

  File "/usr/src/paperless/src/documents/consumer.py", line 670, in run

    document_consumption_finished.send(

  File "/usr/local/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 176, in send

    return [

           ^

  File "/usr/local/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>

    (receiver, receiver(signal=self, sender=sender, **named))

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/paperless/src/documents/signals/handlers.py", line 95, in set_correspondent

    potential_correspondents = matching.match_correspondents(document, classifier)

                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/paperless/src/documents/matching.py", line 37, in match_correspondents

    pred_id = classifier.predict_correspondent(document.content) if classifier else None

              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/paperless/src/documents/classifier.py", line 413, in predict_correspondent

    X = self.data_vectorizer.transform([self.preprocess_content(content)])

                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/paperless/src/documents/classifier.py", line 386, in preprocess_content

    words: list[str] = word_tokenize(

                       ^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/nltk/tokenize/__init__.py", line 142, in word_tokenize

    sentences = [text] if preserve_line else sent_tokenize(text, language)

                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/nltk/tokenize/__init__.py", line 119, in sent_tokenize

    tokenizer = _get_punkt_tokenizer(language)

                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/nltk/tokenize/__init__.py", line 105, in _get_punkt_tokenizer

    return PunktTokenizer(language)

           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/nltk/tokenize/punkt.py", line 1744, in __init__

    self.load_lang(lang)

  File "/usr/local/lib/python3.11/site-packages/nltk/tokenize/punkt.py", line 1749, in load_lang

    lang_dir = find(f"tokenizers/punkt_tab/{lang}/")

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/nltk/data.py", line 579, in find

    raise LookupError(resource_not_found)

LookupError:

**********************************************************************

  Resource [93mpunkt_tab[0m not found.

  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk

  >>> nltk.download('punkt_tab')

  [0m

  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt_tab/english/[0m

  Searched in:

    - PosixPath('/usr/share/nltk_data')

**********************************************************************

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/tasks.py", line 149, in consume_file

    msg = plugin.run()

          ^^^^^^^^^^^^

  File "/usr/src/paperless/src/documents/consumer.py", line 733, in run

    self._fail(

  File "/usr/src/paperless/src/documents/consumer.py", line 304, in _fail

    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception

documents.consumer.ConsumerError: test_file.pdf: The following error occurred while storing document test_file.pdf after parsing:

**********************************************************************

  Resource [93mpunkt_tab[0m not found.

  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk

  >>> nltk.download('punkt_tab')

  [0m

  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt_tab/english/[0m

  Searched in:

    - PosixPath('/usr/share/nltk_data')

**********************************************************************
```

### Paperless-ngx version

2.11.5

### Host OS

NixOS 24.05

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.11.5",
    "server_os": "Linux-6.8.1-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 202324283392,
        "available": 116536750080
    },
    "database": {
        "type": "sqlite",
        "url": "/config/db.sqlite3",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "paperless_mail.0011_remove_mailrule_assign_tag_squashed_0024_alter_mailrule_name_and_more",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://broker:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-08-23T00:00:03.216949+02:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-08-23T01:05:00.319679Z",
        "classifier_error": null
    }
}
```

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Ugh nltk have really bungled their releases of late. I’m going to revert that and release a .6

**Comment by ChrisMagnuson** [comment]
We are on 2.11.6 and don't seem to be able to able to upload files due to what seems like this same issue.

It gets to the point of scanning the file for the date and then errors with
```
Redacted.pdf: The following error occurred while storing document Redacted.pdf after parsing: ********************************************************************** Resource [93mpunkt_tab[0m not found. Please use the NLTK Downloader to obtain the resource: [31m>>> import nltk >>> nltk.download('punkt_tab') [0m For more information see: https://www.nltk.org/data.html Attempted to load [93mtokenizers/punkt_tab/english/[0m Searched in: - PosixPath('/usr/share/nltk_data') ********************************************************************** 
```

**Comment by esclear** [comment]
I can confirm that 2.11.6 solved my issue, so I guess yours is a different one, @ChrisMagnuson.

**Comment by shamoon** [comment]
My guess is you did not correctly upgrade somehow. .6 definitely fixes this

**Comment by shamoon** [comment]
I see, a cloudron issue.
