### ISSUE TITLE
[BUG] [Errno 19] No such device on adding document

### ISSUE THREAD

**Issue by philuk1971** [paperless-ngx/paperless-ngx#752]
### Description

After a fresh install of Paperless-ngx via docker-compose I can only add a single document with subsequent attempts resultin in [Errno 19] No such device. I've repeated the behaviour (3 times) by removing all docker images and volumes, reinstalling and getting the same behaviour.

The behaviour is the same for upload vie the dashboard and the watch folder.

Docker-compose file:
`version: "3.4"
services:
  broker:
    image: redis:6.0
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - /mnt/storage/filing/database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /mnt/storage/filing/data:/usr/src/paperless/data
      - /mnt/storage/filing/media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - /mnt/storage/filing/scanned_files:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db

volumes:
  data:
  media:
  pgdata:
  redisdata:`

### Expected behavior

Add files successfully via the watch folder and through the web UI.

### Steps to reproduce

For first document upload:
1. Install via the install-paperless-ngx.sh script
2. After successful login to Paperless, drag file to upload area on dashboard
3. Document is uploaded, accessible through interface, details are editable, and ocr has worked.

For subsequent document upload:
1. After successful login to Paperless, drag file to upload area on dashboard or copy document to watch folder
2. Document is not uploaded successfully

Logs for both successful and unsuccessful attempts in server logs section below.

### Webserver logs

```bash
Application log for SUCCESSFUL upload:
[2022-04-18 13:42:40,826] [INFO] [paperless.consumer] Consuming 00e19d23-0666-483f-afea-e55db2cb5aa8

[2022-04-18 13:42:40,828] [DEBUG] [paperless.consumer] Detected mime type: application/pdf

[2022-04-18 13:42:40,841] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser

[2022-04-18 13:42:40,847] [DEBUG] [paperless.consumer] Parsing 00e19d23-0666-483f-afea-e55db2cb5aa8...

[2022-04-18 13:42:41,020] [DEBUG] [paperless.parsing.tesseract] Extracted text from PDF file /tmp/paperless/paperless-upload-7cf7n6k4

[2022-04-18 13:42:41,235] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': '/tmp/paperless/paperless-upload-7cf7n6k4', 'output_file': '/tmp/paperless/paperless-465_b0hd/archive.pdf', 'use_threads': True, 'jobs': 2, 'language': 'eng', 'output_type': 'pdfa', 'progress_bar': False, 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': '/tmp/paperless/paperless-465_b0hd/sidecar.txt'}

[2022-04-18 13:43:10,364] [DEBUG] [paperless.parsing.tesseract] Using text from sidecar file

[2022-04-18 13:43:10,367] [DEBUG] [paperless.consumer] Generating thumbnail for 00e19d23-0666-483f-afea-e55db2cb5aa8...

[2022-04-18 13:43:10,375] [DEBUG] [paperless.parsing] Execute: convert -density 300 -scale 500x5000> -alpha remove -strip -auto-orient /tmp/paperless/paperless-465_b0hd/archive.pdf[0] /tmp/paperless/paperless-465_b0hd/convert.png

[2022-04-18 13:43:11,951] [DEBUG] [paperless.parsing.tesseract] Execute: optipng -silent -o5 /tmp/paperless/paperless-465_b0hd/convert.png -out /tmp/paperless/paperless-465_b0hd/thumb_optipng.png

[2022-04-18 13:43:18,098] [DEBUG] [paperless.classifier] Document classification model does not exist (yet), not performing automatic matching.

[2022-04-18 13:43:18,108] [DEBUG] [paperless.consumer] Saving record to database

[2022-04-18 13:43:18,223] [DEBUG] [paperless.consumer] Deleting file /tmp/paperless/paperless-upload-7cf7n6k4

[2022-04-18 13:43:18,232] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-465_b0hd

[2022-04-18 13:43:18,235] [INFO] [paperless.consumer] Document 2020-04-19 00e19d23-0666-483f-afea-e55db2cb5aa8 consumption finished

Application log for UNSUCCESSFUL upload:

[2022-04-18 13:43:50,078] [INFO] [paperless.consumer] Consuming 00c59265-9fe1-41f9-be27-a80115315638

[2022-04-18 13:43:50,083] [DEBUG] [paperless.consumer] Detected mime type: application/pdf

[2022-04-18 13:43:50,094] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser

[2022-04-18 13:43:50,102] [DEBUG] [paperless.consumer] Parsing 00c59265-9fe1-41f9-be27-a80115315638...

[2022-04-18 13:43:50,424] [DEBUG] [paperless.parsing.tesseract] Extracted text from PDF file /tmp/paperless/paperless-upload-h_nvst_m

[2022-04-18 13:43:50,627] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': '/tmp/paperless/paperless-upload-h_nvst_m', 'output_file': '/tmp/paperless/paperless-8t4umyf4/archive.pdf', 'use_threads': True, 'jobs': 2, 'language': 'eng', 'output_type': 'pdfa', 'progress_bar': False, 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': '/tmp/paperless/paperless-8t4umyf4/sidecar.txt'}

[2022-04-18 13:44:48,140] [DEBUG] [paperless.parsing.tesseract] Using text from sidecar file

[2022-04-18 13:44:48,144] [DEBUG] [paperless.consumer] Generating thumbnail for 00c59265-9fe1-41f9-be27-a80115315638...

[2022-04-18 13:44:48,150] [DEBUG] [paperless.parsing] Execute: convert -density 300 -scale 500x5000> -alpha remove -strip -auto-orient /tmp/paperless/paperless-8t4umyf4/archive.pdf[0] /tmp/paperless/paperless-8t4umyf4/convert.png

[2022-04-18 13:44:50,387] [DEBUG] [paperless.parsing.tesseract] Execute: optipng -silent -o5 /tmp/paperless/paperless-8t4umyf4/convert.png -out /tmp/paperless/paperless-8t4umyf4/thumb_optipng.png

[2022-04-18 13:44:58,372] [DEBUG] [paperless.classifier] Document classification model does not exist (yet), not performing automatic matching.

[2022-04-18 13:44:58,378] [DEBUG] [paperless.consumer] Saving record to database

[2022-04-18 13:44:58,448] [ERROR] [paperless.index] [Errno 19] No such device

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/index.py", line 60, in open_index_writer

    yield writer

  File "/usr/src/paperless/src/documents/index.py", line 111, in add_or_update_document

    update_document(writer, document)

  File "/usr/src/paperless/src/documents/index.py", line 81, in update_document

    writer.update_document(

  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 1024, in update_document

    self._record("update_document", args, kwargs)

  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 1001, in _record

    getattr(self.writer, method)(*args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 483, in update_document

    with self.searcher() as s:

  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 297, in searcher

    return Searcher(self.reader(), **kwargs)

  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 638, in reader

    return FileIndex._reader(self.storage, self.schema, self.segments,

  File "/usr/local/lib/python3.9/site-packages/whoosh/index.py", line 529, in _reader

    return segreader(segments[0])

  File "/usr/local/lib/python3.9/site-packages/whoosh/index.py", line 523, in segreader

    return SegmentReader(storage, schema, segment,

  File "/usr/local/lib/python3.9/site-packages/whoosh/reading.py", line 610, in __init__

    files = segment.open_compound_file(storage)

  File "/usr/local/lib/python3.9/site-packages/whoosh/codec/base.py", line 570, in open_compound_file

    return CompoundStorage(dbfile, use_mmap=storage.supports_mmap)

  File "/usr/local/lib/python3.9/site-packages/whoosh/filedb/compound.py", line 75, in __init__

    self._source = mmap.mmap(fileno, 0, access=mmap.ACCESS_READ)

OSError: [Errno 19] No such device

[2022-04-18 13:44:58,459] [ERROR] [paperless.consumer] The following error occured while consuming 00c59265-9fe1-41f9-be27-a80115315638: This writer is closed

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/index.py", line 60, in open_index_writer

    yield writer

  File "/usr/src/paperless/src/documents/index.py", line 111, in add_or_update_document

    update_document(writer, document)

  File "/usr/src/paperless/src/documents/index.py", line 81, in update_document

    writer.update_document(

  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 1024, in update_document

    self._record("update_document", args, kwargs)

  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 1001, in _record

    getattr(self.writer, method)(*args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 483, in update_document

    with self.searcher() as s:

  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 297, in searcher

    return Searcher(self.reader(), **kwargs)

  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 638, in reader

    return FileIndex._reader(self.storage, self.schema, self.segments,

  File "/usr/local/lib/python3.9/site-packages/whoosh/index.py", line 529, in _reader

    return segreader(segments[0])

  File "/usr/local/lib/python3.9/site-packages/whoosh/index.py", line 523, in segreader

    return SegmentReader(storage, schema, segment,

  File "/usr/local/lib/python3.9/site-packages/whoosh/reading.py", line 610, in __init__

    files = segment.open_compound_file(storage)

  File "/usr/local/lib/python3.9/site-packages/whoosh/codec/base.py", line 570, in open_compound_file

    return CompoundStorage(dbfile, use_mmap=storage.supports_mmap)

  File "/usr/local/lib/python3.9/site-packages/whoosh/filedb/compound.py", line 75, in __init__

    self._source = mmap.mmap(fileno, 0, access=mmap.ACCESS_READ)

OSError: [Errno 19] No such device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/consumer.py", line 288, in try_consume_file

    document_consumption_finished.send(

  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 180, in send

    return [

  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>

    (receiver, receiver(signal=self, sender=sender, **named))

  File "/usr/src/paperless/src/documents/signals/handlers.py", line 425, in add_to_index

    index.add_or_update_document(document)

  File "/usr/src/paperless/src/documents/index.py", line 111, in add_or_update_document

    update_document(writer, document)

  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__

    self.gen.throw(typ, value, traceback)

  File "/usr/src/paperless/src/documents/index.py", line 65, in open_index_writer

    writer.commit(optimize=optimize)

  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 1037, in commit

    self.writer.commit(*args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 920, in commit

    self._check_state()

  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 555, in _check_state

    raise IndexingError("This writer is closed")

whoosh.writing.IndexingError: This writer is closed
```

### Paperless-ngx version

1.6.0

### Host OS

Ubuntu 20.04.4

### Installation method

Docker

### Browser

Chrome

### Configuration changes

installation script to specify path to docker-compose.yml and env files

**Comment by philuk1971** [comment]
Additional info, exactly the same behaviour is seen using sqlite as db:

**docker-compose file:**
```
version: "3.4"
services:
  broker:
    image: redis:6.0
    restart: unless-stopped
    volumes:
      - redisdata:/data

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - broker
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /mnt/storage/filing/data:/usr/src/paperless/data
      - /mnt/storage/filing/media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - /mnt/storage/filing/scanned_files:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379


volumes:
  data:
  media:
  redisdata:
```
**Log file showing successful and unsuccessful attempts to add documents:**

```
[2022-04-18 22:28:16,323] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: /usr/src/paperless/src/../consume

[2022-04-18 22:28:46,720] [INFO] [paperless.sanity_checker] Sanity checker detected no issues.

[2022-04-18 22:28:49,863] [INFO] [paperless.consumer] Consuming 00c59265-9fe1-41f9-be27-a80115315638

[2022-04-18 22:28:49,867] [DEBUG] [paperless.consumer] Detected mime type: application/pdf

[2022-04-18 22:28:49,882] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser

[2022-04-18 22:28:49,890] [DEBUG] [paperless.consumer] Parsing 00c59265-9fe1-41f9-be27-a80115315638...

[2022-04-18 22:28:50,072] [DEBUG] [paperless.parsing.tesseract] Extracted text from PDF file /tmp/paperless/paperless-upload-o_9yvyfu

[2022-04-18 22:28:50,355] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': '/tmp/paperless/paperless-upload-o_9yvyfu', 'output_file': '/tmp/paperless/paperless-pqwws94k/archive.pdf', 'use_threads': True, 'jobs': 2, 'language': 'eng', 'output_type': 'pdfa', 'progress_bar': False, 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': '/tmp/paperless/paperless-pqwws94k/sidecar.txt'}

[2022-04-18 22:29:46,739] [DEBUG] [paperless.parsing.tesseract] Using text from sidecar file

[2022-04-18 22:29:46,742] [DEBUG] [paperless.consumer] Generating thumbnail for 00c59265-9fe1-41f9-be27-a80115315638...

[2022-04-18 22:29:46,752] [DEBUG] [paperless.parsing] Execute: convert -density 300 -scale 500x5000> -alpha remove -strip -auto-orient /tmp/paperless/paperless-pqwws94k/archive.pdf[0] /tmp/paperless/paperless-pqwws94k/convert.png

[2022-04-18 22:29:48,985] [DEBUG] [paperless.parsing.tesseract] Execute: optipng -silent -o5 /tmp/paperless/paperless-pqwws94k/convert.png -out /tmp/paperless/paperless-pqwws94k/thumb_optipng.png

[2022-04-18 22:29:56,909] [DEBUG] [paperless.classifier] Document classification model does not exist (yet), not performing automatic matching.

[2022-04-18 22:29:56,915] [DEBUG] [paperless.consumer] Saving record to database

[2022-04-18 22:29:57,038] [DEBUG] [paperless.consumer] Deleting file /tmp/paperless/paperless-upload-o_9yvyfu

[2022-04-18 22:29:57,184] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-pqwws94k

[2022-04-18 22:29:57,188] [INFO] [paperless.consumer] Document 2019-09-10 00c59265-9fe1-41f9-be27-a80115315638 consumption finished

[2022-04-18 22:30:07,133] [INFO] [paperless.consumer] Consuming 00e19d23-0666-483f-afea-e55db2cb5aa8

[2022-04-18 22:30:07,137] [DEBUG] [paperless.consumer] Detected mime type: application/pdf

[2022-04-18 22:30:07,148] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser

[2022-04-18 22:30:07,155] [DEBUG] [paperless.consumer] Parsing 00e19d23-0666-483f-afea-e55db2cb5aa8...

[2022-04-18 22:30:07,246] [DEBUG] [paperless.parsing.tesseract] Extracted text from PDF file /tmp/paperless/paperless-upload-1n3p0tae

[2022-04-18 22:30:07,373] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': '/tmp/paperless/paperless-upload-1n3p0tae', 'output_file': '/tmp/paperless/paperless-v89tp8p3/archive.pdf', 'use_threads': True, 'jobs': 2, 'language': 'eng', 'output_type': 'pdfa', 'progress_bar': False, 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': '/tmp/paperless/paperless-v89tp8p3/sidecar.txt'}

[2022-04-18 22:30:35,265] [DEBUG] [paperless.parsing.tesseract] Using text from sidecar file

[2022-04-18 22:30:35,267] [DEBUG] [paperless.consumer] Generating thumbnail for 00e19d23-0666-483f-afea-e55db2cb5aa8...

[2022-04-18 22:30:35,274] [DEBUG] [paperless.parsing] Execute: convert -density 300 -scale 500x5000> -alpha remove -strip -auto-orient /tmp/paperless/paperless-v89tp8p3/archive.pdf[0] /tmp/paperless/paperless-v89tp8p3/convert.png

[2022-04-18 22:30:36,828] [DEBUG] [paperless.parsing.tesseract] Execute: optipng -silent -o5 /tmp/paperless/paperless-v89tp8p3/convert.png -out /tmp/paperless/paperless-v89tp8p3/thumb_optipng.png

[2022-04-18 22:30:43,229] [DEBUG] [paperless.classifier] Document classification model does not exist (yet), not performing automatic matching.

[2022-04-18 22:30:43,237] [DEBUG] [paperless.consumer] Saving record to database

[2022-04-18 22:30:43,290] [ERROR] [paperless.index] [Errno 19] No such device

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/index.py", line 60, in open_index_writer

    yield writer

  File "/usr/src/paperless/src/documents/index.py", line 111, in add_or_update_document

    update_document(writer, document)

  File "/usr/src/paperless/src/documents/index.py", line 81, in update_document

    writer.update_document(

  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 1024, in update_document

    self._record("update_document", args, kwargs)

  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 1001, in _record

    getattr(self.writer, method)(*args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 483, in update_document

    with self.searcher() as s:

  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 297, in searcher

    return Searcher(self.reader(), **kwargs)

  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 638, in reader

    return FileIndex._reader(self.storage, self.schema, self.segments,

  File "/usr/local/lib/python3.9/site-packages/whoosh/index.py", line 529, in _reader

    return segreader(segments[0])

  File "/usr/local/lib/python3.9/site-packages/whoosh/index.py", line 523, in segreader

    return SegmentReader(storage, schema, segment,

  File "/usr/local/lib/python3.9/site-packages/whoosh/reading.py", line 610, in __init__

    files = segment.open_compound_file(storage)

  File "/usr/local/lib/python3.9/site-packages/whoosh/codec/base.py", line 570, in open_compound_file

    return CompoundStorage(dbfile, use_mmap=storage.supports_mmap)

  File "/usr/local/lib/python3.9/site-packages/whoosh/filedb/compound.py", line 75, in __init__

    self._source = mmap.mmap(fileno, 0, access=mmap.ACCESS_READ)

OSError: [Errno 19] No such device

[2022-04-18 22:30:43,300] [ERROR] [paperless.consumer] The following error occured while consuming 00e19d23-0666-483f-afea-e55db2cb5aa8: This writer is closed

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/index.py", line 60, in open_index_writer

    yield writer

  File "/usr/src/paperless/src/documents/index.py", line 111, in add_or_update_document

    update_document(writer, document)

  File "/usr/src/paperless/src/documents/index.py", line 81, in update_document

    writer.update_document(

  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 1024, in update_document

    self._record("update_document", args, kwargs)

  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 1001, in _record

    getattr(self.writer, method)(*args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 483, in update_document

    with self.searcher() as s:

  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 297, in searcher

    return Searcher(self.reader(), **kwargs)

  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 638, in reader

    return FileIndex._reader(self.storage, self.schema, self.segments,

  File "/usr/local/lib/python3.9/site-packages/whoosh/index.py", line 529, in _reader

    return segreader(segments[0])

  File "/usr/local/lib/python3.9/site-packages/whoosh/index.py", line 523, in segreader

    return SegmentReader(storage, schema, segment,

  File "/usr/local/lib/python3.9/site-packages/whoosh/reading.py", line 610, in __init__

    files = segment.open_compound_file(storage)

  File "/usr/local/lib/python3.9/site-packages/whoosh/codec/base.py", line 570, in open_compound_file

    return CompoundStorage(dbfile, use_mmap=storage.supports_mmap)

  File "/usr/local/lib/python3.9/site-packages/whoosh/filedb/compound.py", line 75, in __init__

    self._source = mmap.mmap(fileno, 0, access=mmap.ACCESS_READ)

OSError: [Errno 19] No such device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/consumer.py", line 288, in try_consume_file

    document_consumption_finished.send(

  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 180, in send

    return [

  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>

    (receiver, receiver(signal=self, sender=sender, **named))

  File "/usr/src/paperless/src/documents/signals/handlers.py", line 425, in add_to_index

    index.add_or_update_document(document)

  File "/usr/src/paperless/src/documents/index.py", line 111, in add_or_update_document

    update_document(writer, document)

  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__

    self.gen.throw(typ, value, traceback)

  File "/usr/src/paperless/src/documents/index.py", line 65, in open_index_writer

    writer.commit(optimize=optimize)

  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 1037, in commit

    self.writer.commit(*args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 920, in commit

    self._check_state()

  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 555, in _check_state

    raise IndexingError("This writer is closed")

whoosh.writing.IndexingError: This writer is closed

[2022-04-18 22:30:43,302] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-v89tp8p3
```

**Comment by shamoon** [comment]
What type of device are you volume mounts? Eg local HD, external etc?

**Comment by philuk1971** [comment]
/mnt/storage/filing/* volumes are on a MergerFS drive comprising ext4 formatted HDDs

(./export is on a SSD)

**Comment by shamoon** [comment]
I dont really know about MergerFS but have you tried (if you are able) on a different volume type / format?

Since of course this app works for most people there must be something specific here.

**Comment by stumpylog** [comment]
Does MergerFS support `mmap`?  This is the exact error code we have in the trouble shooting section [here](https://paperless-ngx.readthedocs.io/en/latest/troubleshooting.html#oserror-errno-19-no-such-device-when-consuming-files)

**Comment by philuk1971** [comment]
Yeah, that was it. As a test, I've moved the /data directory to the SSD outside of the MergerFS pool and everything works as expected. I'll look at the MergerFS config to get mmap later.

Thanks for your help all.
