### ISSUE TITLE
[BUG] Error message after uploading any PDF-File "import nltk"

### ISSUE THREAD

**Issue by DerP4si** [paperless-ngx/paperless-ngx#7530]
### Description

I get this Error-Message if i try to upload any pdf...

![image](https://github.com/user-attachments/assets/0a183248-36b0-4ec1-9270-bd1f25b95b6e)
```
Rezept Korsett T-Shirts.pdf
Rezept Korsett T-Shirts.pdf: The following error occurred while storing document Rezept Korsett T-Shirts.pdf after parsing: ********************************************************************** Resource [93mpunkt_tab[0m not found. Please use the NLTK Downloader to obtain the resource: [31m>>> import nltk >>> nltk.download('punkt_tab') [0m For more information see: https://www.nltk.org/data.html Attempted to load [93mtokenizers/punkt_tab/german/[0m Searched in: - PosixPath('/usr/share/nltk_data') **********************************************************************
```

### Steps to reproduce

1. Upload a pdf
2. Get the Error-Message

### Webserver logs

```bash
[2024-08-23 14:51:25,777] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-7gcphg7i

[2024-08-23 14:51:25,778] [ERROR] [paperless.tasks] ConsumeTaskPlugin failed: Rezept Korsett T-Shirts.pdf: The following error occurred while storing document Rezept Korsett T-Shirts.pdf after parsing:

**********************************************************************

  Resource [93mpunkt_tab[0m not found.

  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk

  >>> nltk.download('punkt_tab')

  [0m

  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt_tab/german/[0m

  Searched in:

    - PosixPath('/usr/share/nltk_data')

**********************************************************************

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 327, in main_wrap

    raise exc_info[1]

  File "/usr/src/paperless/src/documents/consumer.py", line 670, in run

    document_consumption_finished.send(

  File "/usr/local/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 176, in send

    return [

           ^

  File "/usr/local/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>

    (receiver, receiver(signal=self, sender=sender, **named))

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/paperless/src/documents/signals/handlers.py", line 150, in set_document_type

    potential_document_type = matching.match_document_types(document, classifier)

                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/paperless/src/documents/matching.py", line 61, in match_document_types

    pred_id = classifier.predict_document_type(document.content) if classifier else None

              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/paperless/src/documents/classifier.py", line 424, in predict_document_type

    X = self.data_vectorizer.transform([self.preprocess_content(content)])

                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/paperless/src/documents/classifier.py", line 386, in preprocess_content

    words: list[str] = word_tokenize(

                       ^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/nltk/tokenize/__init__.py", line 142, in word_tokenize

    sentences = [text] if preserve_line else sent_tokenize(text, language)

                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/nltk/tokenize/__init__.py", line 119, in sent_tokenize

    tokenizer = _get_punkt_tokenizer(language)

                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/nltk/tokenize/__init__.py", line 105, in _get_punkt_tokenizer

    return PunktTokenizer(language)

           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/nltk/tokenize/punkt.py", line 1744, in __init__

    self.load_lang(lang)

  File "/usr/local/lib/python3.11/site-packages/nltk/tokenize/punkt.py", line 1749, in load_lang

    lang_dir = find(f"tokenizers/punkt_tab/{lang}/")

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/nltk/data.py", line 579, in find

    raise LookupError(resource_not_found)

LookupError:

**********************************************************************

  Resource [93mpunkt_tab[0m not found.

  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk

  >>> nltk.download('punkt_tab')

  [0m

  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt_tab/german/[0m

  Searched in:

    - PosixPath('/usr/share/nltk_data')

**********************************************************************

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/tasks.py", line 149, in consume_file

    msg = plugin.run()

          ^^^^^^^^^^^^

  File "/usr/src/paperless/src/documents/consumer.py", line 733, in run

    self._fail(

  File "/usr/src/paperless/src/documents/consumer.py", line 304, in _fail

    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception

documents.consumer.ConsumerError: Rezept Korsett T-Shirts.pdf: The following error occurred while storing document Rezept Korsett T-Shirts.pdf after parsing:

**********************************************************************

  Resource [93mpunkt_tab[0m not found.

  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk

  >>> nltk.download('punkt_tab')

  [0m

  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt_tab/german/[0m

  Searched in:

    - PosixPath('/usr/share/nltk_data')

**********************************************************************
```
```


### Browser logs

_No response_

### Paperless-ngx version

2.11.5

### Host OS

Linux-4.4.302+-x86_64-with-glibc2.36

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.11.5",
    "server_os": "Linux-4.4.302+-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 15352618299392,
        "available": 4169358458880
    },
    "database": {
        "type": "mysql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "documents.1052_document_transaction_id",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://broker:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-08-23T00:00:12.820137+02:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-08-23T13:05:01.097417Z",
        "classifier_error": null
    }
}
```

### Browser

Chrome

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
This is resolved by .6

**Comment by DerP4si** [comment]
Sorry, Thx!

**Comment by ChrisMagnuson** [comment]
We are on 2.11.6 and are no longer able to upload files due to this. 

It gets to the point of scanning the file for the date and then errors with
```
Redacted.pdf: The following error occurred while storing document Redacted.pdf after parsing: ********************************************************************** Resource [93mpunkt_tab[0m not found. Please use the NLTK Downloader to obtain the resource: [31m>>> import nltk >>> nltk.download('punkt_tab') [0m For more information see: https://www.nltk.org/data.html Attempted to load [93mtokenizers/punkt_tab/english/[0m Searched in: - PosixPath('/usr/share/nltk_data') ********************************************************************** 
```

**Comment by stumpylog** [comment]
You must not be actually updated.  I processed several files this morning with .6 without issue.

**Comment by ChrisMagnuson** [comment]
![image](https://github.com/user-attachments/assets/89f28d6a-3787-4ffc-922b-1b8d4855475e)

**Comment by ChrisMagnuson** [comment]
Get same error when dragging an dropping files as well as with files coming from the consume folder.

**Comment by stumpylog** [comment]
How have you installed?

**Comment by ChrisMagnuson** [comment]
I use Cloudron, here is [the repo for the packaged app](https://git.cloudron.io/cloudron/paperless-ngx-app), and [here is the specific docker file](https://git.cloudron.io/cloudron/paperless-ngx-app/-/blob/master/Dockerfile?ref_type=heads#L15) that shows the version number of `2.11.6`

**Comment by ChrisMagnuson** [comment]
I have opened this [support request](https://forum.cloudron.io/topic/12352/paperless-ngx-errors-when-uploading-documents) with cloudron.

Is there anywhere that I can point them to that outlines what they need to do to fix their Dockerfile as required?

**Comment by ChrisMagnuson** [comment]
@stumpylog Thank you, will work with them to get this fixed

**Comment by MaxKuh** [comment]
I didn't want to open a new issue, but I have the same problems after the update to 2.11.6:

```
Entgeltabrechnung_2024_07.pdf: The following error occurred while storing document Entgeltabrechnung_2024_07.pdf after parsing: 
**********************************************************************
  Resource [93mpunkt_tab[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('punkt_tab')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt_tab/german/[0m

  Searched in:
    - PosixPath('/usr/share/nltk_data')
*********************************************************************
``` 
Installed new version via Tteck Proxmox (GitHub pull): `https://github.com/tteck/Proxmox/blob/main/ct/paperless-ngx.sh`

More info from the Webserver protocol: 
```
[2024-08-23 23:02:06,979] [ERROR] [paperless.tasks] ConsumeTaskPlugin failed: Entgeltabrechnung_2024_07.pdf: The following error occurred while storing document Entgeltabrechnung_2024_07.pdf after parsing:

**********************************************************************

  Resource [93mpunkt_tab[0m not found.

  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk

  >>> nltk.download('punkt_tab')

  [0m

  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt_tab/german/[0m

  Searched in:

    - PosixPath('/usr/share/nltk_data')

**********************************************************************

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/dist-packages/asgiref/sync.py", line 327, in main_wrap

    raise exc_info[1]

  File "/opt/paperless/src/documents/consumer.py", line 670, in run

    document_consumption_finished.send(

  File "/usr/local/lib/python3.11/dist-packages/django/dispatch/dispatcher.py", line 176, in send

    return [

           ^

  File "/usr/local/lib/python3.11/dist-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>

    (receiver, receiver(signal=self, sender=sender, **named))

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/paperless/src/documents/signals/handlers.py", line 95, in set_correspondent

    potential_correspondents = matching.match_correspondents(document, classifier)

                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/paperless/src/documents/matching.py", line 37, in match_correspondents

    pred_id = classifier.predict_correspondent(document.content) if classifier else None

              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/paperless/src/documents/classifier.py", line 413, in predict_correspondent

    X = self.data_vectorizer.transform([self.preprocess_content(content)])

                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/paperless/src/documents/classifier.py", line 386, in preprocess_content

    words: list[str] = word_tokenize(

                       ^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/dist-packages/nltk/tokenize/__init__.py", line 142, in word_tokenize

    sentences = [text] if preserve_line else sent_tokenize(text, language)

                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/dist-packages/nltk/tokenize/__init__.py", line 119, in sent_tokenize

    tokenizer = _get_punkt_tokenizer(language)

                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/dist-packages/nltk/tokenize/__init__.py", line 105, in _get_punkt_tokenizer

    return PunktTokenizer(language)

           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/dist-packages/nltk/tokenize/punkt.py", line 1744, in __init__

    self.load_lang(lang)

  File "/usr/local/lib/python3.11/dist-packages/nltk/tokenize/punkt.py", line 1749, in load_lang

    lang_dir = find(f"tokenizers/punkt_tab/{lang}/")

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/dist-packages/nltk/data.py", line 579, in find

    raise LookupError(resource_not_found)

LookupError:

**********************************************************************

  Resource [93mpunkt_tab[0m not found.

  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk

  >>> nltk.download('punkt_tab')

  [0m

  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt_tab/german/[0m

  Searched in:

    - PosixPath('/usr/share/nltk_data')

**********************************************************************

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/opt/paperless/src/documents/tasks.py", line 149, in consume_file

    msg = plugin.run()

          ^^^^^^^^^^^^

  File "/opt/paperless/src/documents/consumer.py", line 733, in run

    self._fail(

  File "/opt/paperless/src/documents/consumer.py", line 304, in _fail

    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception

documents.consumer.ConsumerError: Entgeltabrechnung_2024_07.pdf: The following error occurred while storing document Entgeltabrechnung_2024_07.pdf after parsing:

**********************************************************************

  Resource [93mpunkt_tab[0m not found.

  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk

  >>> nltk.download('punkt_tab')

  [0m

  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt_tab/german/[0m

  Searched in:

    - PosixPath('/usr/share/nltk_data')

**********************************************************************
``` 

No files can be processed with 2.11.6 for me. Before the update everything worked.

**Comment by mightyjens** [comment]
In the mean time you could get it up and running again by installing the module manually like Shamoon pointed out in the Docker-Fix:
python3 -W ignore::RuntimeWarning -m nltk.downloader -d "/usr/share/nltk_data" punkt_tab

**Comment by MaxKuh** [comment]
Awesome, didn't see that. Thanks. 
Now it is working again. :)

**Comment by nebulade** [comment]
> As expected, they have not fixed their Dockerfile as required. I suggest contacting them about it.

Thanks for the hint, we have fixed the Cloudron package accordingly.
