### ISSUE TITLE
[BUG] Merging PDF + PNG omits PNG

### ISSUE THREAD

**Issue by ginkel** [paperless-ngx/paperless-ngx#7554]
### Description

When attempting to merge a PDF-based document with another document that resulted from a PNG upload the merge process finishes without reporting any obvious error, but the resulting "merged" PDF is missing the page from the PNG-based document. No error is visible from the web frontend.

Working around the issue by downloading and re-uploading the PDF generated for the PNG (and using that for the merge) unfortunately does not work as it is rejected as a duplicate.

### Steps to reproduce

1. Upload PDF
2. Upload PNG
3. Select both documents for merging (generate new metadata, do not delete original files).

### Webserver logs

```bash
[2024-08-27 10:44:43,663] [INFO] [paperless.bulk_edit] Attempting to merge 2 documents into a single document.
[2024-08-27 10:44:43,820] [ERROR] [paperless.bulk_edit] Error merging document 592, it will not be included in the merge: /usr/src/paperless/media/documents/originals/0000592.png: unable to find trailer dictionary while recovering damaged file
Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/bulk_edit.py", line 262, in merge
    with pikepdf.open(str(doc.source_path)) as pdf:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pikepdf/_methods.py", line 398, in open
    pdf = Pdf._open(
          ^^^^^^^^^^
pikepdf._core.PdfError: /usr/src/paperless/media/documents/originals/0000592.png: unable to find trailer dictionary while recovering damaged file
[2024-08-27 10:44:43,822] [INFO] [paperless.bulk_edit] Adding merged document to the task queue.
[2024-08-27 10:44:43,857] [INFO] [celery.worker.strategy] Task documents.tasks.consume_file[fa0ac878-d0ad-472f-9f8b-b1a6f934d58a] received
[2024-08-27 10:44:43,905] [INFO] [paperless.tasks] WorkflowTriggerPlugin completed with: 
[2024-08-27 10:44:43,913] [INFO] [paperless.consumer] Consuming 618_592_merged.pdf
[2024-08-27 10:44:43,931] [INFO] [paperless.parsing.tesseract] pdftotext exited 0
[2024-08-27 10:44:45,693] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 5.52 - no change
[2024-08-27 10:44:55,983] [INFO] [ocrmypdf._pipelines.ocr] Postprocessing...
[2024-08-27 10:44:56,807] [INFO] [ocrmypdf._pipeline] Image optimization ratio: 1.22 savings: 18.3%
[2024-08-27 10:44:56,808] [INFO] [ocrmypdf._pipeline] Total file size ratio: 1.24 savings: 19.6%
[2024-08-27 10:44:56,810] [INFO] [ocrmypdf._pipelines._common] Output file is a PDF/A-2B (as expected)
[2024-08-27 10:44:58,394] [INFO] [paperless.parsing] convert exited 0
[2024-08-27 10:45:01,713] [INFO] [paperless.handlers] Assigning correspondent Thilo-Alexander Ginkel to 2024-08-26 618_592_merged
[2024-08-27 10:45:01,722] [INFO] [paperless.handlers] Assigning document type Abrechnung to 2024-08-26 Thilo-Alexander Ginkel 618_592_merged
[2024-08-27 10:45:01,732] [INFO] [paperless.handlers] Tagging "2024-08-26 Thilo-Alexander Ginkel 618_592_merged" with "Veranstaltung, Abrechnung"
[2024-08-27 10:45:01,799] [INFO] [paperless.consumer] Document 2024-08-26 Thilo-Alexander Ginkel 618_592_merged consumption finished
[2024-08-27 10:45:01,803] [INFO] [paperless.tasks] ConsumeTaskPlugin completed with: Success. New document id 619 created
```

### Paperless-ngx version

2.11.6

### Host OS

Ubuntu 22.04

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.11.6",
    "server_os": "Linux-5.15.0-117-generic-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 473533612032,
        "available": 359678787584
    },
    "database": {
        "type": "postgresql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "documents.1052_document_transaction_id",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://broker:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-08-27T10:47:27.021629+02:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-08-27T08:05:00.617726Z",
        "classifier_error": null
    }
}
```

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
Merging is only possible for PDF documents. 99% sure that is stated in the merge dialogue as well

**Comment by stumpylog** [comment]
https://docs.paperless-ngx.com/usage/#pdf-actions
