### ISSUE TITLE
[BUG] Can't consume documents

### ISSUE THREAD

**Issue by Frevven** [paperless-ngx/paperless-ngx#7579]
### Description

I updated to 2.11.6 yesterday. Now I am not able to consume documents anymore.

### Steps to reproduce

Uploaded a pdf-document via paperless web interface.

### Webserver logs

```bash
[2024-08-30 11:04:44,699] [ERROR] [paperless.consumer] The following error occurred while storing document 2024-08-30_11_24_18_001.pdf after parsing:

**********************************************************************

  Resource [93mpunkt_tab[0m not found.

  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk

  >>> nltk.download('punkt_tab')

  [0m

  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt_tab/english/[0m

  Searched in:

    - PosixPath('/usr/share/nltk_data')

**********************************************************************

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/dist-packages/asgiref/sync.py", line 327, in main_wrap

    raise exc_info[1]

  File "/opt/paperless/src/documents/consumer.py", line 670, in run

    document_consumption_finished.send(

  File "/usr/local/lib/python3.11/dist-packages/django/dispatch/dispatcher.py", line 176, in send

    return [

           ^

  File "/usr/local/lib/python3.11/dist-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>

    (receiver, receiver(signal=self, sender=sender, **named))

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/paperless/src/documents/signals/handlers.py", line 95, in set_correspondent

    potential_correspondents = matching.match_correspondents(document, classifier)

                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/paperless/src/documents/matching.py", line 37, in match_correspondents

    pred_id = classifier.predict_correspondent(document.content) if classifier else None

              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/paperless/src/documents/classifier.py", line 413, in predict_correspondent

    X = self.data_vectorizer.transform([self.preprocess_content(content)])

                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/paperless/src/documents/classifier.py", line 386, in preprocess_content

    words: list[str] = word_tokenize(

                       ^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/dist-packages/nltk/tokenize/__init__.py", line 142, in word_tokenize

    sentences = [text] if preserve_line else sent_tokenize(text, language)

                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/dist-packages/nltk/tokenize/__init__.py", line 119, in sent_tokenize

    tokenizer = _get_punkt_tokenizer(language)

                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/dist-packages/nltk/tokenize/__init__.py", line 105, in _get_punkt_tokenizer

    return PunktTokenizer(language)

           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/dist-packages/nltk/tokenize/punkt.py", line 1744, in __init__

    self.load_lang(lang)

  File "/usr/local/lib/python3.11/dist-packages/nltk/tokenize/punkt.py", line 1749, in load_lang

    lang_dir = find(f"tokenizers/punkt_tab/{lang}/")

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/dist-packages/nltk/data.py", line 579, in find

    raise LookupError(resource_not_found)

LookupError:

**********************************************************************

  Resource [93mpunkt_tab[0m not found.

  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk

  >>> nltk.download('punkt_tab')

  [0m

  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt_tab/english/[0m

  Searched in:

    - PosixPath('/usr/share/nltk_data')

**********************************************************************

[2024-08-30 11:04:44,713] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-_wbt65nx

[2024-08-30 11:04:44,714] [ERROR] [paperless.tasks] ConsumeTaskPlugin failed: 2024-08-30_11_24_18_001.pdf: The following error occurred while storing document 2024-08-30_11_24_18_001.pdf after parsing:

**********************************************************************

  Resource [93mpunkt_tab[0m not found.

  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk

  >>> nltk.download('punkt_tab')

  [0m

  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt_tab/english/[0m

  Searched in:

    - PosixPath('/usr/share/nltk_data')

**********************************************************************

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/dist-packages/asgiref/sync.py", line 327, in main_wrap

    raise exc_info[1]

  File "/opt/paperless/src/documents/consumer.py", line 670, in run

    document_consumption_finished.send(

  File "/usr/local/lib/python3.11/dist-packages/django/dispatch/dispatcher.py", line 176, in send

    return [

           ^

  File "/usr/local/lib/python3.11/dist-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>

    (receiver, receiver(signal=self, sender=sender, **named))

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/paperless/src/documents/signals/handlers.py", line 95, in set_correspondent

    potential_correspondents = matching.match_correspondents(document, classifier)

                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/paperless/src/documents/matching.py", line 37, in match_correspondents

    pred_id = classifier.predict_correspondent(document.content) if classifier else None

              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/paperless/src/documents/classifier.py", line 413, in predict_correspondent

    X = self.data_vectorizer.transform([self.preprocess_content(content)])

                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/paperless/src/documents/classifier.py", line 386, in preprocess_content

    words: list[str] = word_tokenize(

                       ^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/dist-packages/nltk/tokenize/__init__.py", line 142, in word_tokenize

    sentences = [text] if preserve_line else sent_tokenize(text, language)

                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/dist-packages/nltk/tokenize/__init__.py", line 119, in sent_tokenize

    tokenizer = _get_punkt_tokenizer(language)

                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/dist-packages/nltk/tokenize/__init__.py", line 105, in _get_punkt_tokenizer

    return PunktTokenizer(language)

           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/dist-packages/nltk/tokenize/punkt.py", line 1744, in __init__

    self.load_lang(lang)

  File "/usr/local/lib/python3.11/dist-packages/nltk/tokenize/punkt.py", line 1749, in load_lang

    lang_dir = find(f"tokenizers/punkt_tab/{lang}/")

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/dist-packages/nltk/data.py", line 579, in find

    raise LookupError(resource_not_found)

LookupError:

**********************************************************************

  Resource [93mpunkt_tab[0m not found.

  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk

  >>> nltk.download('punkt_tab')

  [0m

  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt_tab/english/[0m

  Searched in:

    - PosixPath('/usr/share/nltk_data')

**********************************************************************

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/opt/paperless/src/documents/tasks.py", line 149, in consume_file

    msg = plugin.run()

          ^^^^^^^^^^^^

  File "/opt/paperless/src/documents/consumer.py", line 733, in run

    self._fail(

  File "/opt/paperless/src/documents/consumer.py", line 304, in _fail

    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception

documents.consumer.ConsumerError: 2024-08-30_11_24_18_001.pdf: The following error occurred while storing document 2024-08-30_11_24_18_001.pdf after parsing:

**********************************************************************

  Resource [93mpunkt_tab[0m not found.

  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk

  >>> nltk.download('punkt_tab')

  [0m

  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt_tab/english/[0m

  Searched in:

    - PosixPath('/usr/share/nltk_data')

**********************************************************************

[2024-08-30 11:05:00,219] [DEBUG] [paperless.classifier] Gathering data from database...

[2024-08-30 11:05:00,784] [DEBUG] [paperless.classifier] 359 documents, 5 tag(s), 26 correspondent(s), 14 document type(s). 1 storage path(es)

[2024-08-30 11:05:00,784] [DEBUG] [paperless.classifier] Vectorizing data...

[2024-08-30 11:05:00,974] [WARNING] [paperless.tasks] Classifier error:

**********************************************************************

  Resource [93mpunkt_tab[0m not found.

  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk

  >>> nltk.download('punkt_tab')

  [0m

  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt_tab/english/[0m

  Searched in:

    - PosixPath('/usr/share/nltk_data')

**********************************************************************
```

### Paperless-ngx version

2.11.6

### Host OS

LXC on Proxmox

### Installation method

Bare metal

### System status

```json
{
    "pngx_version": "2.11.6",
    "server_os": "Linux-6.8.12-1-pve-x86_64-with-glibc2.36",
    "install_type": "bare-metal",
    "storage": {
        "total": 21024600064,
        "available": 11839324160
    },
    "database": {
        "type": "postgresql",
        "url": "paperlessdb",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "documents.1052_document_transaction_id",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://localhost:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-08-30T00:00:04.948711Z",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-08-30T11:05:00.977478Z",
        "classifier_error": null
    }
}
```

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
A very quick search will find the answer.  There's several duplicates

**Comment by shamoon** [comment]
For future reference: #7519 --> #7522 --> https://github.com/paperless-ngx/paperless-ngx/releases/tag/v2.11.6

**Comment by ciphermenial** [comment]
The easiest way to install the required data is with the following.
`sudo python -m nltk.downloader -d /usr/share/nltk_data snowball_data stopwords punkt`
