### ISSUE TITLE
[BUG] rror occurred while consuming: UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 60-61: invalid continuation byte

### ISSUE THREAD

**Issue by tural-ali** [paperless-ngx/paperless-ngx#7612]
### Description

![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/18be4d6b-92f7-4998-b6b7-24610bd32286)
Adding documents in German and getting bunch of errors like the following. Scanning the documents using ScanSnap IX1500

Here is my docker config

```
version: '3.8'
services:
 broker:
    image: redis
    read_only: true
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
    container_name: Paperless-NGX-REDIS
    security_opt:
      - no-new-privileges:true
    environment:
      REDIS_ARGS: "--save 60 10"
    restart: on-failure:5
    volumes:
      - /volume1/docker/paperless/redis:/data


 gotenberg:
    image: docker.io/gotenberg/gotenberg:8.7
    restart: on-failure:5
    security_opt:
      - no-new-privileges:true
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

 tika:
    image: docker.io/apache/tika:latest
    restart: on-failure:5
    

 db:
    image: postgres:16

    container_name: Paperless-NGX-DB
    restart: on-failure:5
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "paperless", "-U", "paperless"]
      timeout: 45s
      interval: 10s
      retries: 10
    security_opt:
      - no-new-privileges:true
    volumes:
      - /volume1/docker/paperless/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

 webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: Paperless-NGX
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    security_opt:
      - no-new-privileges:true
    restart: on-failure:5
    depends_on:
      db:
        condition: service_healthy
      broker:
        condition: service_healthy
      tika:
        condition: service_started
      gotenberg:
        condition: service_started
    ports:
      - 8001:8000
    volumes:
      - /volume1/docker/paperless/data:/usr/src/paperless/data
      - /volume1/docker/paperless/media:/usr/src/paperless/media
      - /volume1/docker/paperless/export:/usr/src/paperless/export
      - /volume1/docker/paperless/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_OCR_SKIP_ARCHIVE_FILE: always
      PAPERLESS_OCR_PAGES: 1
      PAPERLESS_TIME_ZONE: Europe/Berlin
      PAPERLESS_ADMIN_USER: admin
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_FILENAME_FORMAT: "{correspondent}/{created_year}/{created} {title}"
      PAPERLESS_OCR_USER_ARGS: '{"invalidate_digital_signatures": true}'
      PAPERLESS_OCR_LANGUAGE: "aze+deu+eng+rus"
      PAPERLESS_OCR_LANGUAGES: "ces tur aze deu eng rus"
      PAPERLESS_DEBUG: false
```

### Steps to reproduce

1. Scan PDFs using ScanSnap ix1500
2. Upload to the paperless
3. Get the error

### Webserver logs

```bash
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 60: invalid continuation byte

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 327, in main_wrap

    raise exc_info[1]

  File "/usr/src/paperless/src/documents/consumer.py", line 598, in run

    document_parser.parse(self.working_copy, mime_type, self.filename)

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 435, in parse

    raise ParseError(f"{e.__class__.__name__}: {e!s}") from e

documents.parsers.ParseError: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 60: invalid continuation byte

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/tasks.py", line 149, in consume_file

    msg = plugin.run()

          ^^^^^^^^^^^^

  File "/usr/src/paperless/src/documents/consumer.py", line 629, in run

    self._fail(

  File "/usr/src/paperless/src/documents/consumer.py", line 304, in _fail

    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception

documents.consumer.ConsumerError: 03092024_005.pdf: Error occurred while consuming document 03092024_005.pdf: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 60: invalid continuation byte
```

### Paperless-ngx version

2.11.6

### Host OS

Synology DSM 7.2.2

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by maher-nakesh** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by shamoon** [comment]
From the issue template:

> Also, note that Paperless-ngx does not perform OCR or archive file creation itself, those are handled by other tools. Problems with OCR or archive versions of specific files should likely be raised 'upstream', see https://github.com/ocrmypdf/OCRmyPDF/issues or https://github.com/tesseract-ocr/tesseract/issues

So I'll move this to a discussion.

The message suggests there are bytes in the file which are not valid utf8. Presumably you will have to correct the file
