### ISSUE TITLE
[BUG] Paperless worker crashes on particular PDF files

### ISSUE THREAD

**Issue by Ralf264** [paperless-ngx/paperless-ngx#7681]
### Description

Hi, yesterday I performed the upgrade from 2.7.2 to 2.12.0 and run into an issue with particular PDF files (reports or invoices from the heating engineer).

When feeding paperless with PDF files in question, the worker thread after some time always crashes for some reason. These PDF files where generated by "combit® List® & Label Report Generator (28.0.0.0 (1.3.45.0))".

Reprinting the PDF file with "Microsoft Print to PDF" works.

Personally, I don't mind if Paperless can't handle all PDF files, but I don't think it should cause it to crash.

### Steps to reproduce

requires PDF file with some sensitive personal information

### Webserver logs

```bash
[2024-09-10 21:23:01,244] [ERROR] [paperless.consumer] Error occurred while consuming document Bericht_24-2957.pdf: SubprocessOutputError: . See logs for more information.
Traceback (most recent call last):
  File "/opt/paperless/envsp/lib/python3.11/site-packages/ocrmypdf/_exec/tesseract.py", line 385, in generate_pdf
    p = run(args_tesseract, stdout=PIPE, stderr=STDOUT, timeout=timeout, check=True)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/paperless/envsp/lib/python3.11/site-packages/ocrmypdf/subprocess/__init__.py", line 63, in run
    proc = subprocess_run(args, env=env, check=check, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['tesseract', '-l', 'deu', '-c', 'textonly_pdf=1', '/tmp/ocrmypdf.io.b6gsqcn8/000001_ocr.png', '/tmp/ocrmypdf.io.b6gsqcn8/000001_ocr_tess', 'pdf', 'txt']' died with <Signals.SIGKILL: 9>.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/paperless/src/paperless_tesseract/parsers.py", line 368, in parse
    ocrmypdf.ocr(**args)
  File "/opt/paperless/envsp/lib/python3.11/site-packages/ocrmypdf/api.py", line 375, in ocr
    return run_pipeline(options=options, plugin_manager=plugin_manager)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/paperless/envsp/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 225, in run_pipeline
    return _run_pipeline(options, plugin_manager)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/paperless/envsp/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 192, in _run_pipeline
    optimize_messages = exec_concurrent(context, executor)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/paperless/envsp/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 119, in exec_concurrent
    executor(
  File "/opt/paperless/envsp/lib/python3.11/site-packages/ocrmypdf/_concurrent.py", line 74, in __call__
    self._execute(
  File "/opt/paperless/envsp/lib/python3.11/site-packages/ocrmypdf/builtin_plugins/concurrency.py", line 141, in _execute
    result = future.result()
             ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/paperless/envsp/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 82, in _exec_page_sync
    ocr_out, text_out = _image_to_ocr_text(page_context, ocr_image_out)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/paperless/envsp/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 66, in _image_to_ocr_text
    ocr_out, text_out = ocr_engine_textonly_pdf(ocr_image_out, page_context)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/paperless/envsp/lib/python3.11/site-packages/ocrmypdf/_pipeline.py", line 766, in ocr_engine_textonly_pdf
    ocr_engine.generate_pdf(
  File "/opt/paperless/envsp/lib/python3.11/site-packages/ocrmypdf/builtin_plugins/tesseract_ocr.py", line 264, in generate_pdf
    tesseract.generate_pdf(
  File "/opt/paperless/envsp/lib/python3.11/site-packages/ocrmypdf/_exec/tesseract.py", line 397, in generate_pdf
    raise SubprocessOutputError() from e
ocrmypdf.exceptions.SubprocessOutputError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/paperless/envsp/lib/python3.11/site-packages/asgiref/sync.py", line 327, in main_wrap
    raise exc_info[1]
  File "/opt/paperless/src/documents/consumer.py", line 598, in run
    document_parser.parse(self.working_copy, mime_type, self.filename)
  File "/opt/paperless/src/paperless_tesseract/parsers.py", line 391, in parse
    raise ParseError(
documents.parsers.ParseError: SubprocessOutputError: . See logs for more information.
[2024-09-10 21:23:01,918] [ERROR] [paperless.tasks] ConsumeTaskPlugin failed: Bericht_24-2957.pdf: Error occurred while consuming document Bericht_24-2957.pdf: SubprocessOutputError: . See logs for more information.
Traceback (most recent call last):
  File "/opt/paperless/envsp/lib/python3.11/site-packages/ocrmypdf/_exec/tesseract.py", line 385, in generate_pdf
    p = run(args_tesseract, stdout=PIPE, stderr=STDOUT, timeout=timeout, check=True)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/paperless/envsp/lib/python3.11/site-packages/ocrmypdf/subprocess/__init__.py", line 63, in run
    proc = subprocess_run(args, env=env, check=check, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['tesseract', '-l', 'deu', '-c', 'textonly_pdf=1', '/tmp/ocrmypdf.io.b6gsqcn8/000001_ocr.png', '/tmp/ocrmypdf.io.b6gsqcn8/000001_ocr_tess', 'pdf', 'txt']' died with <Signals.SIGKILL: 9>.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/paperless/src/paperless_tesseract/parsers.py", line 368, in parse
    ocrmypdf.ocr(**args)
  File "/opt/paperless/envsp/lib/python3.11/site-packages/ocrmypdf/api.py", line 375, in ocr
    return run_pipeline(options=options, plugin_manager=plugin_manager)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/paperless/envsp/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 225, in run_pipeline
    return _run_pipeline(options, plugin_manager)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/paperless/envsp/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 192, in _run_pipeline
    optimize_messages = exec_concurrent(context, executor)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/paperless/envsp/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 119, in exec_concurrent
    executor(
  File "/opt/paperless/envsp/lib/python3.11/site-packages/ocrmypdf/_concurrent.py", line 74, in __call__
    self._execute(
  File "/opt/paperless/envsp/lib/python3.11/site-packages/ocrmypdf/builtin_plugins/concurrency.py", line 141, in _execute
    result = future.result()
             ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/paperless/envsp/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 82, in _exec_page_sync
    ocr_out, text_out = _image_to_ocr_text(page_context, ocr_image_out)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/paperless/envsp/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 66, in _image_to_ocr_text
    ocr_out, text_out = ocr_engine_textonly_pdf(ocr_image_out, page_context)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/paperless/envsp/lib/python3.11/site-packages/ocrmypdf/_pipeline.py", line 766, in ocr_engine_textonly_pdf
    ocr_engine.generate_pdf(
  File "/opt/paperless/envsp/lib/python3.11/site-packages/ocrmypdf/builtin_plugins/tesseract_ocr.py", line 264, in generate_pdf
    tesseract.generate_pdf(
  File "/opt/paperless/envsp/lib/python3.11/site-packages/ocrmypdf/_exec/tesseract.py", line 397, in generate_pdf
    raise SubprocessOutputError() from e
ocrmypdf.exceptions.SubprocessOutputError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/paperless/envsp/lib/python3.11/site-packages/asgiref/sync.py", line 327, in main_wrap
    raise exc_info[1]
  File "/opt/paperless/src/documents/consumer.py", line 598, in run
    document_parser.parse(self.working_copy, mime_type, self.filename)
  File "/opt/paperless/src/paperless_tesseract/parsers.py", line 391, in parse
    raise ParseError(
documents.parsers.ParseError: SubprocessOutputError: . See logs for more information.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/paperless/src/documents/tasks.py", line 149, in consume_file
    msg = plugin.run()
          ^^^^^^^^^^^^
  File "/opt/paperless/src/documents/consumer.py", line 629, in run
    self._fail(
  File "/opt/paperless/src/documents/consumer.py", line 304, in _fail
    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
documents.consumer.ConsumerError: Bericht_24-2957.pdf: Error occurred while consuming document Bericht_24-2957.pdf: SubprocessOutputError: . See logs for more information.
```

### Paperless-ngx version

2.12.0

### Host OS

Debian 12.7

### Installation method

Bare metal

### System status

```json
{
    "pngx_version": "2.12.0",
    "server_os": "Linux-6.1.0-25-amd64-x86_64-with-glibc2.36",
    "install_type": "bare-metal",
    "storage": {
        "total": 52995522560,
        "available": 50282119168
    },
    "database": {
        "type": "mysql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "paperless_mail.0011_remove_mailrule_assign_tag_squashed_0024_alter_mailrule_name_and_more",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://localhost:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-09-11T13:08:21.439689+02:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-09-11T11:08:31.293374Z",
        "classifier_error": null
    }
}
```

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
You checked a box saying this is not about the ocr or archive creation of a single file, but it is. I'm moving to a discussion
