### ISSUE TITLE
[BUG] Saved Views doesn't work

### ISSUE THREAD

**Issue by Christoph-Raab** [paperless-ngx/paperless-ngx#7706]
### Description

I gave my user the SavedView + the UISettings permissions. When I try to config my personal saved views, the page does not show any views at all.

![image](https://github.com/user-attachments/assets/7db60828-da3b-4628-aca4-1cafb7cef7aa)

I managed to see the fields after a reload (F5) on the page /settings/savedviews. Suddenly I see all fields but they were empty. This is reproducable, meaning it shows the same behavior after login. Trying to delete a view did nothing, I couldn't even see a request in the dev tools.

![image](https://github.com/user-attachments/assets/79171a57-445b-4ebd-bd19-39af09b1391d)

With the default admin user I can manage saved views. So I figured this might be a config problem. But there are some errors in logs and in the browser console also giving my user Superuser rights still doesn't fix the issue.

### Steps to reproduce

1 Give a non-default user SuperUser rights.
2 Create a saved view, like document_type == empty
3 Go to /settings/savedviews
4 See only an empty list

### Webserver logs

```bash
[2024-09-15 15:04:39,953] [WARNING] [django.request] Bad Request: /api/saved_views/2/
```

### Browser logs

```bash
main.js:3 ERROR TypeError: Cannot read properties of undefined (reading 'id')
    at k$ (main.js:3:1809286)
    at iO (main.js:3:106502)
    at nY (main.js:3:109966)
    at le (main.js:3:110486)
    at template (main.js:3:1811868)
    at kS (main.js:3:65617)
    at qW (main.js:3:75642)
    at Z8 (main.js:3:77016)
    at tE (main.js:3:76838)
    at JW (main.js:3:76800)
```

### Paperless-ngx version

Paperless-ngx 2.12.0

### Host OS

Synology DSM 7.2.2

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.12.0",
    "server_os": "Linux-4.4.302+-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 3829376737280,
        "available": 3823833759744
    },
    "database": {
        "type": "postgresql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "paperless_mail.0011_remove_mailrule_assign_tag_squashed_0024_alter_mailrule_name_and_more",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://broker:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-09-15T14:58:30.066697+02:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-09-15T13:05:03.658875Z",
        "classifier_error": null
    }
}
```

### Browser

Brave Version 1.69.168 Chromium: 128.0.6613.138

### Configuration changes

Added a bunch of env vars for config, like timezone, delete dups, none removal

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by Christoph-Raab** [comment]
I just saw that when I switch the page /settings/savedviews view menu, I can't click any button. I need to reload the page to be able to click somewhere else, so I can leave the page.
