### ISSUE TITLE
[BUG] ASN creation not working

### ISSUE THREAD

**Issue by derbeleuchter** [paperless-ngx/paperless-ngx#7716]
### Description

Hello everyone,

I'm facing an issue with my Paperless-NGX installation, and I'm not sure if it might be a bug: Since the last update, ASN numbers are no longer being generated. Documents are correctly imported from the consume folder, but the ASN coming from QR is not being processed.
PAPERLESS_CONSUMER_INOTIFY_DELAY=5 didn't help ...
What can I do?

Thank you very much!

### Steps to reproduce

put an PDF with ASN-QR in the folder "consume"

### Webserver logs

```bash
[2024-09-15 10:31:50,931] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/Paperless_Scan_150924113143.pdf to the task queue.

[2024-09-15 10:31:53,113] [DEBUG] [paperless.tasks] Skipping plugin CollatePlugin

[2024-09-15 10:31:53,113] [DEBUG] [paperless.tasks] Skipping plugin BarcodePlugin

[2024-09-15 10:31:53,114] [DEBUG] [paperless.tasks] Executing plugin WorkflowTriggerPlugin

[2024-09-15 10:31:53,183] [INFO] [paperless.tasks] WorkflowTriggerPlugin completed with:

[2024-09-15 10:31:53,184] [DEBUG] [paperless.tasks] Executing plugin ConsumeTaskPlugin

[2024-09-15 10:31:53,772] [INFO] [paperless.consumer] Consuming Paperless_Scan_150924113143.pdf

[2024-09-15 10:31:53,924] [DEBUG] [paperless.consumer] Detected mime type: application/pdf

[2024-09-15 10:31:54,011] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser

[2024-09-15 10:31:54,015] [DEBUG] [paperless.consumer] Parsing Paperless_Scan_150924113143.pdf...

[2024-09-15 10:31:56,161] [INFO] [paperless.parsing.tesseract] pdftotext exited 0

[2024-09-15 10:31:59,647] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-ngxssaiykb6/Paperless_Scan_150924113143.pdf'), 'output_file': PosixPath('/tmp/paperless/paperless-w_hxw_3z/archive.pdf'), 'use_threads': True, 'jobs': 4, 'language': 'deu+eng', 'output_type': 'pdfa', 'progress_bar': False, 'color_conversion_strategy': 'RGB', 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-w_hxw_3z/sidecar.txt')}

[2024-09-15 10:32:05,828] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 7.59 - no change

[2024-09-15 10:32:21,859] [INFO] [ocrmypdf._pipelines.ocr] Postprocessing...

[2024-09-15 10:32:22,874] [INFO] [ocrmypdf._pipeline] Image optimization ratio: 1.16 savings: 14.1%

[2024-09-15 10:32:22,874] [INFO] [ocrmypdf._pipeline] Total file size ratio: 1.66 savings: 39.7%

[2024-09-15 10:32:22,913] [INFO] [ocrmypdf._pipelines._common] Output file is a PDF/A-2B (as expected)

[2024-09-15 10:32:23,331] [DEBUG] [paperless.parsing.tesseract] Using text from sidecar file

[2024-09-15 10:32:23,332] [DEBUG] [paperless.consumer] Generating thumbnail for Paperless_Scan_150924113143.pdf...

[2024-09-15 10:32:23,875] [DEBUG] [paperless.parsing] Execute: convert -density 300 -scale 500x5000> -alpha remove -strip -auto-orient -define pdf:use-cropbox=true /tmp/paperless/paperless-w_hxw_3z/archive.pdf[0] /tmp/paperless/paperless-w_hxw_3z/convert.webp

[2024-09-15 10:32:25,669] [INFO] [paperless.parsing] convert exited 0

[2024-09-15 10:32:27,652] [DEBUG] [paperless.consumer] Saving record to database

[2024-09-15 10:32:27,652] [DEBUG] [paperless.consumer] Creation date from parse_date: 1951-06-21 00:00:00+00:00

[2024-09-15 10:32:32,169] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/Paperless_Scan_150924113224.pdf to the task queue.

[2024-09-15 10:32:34,766] [INFO] [paperless.handlers] Assigning document type Erklärung to 1951-06-21 Paperless_Scan_150924113143

[2024-09-15 10:32:34,827] [INFO] [paperless.handlers] Tagging "1951-06-21 Paperless_Scan_150924113143" with "FeWo - Meldeschein"

[2024-09-15 10:32:35,376] [DEBUG] [paperless.consumer] Deleting file /tmp/paperless/paperless-ngxssaiykb6/Paperless_Scan_150924113143.pdf

[2024-09-15 10:32:36,988] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-w_hxw_3z

[2024-09-15 10:32:36,990] [INFO] [paperless.consumer] Document 1951-06-21 Paperless_Scan_150924113143 consumption finished

[2024-09-15 10:32:36,994] [INFO] [paperless.tasks] ConsumeTaskPlugin completed with: Success. New document id 1059 created

[2024-09-15 10:32:37,320] [ERROR] [paperless.handlers] Creating PaperlessTask failed

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute

    return self.cursor.execute(sql, params)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute

    return super().execute(query, params)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/signals/handlers.py", line 794, in before_task_publish_handler

    PaperlessTask.objects.create(

  File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method

    return getattr(self.get_queryset(), name)(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 658, in create

    obj.save(force_insert=True, using=self.db)

  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 814, in save

    self.save_base(

  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 877, in save_base

    updated = self._save_table(

              ^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 1020, in _save_table

    results = self._do_insert(

              ^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 1061, in _do_insert

    return manager._insert(

           ^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method

    return getattr(self.get_queryset(), name)(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1805, in _insert

    return query.get_compiler(using=using).execute_sql(returning_fields)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql

    cursor.execute(sql, params)

  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute

    return self._execute_with_wrappers(

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers

    return executor(sql, params, many, context)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute

    with self.db.wrap_database_errors:

  File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__

    raise dj_exc_value.with_traceback(traceback) from exc_value

  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute

    return self.cursor.execute(sql, params)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute

    return super().execute(query, params)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

django.db.utils.OperationalError: database is locked

[2024-09-15 10:32:40,693] [DEBUG] [paperless.tasks] Skipping plugin CollatePlugin

[2024-09-15 10:32:40,693] [DEBUG] [paperless.tasks] Skipping plugin BarcodePlugin

[2024-09-15 10:32:40,694] [DEBUG] [paperless.tasks] Executing plugin WorkflowTriggerPlugin

[2024-09-15 10:32:40,713] [INFO] [paperless.tasks] WorkflowTriggerPlugin completed with:

[2024-09-15 10:32:40,714] [DEBUG] [paperless.tasks] Executing plugin ConsumeTaskPlugin

[2024-09-15 10:32:42,006] [INFO] [paperless.consumer] Consuming Paperless_Scan_150924113224.pdf

[2024-09-15 10:32:42,065] [DEBUG] [paperless.consumer] Detected mime type: application/pdf

[2024-09-15 10:32:42,117] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser

[2024-09-15 10:32:42,121] [DEBUG] [paperless.consumer] Parsing Paperless_Scan_150924113224.pdf...

[2024-09-15 10:32:42,890] [INFO] [paperless.parsing.tesseract] pdftotext exited 0

[2024-09-15 10:32:44,060] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-ngxz6gi6t4w/Paperless_Scan_150924113224.pdf'), 'output_file': PosixPath('/tmp/paperless/paperless-2y1wdh_l/archive.pdf'), 'use_threads': True, 'jobs': 4, 'language': 'deu+eng', 'output_type': 'pdfa', 'progress_bar': False, 'color_conversion_strategy': 'RGB', 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-2y1wdh_l/sidecar.txt')}

[2024-09-15 10:32:47,369] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 6.05 - no change

[2024-09-15 10:32:58,203] [INFO] [ocrmypdf._pipelines.ocr] Postprocessing...

[2024-09-15 10:32:58,982] [INFO] [ocrmypdf._pipeline] Image optimization ratio: 1.29 savings: 22.5%

[2024-09-15 10:32:58,982] [INFO] [ocrmypdf._pipeline] Total file size ratio: 1.90 savings: 47.5%

[2024-09-15 10:32:58,985] [INFO] [ocrmypdf._pipelines._common] Output file is a PDF/A-2B (as expected)

[2024-09-15 10:32:59,310] [DEBUG] [paperless.parsing.tesseract] Using text from sidecar file

[2024-09-15 10:32:59,311] [DEBUG] [paperless.consumer] Generating thumbnail for Paperless_Scan_150924113224.pdf...

[2024-09-15 10:32:59,314] [DEBUG] [paperless.parsing] Execute: convert -density 300 -scale 500x5000> -alpha remove -strip -auto-orient -define pdf:use-cropbox=true /tmp/paperless/paperless-2y1wdh_l/archive.pdf[0] /tmp/paperless/paperless-2y1wdh_l/convert.webp

[2024-09-15 10:33:00,927] [INFO] [paperless.parsing] convert exited 0

[2024-09-15 10:33:02,620] [DEBUG] [paperless.consumer] Saving record to database

[2024-09-15 10:33:02,620] [DEBUG] [paperless.consumer] Creation date from parse_date: 2024-01-02 00:00:00+00:00

[2024-09-15 10:33:06,299] [INFO] [paperless.handlers] Assigning correspondent Sparkasse to 2024-01-02 Paperless_Scan_150924113224

[2024-09-15 10:33:06,322] [INFO] [paperless.handlers] Assigning document type Kontoauszug to 2024-01-02 Sparkasse Paperless_Scan_150924113224

[2024-09-15 10:33:06,434] [DEBUG] [paperless.consumer] Deleting file /tmp/paperless/paperless-ngxz6gi6t4w/Paperless_Scan_150924113224.pdf

[2024-09-15 10:33:07,526] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-2y1wdh_l

[2024-09-15 10:33:07,528] [INFO] [paperless.consumer] Document 2024-01-02 Sparkasse Paperless_Scan_150924113224 consumption finished

[2024-09-15 10:33:07,532] [INFO] [paperless.tasks] ConsumeTaskPlugin completed with: Success. New document id 1060 created
```

### Paperless-ngx version

2.12.0

### Host OS

Synology NAS Diskstation 923+ ( x86_64)

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.12.0",
    "server_os": "Linux-4.4.302+-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 7659816476672,
        "available": 4930213195776
    },
    "database": {
        "type": "sqlite",
        "url": "/usr/src/paperless/data/db.sqlite3",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "documents.1052_document_transaction_id",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://broker:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-09-16T08:44:49.336560Z",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-09-16T08:05:01.847426Z",
        "classifier_error": null
    }
}
```

### Browser

Firefox 130.0

### Configuration changes

PAPERLESS_CONSUMER_INOTIFY_DELAY=5 (but didn't help)

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
Barcodes are not being checked. Presumably you have not configured them correctly, but you have not provided any information as requested regarding configuration.

**Comment by derbeleuchter** [comment]
Thank you very much, you were right - apparently the settings were lost during the container update. It's working again now.
