### ISSUE TITLE
[BUG] Backend fails if broker not accessible

### ISSUE THREAD

**Issue by vigne** [paperless-ngx/paperless-ngx#7946]
### Description

First, I'd like to express my sincere thanks for the effort you put into developing and maintaining this excellent software.

For the past few days, I’ve been experiencing networking (DHCP) issues on the LAN side, which, as far as I understand, should not affect the Docker stack. However, since these issues began, Paperless has started crashing frequently.

I realize this may not be directly related to Paperless, but I thought reporting this traceback might help improve the software’s resilience to network issues. I’m happy to provide additional information if needed.

### Steps to reproduce

1. docker-compose up -d
2. Wait for a few hours (a day max)
3. Docker reports the whole Docker stack as 'down', thus the frontend is no longer working

### Webserver logs

```bash
[2024-10-17 05:05:01,244] [INFO] [celery.app.trace] Task documents.tasks.train_classifier[d5d5e76c-0f32-493a-9896-30c42c03b27a] succeeded in 1.24124452797696s: None
2024-10-17 03:05:21,265 WARN received SIGTERM indicating exit request
2024-10-17 03:05:21,271 INFO waiting for gunicorn, celery, celery-beat, consumer to die
[2024-10-17 05:05:21,108] [WARNING] [celery.worker.consumer.consumer] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/worker/consumer/consumer.py", line 340, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.11/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/usr/local/lib/python3.11/site-packages/celery/worker/consumer/consumer.py", line 746, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.11/site-packages/celery/worker/loops.py", line 97, in asynloop
    next(loop)
  File "/usr/local/lib/python3.11/site-packages/kombu/asynchronous/hub.py", line 373, in create_loop
    cb(*cbargs)
  File "/usr/local/lib/python3.11/site-packages/kombu/transport/redis.py", line 1352, in on_readable
    self.cycle.on_readable(fileno)
  File "/usr/local/lib/python3.11/site-packages/kombu/transport/redis.py", line 569, in on_readable
    chan.handlers[type]()
  File "/usr/local/lib/python3.11/site-packages/kombu/transport/redis.py", line 918, in _receive
    ret.append(self._receive_one(c))
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kombu/transport/redis.py", line 928, in _receive_one
    response = c.parse_response()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 840, in parse_response
    response = self._execute(conn, try_read)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 816, in _execute
    return conn.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/retry.py", line 65, in call_with_retry
    fail(error)
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 818, in <lambda>
    lambda error: self._disconnect_raise_connect(conn, error),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 805, in _disconnect_raise_connect
    raise error
  File "/usr/local/lib/python3.11/site-packages/redis/retry.py", line 62, in call_with_retry
    return do()
           ^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 817, in <lambda>
    lambda: command(*args, **kwargs),
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 838, in try_read
    return conn.read_response(disconnect_on_error=False, push_request=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 512, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/_parsers/hiredis.py", line 130, in read_response
    self.read_from_socket()
  File "/usr/local/lib/python3.11/site-packages/redis/_parsers/hiredis.py", line 92, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
[2024-10-17 05:05:21,283] [INFO] [paperless.management.consumer] Received SIGINT, stopping inotify
2024-10-17 03:05:22,911 INFO stopped: consumer (exit status 0)
2024-10-17 03:05:24,138 INFO stopped: celery-beat (exit status 0)

worker: Warm shutdown (MainProcess)
2024-10-17 03:05:25,139 INFO waiting for gunicorn, celery to die
2024-10-17 03:05:28,142 INFO waiting for gunicorn, celery to die
```

### Paperless-ngx version

2.12.1 

### Host OS

Debian 11.11 inside LXC

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.12.1",
    "server_os": "Linux-6.8.4-3-pve-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 33501757440,
        "available": 22314844160
    },
    "database": {
        "type": "postgresql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "paperless_mail.0011_remove_mailrule_assign_tag_squashed_0024_alter_mailrule_name_and_more",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://broker:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-10-17T00:00:11.021015+02:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-10-17T06:24:21.747292Z",
        "classifier_error": null
    }
}
```

### Browser

FireFox

### Configuration changes

I do not think so, but let me know if you want to see the compose file

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by wsw70** [comment]
(wildly guessing)

> For the past few days, I’ve been experiencing networking (DHCP) issues on the LAN side, which, as far as I understand, should not affect the Docker stack. However, since these issues began, Paperless has started crashing frequently.

The internal docker DNS should indeed resolve internal names of services on its own (`broker` in your case). Have you considered whether the broker itself works? Maybe it needed to access something outside and could not? (say - DHCP provides a faulty gateway, DNS, RA, ...)

When you `docker exec -it broker /bin/sh`, can you ping docker, LAN and external IPs, and resolve docker, internal and external names?

**Comment by stumpylog** [comment]
Yes, the broker is a required service.  This is not a bug. It's not even our code
