### ISSUE TITLE
[BUG] CSRF Token error without a trailing slash

### ISSUE THREAD

**Issue by brandonrbridges** [paperless-ngx/paperless-ngx#8004]
### Description

Paperless will spit out a CSRF Token error, like the following:

```
[WARNING] [django.security.csrf] Forbidden (CSRF cookie not set.): /api/documents/post_document
```

After debugging for about 30 minutes; we discovered that the trailing slash was triggering this. After adding the trailing slash, the error disappeared but it didn't stop us jumping down a rabbit hole of domain configuration trying to fix this. 

### Steps to reproduce

_Using Docker_

1. Make an API call to `{HOST} + '/api/post_document` (no trailing slash)
2. Run `docker logs {ID}`
3. See error similar to above

### Webserver logs

```bash
[2024-10-25 13:24:54,791] [WARNING] [paperless.parsing.tesseract] No text was found in /tmp/paperless/paperless-ngx0_xrd0m6/NotionAvatar.png, the content will be empty.
[2024-10-25 13:24:56,569] [INFO] [paperless.parsing] convert exited 0
[2024-10-25 13:24:56,666] [INFO] [paperless.matching] Document matched WorkflowTrigger 1 from Workflow: Support Code Match
[2024-10-25 13:24:56,666] [INFO] [paperless.handlers] Applying WorkflowAction 1 from Workflow: Support Code Match
[2024-10-25 13:24:56,685] [INFO] [paperless.consumer] Document 2024-10-25 Test Item consumption finished
[2024-10-25 13:24:56,690] [INFO] [paperless.tasks] ConsumeTaskPlugin completed with: Success. New document id 5 created
[2024-10-25 13:24:56,694] [INFO] [celery.app.trace] Task documents.tasks.consume_file[a5ab0771-f57f-4ca7-ba74-4bd6ad1eb3ab] succeeded in 16.656986852001864s: 'Success. New document id 5 created'
[2024-10-25 13:27:03,711] [WARNING] [django.security.csrf] Forbidden (CSRF cookie not set.): /api/documents/post_document
```
```


### Browser logs

```bash
{
  "error": {
    "message": "Request failed with status code 403",
    "name": "AxiosError",
    "stack": "AxiosError: Request failed with status code 403\n    at settle (/Users/brandonbridges/GitHub/commander-api/node_modules/axios/lib/core/settle.js:19:12)\n    at BrotliDecompress.handleStreamEnd (/Users/brandonbridges/GitHub/commander-api/node_modules/axios/lib/adapters/http.js:599:11)\n    at BrotliDecompress.emit (node:events:530:35)\n    at endReadableNT (node:internal/streams/readable:1696:12)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)\n    at Axios.request (/Users/brandonbridges/GitHub/commander-api/node_modules/axios/lib/core/Axios.js:45:41)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at FilesService.uploadToPaperless (/modules/files/files.service.ts:128:24)\n    at FilesController.uploadProjectThumbnail (/modules/files/files.controller.ts:125:20)",
    "config": {
      "transitional": {
        "silentJSONParsing": true,
        "forcedJSONParsing": true,
        "clarifyTimeoutError": false
      },
      "adapter": [
        "xhr",
        "http",
        "fetch"
      ],
      "transformRequest": [
        null
      ],
      "transformResponse": [
        null
      ],
      "timeout": 0,
      "xsrfCookieName": "XSRF-TOKEN",
      "xsrfHeaderName": "X-XSRF-TOKEN",
      "maxContentLength": -1,
      "maxBodyLength": -1,
      "env": {},
      "headers": {
        "Accept": "application/json, text/plain, */*",
        "Content-Type": "multipart/form-data; boundary=--------------------------019569849156829348686014",
        "Authorization": "Token 303fcd4a7038a306549f3a522a4ccb5b925db64b",
        "User-Agent": "axios/1.7.7",
        "Content-Length": "162282",
        "Accept-Encoding": "gzip, compress, deflate, br"
      },
      "method": "post",
      "data": {
        "_overheadLength": 265,
        "_valueLength": 161961,
        "_valuesToMeasure": [],
        "writable": false,
        "readable": true,
        "dataSize": 0,
        "maxDataSize": 2097152,
        "pauseStreams": true,
        "_released": true,
        "_streams": [],
        "_currentStream": null,
        "_insideLoop": false,
        "_pendingNext": false,
        "_boundary": "--------------------------019569849156829348686014",
        "_events": {},
        "_eventsCount": 3
      },
      "url": "https://docs.project-commander.co.uk/api/documents/post_document"
    },
    "code": "ERR_BAD_REQUEST",
    "status": 403
  }
}
```
```


### Paperless-ngx version

2.12.1

### Host OS

No LSB modules are available. Distributor ID: Ubuntu Description: Ubuntu 22.04.4 LTS Release: 22.04 Codename: jammy

### Installation method

Docker - official image

### System status

```json
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy
```

### Configuration changes

URL

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
I'm not seeing the bug here.  A trailing slash is required.  That's just how the API works, has worked and will work.

**Comment by brandonrbridges** [comment]
> I'm not seeing the bug here. A trailing slash is required. That's just how the API works, has worked and will work.

The missing slash is not a CSRF token. CSRF = Cross-Site Request Forgery. A missing slash is not a request forgery. A more accurate response message would be an improvement.

**Comment by stumpylog** [comment]
Do you think we're implementing our own CSRF middleware?  It's very clear that is being logged from Django.

**Comment by brandonrbridges** [comment]
No? I am saying the error we get back is nothing to do with a CSRF token. The error message is misleading.

**Comment by shamoon** [comment]
He’s saying our code is not really the reason it happens, it comes from the framework we use [Django](https://www.djangoproject.com/). You’re not the first person to find it confusing. We always open to PRs

**Comment by brandonrbridges** [comment]
The trailing slash can be optional in Django.

Add to your existing middleware file(`/src/paperless/middlware.py`):
```py
def OptionalTrailingSlash(response):
    def middleware(request):
        if not request.path.endswith('/'):
            request.path_info = request.path = f"{request.path}/"
        return response(request)

    return middleware
```

Add to settings.py:
```py
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "paperless.middleware.ApiVersionMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "paperless.middleware.OptionalTrailingSlash", # Add this line 
]
```

Result: `api/documents/111` and `api/documents/111/` will work respectively.

**Comment by shamoon** [comment]
Not quite so simple. That would break a lot of things, including many of the API endpoints. But yes.

**Comment by brandonrbridges** [comment]
Perhaps it could be listed as an improvement instead; as you mentioned it has been raised a few times.

**Comment by shamoon** [comment]
Sure https://github.com/paperless-ngx/paperless-ngx/discussions/new?category=feature-requests
