### ISSUE TITLE
[BUG] Database migration fails to complete with exception successfully when upgrading from 2.12.1 to 2.13.0

### ISSUE THREAD

**Issue by CodingAlias** [paperless-ngx/paperless-ngx#8027]
### Description

After upgrading my paperless ngx instance to version 2.13 by pulling the latest image from ghcr.io/paperless-ngx/paperless-ngx:latest the container no longer successfully starts. It seems to fail during database migration operations.

I am running paperless ngx via docker on a Synology DiskStation with DSM 7.2 installed. The database is the mariadb database engine (v10.11.6) is running natively on the host operating system (not within a docker container).

### Steps to reproduce

docker-compose pull
docker-compose up -d

### Webserver logs

```bash
2024/10/26 15:10:56	stdout	  Applying paperless_mail.0027_mailaccount_expiration_mailaccount_account_type_and_more...
2024/10/26 15:10:56	stderr	django.db.utils.OperationalError: (1060, "Duplicate column name 'expiration'")
2024/10/26 15:10:56	stderr	    _mysql.connection.query(self, query)
2024/10/26 15:10:56	stderr	  File "/usr/local/lib/python3.12/site-packages/MySQLdb/connections.py", line 261, in query
2024/10/26 15:10:56	stderr	    db.query(q)
2024/10/26 15:10:56	stderr	  File "/usr/local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query
2024/10/26 15:10:56	stderr	          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/10/26 15:10:56	stderr	    res = self._query(mogrified_query)
2024/10/26 15:10:56	stderr	  File "/usr/local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute
2024/10/26 15:10:56	stderr	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/10/26 15:10:56	stderr	    return self.cursor.execute(query, args)
2024/10/26 15:10:56	stderr	  File "/usr/local/lib/python3.12/site-packages/django/db/backends/mysql/base.py", line 76, in execute
2024/10/26 15:10:56	stderr	           ^^^^^^^^^^^^^^^^^^^^^^^^
2024/10/26 15:10:56	stderr	    return self.cursor.execute(sql)
2024/10/26 15:10:56	stderr	  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 103, in _execute
2024/10/26 15:10:56	stderr	    raise dj_exc_value.with_traceback(traceback) from exc_value
2024/10/26 15:10:56	stderr	  File "/usr/local/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
2024/10/26 15:10:56	stderr	         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/10/26 15:10:56	stderr	    with self.db.wrap_database_errors:
2024/10/26 15:10:56	stderr	  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
2024/10/26 15:10:56	stderr	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/10/26 15:10:56	stderr	    return executor(sql, params, many, context)
2024/10/26 15:10:56	stderr	  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
2024/10/26 15:10:56	stderr	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/10/26 15:10:56	stderr	    return self._execute_with_wrappers(
2024/10/26 15:10:56	stderr	  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
2024/10/26 15:10:56	stderr	    cursor.execute(sql, params)
2024/10/26 15:10:56	stderr	  File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/schema.py", line 202, in execute
2024/10/26 15:10:56	stderr	    self.execute(sql, params or None)
2024/10/26 15:10:56	stderr	  File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/schema.py", line 768, in add_field
2024/10/26 15:10:56	stderr	    super().add_field(model, field)
2024/10/26 15:10:56	stderr	  File "/usr/local/lib/python3.12/site-packages/django/db/backends/mysql/schema.py", line 113, in add_field
2024/10/26 15:10:56	stderr	    schema_editor.add_field(
2024/10/26 15:10:56	stderr	  File "/usr/local/lib/python3.12/site-packages/django/db/migrations/operations/fields.py", line 110, in database_forwards
2024/10/26 15:10:56	stderr	    operation.database_forwards(
2024/10/26 15:10:56	stderr	  File "/usr/local/lib/python3.12/site-packages/django/db/migrations/migration.py", line 132, in apply
2024/10/26 15:10:56	stderr	            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/10/26 15:10:56	stderr	    state = migration.apply(state, schema_editor)
2024/10/26 15:10:56	stderr	  File "/usr/local/lib/python3.12/site-packages/django/db/migrations/executor.py", line 255, in apply_migration
2024/10/26 15:10:56	stderr	            ^^^^^^^^^^^^^^^^^^^^^
2024/10/26 15:10:56	stderr	    state = self.apply_migration(
2024/10/26 15:10:56	stderr	  File "/usr/local/lib/python3.12/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
2024/10/26 15:10:56	stderr	            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/10/26 15:10:56	stderr	    state = self._migrate_all_forwards(
2024/10/26 15:10:56	stderr	  File "/usr/local/lib/python3.12/site-packages/django/db/migrations/executor.py", line 135, in migrate
2024/10/26 15:10:56	stderr	                         ^^^^^^^^^^^^^^^^^
2024/10/26 15:10:56	stderr	    post_migrate_state = executor.migrate(
2024/10/26 15:10:56	stderr	  File "/usr/local/lib/python3.12/site-packages/django/core/management/commands/migrate.py", line 357, in handle
2024/10/26 15:10:56	stderr	          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/10/26 15:10:56	stderr	    res = handle_func(*args, **kwargs)
2024/10/26 15:10:56	stderr	  File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 107, in wrapper
2024/10/26 15:10:56	stderr	             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/10/26 15:10:56	stderr	    output = self.handle(*args, **options)
2024/10/26 15:10:56	stderr	  File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 459, in execute
2024/10/26 15:10:56	stderr	    self.execute(*args, **cmd_options)
2024/10/26 15:10:56	stderr	  File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 413, in run_from_argv
2024/10/26 15:10:56	stderr	    self.fetch_command(subcommand).run_from_argv(self.argv)
2024/10/26 15:10:56	stderr	  File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
2024/10/26 15:10:56	stderr	    utility.execute()
2024/10/26 15:10:56	stderr	  File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
2024/10/26 15:10:56	stderr	    execute_from_command_line(sys.argv)
2024/10/26 15:10:56	stderr	  File "/usr/src/paperless/src/manage.py", line 10, in <module>
2024/10/26 15:10:56	stderr	Traceback (most recent call last):
2024/10/26 15:10:56	stderr	
2024/10/26 15:10:56	stderr	The above exception was the direct cause of the following exception:
2024/10/26 15:10:56	stderr	
2024/10/26 15:10:56	stderr	MySQLdb.OperationalError: (1060, "Duplicate column name 'expiration'")
2024/10/26 15:10:56	stderr	    _mysql.connection.query(self, query)
2024/10/26 15:10:56	stderr	  File "/usr/local/lib/python3.12/site-packages/MySQLdb/connections.py", line 261, in query
2024/10/26 15:10:56	stderr	    db.query(q)
2024/10/26 15:10:56	stderr	  File "/usr/local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query
2024/10/26 15:10:56	stderr	          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/10/26 15:10:56	stderr	    res = self._query(mogrified_query)
2024/10/26 15:10:56	stderr	  File "/usr/local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute
2024/10/26 15:10:56	stderr	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/10/26 15:10:56	stderr	    return self.cursor.execute(query, args)
2024/10/26 15:10:56	stderr	  File "/usr/local/lib/python3.12/site-packages/django/db/backends/mysql/base.py", line 76, in execute
2024/10/26 15:10:56	stderr	           ^^^^^^^^^^^^^^^^^^^^^^^^
2024/10/26 15:10:56	stderr	    return self.cursor.execute(sql)
2024/10/26 15:10:56	stderr	  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 103, in _execute
2024/10/26 15:10:55	stderr	Traceback (most recent call last):
2024/10/26 15:10:54	stdout	Running migrations:
2024/10/26 15:10:54	stdout	  Apply all migrations: account, admin, auditlog, auth, authtoken, contenttypes, django_celery_results, documents, guardian, paperless, paperless_mail, sessions, socialaccount
2024/10/26 15:10:54	stdout	Operations to perform:
2024/10/26 15:10:45	stdout	Apply database migrations...
2024/10/26 15:10:45	stdout	Connected to Redis broker.
2024/10/26 15:10:45	stdout	Waiting for Redis...
2024/10/26 15:10:43	stdout	Connected to MariaDB
2024/10/26 15:10:43	stdout	Waiting for MariaDB to start...
2024/10/26 15:10:43	stdout	changed ownership of '/usr/src/paperless/export' from paperless:1000 to paperless:paperless
2024/10/26 15:10:43	stdout	Adjusting permissions of paperless files. This may take a while.
2024/10/26 15:10:43	stdout	mkdir: created directory '/tmp/paperless'
2024/10/26 15:10:43	stdout	Creating directory scratch directory /tmp/paperless
2024/10/26 15:10:42	stdout	Mapping UID and GID for paperless:paperless to 1051:65539
2024/10/26 15:10:42	stdout	Paperless-ngx docker container starting...
```

### Paperless-ngx version

2.13.0

### Host OS

Docker on Synology Diskstation 7.2

### Installation method

Docker - official image

### System status

```json
Container keeps restarting with the log-output shown above
```

### Browser

Firefox

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
There's definitely not a column named that already. Unfortunately it seems your database has become corrupted in some way.  Perhaps it was shutdown in the middle of migrations.

You can attempt to manually edit the migrations table to assume this migration is already applied, but there's nothing we're able to do.
