### ISSUE TITLE
[BUG] After update to 2.13.0 can't delete documents anymore

### ISSUE THREAD

**Issue by Momentum6890** [paperless-ngx/paperless-ngx#8058]
### Description

Since the update to 2.13.0, I can no longer delete documents. I have already tried an export and then set it up again, but the export cannot be imported. It also terminates with an error. If I restore a backup with 2.12.1, everything works again and I can also delete documents again. If I update to 2.13.0 again, I cannot delete any documents again.
![464372832_10234143295542174_4100092320993449015_n](https://github.com/user-attachments/assets/692380b1-c416-402e-8164-a6a952c692d6)
![464408677_10234143295502173_4897762985706670673_n](https://github.com/user-attachments/assets/005eadec-84d4-4061-ad22-8a3f0c2184ac)
![464783513_10234143295582175_548768961963099061_n](https://github.com/user-attachments/assets/9f7cce95-80e2-48c8-bb8f-e0b359cf4efc)

### Steps to reproduce

.

### Webserver logs

```bash
See screenshots.
```

### Browser logs

```bash
See screenshots.
```

### Paperless-ngx version

2.13.0

### Host OS

Proxmox > LXC with Debian 12

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.13.0",
    "server_os": "Linux-6.8.12-2-pve-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 3829392842752,
        "available": 3072484376576
    },
    "database": {
        "type": "mysql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "paperless_mail.0027_mailaccount_expiration_mailaccount_account_type_and_more",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://paperless_redis:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-10-27T16:35:04.598685+01:00",
        "index_error": null,
        "classifier_status": "WARNING",
        "classifier_last_trained": null,
        "classifier_error": "Classifier file does not exist (yet). Re-training may be pending."
    }
}
```

### Browser

Chrome

### Configuration changes

nothing

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
You haven't provided any actual logs, but I'm going to assume you are using MariaDb?

**Comment by stumpylog** [comment]
Yes, it is.  I'm going to assume it is the issue being worked in #8034.  In the future, pleas provide logs.  We ask for them for a reason.

**Comment by Momentum6890** [comment]
@stumpylog sorry, yes i'm using MariaDB. Which logs exactly do you need? In the log view of Paperless, the single yellow line (screenshot) is unfortunately the only entry that is displayed to me.

When I install the container fresh and perform an import, I get the following error:

root@Paperless:~# docker exec paperless_app document_importer ../export
Checking the manifest
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 239, in __get__
    rel_obj = self.field.get_cached_value(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/fields/mixins.py", line 37, in get_cached_value
    return instance._state.fields_cache[self.cache_name]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'document'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/paperless/src/documents/management/commands/document_importer.py", line 267, in handle
    self.load_data_to_database()
  File "/usr/src/paperless/src/documents/management/commands/document_importer.py", line 202, in load_data_to_database
    call_command("loaddata", manifest_path)
  File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 194, in call_command
    return command.execute(*args, **defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/management/commands/loaddata.py", line 103, in handle
    self.loaddata(fixture_labels)
  File "/usr/local/lib/python3.12/site-packages/django/core/management/commands/loaddata.py", line 164, in loaddata
    self.load_label(fixture_label)
  File "/usr/local/lib/python3.12/site-packages/django/core/management/commands/loaddata.py", line 254, in load_label
    if self.save_obj(obj):
       ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/management/commands/loaddata.py", line 210, in save_obj
    obj.save(using=self.using)
  File "/usr/local/lib/python3.12/site-packages/django/core/serializers/base.py", line 265, in save
    models.Model.save_base(self.object, using=using, raw=True, **kwargs)
  File "/usr/local/lib/python3.12/site-packages/django/db/models/base.py", line 1012, in save_base
    post_save.send(
  File "/usr/local/lib/python3.12/site-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/paperless/src/documents/signals/handlers.py", line 376, in update_filename_and_move_files
    instance = instance.document
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 257, in __get__
    rel_obj = self.get_object(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 220, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 649, in get
    raise self.model.DoesNotExist(
documents.models.Document.DoesNotExist: Problem installing fixture '/usr/src/paperless/export/manifest.json': Document matching query does not exist.

**Comment by Guezli** [comment]
Hello together

I have the same problem. Since the update from v2.12.1 to v2.13 I can't delete any files. After a downgrade to v2.12.1 the deletion works.
I use the version with Docker-Compose (Redus:6.0, mariadb:10, tika:latest).




2024-10-28 20:23:19,745] [ERROR] [paperless.api] Error deleting document: (1406, "Data too long for column 'transaction_id' at row 1")

[2024-10-28 20:23:49,777] [INFO] [paperless.management.consumer] Received SIGINT, stopping inotify

[2024-10-28 20:23:49,777] [DEBUG] [paperless.management.consumer] Consumer exiting.

[2024-10-28 20:24:06,119] [WARNING] [paperless.management.consumer] Not consuming file /usr/src/paperless/consume/.stignore: Unknown file extension.

[2024-10-28 20:24:06,120] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: /usr/src/paperless/consume

[2024-10-28 20:24:15,681] [DEBUG] [paperless.classifier] Document classification model does not exist (yet), not performing automatic matching.

[2024-10-28 20:24:19,144] [WARNING] [paperless.api] Detected a possible incompatible database column. See https://docs.paperless-ngx.com/troubleshooting/#convert-uuid-field

[2024-10-28 20:24:19,144] [ERROR] [paperless.api] Error deleting document: (1406, "Data too long for column 'transaction_id' at row 1")

[2024-10-28 20:27:29,710] [DEBUG] [paperless.classifier] Document classification model does not exist (yet), not performing automatic matching.

[2024-10-28 20:30:20,840] [INFO] [paperless.management.consumer] Received SIGINT, stopping inotify

[2024-10-28 20:30:20,840] [DEBUG] [paperless.management.consumer] Consumer exiting.

[2024-10-28 20:30:37,565] [WARNING] [paperless.management.consumer] Not consuming file /usr/src/paperless/consume/.stignore: Unknown file extension.

[2024-10-28 20:30:37,565] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: /usr/src/paperless/consume

[2024-10-28 20:30:40,055] [DEBUG] [paperless.classifier] Document classification model does not exist (yet), not performing automatic matching.

[2024-10-28 20:30:48,080] [WARNING] [paperless.api] Detected a possible incompatible database column. See https://docs.paperless-ngx.com/troubleshooting/#convert-uuid-field

[2024-10-28 20:30:48,080] [ERROR] [paperless.api] Error deleting document: (1406, "Data too long for column 'transaction_id' at row 1")

[2024-10-28 20:31:16,112] [INFO] [paperless.management.consumer] Received SIGINT, stopping inotify

[2024-10-28 20:31:16,112] [DEBUG] [paperless.management.consumer] Consumer exiting.

[2024-10-28 20:35:21,669] [WARNING] [paperless.management.consumer] Not consuming file /usr/src/paperless/consume/.stignore: Unknown file extension.

[2024-10-28 20:35:21,670] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: /usr/src/paperless/consume

[2024-10-28 20:35:34,140] [WARNING] [paperless.bulk_edit] Detected a possible incompatible database column. See https://docs.paperless-ngx.com/troubleshooting/#convert-uuid-field

[2024-10-28 20:35:34,140] [ERROR] [paperless.bulk_edit] Error deleting documents: (1406, "Data too long for column 'transaction_id' at row 1")

[2024-10-28 20:35:38,140] [WARNING] [paperless.bulk_edit] Detected a possible incompatible database column. See https://docs.paperless-ngx.com/troubleshooting/#convert-uuid-field

[2024-10-28 20:35:38,140] [ERROR] [paperless.bulk_edit] Error deleting documents: (1406, "Data too long for column 'transaction_id' at row 1")

[2024-10-28 20:35:40,335] [DEBUG] [paperless.classifier] Document classification model does not exist (yet), not performing automatic matching.

[2024-10-28 20:35:44,143] [WARNING] [paperless.api] Detected a possible incompatible database column. See https://docs.paperless-ngx.com/troubleshooting/#convert-uuid-field

[2024-10-28 20:35:44,143] [ERROR] [paperless.api] Error deleting document: (1406, "Data too long for column 'transaction_id' at row 1")

[2024-10-28 20:36:31,192] [INFO] [paperless.management.consumer] Received SIGINT, stopping inotify

[2024-10-28 20:36:31,193] [DEBUG] [paperless.management.consumer] Consumer exiting.

[2024-10-28 20:36:46,549] [WARNING] [paperless.management.consumer] Not consuming file /usr/src/paperless/consume/.stignore: Unknown file extension.

[2024-10-28 20:36:46,550] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: /usr/src/paperless/consume

[2024-10-28 20:36:57,435] [DEBUG] [paperless.classifier] Document classification model does not exist (yet), not performing automatic matching.`

**Comment by shamoon** [comment]
https://github.com/paperless-ngx/paperless-ngx/issues/8013#issuecomment-2442477574
