### ISSUE TITLE
[BUG] export does not work anymore after the update from 2.13.0 to 2.13.1

### ISSUE THREAD

**Issue by klatka** [paperless-ngx/paperless-ngx#8098]
### Description

Paperless export does not work anymore after the update from 2.13.0 to 2.13.1

### Steps to reproduce

docker compose -f /home/paperless/docker-compose.yml exec -T webserver document_exporter ../export --delete --passphrase XYZ

### Webserver logs

```bash
Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/paperless/src/documents/management/commands/document_exporter.py", line 218, in handle
    self.dump()
  File "/usr/src/paperless/src/documents/management/commands/document_exporter.py", line 289, in dump
    self.encrypt_secret_fields(manifest_dict)
  File "/usr/src/paperless/src/documents/management/commands/document_exporter.py", line 568, in encrypt_secret_fields
    if manifest_record["fields"][field]:
       ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
KeyError: 'key'
```

### Paperless-ngx version

2.13.1

### Host OS

Debian 12 x86_64

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
This one is my bad, I can fix unless you’re already working on it stumpy?
