### ISSUE TITLE
[BUG] Workers ending prematurely with kill -9

### ISSUE THREAD

**Issue by jamess60** [paperless-ngx/paperless-ngx#8125]
### Description

When uploading medium-large documents (eg 30 pages/25MB, even 1 at a time), the file gets stuck on processing document for several minutes before the CPU usage of the container drops to idle. 

The file tasks tab shows the following error:
`Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/billiard/pool.py", line 1265, in mark_as_worker_lost
    raise WorkerLostError(
billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL) Job: 197.
`

This problem seems to be intermittent as it will eventually accept the file after 5-10 retries. 

### Steps to reproduce

1. Generate a large PDF (eg a 600dpi scan of a 30 page document)
2. Attempt to upload the file to paperless
3. wait a few minutes 
4. check the file tasks tab 

### Webserver logs

```bash
[2024-10-30 23:30:13,696] [INFO] [paperless.parsing.tesseract] pdftotext exited 0                                                   │
│   [2024-10-30 23:30:13,717] [INFO] [paperless.parsing.tesseract] pdftotext exited 0                                                   │
│   [2024-10-30 23:30:14,429] [INFO] [ocrmypdf._pipelines.ocr] Start processing 2 pages concurrently                                    │
│   [2024-10-30 23:30:14,429] [INFO] [ocrmypdf._pipelines.ocr] Start processing 2 pages concurrently                                    │
│   [2024-10-30 23:30:16,871] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 33.08 - rotation appears correct                 │
│   [2024-10-30 23:30:16,881] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 24.63 - rotation appears correct                 │
│   [2024-10-30 23:30:16,998] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 14.28 - rotation appears correct                 │
│   [2024-10-30 23:30:17,027] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 10.81 - no change                                │
│   [2024-10-30 23:31:05,413] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 8.63 - no change                                 │
│   [2024-10-30 23:31:06,411] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 35.22 - rotation appears correct                 │
│   [2024-10-30 23:31:08,047] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 37.60 - rotation appears correct                 │
│   [2024-10-30 23:31:14,146] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 12.44 - rotation appears correct                 │
│   [2024-10-30 23:31:51,831] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 12.59 - rotation appears correct                 │
│   [2024-10-30 23:31:56,808] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 39.18 - rotation appears correct                 │
│   [2024-10-30 23:31:57,201] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 37.14 - rotation appears correct                 │
│   [2024-10-30 23:32:06,025] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 13.84 - rotation appears correct                 │
│   [2024-10-30 23:32:47,055] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 11.91 - no change                                │
│   [2024-10-30 23:32:48,597] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 35.16 - rotation appears correct                 │
│   [2024-10-30 23:32:48,631] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 36.88 - rotation appears correct                 │
│   [2024-10-30 23:32:59,262] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 11.25 - no change
```

### Paperless-ngx version

2.13.2

### Host OS

Debian 12 amd64 + docker

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.13.2",
    "server_os": "Linux-6.1.0-25-amd64-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 262075314176,
        "available": 162364780544
    },
    "database": {
        "type": "sqlite",
        "url": "/usr/src/paperless/data/db.sqlite3",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "documents.1056_customfieldinstance_deleted_at_and_more",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://pngx-broker:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-10-30T23:29:14.364138Z",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-10-30T23:05:02.140740Z",
        "classifier_error": null
    }
}
```

### Browser

Firefox on macOS

### Configuration changes

    pngx-broker:
        container_name: pngx-broker
        image: docker.io/library/redis:7
        restart: unless-stopped
        volumes:
            - /containers/v-cont-01/data/paperless-ngx/redisdata:/data
    pngx-webserver: 
        container_name: pngx-webserver
        image: ghcr.io/paperless-ngx/paperless-ngx:latest
        restart: unless-stopped
        depends_on:
            - pngx-broker
            - pngx-gotenberg
            - pngx-tika
        ports:
            - "5006:8000"
        healthcheck:
            test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
            interval: 30s
            timeout: 10s
            retries: 5
        volumes:
            - /containers/v-cont-01/data/paperless-ngx/data:/usr/src/paperless/data
            - /containers/v-cont-01/data/paperless-ngx/media:/usr/src/paperless/media
            - /containers/v-cont-01/data/paperless-ngx/export:/usr/src/paperless/export
            - /containers/v-cont-01/data/paperless-ngx/consume:/usr/src/paperless/consume
        env_file: /containers/v-cont-01/data/paperless-ngx/docker-compose.env
        environment:
            PAPERLESS_REDIS: redis://pngx-broker:6379
            PAPERLESS_TIKA_ENABLED: 1
            PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://pngx-gotenberg:3000
            PAPERLESS_TIKA_ENDPOINT: http://pngx-tika:9998
        deploy:
            resources:
                limits:
                    cpus: '12'
                    memory: 4G
    pngx-gotenberg:
        container_name: pngx-gotenberg
        image: docker.io/gotenberg/gotenberg:7.8
        restart: unless-stopped
        command:
            - "gotenberg"
            - "--chromium-disable-javascript=true"
            - "--chromium-allow-list=file:///tmp/.*"
    pngx-tika:
        container_name: pngx-tika
        image: ghcr.io/paperless-ngx/tika:latest
        restart: unless-stopped

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
The worker is being killed by the system, likely due to memory constraints.  You can check that easily via dmesg or the equivalent for your system.  Ocr is an intensive process.

This is not a bug, there is nothing we're doing wrong or can change.

**Comment by jamess60** [comment]
@stumpylog I upped the ram from 4GB to 8GB and Im still seeing the same behavior. It appears the container isnt using more than 3GB ram 99% of the time

**Comment by kingp0dd** [comment]
I'm getting the same error. My RAM usage is only 6GB out of 9GB. CPU usage is also at 8% only:

![image](https://github.com/user-attachments/assets/ec3bab64-514a-4e39-82ab-8f773e8cefeb)

This is the file I'm trying to upload:

https://brd.so/K5uUE328rEeYLRwSCLV2eYBnzPPv/user-manual-dl7800-en.pdf

Logs:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/billiard/pool.py", line 1265, in mark_as_worker_lost
    raise WorkerLostError(
billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL) Job: 136.

Logs:


[2024-11-05 17:19:45,756] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-ngx8ma60l6v/user-manual-dl7800-en.pdf'), 'output_file': PosixPath('/tmp/paperless/paperless-y8v5fc2x/archive.pdf'), 'use_threads': True, 'jobs': 8, 'language': 'eng', 'output_type': 'pdfa', 'progress_bar': False, 'color_conversion_strategy': 'RGB', 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-y8v5fc2x/sidecar.txt')}

[2024-11-05 17:19:49,692] [INFO] [ocrmypdf._pipelines.ocr] Start processing 8 pages concurrently

[2024-11-05 17:19:49,693] [INFO] [ocrmypdf._pipeline] page has no images - skipping all processing on this page to avoid losing detail. Use --force-ocr if you wish to perform OCR on pages that have vector content.

[2024-11-05 17:19:49,694] [INFO] [ocrmypdf._pipeline] page has no images - skipping all processing on this page to avoid losing detail. Use --force-ocr if you wish to perform OCR on pages that have vector content.

[2024-11-05 17:19:49,694] [INFO] [ocrmypdf._pipeline] page has no images - skipping all processing on this page to avoid losing detail. Use --force-ocr if you wish to perform OCR on pages that have vector content.

[2024-11-05 17:19:49,694] [INFO] [ocrmypdf._pipeline] page has no images - skipping all processing on this page to avoid losing detail. Use --force-ocr if you wish to perform OCR on pages that have vector content.

[2024-11-05 17:19:49,694] [INFO] [ocrmypdf._pipeline] page has no images - skipping all processing on this page to avoid losing detail. Use --force-ocr if you wish to perform OCR on pages that have vector content.

[2024-11-05 17:19:49,695] [INFO] [ocrmypdf._pipeline] page has no images - skipping all processing on this page to avoid losing detail. Use --force-ocr if you wish to perform OCR on pages that have vector content.

[2024-11-05 17:19:49,695] [INFO] [ocrmypdf._pipeline] page has no images - skipping all processing on this page to avoid losing detail. Use --force-ocr if you wish to perform OCR on pages that have vector content.

[2024-11-05 17:19:49,695] [INFO] [ocrmypdf._pipeline] page has no images - skipping all processing on this page to avoid losing detail. Use --force-ocr if you wish to perform OCR on pages that have vector content.

[2024-11-05 17:19:49,698] [INFO] [ocrmypdf._pipeline] page has no images - skipping all processing on this page to avoid losing detail. Use --force-ocr if you wish to perform OCR on pages that have vector content.

[2024-11-05 17:19:49,698] [INFO] [ocrmypdf._pipeline] page has no images - skipping all processing on this page to avoid losing detail. Use --force-ocr if you wish to perform OCR on pages that have vector content.

[2024-11-05 17:19:49,698] [INFO] [ocrmypdf._pipeline] page has no images - skipping all processing on this page to avoid losing detail. Use --force-ocr if you wish to perform OCR on pages that have vector content.

[2024-11-05 17:19:49,699] [INFO] [ocrmypdf._pipeline] page has no images - skipping all processing on this page to avoid losing detail. Use --force-ocr if you wish to perform OCR on pages that have vector content.

[2024-11-05 17:19:49,699] [INFO] [ocrmypdf._pipeline] page has no images - skipping all processing on this page to avoid losing detail. Use --force-ocr if you wish to perform OCR on pages that have vector content.

[2024-11-05 17:19:49,699] [INFO] [ocrmypdf._pipeline] page has no images - skipping all processing on this page to avoid losing detail. Use --force-ocr if you wish to perform OCR on pages that have vector content.

[2024-11-05 17:19:49,699] [INFO] [ocrmypdf._pipeline] page has no images - skipping all processing on this page to avoid losing detail. Use --force-ocr if you wish to perform OCR on pages that have vector content.

[2024-11-05 17:19:49,701] [INFO] [ocrmypdf._pipeline] page has no images - skipping all processing on this page to avoid losing detail. Use --force-ocr if you wish to perform OCR on pages that have vector content.

[2024-11-05 17:19:49,702] [INFO] [ocrmypdf._pipeline] page has no images - skipping all processing on this page to avoid losing detail. Use --force-ocr if you wish to perform OCR on pages that have vector content.

[2024-11-05 17:19:50,750] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 11.67 - no change

[2024-11-05 17:19:50,785] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 11.65 - no change

[2024-11-05 17:19:50,857] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 10.07 - no change

```

**Comment by shamoon** [comment]
There is nothing to investigate here, paperless doesn’t even handle the ocr itself as noted in multiple places in the issue template (and it notes the correct place to consider opening a report).

If the concern is about python multi threading, that also isn’t something we particularly control…
