### ISSUE TITLE
[BUG] Splitting a PDF with ASNs failure to consume

### ISSUE THREAD

**Issue by JarlMorgennebel** [paperless-ngx/paperless-ngx#8141]
### Description

Existing document with ASN (label and ID configured) shall be splitted (Menu Action) into two files.

Error:
3629_1-4.pdf
3629_1-4.pdf: Not consuming 3629_1-4.pdf: Given ASN 584 already exists!

Both new files are not consumed and not added. Splitting the PDF fails :(

Instead of reusing the ASN assigned to the original and may be required to use MAX-ASN+1 and MAX-ASN+2 for the new splitted files - and inform the user to delete these labels.

### Steps to reproduce

1. Open a multi-page PDF with ASN assigned
2. Select menu Action -> Split
3. Add a divider between some pages
4. Run

### Webserver logs

```bash
webserver_1  | [2024-11-01 21:10:33,894] [INFO] [paperless.handlers] Tagging "2023-08-09 Stadtwerke Heide Grundversorgung Erdgas (split 2)" with "Bank"
webserver_1  | [2024-11-01 21:10:34,466] [INFO] [paperless.consumer] Document 2023-08-09 Stadtwerke Heide Grundversorgung Erdgas (split 2) consumption finished
webserver_1  | [2024-11-01 21:10:34,474] [INFO] [paperless.tasks] ConsumeTaskPlugin completed with: Success. New document id 3727 created
webserver_1  | [2024-11-01 21:10:34,486] [ERROR] [django_celery_results.backends.database] Chord 'e52f477c-1030-4e09-8ee6-01be1ed1f1ea' raised: ConsumerError('3629_1-4.pdf: Not consuming 3629_1-4.pdf: Given ASN 584 already exists!')
webserver_1  | Traceback (most recent call last):
webserver_1  |   File "/usr/local/lib/python3.11/site-packages/django_celery_results/backends/database.py", line 292, in trigger_callback
webserver_1  |     ret = j(timeout=app.conf.result_chord_join_timeout, propagate=True)
webserver_1  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webserver_1  |   File "/usr/local/lib/python3.11/site-packages/celery/result.py", line 775, in join
webserver_1  |     value = result.get(
webserver_1  |             ^^^^^^^^^^^
webserver_1  |   File "/usr/local/lib/python3.11/site-packages/celery/result.py", line 247, in get
webserver_1  |     self.maybe_throw(callback=callback)
webserver_1  |   File "/usr/local/lib/python3.11/site-packages/celery/result.py", line 365, in maybe_throw
webserver_1  |     self.throw(value, self._to_remote_traceback(tb))
webserver_1  |   File "/usr/local/lib/python3.11/site-packages/celery/result.py", line 358, in throw
webserver_1  |     self.on_ready.throw(*args, **kwargs)
webserver_1  |   File "/usr/local/lib/python3.11/site-packages/vine/promises.py", line 235, in throw
webserver_1  |     reraise(type(exc), exc, tb)
webserver_1  |   File "/usr/local/lib/python3.11/site-packages/vine/utils.py", line 27, in reraise
webserver_1  |     raise value
webserver_1  | documents.consumer.ConsumerError: 3629_1-4.pdf: Not consuming 3629_1-4.pdf: Given ASN 584 already exists!
webserver_1  | [2024-11-01 21:10:34,495] [INFO] [celery.app.trace] Task documents.tasks.consume_file[1797219e-bd66-4c2f-a8bd-332baaf2d875] succeeded in 212.81392761692405s: 'Success. New document id 3727 created'
webserver_1  | [2024-11-01 21:10:37,151] [INFO] [celery.app.trace] Task paperless_mail.tasks.process_mail_accounts[e0d2a3a1-0c91-4925-b684-79ad405aa41c] succeeded in 0.4214999321848154s: 'No new documents were added.'
```

### Paperless-ngx version

2.12.1

### Host OS

Devuan 5.0

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.12.1",
    "server_os": "Linux-6.1.0-25-amd64-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 93896515584,
        "available": 72117334016
    },
    "database": {
        "type": "postgresql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "documents.1052_document_transaction_id",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://broker:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-11-01T21:10:34.343898+01:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-11-01T20:06:47.291501Z",
        "classifier_error": null
    }
}
```

### Browser

Vivaldi 

### Configuration changes

Added ASN processing and password removal scripts:

      PAPERLESS_CONSUMER_ENABLE_BARCODES: 1
      PAPERLESS_CONSUMER_ENABLE_ASN_BARCODE: 1
      PAPERLESS_CONSUMER_BARCODE_SCANNER: ZXING
      PAPERLESS_PRE_CONSUME_SCRIPT: /usr/src/paperless/scripts/removepassword.py

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
There is no mechanism currently by which this is expected to happen, in other words it’s not supported. And splitting doesn’t replace the existing document it creates two new ones, so yes it seems they’ll fail.

You can open a feature request if you’d like, if there are others hitting this it can always be implemented.
