### ISSUE TITLE
[BUG] Error while processing mail: Base64 decoding error

### ISSUE THREAD

**Issue by definitio** [paperless-ngx/paperless-ngx#8246]
### Description

Some mails can't be processed. I have this error for a few months.

### Steps to reproduce

1. Receive a mail

### Webserver logs

```bash
[2024-11-10 11:30:06,106] [ERROR] [paperless_mail] Rule $RULE_NAME: Error while processing mail $NUMBER: Base64 decoding error

Traceback (most recent call last):

  File "/usr/local/lib/python3.12/email/header.py", line 124, in decode_header

    word = email.base64mime.decode(encoded_string)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/email/base64mime.py", line 108, in decode

    return a2b_base64(string.encode('raw-unicode-escape'))

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

binascii.Error: Invalid base64-encoded string: number of data characters (53) cannot be 1 more than a multiple of 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_mail/mail.py", line 656, in _handle_mail_rule

    processed_files = self._handle_message(message, rule)

                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/paperless/src/paperless_mail/mail.py", line 684, in _handle_message

    f"Processing mail {message.subject} from {message.from_} with "

                       ^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/imap_tools/message.py", line 101, in subject

    return ''.join(decode_value(*head_part) for head_part in decode_header(raw))

                                                             ^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/email/header.py", line 126, in decode_header

    raise HeaderParseError('Base64 decoding error')

email.errors.HeaderParseError: Base64 decoding error
```

### Paperless-ngx version

2.13.4

### Host OS

Debian 12

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
It's not a valid email.  Exactly as the error states, it's not encoded correctly. There's nothing we can do, that email can't be consumed without manual intervention.

**Comment by definitio** [comment]
Unfortunately it's impossible to fix incoming mails.
