### ISSUE TITLE
[BUG] OCR fails on lage resolution PDFs

### ISSUE THREAD

**Issue by Schluggi** [paperless-ngx/paperless-ngx#8251]
### Description

In the past I scanned a lot of documents via Switfscan (you can take pictures and it will create a PDF and also do OCR on top).

Now I want to switch to Paperless-NGX but all my old self scanned documents fail. I guess because these files are big (~500kb/file) and saved with high resolution images. 

I post this issue here because if I grabbed the png from paperless and tried the same command (same version) on my local device and it worked without any issues. 

Maybe this issue happens because of other pre-progressing or the command simply timeouts?

Moreover: 
Paperless Docker uses the outdated debian bookworm version of tesseract. Is there any reason not to use the latest version? Maybe this would improve and fix some stuff.

### Steps to reproduce

1. Install Switfscan from the Playstore
2. Go to `Settings -> Scan Quality` and set this to `best`
3. Enable OCR (`Settings -> Text Recognition (OCR)`)
4. Scan a A4 colorfull document with the app
5. Upload the document to Paperless-NGX

### Webserver logs

```bash
2024-11-10 11:21:56.639515+00:00[2024-11-10 12:21:56,635] [INFO] [celery.worker.strategy] Task documents.tasks.consume_file[4ef4c9eb-794f-4681-adc7-19e801bc42b9] received
2024-11-10 11:21:56.691776+00:00[2024-11-10 12:21:56,691] [INFO] [paperless.tasks] WorkflowTriggerPlugin completed with: 
2024-11-10 11:21:56.702507+00:00[2024-11-10 12:21:56,701] [INFO] [paperless.consumer] Consuming 2024-05-06 Zahnreinigung.pdf
2024-11-10 11:21:56.730425+00:00[2024-11-10 12:21:56,729] [INFO] [paperless.parsing.tesseract] pdftotext exited 0
2024-11-10 11:21:57.273947+00:00[2024-11-10 12:21:57,273] [INFO] [ocrmypdf._pipeline] redoing OCR
2024-11-10 11:22:19.070911+00:00[2024-11-10 12:22:19,070] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 8.59 - no change
2024-11-10 11:23:04.346205+00:00[2024-11-10 12:23:04,345] [WARNING] [ocrmypdf._exec.unpaper] Image with size 14829x20989 is too large for cleaning with 'unpaper'.
2024-11-10 11:23:44.283245+00:00[2024-11-10 12:23:44,276] [ERROR] [paperless.consumer] Error occurred while consuming document 2024-05-06 Zahnreinigung.pdf: SubprocessOutputError: . See logs for more information.
2024-11-10 11:23:44.283308+00:00Traceback (most recent call last):
2024-11-10 11:23:44.283320+00:00File "/usr/local/lib/python3.12/site-packages/ocrmypdf/_exec/tesseract.py", line 313, in generate_hocr
2024-11-10 11:23:44.283370+00:00p = run(args_tesseract, stdout=PIPE, stderr=STDOUT, timeout=timeout, check=True)
2024-11-10 11:23:44.283381+00:00^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-10 11:23:44.283390+00:00File "/usr/local/lib/python3.12/site-packages/ocrmypdf/subprocess/__init__.py", line 62, in run
2024-11-10 11:23:44.283398+00:00proc = subprocess_run(args, env=env, check=check, **kwargs)
2024-11-10 11:23:44.283511+00:00^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-10 11:23:44.283524+00:00File "/usr/local/lib/python3.12/subprocess.py", line 571, in run
2024-11-10 11:23:44.283533+00:00raise CalledProcessError(retcode, process.args,
2024-11-10 11:23:44.283590+00:00subprocess.CalledProcessError: Command '['tesseract', '-l', 'deu+eng', '/tmp/ocrmypdf.io.rwvvoql2/000001_ocr.png', '/tmp/ocrmypdf.io.rwvvoql2/000001_ocr_hocr', 'hocr', 'txt']' died with <Signals.SIGKILL: 9>.
2024-11-10 11:23:44.283603+00:002024-11-10T11:23:44.283603003Z
2024-11-10 11:23:44.283610+00:00The above exception was the direct cause of the following exception:
2024-11-10 11:23:44.283618+00:002024-11-10T11:23:44.283618839Z
2024-11-10 11:23:44.283651+00:00Traceback (most recent call last):
2024-11-10 11:23:44.283659+00:00File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 376, in parse
2024-11-10 11:23:44.283668+00:00ocrmypdf.ocr(**args)
2024-11-10 11:23:44.283676+00:00File "/usr/local/lib/python3.12/site-packages/ocrmypdf/api.py", line 380, in ocr
2024-11-10 11:23:44.283755+00:00return run_pipeline(options=options, plugin_manager=plugin_manager)
2024-11-10 11:23:44.283778+00:00^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-10 11:23:44.283787+00:00File "/usr/local/lib/python3.12/site-packages/ocrmypdf/_pipelines/ocr.py", line 223, in run_pipeline
2024-11-10 11:23:44.283818+00:00return _run_pipeline(options, plugin_manager)
2024-11-10 11:23:44.283828+00:00^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-10 11:23:44.283837+00:00File "/usr/local/lib/python3.12/site-packages/ocrmypdf/_pipelines/ocr.py", line 190, in _run_pipeline
2024-11-10 11:23:44.283846+00:00optimize_messages = exec_concurrent(context, executor)
2024-11-10 11:23:44.283884+00:00^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-10 11:23:44.283896+00:00File "/usr/local/lib/python3.12/site-packages/ocrmypdf/_pipelines/ocr.py", line 117, in exec_concurrent
2024-11-10 11:23:44.283905+00:00executor(
2024-11-10 11:23:44.283916+00:00File "/usr/local/lib/python3.12/site-packages/ocrmypdf/_concurrent.py", line 78, in __call__
2024-11-10 11:23:44.283972+00:00self._execute(
2024-11-10 11:23:44.283983+00:00File "/usr/local/lib/python3.12/site-packages/ocrmypdf/builtin_plugins/concurrency.py", line 144, in _execute
2024-11-10 11:23:44.284003+00:00result = future.result()
2024-11-10 11:23:44.284012+00:00^^^^^^^^^^^^^^^
2024-11-10 11:23:44.284140+00:00File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
2024-11-10 11:23:44.284158+00:00return self.__get_result()
2024-11-10 11:23:44.284167+00:00^^^^^^^^^^^^^^^^^^^
2024-11-10 11:23:44.284175+00:00File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
2024-11-10 11:23:44.284226+00:00raise self._exception
2024-11-10 11:23:44.284244+00:00File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
2024-11-10 11:23:44.284254+00:00result = self.fn(*self.args, **self.kwargs)
2024-11-10 11:23:44.284262+00:00^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-10 11:23:44.284307+00:00File "/usr/local/lib/python3.12/site-packages/ocrmypdf/_pipelines/ocr.py", line 81, in _exec_page_sync
2024-11-10 11:23:44.284319+00:00ocr_out, text_out = _image_to_ocr_text(page_context, ocr_image_out)
2024-11-10 11:23:44.284328+00:00^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-10 11:23:44.284336+00:00File "/usr/local/lib/python3.12/site-packages/ocrmypdf/_pipelines/ocr.py", line 62, in _image_to_ocr_text
2024-11-10 11:23:44.284367+00:00hocr_out, text_out = ocr_engine_hocr(ocr_image_out, page_context)
2024-11-10 11:23:44.284377+00:00^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-10 11:23:44.284385+00:00File "/usr/local/lib/python3.12/site-packages/ocrmypdf/_pipeline.py", line 665, in ocr_engine_hocr
2024-11-10 11:23:44.284413+00:00ocr_engine.generate_hocr(
2024-11-10 11:23:44.284422+00:00File "/usr/local/lib/python3.12/site-packages/ocrmypdf/builtin_plugins/tesseract_ocr.py", line 268, in generate_hocr
2024-11-10 11:23:44.284432+00:00tesseract.generate_hocr(
2024-11-10 11:23:44.284441+00:00File "/usr/local/lib/python3.12/site-packages/ocrmypdf/_exec/tesseract.py", line 327, in generate_hocr
2024-11-10 11:23:44.284463+00:00raise SubprocessOutputError() from e
2024-11-10 11:23:44.284472+00:00ocrmypdf.exceptions.SubprocessOutputError
2024-11-10 11:23:44.284481+00:002024-11-10T11:23:44.284481221Z
2024-11-10 11:23:44.284489+00:00The above exception was the direct cause of the following exception:
2024-11-10 11:23:44.284510+00:002024-11-10T11:23:44.284510803Z
2024-11-10 11:23:44.284519+00:00Traceback (most recent call last):
2024-11-10 11:23:44.284526+00:00File "/usr/local/lib/python3.12/site-packages/asgiref/sync.py", line 327, in main_wrap
2024-11-10 11:23:44.284534+00:00raise exc_info[1]
2024-11-10 11:23:44.284542+00:00File "/usr/src/paperless/src/documents/consumer.py", line 477, in run
2024-11-10 11:23:44.284563+00:00document_parser.parse(self.working_copy, mime_type, self.filename)
2024-11-10 11:23:44.284572+00:00File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 399, in parse
2024-11-10 11:23:44.284581+00:00raise ParseError(
2024-11-10 11:23:44.284601+00:00documents.parsers.ParseError: SubprocessOutputError: . See logs for more information.
2024-11-10 11:23:44.286671+00:00[2024-11-10 12:23:44,283] [ERROR] [paperless.tasks] ConsumeTaskPlugin failed: 2024-05-06 Zahnreinigung.pdf: Error occurred while consuming document 2024-05-06 Zahnreinigung.pdf: SubprocessOutputError: . See logs for more information.
```

### Paperless-ngx version

2.13.4

### Host OS

TrueNAS 24.10.0.2 

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.13.4",
    "server_os": "Linux-6.6.44-production+truenas-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 498592776192,
        "available": 498592251904
    },
    "database": {
        "type": "postgresql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "paperless_mail.0028_alter_mailaccount_password_and_more",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://redis:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-11-10T12:18:51.536249+01:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-11-10T11:06:13.436091Z",
        "classifier_error": null
    }
}
```

### Browser

Firefox

### Configuration changes

![image](https://github.com/user-attachments/assets/2720d0b1-d0dc-4c38-a93d-710338b6a14e)

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
The second box you checked states that your issue is not about Ocr. It is about Ocr.  This is not a bug.
