### ISSUE TITLE
[BUG]  django.db.utils.OperationalError: (1050, "Table 'documents_xxxxxxxx' already exists"

### ISSUE THREAD

**Issue by mr-elamin** [paperless-ngx/paperless-ngx#8338]
### Description

Hi,

I'm not sure but I think this is a bug.
I'm hosting multiple instances of Paperless-ngx on k8s for friends and family, I'm using this image:

  repository: ghcr.io/paperless-ngx/paperless-ngx
  # -- Image pull policy
  pullPolicy: IfNotPresent
  # -- Image tag
  tag: 2.13.5
  
Whenever I install a new fresh deployment of the app I get an error that the table exists:
today I got this error on this table:
django.db.utils.OperationalError: (1050, "Table 'documents_comment' already exists")

on previous installations I got error on other table like:
django.db.utils.OperationalError: (1050, "Table 'auth_user' already exists")

or
django.db.utils.OperationalError: (1050, "Table 'paperless_mail_mailaccount' already exists")

or
django.db.utils.OperationalError: (1060, "Duplicate column name 'date_created'")

with every new installation, I get such an error with a duplication in the MariaDB Version 11.4.3

Sometimes it works when I drop the table manually and sometimes it doesn't work and I need to drop the complete database, and the persistentvolumeclaim and reinstall the app from the beginning.

################## here are my complete helm values ################
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/a081de5/charts/library/common/values.yaml
#

image:
  # -- Image repository
  repository: ghcr.io/paperless-ngx/paperless-ngx
  # -- Image pull policy
  pullPolicy: IfNotPresent
  # -- Image tag
  tag: 2.13.5 

env:

  TZ: UTC

  ####### External-MariaDB ########
  PAPERLESS_DBENGINE: mariadb
  PAPERLESS_DBHOST: wp-mariadb-primary.wp-mariadb.svc.cluster.local
  PAPERLESS_DBPORT: "3306"
  PAPERLESS_DBNAME: paperless-my-host-com
  PAPERLESS_DBUSER: maria_db_user
  PAPERLESS_DBPASS:
    secretKeyRef:
      name: mariadb-password-wp-rikaz-group
      key: mariadb-password

 ####### External-Redis ########
  PAPERLESS_REDIS: 'redis://:mypassword@paperless-redis-master.paperless-redis.svc.cluster.local:6379'
  PAPERLESS_REDIS_PREFIX: "my-host-com" #adil

######## Admin #########
  PAPERLESS_ADMIN_USER: "admin"  # Add this line
  PAPERLESS_ADMIN_PASSWORD: # Add this line
    secretKeyRef:
      name: my-host-paperless-admin-password
      key: paperless-admin-password

service:
  main:
    ports:
      http:
        port: 8000

ingress:

  main:
    enabled: true #adil default is false
    ingressClassName: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 64m
      cert-manager.io/cluster-issuer: letsencrypt-dns01-staging
    hosts:
      - host: my-host.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: my-host.com-tls
        hosts:
          - my-host.com

persistence:

  data:
    enabled: true 
    retain: true
    mountPath: /usr/src/paperless/data
    storageClass: "rook-cephfs"
    accessMode: ReadWriteOnce
    size: 1Gi

  media:
    enabled: true
    retain: true
    mountPath: /usr/src/paperless/media
    storageClass: "rook-cephfs"
    accessMode: ReadWriteOnce
    size: 5Gi

  export:
    enabled: true
    retain: true
    mountPath: /usr/src/paperless/export
    storageClass: "rook-nfs"
    accessMode: ReadWriteMany
    size: 5Gi

  consume:
    enabled: true
    retain: true
    mountPath: /usr/src/paperless/consume
    storageClass: "rook-nfs"
    accessMode: ReadWriteMany
    size: 1Gi

postgresql:
  enabled: false
  auth:
    database: paperless
    postgresPassword: changeme
  primary:
    persistence:
      enabled: false
      # storageClass: ""
      # size: 8Gi

mariadb:
  enabled: false
  auth:
    database: paperless
    username: paperless
    password: changeme
    rootPassword: changeme
  primary:
    persistence:
      enabled: false
      # storageClass: ""
      # size: 8Gi

redis:
  enabled: false 
  auth:
    enabled: true
    username: ""
  port: 6379 # Set the Redis port
 under the hood
  master:
    persistence:
      enabled: false
  replica:
    replicaCount: 0

if it's a bug I hope the community could fix it on the mentioned image tag.
I'm ready to provide more info if required.
Thanks.

### Steps to reproduce

Create a new MariaDB Database.
Reference the DB in the Helm chart
run the command: helm install paperless-release-01 .
kubectl logs pod name --follow

### Webserver logs

```bash
Paperless-ngx docker container starting...
Creating directory scratch directory /tmp/paperless
mkdir: created directory '/tmp/paperless'
Adjusting permissions of paperless files. This may take a while.
Waiting for MariaDB to start...
Connected to MariaDB
Waiting for Redis...
Connected to Redis broker.
Apply database migrations...
Operations to perform:
  Apply all migrations: account, admin, auditlog, auth, authtoken, contenttypes, django_celery_results, documents, guardian, paperless, paperless_mail, sessions, socialaccount
Running migrations:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 103, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/mysql/base.py", line 76, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/usr/local/lib/python3.12/site-packages/MySQLdb/connections.py", line 261, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1050, "Table 'documents_comment' already exists")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 107, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/management/commands/migrate.py", line 357, in handle
    post_migrate_state = executor.migrate(
                         ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/migrations/executor.py", line 255, in apply_migration
    state = migration.apply(state, schema_editor)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/migrations/migration.py", line 132, in apply
    operation.database_forwards(
  File "/usr/local/lib/python3.12/site-packages/django/db/migrations/operations/models.py", line 97, in database_forwards
    schema_editor.create_model(model)
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/schema.py", line 505, in create_model
    self.execute(sql, params or None)
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/schema.py", line 202, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 103, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/mysql/base.py", line 76, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/usr/local/lib/python3.12/site-packages/MySQLdb/connections.py", line 261, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1050, "Table 'documents_comment' already exists")
  Applying documents.1022_paperlesstask_squashed_1036_alter_savedviewfilterrule_rule_type...
```

### Paperless-ngx version

2.13.5

### Host OS

Ubuntu 24.04 k8s version v1.31.1

### Installation method

Other (please describe above)

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by mr-elamin** [comment]
I confirm the installation works very smoothly when I do not use any DB engine.
but this is very strange behavior.
