### ISSUE TITLE
[BUG] Can not add mail server to paperless-ngx (unexpected response)

### ISSUE THREAD

**Issue by Brice187** [paperless-ngx/paperless-ngx#8395]
### Description

![image](https://github.com/user-attachments/assets/7ebadb07-513d-43b1-a96e-8ddd1d38b5bc)

```
[2024-11-30 16:42:54,220] [ERROR] [django.request] Internal Server Error: /api/mail_accounts/test/
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/paperless/src/paperless_mail/views.py", line 70, in post
    with get_mailbox(
         ^^^^^^^^^^^^
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 417, in get_mailbox
    mailbox = MailBoxTls(server, port, ssl_context=ssl_context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/imap_tools/mailbox.py", line 353, in __init__
    super().__init__()
  File "/usr/local/lib/python3.12/site-packages/imap_tools/mailbox.py", line 33, in __init__
    self.client = self._get_mailbox_client()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/imap_tools/mailbox.py", line 361, in _get_mailbox_client
    client = imaplib.IMAP4(self._host, self._port, timeout=self._timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/imaplib.py", line 205, in __init__
    self._connect()
  File "/usr/local/lib/python3.12/imaplib.py", line 247, in _connect
    self.welcome = self._get_response()
                   ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/imaplib.py", line 1104, in _get_response
    raise self.abort("unexpected response: %r" % resp)
imaplib.IMAP4.abort: unexpected response: b'220 layka.disroot.org ESMTP (Debian)'
```

### Steps to reproduce

Add mailserver disrupt.org

### Webserver logs

```bash
see problem description
```

### Paperless-ngx version

2.13.5

### Host OS

Debian

### Installation method

Other (please describe above)

### System status

```json
Kubernetes 1.31.1
```

### Browser

Safari

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
This is clearly a problem with the mail server you are connecting to.   As you can see, the error is coming from Python's standard IMAP library, which is well tested and not going to be wrong 

If you are hosting the server, check settings, otherwise contact your hoster.

**Comment by shamoon** [comment]
Ha. Yea the point of the test button is to test, not open a bug report if your mail server work...

**Comment by stumpylog** [comment]
Quick Google tells me you're connected to SMTP not IMAP
