### ISSUE TITLE
2006, 'Server has gone away'

### ISSUE THREAD

**Issue by m0wlheld** [paperless-ngx/paperless-ngx#8418]
I see some issues and at least one discussion, regarding topic "2006, 'Server has gone away'". All of them are closed, some are marked as being not a bug. However, I am facing this issue as well when using paperless-ngx via docker compose, but using an external MariaDB instance. 

It happens predictable, when processing a PDF takes some time. In my case when analysing a PDF attachment from an E-Mail being retrieved by a workflow.

**Comment by m0wlheld** [comment]
Attached, please find the error messages printed. Since the error occurs after processing, when storing metadata into database, the document is not accessible from the Paperless frontend.

```
[2024-12-03 15:44:01,105] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-w4e01p_e

[2024-12-03 15:44:01,106] [ERROR] [paperless.tasks] ConsumeTaskPlugin failed: F2_3004283968.PDF: The following error occurred while storing document F2_3004283968.PDF after parsing: (2013, 'Lost connection to server during query')

Traceback (most recent call last):

  File "/usr/local/lib/python3.12/site-packages/django/db/backends/mysql/base.py", line 298, in _set_autocommit

    self.connection.autocommit(autocommit)

  File "/usr/local/lib/python3.12/site-packages/MySQLdb/connections.py", line 246, in autocommit

    _mysql.connection.autocommit(self, on)

MySQLdb.OperationalError: (2013, 'Lost connection to server during query')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/local/lib/python3.12/site-packages/asgiref/sync.py", line 327, in main_wrap

    raise exc_info[1]

  File "/usr/src/paperless/src/documents/consumer.py", line 543, in run

    with transaction.atomic():

         ^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/django/db/transaction.py", line 216, in __enter__

    connection.set_autocommit(

  File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 487, in set_autocommit

    self._set_autocommit(autocommit)

  File "/usr/local/lib/python3.12/site-packages/django/db/backends/mysql/base.py", line 297, in _set_autocommit

    with self.wrap_database_errors:

         ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__

    raise dj_exc_value.with_traceback(traceback) from exc_value

  File "/usr/local/lib/python3.12/site-packages/django/db/backends/mysql/base.py", line 298, in _set_autocommit

    self.connection.autocommit(autocommit)

  File "/usr/local/lib/python3.12/site-packages/MySQLdb/connections.py", line 246, in autocommit

    _mysql.connection.autocommit(self, on)

django.db.utils.OperationalError: (2013, 'Lost connection to server during query')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/tasks.py", line 148, in consume_file

    msg = plugin.run()

          ^^^^^^^^^^^^

  File "/usr/src/paperless/src/documents/consumer.py", line 622, in run

    self._fail(

  File "/usr/src/paperless/src/documents/consumer.py", line 151, in _fail

    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception

documents.consumer.ConsumerError: F2_3004283968.PDF: The following error occurred while storing document F2_3004283968.PDF after parsing: (2013, 'Lost connection to server during query')

[2024-12-03 15:44:01,128] [ERROR] [paperless.handlers] Updating PaperlessTask failed

Traceback (most recent call last):

  File "/usr/local/lib/python3.12/site-packages/django/db/backends/mysql/base.py", line 298, in _set_autocommit

    self.connection.autocommit(autocommit)

  File "/usr/local/lib/python3.12/site-packages/MySQLdb/connections.py", line 246, in autocommit

    _mysql.connection.autocommit(self, on)

MySQLdb.OperationalError: (2013, 'Lost connection to server during query')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/local/lib/python3.12/site-packages/asgiref/sync.py", line 327, in main_wrap

    raise exc_info[1]

  File "/usr/src/paperless/src/documents/consumer.py", line 543, in run

    with transaction.atomic():

         ^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/django/db/transaction.py", line 216, in __enter__

    connection.set_autocommit(

  File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 487, in set_autocommit

    self._set_autocommit(autocommit)

  File "/usr/local/lib/python3.12/site-packages/django/db/backends/mysql/base.py", line 297, in _set_autocommit

    with self.wrap_database_errors:

         ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__

    raise dj_exc_value.with_traceback(traceback) from exc_value

  File "/usr/local/lib/python3.12/site-packages/django/db/backends/mysql/base.py", line 298, in _set_autocommit

    self.connection.autocommit(autocommit)

  File "/usr/local/lib/python3.12/site-packages/MySQLdb/connections.py", line 246, in autocommit

    _mysql.connection.autocommit(self, on)

django.db.utils.OperationalError: (2013, 'Lost connection to server during query')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/local/lib/python3.12/site-packages/celery/app/trace.py", line 453, in trace_task

    R = retval = fun(*args, **kwargs)

                 ^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/celery/app/trace.py", line 736, in __protected_call__

    return self.run(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/asgiref/sync.py", line 327, in main_wrap

    raise exc_info[1]

  File "/usr/src/paperless/src/documents/tasks.py", line 148, in consume_file

    msg = plugin.run()

          ^^^^^^^^^^^^

  File "/usr/src/paperless/src/documents/consumer.py", line 622, in run

    self._fail(

  File "/usr/src/paperless/src/documents/consumer.py", line 151, in _fail

    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception

documents.consumer.ConsumerError: F2_3004283968.PDF: The following error occurred while storing document F2_3004283968.PDF after parsing: (2013, 'Lost connection to server during query')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute

    return self.cursor.execute(sql, params)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/django/db/backends/mysql/base.py", line 76, in execute

    return self.cursor.execute(query, args)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute

    res = self._query(mogrified_query)

          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query

    db.query(q)

  File "/usr/local/lib/python3.12/site-packages/MySQLdb/connections.py", line 261, in query

    _mysql.connection.query(self, query)

MySQLdb.OperationalError: (2006, 'Server has gone away')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/local/lib/python3.12/site-packages/celery/app/trace.py", line 470, in trace_task

    I, R, state, retval = on_error(task_request, exc)

                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/celery/app/trace.py", line 381, in on_error

    R = I.handle_error_state(

        ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/celery/app/trace.py", line 175, in handle_error_state

    return {

           ^

  File "/usr/local/lib/python3.12/site-packages/celery/app/trace.py", line 227, in handle_failure

    task.backend.mark_as_failure(

  File "/usr/local/lib/python3.12/site-packages/celery/backends/base.py", line 167, in mark_as_failure

    self.store_result(task_id, exc, state,

  File "/usr/local/lib/python3.12/site-packages/celery/backends/base.py", line 526, in store_result

    self._store_result(task_id, result, state, traceback,

  File "/usr/local/lib/python3.12/site-packages/django_celery_results/backends/database.py", line 147, in _store_result

    self.TaskModel._default_manager.store_result(**task_props)

  File "/usr/local/lib/python3.12/site-packages/django_celery_results/managers.py", line 42, in _inner

    return fun(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/django_celery_results/managers.py", line 164, in store_result

    obj, created = self.using(using).get_or_create(task_id=task_id,

                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 948, in get_or_create

    return self.get(**kwargs), False

           ^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 645, in get

    num = len(clone)

          ^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 382, in __len__

    self._fetch_all()

  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1928, in _fetch_all

    self._result_cache = list(self._iterable_class(self))

                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__

    results = compiler.execute_sql(

              ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql

    cursor.execute(sql, params)

  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute

    return self._execute_with_wrappers(

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers

    return executor(sql, params, many, context)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute

    with self.db.wrap_database_errors:

         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__

    raise dj_exc_value.with_traceback(traceback) from exc_value

  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute

    return self.cursor.execute(sql, params)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/django/db/backends/mysql/base.py", line 76, in execute

    return self.cursor.execute(query, args)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute

    res = self._query(mogrified_query)

          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query

    db.query(q)

  File "/usr/local/lib/python3.12/site-packages/MySQLdb/connections.py", line 261, in query

    _mysql.connection.query(self, query)

django.db.utils.OperationalError: (2006, 'Server has gone away')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute

    return self.cursor.execute(sql, params)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/django/db/backends/mysql/base.py", line 76, in execute

    return self.cursor.execute(query, args)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute

    res = self._query(mogrified_query)

          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query

    db.query(q)

  File "/usr/local/lib/python3.12/site-packages/MySQLdb/connections.py", line 261, in query

    _mysql.connection.query(self, query)

MySQLdb.IntegrityError: (1048, "Column 'status' cannot be null")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/signals/handlers.py", line 1006, in task_postrun_handler

    task_instance.save()

  File "/usr/local/lib/python3.12/site-packages/django/db/models/base.py", line 891, in save

    self.save_base(

  File "/usr/local/lib/python3.12/site-packages/django/db/models/base.py", line 997, in save_base

    updated = self._save_table(

              ^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/django/db/models/base.py", line 1129, in _save_table

    updated = self._do_update(

              ^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/django/db/models/base.py", line 1194, in _do_update

    return filtered._update(values) > 0

           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1278, in _update

    return query.get_compiler(self.db).execute_sql(CURSOR)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 2003, in execute_sql

    cursor = super().execute_sql(result_type)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql

    cursor.execute(sql, params)

  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute

    return self._execute_with_wrappers(

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers

    return executor(sql, params, many, context)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute

    with self.db.wrap_database_errors:

         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__

    raise dj_exc_value.with_traceback(traceback) from exc_value

  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute

    return self.cursor.execute(sql, params)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/django/db/backends/mysql/base.py", line 76, in execute

    return self.cursor.execute(query, args)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute

    res = self._query(mogrified_query)

          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query

    db.query(q)

  File "/usr/local/lib/python3.12/site-packages/MySQLdb/connections.py", line 261, in query

    _mysql.connection.query(self, query)

django.db.utils.IntegrityError: (1048, "Column 'status' cannot be null")
```
