### ISSUE TITLE
[BUG] Can't merge two documents that were originally uploaded as JPEGs

### ISSUE THREAD

**Issue by niklaswa** [paperless-ngx/paperless-ngx#8531]
### Description

Currently when uploading two documents in JPEG format, those documents are converted to PDFs correctly.
When trying to merge two of those documents together, it seems like the application is trying to merge the JPEG files together which fails.

### Steps to reproduce

- Upload two JPEG documents
- Merge them together

### Webserver logs

```bash
[2024-12-21 11:53:10,972] [INFO] [paperless.consumer] Consuming Scan_20241219.jpg
[2024-12-21 11:53:10,974] [DEBUG] [paperless.consumer] Detected mime type: image/jpeg
[2024-12-21 11:53:10,983] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser
[2024-12-21 11:53:10,987] [DEBUG] [paperless.consumer] Parsing Scan_20241219.jpg...
[2024-12-21 11:53:11,309] [DEBUG] [paperless.parsing.tesseract] Estimated DPI 290 based on image width 2400
[2024-12-21 11:53:11,309] [DEBUG] [paperless.parsing.tesseract] Detected DPI for image /tmp/paperless/paperless-ngxmg6m1c_b/Scan_20241219.jpg: 300
[2024-12-21 11:53:11,310] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-ngxmg6m1c_b/Scan_20241219.jpg'), 'output_file': PosixPath('/tmp/paperless/paperless-84fla1f9/archive.pdf'), 'use_threads': True, 'jobs': 4, 'language': 'deu', 'output_type': 'pdfa', 'progress_bar': False, 'color_conversion_strategy': 'RGB', 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-84fla1f9/sidecar.txt'), 'image_dpi': 300}
[2024-12-21 11:53:11,525] [INFO] [ocrmypdf._pipeline] Input file is not a PDF, checking if it is an image...
[2024-12-21 11:53:11,525] [INFO] [ocrmypdf._pipeline] Input file is an image
[2024-12-21 11:53:11,526] [INFO] [ocrmypdf._pipeline] Input image has no ICC profile, assuming sRGB
[2024-12-21 11:53:11,526] [INFO] [ocrmypdf._pipeline] Image seems valid. Try converting to PDF...
[2024-12-21 11:53:11,530] [INFO] [ocrmypdf._pipeline] Successfully converted to PDF, processing...
[2024-12-21 11:53:13,545] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 12.36 - rotation appears correct
[2024-12-21 11:53:23,454] [INFO] [ocrmypdf._pipelines.ocr] Postprocessing...
[2024-12-21 11:53:24,207] [INFO] [ocrmypdf._pipeline] Image optimization ratio: 1.38 savings: 27.8%
[2024-12-21 11:53:24,207] [INFO] [ocrmypdf._pipeline] Total file size ratio: 0.81 savings: -23.7%
[2024-12-21 11:53:24,210] [INFO] [ocrmypdf._pipelines._common] Output file is a PDF/A-2B (as expected)
[2024-12-21 11:53:24,536] [DEBUG] [paperless.parsing.tesseract] Using text from sidecar file
[2024-12-21 11:53:24,537] [DEBUG] [paperless.consumer] Generating thumbnail for Scan_20241219.jpg...
[2024-12-21 11:53:24,541] [DEBUG] [paperless.parsing] Execute: convert -density 300 -scale 500x5000> -alpha remove -strip -auto-orient -define pdf:use-cropbox=true /tmp/paperless/paperless-84fla1f9/archive.pdf[0] /tmp/paperless/paperless-84fla1f9/convert.webp
[2024-12-21 11:53:25,873] [INFO] [paperless.parsing] convert exited 0
[2024-12-21 11:53:26,581] [DEBUG] [paperless.consumer] Saving record to database
[2024-12-21 11:53:26,582] [DEBUG] [paperless.consumer] Creation date from parse_date: 2023-01-01 00:00:00+01:00
[2024-12-21 11:53:27,849] [DEBUG] [paperless.consumer] Deleting file /tmp/paperless/paperless-ngxmg6m1c_b/Scan_20241219.jpg
[2024-12-21 11:53:27,891] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-84fla1f9
[2024-12-21 11:53:27,892] [INFO] [paperless.consumer] Document Scan_20241219 consumption finished
[2024-12-21 11:53:27,898] [INFO] [paperless.tasks] ConsumeTaskPlugin completed with: Success. New document id 115 created
[2024-12-21 11:53:28,412] [DEBUG] [paperless.tasks] Skipping plugin CollatePlugin
[2024-12-21 11:53:28,413] [DEBUG] [paperless.tasks] Skipping plugin BarcodePlugin
[2024-12-21 11:53:28,413] [DEBUG] [paperless.tasks] Executing plugin WorkflowTriggerPlugin
[2024-12-21 11:53:28,415] [INFO] [paperless.tasks] WorkflowTriggerPlugin completed with:
[2024-12-21 11:53:28,416] [DEBUG] [paperless.tasks] Executing plugin ConsumeTaskPlugin
[2024-12-21 11:53:28,426] [INFO] [paperless.consumer] Consuming Scan_20241219_2.jpg
[2024-12-21 11:53:28,428] [DEBUG] [paperless.consumer] Detected mime type: image/jpeg
[2024-12-21 11:53:28,434] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser
[2024-12-21 11:53:28,437] [DEBUG] [paperless.consumer] Parsing Scan_20241219_2.jpg...
[2024-12-21 11:53:28,714] [DEBUG] [paperless.parsing.tesseract] Estimated DPI 290 based on image width 2400
[2024-12-21 11:53:28,714] [DEBUG] [paperless.parsing.tesseract] Detected DPI for image /tmp/paperless/paperless-ngxkg75rf2w/Scan_20241219_2.jpg: 300
[2024-12-21 11:53:28,714] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-ngxkg75rf2w/Scan_20241219_2.jpg'), 'output_file': PosixPath('/tmp/paperless/paperless-plu_0sqh/archive.pdf'), 'use_threads': True, 'jobs': 4, 'language': 'deu', 'output_type': 'pdfa', 'progress_bar': False, 'color_conversion_strategy': 'RGB', 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-plu_0sqh/sidecar.txt'), 'image_dpi': 300}
[2024-12-21 11:53:28,890] [INFO] [ocrmypdf._pipeline] Input file is not a PDF, checking if it is an image...
[2024-12-21 11:53:28,891] [INFO] [ocrmypdf._pipeline] Input file is an image
[2024-12-21 11:53:28,891] [INFO] [ocrmypdf._pipeline] Input image has no ICC profile, assuming sRGB
[2024-12-21 11:53:28,892] [INFO] [ocrmypdf._pipeline] Image seems valid. Try converting to PDF...
[2024-12-21 11:53:28,896] [INFO] [ocrmypdf._pipeline] Successfully converted to PDF, processing...
[2024-12-21 11:53:31,126] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 8.32 - no change
[2024-12-21 11:53:43,470] [WARNING] [ocrmypdf._exec.tesseract] [tesseract] lots of diacritics - possibly poor OCR
[2024-12-21 11:53:43,534] [INFO] [ocrmypdf._pipelines.ocr] Postprocessing...
[2024-12-21 11:53:44,485] [INFO] [ocrmypdf._pipeline] Image optimization ratio: 1.22 savings: 18.3%
[2024-12-21 11:53:44,486] [INFO] [ocrmypdf._pipeline] Total file size ratio: 0.61 savings: -62.9%
[2024-12-21 11:53:44,488] [INFO] [ocrmypdf._pipelines._common] Output file is a PDF/A-2B (as expected)
[2024-12-21 11:53:44,906] [WARNING] [ocrmypdf._validation] The output file size is 1.64× larger than the input file.
Possible reasons for this include:
--deskew was issued, causing transcoding.
PDF/A conversion was enabled. (Try `--output-type pdf`.)

[2024-12-21 11:53:44,910] [DEBUG] [paperless.parsing.tesseract] Using text from sidecar file
[2024-12-21 11:53:44,911] [DEBUG] [paperless.consumer] Generating thumbnail for Scan_20241219_2.jpg...
[2024-12-21 11:53:44,915] [DEBUG] [paperless.parsing] Execute: convert -density 300 -scale 500x5000> -alpha remove -strip -auto-orient -define pdf:use-cropbox=true /tmp/paperless/paperless-plu_0sqh/archive.pdf[0] /tmp/paperless/paperless-plu_0sqh/convert.webp
[2024-12-21 11:53:46,503] [INFO] [paperless.parsing] convert exited 0
[2024-12-21 11:53:47,152] [DEBUG] [paperless.consumer] Saving record to database
[2024-12-21 11:53:47,153] [DEBUG] [paperless.consumer] Creation date from parse_date: 2023-01-01 00:00:00+01:00
[2024-12-21 11:53:48,316] [DEBUG] [paperless.consumer] Deleting file /tmp/paperless/paperless-ngxkg75rf2w/Scan_20241219_2.jpg
[2024-12-21 11:53:48,340] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-plu_0sqh
[2024-12-21 11:53:48,341] [INFO] [paperless.consumer] Document Scan_20241219_2 consumption finished
[2024-12-21 11:53:48,346] [INFO] [paperless.tasks] ConsumeTaskPlugin completed with: Success. New document id 116 created
[2024-12-21 11:54:13,616] [INFO] [paperless.bulk_edit] Attempting to merge 2 documents into a single document.
[2024-12-21 11:54:13,653] [ERROR] [paperless.bulk_edit] Error merging document 115, it will not be included in the merge: /share/paperless/media/documents/originals/2023/xxxxxxxxx/Scan_20241219.jpg: unable to find trailer dictionary while recovering damaged file
Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/bulk_edit.py", line 268, in merge
    with pikepdf.open(str(doc.source_path)) as pdf:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pikepdf/_methods.py", line 399, in open
    pdf = Pdf._open(
          ^^^^^^^^^^
pikepdf._core.PdfError: /share/paperless/media/documents/originals/2023/xxxxxxxxx/Scan_20241219.jpg: unable to find trailer dictionary while recovering damaged file
[2024-12-21 11:54:13,687] [ERROR] [paperless.bulk_edit] Error merging document 116, it will not be included in the merge: /share/paperless/media/documents/originals/2023/xxxxxxxxx/Scan_20241219_2.jpg: unable to find trailer dictionary while recovering damaged file
Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/bulk_edit.py", line 268, in merge
    with pikepdf.open(str(doc.source_path)) as pdf:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pikepdf/_methods.py", line 399, in open
    pdf = Pdf._open(
          ^^^^^^^^^^
pikepdf._core.PdfError: /share/paperless/media/documents/originals/2023/xxxxxxxxx/Scan_20241219_2.jpg: unable to find trailer dictionary while recovering damaged file
[2024-12-21 11:54:13,687] [WARNING] [paperless.bulk_edit] No documents were merged
```

### Paperless-ngx version

2.13.5

### Host OS

Linux-6.6.66-haos-x86_64-with-glibc2.36

### Installation method

Other (please describe above)

### System status

```json
{
    "pngx_version": "2.13.5",
    "server_os": "Linux-6.6.66-haos-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 33058951168,
        "available": 1565749248
    },
    "database": {
        "type": "sqlite",
        "url": "/config/data/db.sqlite3",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "paperless_mail.0028_alter_mailaccount_password_and_more",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://localhost:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-12-21T11:53:48.296834+01:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-12-21T10:05:00.388760Z",
        "classifier_error": null
    }
}
```

### Browser

Chrome on macOS

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
Merging happens against the originals, not the archives.  Merging anything except PDF is not supported, as clearly indicated in the UI.

**Comment by niklaswa** [comment]
Oh okay - well, not clear enough it seems 😅 

A good approach would be to grey out the button when attempting to merge two incompatible documents, forcing the user to remove those documents from the selection. Simply excluding incompatible documents in the process is not very transparent and doesn't align with the behavior the user expects from the application when submitting this task.
