### ISSUE TITLE
Document view on  Documents page not showing

### ISSUE THREAD

**Issue by blogdemoi** [paperless-ngx/paperless-ngx#892]
### Description

When on the Documents page, the documents preview (vignettes) are not showing (please, see screenshot below). I tried in Firefox 100 and Brave with the same results. However it used to work before, so I guess one of my updates broke something...
![2022-Friday-May-22-12-06](https://user-images.githubusercontent.com/83965802/167210246-56858036-651f-42c6-9683-7ff8a74e1a05.png)

I installed Paperless-ngx from  this AUR package https://aur.archlinux.org/packages/paperless-ngx on my Manjaro laptop Xfce (no server, just local install)

### Steps to reproduce

NA

### Paperless-ngx version

Paperless-ngx 1.6.0 

### Host OS

Manjaro Xfce

### Installation method

Other (please describe above)

### Browser

Firefox, Brave

**Comment by shamoon** [comment]
Please check your logs, browser console etc and provide if needed. I do not expect this is an actual bug but rather something specific to your environment

**Comment by amo13** [comment]
I can reproduce it, but I agree with @shamoon. This certainly is something with the setup on archlinux. I'll see what I can do.

**Comment by amo13** [comment]
This happened after an system update. Django 4 is the culprit here. I guess that paperless is not yet ready for django 4. Downgrading django to 3.2.10 on archlinux works around the issue for now.

Here is the log of the gunicorn webserver for reference:
```
May 07 09:34:21 archvm gunicorn[432]: [2022-05-07 07:34:21,348] [ERROR] [django.request] Internal Server Error: /api/documents/1/thumb/
May 07 09:34:21 archvm gunicorn[432]: Traceback (most recent call last):
May 07 09:34:21 archvm gunicorn[432]:   File "/usr/lib/python3.10/site-packages/asgiref/sync.py", line 451, in thread_handler
May 07 09:34:21 archvm gunicorn[432]:     raise exc_info[1]
May 07 09:34:21 archvm gunicorn[432]:   File "/usr/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner
May 07 09:34:21 archvm gunicorn[432]:     response = await get_response(request)
May 07 09:34:21 archvm gunicorn[432]:   File "/usr/lib/python3.10/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
May 07 09:34:21 archvm gunicorn[432]:     response = await wrapped_callback(
May 07 09:34:21 archvm gunicorn[432]:   File "/usr/lib/python3.10/site-packages/asgiref/sync.py", line 414, in __call__
May 07 09:34:21 archvm gunicorn[432]:     ret = await asyncio.wait_for(future, timeout=None)
May 07 09:34:21 archvm gunicorn[432]:   File "/usr/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
May 07 09:34:21 archvm gunicorn[432]:     return await fut
May 07 09:34:21 archvm gunicorn[432]:   File "/usr/lib/python3.10/site-packages/asgiref/current_thread_executor.py", line 22, in run
May 07 09:34:21 archvm gunicorn[432]:     result = self.fn(*self.args, **self.kwargs)
May 07 09:34:21 archvm gunicorn[432]:   File "/usr/lib/python3.10/site-packages/asgiref/sync.py", line 455, in thread_handler
May 07 09:34:21 archvm gunicorn[432]:     return func(*args, **kwargs)
May 07 09:34:21 archvm gunicorn[432]:   File "/usr/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
May 07 09:34:21 archvm gunicorn[432]:     return view_func(*args, **kwargs)
May 07 09:34:21 archvm gunicorn[432]:   File "/usr/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
May 07 09:34:21 archvm gunicorn[432]:     return self.dispatch(request, *args, **kwargs)
May 07 09:34:21 archvm gunicorn[432]:   File "/usr/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
May 07 09:34:21 archvm gunicorn[432]:     response = self.handle_exception(exc)
May 07 09:34:21 archvm gunicorn[432]:   File "/usr/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
May 07 09:34:21 archvm gunicorn[432]:     self.raise_uncaught_exception(exc)
May 07 09:34:21 archvm gunicorn[432]:   File "/usr/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
May 07 09:34:21 archvm gunicorn[432]:     raise exc
May 07 09:34:21 archvm gunicorn[432]:   File "/usr/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
May 07 09:34:21 archvm gunicorn[432]:     response = handler(request, *args, **kwargs)
May 07 09:34:21 archvm gunicorn[432]:   File "/usr/lib/python3.10/site-packages/django/views/decorators/cache.py", line 35, in _cache_controlled
May 07 09:34:21 archvm gunicorn[432]:     raise TypeError(
May 07 09:34:21 archvm gunicorn[432]: TypeError: cache_control didn't receive an HttpRequest. If you are decorating a classmethod, be sure to use @method_decorator.
May 07 09:34:21 archvm gunicorn[432]: [2022-05-07 07:34:21,353] [ERROR] [django.request] Internal Server Error: /api/documents/2/thumb/
May 07 09:34:21 archvm gunicorn[432]: Traceback (most recent call last):
May 07 09:34:21 archvm gunicorn[432]:   File "/usr/lib/python3.10/site-packages/asgiref/sync.py", line 451, in thread_handler
May 07 09:34:21 archvm gunicorn[432]:     raise exc_info[1]
May 07 09:34:21 archvm gunicorn[432]:   File "/usr/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner
May 07 09:34:21 archvm gunicorn[432]:     response = await get_response(request)
May 07 09:34:21 archvm gunicorn[432]:   File "/usr/lib/python3.10/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
May 07 09:34:21 archvm gunicorn[432]:     response = await wrapped_callback(
May 07 09:34:21 archvm gunicorn[432]:   File "/usr/lib/python3.10/site-packages/asgiref/sync.py", line 414, in __call__
May 07 09:34:21 archvm gunicorn[432]:     ret = await asyncio.wait_for(future, timeout=None)
May 07 09:34:21 archvm gunicorn[432]:   File "/usr/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
May 07 09:34:21 archvm gunicorn[432]:     return await fut
May 07 09:34:21 archvm gunicorn[432]:   File "/usr/lib/python3.10/site-packages/asgiref/current_thread_executor.py", line 22, in run
May 07 09:34:21 archvm gunicorn[432]:     result = self.fn(*self.args, **self.kwargs)
May 07 09:34:21 archvm gunicorn[432]:   File "/usr/lib/python3.10/site-packages/asgiref/sync.py", line 455, in thread_handler
May 07 09:34:21 archvm gunicorn[432]:     return func(*args, **kwargs)
May 07 09:34:21 archvm gunicorn[432]:   File "/usr/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
May 07 09:34:21 archvm gunicorn[432]:     return view_func(*args, **kwargs)
May 07 09:34:21 archvm gunicorn[432]:   File "/usr/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
May 07 09:34:21 archvm gunicorn[432]:     return self.dispatch(request, *args, **kwargs)
May 07 09:34:21 archvm gunicorn[432]:   File "/usr/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
May 07 09:34:21 archvm gunicorn[432]:     response = self.handle_exception(exc)
May 07 09:34:21 archvm gunicorn[432]:   File "/usr/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
May 07 09:34:21 archvm gunicorn[432]:     self.raise_uncaught_exception(exc)
May 07 09:34:21 archvm gunicorn[432]:   File "/usr/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
May 07 09:34:21 archvm gunicorn[432]:     raise exc
May 07 09:34:21 archvm gunicorn[432]:   File "/usr/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
May 07 09:34:21 archvm gunicorn[432]:     response = handler(request, *args, **kwargs)
May 07 09:34:21 archvm gunicorn[432]:   File "/usr/lib/python3.10/site-packages/django/views/decorators/cache.py", line 35, in _cache_controlled
May 07 09:34:21 archvm gunicorn[432]:     raise TypeError(
May 07 09:34:21 archvm gunicorn[432]: TypeError: cache_control didn't receive an HttpRequest. If you are decorating a classmethod, be sure to use @method_decorator.
May 07 09:35:40 archvm gunicorn[339]: [2022-05-07 07:35:40 +0000] [339] [CRITICAL] WORKER TIMEOUT (pid:431)
```

**Comment by amo13** [comment]
Actually, sorry for the confusion: Paperless 1.7.0 *is* working fine with django 4. It is 1.6.0 that does not and the version in the AUR still is 1.6.0 at the moment. I am working on pushing the update to 1.7.0 to the AUR right now. It should land there very soon.

In the meantime, I guess that this issue can be closed.

**Comment by blogdemoi** [comment]
> Paperless 1.7.0 _is_ working fine with django 4.

Thank you, I just upgraded to 1.7.0, image vignettes are ok now.
