### ISSUE TITLE
[BUG] PSSyntaxError: Invalid dictionary construct

### ISSUE THREAD

**Issue by stepanov1975** [paperless-ngx/paperless-ngx#900]
### Description

I currently have a couple of documents that paperless failing to consume.

### Steps to reproduce

1. Document added via UI
2. Paperless fails to consume it

### Webserver logs

```bash
[2022-05-09 15:33:27,686] [INFO] [paperless.consumer] Consuming 1.pdf

[2022-05-09 15:33:27,687] [DEBUG] [paperless.consumer] Detected mime type: application/pdf

[2022-05-09 15:33:27,687] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser

[2022-05-09 15:33:27,690] [DEBUG] [paperless.consumer] Parsing 1.pdf...

[2022-05-09 15:33:27,708] [WARNING] [paperless.parsing.tesseract] Error while getting text from PDF document with pdfminer.six

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 120, in extract_text

    stripped = post_process_text(pdfminer_extract_text(pdf_file))

  File "/usr/local/lib/python3.9/site-packages/pdfminer/high_level.py", line 164, in extract_text

    interpreter.process_page(page)

  File "/usr/local/lib/python3.9/site-packages/pdfminer/pdfinterp.py", line 991, in process_page

    self.render_contents(page.resources, page.contents, ctm=ctm)

  File "/usr/local/lib/python3.9/site-packages/pdfminer/pdfinterp.py", line 1008, in render_contents

    self.init_resources(resources)

  File "/usr/local/lib/python3.9/site-packages/pdfminer/pdfinterp.py", line 384, in init_resources

    self.fontmap[fontid] = self.rsrcmgr.get_font(objid, spec)

  File "/usr/local/lib/python3.9/site-packages/pdfminer/pdfinterp.py", line 216, in get_font

    font = PDFType1Font(self, spec)

  File "/usr/local/lib/python3.9/site-packages/pdfminer/pdffont.py", line 998, in __init__

    PDFSimpleFont.__init__(self, descriptor, widths, spec)

  File "/usr/local/lib/python3.9/site-packages/pdfminer/pdffont.py", line 963, in __init__

    CMapParser(self.unicode_map, BytesIO(strm.get_data())).run()

  File "/usr/local/lib/python3.9/site-packages/pdfminer/cmapdb.py", line 292, in run

    self.nextobject()

  File "/usr/local/lib/python3.9/site-packages/pdfminer/psparser.py", line 630, in nextobject

    raise PSSyntaxError(error_msg)

pdfminer.psparser.PSSyntaxError: Invalid dictionary construct: [/'', /b'Registry', b'Adobe', /'', /b'Ordering', b'UCS', /'', /b'Supplement', 0]

[2022-05-09 15:33:27,752] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': '/tmp/paperless/paperless-upload-ypyidhb_', 'output_file': '/tmp/paperless/paperless-qpf0pm15/archive.pdf', 'use_threads': True, 'jobs': '2', 'language': 'heb+eng', 'output_type': 'pdfa', 'progress_bar': False, 'redo_ocr': True, 'clean': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': '/tmp/paperless/paperless-qpf0pm15/sidecar.txt'}

[2022-05-09 15:33:27,875] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-qpf0pm15

[2022-05-09 15:33:27,879] [ERROR] [paperless.consumer] Error while consuming document 1.pdf: PSSyntaxError: Invalid dictionary construct: [/'', /b'Registry', b'Adobe', /'', /b'Ordering', b'UCS', /'', /b'Supplement', 0]

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 261, in parse

    ocrmypdf.ocr(**args)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/api.py", line 337, in ocr

    return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 370, in run_pipeline

    pdfinfo = get_pdfinfo(

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 163, in get_pdfinfo

    return PdfInfo(

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 904, in __init__

    self._pages = _pdf_pageinfo_concurrent(

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 681, in _pdf_pageinfo_concurrent

    executor(

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_concurrent.py", line 82, in __call__

    self._execute(

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/builtin_plugins/concurrency.py", line 135, in _execute

    result = future.result()

  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result

    return self.__get_result()

  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result

    raise self._exception

  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run

    result = self.fn(*self.args, **self.kwargs)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 638, in _pdf_pageinfo_sync

    page = PageInfo(pdf, pageno, infile, check_pages, detailed_analysis)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 716, in __init__

    self._gather_pageinfo(pdf, pageno, infile, check_pages, detailed_analysis)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 735, in _gather_pageinfo

    miner = get_page_analysis(infile, pageno, pscript5_mode)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/pdfinfo/layout.py", line 245, in get_page_analysis

    interp.process_page(page)

  File "/usr/local/lib/python3.9/site-packages/pdfminer/pdfinterp.py", line 991, in process_page

    self.render_contents(page.resources, page.contents, ctm=ctm)

  File "/usr/local/lib/python3.9/site-packages/pdfminer/pdfinterp.py", line 1008, in render_contents

    self.init_resources(resources)

  File "/usr/local/lib/python3.9/site-packages/pdfminer/pdfinterp.py", line 384, in init_resources

    self.fontmap[fontid] = self.rsrcmgr.get_font(objid, spec)

  File "/usr/local/lib/python3.9/site-packages/pdfminer/pdfinterp.py", line 216, in get_font

    font = PDFType1Font(self, spec)

  File "/usr/local/lib/python3.9/site-packages/pdfminer/pdffont.py", line 998, in __init__

    PDFSimpleFont.__init__(self, descriptor, widths, spec)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/pdfinfo/layout.py", line 36, in PDFSimpleFont__init__

    original_PDFSimpleFont_init(self, descriptor, widths, spec)

  File "/usr/local/lib/python3.9/site-packages/pdfminer/pdffont.py", line 963, in __init__

    CMapParser(self.unicode_map, BytesIO(strm.get_data())).run()

  File "/usr/local/lib/python3.9/site-packages/pdfminer/cmapdb.py", line 292, in run

    self.nextobject()

  File "/usr/local/lib/python3.9/site-packages/pdfminer/psparser.py", line 630, in nextobject

    raise PSSyntaxError(error_msg)

pdfminer.psparser.PSSyntaxError: Invalid dictionary construct: [/'', /b'Registry', b'Adobe', /'', /b'Ordering', b'UCS', /'', /b'Supplement', 0]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/consumer.py", line 261, in try_consume_file

    document_parser.parse(self.path, mime_type, self.filename)

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 314, in parse

    raise ParseError(f"{e.__class__.__name__}: {str(e)}")

documents.parsers.ParseError: PSSyntaxError: Invalid dictionary construct: [/'', /b'Registry', b'Adobe', /'', /b'Ordering', b'UCS', /'', /b'Supplement', 0]
```

### Paperless-ngx version

1.7.0

### Host OS

Fedora 35

### Installation method

Docker

### Browser

Google chrome

### Configuration changes
```
PAPERLESS_OCR_LANGUAGE=heb+eng
PAPERLESS_FILENAME_FORMAT={document_type}/{created_year}/{created_month}/{tag_list}_{title}
PAPERLESS_OCR_MODE=redo
PAPERLESS_OCR_CLEAN=clean
PAPERLESS_TASK_WORKERS=2
PAPERLESS_THREADS_PER_WORKER=2
```

**Comment by stepanov1975** [comment]
Is it failing because of OCR? May be temporary fix it by catching exception and bypassing OCR? Just want documents inside Paperless. Sorry this intended to be in paperless

**Comment by stumpylog** [comment]
I think this is happening before OCR happens, when trying to get existing text.  You could try setting ocr to skip though, just in case

**Comment by stepanov1975** [comment]
> I think this is happening before OCR happens, when trying to get existing text. You could try setting ocr to skip though, just in case

So I think:
1. If PAPERLESS_OCR_MODE=redo is set paperless should not even try to get existing text unless OCR fails.
2. Anyway any problem should be caught and the document should be added to the database no matter what.

**Comment by stepanov1975** [comment]
Sorry to bother you, but is it a chance there will be a workaround for this problem? I am unable to get documents into paperless and it is very frustrating. I am sure there is a possibility to ignore error and consume the document without OCR.

**Comment by stumpylog** [comment]
I would attempt to run the problem file(s) through qpdf.  A command such as `qpdf --replace-input infile.pdf` would re-generate the file, and attempt to fix any issues it can.  If that would, setting it up as a pre-consume script would be simple enough.

**Comment by stumpylog** [comment]
Or if you can provide a sample file, it may be possible to force OCR and continue the processing with that content.
