### ISSUE TITLE
[BUG] Error 500/Mail fetching task false positive success. missing table: paperless_mail_mailrule_assign_tags

### ISSUE THREAD

**Issue by darkmattercoder** [paperless-ngx/paperless-ngx#936]
### Description

I wondered why my paperless-ngx did not import any e-mails in the last days. It might either be the case since I went from paperless-ng to ngx or only after upgrading from 1.6 to 1.7 a few days ago. I do not process that many e-mails usually.

First I noticed that all e-mail fetching jobs were listed as being successful. While trying to delete a rule or even an e-mail account I first ran into a `Server error (500)` 

In the logs, all e-mail related actions seem to trigger the missing table exception even the regularly scheduled mail fetching action, which is listed as being ran successfully in the task overview:

```
paperless-ngx    | 20:40:20 [Q] INFO Enqueued 1
paperless-ngx    | 20:40:20 [Q] INFO Process-1 created a task from schedule [Check all e-mail accounts]
paperless-ngx    | 20:40:20 [Q] INFO Process-1:2 processing [pennsylvania-network-kilo-comet]
paperless-ngx    | [2022-05-12 20:40:21,251] [ERROR] [paperless_mail] Rule account@mydomain.xyz.Scan-Mails: Error while processing mail 53: no such table: paperless_mail_mailrule_assign_tags
paperless-ngx    | Traceback (most recent call last):
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 89, in _execute
paperless-ngx    |     return self.cursor.execute(sql, params)
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/sqlite3/base.py", line 477, in execute
paperless-ngx    |     return Database.Cursor.execute(self, query, params)
paperless-ngx    | sqlite3.OperationalError: no such table: paperless_mail_mailrule_assign_tags
paperless-ngx    | 
paperless-ngx    | The above exception was the direct cause of the following exception:
paperless-ngx    | 
paperless-ngx    | Traceback (most recent call last):
paperless-ngx    |   File "/app/paperless/src/paperless_mail/mail.py", line 222, in handle_mail_rule
paperless-ngx    |     processed_files = self.handle_message(message, rule)
paperless-ngx    |   File "/app/paperless/src/paperless_mail/mail.py", line 269, in handle_message
paperless-ngx    |     tag_ids = [tag.id for tag in rule.assign_tags.all()]
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 320, in __iter__
paperless-ngx    |     self._fetch_all()
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 1507, in _fetch_all
paperless-ngx    |     self._result_cache = list(self._iterable_class(self))
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 57, in __iter__
paperless-ngx    |     results = compiler.execute_sql(
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1361, in execute_sql
paperless-ngx    |     cursor.execute(sql, params)
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 67, in execute
paperless-ngx    |     return self._execute_with_wrappers(
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
paperless-ngx    |     return executor(sql, params, many, context)
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 89, in _execute
paperless-ngx    |     return self.cursor.execute(sql, params)
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/django/db/utils.py", line 91, in __exit__
paperless-ngx    |     raise dj_exc_value.with_traceback(traceback) from exc_value
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 89, in _execute
paperless-ngx    |     return self.cursor.execute(sql, params)
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/sqlite3/base.py", line 477, in execute
paperless-ngx    |     return Database.Cursor.execute(self, query, params)
paperless-ngx    | django.db.utils.OperationalError: no such table: paperless_mail_mailrule_assign_tags
paperless-ngx    | [2022-05-12 20:40:21,294] [ERROR] [paperless_mail] Rule account@mydomain.xyz.Scan-Mails: Error while processing mail 54: no such table: paperless_mail_mailrule_assign_tags
paperless-ngx    | Traceback (most recent call last):
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 89, in _execute
paperless-ngx    |     return self.cursor.execute(sql, params)
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/sqlite3/base.py", line 477, in execute
paperless-ngx    |     return Database.Cursor.execute(self, query, params)
paperless-ngx    | sqlite3.OperationalError: no such table: paperless_mail_mailrule_assign_tags
paperless-ngx    | 
paperless-ngx    | The above exception was the direct cause of the following exception:
paperless-ngx    | 
paperless-ngx    | Traceback (most recent call last):
paperless-ngx    |   File "/app/paperless/src/paperless_mail/mail.py", line 222, in handle_mail_rule
paperless-ngx    |     processed_files = self.handle_message(message, rule)
paperless-ngx    |   File "/app/paperless/src/paperless_mail/mail.py", line 269, in handle_message
paperless-ngx    |     tag_ids = [tag.id for tag in rule.assign_tags.all()]
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 320, in __iter__
paperless-ngx    |     self._fetch_all()
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 1507, in _fetch_all
paperless-ngx    |     self._result_cache = list(self._iterable_class(self))
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 57, in __iter__
paperless-ngx    |     results = compiler.execute_sql(
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1361, in execute_sql
paperless-ngx    |     cursor.execute(sql, params)
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 67, in execute
paperless-ngx    |     return self._execute_with_wrappers(
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
paperless-ngx    |     return executor(sql, params, many, context)
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 89, in _execute
paperless-ngx    |     return self.cursor.execute(sql, params)
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/django/db/utils.py", line 91, in __exit__
paperless-ngx    |     raise dj_exc_value.with_traceback(traceback) from exc_value
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 89, in _execute
paperless-ngx    |     return self.cursor.execute(sql, params)
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/sqlite3/base.py", line 477, in execute
paperless-ngx    |     return Database.Cursor.execute(self, query, params)
paperless-ngx    | django.db.utils.OperationalError: no such table: paperless_mail_mailrule_assign_tags
paperless-ngx    | 20:40:21 [Q] INFO Process-1:2 stopped doing work
paperless-ngx    | 20:40:21 [Q] INFO Processed [pennsylvania-network-kilo-comet]
paperless-ngx    | 20:40:21 [Q] INFO recycled worker Process-1:2
paperless-ngx    | 20:40:21 [Q] INFO Process-1:6 ready for work at 997
 ```
Running in `linuxserver.io/docker-paperless-ngx`

### Steps to reproduce

1. Fetch e-mails -> see the error in the logs
2. Try to delete or modify e-mail account or rules -> see the error in the logs and as well in the browser

### Paperless-ngx version

1.7.0

### Host OS

Debian buster

### Installation method

Docker

### Browser

any

**Comment by stumpylog** [comment]
You're somehow missing migrations.

Could you provide two peices of info:

1. In your paperless data directory, is there a file called `migration_lock`?
2. Can you restart your container and provide the logs up until the point where it says "Executing /usr/local/bin/supervisord -c /etc/supervisord.conf"?

**Comment by darkmattercoder** [comment]
1. I have no file `m̀igration_lock` in the data dir. 
2. As I stated above, I am using the docker image provided through the linuxserver.io ecosystem. Their images do not use `supervisord` I assume. 

Do you think it is related to the execution docker environment rather than to paperless-ngx itself? Then I probably should file an issue over there instead. 

Nevertheless, here is the complete docker log up until the application is ready:

```
docker-compose up  
Creating network "paperless-ng_default" with the default driver
Creating paperless-ngx ... done
Attaching to paperless-ngx
paperless-ngx    | [mod-init] Curl/JQ was not found on this system for Docker mods installing
paperless-ngx    | Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
paperless-ngx    | Get:2 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
paperless-ngx    | Get:3 http://archive.ubuntu.com/ubuntu focal-security InRelease [114 kB]
paperless-ngx    | Get:4 http://archive.ubuntu.com/ubuntu focal-updates/restricted Sources [41.8 kB]
paperless-ngx    | Get:5 http://archive.ubuntu.com/ubuntu focal-updates/universe Sources [298 kB]
paperless-ngx    | Get:6 http://archive.ubuntu.com/ubuntu focal-updates/main Sources [595 kB]
paperless-ngx    | Get:7 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [2,239 kB]
paperless-ngx    | Get:8 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [1,249 kB]
paperless-ngx    | Get:9 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [1,156 kB]
paperless-ngx    | Get:10 http://archive.ubuntu.com/ubuntu focal-security/main Sources [278 kB]
paperless-ngx    | Get:11 http://archive.ubuntu.com/ubuntu focal-security/restricted Sources [41.8 kB]
paperless-ngx    | Get:12 http://archive.ubuntu.com/ubuntu focal-security/restricted amd64 Packages [1,170 kB]
paperless-ngx    | Get:13 http://archive.ubuntu.com/ubuntu focal-security/main amd64 Packages [1,812 kB]
paperless-ngx    | Get:14 http://archive.ubuntu.com/ubuntu focal-security/universe amd64 Packages [873 kB]
paperless-ngx    | Fetched 9,982 kB in 2s (6,298 kB/s)
paperless-ngx    | Reading package lists...
paperless-ngx    | Reading package lists...
paperless-ngx    | Building dependency tree...
paperless-ngx    | Reading state information...
paperless-ngx    | The following additional packages will be installed:
paperless-ngx    |   libcurl4 libjq1 libonig5
paperless-ngx    | The following NEW packages will be installed:
paperless-ngx    |   jq libjq1 libonig5
paperless-ngx    | The following packages will be upgraded:
paperless-ngx    |   curl libcurl4
paperless-ngx    | 2 upgraded, 3 newly installed, 0 to remove and 14 not upgraded.
paperless-ngx    | Need to get 710 kB of archives.
paperless-ngx    | After this operation, 1,062 kB of additional disk space will be used.
paperless-ngx    | Get:1 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 curl amd64 7.68.0-1ubuntu2.11 [162 kB]
paperless-ngx    | Get:2 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libcurl4 amd64 7.68.0-1ubuntu2.11 [235 kB]
paperless-ngx    | Get:3 http://archive.ubuntu.com/ubuntu focal/universe amd64 libonig5 amd64 6.9.4-1 [142 kB]
paperless-ngx    | Get:4 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 libjq1 amd64 1.6-1ubuntu0.20.04.1 [121 kB]
paperless-ngx    | Get:5 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 jq amd64 1.6-1ubuntu0.20.04.1 [50.2 kB]
paperless-ngx    | debconf: unable to initialize frontend: Dialog
paperless-ngx    | debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 5.)
paperless-ngx    | debconf: falling back to frontend: Readline
paperless-ngx    | debconf: unable to initialize frontend: Readline
paperless-ngx    | debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7, <> line 5.)
paperless-ngx    | debconf: falling back to frontend: Teletype
paperless-ngx    | dpkg-preconfigure: unable to re-open stdin: 
paperless-ngx    | Fetched 710 kB in 0s (2,681 kB/s)
(Reading database ... 12219 files and directories currently installed.)
paperless-ngx    | Preparing to unpack .../curl_7.68.0-1ubuntu2.11_amd64.deb ...
paperless-ngx    | Unpacking curl (7.68.0-1ubuntu2.11) over (7.68.0-1ubuntu2.10) ...
paperless-ngx    | Preparing to unpack .../libcurl4_7.68.0-1ubuntu2.11_amd64.deb ...
paperless-ngx    | Unpacking libcurl4:amd64 (7.68.0-1ubuntu2.11) over (7.68.0-1ubuntu2.10) ...
paperless-ngx    | Selecting previously unselected package libonig5:amd64.
paperless-ngx    | Preparing to unpack .../libonig5_6.9.4-1_amd64.deb ...
paperless-ngx    | Unpacking libonig5:amd64 (6.9.4-1) ...
paperless-ngx    | Selecting previously unselected package libjq1:amd64.
paperless-ngx    | Preparing to unpack .../libjq1_1.6-1ubuntu0.20.04.1_amd64.deb ...
paperless-ngx    | Unpacking libjq1:amd64 (1.6-1ubuntu0.20.04.1) ...
paperless-ngx    | Selecting previously unselected package jq.
paperless-ngx    | Preparing to unpack .../jq_1.6-1ubuntu0.20.04.1_amd64.deb ...
paperless-ngx    | Unpacking jq (1.6-1ubuntu0.20.04.1) ...
paperless-ngx    | Setting up libcurl4:amd64 (7.68.0-1ubuntu2.11) ...
paperless-ngx    | Setting up curl (7.68.0-1ubuntu2.11) ...
paperless-ngx    | Setting up libonig5:amd64 (6.9.4-1) ...
paperless-ngx    | Setting up libjq1:amd64 (1.6-1ubuntu0.20.04.1) ...
paperless-ngx    | Setting up jq (1.6-1ubuntu0.20.04.1) ...
paperless-ngx    | Processing triggers for libc-bin (2.31-0ubuntu9.7) ...
paperless-ngx    | /sbin/ldconfig.real: /usr/local/lib/libjbig2enc.so.0 is not a symbolic link
paperless-ngx    | 
paperless-ngx    | [mod-init] Attempting to run Docker Modification Logic
paperless-ngx    | [mod-init] Applying linuxserver/mods:papermerge-multilangocr files to container
paperless-ngx    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
paperless-ngx    | [s6-init] ensuring user provided files have correct perms...exited 0.
paperless-ngx    | [fix-attrs.d] applying ownership & permissions fixes...
paperless-ngx    | [fix-attrs.d] done.
paperless-ngx    | [cont-init.d] executing container initialization scripts...
paperless-ngx    | [cont-init.d] 01-envfile: executing... 
paperless-ngx    | [cont-init.d] 01-envfile: exited 0.
paperless-ngx    | [cont-init.d] 01-migrations: executing... 
paperless-ngx    | [migrations] started
paperless-ngx    | [migrations] no migrations found
paperless-ngx    | [cont-init.d] 01-migrations: exited 0.
paperless-ngx    | [cont-init.d] 02-tamper-check: executing... 
paperless-ngx    | [cont-init.d] 02-tamper-check: exited 0.
paperless-ngx    | [cont-init.d] 10-adduser: executing... 
paperless-ngx    | 
paperless-ngx    | -------------------------------------
paperless-ngx    |           _         ()
paperless-ngx    |          | |  ___   _    __
paperless-ngx    |          | | / __| | |  /  \
paperless-ngx    |          | | \__ \ | | | () |
paperless-ngx    |          |_| |___/ |_|  \__/
paperless-ngx    | 
paperless-ngx    | 
paperless-ngx    | Brought to you by linuxserver.io
paperless-ngx    | -------------------------------------
paperless-ngx    | 
paperless-ngx    | To support LSIO projects visit:
paperless-ngx    | https://www.linuxserver.io/donate/
paperless-ngx    | -------------------------------------
paperless-ngx    | GID/UID
paperless-ngx    | -------------------------------------
paperless-ngx    | 
paperless-ngx    | User uid:    995
paperless-ngx    | User gid:    995
paperless-ngx    | -------------------------------------
paperless-ngx    | 
paperless-ngx    | [cont-init.d] 10-adduser: exited 0.
paperless-ngx    | [cont-init.d] 50-config: executing... 
paperless-ngx    | SystemCheckError: System check identified some issues:
paperless-ngx    | 
paperless-ngx    | ERRORS:
paperless-ngx    | ?: The selected ocr language deu is not installed. Paperless cannot OCR your documents without it. Please fix PAPERLESS_OCR_LANGUAGE.
paperless-ngx    | SystemCheckError: System check identified some issues:
paperless-ngx    | 
paperless-ngx    | ERRORS:
paperless-ngx    | ?: The selected ocr language deu is not installed. Paperless cannot OCR your documents without it. Please fix PAPERLESS_OCR_LANGUAGE.
paperless-ngx    | [cont-init.d] 50-config: exited 0.
paperless-ngx    | [cont-init.d] 70-aliases: executing... 
paperless-ngx    | [cont-init.d] 70-aliases: exited 0.
paperless-ngx    | [cont-init.d] 90-custom-folders: executing... 
paperless-ngx    | [cont-init.d] 90-custom-folders: exited 0.
paperless-ngx    | [cont-init.d] 95-apt-get: executing... 
paperless-ngx    | Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
paperless-ngx    | Hit:2 http://archive.ubuntu.com/ubuntu focal-updates InRelease
paperless-ngx    | Hit:3 http://archive.ubuntu.com/ubuntu focal-security InRelease
paperless-ngx    | Reading package lists...
paperless-ngx    | [cont-init.d] 95-apt-get: exited 0.
paperless-ngx    | [cont-init.d] 98-multilangocr: executing... 
paperless-ngx    | OCRLANG variable is set, processing the language packages
paperless-ngx    | installing tesseract-ocr-deu
paperless-ngx    | Reading package lists...
paperless-ngx    | Building dependency tree...
paperless-ngx    | Reading state information...
paperless-ngx    | The following NEW packages will be installed:
paperless-ngx    |   tesseract-ocr-deu
paperless-ngx    | 0 upgraded, 1 newly installed, 0 to remove and 14 not upgraded.
paperless-ngx    | Need to get 745 kB of archives.
paperless-ngx    | After this operation, 1,540 kB of additional disk space will be used.
paperless-ngx    | Get:1 http://archive.ubuntu.com/ubuntu focal/universe amd64 tesseract-ocr-deu all 1:4.00~git30-7274cfa-1 [745 kB]
paperless-ngx    | debconf: unable to initialize frontend: Dialog
paperless-ngx    | debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 1.)
paperless-ngx    | debconf: falling back to frontend: Readline
paperless-ngx    | debconf: unable to initialize frontend: Readline
paperless-ngx    | debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7, <> line 1.)
paperless-ngx    | debconf: falling back to frontend: Teletype
paperless-ngx    | dpkg-preconfigure: unable to re-open stdin: 
paperless-ngx    | Fetched 745 kB in 0s (3,321 kB/s)
paperless-ngx    | Selecting previously unselected package tesseract-ocr-deu.
(Reading database ... 12236 files and directories currently installed.)
paperless-ngx    | Preparing to unpack .../tesseract-ocr-deu_1%3a4.00~git30-7274cfa-1_all.deb ...
paperless-ngx    | Unpacking tesseract-ocr-deu (1:4.00~git30-7274cfa-1) ...
paperless-ngx    | Setting up tesseract-ocr-deu (1:4.00~git30-7274cfa-1) ...
paperless-ngx    | [cont-init.d] 98-multilangocr: exited 0.
paperless-ngx    | [cont-init.d] 99-custom-scripts: executing... 
paperless-ngx    | [custom-init] no custom files found exiting...
paperless-ngx    | [cont-init.d] 99-custom-scripts: exited 0.
paperless-ngx    | [cont-init.d] done.
paperless-ngx    | [services.d] starting services
paperless-ngx    | Waiting for redis to become available...
paperless-ngx    | Waiting for redis to become available...
paperless-ngx    | Waiting for redis to become available...
paperless-ngx    | [services.d] done.
paperless-ngx    | 898:C 12 May 2022 21:34:21.722 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
paperless-ngx    | 898:C 12 May 2022 21:34:21.722 # Redis version=5.0.7, bits=64, commit=00000000, modified=0, pid=898, just started
paperless-ngx    | 898:C 12 May 2022 21:34:21.722 # Configuration loaded
paperless-ngx    | 898:M 12 May 2022 21:34:21.724 * Running mode=standalone, port=6379.
paperless-ngx    | 898:M 12 May 2022 21:34:21.724 # Server initialized
paperless-ngx    | 898:M 12 May 2022 21:34:21.724 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
paperless-ngx    | 898:M 12 May 2022 21:34:21.724 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
paperless-ngx    | 898:M 12 May 2022 21:34:21.724 * Ready to accept connections
paperless-ngx    | [2022-05-12 21:34:32 +0200] [896] [INFO] Starting gunicorn 20.1.0
paperless-ngx    | [2022-05-12 21:34:32 +0200] [896] [INFO] Listening at: http://0.0.0.0:8000 (896)
paperless-ngx    | [2022-05-12 21:34:32 +0200] [896] [INFO] Using worker: paperless.workers.ConfigurableWorker
paperless-ngx    | [2022-05-12 21:34:32 +0200] [896] [INFO] Server is ready. Spawning workers
```

**Comment by stumpylog** [comment]
Ah, I missed that, but the log was helpful.  In their system, when `[cont-init.d] 50-config` is executing, it should run migrations.  I'm guessing due to the missing OCR language page SystemCheckError, the migrations don't happen.  I'm unsure why it doesn't error out instead of continuing.

Installing the missing language, however lsio reccomends doing that, will likely resolve it.

**Comment by darkmattercoder** [comment]
Hm, thanks I will bring that up with their issue tracker. The language pack is installed afterwards. However, at least with the older versions pre ngx, the issue was not present. So far thanks for the assistance.
