### ISSUE TITLE
Not able to consume documents

### ISSUE THREAD

**Issue by dmerkert** [paperless-ngx/paperless-ngx#961]
### Description

When consuming a document (either via import directory or drag&drop), paperless stops at "Datei hochgeladen, warte..." (in english something like 'uploaded document, waiting .....') indefinitely.
![image](https://user-images.githubusercontent.com/62744/168601043-20c1a4fd-abe2-4c4b-ac2a-3745079ccf01.png)

The log of the docker container is full of errors (see below). This morning, everything was working. After updating the docker container to the latest version, I was no longer able to consume documents.

Docker-compose that I use:
[paperless.txt](https://github.com/paperless-ngx/paperless-ngx/files/8700388/paperless.txt)

### Steps to reproduce

1. Drag&Drop or upload file

### Webserver logs

```bash
2022-05-16T13:12:48.693699000Z [2022-05-16 15:12:48,669] [INFO] [paperless.consumer] Consuming Scan 20220429-140147.pdf
2022-05-16T13:12:49.288208000Z [2022-05-16 15:12:49,239] [INFO] [paperless.consumer] Consuming 0000280.pdf
2022-05-16T13:12:53.032722000Z [2022-05-16 15:12:52,994] [ERROR] [paperless.consumer] Error while consuming document Scan 20220429-140147.pdf: ValueError: max_workers must be greater than 0
2022-05-16T13:12:53.033930000Z Traceback (most recent call last):
2022-05-16T13:12:53.034279000Z   File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 261, in parse
2022-05-16T13:12:53.034566000Z     ocrmypdf.ocr(**args)
2022-05-16T13:12:53.034869000Z   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/api.py", line 337, in ocr
2022-05-16T13:12:53.035336000Z     return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)
2022-05-16T13:12:53.035697000Z   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 385, in run_pipeline
2022-05-16T13:12:53.036013000Z     exec_concurrent(context, executor)
2022-05-16T13:12:53.036343000Z   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 274, in exec_concurrent
2022-05-16T13:12:53.036637000Z     executor(
2022-05-16T13:12:53.036960000Z   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_concurrent.py", line 82, in __call__
2022-05-16T13:12:53.037292000Z     self._execute(
2022-05-16T13:12:53.037591000Z   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/builtin_plugins/concurrency.py", line 127, in _execute
2022-05-16T13:12:53.037886000Z     with self.pbar_class(**tqdm_kwargs) as pbar, executor_class(
2022-05-16T13:12:53.038208000Z   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 144, in __init__
2022-05-16T13:12:53.038528000Z     raise ValueError("max_workers must be greater than 0")
2022-05-16T13:12:53.038885000Z ValueError: max_workers must be greater than 0
2022-05-16T13:12:53.039758000Z During handling of the above exception, another exception occurred:
2022-05-16T13:12:53.040419000Z Traceback (most recent call last):
2022-05-16T13:12:53.040745000Z   File "/usr/src/paperless/src/documents/consumer.py", line 261, in try_consume_file
2022-05-16T13:12:53.041120000Z     document_parser.parse(self.path, mime_type, self.filename)
2022-05-16T13:12:53.041455000Z   File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 314, in parse
2022-05-16T13:12:53.041780000Z     raise ParseError(f"{e.__class__.__name__}: {str(e)}")
2022-05-16T13:12:53.042107000Z documents.parsers.ParseError: ValueError: max_workers must be greater than 0
2022-05-16T13:12:53.056210000Z 15:12:53 [Q] INFO Process-1:7 stopped doing work
2022-05-16T13:12:53.173535000Z 15:12:53 [Q] ERROR Failed [Scan 20220429-140147.pdf] - Scan 20220429-140147.pdf: Error while consuming document Scan 20220429-140147.pdf: ValueError: max_workers must be greater than 0 : Traceback (most recent call last):
2022-05-16T13:12:53.173987000Z   File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 261, in parse
2022-05-16T13:12:53.174318000Z     ocrmypdf.ocr(**args)
2022-05-16T13:12:53.175312000Z   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/api.py", line 337, in ocr
2022-05-16T13:12:53.175659000Z     return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)
2022-05-16T13:12:53.175969000Z   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 385, in run_pipeline
2022-05-16T13:12:53.176269000Z     exec_concurrent(context, executor)
2022-05-16T13:12:53.176557000Z   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 274, in exec_concurrent
2022-05-16T13:12:53.176822000Z     executor(
2022-05-16T13:12:53.177119000Z   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_concurrent.py", line 82, in __call__
2022-05-16T13:12:53.177390000Z     self._execute(
2022-05-16T13:12:53.178114000Z   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/builtin_plugins/concurrency.py", line 127, in _execute
2022-05-16T13:12:53.178540000Z     with self.pbar_class(**tqdm_kwargs) as pbar, executor_class(
2022-05-16T13:12:53.178851000Z   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 144, in __init__
2022-05-16T13:12:53.179492000Z     raise ValueError("max_workers must be greater than 0")
2022-05-16T13:12:53.179861000Z ValueError: max_workers must be greater than 0
2022-05-16T13:12:53.180571000Z During handling of the above exception, another exception occurred:
2022-05-16T13:12:53.181675000Z Traceback (most recent call last):
2022-05-16T13:12:53.182005000Z   File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 275, in main_wrap
2022-05-16T13:12:53.182345000Z     raise exc_info[1]
2022-05-16T13:12:53.182686000Z   File "/usr/src/paperless/src/documents/consumer.py", line 261, in try_consume_file
2022-05-16T13:12:53.183059000Z     document_parser.parse(self.path, mime_type, self.filename)
2022-05-16T13:12:53.183847000Z   File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 314, in parse
2022-05-16T13:12:53.184376000Z     raise ParseError(f"{e.__class__.__name__}: {str(e)}")
2022-05-16T13:12:53.184917000Z documents.parsers.ParseError: ValueError: max_workers must be greater than 0
2022-05-16T13:12:53.186077000Z During handling of the above exception, another exception occurred:
2022-05-16T13:12:53.187208000Z Traceback (most recent call last):
2022-05-16T13:12:53.187880000Z   File "/usr/local/lib/python3.9/site-packages/django_q/cluster.py", line 432, in worker
2022-05-16T13:12:53.188693000Z     res = f(*task["args"], **task["kwargs"])
2022-05-16T13:12:53.189269000Z   File "/usr/src/paperless/src/documents/tasks.py", line 298, in consume_file
2022-05-16T13:12:53.189772000Z     document = Consumer().try_consume_file(
2022-05-16T13:12:53.190359000Z   File "/usr/src/paperless/src/documents/consumer.py", line 280, in try_consume_file
2022-05-16T13:12:53.190989000Z     self._fail(
2022-05-16T13:12:53.191650000Z   File "/usr/src/paperless/src/documents/consumer.py", line 81, in _fail
2022-05-16T13:12:53.192140000Z     raise ConsumerError(f"{self.filename}: {log_message or message}")
2022-05-16T13:12:53.192759000Z documents.consumer.ConsumerError: Scan 20220429-140147.pdf: Error while consuming document Scan 20220429-140147.pdf: ValueError: max_workers must be greater than 0
2022-05-16T13:14:55.662809000Z [2022-05-16 15:14:55,660] [WARNING] [ocrmypdf._exec.tesseract] [tesseract] lots of diacritics - possibly poor OCR
2022-05-16T13:15:22.808201000Z 15:15:22 [Q] INFO Enqueued 1
```

### Paperless-ngx version

1.7.1 (ghcr.io/paperless-ngx/paperless-ngx:latest)

### Host OS

Armbian (aarch64)

### Installation method

Docker

### Browser

Chrome

**Comment by stumpylog** [comment]
Could you provide any configuration changes you have made?

**Comment by stumpylog** [comment]
Does this happen only with a particular document or all documents you try with?

**Comment by HeyVern** [comment]
This appears to be happening to me too.

**Comment by stumpylog** [comment]
Well, we haven't had any releases in the past 2 days.  And a docker image can't update the versions inside it either.

What happens if you try to run ocrmypdf manually?  From inside the container, something like `ocrmypdf input.pdf output.pdf`.  Either way, having a sample PDF would help either us or the upstream figure out the issue.

**Comment by HeyVern** [comment]
Restarted container a few times and kept trying...eventually go this:

>[2022-05-18 15:59:29,965] [ERROR] [paperless.consumer] The following error occured while consuming 20220518_For Service To.pdf: UNIQUE constraint failed: documents_document.checksum
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 477, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: documents_document.checksum

**Comment by stumpylog** [comment]
That's a different error than the above.  I suspect possibly due to restarting the container while a document was being consumed.  

If you're getting the same or very similar to the above, that would be helpful to know, but a very different error doesn't assist with finding a fix.

**Comment by Psychi1** [comment]
Hi,

> This appears to be happening to me too. It just stopped consuming documents...and manual uploads just keep saying "Upload complete...waiting..."

The message about "Upload complete...waiting..." for manual uploads appears since version 1.7.0 - for me. I don't use import dictionary, so no information available from me. 

Bye

**Comment by stumpylog** [comment]
A message of "Upload complete ... waiting" is quite normal as the processing happens in the background.  Logs from the webserver would help show if there is an issue or not.  I don't know idea what this "import dictionary".

In any case, without a file to reproduce with, or confirmation it happens with every file, there isn't much to do.  For the initial issue reported, that's value is set internally to ocrmypdf, and so is likely an issue with it.

**Comment by bradgy** [comment]
I wonder if I am able to provide any information on what I think might be a similar bug.

Using the docker image.

Out of 794 documents so far, this is the one! that doesn't seem to be consumed.
[micro prac-10062014230404.pdf](https://github.com/paperless-ngx/paperless-ngx/files/8748731/micro.prac-10062014230404.pdf)

ocrmypdf file.pdf output.pdf run in the container completed in about 10 minutes with no errors.

Trying to consume this file through either the web interface or the consume folder, there's lots of errors and it just kinds of hangs/stops.

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing... 
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 02-tamper-check: executing... 
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 50-config: executing... 
[cont-init.d] 50-config: exited 0.
[cont-init.d] 70-aliases: executing... 
[cont-init.d] 70-aliases: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] 99-migrations: executing... 
No changes detected
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, django_q, documents, paperless_mail, sessions
Running migrations:
  No migrations to apply.
[cont-init.d] 99-migrations: exited 0.
[cont-init.d] done.
[services.d] starting services
Waiting for redis to become available...
Waiting for redis to become available...
Waiting for redis to become available...
[services.d] done.
411:C 22 May 2022 13:38:10.737 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
411:C 22 May 2022 13:38:10.745 # Redis version=5.0.7, bits=64, commit=00000000, modified=0, pid=411, just started
411:C 22 May 2022 13:38:10.751 # Configuration loaded
411:M 22 May 2022 13:38:10.780 * Running mode=standalone, port=6379.
411:M 22 May 2022 13:38:10.784 # Server initialized
411:M 22 May 2022 13:38:10.784 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
411:M 22 May 2022 13:38:10.784 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
411:M 22 May 2022 13:38:10.788 * Ready to accept connections
[2022-05-22 03:38:30 +0000] [416] [INFO] Starting gunicorn 20.1.0
[2022-05-22 03:38:30 +0000] [416] [INFO] Listening at: http://0.0.0.0:8000 (416)
[2022-05-22 03:38:30 +0000] [416] [INFO] Using worker: paperless.workers.ConfigurableWorker
[2022-05-22 03:38:30 +0000] [416] [INFO] Server is ready. Spawning workers
[2022-05-22 03:38:42,732] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: /data/consume
03:38:47 [Q] INFO Q Cluster finch-seventeen-nebraska-yankee starting.
03:38:47 [Q] INFO Process-1:2 ready for work at 470
03:38:47 [Q] INFO Process-1:1 ready for work at 469
03:38:47 [Q] INFO Process-1 guarding cluster finch-seventeen-nebraska-yankee
03:38:47 [Q] INFO Process-1:4 pushing tasks at 472
03:38:47 [Q] INFO Process-1:3 monitoring at 471
03:38:47 [Q] INFO Q Cluster finch-seventeen-nebraska-yankee running.
03:39:17 [Q] INFO Enqueued 1
03:39:17 [Q] INFO Process-1 created a task from schedule [Check all e-mail accounts]
03:39:17 [Q] INFO Process-1:2 processing [hotel-berlin-fourteen-whiskey]
03:39:20 [Q] INFO Process-1:2 stopped doing work
03:39:20 [Q] INFO recycled worker Process-1:2
03:39:20 [Q] INFO Process-1:5 ready for work at 499
03:39:20 [Q] INFO Processed [hotel-berlin-fourteen-whiskey]
[2022-05-22 03:39:24,371] [INFO] [paperless.management.consumer] Adding /data/consume/micro prac-10062014230404.pdf to the task queue.
03:39:24 [Q] INFO Enqueued 1
03:39:24 [Q] INFO Process-1:1 processing [micro prac-10062014230404.pdf]
[2022-05-22 03:39:26,098] [INFO] [paperless.consumer] Consuming micro prac-10062014230404.pdf
[2022-05-22 03:40:13,181] [WARNING] [ocrmypdf._exec.tesseract] [tesseract] lots of diacritics - possibly poor OCR
[2022-05-22 03:40:15,389] [ERROR] [ocrmypdf._exec.tesseract] [tesseract] Error during processing.
03:45:19 [Q] INFO Enqueued 1
03:45:19 [Q] INFO Process-1 created a task from schedule [Check all e-mail accounts]
03:45:19 [Q] INFO Process-1:5 processing [burger-video-purple-maine]
03:45:22 [Q] INFO Process-1:5 stopped doing work
03:45:22 [Q] INFO Processed [burger-video-purple-maine]
03:45:22 [Q] INFO recycled worker Process-1:5
03:45:22 [Q] INFO Process-1:6 ready for work at 741
[2022-05-22 03:45:53,364] [ERROR] [ocrmypdf._exec.tesseract] [tesseract] Error during processing.
[2022-05-22 03:45:56,001] [ERROR] [ocrmypdf._exec.tesseract] [tesseract] Error during processing.
[2022-05-22 03:46:05,708] [ERROR] [ocrmypdf._exec.tesseract] [tesseract] Error during processing.
[2022-05-22 03:46:29,650] [WARNING] [ocrmypdf._exec.tesseract] [tesseract] lots of diacritics - possibly poor OCR
[2022-05-22 03:46:30,352] [ERROR] [ocrmypdf._exec.tesseract] [tesseract] Error during processing.
[2022-05-22 03:46:41,254] [ERROR] [ocrmypdf._exec.tesseract] [tesseract] Error during processing.
[2022-05-22 03:47:31,305] [ERROR] [ocrmypdf._exec.tesseract] [tesseract] Error during processing.
[2022-05-22 03:48:39,181] [ERROR] [ocrmypdf._exec.tesseract] [tesseract] Error during processing.
[2022-05-22 03:49:21,494] [ERROR] [ocrmypdf._exec.tesseract] [tesseract] Error during processing.
[2022-05-22 03:51:36,049] [WARNING] [ocrmypdf._exec.tesseract] [tesseract] lots of diacritics - possibly poor OCR
[2022-05-22 03:51:56,302] [ERROR] [ocrmypdf._exec.tesseract] [tesseract] Error during processing.
[2022-05-22 03:52:23,094] [WARNING] [ocrmypdf._exec.tesseract] [tesseract] lots of diacritics - possibly poor OCR
[2022-05-22 03:52:44,483] [ERROR] [ocrmypdf._exec.tesseract] [tesseract] Error during processing.
[2022-05-22 03:52:47,160] [ERROR] [ocrmypdf._exec.tesseract] [tesseract] Error during processing.
[2022-05-22 03:52:55,877] [ERROR] [ocrmypdf._exec.tesseract] [tesseract] Error during processing.
[2022-05-22 03:53:38,296] [ERROR] [ocrmypdf._exec.tesseract] [tesseract] Error during processing.
[2022-05-22 03:53:46,690] [ERROR] [ocrmypdf._exec.tesseract] [tesseract] Error during processing.
[2022-05-22 03:54:33,990] [ERROR] [ocrmypdf._exec.tesseract] [tesseract] Error during processing.
03:55:21 [Q] INFO Process-1:6 processing [pip-foxtrot-uranus-georgia]
03:55:21 [Q] INFO Enqueued 1
03:55:21 [Q] INFO Process-1 created a task from schedule [Check all e-mail accounts]
[2022-05-22 03:55:23,144] [WARNING] [ocrmypdf._exec.tesseract] [tesseract] lots of diacritics - possibly poor OCR
03:55:24 [Q] INFO Process-1:6 stopped doing work
03:55:24 [Q] INFO Processed [pip-foxtrot-uranus-georgia]
03:55:24 [Q] INFO recycled worker Process-1:6
03:55:24 [Q] INFO Process-1:7 ready for work at 1366
[2022-05-22 03:55:28,659] [WARNING] [ocrmypdf._exec.tesseract] [tesseract] lots of diacritics - possibly poor OCR
[2022-05-22 03:56:33,329] [WARNING] [ocrmypdf._exec.tesseract] [tesseract] lots of diacritics - possibly poor OCR
[2022-05-22 03:56:40,782] [WARNING] [ocrmypdf._exec.tesseract] [tesseract] lots of diacritics - possibly poor OCR
[2022-05-22 04:00:08,647] [WARNING] [ocrmypdf._exec.tesseract] [tesseract] lots of diacritics - possibly poor OCR
[2022-05-22 04:01:46,799] [ERROR] [ocrmypdf._exec.tesseract] [tesseract] Error during processing.
[2022-05-22 04:02:00,137] [WARNING] [ocrmypdf._exec.tesseract] [tesseract] lots of diacritics - possibly poor OCR
[2022-05-22 04:03:34,551] [WARNING] [ocrmypdf._exec.tesseract] [tesseract] lots of diacritics - possibly poor OCR
[2022-05-22 04:03:41,646] [WARNING] [ocrmypdf._exec.tesseract] [tesseract] lots of diacritics - possibly poor OCR
[2022-05-22 04:03:48,523] [WARNING] [ocrmypdf._exec.tesseract] [tesseract] lots of diacritics - possibly poor OCR
[2022-05-22 04:04:04,668] [ERROR] [ocrmypdf._exec.tesseract] [tesseract] Error during processing.
[2022-05-22 04:04:07,350] [ERROR] [ocrmypdf._exec.tesseract] [tesseract] Error during processing.
[2022-05-22 04:04:09,899] [ERROR] [ocrmypdf._exec.tesseract] [tesseract] Error during processing.
[2022-05-22 04:04:12,473] [ERROR] [ocrmypdf._exec.tesseract] [tesseract] Error during processing.
[2022-05-22 04:04:15,035] [ERROR] [ocrmypdf._exec.tesseract] [tesseract] Error during processing.
[2022-05-22 04:04:17,639] [ERROR] [ocrmypdf._exec.tesseract] [tesseract] Error during processing.
[2022-05-22 04:04:23,285] [ERROR] [ocrmypdf._exec.tesseract] [tesseract] Error during processing.
[2022-05-22 04:04:59,346] [WARNING] [ocrmypdf._exec.tesseract] [tesseract] lots of diacritics - possibly poor OCR
[2022-05-22 04:05:03,617] [ERROR] [ocrmypdf._exec.tesseract] [tesseract] Error during processing.
04:05:23 [Q] INFO Process-1:7 processing [failed-arkansas-music-three]
04:05:23 [Q] INFO Enqueued 1
04:05:23 [Q] INFO Process-1 created a task from schedule [Check all e-mail accounts]
04:05:26 [Q] INFO Process-1:7 stopped doing work
04:05:26 [Q] INFO Processed [failed-arkansas-music-three]
04:05:26 [Q] INFO recycled worker Process-1:7
04:05:26 [Q] INFO Process-1:8 ready for work at 1995
04:09:31 [Q] WARNING reincarnated worker Process-1:1 after timeout
04:09:31 [Q] INFO Process-1:9 ready for work at 2141
`


Info from the logs in the tab on the webpage:
[2022-05-22 03:38:42,732] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: /data/consume

[2022-05-22 03:39:24,371] [INFO] [paperless.management.consumer] Adding /data/consume/micro prac-10062014230404.pdf to the task queue.

[2022-05-22 03:39:26,098] [INFO] [paperless.consumer] Consuming micro prac-10062014230404.pdf

[2022-05-22 03:39:26,128] [DEBUG] [paperless.consumer] Detected mime type: application/pdf

[2022-05-22 03:39:26,136] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser

[2022-05-22 03:39:26,179] [DEBUG] [paperless.consumer] Parsing micro prac-10062014230404.pdf...

[2022-05-22 03:39:28,703] [DEBUG] [paperless.parsing.tesseract] Extracted text from PDF file /data/consume/micro prac-10062014230404.pdf

[2022-05-22 03:39:29,188] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': '/data/consume/micro prac-10062014230404.pdf', 'output_file': '/tmp/paperless/paperless-161m1mph/archive.pdf', 'use_threads': True, 'jobs': 1, 'language': 'eng', 'output_type': 'pdfa', 'progress_bar': False, 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': '/tmp/paperless/paperless-161m1mph/sidecar.txt'}

**Comment by bradgy** [comment]
That's probably the issue - my server is a NUC like box with a pretty low powered CPU. Thanks for taking a look.

**Comment by tooomm** [comment]
Are there any recommendations on max file size and max page count etc. for certain CPU classes or RAM sizes to prevent issues?

**Comment by stumpylog** [comment]
I think it would be an impossible task to recommend details like that.  There's just so much variance in documents.  If it's already OCRed, that will be very fast.  If it has lots of pictures or scan artifacts or is heavily rotated.
