### ISSUE TITLE
[BUG] User matching query does not exist

### ISSUE THREAD

**Issue by giacomofabbri** [paperless-ngx/paperless-ngx#988]
### Description

Hi guys, since upgrading my docker image to 1.7.1 from 1.6.x whenever I upload any kind of PDF via browser/import folder I get this error:
User matching query does not exist

I tried with both simple PDF and also "complex" but always same error.

### Steps to reproduce

Just uploading a file and in the end I'll get that error

### Webserver logs

```bash
12:16:45 [Q] INFO Process-1:2 processing [Procedura QR Code.pdf]
[2022-05-19 12:16:46,277] [INFO] [paperless.consumer] Consuming Procedura QR Code.pdf
[2022-05-19 12:16:47,899] [WARNING] [ocrmypdf._pipeline] Some input metadata could not be copied because it is not permitted in PDF/A. You may wish to examine the output PDF's XMP metadata.
[2022-05-19 12:16:55,617] [ERROR] [paperless.consumer] The following error occured while consuming Procedura QR Code.pdf: User matching query does not exist.
Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/consumer.py", line 306, in try_consume_file
    document_consumption_finished.send(
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/usr/src/paperless/src/documents/signals/handlers.py", line 416, in set_log_entry
    user = User.objects.get(username="consumer")
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 496, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.User.DoesNotExist: User matching query does not exist.
12:16:55 [Q] INFO Process-1:2 stopped doing work
12:16:55 [Q] ERROR Failed [Procedura QR Code.pdf] - Procedura QR Code.pdf: The following error occured while consuming Procedura QR Code.pdf: User matching query does not exist. : Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 275, in main_wrap
    raise exc_info[1]
  File "/usr/src/paperless/src/documents/consumer.py", line 306, in try_consume_file
    document_consumption_finished.send(
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/usr/src/paperless/src/documents/signals/handlers.py", line 416, in set_log_entry
    user = User.objects.get(username="consumer")
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 496, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.User.DoesNotExist: User matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django_q/cluster.py", line 432, in worker
    res = f(*task["args"], **task["kwargs"])
  File "/usr/src/paperless/src/documents/tasks.py", line 298, in consume_file
    document = Consumer().try_consume_file(
  File "/usr/src/paperless/src/documents/consumer.py", line 363, in try_consume_file
    self._fail(
  File "/usr/src/paperless/src/documents/consumer.py", line 81, in _fail
    raise ConsumerError(f"{self.filename}: {log_message or message}")
documents.consumer.ConsumerError: Procedura QR Code.pdf: The following error occured while consuming Procedura QR Code.pdf: User matching query does not exist.
```

### Paperless-ngx version

1.7.1

### Host OS

Linux debian 4.19.0-20-amd64

### Installation method

Docker

### Browser

Chrome

**Comment by stumpylog** [comment]
Huh, that user is created by a migration which has been in the code since 2017.  So long before 1.6 or 1.7. Have you changed database types or generally done anything with the database?

**Comment by stumpylog** [comment]
And I assume if you restart the container, it doesn't help?

Could you attach the logs from a restart, up until the line "Executing /usr/local/bin/supervisord -c /etc/supervisord.conf"?

Or if you're able to view the database, just confirming in the `auth_user` table, there is no consumer?

**Comment by giacomofabbri** [comment]
Yes I already tried restarting the docker, the machine and also recreate it but no luck.

```
Paperless-ngx docker container starting...
Creating directory /tmp/paperless
Adjusting permissions of paperless files. This may take a while.
Waiting for Redis: redis://broker:6379
Connected to Redis broker: redis://broker:6379
Apply database migrations...
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, django_q, documents, paperless_mail, sessions
Running migrations:
  No migrations to apply.
Executing /usr/local/bin/supervisord -c /etc/supervisord.conf
```

**Comment by jamesbchz** [comment]
This happened to me as well. Activity pane on Admin page shows that I recently deleted consumer user, which I definitely did not do. 
Once I created consumer user again (with all the permissions for 'documents' related tasks), all is well. 
![chrome_0DqPGrOtJq](https://user-images.githubusercontent.com/53843374/212941994-94a51c36-6a65-4d92-9c5b-1e726941937d.png)
